### ISSUE TITLE
Network state aware subscription

### ISSUE THREAD

**Issue by wtrocki** [apollographql/apollo-android#1003]
## Motivation

I recently noticed that network state interacts heavily with the Apollo subscriptions. When connected using websockets after network is restored new updates will not be delivered. Developers who wish to implement proper offline behavior in the application almost always will need to wrap subscriptions into `NetworkStateReceiver` in order to refresh data automatically when device network connection will be restored. Apollo javascript client. 

## Suggested solution

Add `reconnect` method to `ApolloSubscriptionCall` to reinstate subscription after network state changes. 

Calling execute again is not possible because of code here:
https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/RealApolloSubscriptionCall.java#L47-L50

Currently API users need to terminate connection and create new subscription on every network change.

I'm happy to contribute and document this change if agreed that this could be useful.

**Comment by digitalbuddha** [comment]
Sound like a great contribution! @ivans you have any objection?

**Comment by wtrocki** [comment]
Actually after implementing this I found that all is being managed by [RealSubscriptionManager](https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/subscription/RealSubscriptionManager.java#L205)

**Comment by adrian1388** [comment]
Any change on this?

Currently, following docs and the sample project, I successfully get errors when, for example the server restarts, but when Apollo Android app runs out of connection I don't get any error and then the subscriptions do not work anymore. Actually, my Apollo Android app is a Spring Boot App.

I get errors from server in onError:
```
new DisposableSubscriber<Response<MySubscription.Data>>() {
...
  @Override public void onError(Throwable e) {
	  e.printStackTrace();
	  if (e instanceof ApolloSubscriptionTerminatedException) {
		  logger.info("**** Unsubscribing... ");
	  }
  }
...
}
```
but I do not know where or how to catch the local network errors. Please your help with this, maybe I am missing something.

**Comment by sav007** [comment]
After giving another thought, introducing new API `reconnect` doesn't really different from calling `ApolloSubscriptionCall#clone` and then `ApolloSubscriptionCall#execute`. 

I think we can close this.

**Comment by martinbonnin** [comment]
[Apollo Android 3](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-rc01) now exposes a `Flow<ApolloResponse<*>>` that will throw when the network goes unavailable so users can use [retry](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/retry.html) to reconnect. 

I'm closing this issue. Please open a new one if needed.
