### ISSUE TITLE
verifySystemApolloCodegenVersion not working on Windows ?

### ISSUE THREAD

**Issue by johanneskraem3r** [apollographql/apollo-android#1005]
Here: 
https://github.com/apollographql/apollo-android/blob/37d3f8c6538eda02971f5bde2a884c853c9f242c/apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloPlugin.groovy#L219

verifySystemApolloCodegenVersion doesn't work on Windows. Output:
---------------------
"Failed to verify system 'apollo-codegen' version: java.io.IOException: Cannot run program "apollo-codegen": CreateProcess error=2, The system cannot find the file specified
Installing apollo-codegen ..."
---------------------
But, "apollo-codegen" is present and running, "apollo-codegen --version" works in a terminal.

I think the problem is that executing "apollo-codegen" will not work, since on windows, it's a CMD file.
I assume that changing the line to :

Process checkGlobalApolloCodegen = "apollo-codegen.cmd --version".execute()

.... should work. 
Not sure how to properly make this cross-platform. One way could be to run the "unix style" check first and, if it fails, run the check for the .cmd file.

**Comment by birdyblood** [comment]
I test in a groovy console under **windows**
* `"apollo-codegen --version".execute()` fails 
* `"apollo-codegen.cmd --version".execute()` works fine

**Comment by tasomaniac** [comment]
The proper fix to this is to have a separate task that uses Gradle's `Exec` task to execute the version check.

**Comment by sav007** [comment]
Please try latest version with a new code generation engine https://github.com/apollographql/apollo-android/releases/tag/1.1.0

If you see the same issue pls reopen.
