### ISSUE TITLE
Failed to parse nested Github Connection type ?

### ISSUE THREAD

**Issue by Holidaybear** [apollographql/apollo-android#1009]
Hello, I found a confused situation, when I try Github GraphQL API and use the script below:
```
query TestQuery($first: Int, $query: String!, $type: SearchType!) {
  search(first: $first, query: $query, type: $type) {
    edges {
      node {
        ... on Repository {
          name
          owner {
            login
          }
        }
      }
    }
  }
}
```
Then it works fine. But, if now I also want to query `repositoryTopics`, and use below:
```
query TestQuery($first: Int, $query: String!, $type: SearchType!, $count: Int) {
  search(first: $first, query: $query, type: $type) {
    edges {
      node {
        ... on Repository {
          name
          owner {
            login
          }
          repositoryTopics(first: $count) {
            edges {
              node {
                ... on RepositoryTopic {
                  topic {
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

After that, I will get **Failed to parse http response**, but it is correct and works in [Github GraphQL Explorer](https://developer.github.com/v4/explorer/). Can Apollo support this kind of nested query script ? Thanks.

**Comment by Holidaybear** [comment]
Hi, is there any update ?  🤔

**Comment by sav007** [comment]
Sorry was busy with the other stuff, could you please attach the full stack of the error?

**Comment by sav007** [comment]
Did you follow github instructions to generate token and use it to make any requests?

**Comment by sav007** [comment]
Could you please provide what version of Apollo are you using.
Just tried on my sample your query works for me, the only assumption it could be some permission issues?

**Comment by Holidaybear** [comment]
I found it works fine now, strange.
Thanks, and sorry for wasting your time.  😮
