### ISSUE TITLE
dynamic query graphql apollo with java

### ISSUE THREAD

**Issue by FarshidRoohi** [apollographql/apollo-android#1014]
The routine of working with the graphql apollo is that add file query .graphql

i would create dynamic query with java and i do not create file for each query
in fact, i would to get dynamic querys with Java
[questions](https://stackoverflow.com/questions/51608768/dynamic-query-graphql-apollo-with-java)
is it possible?

**Comment by sav007** [comment]
By dynamic do you mean some sort of Java builder to construct the query? If yes than the answer no as the whole idea behind the Apollo is completely different,  for example dynamic query won't allow you to build queries with non null assurance.

**Comment by FarshidRoohi** [comment]
@sav007 
As I understand it, it does not make the following queries dynamically with Java right?

```
query EntryDetailQuery($repoFullName: String!) {
  entry(repoFullName: $repoFullName) {
    id
    repository {
      full_name
      description
      owner {
          login
      }
    }
    postedBy {
      login
    }
  }
}
```
next time just request full_name or other field...
```
query EntryDetailQuery($repoFullName: String!) {
  entry(repoFullName: $repoFullName) {
    id
    repository {
      full_name

    }
  }
}
```

**Comment by sav007** [comment]
Yes it static query, first you need to write GraphQL query probably give it a try in GraphiQL tool and then when it's ready you save it and Apollo will generate models for the query. You can later modify it and Apollo will re-generate models.

**Comment by digitalbuddha** [comment]
There is no current support planned for dynamic queries. You can explore creating a fork and implementing there.
