### ISSUE TITLE
Generated Apollo Class implements Query interface instead Subscription

### ISSUE THREAD

**Issue by Starcodex** [apollographql/apollo-android#1015]
I've been figthing with this issue, the generated class implements Query Instead Subscription, when I try to subscribe like Android project : 
`
ApolloSubscriptionCall<ClassRequestFinding.Data> subscriptionCall = application.apolloClient()
        .subscribe(new ClassRequestFinding());
`
I get a wrong types Error.

`
subscribe
(com.apollographql.apollo.api.Subscription<com.apollographql.apollo.api.Operation.Data,com.project.apollotest.ClassRequestFinding.Data,com.apollographql.apollo.api.Operation.Variables>)
in ApolloClient cannot be applied
to
(com.project.ClassRequestFinding)`

this is my .graphql file called :

`subscription ClassRequestFinding{
        classRequestFinding {
            id
        }
}`

Generated Class:
`
@Generated("Apollo GraphQL")
public final class ClassRequestFinding implements Query<ClassRequestFinding.Data, ClassRequestFinding.Data, Operation.Variables> {
  public static final String OPERATION_DEFINITION = "subscription ClassRequestFinding {\n"
      + "  classRequestFinding {\n"
      + "    __typename\n"
      + "    id\n"
      + "  }\n"
      + "}";
}
`

Schema Auto-Generated:

`
{
"kind": "OBJECT",
          "name": "Subscription",
          "description": "",
          "fields": [
            {
              "name": "classRequestFinding",
              "description": "",
              "args": [],
              "type": {
                "kind": "OBJECT",
                "name": "ClassRequest",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": null
            }
         ],
          "inputFields": null,
          "interfaces": [],
          "enumValues": null,
          "possibleTypes": null
}
`

my Gradle dependencies:

`
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'

  implementation "com.apollographql.apollo:apollo-android-support:1.0.0-alpha"  //Android Support
    implementation "com.apollographql.apollo:apollo-runtime:1.0.0-alpha" // Runtime
    implementation "com.apollographql.apollo:apollo-rx-support:1.0.0-alpha"  //// RX Support
    implementation "com.apollographql.apollo:apollo-rx2-support:1.0.0-alpha"  //// RX2 Support
    implementation "com.apollographql.apollo:apollo-http-cache:1.0.0-alpha"  //// Http Cache

    implementation "io.reactivex:rxjava:1.2.9"
    implementation "io.reactivex.rxjava2:rxjava:2.0.5"
    implementation "io.reactivex.rxjava2:rxandroid:2.0.1"
    implementation "javax.annotation:jsr250-api:1.0"

}

`

**Comment by sav007** [comment]
I think there is something wrong in your schema, look at the example how subscription is defined:
https://github.com/apollographql/apollo-android/blob/master/apollo-sample/src/main/graphql/com/apollographql/apollo/sample/schema.json#L82

Or could you provide the whole schema that you have.

**Comment by Starcodex** [comment]
The Schema.json is apollo-codegen generated.
It contains too that definition as mentioned.
`
"subscriptionType": {
        "name": "Subscription"
      }
`

I've tested with aws appsync plugin and the generated class implements Subscription, But I can not run it with apollo libraries, I got "dex merge" issues.

**Comment by sav007** [comment]
what version of plugin are you using? 

And `aws appsync plugin` is unofficial fork we don't support it

**Comment by Starcodex** [comment]
I see.
I'm using this:
`classpath 'com.apollographql.apollo:gradle-plugin:0.4.1'`

**Comment by Starcodex** [comment]
I've tested with this:
`classpath 'com.apollographql.apollo:apollo-gradle-plugin:0.4.4'`

it's working fine now, thank you!
