### ISSUE TITLE
__typename added to every object in the query

### ISSUE THREAD

**Issue by ruiaraujo** [apollographql/apollo-android#1018]
I would like to understand why __typename is added to every object in a query. I would expect it to be there only in cases of unions or interfaces.

We use persisted queries to know which parts of the schema was safe to break when refactoring the schema, which includes type names. 

With this query transformation, our contract is getting extending to the type names we use with no obvious benefit.

**Comment by sav007** [comment]
Don't really remember why we decided to include it by default, @martijnwalraven could you please elaborate on the decision we made in the past?

**Comment by ruiaraujo** [comment]
How is it required for fragments?

**Comment by Nitishreddy787** [comment]
I just want __typename to not print in my json response.

**Comment by Nitishreddy787** [comment]
here is my response :
Data {
	getChannels = [GetChannel1 {
		__typename = ChannelResponse, _id = 5 a8bb0b84e4ee9a6f2f0b00c, channelName = medplus
	}, GetChannel1 {
		__typename = ChannelResponse, _id = 5 a8bb0b84e4ee9a6f2f0b00e, channelName = jiva
	}, GetChannel1 {
		__typename = ChannelResponse, _id = 5 a8bb0b84e4ee9a6f2f0b011, channelName = alpha
	}, GetChannel1 {
		__typename = ChannelResponse, _id = 5 a8bb0b84e4ee9a6f2f0b013, channelName = myCare
	}, GetChannel1 {
		__typename = ChannelResponse, _id = 5 a8bb0b84e4ee9a6f2f0b017, channelName = my trialing
	}, GetChannel1 {
		__typename = ChannelResponse, _id = 5 a93aa15b13d4c002736d336, channelName = Sample test Channel
	}, GetChannel1 {
		__typename = ChannelResponse, _id = 5 a97cb13fa9b91002734c09c, channelName = newchannel
	}, GetChannel1 {
		__typename = ChannelResponse, _id = 5 aa6236b4a71f5002a4fa895, channelName = doctorc
	}, GetChannel1 {
		__typename = ChannelResponse, _id = 5 aaf53ce4897f500279e3061, channelName = cellmoney
	}]
}

__typename is displaying in response it looks clumsy i just dont want __typename in my response

**Comment by Nitishreddy787** [comment]
Earlier in Hybride web apps we used Angular we approached 

apollo.create({
      link: httpLink.create({ uri: 'https://api.insuranceinbox.in/graphql-api/graphql?'}),
      cache: new InMemoryCache({
        addTypename: false
})
});


Here we user addTypeaname to remove __typename varaible in the response

**Comment by Nitishreddy787** [comment]
@sav007 can you please help for the above issue that i am facing.

**Comment by sav007** [comment]
Inline fragments and regular fragments requires this field to be able correctly parse response. 
```
query TestQuery {
  hero {
    ...HeroDetails
  }
}

fragment HeroDetails on Character {
  name
}

```

in this example we have fragment defined on the type `Character`. The only way to find out that the respose returned as Character type is to look for this special field `__typename`. There is no option to turn it off. 

Still I don't understand the issue, you want to remove `__typename` field from the response just because you don't like it? And by doing this fragments and inline fragments will stop working.

**Comment by ruiaraujo** [comment]
The problem is that `__typename` is added to every object, regardless if it is a fragment or not.

**Comment by RushiMThakker** [comment]
Adding typename to every object is generating a null response in your sample app. I checked with [Insomnia](https://insomnia.rest/). Firing queries on base url : https://api.githunt.com/graphql normally work fine but in case of sample app it is giving null response for some field. Eg. for FeedQuery, it is giving all "repository" and "postedBy" as null.

**Comment by Brajendra** [comment]
{
    "errors": [
        {
            "message": "column \"__typename\" does not exist",
            "locations": [
                {
                    "line": 1,
                    "column": 134
                }
            ],
            "path": [
                "search",
                "articles"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ],
    "data": null,
    "extensions": {
        "tracing": {
            "version": 1,
            "startTime": "2019-05-31T09:30:52.213Z",
            "endTime": "2019-05-31T09:30:52.271Z",
            "duration": 57717193,
            "execution": {
                "resolvers": [
                    {
                        "path": [
                            "search"
                        ],
                        "parentType": "Query",
                        "fieldName": "search",
                        "returnType": "SearchResults!",
                        "startOffset": 396178,
                        "duration": 1018880
                    },
                    {
                        "path": [
                            "search",
                            "articles"
                        ],
                        "parentType": "SearchResults",
                        "fieldName": "articles",
                        "returnType": "[Article]!",
                        "startOffset": 1480480,
                        "duration": 55994106
                    }
                ]
            }
        }
    }
}

**Comment by roffe** [comment]
why is the apollo anroid insisting on breaking every single query we created in it by adding a non required __typename

**Comment by martinbonnin** [comment]
Hi @roffe!

`__typename` is required by the runtime to handle polymorphism and fragments. For an example:

```
query GetHero {
  hero {
    ... on Human {
      name
      height
    }
    ... on Droid {
      name
      primaryFunction
    }
  }
}
```

The generated models for Droid and Humans will be different so the concrete type of the Hero is required.

Can you elaborate on what is breaking? The `__typename` field is in the [GraphQL spec](https://spec.graphql.org/June2018/#sec-Type-Name-Introspection) and any compliant server should support it.

**Comment by roffe** [comment]
how do i turn it off, don't need either

**Comment by martinbonnin** [comment]
There is still no option to remove `__typename` at the moment as it would require a lot of changes to support this and would complexify the code a lot. Adding such an option would be complex but, in theory, possible. We'd first need to understand what actual problem we're trying to solve.

**Comment by martinbonnin** [comment]
Hi 👋
I know it's been a while but if anyone is reading this in 2024, there's a `addTypename` option to customize the generation of `__typename` 🎉 . 

See [the Kdoc](https://apollographql.github.io/apollo-kotlin/kdoc/apollo-gradle-plugin-external/com.apollographql.apollo.gradle.api/-service/add-typename.html) for more info.
