### ISSUE TITLE
Intermittent Apollo Parse Exceptions

### ISSUE THREAD

**Issue by dbaggett** [apollographql/apollo-android#1019]
I am getting intermittent apollo parse exceptions. 

Exception message: "Failed to parse http response"
Cause message: "For input string: "14.E14E00"

I added the okhttp logging interceptor to the chain and the response is a valid response based on the schema, the string mentioned in the error messaged is not present.

**Comment by sav007** [comment]
could you please provide more info on what is the type for this field in schema and what model been generated for this field

**Comment by dbaggett** [comment]
@sav007 I am not sure which field is problematic in this case. The error message is random as well.

Here is the query:

`query VideoQuery($property_id: String!, $tag: String!, $first: Int, $type: ContentHint) {
  viewer {
    content {
      contentListByTag(tag: $tag, property_id: $property_id) {
        contents(first: $first, type: $type) {
          edges {
            node {
              id
              title
              caption
              originalPublishDate
              permalink
              ... VideoFragment
            }
          }
        }
      }
    }
  }
}

fragment VideoFragment on Video {
  image {
    asset {
      url
      width
      height
    }
  }
  videoAsset {
    playbackUrl
    runtimeSecs
  }
}`

I will work on sharing the schema.

**Comment by sav007** [comment]
Could you please attach the full stack trace of the error?

**Comment by dbaggett** [comment]
@sav007 Here's the stack trace which appears to be choking on the originalPublishDate

`"sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1890)"
"sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)"
"java.lang.Double.parseDouble(Double.java:538)"
"java.text.DigitList.getDouble(DigitList.java:169)"
"java.text.DecimalFormat.parse(DecimalFormat.java:2056)"
"java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:1869)"
"java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)"
"java.text.DateFormat.parse(DateFormat.java:364)"
"package.graphqlclient.shieldv3.client.ApolloClientFactory$dateTimeAdapter$1.decode(ApolloClientFactory.kt:31)"
"package.graphqlclient.shieldv3.client.ApolloClientFactory$dateTimeAdapter$1.decode(ApolloClientFactory.kt:26)"
"com.apollographql.apollo.internal.response.RealResponseReader.readCustomType(RealResponseReader.java:193)"
"package.graphqlclient.shieldv3.VideoQuery$Node$Mapper.map(VideoQuery.java:1047)"
"package.graphqlclient.shieldv3.VideoQuery$Edge$Mapper$1.read(VideoQuery.java:809)"
"package.graphqlclient.shieldv3.VideoQuery$Edge$Mapper$1.read(VideoQuery.java:806)"
"com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:138)"
"package.graphqlclient.shieldv3.VideoQuery$Edge$Mapper.map(VideoQuery.java:806)"
"package.graphqlclient.shieldv3.VideoQuery$Contents$Mapper$1$1.read(VideoQuery.java:710)"
"package.graphqlclient.shieldv3.VideoQuery$Contents$Mapper$1$1.read(VideoQuery.java:707)"
"com.apollographql.apollo.internal.response.RealResponseReader$ListItemReader.readObject(RealResponseReader.java:312)"
"package.graphqlclient.shieldv3.VideoQuery$Contents$Mapper$1.read(VideoQuery.java:707)"
"package.graphqlclient.shieldv3.VideoQuery$Contents$Mapper$1.read(VideoQuery.java:704)"
"com.apollographql.apollo.internal.response.RealResponseReader.readList(RealResponseReader.java:165)"
"package.graphqlclient.shieldv3.VideoQuery$Contents$Mapper.map(VideoQuery.java:704)"
"package.graphqlclient.shieldv3.VideoQuery$ContentListByTag$Mapper$1.read(VideoQuery.java:608)"
"package.graphqlclient.shieldv3.VideoQuery$ContentListByTag$Mapper$1.read(VideoQuery.java:605)"
"com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:138)"
"package.graphqlclient.shieldv3.VideoQuery$ContentListByTag$Mapper.map(VideoQuery.java:605)"
"package.graphqlclient.shieldv3.VideoQuery$Content$Mapper$1.read(VideoQuery.java:505)"
"package.graphqlclient.shieldv3.VideoQuery$Content$Mapper$1.read(VideoQuery.java:502)"
"com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:138)"
"package.graphqlclient.shieldv3.VideoQuery$Content$Mapper.map(VideoQuery.java:502)"
"package.graphqlclient.shieldv3.VideoQuery$Viewer$Mapper$1.read(VideoQuery.java:402)"
"package.graphqlclient.shieldv3.VideoQuery$Viewer$Mapper$1.read(VideoQuery.java:399)"
"com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:138)"
"package.graphqlclient.shieldv3.VideoQuery$Viewer$Mapper.map(VideoQuery.java:399)"
"package.graphqlclient.shieldv3.VideoQuery$Data$Mapper$1.read(VideoQuery.java:308)"
"package.graphqlclient.shieldv3.VideoQuery$Data$Mapper$1.read(VideoQuery.java:305)"
"com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:138)"
"package.graphqlclient.shieldv3.VideoQuery$Data$Mapper.map(VideoQuery.java:305)"
"package.graphqlclient.shieldv3.VideoQuery$Data$Mapper.map(VideoQuery.java:300)"
"com.apollographql.apollo.response.OperationResponseParser$1.read(OperationResponseParser.java:96)"
"com.apollographql.apollo.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.java:86)"
"com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:91)"
"com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)"
"com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)"
"com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:94)"
"okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)"
"okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)"
"java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)"
"java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)"
"java.lang.Thread.run(Thread.java:745)"`

**Comment by dbaggett** [comment]
@sav007 Here's my datetime adapter for reference:

`private val dateTimeAdapter = object: CustomTypeAdapter<Date> {
        private val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")

        override fun decode(value: CustomTypeValue<Any>): Date {
            try {
                return dateFormat.parse(value.value.toString())
            } catch (e: ParseException) {
                throw RuntimeException(e)
            }
        }

        override fun encode(value: Date): CustomTypeValue<String> {
            return CustomTypeValue.GraphQLString(dateFormat.format(value))
        }
    }`

The data is sensitive, but I can confirm with reasonable confidence that all instances of 'originalPublishDate' adhere to the expected format. Once again, this failure is intermittent - it will pass and fail with the same response.

This is beginning to look like an issue with SimpleDateFormat parsing.

**Comment by dbaggett** [comment]
Closing this ticket as I have confirmed this is an issue with SimpleDateFormat parsing. If anyone is curious, the joda date library is able to parse the format mentioned above 100% of the time.
