### ISSUE TITLE
Field seperator in query json

### ISSUE THREAD

**Issue by Stonepaw** [apollographql/apollo-android#1023]
Is it possible to specify the field separator in the outgoing request body?

For example if I have the following query:
```
query UsersQuery {
  users {
    id,
    username
  }
}
```
The current query json would be 
```"query UsersQuery {  users {    __typename    id    username  }}"```

Is it possible to change the fields to be comma separated?
```"query UsersQuery {  users {__typename,id,username}}"```

**Comment by digitalbuddha** [comment]
It is not, that does not seem to be valid graphql syntax

**Comment by sav007** [comment]
It;s not a valid syntax http://graphql.github.io
