### ISSUE TITLE
NETWORK_ONLY cache policy is still caching data?

### ISSUE THREAD

**Issue by emanzanoaxa** [apollographql/apollo-android#1026]
When I execute a  NETWORK_ONLY  query, and after that I execute the same query with CACHE_ONLY cache policy I get data from cache. This is correct? It's not supposed to return an error because no data is cached?
I am using http cache, not normalized one. Is there a way to prevent data from being cached for a query?

**Comment by sav007** [comment]
We have `com.apollographql.apollo.cache.ApolloCacheHeaders#DO_NOT_STORE` but this header works only for normalized cache. I think what we need to make it work for HttpCache as well.
