### ISSUE TITLE
1.0.0-alpha2: No such property: Date

### ISSUE THREAD

**Issue by abredykhin** [apollographql/apollo-android#1028]
After updating to Alpha2 I instantly see this error when syncing Gradle files: 

> No such property: Date for class: org.gradle.api.internal.provider.DefaultPropertyState
Possible solutions: type

This is with Gradle 4.9 and Android Gradle Plugin 3.3.0-alpha07

**Comment by abredykhin** [comment]
I figured why I got that error. It was caused by me using old style mapping for custom types. I had to change this
`
apollo {
    customTypeMapping['Date'] = "java.util.Date"
    customTypeMapping['DateTime'] = "java.util.Date"
}`

to this to get the build running

`
apollo {
    customTypeMapping = [
            "Date" : "java.util.Date",
            "DateTime" :"java.util.Date"
    ]
}
`

**Comment by digitalbuddha** [comment]
Pr appreciated to update Readme 🙂

**Comment by sav007** [comment]
seems that no one reads readme :)

https://github.com/apollographql/apollo-android#custom-scalar-types

**Comment by abredykhin** [comment]
To be fair the new syntax doesn't work with alpha1, that's where I got confused about that

**Comment by Phoca** [comment]
I stumbled upon this issue since I was using the old syntax as stated in the JavaDoc of the `CustomTypeAdapter` interface. Would be nice to update the docs there as well.
