### ISSUE TITLE
node.exe'' finished with non-zero exit value 1 (generateDebugApolloIR)

### ISSUE THREAD

**Issue by hopstad** [apollographql/apollo-android#1029]
This has been mentioned before but the topics are closed.

Our GraphQL variables had to be changed on the server so I needed a new schema.json

Done by generating it from the node_modules/.bin/ directory: 

`apollo-codegen download-schema https://oursite/api/graphql --output schema.json`

File get downloaded and moved to the app/src/main/graphql/com.myapp.something folder

So - The setup is the same like before but downloading this new schema is breaking everything. I have now gone back to square one. Deleted all my query files and just left with the schema.json file and the same error occours.

`app\.gradle\nodejs\node-v6.7.0-win-x64\node.exe'' finished with non-zero exit value 1`

**Comment by digitalbuddha** [comment]
Could you run gradle build with info and stack trace flags from command line. It should give more detail about the error

**Comment by digitalbuddha** [comment]
Does --info give any more detail? Tough to see from stack trace what is the problem

**Comment by hopstad** [comment]
@digitalbuddha 
Ah yes, I updated my reply above

**Comment by hopstad** [comment]
Solved by removing apollo and installing the new one. Then using new command for downloading schema : `apollo schema:download --endpoint=https://something.com`
