### ISSUE TITLE
Could not set unknown property 'sourceSetNames' for task ':xx:generateJunitApolloIR' of type com.apollographql.apollo.gradle.ApolloSystemCodegenGenerationTask.

### ISSUE THREAD

**Issue by steventannz** [apollographql/apollo-android#1032]
Getting this error with apollo-1.0.0-alpha2 when trying to use system installed apollo-codegen on a project using source sets.

Using:
- apollo-1.0.0-alpha2
- Gradle 4.4
- apollo-codegen 0.19.1

```
A problem occurred configuring project ':xx'.
> Could not set unknown property 'sourceSetNames' for task ':xx:generateJunitApolloIR' of type com.apollographql.apollo.gradle.ApolloSystemCodegenGenerationTask.

Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'sourceSetNames' for task ':xx:generateJunitApolloIR' of type com.apollographql.apollo.gradle.ApolloSystemCodegenGenerationTask.
        at org.gradle.internal.metaobject.AbstractDynamicObject.setMissingProperty(AbstractDynamicObject.java:115)
        at org.gradle.internal.metaobject.ConfigureDelegate.setProperty(ConfigureDelegate.java:105)
        at com.apollographql.apollo.gradle.ApolloPlugin$_createApolloIRGenTask_closure5.doCall(ApolloPlugin.groovy:151)
```
It is working with alpha1

**Comment by sav007** [comment]
Do you have any `sourceSetNames ` custom type defined in apollo config?

**Comment by steventannz** [comment]
I don't believe I do.

To clarify, this works on alpha2 using the downloaded version (via `installApolloCodegen`) instead of the system one.

It works with the system one on alpha1

**Comment by sav007** [comment]
Could you please show me your config for Apollo plugin that you have in gardle

**Comment by sav007** [comment]
Wait you are using system installed Apollo codegen, right?

**Comment by steventannz** [comment]
Yes, using the system installed Apollo Codegen (0.19.1), which it fails on. For further clarification:

alpha2 - system installed - Not Working
alpha2 - `installApolloCodegen`- Working
alpha1 - both - Working

Nothing really special in my gradle config besides
```
classpath "com.apollographql.apollo:apollo-gradle-plugin:apollo-1.0.0-alpha2"
apply plugin: 'com.apollographql.android'
    implementation "com.apollographql.apollo:apollo-runtime:apollo-1.0.0-alpha2"
    implementation "com.apollographql.apollo:apollo-rx2-support:apollo-1.0.0-alpha2"
```
and a couple of source sets configured for different flavors of my app that don't touch any apollo classes or anything.
