### ISSUE TITLE
Request is sent with unnecessary whitespace

### ISSUE THREAD

**Issue by Stonepaw** [apollographql/apollo-android#1034]
I've been experimenting with this library and noticed that the outgoing requests are sent in the POST body with unnecessary white space characters and line breaks. 

For example the query:
```
mutation CreateSession { 
  createSession {
    token
    content
  }
}
```
Is sent as a POST request with a body of:
<code>{"query":"mutation CreateSession { &nbsp;createSession { &nbsp;&nbsp;&nbsp;__typename &nbsp;&nbsp; token &nbsp;&nbsp; content &nbsp;}}","operationName":"CreateSession","variables":{}}</code>

Is there an option to normalize this behavior and strip the excessive white space and line break characters?

**Comment by ralphie9224** [comment]
@sav007 Picking this up if it's available
