### ISSUE TITLE
latest version in jcenter is 0.4.1

### ISSUE THREAD

**Issue by teicher** [apollographql/apollo-android#1035]
the latest version available from jcenter is 0.4.1 from August 2017.
`https://bintray.com/bintray/jcenter/com.apollographql.apollo%3Aapollo-runtime/0.4.1`
the readme page suggests it should be 1.0.0-alpha2
if maybe not alpha2, the 0.5.0 should be in jcenter.

**Comment by watery** [comment]
Check this: https://bintray.com/apollographql/android/apollo-runtime

**Comment by teicher** [comment]
Well, that's not jcenter.
The docs / gradle samples say to use jcenter(). The 1.0.0-alpha2 was not found there.
Maybe rather the gradle instructions need adjusting ?

**Comment by digitalbuddha** [comment]
The package name changed please see the link above. Also jcenter is owned by bintray and serves the above dependency

**Comment by teicher** [comment]
Ok so only the bintray search result was misleading. Many thanks.

**Comment by teicher** [comment]
except it does not work.
On the above link I directly copy the displayed gradle dependency snippet:
`compile 'com.apollographql.apollo:apollo-runtime:1.0.0-alpha2'`
and this is what I get
> Could not find com.apollographql.apollo:apollo-runtime:1.0.0-alpha2.

**Comment by watery** [comment]
@teicher I'm using it in Maven, but check the "Set me up!" button in the upper right corner in that page, there's a section `Resolving artifacts using Gradle` that may help you.

**Comment by teicher** [comment]
Hi thanks, that is exactly what I am saying!

The bintray "set me up" tells me to
```
maven { url "https://dl.bintray.com/apollographql/android" }
```
however the docs in the Readme say to use
```
jcenter()
```
which does not work, since jcenter() is not bintray (albeit hosted by the same company, whatever)

Can we reopen this issue please ?
