### ISSUE TITLE
Cannot access Fragment class in Kotlin Test

### ISSUE THREAD

**Issue by CedrickFlocon** [apollographql/apollo-android#1036]
Hello, 

When I try to use a Fragment class in a Test I got this build error : 
> e: PATH_TO_TEST/Test.kt: (11, 11): Cannot access class 'com.example.graphql.fragment.Name'. Check your module classpath for missing or conflicting dependencies

I have investigate a bit it and if I write my test in Java this error will not occurred.

Apollo Version : 1.0.0-alpha2
Kotlin version : 1.2.61

**Comment by japplin** [comment]
@digitalbuddha I'm still having this issue why was this closed?

**Comment by japplin** [comment]
Well after another hour I figured out something to at least get my tests working. I'll leave what I did here in case anyone else stumbles onto this(not that I think this is a great solution): 
```
java {
	sourceSets {
		test {
			java {
				include("**/*.java")
			}
		}
	}

	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8
}
```

**Comment by itdsk** [comment]
@japplin I  guess I had a similar issue and the following sourceSets snippet in my build.gradle file fixed the issue by adding the apollo-codegen generated source files to the java-test source files:
```
sourceSets {
    test {
        java {
            srcDirs = ["$buildDir/build/generated/source/apollo/classes"
            ]
        }
    }
}
```

**Comment by martino2k6** [comment]
I'm having the same issue and the suggested fix by @itdsk does not work.

**Comment by martino2k6** [comment]
No longer seems to be happening to me using version 1.2.1.

**Comment by Eselfar** [comment]
I have this issue with `3.8.2`.
If I run the tests the first time it works. Subsequent times fail with the above error.
If I clean the project first every time I want to run the tests, then it's working. Of course it's not a solution as rebuilding everything every time is quite time consuming.

I tried @itd-sk solution but it doesn't seem to work. Anyone with a solution?

**Comment by martinbonnin** [comment]
@Eselfar thanks for reporting this! Do you mind opening a separate issue with your Gradle configuration (`apollo {}` block) and full stacktrace? The original issue is from 2019 and the project changed a lot since then so I'm pretty confident this is a separate issue.

**Comment by Eselfar** [comment]
@martinbonnin Created a new ticket as requested: #5365
