### ISSUE TITLE
Need some docs and explain

### ISSUE THREAD

**Issue by Heroes84** [apollographql/apollo-android#1038]
Hi I have two question:
1.) How can I use prefetching ? I think that missing documentation like angular page have: https://www.apollographql.com/docs/angular/recipes/prefetching.html. I mean not only mention that use `ApolloClient.prefetch`to prefetch but provide examples how invalidate this prefetched data, how is stored (memory cache or sql), how can i configured it.
2.) How use "cast" class (this class with prefix "As"), for example I have complex query:
```
query routeQuery {
  routeByPath(path:"home-hz", publication:HZ) {
    object {
      ... on LandingPage {
        body {
          ... on EntityQueueParagraph {
            entityQueue {
              items {
                edges {
                  node {
                    ... on Article {
                      id
                      title
                      preferredUri
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

and now i try get article:
```
Rx2Apollo.from(caller)
                .flatMapIterable { (it.data()?.routeByPath()?.object() as RouteQuery.AsLandingPage).body() }
                .filter { it.__typename() == "EntityQueueParagraph" }
                .flatMapIterable { (it as RouteQuery.AsEntityQueueParagraph).entityQueue()?.items()?.edges() }
                .filter { it.node()?.__typename() == "Article" }
                .map { it.node() as RouteQuery.AsArticle }
                .filter { it.id() != null && it.title() != null && it.preferredUri() != null }
                .map {
                    Item(it.id() ?: "", it.title() ?: "", it.preferredUri() ?: "")
                }
                .collect({ Items(mutableListOf()) }, { items: Items, item: Item -> items.items.add(item) })
```

is any possiblity to avoid adding extra map function only to safe cast ?

**Comment by sav007** [comment]
1. Prefetch uses http cache, means it will dump the raw http response to the disk (prefetch executes almost at the same way as regular request  with http cache enabled except it doesn't parse response). 

If you want to ignore  prefetched and cached response you can provide appropriate Http cache policy such as `NETWORK_ONLY` or provide expireAfter

2. Not sure I'm following the question. What do you mean `avoid adding extra map function`?
