### ISSUE TITLE
How to do synchronized calls to the graphql server?

### ISSUE THREAD

**Issue by watery** [apollographql/apollo-android#1039]
I'm using this project in a Java web application that exposes a REST API and needs to access a GraphQL backend to fulfill some requests.

I managed to get Java classes generation from a GraphQL schema and queries files and GraphQL server connection working.

But since the application is serving REST requests, I need queries to happen in the same thread that is serving REST client requests, to be able to return the GraphQL query result back to the client.

How do I do it?

**Comment by watery** [comment]
I just found [this issue](https://github.com/apollographql/apollo-android/issues/606) and [this pull request](https://github.com/apollographql/apollo-android/pull/639), I guess synchronized calls are off limits now?

**Comment by digitalbuddha** [comment]
Yup the last suggestion in the pr is what I'd recommend https://github.com/apollographql/apollo-android/pull/639#issuecomment-388515264

**Comment by watery** [comment]
@digitalbuddha Thanks, I'll give it a look.

I hope synchronized calls will be re-added, the parts I'm using (code generation and server connections) seems well suited for independent non-android modules.

**Comment by digitalbuddha** [comment]
It cannot be added due to some Apollo query requests returning 2 results, one from cache one from network. There isn't a way to do they synchronously
