### ISSUE TITLE
Variable type name start with lowercase but generated class name start with uppercase.

### ISSUE THREAD

**Issue by BasyukYaroslav** [apollographql/apollo-android#1041]
Variable type name starts with lowercase but generated class name start with uppercase and as result
the project doesn't build because "CustomerLocationHumanizedInput" and "customerLocationHumanizedInput" are different  types and I receive "error: cannot find symbol class customerLocationHumanizedInput"

```
@Generated("Apollo GraphQL")
CustomerLocationHumanizedInput{

................................

}
```

```
@Generated("Apollo GraphQL")
public final class RegisterCustomerInput implements InputType {
  private final @NotNull String phoneNumber;

  private final @NotNull String email;

  private final Input<String> firstName;

  private final Input<String> lastName;

 // class  name starts with lowercase
  private final Input<List<customerLocationHumanizedInput>> locations;
  
  .................................
}
```

In the attached zip file I prepared an example project where is reproduce this problem
and there are schema query and all information.
[ApolloDifferentClassNaming.zip](https://github.com/apollographql/apollo-android/files/2340267/ApolloDifferentClassNaming.zip)

**Comment by sav007** [comment]
Thanks for the reporting the issue, we will try to address this. But just a note it's very common to use capitalized name for object types in GraphQL. By looking into your schema you have all object names started with lower case.
