### ISSUE TITLE
Apollo Codegen deprecated

### ISSUE THREAD

**Issue by KennyTsui** [apollographql/apollo-android#1042]
It seems like Apollo Codegen has been deprecated and replaced with Apollo, see:
https://www.npmjs.com/package/apollo-codegen
https://www.npmjs.com/package/apollo
```
> Task :installApolloCodegen
npm WARN deprecated apollo-codegen@0.18.3: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.
```

Based on the output, it looks like Apollo Android still uses the deprecated module, are there plans to migrate to Apollo from Apollo Codegen?

Follow up question: If a provided schema.json exists in the appropriate location, is it possible to skip node and apollo-codegen install entirely?

**Comment by sav007** [comment]
Yes there is such plan, the only what was blocking us https://github.com/apollographql/apollo-cli/issues/537. But seems it fixed now

**Comment by anudeep3998** [comment]
Any updates on when this will be released?

**Comment by sav007** [comment]
There are still some issues with Apollo code gen module we are trying to resolve. For now there is no big benefit of migrating to new apollo cli

**Comment by drsounds** [comment]
But it doesn't seems to generate any code anymore

**Comment by venik** [comment]
There is, apparently, a problem with the apollo-tooling:0.19.1
https://github.com/apollographql/apollo-tooling/blob/v0.19.1/package.json

it consumes:
    "graphql": "^0.13.1",

The problem we get looks similar to
https://github.com/apollographql/apollo-tooling/issues/630#issuecomment-434164573

and was fixed with (by updating graphql to version 14):
https://github.com/apollographql/apollo-tooling/pull/624

It would be really nice to move to the latest.

**Comment by mirkonasato** [comment]
Looks like the Apollo CLI doesn't support generating Java code yet. (As of v2.4.4.) Maybe that's the main issue?

Help for [apollo client:codegen](https://github.com/apollographql/apollo-tooling#apollo-clientcodegen-output):
> --target=target                            (required) Type of code generator to use (swift | typescript | flow | scala), inferred from output

There's a PR: [[WIP] add support for java and comment syntax](https://github.com/apollographql/apollo-tooling/pull/772)

**Comment by venik** [comment]
Current gradle plugin implementation generates JSON from GraphQL files and then uses Moshi
https://github.com/square/moshi
to generate Java code, problem here that apollo-tooling has a bug, which was solved, but current apollo-android still points to the old (buggy) apollo-tooling

**Comment by mirkonasato** [comment]
@venik as far as I can tell Moshi is just a JSON parser, not a code generator. It's [used](https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/main/java/com/apollographql/apollo/gradle/ApolloCodegenInstallTask.java#L77) by the Gradle plugin only to parse `package.json`. The plugin uses [apollo-codegen](https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloLocalCodegenGenerationTask.groovy#L14) to generate Java code.

**Comment by venik** [comment]
Well, it generates from
```
query blocksList {
  blocks {
    blockType
  }
}
```

something java-like

```
package com.sample.schemaapollo;
...
@Generated("Apollo GraphQL")
public final class BlocksListQuery implements Query<BlocksListQuery.Data, BlocksListQuery.Data, Operation.Variables> {
  public static final String OPERATION_ID = "bc2856a07ab37724cac77379757113c3e0b46fff849dc03bda9697ba58b3ea3e";

  public static final String QUERY_DOCUMENT = "query blocksList {\n"
      + "  blocks {\n"
      + "    __typename\n"
      + "    blockType\n"
      + "  }\n"
      + "}";

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "blocksList";
    }
  };

  private final Operation.Variables variables;

  public BlocksListQuery() {
    this.variables = Operation.EMPTY_VARIABLES;
  }
  ...
```

**Comment by friederikewild** [comment]
@sav007 Any news on this? Just integrated Apollo into my project and also noticed a build warning that seems to be related to this?

> deprecated apollo-codegen@0.19.1: The 'apollo-codegen' command ahs been replaced with the more-powerful 'apollo' CLI

**Comment by ashish-patidar-rau** [comment]
i have a same problem 

```
npm WARN deprecated apollo-codegen@0.19.1: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.
```

Is any other way to implement Apollo into Android?

**Comment by georgehadly-marleyspoon** [comment]
Getting the same warning from the CI tool, any news ?

```
npm WARN deprecated apollo-codegen@0.19.1: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.
```

**Comment by martinbonnin** [comment]
apollo-codegen is going away soon: https://github.com/apollographql/apollo-android/pull/1482.

You can actually already test this in the 1.0.3-SNAPSHOT version.

**Comment by sav007** [comment]
Please try latest version with a new code generation engine https://github.com/apollographql/apollo-android/releases/tag/1.1.0

If you see the same issue pls reopen.
