### ISSUE TITLE
Apollo Gradle Plugin need to be updated!

### ISSUE THREAD

**Issue by kissedcode** [apollographql/apollo-android#1043]
Someday i start building by android application, and gradle task named app:installApolloCodegen freezed. Here is the log:

> Task :app:installApolloCodegen 
Starting process 'command '/Users/kissed/projects/android/hands_clientapp/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node''. Working directory: /Users/kissed/projects/android/hands_clientapp/app/build/apollo-codegen Command: /Users/kissed/projects/android/hands_clientapp/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node /Users/kissed/projects/android/hands_clientapp/app/.gradle/nodejs/node-v6.7.0-darwin-x64/lib/node_modules/npm/bin/npm-cli.js install apollo-codegen@0.19.1 --save --save-exact
Successfully started process 'command '/Users/kissed/projects/android/hands_clientapp/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node''
npm WARN deprecated apollo-codegen@0.19.1: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.
<======-------> 50% EXECUTING [4m 51s]

I think cause is than apollo-codegen is deprecated, and apollo-gradle-plugin want to install it, but can't do this. Maybe apollo-gradle-plugin has to be fixed, changed to using "apollo".

It's blocking to me, please fix it ASAP. Thank you!

[x] blocking

**Comment by KennyTsui** [comment]
Try installing apollo-codegen manually into the working directory: `npm install apollo-codegen@0.19.1`

**Comment by sav007** [comment]
dup https://github.com/apollographql/apollo-android/issues/1042
