### ISSUE TITLE
Pre-installed apollo-codegen gives Cannot run program CreateProcess error=2

### ISSUE THREAD

**Issue by watery** [apollographql/apollo-android#1044]
I'm on Windows 7, Gradle 4.10 and Node v8.11.2 and if I run:

    apollo-codegen --version

on the command prompt I get:

    0.19.1

But if, within that same command prompt, I run:

    gradlew build

then I get:

    Verifying system 'apollo-codegen' version (executing command 'apollo-codegen --version') ...
    Failed to verify system 'apollo-codegen' version: java.io.IOException: Cannot run program "apollo-codegen": CreateProcess error=2, The system cannot find the file specified
    Installing apollo-codegen ...

Both commands are run from a non-privileged prompt, but `apollo-codegen --version` from a prompt with administrator rights still returns `0.19.1`.

On further inspection, I found that the plugin is using the Groovy ability to [Executing External Processes](http://docs.groovy-lang.org/latest/html/documentation/#process-management), which creates system processes using Java [Process](https://docs.oracle.com/javase/7/docs/api/java/lang/Process.html) class.

In fact, the following yields the same error:

```
public class StaticMain {

	public static void main(String[] args) {
		try {
			new ProcessBuilder("apollo-codegen",  "--version").start();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
}
```

That's because, I guess, the `apollo-codegen` found on the PATH (is located in `C:\Users\<username>\AppData\Roaming\npm`) is a Linux script. The Windows (batch) version is named `apollo-codegen.cmd`.

To have it succesfully terminate I have to either run:

* `new ProcessBuilder("apollo-codegen.cmd",  "--version").start();`
* `new ProcessBuilder("cmd", "/c", "apollo-codegen", "--version").start();`

**Comment by anosmhazo** [comment]
So how do we fix this.

**Comment by sav007** [comment]
Please try latest version with a new code generation engine https://github.com/apollographql/apollo-android/releases/tag/1.1.0

If you see the same issue pls reopen.
