### ISSUE TITLE
Can't declare multiple queries...

### ISSUE THREAD

**Issue by tjouin** [apollographql/apollo-android#1048]
Hey, I got an issue, if I put one query in a queries.graphql file its work, code generated, query work.

I got three queries done, each one work alone, but if I tried to put them in one file or seperated in three file. When I build nothing get generated and this error appear : 

Process 'command '/Users/tomjouin/StayTouchAndroid/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1

error: Validation of GraphQL query document failed

Here the complete compiler error trace : 
https://gist.github.com/tjouin/e612750b533e3ea4e93c0d676ada2191

Here are the queries : 

`query UserBasicInformation {
	my {
		accountInformation {
			id
			cognitoUserId
			email
			phone
			primaryPhone
			emailVerified
			phoneVerified
			type
			firstName
			lastName
			devices {
				id
				key
				name
				type
			}
		}
	}
}

query UserProfiles($id: [ID], $profileType: [ProfileType]) {
	my {
		profiles(id: $id, type: $profileType) {
			id
			type
			title
			hasPrimaryPhone
			data {
				key
				title
				value
				format
			}
		}
	}
}

query UserContacts {
	my {
		contacts {
			id
			firstName
			lastName
			title
			data {
				key
				title
				value
				format
			}
		}
	}
}
`

**Comment by sav007** [comment]
> error: Validation of GraphQL query document failed

Tells that you have not valid GraphQL query. Check the query

**Comment by sav007** [comment]
And multiple queries are not allowed in one file. They must be in separate files

**Comment by tjouin** [comment]
These queries all work on iOS with our schema. Do you see something wrong around UserContacts query ?
