### ISSUE TITLE
How to properly close/shutdown an apollo client?

### ISSUE THREAD

**Issue by watery** [apollographql/apollo-android#1052]
How do I "close" an `ApolloClient` which holds an active subscription to a GraphQL server and/or has any pending outgoing requests?

I'm using it inside a web application, it that matters.

**Comment by watery** [comment]
I found this [comment](https://github.com/square/okhttp/issues/3372#issuecomment-335858692) among [OkHttp](https://github.com/square/okhttp) issues that says to call:

     okHttpClient.dispatcher().executorService().shutdown();
     okHttpClient.connectionPool().evictAll();
     okHttpClient.cache().close();

But this doesn't work when a subscription has been `execute()`d, therefore causing my Tomcat instance not to exit.

After a forced stop, Tomcat outputs:

```
set 11, 2018 2:33:17 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
GRAVE: The web application [/] appears to have started a thread named [Apollo Dispatcher] but has failed to stop it. This is very likely to create a memory leak.
set 11, 2018 2:33:17 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
GRAVE: The web application [/] appears to have started a thread named [OkHttp ConnectionPool] but has failed to stop it. This is very likely to create a memory leak.
set 11, 2018 2:33:17 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
GRAVE: The web application [/] appears to have started a thread named [Okio Watchdog] but has failed to stop it. This is very likely to create a memory leak.

```

**Comment by sav007** [comment]
Closing
