### ISSUE TITLE
Cache an API call

### ISSUE THREAD

**Issue by priyakar** [apollographql/apollo-android#1053]
I just wanted to ask if there is any way to cache one single API call? 
Right now Im using the `Normalized Disk Cache` and it looks like its overriding the last saved API response.

**Comment by sav007** [comment]
I'm not sure I got you issue. Are you referring to http cache or normalized cache?

**Comment by priyakar** [comment]
Normalized cache. Is there a memory limit on it or something? Because I am loading images on the first screen and then a bunch of other text for other screens.

**Comment by priyakar** [comment]
I switched to HttpCache since it let me define a size. I think since I was caching images, the Normalized Cache may have had memory problems.
