### ISSUE TITLE
Latest version of plugin (Sept 10 2018) causes build error (uppercase/lowercase conflict)

### ISSUE THREAD

**Issue by HelenaSewell** [apollographql/apollo-android#1056]
Using the plugin `'com.apollographql.apollo:apollo-gradle-plugin:1.0.1-SNAPSHOT'` on my project.
This is one of the queries that was affected:
```
query MyQuery($uri: String!) {
    page(uri: $uri) {
        id
        title
        uri
        children {
            id
            title
            uri
            ... on FolderTemplate {
                ... Folder
            }
        }
    }
}
```
It seems like the plugin must have been updated, and after that, I started getting build errors on my project:
```
error: cannot find symbol
    final @Nullable List<Child> children;
                         ^
  symbol:   class Child
  location: class Page
```
Looking at the file, it seems the interface had been created in lowercase:
```
public interface child {
    @NotNull String __typename();
```
As you can see from the error, all the references to this interface are in uppercase.

Using 0.5.1-SNAPSHOT instead of the latest fixed the issue.

**Comment by sav007** [comment]
Could you try again latest snapshot there was PR https://github.com/apollographql/apollo-android/pull/1051 merged recently. And the question did it start happening recently? I mean did you use `1.0.1-SNAPSHOT` before and it was working ok?

**Comment by HelenaSewell** [comment]
Yes, the latest version fails. This started happening immediately after that was merged, and previously was fine.

**Comment by sav007** [comment]
Is it possible to sneak peak on your schema and graphql query, you can dm me in slack.

**Comment by sav007** [comment]
I tried all my best to replicate the issue but couldn't. So to fix this issue I nee you to provide me your schema.

**Comment by HelenaSewell** [comment]
I have messaged you the schema in slack :)

**Comment by HelenaSewell** [comment]
Has the plugin updated? The build error seems to be occurring the same as before
