### ISSUE TITLE
Failed to parse http response but before i get correct data

### ISSUE THREAD

**Issue by QitmentX7** [apollographql/apollo-android#1057]
I now this is child task but i cannot resolve it.
I try this code: 

```
MyApolloClient.getMyApolloClient().query(GetSQuery.builder().build())
                .enqueue(new ApolloCall.Callback<GetSQuery.Data>() {
                    @Override
                    public void onResponse(@Nonnull Response<GetSQuery.Data> response) {
                        try {
                            Log.d(TAG, "onResponce: " + response.data().getS().ts().toString());
                        } catch (Exception e) {
                            e.printStackTrace();
                        }


                    }

                    @Override
                    public void onFailure(@Nonnull ApolloException e) {
                        Log.d(TAG, "onFailed: " + e.getMessage());
                    }
                });
```
And try this Query:
```
`query getSQuery{
   getS{
     ts
     topic
     value
   }
 }`
```
And i get correct results but not correct parse result:

```
 ` 
 D/OkHttp: {"data":{"getSensor":{"__typename":"Sensor","ts":1536752717,"topic":"dev/pv/00-04-a3-0b-00-22-79-ef/status/1","value":5380576}}}
 D/MainActivity: onFailed: Failed to parse http response
 `
```
Thank you all!

**Comment by sav007** [comment]
Sorry but the response seems not in sync with query. In query you ask for `getS ` but in response theres `getSensor `

**Comment by sav007** [comment]
Could you print the whole stack trace of the error

**Comment by QitmentX7** [comment]
I am try version 0.4.1 and all work fine!

**Comment by sav007** [comment]
Query / response seem legit. Could you pls print the stack trace of the error you getting in the `onFailed ` callback? And please join our slack http://www.apollostack.com/#slack and ping me there, might be faster

**Comment by piercruz** [comment]
I have a similar issue with this, usually is because the type of the field requested is not being passed by apollo. I remove all fields and adding one by one until get this problem ride off, once you have found the incorrect field you should fix in your backend. I had a date issue and my adapter was not converting in the correct way so I get many times that kind of error and I spent at least 3 days trying to fix it. I hope it can helps you.

**Comment by QitmentX7** [comment]
@piercruz  Great thanks for answer but i already find decisions. Yes my problem was in some field (custom scalar type):
``Caused by: java.lang.IllegalArgumentException: Can't map GraphQL type: Long to: class java.lang.Object. Did you forget to add custom type adapter`
`
Great thanks for help @sav007 , i add this line and all become okay.

```
apollo {
  customTypeMapping = [
    "Long" : "java.lang.Long"
  ]
}
```
More about custom scalar type you can learn from this [article](http://graphql.github.io/learn/schema/#scalar-types):

**Comment by zeEzOoo** [comment]
> @piercruz Great thanks for answer but i already find decisions. Yes my problem was in some field (custom scalar type):
> ``Caused by: java.lang.IllegalArgumentException: Can't map GraphQL type: Long to: class java.lang.Object. Did you forget to add custom type adapter` `
> Great thanks for help @sav007 , i add this line and all become okay.
> 
> ```
> apollo {
>   customTypeMapping = [
>     "Long" : "java.lang.Long"
>   ]
> }
> ```
> 
> More about custom scalar type you can learn from this [article](http://graphql.github.io/learn/schema/#scalar-types):

My problem also same as you. how can you get this java.lang. IllegalArgumentException exception.
My query is this:
```
query FetchProducts ($first: Int!, ) 
                     {
      products(first: $first) {
      pageInfo {
          hasNextPage
        }
        edges {
          cursor
          node {
            id
            title
            priceRange{
              maxVariantPrice{
                amount
              }
            }
            images(first: 1) {
                edges {
                  node {
                    id
                    originalSrc
                  }
                }
              }
        productType
        description
      }
     }
    }
}
```
and my problem is in "images" field. How can i fix it. And how can I decide which customTypeMapping need to add.
