### ISSUE TITLE
Is X-APOLLO-OPERATION-NAME stable?

### ISSUE THREAD

**Issue by ursusursus** [apollographql/apollo-android#1061]
Hi,
I am writing a ok http interceptor to add authorization header to certain queries. Obviously all calls share the same url so I need something to distinguish between them. Ive noticed X-APOLLO-OPERATION-NAME header added by Apollo

Is this considered stable? Can I rely on this string? Whats the recommended way to do this? Thanks

(Best would be to pass application custom header somewhere at apollo.enqueue level)

**Comment by sav007** [comment]
You can rely on both `HEADER_APOLLO_OPERATION_NAME` and `HEADER_APOLLO_OPERATION_ID`.  Where:
-  `HEADER_APOLLO_OPERATION_NAME` is the name you gave it to the graphql operation in your query, it will change only if you change the name.
- `HEADER_APOLLO_OPERATION_ID`  will be change only if you change the query (like name, add or remove new field, etc.)
