### ISSUE TITLE
How to utilize multiple GraphQL schemas in same project?

### ISSUE THREAD

**Issue by hmittal90** [apollographql/apollo-android#1063]
Hello,

I am unable to figure out how I can utilize multiple graphql schemas (with different endpoints) in the same project. I could find a PR that states this functionality is implemented in apollo-android (#226 ), but where/how do I use that in my code?

e.g I have put two different `schema.json` files in `/src/main/graphql/github/schema.json` and `/src/main/graphql/linkedin/schema.json` (along with their corresponding query `.graphql` files), and when I try to build the project, only `github/schema.json` is picked, and any code referencing `linkedin` queries make the build fail. 

Do I need to create multiple `ApolloClient`s for this? I am finding the documentation lacking in terms of explaining how to utilize this workflow. I can create a PR for the docs if you can help me clarify how this can be accomplished.

Thanks in advance.

**Comment by sav007** [comment]
That strange as it should work, let me check on my end.

**Comment by disparate** [comment]
Hello, any updates on that? Is there any sample with 2 different schema.json's for different apis in single module? Currently I'm using workaround with separate modules for every api.

**Comment by sav007** [comment]
Did you try to use package folder structure and put each schema into different packages:
https://github.com/apollographql/apollo-android/tree/master/apollo-integration/src/main/graphql/com/apollographql/apollo/integration
