### ISSUE TITLE
How to feed hardcoded string json responses?

### ISSUE THREAD

**Issue by ursusursus** [apollographql/apollo-android#1068]
Hi, I am looking for a mock mode but in a actual app, not unittest so I kind of dont want MockWebserver. Is there a way I could use just the json mappers directly? From what Ive seen they take ResponseReader which I am not how to implement.

Is there a easier way?

Thanks

**Comment by sav007** [comment]
I think this should help: https://github.com/apollographql/apollo-android/blob/master/apollo-integration/src/test/java/com/apollographql/apollo/IntegrationTest.java#L291
