### ISSUE TITLE
Support Android Feature modules

### ISSUE THREAD

**Issue by 16BitsOfAwesome** [apollographql/apollo-android#1069]
### Issue
When using Apollo with the android plugin, `com.android.feature`, the following error is shown: "Apollo plugin couldn't be applied. The Android or Java plugin must be configured first"

This is an extension on the closed issue, #698.

### Discussion

With Android's new Instant App structure, it requires apps to use the following plugins for their modules:

- `com.android.application`
- `com.android.instantapp`
- `com.android.feature`

An example of this structure is found here: https://github.com/googlesamples/android-instant-apps/tree/master/multi-feature-module

Currently, Apollo works with `application` and, as of #1067, `instantapp`. This issue requests adding support for `feature`.

The proposed fix, proposed by the plugin author @marwanad in #698, is to add `project.plugins.hasPlugin("com.android.feature")` to the list of checks [here](https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloPlugin.groovy#L41).

**I would be happy to make a pull request for this change**, but wanted to have a quick code style discussion first. Namely, the conditional in the if-else statement will grow another line. Would that be an issue, or would you rather have all of that wrapped in a `canApplyPlugin()` method?

**Comment by digitalbuddha** [comment]
wrap it in a function/method. Thank you

**Comment by sav007** [comment]
I think we can close this issue.

**Comment by RishabhTayal** [comment]
@digitalbuddha Can you provide more details on how to wrap it in a function/method?
