### ISSUE TITLE
ApolloInterceptor: Why I got $hashCode and $hashCodeMemoized values

### ISSUE THREAD

**Issue by bellierjonathan** [apollographql/apollo-android#1071]
Hello,

I would like to intercept custom errors with an ApolloInterceptor but I don't understand why I got `$hashCode` and `$hashCodeMemoized` values when I use the method `request.operation.variables()`.

```
val gsonPretty = GsonBuilder().setPrettyPrinting().create()
gsonPretty.toJson(request.operation.variables())
```
**OUTPUT :**
```
...
"$hashCode": 0,
"$hashCodeMemoized": false,
...
```

Thanks,

**Comment by sav007** [comment]
hashCode and  hashCodeMemoized are special fields generated to correctly compare objects. If you open generated class source code you will see Apollo generates `equals` and `hashcode` similar to what AutoValue does

**Comment by bellierjonathan** [comment]
Yes I saw this, but I'm looking for to have just object without `$hashcode` or `$hashCodeMemoized`.
It's to pass it to Sentry if there is an error to get all parameters that has been sent by the user. I would like exactly parameters that has been used 😕

**Comment by sav007** [comment]
I think what we are missing is `transient` modifier, to disable these fields be serialized.
