### ISSUE TITLE
How do subscriptions work? 

### ISSUE THREAD

**Issue by k-misztal** [apollographql/apollo-android#1075]
As there is not a lot of documentation about `subscriptions` I'd like to ask about a few things. 

1. Is there any reconnection mechanism implemented? If it is, how does it work? Am I notified anyhow about reconnecting attempts? 
If `Apollo` reconnects automatically, what happens with data that could be hypothetically emitted by the server during our _down time_? Does `Apollo` try to fetch it or do I have to manually fetch data after reconnection? 

2. What happens if I subscribe to the same subscription many times? Is the same (socket?) connection reused, or each time there is a new connection created? 

/label question

**Comment by sav007** [comment]
You need to clone call before re-trying `com.apollographql.apollo.ApolloCall#clone`

**Comment by k-misztal** [comment]
Thanks for the tip, it helped me to find my bug. I used an Rx, and I forgot to `defer` my `Flowables`, so each time `retryWhen` was trying to resubscribe it used the old, _used_ call. 

Thank you for your help. It's actually all I wanted to find out about subscriptions. You can close the issue or leave it open to make it visible for other users. Up to you.

**Comment by android-imdad** [comment]
@k-misztal I am having the same issue, would you care to share your solution, I am not very familiar with RxJava Flowables.
