### ISSUE TITLE
Make Apollo compiler to generate Kotlin classes

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#1079]
Idea to have a feature flag to be able select Kotlin or Java models generation.

**Comment by k-misztal** [comment]
Kotlin data classes would be aweeeeeeeesome.

**Comment by TuonBondol** [comment]
If that possible, should have to implement both Parcelable and Serializable too, for Android Development, we need it to wrap data when parsing data with intent to new activity.

**Comment by hzsweers** [comment]
At the risk of starting an architecture flamewar - you shouldn't be sending full models through intents like that. I don't think that supporting that case should be a concern right now for getting initial kotlin code gen support

**Comment by k-misztal** [comment]
I agree that this feature is not a _must have_, but more _nice to have_. Obviously sending large objects via intents is not a good idea and it's better to just send an id and query for data in a new activity/fragment. 

Although, sometimes you have a small object that you'd like to send and this can be handy. 

I've never worked on a code-gen type of library so I don't know what the possibilities are. But if it'd be possible to just use `Parcelable` generation provided by Kotlin, all you have to do is annotate your classes with `@Parcelize` annotation. If not, and implementing that feature is a problem I definitely agree that it shouldn't be a concern.

**Comment by k-misztal** [comment]
Another idea - it'd be nice to have union types represented by sealed classes.

**Comment by dri94** [comment]
@sav007 I see you closed this issue but can you explain how we make it generate kotlin?

**Comment by ZacSweers** [comment]
It's in the README

**Comment by abhishekdubeyp** [comment]
Support for kotlin
   // build.gradle or build.gradle.kts
    apollo {
        generateKotlinModels.set(true) // or false for Java models
    }
