### ISSUE TITLE
Allow ApolloClient to be Proxied

### ISSUE THREAD

**Issue by xenoterracide** [apollographql/apollo-android#1083]
https://github.com/spring-projects/spring-boot/issues/14879#issuecomment-430777067

Can `ApolloClient` please not be final, or maybe have a single interface that composes the 4 factory interfaces? Right now my client will be fine with just mutation, but if I wanted to do read/write in the same interface I'd have to inject 2 or more of them. Interface method is preferred, imho.

**Comment by Hemantkumar-Chigadani** [comment]
And `final` makes it hard to mock via mockito. Using `mock-maker-inline` as work around.

**Comment by digitalbuddha** [comment]
you can make a single interface by extending the 4 interfaces. I'm not sure if conflating interfaces together for  general use is what we want.

**Comment by xenoterracide** [comment]
yes, but I can't make your class use my interface, and it's final, thus I can't extend it... so what exactly do you expect? me to reimplement a full delegate?

**Comment by digitalbuddha** [comment]
Misunderstood the issue sorry. Reopening

**Comment by sav007** [comment]
Closing out of date. You can always mock raw http server request if needed with https://github.com/square/okhttp/tree/master/mockwebserver
