### ISSUE TITLE
Deprecated Generated Mutations/Queries are not picked up by lint

### ISSUE THREAD

**Issue by JacquesSmuts** [apollographql/apollo-android#1097]
I'm not sure if this is an issue with my lint setup or with Apollo. I have a Mutation which is tagged as @OBSOLETE in the schema. The generated class does tag the Mutation as deprecated, but when I use the GeneratedClass.builder(), lint does not pick up that it is deprecated.

So for example, the `Date(year,month,date) ` constructor is deprecated in Java and throws a warning.

But the generated `GroupRenameMutation.builder().build()` class does not throw a warning.

Can  the builder() constructor or build() function also be tagged as deprecated in a deprecated class?

**Comment by JacquesSmuts** [comment]
For some clarification: Deprecated parameters in the schema do get the deprecated label in the generated code and I get a lint warning if I attempt to use that parameter.

Queries and Mutations, however, do not.

**Comment by digitalbuddha** [comment]
low priority, pr welcome :-)

**Comment by tasomaniac** [comment]
In this case, even though the functions are not marked, `GroupRenameMutation` should have strikethrough on it when you call `GroupRenameMutation.builder().build()`

**Comment by sav007** [comment]
looks like out of date.
