### ISSUE TITLE
Apollo classes generated with 2 errors 

### ISSUE THREAD

**Issue by JackFlash7** [apollographql/apollo-android#1107]
I'm trying to run the following simple query that works fine on insomnia 
query  BrandsQuery {
    brands {
      results {
        _id
      }
    }
}

but when trying to run I get the following error messages:

/Users/eyalzisman/Developer/ApolloTest/app/build/generated/source/apollo/classes/com/apollographql/apollo/sample/BrandsQuery.java:210: error: <anonymous com.apollographql.apollo.sample.BrandsQuery$Brands$1$1> is not abstract and does not override abstract method write(List,ListItemWriter) in ListWriter
          writer.writeList($responseFields[1], results, new ResponseWriter.ListWriter() {
                                                                                        ^
/Users/eyalzisman/Developer/ApolloTest/app/build/generated/source/apollo/classes/com/apollographql/apollo/sample/BrandsQuery.java:211: error: method does not override or implement a method from a supertype
            @Override
            ^
Note: /Users/eyalzisman/Developer/ApolloTest/app/src/main/java/com/example/applevel/MyApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

I'm using:

    classpath 'com.apollographql.apollo:apollo-gradle-plugin:1.0.0-alpha2'

and:
    implementation "com.apollographql.apollo:apollo-runtime:1.0.0-alpha2"
    implementation "com.apollographql.apollo:apollo-android-support:1.0.0-alpha2"
    implementation "com.apollographql.apollo:apollo-rx2-support:1.0.0-alpha2"

Please help

**Comment by sav007** [comment]
Could you please try a snapshot version?

**Comment by JackFlash7** [comment]
OK I was combining 1.0.1-SNAPSHOT for the plugin and 0.5.0 for the dependencies and it seem to work.

Thanks.
