### ISSUE TITLE
Conflict when Api returns an object called Operation

### ISSUE THREAD

**Issue by fievx** [apollographql/apollo-android#1110]
So this is a very edgy case but still.

The api I am calling using Apollo contains an object called Operation and when I create a query supposed to return an Operation from this Api, the Apollo generated query file does not compile because the Variables class generated is trying to extend from Operation.Variables, which does not exist because the Operation class available in this context is the api Operation model and not the Apollo Operation object.

**Comment by sav007** [comment]
I think that we should add such keywords used by Apollo API to the list of reserved keywords, and resolve conflict GraphQL schema types accordingly
