### ISSUE TITLE
How do you update UI?

### ISSUE THREAD

**Issue by brandon-binary** [apollographql/apollo-android#1111]
I find it confusing that the documentation asks you to update the UI inside the onResponse method. 

Currently, what I wanted to do is load the data from a source and pass it into an custom Adapter class so I can display it on a GridView in a fragment. I run into the problem where because the data is queried in the background, it does not return the data when I call the function. Is there a wait and return function?

**Comment by sav007** [comment]
If you want to update UI inside the callback `onResponse ` you need to switch to the main thread or use `com.apollographql.apollo.ApolloCallback` from `apollo-android-support`
