### ISSUE TITLE
customTypeMapping - cannot assign a value to final field warning

### ISSUE THREAD

**Issue by ollie72** [apollographql/apollo-android#1118]
With `1.0.0-alpha3`:

```
apollo {
    customTypeMapping = [
        "DateTime" : "java.lang.String",
        "UUID" : "java.lang.String",
        "JSONString" : "java.lang.String"
    ]
}
```

`customTypeMapping` recently started showing `Cannot assign a value to a final field` warning in the Gradle build file. The project builds and runs fine, the configuration IS applied. If I remove the above, I see type build failures for DateTime, UUID and JSONString.

I tried this approach:

```
apollo {
    customTypeMapping['DateTime'] = "java.lang.String"
    customTypeMapping['UUID'] = "java.lang.String"
    customTypeMapping['JSONString'] = "java.lang.String"
}
```

This gives a build error: `No such property: DateTime for class: org.gradle.api.internal.provider.DefaultPropertyState`

Is there a way to get rid of the warning in Android Studio, whilst still applying the configuration? Or if the first example above is the correct approach, does the warning need removing?

**Comment by sav007** [comment]
So it's just warning, right? And what version of gradle are you running on?

**Comment by sav007** [comment]
I guess I know why it complaints, hope fix will fix it

**Comment by ollie72** [comment]
Yes, just an IDE warning:

<img width="500" alt="screen shot 2018-11-23 at 08 06 45" src="https://user-images.githubusercontent.com/823913/48933096-ec61d480-eef6-11e8-8702-775b58dbe8d4.png">

Android Gradle plugin 3.2.1
Gradle 4.6
