### ISSUE TITLE
Upload release artifacts to Maven Central?

### ISSUE THREAD

**Issue by brockgibson** [apollographql/apollo-android#1130]
I am looking to integrate apollo-android into an application in a development environment that has integration with maven central but not jcenter. Would it be possible to have all apollo-android (e.g. apollo-runtime, ...) get deployed to maven central in addition to jcenter? The last release I see showing is [0.4.1](https://mvnrepository.com/artifact/com.apollographql.apollo/apollo-runtime).

I do see releases pushed under a [tab called "Spring Plugins"](https://mvnrepository.com/artifact/com.apollographql.apollo/apollo-runtime?repo=springio-plugins-release) which seems a little odd and they are not available at https://repo.maven.apache.org/maven2 either.

**Comment by digitalbuddha** [comment]
I think you have the old package name. Use these' instead: https://search.maven.org/search?q=com.apollographql.apollo

**Comment by digitalbuddha** [comment]
you're right there's a problem with the publishing.  We will correct. In the meantime use jcenter

**Comment by martinbonnin** [comment]
Even jcenter seems to lag sometimes ? I recently had to include bintray explicitely (and not jcenter)

    maven {
        url 'http://dl.bintray.com/apollographql/android'
    }

I'm not an expert at this but it certainly feels a bit weird

**Comment by Sparow199** [comment]
Hello,
You could easily sync release artifacts to maven central from the UI using the API.
https://bintray.com/docs/api/#_sync_version_artifacts_to_maven_central

**Comment by gabrielittner** [comment]
Any updates on this?

**Comment by adghrera** [comment]
Any updates?

**Comment by martinbonnin** [comment]
Another reason to switch to mavenCentral would be to have proper plugin marker support, I can't get them to be promoted to jcenter. 

I might give it a shot in the coming days/weeks. Still figuring out whether to use bintray sync or just promote the SNAPSHOTs that we are already uploading to OSS.

**Comment by martinbonnin** [comment]
Plugin markers are now uploaded to jcenter too. See https://github.com/apollographql/apollo-android/pull/2001.

Is mavenCentral really needed ? Now that I think about it, I kind of like having a single source of truth in jcenter. What are the pros of syncing to mavenCentral ?

**Comment by bbc2** [comment]
Maven Central being the default repository in Maven, having apollo-android there would enable users to get it without having to tweak repositories.

**Comment by martinbonnin** [comment]
> Maven Central being the default repository in Maven

Are you using apollo with maven (as in the maven build tool) ? Since apollo uses a gradle plugin I was expecting everyone to use gradle and there jcenter() and mavenCentral() both have to be explicitely added if I'm not mistaken.

For the record, I'm not against adding mavenCentral, I'm trying to understand what the use case exactly before committing to supporting yet another repo.

**Comment by bbc2** [comment]
Yes, we build an API client library with the Gradle plugin, but that library is then used by various projects, including some that are built with Maven.  The transitive dependency they have to download, currently from jcenter, is `com.apollographql.apollo:apollo-runtime`.  So, for us at least, being able to get that artifact from Maven Central (and also for our users) would be great!

**Comment by aoudiamoncef** [comment]
Any updates?

**Comment by aoudiamoncef** [comment]
The issue was fixed.
Thanks 👍

**Comment by martinbonnin** [comment]
@aoudiamoncef artifacts shouldn't be in mavenCentral yet. https://repo1.maven.org/maven2/com/apollographql/apollo/ only contains old versions.
There are some snapshots at https://oss.sonatype.org/content/repositories/snapshots/com/apollographql/apollo/ but I don't recommend using snapshots in production.
If you can find them, please let us know at what url as it sounds weird.

**Comment by aoudiamoncef** [comment]
I'm sorry, I commented the wrong issue 🙏. I was talking about #2099.

**Comment by ToxicMushroom** [comment]
Bintray releases seem to be missing ?

**Comment by martinbonnin** [comment]
Releases starting with `2.2.0` should be both on MavenCentral and JCenter:

https://repo1.maven.org/maven2/com/apollographql/apollo/
https://jcenter.bintray.com/com/apollographql/apollo/
