### ISSUE TITLE
Cannot build project using gradle-5.0-rc-2 using 1.0.0-alpha3

### ISSUE THREAD

**Issue by paixols** [apollographql/apollo-android#1135]
[Apollo Android version 1.0.0-alpha3]

Getting the same error as closed issue [https://github.com/apollographql/apollo-android/issues/1106](url) #1106
`--> > java.io.FileNotFoundException: [...]/build/generated/source/apollo/generatedIR/staging (Is a directory)`

Any ideas on how to solve this?

**Comment by lgawin** [comment]
It's already fixed with #1125 
Please try with `1.0.1-SNAPSHOT` version (note you need to use Sonatype's snapshots repository as described in `README.md`)

**Comment by paixols** [comment]
Current versions that built successfully:
apollo = "0.3.2" 
apolloRx = "1.0.0-alpha" 
gradleVersion = '3.3.0-beta04' 
apollo/2.1.6 darwin-x64 node-v11.3.0
- **Will continue to test with @lgawin recommendations**

**Comment by scana** [comment]
@sav007 would it be possible to release the fix from #1125 as a non-SNAPSHOT version, i.e. `1.0.0-alpha4`?

**Comment by digitalbuddha** [comment]
We will get a release out shortly, sorry for delay. Holidays and such :-)

**Comment by paixols** [comment]
I noticed that if you're using apollo version **1.0.0-alpha3** with **Android Studio 3.3Rc2** it's important to check your **gradle-wrapper.properties** file must point to this distribution url **https\://services.gradle.org/distributions/gradle-4.10.1-all.zip** in order to succeed. 

If using Android Studio Preview in the Canary Channel  it has to be in **https\://services.gradle.org/distributions/gradle-5.X.X-all.zip** and using the apollo **Snapshot** version. 

Sometimes Android Studio doesn't update the gradle wrapper automatically if running different versions in the same machine.

**Comment by TonnyL** [comment]
Any progress on this?

**Comment by tasomaniac** [comment]
This should be closed. Alpha4 is already released and I can confirm that this issue has been fixed.

**Comment by ber4444** [comment]
It's broken again with Gradle 5.1.1

**Comment by ber4444** [comment]
Which makes it incompatible with Android plugin 3.4.0 and higher.

**Comment by tasomaniac** [comment]
We are using Android plugin. 3.4.0 with Gradle 5.3.1 with no problem. Are you sure you are getting the same issue?

**Comment by ber4444** [comment]
Yes, but I fixed it with this hack: https://github.com/apollographql/apollo-android/issues/1236#issuecomment-484414774

**Comment by pvegh** [comment]
> We will get a release out shortly, sorry for delay. Holidays and such :-)

Can we have an alpha6 with a new fix?
