### ISSUE TITLE
ApolloClient UnitTest

### ISSUE THREAD

**Issue by ghost** [apollographql/apollo-android#1144]
I have a API and UseCase class likes below. 

Api class
```
class TestingApi(private val client: ApolloClient) {
    fun get(): Single<Response<PersonQuery.Data>> {
        return PersonQuery().let { query ->
            client.query(query)
        }.let { call ->
            Rx2Apollo.from(call)
        }.let { observable ->
            Single.fromObservable(observable)
        }
    }
}
```

UseCase Class

```
class TestingCase(private val testingApi: TestingApi) {

    fun get(): Single<Person> {
       return testingApi.get().map{
         makePerson(it)
       }
   }
}
```

So, I will call UseCase class from ViewModel class of Android.
I'm trying to write UnitTest for UseCase class so I have to mock API here. 
As far as I know, I've to prepare the json data of Person data class and create a Single<Person>,,,etc
Is this possible to mock API ( MockApolloClient??) in Apollo Client Android?
Thank you

**Comment by hoangfuda** [comment]
@sav007 Can you have a look at this issue?

**Comment by sav007** [comment]
Why can't you make `TestingApi#get` to return mocked versions of `Response<PersonQuery.Data>`? Why do you need to mock the whole Apollo client? 

BTW you can enable `generateModelBuilder` apollo plugin configuration to generate builders for models, that will make it easier to create mocked response.

**Comment by hoangfuda** [comment]
> Why can't you make TestingApi#get to return mocked versions of Response<PersonQuery.Data>? Why do you need to mock the whole Apollo client?

Because when I mock UseCase class. I have to pass TestingApi as parameter inside.
In that case, in order to mock TestingApi , the class ApolloClient and Rx2Apollo must be mocked ( initialized). It is not possible !

As you mention `generateModelBuilder` I found it in this issue https://github.com/apollographql/apollo-android/issues/677
Do you have some sample about it ?

**Comment by astamato** [comment]
Sorry, what was the solution to this? I have the exact same doubt, essentially, im testing a method that goes like this: 

```
 return Rx2Apollo.from(apolloClient.query(call)).map { moreCode() }
```

I want to verify that moreCode() processes correctly the response, but dont know how to test `apolloClient.query(call)` and Ive tried a good many things.

**Comment by pdesh-acorns** [comment]
Bump, would be helpful to know the solution

**Comment by Abdelsattar** [comment]
Hey @sav007 
I'm having a problem now mocking the returned response of query as @astamato 
can you provide us an example? 
I will try to write a medium article after writing the test if it's not already exist 

current problem is when I'm trying to build the resposne as 
` val expectedResponse = Response<MyQuery.Data>(
            Response.Builder<MyQuery.Data>
        )`

<img width="363" alt="Screenshot 2021-08-11 at 15 58 32" src="https://user-images.githubusercontent.com/9407394/129042429-b7fa97d2-aedf-4a67-a0e7-988f6df72cad.png">

how I can solve this?
