### ISSUE TITLE
Non-null fragment value returned as nullable when using inline fragments

### ISSUE THREAD

**Issue by gaucidaniel** [apollographql/apollo-android#1145]
Using the following query, the fragment's value `...fragment().characterDetails()` is being returned as nullable.

```js
query getCharacterDetails {
    ...CharacterDetails
}

fragment CharacterDetails on Character {
    id
    name
    ... on Droid {
        droidType
    }
}

interface Character
type Droid implements Character
```

This only happens when the inline fragment `... on Droid` is used in the `CharacterDetails` fragment. Removing this returns a non-null value, as expected.

On our iOS codebase, Apollo is not generating the fragment result as nullable (thus, adhering to the schema), however on Android, Apollo is returning a nullable value for the above scenario.

What could be the cause of this, am I missing something or could it be an Apollo client bug?

**Comment by sav007** [comment]
I guess this is an issue with the way how we generate the code. But I need more info.

Not sure that provided sample query is valid. Could you please attach generate IR.json file for this query (can be located at generated source folder `/build/generated/source/apollo/generatedIR`)

**Comment by gaucidaniel** [comment]
Here's the revised query that fully replicates this issue, along with the generated IR.

    query GetDroids {
        droids {
           ...DroidFull
        }
    }

    fragment DroidFull on Droid {
        id
        name
        description
        image
        ... on ProtocolDroid {
            languagesSpoken
        }
        ... on BattleDroid {
            battlesWon
        }
    }

    # Generated IR

    {
        "operations": [
            {
                "filePath": "../GetDroids.graphql",
                "operationName": "GetDroids",
                "operationType": "query",
                "rootType": "Query",
                "variables": [],
                "source": "query GetDroids {\n  droids {\n    __typename\n    ...DroidFull\n  }\n}",
                "fields": [
                    {
                        "responseName": "droids",
                        "fieldName": "droids",
                        "type": "[Droid!]",
                        "isConditional": false,
                        "isDeprecated": false,
                        "deprecationReason": null,
                        "fields": [
                            {
                                "responseName": "__typename",
                                "fieldName": "__typename",
                                "type": "String!",
                                "isConditional": false
                            }
                        ],
                        "fragmentSpreads": [
                            "DroidFull"
                        ],
                        "inlineFragments": []
                    }
                ],
                "fragmentSpreads": [],
                "inlineFragments": [],
                "fragmentsReferenced": [
                    "DroidFull"
                ],
                "sourceWithFragments": "query GetDroids {\n  droids {\n    __typename\n    ...DroidFull\n  }\n}\nfragment DroidFull on Droid {\n  __typename\n  id\n  name\n  description\n  image\n  ... on ProtocolDroid {\n    languagesSpoken\n  }\n  ... on BattleDroid {\n    battlesWon\n  }\n}",
                "operationId": "80231ff654d27a276e62ed54b72c2d4e463d2b6222cd92b152f6718701b50bb9"
            }
        ],
        "fragments": [
            {
                "typeCondition": "Droid",
                "possibleTypes": [
                    "ProtocolDroid",
                    "BattleDroid"
                ],
                "fragmentName": "DroidFull",
                "filePath": "../fragments.graphql",
                "source": "fragment DroidFull on Droid {\n  __typename\n  id\n  name\n  description\n  image\n  ... on ProtocolDroid {\n    languagesSpoken\n  }\n  ... on BattleDroid {\n    battlesWon\n  }\n}",
                "fields": [
                    {
                        "responseName": "__typename",
                        "fieldName": "__typename",
                        "type": "String!",
                        "isConditional": false
                    },
                    {
                        "responseName": "id",
                        "fieldName": "id",
                        "type": "ID!",
                        "isConditional": false,
                        "isDeprecated": false,
                        "deprecationReason": null
                    },
                    {
                        "responseName": "name",
                        "fieldName": "name",
                        "type": "String!",
                        "isConditional": false,
                        "isDeprecated": false,
                        "deprecationReason": null
                    },
                    {
                        "responseName": "description",
                        "fieldName": "description",
                        "type": "String!",
                        "isConditional": false,
                        "isDeprecated": false,
                        "deprecationReason": null
                    },
                    {
                        "responseName": "image",
                        "fieldName": "image",
                        "type": "URL!",
                        "isConditional": false,
                        "isDeprecated": false,
                        "deprecationReason": null
                    }
                ],
                "fragmentSpreads": [],
                "inlineFragments": [
                    {
                        "typeCondition": "ProtocolDroid",
                        "possibleTypes": [
                            "ProtocolDroid"
                        ],
                        "fields": [
                            {
                                "responseName": "__typename",
                                "fieldName": "__typename",
                                "type": "String!",
                                "isConditional": false
                            },
                            {
                                "responseName": "id",
                                "fieldName": "id",
                                "type": "ID!",
                                "isConditional": false,
                                "isDeprecated": false,
                                "deprecationReason": null
                            },
                            {
                                "responseName": "name",
                                "fieldName": "name",
                                "type": "String!",
                                "isConditional": false,
                                "isDeprecated": false,
                                "deprecationReason": null
                            },
                            {
                                "responseName": "description",
                                "fieldName": "description",
                                "type": "String!",
                                "isConditional": false,
                                "isDeprecated": false,
                                "deprecationReason": null
                            },
                            {
                                "responseName": "image",
                                "fieldName": "image",
                                "type": "URL!",
                                "isConditional": false,
                                "isDeprecated": false,
                                "deprecationReason": null
                            },
                            {
                                "responseName": "languagesSpoken",
                                "fieldName": "languagesSpoken",
                                "type": "Int!",
                                "isConditional": false,
                                "isDeprecated": false,
                                "deprecationReason": null
                            }
                        ],
                        "fragmentSpreads": []
                    },
                    {
                        "typeCondition": "BattleDroid",
                        "possibleTypes": [
                            "BattleDroid"
                        ],
                        "fields": [
                            {
                                "responseName": "__typename",
                                "fieldName": "__typename",
                                "type": "String!",
                                "isConditional": false
                            },
                            {
                                "responseName": "id",
                                "fieldName": "id",
                                "type": "ID!",
                                "isConditional": false,
                                "isDeprecated": false,
                                "deprecationReason": null
                            },
                            {
                                "responseName": "name",
                                "fieldName": "name",
                                "type": "String!",
                                "isConditional": false,
                                "isDeprecated": false,
                                "deprecationReason": null
                            },
                            {
                                "responseName": "description",
                                "fieldName": "description",
                                "type": "String!",
                                "isConditional": false,
                                "isDeprecated": false,
                                "deprecationReason": null
                            },
                            {
                                "responseName": "image",
                                "fieldName": "image",
                                "type": "URL!",
                                "isConditional": false,
                                "isDeprecated": false,
                                "deprecationReason": null
                            },
                            {
                                "responseName": "battlesWon",
                                "fieldName": "battlesWon",
                                "type": "Int!",
                                "isConditional": false,
                                "isDeprecated": false,
                                "deprecationReason": null
                            }
                        ],
                        "fragmentSpreads": []
                    }
                ]
            }
        ],
        "typesUsed": [
            {
                "kind": "ScalarType",
                "name": "URL",
                "description": ""
            }
        ]
    }

**Comment by sav007** [comment]
Sorry for the delay.

So this PR introduced fragments that have inline fragments to be always optional https://github.com/apollographql/apollo-android/pull/899

but after this PR https://github.com/apollographql/apollo-android/pull/971 it doesn't make any sense as we always generate base class for inline fragment.

So I can assume we can remove this condition [`inlineFragments.isNotEmpty()`](https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/SchemaTypeSpecBuilder.kt#L169)
