### ISSUE TITLE
How to upload a file?

### ISSUE THREAD

**Issue by zzwdream** [apollographql/apollo-android#1149]

**Comment by sav007** [comment]
https://graphql.github.io/learn/

> GraphQL is a query language for your API, and a server-side runtime for executing queries by using a type system you define for your data

Use raw http request to upload files.

**Comment by Dragons0458** [comment]
Sorry to reopen the thread, but then do you recommend not using GraphQL to handle file uploads? How would you handle uploading a file that has data as a description attached?

Example:

Upload a file and a text that describes what the file is for.

Would you upload the file with a HTTP RAW request and the description of the file as a GraphQL request? Or would you upload file and text as RAW? Thank you!

**Comment by dengxiang** [comment]
apollo-server support upload file and there are JS implementation Client support using GraphQL to upload file.
https://github.com/jaydenseric/graphql-multipart-request-spec
https://github.com/jaydenseric/apollo-upload-client

I wish apollo-android support this feature.

**Comment by trumpets** [comment]
Exactly! @sav007 I believe you are dismissing these requests to eagerly, Apollo itself supports file uploads: https://blog.apollographql.com/file-uploads-with-apollo-server-2-0-5db2f3f60675 We just need to get the Android lib in parity.

**Comment by digitalbuddha** [comment]
Pr welcome 🙂

**Comment by trumpets** [comment]
Someone already linked their implementation in another issue which was abruptly closed: https://github.com/apollographql/apollo-android/issues/640#issuecomment-435693636

**Comment by tongzou** [comment]
I would love to see this implemented.

**Comment by hanmant83** [comment]
Hello
I have to send file with message please suggest right code

**Comment by Dragons0458** [comment]
I hope this serves as something, success!
`try {
           val fileToUpload = File(path)

           val requestBody = MultipartBody.Builder().setType(MultipartBody.FORM).also {
                                    addFormDataPart("operations", "{\"query\": \"mutation x(\$id: Int!, \$file: Upload!) { x( id: \$id, file: \$file ) { id, path } }\", \"variables\": { \"id\": 1,\"file\": null } }")
           
                                    addFormDataPart("map", "{ \"0\": [\"variables.file\"] }")           
           
                                    addFormDataPart(
                                                                   "0",
                                                                   fileToUpload.name,
                                                                   RequestBody.create(MediaType.parse("image/jpg"), fileToUpload)
                                     )
           }

            val request = Request.Builder()
                    .url(serverURL)
                    .post(requestBody)
                    .build()

            okHttpClient.newCall(request).enqueue(object : Callback {

                override fun onFailure(call: Call, e: IOException) {
                    e.printStackTrace()
                }

                @Throws(IOException::class)
                override fun onResponse(call: Call, response: Response) {
                    if (response.isSuccessful) {
                        println("OK")
                    } else {
                        println(response.body())
                    }
                }
            })
        } catch (ex: Exception) {
            ex.printStackTrace()
        }`
