### ISSUE TITLE
Generated classes not nested

### ISSUE THREAD

**Issue by kcrimi** [apollographql/apollo-android#1152]
In your example for consuming code you write
```
for (FeedQuery.Data.Feed feed : dataResponse.data().feed()) {
...
```

For some reason, my generated code does not nest according to the schema structure. For example, instead of `FeedQuery.Data.Feed`, I would only see `FeedQuery.Data` and `FeedQuery.Feed`.

This is generally fine and might even be a feature in order to reduce the amount of code for using the types further down the query tree. However, it causes some weirdness with queries that return derived types.

**Example**
For my query below, I get the `CourseListQuery` parent class interface of `Teacher` is implemented by `Teacher1`, used in `ComposedCourseListByType` and `Teacher2`, which is used in `UserCourse` even though these 2 classes are identical. 

I would think if the classes were nested similar to your example, this wouldn't happen since the classes would be named spaced correctly.
```
query CourseList {
    viewer {
        composedCourseListByType(type: CONTINUE_WATCHING, exclude: [SAVED_COURSES]){
            teacher {
                name
                smallPictureUrl
            }
            ...on UserCourse{
                totalLessonsDurationInSeconds
                totalLessonsProgressInSeconds
            }
        }
    }
}
```

Is there a way to enable/disable the nesting of the classes? Is this an expected behavior?

**Comment by sav007** [comment]
That was the initial intention to flatten the class structure as it easily to get out of hand the nesting, on real project I had 10-15 nested layers of classes.

**Comment by kcrimi** [comment]
Thanks @sav007 . Just to confirm, it's expected and acceptable that I'll have duplicate classes (eg `Teacher1`, `Teacher2`) for types that are within the same class that has derived types?
