### ISSUE TITLE
Cannot import fragment from other file.

### ISSUE THREAD

**Issue by yazumoto** [apollographql/apollo-android#1157]
I read some articles that says using `#import "./file-name.gql` in graphql file, can import fragment from other file.

But apollo-android cannot import fragment from other file with this statements.

Is this a bug? Or is there any other way to import fragment from other file?

**Comment by sav007** [comment]
We currently don't support importing graphql fragments from files.

**Comment by vikrama** [comment]
Do you suggest any good work around for this? 

We have (supposedly) a fragment that is repeated among several of our mutations and queries. Should we merge all those in one gql file so that we have only one fragment's generated Entity class?

**Comment by sav007** [comment]
You can reference fragment from another file without importing it.
