### ISSUE TITLE
Change annotation dependency scope to provided 

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#116]
Currently we are packaging in the annotation dependencies which conflict with Espresso. This is an issue tracking the change from compile to provided

**Comment by digitalbuddha** [comment]
Maybe I'm being silly but I couldn't find `provided` in java only projects as a dependency type.  I had to go with `compileOnly` https://blog.gradle.org/introducing-compile-only-dependencies  
"In the Gradle model we consider tests to be a “consumer” of the production code. With this in mind, compile-only dependencies are not inherited by the test classpath. The intention is that tests, like any other runtime environment, should provide their own implementation, either in the form of mocks or some other dependency."

I think this should work

**Comment by felipecsl** [comment]
yeah compileOnly is the same as provided AFAIK

**Comment by sav007** [comment]
@digitalbuddha is this ticket still valid?

**Comment by digitalbuddha** [comment]
not sure will check

**Comment by marwanad** [comment]
I think it's fine keeping them with a compile scope. 

In theory, any `androidTestCompile` dependency can bring in a dependency with a version that conflicts with one of the dependencies we package in apollo.
 
So it's better to leave it to the user to fix through:

```
androidTestCompile ('.....'){
    exclude module: '...'
}
```

**Comment by sav007** [comment]
is it still valid?

**Comment by jaredsburrows** [comment]
Is this still a problem? @digitalbuddha You closed your own PR.

**Comment by digitalbuddha** [comment]
Not sure tbh. I never was able to get CI to pass after changing scope. Feel free to take a look at it.
