### ISSUE TITLE
How to get response data if http code is not 200?

### ISSUE THREAD

**Issue by Spinnner** [apollographql/apollo-android#1166]
I'm trying to sign up a user on the server. If user's data is not valid I get http code 422: Unprocessible Entity,  and in this case I cannot get any response details. I use standard way to make a call:
```
.enqueue(object : ApolloCall.Callback<CreateUserMutation.Data>() {
                        override fun onFailure(e: ApolloException) {
                        }

                        override fun onResponse(response: Response<CreateUserMutation.Data>) {
                        }
```
And after this I'm in the onFailure block. ApolloException contains only http code description. But I want to see error details in a full response, that I can see via the Postman:
```
{
    "data": {
        "signUp": {
            "result": {
                "approval": false,
                "errors": [
                    {
                        "field": "email",
                        "locale": "en",
                        "message": "Email \"spinn1256@gmail.com\" already exists in the database."
                    },
                    {
                        "field": "phone",
                        "locale": "en",
                        "message": "Tel. number is incorrect."
                    }
                ]
            }
        }
    }
}
```

**Comment by digitalbuddha** [comment]
Look for com.apollographql.apollo.ApolloCall.Callback#onHttpError you can override in your callback but you have to close response manually then e.rawResponse().close()

**Comment by Spinnner** [comment]
> Look for com.apollographql.apollo.ApolloCall.Callback#onHttpError you can override in your callback but you have to close response manually then e.rawResponse().close()

I've checked rawResponse...It contains networkResponse object, but body = null. Cannot see any data from server((
