### ISSUE TITLE
Proper way to  update from version 0.5.0 to version v1.0.0-alpha4 

### ISSUE THREAD

**Issue by roni-castro** [apollographql/apollo-android#1174]
When I try to upgrade to version v1.0.0-alpha4, it breaks hundreds of lines of my code, as it fixes mapping GraphQl Int type to Java int type instead of Long(#901 ). Is there a way to update it without breaking most of my models that have Long type?
I am trying to update to this version to get the `SqlNormalizedCacheFactory` class, as it is not present in version 0.5.0.

**Comment by sav007** [comment]
Unfortunately no, sorry but before stable 1.0 release we can't guarantee backward compatibility. You have to migrate.
