### ISSUE TITLE
Example of how to cache a request with params using NormalizedCache

### ISSUE THREAD

**Issue by roni-castro** [apollographql/apollo-android#1176]
How to cache a query whose response and params are objects and do not have any id?
I have lost a lot of time trying to cache it and I still don't understand how `LruNormalizedCache` cache works and how to make it works.

Is there a sample of using cache whose query have some params or any docs explaining how the cache logic works?

My stackoverflow question: https://stackoverflow.com/questions/54137559/cache-a-whole-query-in-apollo-android

**Comment by martinbonnin** [comment]
Hi @roni-castro ! Sorry for the super late response ! Does https://www.apollographql.com/docs/android/essentials/normalized-cache/ help?

**Comment by moshkit** [comment]
I have faced with similar problems.
If you wil not provide CacheKeyResolver, cahe key will be generated. I think t happens somewhere [here](https://github.com/apollographql/apollo-android/blob/96d53ba7ec479e4e2c05dcc456e74031985f0bb6/apollo-normalized-cache/src/commonMain/kotlin/com/apollographql/apollo/cache/normalized/internal/RealCacheKeyBuilder.kt)

The generated key looks like this:
descriptions({"limit":"1","where":{"cooktime":{"_gte":null,"_lte":null},"devices":{"device_id":{"_eq":null}},"energy":{"_gte":null,"_lte":null},"state":{"_eq":"available"},"translatable_fields":{"locale":{"_eq":"ru"}},"vendor_id":{"_in":[1]}}})

**Comment by martinbonnin** [comment]
Hi 👋 . 

> How to cache a query whose response and params are objects and do not have any id?

In general, if your objects don't have an `id`, you cannot deduplicate your data (See [this blog post](https://www.apollographql.com/blog/apollo-client/caching/demystifying-cache-normalization/) for a high level overview of normalization and deduplication).

Even if your data is not deduplicated, it should still be cached using the path to your object as a cache key. For more information, you can also read [the documentation about Apollo Android normalized cache](https://www.apollographql.com/docs/android/v3/caching/introduction/). Especially, Apollo Android 3 now has a declarative cache that makes it easier to define your cache key without using a `CacheKeyResolver`.

I'm going to close this issue. Feel free to open a new one if needed.
