### ISSUE TITLE
how to use apollo-gradle-plugin from maven

### ISSUE THREAD

**Issue by raulvillalbamedina** [apollographql/apollo-android#1178]
In my project we use maven and i cannot execute this plugin

**Comment by sav007** [comment]
We don't have maven plugin, only gradle. The only way I see is to call the compiler manually from some script

**Comment by raulvillalbamedina** [comment]
What os the Command to compile?

**Comment by Sparow199** [comment]
@raulvillalbamedina 
I merged the pending PRs from the main project and i update the plugin to last version of Apollo GraphQL compiler. In my projects, the plugin work only with flat queries (no fragments).

[Apollo-client-maven-plugin](https://github.com/Sparow199/apollo-client-maven-plugin)

**Comment by Sparow199** [comment]
Hi @sav007,
What kind of documentation that you need ? i can help with a PR.
I have an only the [Readme](https://github.com/Sparow199/apollo-client-maven-plugin/blob/master/README.md) file at the moment.

**Comment by SundaresanGanapathy** [comment]
> @raulvillalbamedina
> I merged the pending PRs from the main project and i update the plugin to last version of Apollo GraphQL compiler.
> 
> [Apollo-client-maven-plugin](https://github.com/Sparow199/apollo-client-maven-plugin)

can you give me the steps to generate maven artifact from this github fork?

**Comment by nata7che** [comment]
Any updates on this? Is there a solution one can use when working with Maven?

**Comment by aoudiamoncef** [comment]
Hi @nata7che

Look at [spring-boot-mvc-apollo-graphql](https://github.com/aoudiamoncef/spring-boot-mvc-apollo-graphql).

After, you have to continue with Apollo android documentation in order to setup ApolloClient and configure your Okhttp instance...etc

**Comment by martinbonnin** [comment]
Closing this one as it is now served by https://github.com/aoudiamoncef/apollo-client-maven-plugin
