### ISSUE TITLE
Allow manual code generation (not with every build)

### ISSUE THREAD

**Issue by davidvavra** [apollographql/apollo-android#1180]
Generating Apollo classes with every build is not necessary for us - it slows down the build. We would like to generate the classes only when .graphql files are changed and then put generated classes directly into the src folder, not to the gen folder. What I'm looking for is an option to disable the gradle plugin for every build - running it only via some maunal gradle command. It also needs an option for a path where to generate the classes.

**Comment by digitalbuddha** [comment]
Hi David. Simplest way is to exclude the apollo task from your build. Gradle has an api to disable tasks. Then when you want to run apollo you can manually run the apollo gradle task. I'm away from computer and don't remember exact gradle flag, might be - xTaskName

**Comment by davidvavra** [comment]
@digitalbuddha Yes that's possible, but it was a lot of plumbing to do this. Imho the library could make this easier. This is what I did, might be useful to others:

I added this code to root `build.gradle.kts`:

```
val apolloEnabled: String? by project

task("manualApollo") {
    dependsOn(":ourSubprojectWithApollo:generateApolloClasses")
    doLast {
        ant.withGroovyBuilder {
            "move"("file" to "$buildDir/../ourSubprojectWithApollo/build/generated/source/apollo/classes", "todir" to "$buildDir/../ourSubprojectWithApollo/src/main/java")
        }
        println("Apollo classes generated")
    }
}

subprojects {
    // Apollo generation is disabled by default to speed up build
    // If .graphql files change, run './gradlew manualApollo -PapolloEnabled=true'
    if (apolloEnabled == null) {
        tasks.whenTaskAdded(Action<Task> {
            if (this.name.contains("Apollo")) {
                this.enabled = false
            }
        })
    }
}
```

When our .graphql files change, we run `./gradlew manualApollo -PapolloEnabled=true`

**Comment by sav007** [comment]
Apollo plugin doesn't generate models with every build, only if it's a clean build or one of graphql file changed. Are you sure that for you it trigger code generation for every build? It might be an issue then, but the plugin definitely support up-to-date feature.

**Comment by tasomaniac** [comment]
When switching branches, you need to generate the code since the already generated code may not be up to date and that may cause compilation issues. I would say this issue is working as intended.

**Comment by martinbonnin** [comment]
The new [codegen not using npm](https://github.com/apollographql/apollo-android/pull/1482) should  make things faster. 

@davidvavra How long do you spend generating classes ? In the grand scheme of android apps, this time should be an order of magnitude less that dexing or just downloading the Android SDKs and gradle dependencies. If that's not the case, it should definitely be optimized.

**Comment by davidvavra** [comment]
@martinbonnin The code generation is not too bad. The main reason I workarounded it was the 'npm' - it has its own issues on different systems/configurations and build wasn't easily portable. When codegen without npm is released, I will probably switch back to code generation every time.

**Comment by sav007** [comment]
Please try latest version with a new code generation engine https://github.com/apollographql/apollo-android/releases/tag/1.1.0

If you see the same issue pls reopen.
