### ISSUE TITLE
Know when a subscription is connected

### ISSUE THREAD

**Issue by kgeckhart** [apollographql/apollo-android#1188]
When trying to use this library for testing purposes I am trying to wait for the subscription to be connected. I have not found a way to accomplish this task so far. I believe the missing piece is updating ApolloSubscriptionCall to expose something like OnConnected. I noticed that OnTerminated was added recently (https://github.com/apollographql/apollo-android/pull/1175) and I was wondering if it would be possible to do something similar for OnConnected. Given the PR for OnTerminated was rather light I would be willing to do the work if it's something people feel is valuable.

**Comment by sav007** [comment]
Sure seems like nice to have.
