### ISSUE TITLE
ApolloHttpCache only accepts a DiskCache

### ISSUE THREAD

**Issue by bpollock-vida** [apollographql/apollo-android#1189]
I want an in-memory LruCache like the options provided for normalized cache, but the only thing that implements HttpCacheStore is DiskLruHttpCacheStore.

**Comment by sav007** [comment]
Not sure that it wise to keep raw response in the memory. Are you sure about this, concern that it will require one big chunk of memory?

**Comment by bpollock-vida** [comment]
I guess its storing more than the < 30 lines of json text? If not, that doesn't seem too much.

The normalized cache has an in-memory option, why is this different?

**Comment by bpollock-vida** [comment]
I see, but the normalized cache also seems to fall back upon query-based caching. While also supporting a in-memory only cache. Won't that have the same issue?

**Comment by sav007** [comment]
No as for normalized cache it stores as a Map rather than big one continues chunk in mem.
