### ISSUE TITLE
Retry GraphQL Query using Rx emitting IllegalStateException "Already Executed"

### ISSUE THREAD

**Issue by SeanBeckman** [apollographql/apollo-android#1192]
Apologies for opening a similar issue to:
https://github.com/apollographql/apollo-android/issues/963#issuecomment-457033536
But the issue was closed without an answer that was making sense to me.

I have a wrapper class around the client which gives me observables without having to call Rx2Apollo everywhere:
```
val call = apolloClient
            .query(query)
            .httpCachePolicy(cachePolicy)
            .responseFetcher(fetcher)
        return Rx2Apollo
            .from(
                call.clone()
            )
```

One of the consumers wants to retry a query if the result is some type.
It would be better if it was a subscription, but it is what it is.

```
graphqlClient
    .query(SomeQuery)
    .flatMap {
        if (it.data() is PendingResult) {
            Observable.error(RetryException)
        } else {
            Observable.just(it.data())
        }
    }
    .retryWhen {
        it.flatMap {
            if (it is RetryException) {
                Observable.just(it)
            } else {
                Observable.error(it)
            }
    }
```

As you can see in the wrapper I am calling clone on the Call object but I am still getting the exception and I don't see how it will have any effect anyway, as we only call the method once to get a stream. Rx's retry operator is responsible for resubscribing  and thus the same Call class is used.

**Comment by SeanBeckman** [comment]
I see how Rx2Apollo is working now, I copied the code and replaced with mine:

```return Observable.create<Response<T>> { emitter ->
            val callClone = call.clone()
            emitter.setDisposable(getRx2Disposable(callClone))
            callClone.enqueue(object : ApolloCall.Callback<T>() {
                override fun onResponse(response: Response<T>) {
                    if (!emitter.isDisposed) {
                        emitter.onNext(response)
                    }
                }

                override fun onFailure(e: ApolloException) {
                    Exceptions.throwIfFatal(e)
                    if (!emitter.isDisposed) {
                        emitter.onError(e)
                    }
                }

                override fun onStatusEvent(event: ApolloCall.StatusEvent) {
                    if (event == ApolloCall.StatusEvent.COMPLETED && !emitter.isDisposed) {
                        emitter.onComplete()
                    }
                }
            })
        }```

Now each time a subscription is made it clones the call as you suggested but now I am getting a different exception:

> Caused by: com.apollographql.apollo.exception.ApolloNetworkException: Failed to execute http call
	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onFailure(ApolloServerInterceptor.java:91)

**Comment by sav007** [comment]
I think the last error tells you what is the issue:
Caused by: java.net.SocketTimeoutException: Read timed out

**Comment by SeanBeckman** [comment]
Yeah I figured that, just not sure why it throws Already Executed without the clone, and socket timeout with the clone.

**Comment by SeanBeckman** [comment]
Yeah, I just thought about that this weekend. It's probably mock web server, yes it is a unit test. I was too distracted thinking it was something Apollo was caching. I was making a PR with some example code on your repo, will pause that for now and investigate my original test.

**Comment by SeanBeckman** [comment]
Yeah it was mock web server, I mistakingly was enqueueing one less response than the retry amount. Getting another issue but I can probably massage this to green. Clone works fine as intended, though I would like convenient method for emitting to an observable with cloning call every subscription so that I don't have to copy that Rx2Apollo method, but it's fine for now.

Thanks for the prompt responses and help.

**Comment by congdanh1608** [comment]
Change:
`Rx2Apollo
            .from(
                call.clone()
            )
            `

to

`Observable.defer { Rx2Apollo.from(queryCall.clone()) }`

It works. Because Rx2Apollo does not trigger the onStatusEvent with the StatusEvent.COMPLETE.
