### ISSUE TITLE
A list of requirements for cached responses in readme

### ISSUE THREAD

**Issue by JacquesSmuts** [apollographql/apollo-android#1194]
I think it would be a good idea if we can get a list of requirements in the sql normalized Cached responses readme section, or perhaps inside the CacheKey object.

Some example requirements which requires feedback:
- The top level response to any query must have a resolved CacheKey.fromId(), otherwise the caching will default to query-based caching.
- any object that resolves to CacheKey.NO_KEY cannot be referenced from other objects. This may reduce normalization efficiency and increase the db-size.

If these seem like sensible requirements and we can't think of others, I'll add them with a PR.

**Comment by martinbonnin** [comment]
Hi @JacquesSmuts 👋 Sorry for the huuuge delay! Normalized cache **is** a complex topic and any documentation about it is welcome! 

> • The top level response to any query must have a resolved CacheKey.fromId(), otherwise the caching will default to query-based caching.
> • any object that resolves to CacheKey.NO_KEY cannot be referenced from other objects. This may reduce normalization efficiency and increase the db-size.

This sounds like the same constraints ultimately? The top level field being an object like the others, if it has no id, it cannot be reused? Or did you mean something else?

**Comment by JacquesSmuts** [comment]
Yeah it does look like the same thing, being said in two different ways.

I'm sorry, I haven't worked with Apollo's cached responses in 2 years, so I cannot remember what I meant here. Please feel free to close this issue.

**Comment by martinbonnin** [comment]
Sounds good 👍 . As a heads up, we just released the first alpha of Apollo Android 3. If you (or someone reading this) ever bumps into this again, I'd recommend checking `@typePolicy` and `@fieldPolicy`directives that can do most of these verifications at compile time.
