### ISSUE TITLE
Couldn't get response headers

### ISSUE THREAD

**Issue by TarasMel** [apollographql/apollo-android#1195]
Hi have little problem, i need get some items from Response Header, can you tell me how i can get it...
Our API gives response.body() with some data, and JWT are in headers, but i can't get it.
Any suggestions on how I might do this?
Thanks

**Comment by sav007** [comment]
Unfortunately we don't have such feature. Is there any reason why token can't be returned as a part of GraphQL response

**Comment by TarasMel** [comment]
Omly one reason - secure. Token put in response header in Cookie

**Comment by TarasMel** [comment]
Hi, I solved this problem through OkHttpClient.addInterseptor, where you can gat response.headers() and take any information, in my case Set-Cookie.
Thank you

**Comment by mineshpatel1511** [comment]
@TarasMel Can you please give an example of how to add an Interceptor to get response headers. I have done a similar thing to add and remove request headers but not for response.
