### ISSUE TITLE
Allow queries and mutations over websocket

### ISSUE THREAD

**Issue by jaregier** [apollographql/apollo-android#1197]
Right now, queries and mutations must be made using a normal HTTP request.  However, it seems that other Apollo clients have the functionality to perform queries and mutations over a websocket.  For example:

iOS: https://github.com/apollographql/apollo-ios/pull/220
Browser: https://github.com/apollographql/subscriptions-transport-ws#full-websocket-transport

The reasoning behind why this would be valuable is that in scenarios where there is already an open websocket (an active subscription, for example), we can just reuse the open websocket instead of opening a new connection to the server.

**Comment by sav007** [comment]
Are you referring to Subscriptions feature? Apollo Android has subscriptions support

**Comment by jaregier** [comment]
I'm aware Apollo has subscription support, but this would be to also allow queries and mutations over the same websocket as subscriptions.  As far as I'm aware, queries and mutations are only supported using HTTP right now.

**Comment by arendjr** [comment]
The lack of this feature is a deal-breaker for us too, as WebSocket connections have implicit state provided by the connection params, without which our queries and mutations simply don't work.

**Comment by lucasmontano** [comment]
that's a very important feature! is anyone looking to implement this?

**Comment by sav007** [comment]
Just to give the update on this feature request. This is definitely is non trivial as it requires to refactor the our network layer to make it working with HTTP and WebSocket transport layer.

I can start working on it, but again it's a big feature request.

**Comment by designatednerd** [comment]
👋 iOS maintainer here - One thing to keep in mind is that on the iOS side, `SplitNetworkTransport` still sends all queries and mutations via HTTP, not the web Socket. It basically looks at the type and then decides whether to use the WebSocket or not. Having everything send directly through the WebSocket is indeed somewhat more difficult. 

Is the concern more having a single interface that can be used for both subscriptions and queries/mutations, or is it specifically sending the mutations and queries over the web socket?

**Comment by arendjr** [comment]
> Is the concern more having a single interface that can be used for both subscriptions and queries/mutations, or is it specifically sending the mutations and queries over the web socket?

At least in our case, it is specifically required for everything to be sent over the web socket. This is because the connection has state associated based on the connection parameters that were specified when the connection was set up. The API is designed to take advantage of this, and queries/mutations that get sent outside of the connection wouldn't work because of this.

**Comment by nikartm** [comment]
Hi, I really need this feature too. This, unfortunately, prevents us from using this excellent library.

**Comment by nikartm** [comment]
@sav007 Hi, is there any hope that this feature will be available soon?

**Comment by sav007** [comment]
Not really sure it will be available soon, as it requires quite a lot of changes to the runtime, there are so many parts that very closely coupled to plain OkHttp request / response.

cc @martinbonnin @tasomaniac

**Comment by nokite** [comment]
@sav007 are there any plans to address this in the near future?
We're still interested in using Apollo, but this issue severely limits what we can do with it.
Cheers!

**Comment by sav007** [comment]
Hey, it's not officially released or promoted yet but I guess you can try a new `apollo-runtime-kotlin` module. Unfortunately new runtime doesn't have any caching yet (neither http nor normalized, work still in progress).

So with new runtime you can set network layer up with `ApolloWebSocketNetworkTransport`. 
See  https://github.com/apollographql/apollo-android/blob/master/apollo-runtime-kotlin/src/commonMain/kotlin/com/apollographql/apollo/ApolloClient.kt

and https://github.com/apollographql/apollo-android/blob/master/samples/multiplatform/kmp-lib-sample/src/commonMain/kotlin/com/apollographql/apollo/kmpsample/data/ApolloCoroutinesRepository.kt

for reference.

**Comment by dchappelle** [comment]
We need this functionality as well. I see that @sav007 comment was from last year... I take it's still not official because I have a recent version and this functionality is not in it. @sav007 is that still the most recent solution?

**Comment by sav007** [comment]
cc @martinbonnin  any updates regarding new 3.0 version?

**Comment by martinbonnin** [comment]
We're getting there... It's still missing a few bits and pieces but it's starting to be usable. You can try `com.apollographql.apollo3:apollo-runtime-kotlin:3.0.0-dev8`. APIs will most likely change but that might be good enough to investigate this.

**Comment by dchappelle** [comment]
Thanks @sav007 / @martinbonnin I'll give it a try

**Comment by martinbonnin** [comment]
@dchappelle is there any chance your server is publicly accessible? That'd be pretty cool to test against.

**Comment by dchappelle** [comment]
@martinbonnin our server is not currently publicly accessible but it also uses the graphql-ws protocol [issue 3029](https://github.com/apollographql/apollo-android/issues/3029) :)
I don't suppose you have any sample code showing how to use the websocket for query and mutation actions?

**Comment by martinbonnin** [comment]
> I don't suppose you have any sample code showing how to use the websocket for query and mutation actions?

Not really... It's a chicken and egg problem really. It's hard to test the client without a server and vice versa. Ideally we could use something like `MockWebServer` to integration test this without having to rely on a 3rd party server but I'm not sure how doable that is.

**Comment by dchappelle** [comment]
@martinbonnin it looks like 'apollo3' is to be used instead of 'apollo' in the class path e.g.,  com.apollographql.apollo3.api?
If so, I'm not sure how to get a version of the com.apollographql.apollo plugin that generates code to use it?

**Comment by martinbonnin** [comment]
You can use `com.apollographql.apollo3` as a plugin ID. We changed the package name to avoid any binary incompatibilities. See https://github.com/apollographql/apollo-android/issues/2879 for more details.

**Comment by dchappelle** [comment]
@martinbonnin - from Gradle...  _Plugin [id: 'com.apollographql.apollo3'] was not found in any of the following sources:_
Is there a certain version I need to use?

**Comment by martinbonnin** [comment]
Hi @dchappelle 👋 ! `generateKotlinModels` is not needed anymore since it's the default. More generally, there are a bunch of breaking changes in version 3 that don't have a migration guide yet as the API is changing too often. If you have more question about the dev previews, do you mind following up in the kotlinlang slack (channel [#apollo-android](https://app.slack.com/client/T09229ZC6/C01A6KM1SBZ/thread/C01A6KM1SBZ-1619451903.071800)) or [spectrum](https://spectrum.chat/apollo/apollo-android?tab=posts) if you prefer so we don't fill this issue with a lot of soon-to-be-obsolete comments and other things specific to `3.0.0-dev8` ?

**Comment by dchappelle** [comment]
> kotlinlang slack (channel #apollo-android)

Is this the link to sign up? https://surveys.jetbrains.com/s3/kotlin-slack-sign-up

**Comment by martinbonnin** [comment]
> Is this the link to sign up? https://surveys.jetbrains.com/s3/kotlin-slack-sign-up

Looks like it!

**Comment by dchappelle** [comment]
Sorry @martinbonnin (don't have access to kotlin slack yet)... I'm not seeing 'network' in this classpath?

import com.apollographql.apollo3.**network**.ws.ApolloWebSocketNetworkTransport

**Comment by dchappelle** [comment]
@martinbonnin last question... do I have to import 'apollo-runtime-kotlin' instead of 'apollo-runtime'? (I can't import them both due to duplicate definitions)

**Comment by erizoo** [comment]
@dchappelle Hi, Did you can to use the new apollo android protocol? graphql-transport-ws

I am faced with the problem that when connecting to the server I get 101 Switching Protocols Protocol Error


Could you help me to deal with this problem ?

**Comment by dchappelle** [comment]
@erizoo Hi, yes the graphql-transport-ws is working well for me. What version of Apollo-android are you using?

**Comment by martinbonnin** [comment]
`3.0.0-alpha01` has support for `graphql-ws` and can do queries/mutation over a websocket when using a `WebSocketNetworkTransport`. Simple example:

```kotlin
    val apolloClient = ApolloClient(
        networkTransport = WebSocketNetworkTransport(
            serverUrl = "http://localhost:9090/graphql",
            protocol = GraphQLWsProtocol()
        )
    )

    val response = apolloClient.query(HelloQuery())
```

See [GraphQLWsTest](https://github.com/apollographql/apollo-android/blob/f7caee8dfeef54d05e88a1fa1e6c7cac8552c2d8/composite/tests/websockets/src/commonTest/kotlin/GraphQLWsTest.kt#L17) for more details.

I'm closing this issue as it's working for simple cases. There might be other protocol or more advanced use cases, feel free to open new issues to discuss these.

**Comment by nokite** [comment]
Hi @martinbonnin , could you share what simple vs advanced use cases you had in mind? (or point me where to look) This would help us understand if we can use the library in our project, before we start experimenting.

**Comment by martinbonnin** [comment]
Hi 👋. As of today, I'm thinking of "simple" as what's in the [Integration Tests](https://github.com/apollographql/apollo-android/blob/f7caee8dfeef54d05e88a1fa1e6c7cac8552c2d8/composite/tests/websockets/src/commonTest/kotlin/GraphQLWsTest.kt#L17): using [graphql-ws](https://github.com/enisdenjo/graphql-ws) for either queries, mutation or subscriptions.

"Advanced" was for everything that's not in the radar yet so it's difficult to enumerate what's not a known quantity. The websocket backends seem more fragmented than the HTTP ones so there are possibilities for other use cases. I was thinking mainly other protocols than `graphql-ws` but maybe there are other things. I've seen use cases that required the caller to control the lifecycle of the WebSocket, closing it at some specific times for an example, I'm not 100% how that would work. But as long as you stick with `graphql-ws` and queries/mutations/subscriptions, you should be fine. If you already have a backend publicly available, I'm happy to test it see how that works.
