### ISSUE TITLE
Android apollo client GET method request.

### ISSUE THREAD

**Issue by mshaileshr** [apollographql/apollo-android#1204]
In interceptor, I have changed method call to GET like below.
Request.Builder builder = original.newBuilder().method(original.method(), null);
OR
Request.Builder builder = original.newBuilder().get();
but while debugging i found that the class RealInterceptorChain having below method requesting **POST** method.
@override public Response proceed(Request request) throws IOException {
return proceed(request, streamAllocation, httpCodec, connection);
}

I want to my request method should be **GET**

**Comment by mzolimpieff** [comment]
Is someone working on this? I just forked the code, my team need this feature, otherwise our backend cannot cache our requests. 
@stonestclair

**Comment by stonestclair** [comment]
Why was I mentioned?
@mzolimpieff

**Comment by mzolimpieff** [comment]
Sorry! wrong @. Just fixed

**Comment by digitalbuddha** [comment]
I don't believe anyone is working on it. Feel free to open pr if your team gets to a good implementation

**Comment by AndroideRob** [comment]
Any update on this feature?

**Comment by mzolimpieff** [comment]
@AndroideRob wip
