### ISSUE TITLE
CacheAndNetworkFetcher not propagating Network errors

### ISSUE THREAD

**Issue by julianomoraes** [apollographql/apollo-android#1207]
Hello,

We've noticed that `CacheAndNetworkFetcher` by design will not return network errors if the cached data was successfully returned.  I would guess the intention was to silent fail when the cache data is available. 
However, it does not cover the use case where we want to show an error to the user in the UI.

Is there any strong opinions about this? 
I would suggest to change it from:
```
// Only send the network result after the cache result has been dispatched
      if (dispatchedCacheResult) {
        if (networkResponse.isPresent()) {
          originalCallback.onResponse(networkResponse.get());
          originalCallback.onCompleted();
        } else if (networkException.isPresent()) {
          if (cacheException.isPresent()) {
            // Both cache and network errored out
            originalCallback.onFailure(networkException.get());
          } else {
            // Cache was successful. Just terminate.
            originalCallback.onCompleted();
          }
        }
      }
```

to 

```
// Only send the network result after the cache result has been dispatched
      if (dispatchedCacheResult) {
        if (networkResponse.isPresent()) {
          originalCallback.onResponse(networkResponse.get());
          originalCallback.onCompleted();
        } else if (networkException.isPresent()) {
            originalCallback.onFailure(networkException.get());
        }
      }
```

With this approach it is up to the UI to ignore and fail silent if it desires.

Before I send out a PR wanted to check the reasoning behind this logic.

BTW, on iOS ApolloClient all cache errors are swallowed, and any network error is propagated.
Perhaps it is a good idea to keep a consistency and make it more flexible.

**Comment by sav007** [comment]
Not really sure why it was implemented in this way. Seems like proposed changes make totally sense so please go ahead with PR.

**Comment by DanteNguyen1008** [comment]
Hi guys, I am having problem with receive Network exception by calling query with CacheAndNetworkFetcher and Coroutine. Do you have any way to catch the exception after the coroutine call was finished?
