### ISSUE TITLE
parsing fails for null data field in com.apollographql.apollo.response.OperationResponseParser 

### ISSUE THREAD

**Issue by gshcherb** [apollographql/apollo-android#1215]
According to https://facebook.github.io/graphql/draft/#sec-Data

null data value is a valid value and can be present in the response. Current implementation of `OperationResponseParser` just takes null value and treats it as valid map with data.

This later causes a crash in 

`com.apollographql.apollo.response.OperationResponseParser.parse` when null is queried for data.

**Comment by sav007** [comment]
PR was merged.
