### ISSUE TITLE
how to get AsUserProfile

### ISSUE THREAD

**Issue by JavohirYakubov** [apollographql/apollo-android#1218]
I have this query on GraphQL client:
`user {
      id
      roles

      profile {
        phone

          ...on UserProfile {
            firstName
            lastName`
I need firstname, lastName but not get when I write as this response.data().viewer().user().profile().; This my java code:
apolloClient.query(GetUserTypeQuery.builder().build()).enqueue(new` ApolloCall.Callback<GetUserTypeQuery.Data>()` {
                @Override
                public void onResponse(@NotNull Response<GetUserTypeQuery.Data> response) {
                }
                @Override
                public void onFailure(@NotNull ApolloException e) {
                }
            });

**Comment by sav007** [comment]
As this is inline fragment you need to cast profile to AsUserProfile

**Comment by sav007** [comment]
Closing.
