### ISSUE TITLE
Add multiple schema support

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#122]
The problem: user can have several GraphQL endpoints with different schemas. Right now gradle plugin is hardcoded to look only for one specific file `schema.json` in source folders. That makes impossible to define queries with different GraphQL schemas in one module. As workaround for now user should define new gradle submodule for each schema. 

Suggestion: update gradle plugin to resolve quires and corresponding schema file by hierarchy of folder structure. For example:
`src/main/graphql/com/github/schema.json`
`src/main/graphql/com/github/users/GetUsers.graphql`
`src/main/graphql/com/github/users/issues/GetUserIssues.graphql`
`src/main/graphql/com/linkedin/schema.json`
`src/main/graphql/com/linkedin/users/GetUsers.graphql`
`src/main/graphql/com/linkedin/users/posts/GetUserPosts.graphql`

When gradle plugin finds `schema.json` all `*.graphql` queries that placed in subpackages will be considered as queries defined against this schema, in our example: `com/github/users/GetUsers.graphql` and `com/github/users/issues/GetUserIssues.graphql` should be used with `com/github/schema.json`.

**Comment by marwanad** [comment]
@sav007 

How about the following flow? (Following up from #124)

Consider the variant "DemoDebug",

We start by the `src/demoDebug/graphql` sourceSet,  and check the path of every schema.json file found under `src/demoDebug/graphql`. If one was found say under `src/demoDebug/graphql/github` and not under `src/main/graphql/github`. We pick the one under `src/demoDebug/graphql/github` as our schema file (similar to how Gradle's sourceset resolution works).

All `.graphql` files under `src/demoDebug/graphql/github`, `src/debug/graphql/github`, `src/demo/graphql/github` and `src/main/graphql/github` will be passed to `apollo-codegen` to generate the IR.


If a schema file was found under the paren folder `src/demoDebug/graphql/`, then all `.graphql` files under its subdirectories (**including the `github` subdirectory**) will be passed to `apollo-codegen` to generate the IR in addition to the ones under `src/main/graphql`, `src/demo/graphql` and `src/debug/graphql`.

**Comment by sav007** [comment]
discussion continues in #124
