### ISSUE TITLE
How to add http query parameter

### ISSUE THREAD

**Issue by kuno** [apollographql/apollo-android#1223]
@digitalbuddha 

For some reason, we need to add special HTTP query parameters for each query/mutation. 
for example `https://example/graphql?type=SpeicalType`, here `SpecialType` is the parameter, and different query/mutation has different parameters.

I knew that We might be able to do this by Okhttp interceptor, but is there better approach?

**Comment by digitalbuddha** [comment]
Interceptor is the preferred approach. We have leaned away from reimplementing http spec. For example you want to add query param while someone wants to add header and someone else a post body
