### ISSUE TITLE
Coroutines, "Failed to resolve"

### ISSUE THREAD

**Issue by Dragons0458** [apollographql/apollo-android#1224]
Hello, I was trying to use the coroutines but when trying to use the implementation I get the following error: "ERROR: Failed to resolve: com.apollographql.apollo: apollo-coroutine-support: 1.0.0-alpha5" Any suggestions? It's the only one that does not work, thank you!

**Comment by Dragons0458** [comment]
ok, add this:

`maven {
        url  "https://dl.bintray.com/apollographql/android" 
    }`

Update README please, thank you! :D

**Comment by AdamMc331** [comment]
Saw this ticket was closed because you figured it out, but I'm adding a readme inside the coroutines module for this: https://github.com/apollographql/apollo-android/pull/1307
