### ISSUE TITLE
Add android sample with POJO converter usage

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#123]
Should be part of `apollo-sample` module, maybe as new build flavour

**Comment by martinbonnin** [comment]
what about re-using the existing sample app and making a listview with several configurations ?

* droid-moshi
* droid-pojo 
* ...

**Comment by sav007** [comment]
Yes sounds good, that what I had in mind

**Comment by sav007** [comment]
@martinbonnin Wait you mean use the same build flavour but different for example activities ?

**Comment by martinbonnin** [comment]
just one build flavour, 1 activity. This activity would have a ListView as its contentView. clicking the listview triggers the appropriate call and displays a popup.

**Comment by sav007** [comment]
Well but how you will setup 2 different config option for gradle plugin: one with `generateClasses` option enabled another without. Plus for moshi you need include dep to moshi lib but in case pojo you don't need moshi

**Comment by martinbonnin** [comment]
We could pull all the dependencies at once. But you're right, half of the sample is about configuring the gradle file so a separate module makes more sense.

**Comment by sav007** [comment]
Maybe it worth not as separate module but as separate Gradle  build flavor for sample module

**Comment by martinbonnin** [comment]
I'm actually not so sure about the build flavor. As an android developer, it took me a very long time to understand the flavors, sourceSets, etc (I'm actually not really sure I understand correctly now ;)). 
I believe most of android devs know very little about gradle, appart from adding repositories and dependencies so adding a separate module where they can just copy/paste the maybe it's easier.

**Comment by martinbonnin** [comment]
Also, we should explain what's the difference between pojo converters and moshi converters. I like the idea of having `one-- and preferably only one --obvious way to do it`. Asking devs to chose is making it more difficult to enter the project.

**Comment by digitalbuddha** [comment]
I vote for different gradle modules not seperate flavors if possible. It's how retrofit is setup. 

As for moshi vs pojo converter: Some android apps including me at NYTimes and Felipe at airbnb use code generated models through autovalue. The current setup allows those who want an east setup to use the auto generated models while people at larger companies to stick with current policies and use autovalue for model gen.

**Comment by martinbonnin** [comment]
Is this ticket still needed with https://github.com/apollographql/apollo-android/commit/08e2556d0b6843d657e1754eb2428846326e464e ?

**Comment by sav007** [comment]
This ticket is not valid anymore, as sample has been changed to use POJO by default
