### ISSUE TITLE
Gradle Plugin Resolution Changes

### ISSUE THREAD

**Issue by marwanad** [apollographql/apollo-android#124]
This is mainly to document the `schema` and `.graphql` files lookup and open discussions to fit use cases.

## SourceSet Extensions

Currently we support users providing their own schema and graphql paths and those would be respected as long as they don't conflict.

For instance,

```
android {
sourceSets {
  debug {
   graphql {
   graphQLPath = "x"
   schemaFile = "y"
  }
  }
 }
}

```

## Current  Behaviour

If a user provide those two config options for a SOURCESET **AND** they don't provide a conflicting for another sourceSet that is shared by a variant. Those two will be respected and only files under graphQLPath and schemaFile will be used to generate the IR. 

If, on the other hand they also provide those two config options for the `main` sourceSet for example, we throw an exception because it kinda doesn't make sense for that. For instance, that would be an example for a conflicting configuration
```
android {
sourceSets {
  debug {
   graphql {
   graphQLPath = "x"
   schemaFile = "y"
  }
  main {
   graphql {
   graphQLPath = "z"
   schemaFile = "y"
  }
  }
 }
}
```

Regarding flavours (cc: @digitalbuddha) and if no extension options were specified.

Consider the following
```
 project.android {
      compileSdkVersion 25
      buildToolsVersion "25.0.2"
      productFlavors {
        demo {
          applicationIdSuffix ".demo"
          versionNameSuffix "-demo"
        }
        full {
          applicationIdSuffix ".full"
          versionNameSuffix "-full"
        }
      }
    }
```

The tasks added by apollo plugin will be `generatedApolloIRDemoDebug`, `generatedApolloIRDemoRelease`, `generatedApolloIRFullDebug`, `generatedApolloIRFullRelease`

Consider the demo flavour, it will the following sourceSets
```
src/demoDebug/ (build variant source set)
src/debug/ (build type source set)
src/demo/ (product flavor source set)
src/main/ (main source set)
```
If **no config options** were specified, we do the resolution in a way that's similar to the Gradle lookup mechanism.
So, if we are running `generateApolloDemoDebug`, if a schema file exists under `src/demoDebug/graphql/`, it uses that file and passes it all `.graphql` files found under all the **sourceSets** (the four mentioned above). If not it keeps looking in the other sourceSet directories. We also pick the schemaFile in a style similar to the Gradle resolution. Ie. pick the one from `demoDebug` in that case regardless of the existence of others in the other variant sourceSets.

**Comment by sav007** [comment]
```
graphQLPath = "x"
   schemaFile = "y"
```
Are these config options for gradle plugin? 

I thought we trying to find schema and queries under `src/flavour/graphql/` folder?
And do we need these configs can't we just resolve everything by files lookup? 
I'm not big fan of too much configuration, right now we have config flag to enable pojo generation, then we are going to have custom type mapping, now these

**Comment by sav007** [comment]
Probably this #122 issue is dup

**Comment by marwanad** [comment]
#122 is kinda different because there's still work to do for multiple schemas (or work towards a flow that fits all use-cases with the least config options)

> Are these config options for gradle plugin?

Yes, the source set extensions are configurable through the plugin.

> I thought we trying to find schema and queries under src/flavour/graphql/ folder?

It is tricky in that sense because the tasks that generate IR and classes from schemas are **per variant** not per source set. Variants have multiple folders.

> do we need these configs can't we just resolve everything by files lookup?

If the user doesn't provide those configs, we just do the lookup ourselves
```
If no config options were specified, we do the resolution in a way 
that's similar to the Gradle lookup mechanism.
So, if we are running generateApolloDemoDebug, 
if a schema file exists under src/demoDebug/graphql/, it uses that file 
and passes it all .graphql files found under 
all the sourceSets (the four mentioned above). If not it keeps looking in the other 
sourceSet directories.
```

These flags exist to provide extra extensibility (say, if the user wants to limit the graphql files attached to a sourceSet vs including everything under that sourceSet folder, etc) but they're not needed at all.

**Comment by sav007** [comment]
Merging #122 to this one:

sav007:
> The problem: user can have several GraphQL endpoints with different schemas. Right now gradle plugin is hardcoded to look only for one specific file schema.json in source folders. That makes impossible to define queries with different GraphQL schemas in one module. As workaround for now user should define new gradle submodule for each schema.
>
> Suggestion: update gradle plugin to resolve quires and corresponding schema file by hierarchy of folder structure. For example:
src/main/graphql/com/github/schema.json
src/main/graphql/com/github/users/GetUsers.graphql
src/main/graphql/com/github/users/issues/GetUserIssues.graphql
src/main/graphql/com/linkedin/schema.json
src/main/graphql/com/linkedin/users/GetUsers.graphql
src/main/graphql/com/linkedin/users/posts/GetUserPosts.graphql
>
>When gradle plugin finds schema.json all *.graphql queries that placed in subpackages will be considered as queries defined against this schema, in our example: com/github/users/GetUsers.graphql and com/github/users/issues/GetUserIssues.graphql should be used with com/github/schema.json.

marwanad:

>How about the following flow? (Following up from #124)
>
>Consider the variant "DemoDebug",
>
>We start by the src/demoDebug/graphql sourceSet, and check the path of every schema.json file found under src/demoDebug/graphql. If one was found say under src/demoDebug/graphql/github and not under src/main/graphql/github. We pick the one under src/demoDebug/graphql/github as our schema file (similar to how Gradle's sourceset resolution works).
>
>All .graphql files under src/demoDebug/graphql/github, src/debug/graphql/github, src/demo/graphql/github and src/main/graphql/github will be passed to apollo-codegen to generate the IR.
>
>If a schema file was found under the paren folder src/demoDebug/graphql/, then all .graphql files under its subdirectories (including the github subdirectory) will be passed to apollo-codegen to generate the IR in addition to the ones under src/main/graphql, src/demo/graphql and src/debug/graphql.

**Comment by marwanad** [comment]
I'll start working on this.
