### ISSUE TITLE
Implementing Cursor based pagination in Android

### ISSUE THREAD

**Issue by burf2000** [apollographql/apollo-android#1240]
Is there any examples of the Android Apollo client implementing Cursor based pagination for something like a recycleview?  

I have implemented it on the server, and added to my query but what do I need to do next so it will do the polling to get all the other records.

Use the standard Apollo client

**Comment by sav007** [comment]
pagination query is the regular query except it has additional argument to get next or previous page for the cursor. For example:
this is paginated query https://github.com/Shopify/mobile-buy-sdk-android/blob/master/MobileBuy/sample/src/xApollo/graphql/com/shopify/sample/domain/CollectionProductPage.graphql

this is usage
https://github.com/Shopify/mobile-buy-sdk-android/blob/master/MobileBuy/sample/src/xApollo/java/com/shopify/sample/domain/usecases/FetchProductsUseCaseImpl.java#L38

**Comment by vikas115m** [comment]
@sav007 : I think the links are not working could you please post working links :)
