### ISSUE TITLE
Publish gradle plugin

### ISSUE THREAD

**Issue by simPod** [apollographql/apollo-android#1244]
Hi, it would be nice if gradle plugin was available from https://plugins.gradle.org

See https://plugins.gradle.org/docs/submit

**Comment by robcolburn** [comment]
Closed by #1790 ?

https://plugins.gradle.org/plugin/com.apollographql.apollo

**Comment by martinbonnin** [comment]
Not yet, sorry. You won't find 1.2.2 on the gradle portal yet. This was reverted in https://github.com/apollographql/apollo-android/pull/1813, I'll enable it again in 1.3.x.

**Comment by martinbonnin** [comment]
Closed with https://github.com/apollographql/apollo-android/pull/1932
