### ISSUE TITLE
ApolloSubscriptionException Failed to parse server message

### ISSUE THREAD

**Issue by sudansh** [apollographql/apollo-android#1245]
I am getting the following error on a subscription. It was working fine before, but started giving the following error suddenly
`Caused by: com.apollographql.apollo.internal.subscription.ApolloSubscriptionException: Failed to parse server message`

I have tried using stable, alpha and snapshot versions of the library. But same error in all.

Subscription is working fine. I have checked in ios app and also in web.

Stacktrace: 
Caused by: com.apollographql.apollo.internal.subscription.ApolloSubscriptionException: Failed to parse server message
W/System.err:     at com.apollographql.apollo.internal.subscription.RealSubscriptionManager.onOperationDataServerMessage(RealSubscriptionManager.java:321)
W/System.err:     at com.apollographql.apollo.internal.subscription.RealSubscriptionManager.onOperationServerMessage(RealSubscriptionManager.java:234)
W/System.err:     at com.apollographql.apollo.internal.subscription.RealSubscriptionManager$SubscriptionTransportCallback$3.run(RealSubscriptionManager.java:448)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
W/System.err: Caused by: java.lang.NullPointerException: corrupted response reader, expected non null value for __typename
W/System.err:     at com.apollographql.apollo.internal.response.RealResponseReader.checkValue(RealResponseReader.java:264)
W/System.err:     at com.apollographql.apollo.internal.response.RealResponseReader.readString(RealResponseReader.java:45)

**Comment by sav007** [comment]
I guess the response has changed:
>Caused by: java.lang.NullPointerException: corrupted response reader, expected non null value for __typename
