### ISSUE TITLE
enqueue() works fine on emulator, but not on actual device.

### ISSUE THREAD

**Issue by stonestclair** [apollographql/apollo-android#1246]
I'm come across an issue when the app tries to enqueue a query on a physical device. `apolloClient.query(query).enqueue(new ApolloCall.Callback<GetUserDataQuery.Data>() {...`

There's no error ever thrown, the problem is that it takes about 3 minutes before it finally sends the request to the server.
This only happens on the phone itself, the request is sent instantly on an emulator.

**Comment by stonestclair** [comment]
Just figured out that it's because Apollo is having a problem with subdomains.
If I send the query to the live server (with an A Record), it works fine: 
`https://www.myserver.com/query`
However, when it's sent to a subdomain (with a CNAME record), it takes multiple minutes: 
`https://dev.myserver.com/query`

**Comment by sav007** [comment]
Not sure that this is related to the Apollo client itself, it uses regular OkHttp client and doesn't have own network stack. So it might be your infrastructure issues
