### ISSUE TITLE
Apollo + Dagger code generation order

### ISSUE THREAD

**Issue by tir38** [apollographql/apollo-android#1260]
I'm starting to use Apollo and I can successfully create and use an `ApolloClient`. I'm also using Dagger to supply dependencies. I started off by creating ApolloClient inside a wrapper class:

```
public class GraphWrapper {

    private final ApolloClient apolloClient;

    public GraphWrapper() {
        String baseUrl = "https://....";
        apolloClient = ApolloClient.builder()
                .serverUrl(baseUrl)
                .build();
    }
}
```

```
@Module
public class ApiModule {

    @Provides
    @Singleton
    GraphWrapper provideGraphWrapper() {
        return new GraphWrapper();
    }
    ...
}
```
Everything compiles fine. However I now want to supply ApolloClient via D.I.:

```
import com.apollographql.apollo.ApolloClient;

public class GraphWrapper {

    private final ApolloClient apolloClient;

    public GraphWrapper(ApolloClient apolloClient) {
        this.apolloClient = apolloClient;
    }
}
```

```
@Module
public class ApiModule {

    @Provides
    @Singleton
    GraphWrapper provideGraphWrapper(ApolloClient apolloClient) {
        return new GraphWrapper(apolloClient);
    }
    
    @Provides
    @Singleton
    ApolloClient provideApolloClient() {
        String baseUrl = "https://....";
        return ApolloClient.builder()
                .serverUrl(baseUrl)
                .build();
    }
}
```

When I try to compile this code I see the following error.

```
...

  location: package com.example.di
/Users/Example/MyApplication.java:15: error: cannot find symbol
import com.example.di.DaggerAppComponent;
                                       ^
  symbol:   class DaggerAppComponent
  location: package com.example.di
error: cannot access ApolloClient
  class file for com.apollographql.apollo.ApolloClient not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.apollographql.apollo.ApolloClient not found
```

Is it possible that Dagger is doing it's code generation *before* Apollo is doing its code generation?

(I know this is similar to issue https://github.com/apollographql/apollo-android/issues/1255 but it's not entirely the same.

**Comment by digitalbuddha** [comment]
ApolloClient is not part of the codegen but the run-time. Maybe you are missing a dependency?

**Comment by AlbertVilaCalvo** [comment]
You may need to add the Apollo dependency explicitly to any module that has a Dagger component that uses `ApolloClient`, or alternatively set the Apollo library as `api` instead of `implementation` so that other gradle modules see `ApolloClient`.

Search for a `import com.apollographql.apollo.ApolloClient` and you'll see which Dagger components use it. That module needs to have access to Apollo.
