### ISSUE TITLE
marshaller compile errors with array types

### ISSUE THREAD

**Issue by shasti421** [apollographql/apollo-android#1262]
For array types, below code is generated
   ```
    public @Nullable List<Result> results() {
      return this.results;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeInt($responseFields[1], totalCount);
          writer.writeList($responseFields[2], results, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((Result) item).marshaller());
              }
            }
          });
        }
      };
    }
   ```
Above fails to compile as ResponseWriter.ListWriter().write expects first argument as Object, but the generated code has List as the first argument. 

I had to manually adjust the code as shown below to get going
  ``` 
   public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeInt($responseFields[1], totalCount);
          writer.writeList($responseFields[2], results, new ResponseWriter.ListWriter() {
            @Override
             public void write(Object obj, ResponseWriter.ListItemWriter listItemWriter) {
              List items = (List) obj;
              for (Object item : items) {
                listItemWriter.writeObject(((Result) item).marshaller());
              }
            }
          });
        }
      };
    }
  ```

**Comment by martygeek** [comment]
I'm running 1.0.0-alpha5 and am also getting an error in the same place. My error message, 
however, is :
     <query> is not abstract and does not provide override method write(Object, ListItemWriter)

If I try to edit the file and implement write() as studio suggests the signature has changed to:
   public void write(@javax.annotation.Nullable Object value, @Nonull ResponseWriter.ListItemWriter listItemwriter)

Where as it was  
    public void write(List items, ResponseWriter.ListItemWriter listItemWriter)

**Comment by shasti421** [comment]
> I'm running 1.0.0-alpha5 and am also getting an error in the same place. My error message,
> however, is :
> is not abstract and does not provide override method write(Object, ListItemWriter)
> 
> If I try to edit the file and implement write() as studio suggests the signature has changed to:
> public void write(@javax.annotation.Nullable Object value, @nonull ResponseWriter.ListItemWriter listItemwriter)
> 
> Where as it was
> public void write(List items, ResponseWriter.ListItemWriter listItemWriter)

@martygeek, It's the same error I am seeing. The studio suggested fix for you is the same as mine except that I didn't add annotations.

**Comment by martygeek** [comment]
I don't see a suggested fix in this thread. Do you have a link?

**Comment by shasti421** [comment]
> I don't see a suggested fix in this thread. Do you have a link?

See my second snippet in my original post. I updated the generated code of ResponseWriter.ListWriter() implementation to
   
          @Override
           public void write(Object obj, ResponseWriter.ListItemWriter listItemWriter) { //Change arg type to Object
            List items = (List) obj;    //Change
            for (Object item : items) {
              listItemWriter.writeObject(((Result) item).marshaller());
            }
          }
  
With the above manual change, I was able to run my client code successfully.

**Comment by martygeek** [comment]
That's a generated file in my project - it will regenerate upon build

**Comment by shasti421** [comment]
> That's a generated file in my project - it will regenerate upon build

Yes, it's a hack till underlying code generator is fixed.

**Comment by sav007** [comment]
I'm confused, as https://github.com/apollographql/apollo-android/blob/master/apollo-api/src/main/java/com/apollographql/apollo/api/ResponseWriter.java#L26
first argument is a list

Could you check what version of `apollo-api` dependency

**Comment by shasti421** [comment]
Moving to the latest API version fixed the issue

**Comment by martygeek** [comment]
I just pulled down v1.0.0 and am seeing the same error in the generated Java files:

<anonymous GetCountriesQuery$Data$1$1> is not abstract and does not override abstract method write(Object,ListItemWriter) in ListWriter
          writer.writeList($responseFields[0], countries, new ResponseWriter.ListWriter() {
