### ISSUE TITLE
java.io.IOException: Unable to delete file

### ISSUE THREAD

**Issue by devharis** [apollographql/apollo-android#1263]
Version: `1.0.0-alpha5`

OS: `Windows 10`

Everytime I try to compile my app, I get this error (see image) due to `:app:installApolloCodegen` trying to delete `package.json`. 

![image](https://user-images.githubusercontent.com/3015506/56675452-61128800-66bc-11e9-95cc-7bf302a492b0.png)

How do I prevent this from happening? It happens constantly. Current work-around is to manually delete it in file explorer. Then try to rerun compilation.

**Comment by sav007** [comment]
Is it windows OS?

**Comment by altairmizuchi** [comment]
Hello! I have the same issue on Windows

**Comment by devharis** [comment]
@sav007 Sorry for late response. Yes its Windows specific.
Any clue?

**Comment by sav007** [comment]
It might be some issues with the access right, we saw this in the past for Windows OS

**Comment by altairmizuchi** [comment]
I do not think this is a permissions problem. I tried to grant full access to all users and it didn't help while rebuild did the thing

**Comment by devharis** [comment]
I agree, grant permission isn't a sufficient solution. I gave the folder and subfolders full access and still this issue occurs.

**Comment by Orillion360** [comment]
I have the same issue. If i run `Build -> Rebuild Project` it seems to properly clean it, but this is not a nice work around.

**Comment by Orillion360** [comment]
A better workaround that I have found is to use the global version of `apollo-codegen`. You can simply install it with:
```
$ npm install -g apollo-codegen@0.19.1
```
as it says in the docs and then create a `gradle.properties` file in your home folder usually `C:\Users\<USERNAME>\.gradle\` with the line:
```
systemProp.apollographql.useGlobalApolloCodegen=true
```
This way it will not attempt to delete the file constantly, but you can still put the project in version control. Your non-windows team mates will not have the need to install apollo-codegen globally (assuming this problem only exists on Windows)

**Comment by sav007** [comment]
We might get a fix of this issue via https://github.com/apollographql/apollo-android/pull/1338

**Comment by devharis** [comment]
I think we can close this, I don't see the issue occurring after upgrading to 1.0.0.

**Comment by mesargent** [comment]
Having the same issue. Using 'com.apollographql.apollo:apollo-runtime:1.0.0', on Windows 10 with Android studio 3.4.1. Have read/write access to file. Clean doesn't work.

**Comment by Vishalratnam** [comment]
@mesargent did you find a fix for this? I have the same problem!

**Comment by mesargent** [comment]
> @mesargent did you find a fix for this? I have the same problem!

I switched to: 'com.apollographql.apollo:apollo-runtime:1.0.2-SNAPSHOT' instead of 1.0.0, seemed to fix the problem

**Comment by Vishalratnam** [comment]
Umm.. I'm using this API for the first time and I'm referring the docs at [(https://aws-amplify.github.io/docs/android/start?ref=amplify-android-btn)] (the Amplify framework docs). There is no specific dependency included in the docs. Is there somewhere else I have to change the version? Or can I add is as a new dependency?

**Comment by mesargent** [comment]
Just add implement com.apollographql.apollo:apollo-runtime:1.0.2-SNAPSHOT to your dependencies, remove the earlier one.

**Comment by Vishalratnam** [comment]
@mesargent thanks man..It works for me!

**Comment by philip978** [comment]
I solved such problem by commenting out all json related code and running my code to work on other file extension like ".txt" and it worked perfectly so i came to delete the json file and it was deleted without ecountering any errors after that i uncommented all  json related codes and runned it again and it worked.
You can private message me on my account for any assitance.Adios!!!
