### ISSUE TITLE
Gradle v5 deprecations

### ISSUE THREAD

**Issue by MarcBernstein** [apollographql/apollo-android#1271]
After updating to Android Studio 3.4 (and thus Gradle v5.1.1), some new deprecation notices show up in the build. These deprecations will be removed in Gradle v6.0, and will need to be resolved by then.

Repro steps:
1. Create a new Android app via Android Studio 3.4
1. Add apollo-android 1.0.0-alpha5 to the app
1. Run `./gradlew help --scan`
1. View the generated report on gradle.com
    * An example report is here (not sure how long they keep them up): https://scans.gradle.com/s/id2ke3xby26xm/deprecations

```
1. The DefaultSourceDirectorySet constructor has been deprecated.
  This is scheduled to be removed in Gradle 6.0.
  Please use the ObjectFactory service to create instances of SourceDirectorySet instead.
```
**DefaultSourceDirectorySet** usage location
* https://github.com/apollographql/apollo-android/blob/706db8d/apollo-gradle-plugin/src/main/java/com/apollographql/apollo/gradle/GraphQLSourceDirectorySet.java#L17

```
2. The ProjectLayout.directoryProperty() method has been deprecated.
  This is scheduled to be removed in Gradle 6.0.
  Please use the ObjectFactory.directoryProperty() method instead.
```
**ProjectLayout.directoryProperty()** usage locations
* https://github.com/apollographql/apollo-android/blob/706db8d/apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloClassGenerationTask.groovy#L28
* https://github.com/apollographql/apollo-android/blob/706db8d/apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloSystemCodegenGenerationTask.groovy#L16

```
3. Using method ObjectFactory.property() method to create a property of type Map<K, V> has been deprecated.
  This will fail with an error in Gradle 6.0.
  Please use the ObjectFactory.mapProperty() method instead.
```
**ObjectFactory.property() for a Map** usage locations
* https://github.com/apollographql/apollo-android/blob/706db8d/apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloClassGenerationTask.groovy#L17
* https://github.com/apollographql/apollo-android/blob/706db8d/apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloExtension.groovy#L45

**Comment by martinbonnin** [comment]
This should be fixed with https://github.com/apollographql/apollo-android/pull/1476

**Comment by sav007** [comment]
Closing.
