### ISSUE TITLE
Consolidate Kotlin sample data calls?

### ISSUE THREAD

**Issue by AdamMc331** [apollographql/apollo-android#1277]
I was looking at the kotlin sample module, and I noticed that there are three activities and all pull them a different way:

- CommitsActivity uses co-routines
- MainActivity uses an apollo callback
- RepositoryDetail uses RxJava

As a new person looking at the sample, this can be confusing and not really clear what the "best practice" is. I was wondering if we could:

1. Refactor to one consistent option
2. Pull this flow out into a `GitHubRepository` interface, and then have three implementations like `ApolloRxJavaService`, `ApolloCoroutinesService`, `ApolloCallbackService` and people can see those three individually, rather than a mixed bag. 

I'm happy to contribute either, but I wanted to ask here first if the three options were intentional - because if that is what we want to show people I would refactor in a way to ensure that happens.

**Comment by digitalbuddha** [comment]
It was not intentional. Your suggestions sound great, feel free to open a pr with a refactor.

**Comment by AdamMc331** [comment]
Will do!

**Comment by AdamMc331** [comment]
PR: https://github.com/apollographql/apollo-android/pull/1302
