### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by gmrandom** [apollographql/apollo-android#1285]
Hi folks,

We are in dire need of the code that was introduced in #1234 ; setting per-request headers with apollo-android currently means instantiating a new okhttp client for every request, which is very expensive.

Any idea when the next release will be out? Would it be possible to get an alpha6 soon?

Thanks for all your hard work, it is really appreciated!

**Comment by gmrandom** [comment]
Ping. Any update on the next release?

**Comment by sav007** [comment]
Will try to release over this weekends.

**Comment by adimit** [comment]
Anything we can do to help? :slightly_smiling_face:

**Comment by sav007** [comment]
Done
