### ISSUE TITLE
com.apollographql.apollo.exception.ApolloNetworkException: Subscription failed

### ISSUE THREAD

**Issue by Akshshr** [apollographql/apollo-android#1289]
### seeing **java.io.EOFException** **Subscription failed** onFailure callback. Any reason why this might be happening?

Here is the query

`subscription easeeSubscription ($chargerId: String){
    evChargerState(chargerId: $chargerId){
        id
        name
        shortName
        lastSeen
        isAlive
        imgUrl
        state{
            isCharging
        }
        schedule{
        isSupported
        isEnabled
        isSuspended
        localTimeTo
        }
        settings{
            maxChargePower
            permanentCableLock
        }
        backgroundStyle
        mainScreen{
            siteTitle
            title
            description
            imgUrl
            startChargingButton{
                text
                enabled
                icon
                backgroundColor
            }
            startChargingAlert{
                imgUrl
                title
                description
                okText
                cancelText
            }
            lockButton{
                text
                enabled
                icon
                backgroundColor
            }
            lockButtonAlert{
                imgUrl
                title
                description
                okText
                cancelText
            }
            consumptionText
            consumptionUnitText
            energyCostUnitText
            settingsButton{
                text
                enabled
                backgroundColor
            }
        }
        settingsScreen{
            siteTitle
            description
            scheduleTitle
            scheduleDisableAlert{
                title
                description
                disableText
                suspendText
                cancelText
            }
            scheduleSuspendedText
            hourTitle
            maxChargePowerTitle
            permanentCableLockTitle
            maxChargePowerRates{
                values
                unit
            }
            loadBalanceMainFuseTitle
            loadBalanceMainFuseEnabled
            energyDealCallToAction{
                text
                url
                redirectUrlStartsWith
                link
            }
        }
    }
}`

### Version:
`    ext.apolloReleaseVersion = '1.0.0-alpha2'
`

### Stacktrace:
`stackTrace = {StackTraceElement[7]@8261} 
 0 = {StackTraceElement@8270} "com.apollographql.apollo.internal.RealApolloSubscriptionCall$SubscriptionManagerCallback.onNetworkError(RealApolloSubscriptionCall.java:154)"
  declaringClass = "com.apollographql.apollo.internal.RealApolloSubscriptionCall$SubscriptionManagerCallback"
  fileName = "RealApolloSubscriptionCall.java"
  lineNumber = 154
  methodName = "onNetworkError"
  shadow$_klass_ = {Class@4148} "class java.lang.StackTraceElement"
  shadow$_monitor_ = -2094783150
 1 = {StackTraceElement@8271} "com.apollographql.apollo.internal.subscription.RealSubscriptionManager$SubscriptionRecord.notifyOnNetworkError(RealSubscriptionManager.java:339)"
  declaringClass = "com.apollographql.apollo.internal.subscription.RealSubscriptionManager$SubscriptionRecord"
  fileName = "RealSubscriptionManager.java"
  lineNumber = 339
  methodName = "notifyOnNetworkError"
  shadow$_klass_ = {Class@4148} "class java.lang.StackTraceElement"
  shadow$_monitor_ = -1993404381
 2 = {StackTraceElement@8272} "com.apollographql.apollo.internal.subscription.RealSubscriptionManager.onTransportFailure(RealSubscriptionManager.java:180)"
  declaringClass = "com.apollographql.apollo.internal.subscription.RealSubscriptionManager"
  fileName = "RealSubscriptionManager.java"
  lineNumber = 180
  methodName = "onTransportFailure"
  shadow$_klass_ = {Class@4148} "class java.lang.StackTraceElement"
  shadow$_monitor_ = -1912162016
 3 = {StackTraceElement@8273} "com.apollographql.apollo.internal.subscription.RealSubscriptionManager$SubscriptionTransportCallback$2.run(RealSubscriptionManager.java:369)"
  declaringClass = "com.apollographql.apollo.internal.subscription.RealSubscriptionManager$SubscriptionTransportCallback$2"
  fileName = "RealSubscriptionManager.java"
  lineNumber = 369
  methodName = "run"
  shadow$_klass_ = {Class@4148} "class java.lang.StackTraceElement"
  shadow$_monitor_ = -2080062759
 4 = {StackTraceElement@8274} "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)"
  declaringClass = "java.util.concurrent.ThreadPoolExecutor"
  fileName = "ThreadPoolExecutor.java"
  lineNumber = 1162
  methodName = "runWorker"
  shadow$_klass_ = {Class@4148} "class java.lang.StackTraceElement"
  shadow$_monitor_ = -2042936162
 5 = {StackTraceElement@8275} "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)"
  declaringClass = "java.util.concurrent.ThreadPoolExecutor$Worker"
  fileName = "ThreadPoolExecutor.java"
  lineNumber = 636
  methodName = "run"
  shadow$_klass_ = {Class@4148} "class java.lang.StackTraceElement"
  shadow$_monitor_ = -2041017473
 6 = {StackTraceElement@8276} "java.lang.Thread.run(Thread.java:764)"
  declaringClass = "java.lang.Thread"
  fileName = "Thread.java"
  lineNumber = 764
  methodName = "run"
  shadow$_klass_ = {Class@4148} "class java.lang.StackTraceElement"
  shadow$_monitor_ = -2123479220`

<img width="1602" alt="Screen Shot 2019-05-06 at 3 18 06 PM" src="https://user-images.githubusercontent.com/11215286/57231503-eb42e080-701a-11e9-9f70-fdb06a31c33c.png">

**Comment by sav007** [comment]
The only I can say by looking into stacktrace is smth related to the network, not sure why but seems the connection has been interrupted.

**Comment by Akshshr** [comment]
Hmm @sav007 Any ideas to where you can point me, to help understand this better?

**Comment by SaurabhKukreja** [comment]
Did you resolve it ?

**Comment by andy85048** [comment]
I am also getting the same error.
Any ideas?

**Comment by sav007** [comment]
It seems it network issues, closing for now but feel free to reopen if it still valid issue.

**Comment by Akshshr** [comment]
Yup, this is very much an issue that persists. 
Any updated knowledge to help us understand this?

**Comment by 7Fab** [comment]
I have loads of crashes because of this, can we bump it? Can't surround everything with try and catch...

**Comment by bryanspitz** [comment]
I, too, am getting this. It happens exactly two minutes after connection, every time, regardless of how many successful events are received in that time. At least for me.

**Comment by bryanspitz** [comment]
It also seems to be unrelated to how frequently the server sends keepAlives. My server team has been fiddling with that, to no avail.
