### ISSUE TITLE
Enable full logging

### ISSUE THREAD

**Issue by tir38** [apollographql/apollo-android#1290]
I see that I can log some internal log statements w/ `Logger` interface and then pipe them to something like Timber.

```
apolloClient = ApolloClient.builder()
        .serverUrl(baseUrl)
        .logger((priority, message, t, args) -> Timber.tag("Apollo").d(message, args))
        .build();
````

But I'm only seeing a few logs like this:

```
Cache MISS for operation com.example.api.GetSomethingQuery@df79fb2
```

How can I log the full json response?

**Comment by sav007** [comment]
If you want to log the network calls just provide the custom OkHttpClient in ApolloClient builder with the logging network interceptor.

**Comment by itsandreramon** [comment]
How should this be done? I would like to include a dependency thats compatible with the OkHttp versions used by Apollo?

**Comment by Abdelsattar** [comment]
I made it like this 

`    implementation "com.squareup.okhttp3:logging-interceptor:4.9.0" `


     val logging = HttpLoggingInterceptor()
        logging.level = (HttpLoggingInterceptor.Level.BODY)
        checkNotNull(authStateManager) { "authStateManager can't be null" }
        return OkHttpClient.Builder()
            .addNetworkInterceptor { chain ->
                val request = chain.request().newBuilder()
                    .addHeader(
                        HEADER_AUTHORIZATION,
                        "$HEADER_AUTHORIZATION_BEARER ${accessToken}"
                    ).build()

                chain.proceed(request)
            }
            .addInterceptor(logging)
            .build()


`   return ApolloClient.builder()
            .serverUrl(BASE_GRAPHQL_URL)
            .okHttpClient(okHttpClient)
            .build()`
