### ISSUE TITLE
Incorrect generation of Kotlin enum classes with long name

### ISSUE THREAD

**Issue by alexxxdev** [apollographql/apollo-android#1296]
example
```Kotlin
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package ...

import kotlin.String

enum class DeliveryAddressStatusEnum(val rawValue: String) {

...
    companion object {
        fun safeValueOf(rawValue: String): DeliveryAddressStatusEnum = values().find { it.rawValue
                == rawValue } ?: UNKNOWN__
    }
}
```
:kaptGenerateStubsDebugKotlin FAILED: Expecting an element in line ```== rawValue } ?: UNKNOWN__```

For short class names, everything is generated correctly:
```Kotlin
companion object {
        fun safeValueOf(rawValue: String): TypeEnum = values().find { it.rawValue == rawValue
                } ?: UNKNOWN__
    }
```

**Comment by digitalbuddha** [comment]
Bad line wrapping thanks for reporting

**Comment by sav007** [comment]
Oh it seems the issue with the Kotlin poet, will check if it's true will open an issue.

**Comment by sav007** [comment]
Issue https://github.com/square/kotlinpoet/issues/695 has been created. Will try to fix it on our end.

**Comment by jayresta** [comment]
Hi- even on current master I am still seeing a variant of this issue for a generated Kotlin enum type which is exactly 45 characters long. The generated line wraps the { bracket after the values().find which causes a compile error.

  companion object {
    fun safeValueOf(rawValue: String): MyGeneratedTypeWhichIs45CharactersLong = values().find
        { it.rawValue == rawValue } ?: UNKNOWN__
  }
