### ISSUE TITLE
Failed to resolve: com.apollographql.apollo:apollo-coroutine-support:1.0.0

### ISSUE THREAD

**Issue by friederikewild** [apollographql/apollo-android#1298]
After updating to version `1.0.0` of all used apollo gradle statements (from previously using `1.0.0-alpha5`), I get the following on **`coroutine-support`**:

`ERROR: Failed to resolve: com.apollographql.apollo:apollo-coroutine-support:1.0.0`

Note, I have the proposed additional repository entry in place:
`maven { url "https://dl.bintray.com/apollographql/android" }`

**Comment by friederikewild** [comment]
Double checked the documentation and also tried adding repository `maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }` - but also doesn't resolve the error. I guess I'll keep the coroutine-support on `1.0.0-alpha5` for now and only update the rest of the implementations

**Comment by digitalbuddha** [comment]
@sav007 any idea?

**Comment by sav007** [comment]
Yeah not sure when but the artifact id was changed  try `apollo-coroutines-support` instead please (`coroutine` was changed to `coroutines`)

**Comment by friederikewild** [comment]
@sav007 Thanks for your swift reply. I can confirm that updating the artefact id worked and I was able to now fully use version 1.0 👍
