### ISSUE TITLE
Kotlin generated code using java.lang.Object

### ISSUE THREAD

**Issue by jbttn** [apollographql/apollo-android#1305]
I have a schema which has some dates.  I have the gradle plugin configured like this:

```
    apollo {
        generateKotlinModels true
        customTypeMapping = [
            "Date" : "java.util.Date"
        ]
    }
```

I would expect that the generated Kotlin code would use `java.util.Date`, but instead it generates using `java.lang.Object`.

The problem is that we have warnings as errors enabled on our project, so any reference to `java.lang.Object` fails the build with the error "`This class shouldn't be used in Kotlin. Use kotlin.Any instead.`".  This makes sense to me... what's the reason for using Object rather than Any?  It would be even better if it actually used the class defined in the custom type mapping.

**Comment by jbttn** [comment]
My mistake.  I just realized the mapping was incorrect.  In the schema we have "DateTime" defined rather than "Date".  Updating that changed the generated code to use `java.util.Date` as I expect.

I still think it is problematic to use `java.lang.Object` rather than `Kotlin.Any` though for the build issue I described.

**Comment by Belka1000867** [comment]
In which version this feature was added?

**Comment by martinbonnin** [comment]
@Belka1000867 #1309 should be in version `1.0.1` released in July 2019

**Comment by Belka1000867** [comment]
hm, strange, I have recently updated to 1.3.0 and still have the same warning
