### ISSUE TITLE
Coroutines support not on jcenter

### ISSUE THREAD

**Issue by BoD** [apollographql/apollo-android#1325]
Hi!

I am surprised to notice that adding this dependency doesn't work:
```
implementation "com.apollographql.apollo:apollo-coroutine-support:1.0.0"
```

and looking [at the repo](https://jcenter.bintray.com/com/apollographql/apollo/) you can see that indeed the artifact is not published.

Is that... normal?

**Comment by nzakharchenko** [comment]
@BoD but documentation actually says that you should add maven repo first:

```maven { 
    url "https://dl.bintray.com/apollographql/android" 
}```

https://github.com/apollographql/apollo-android/tree/master/apollo-coroutines-support#implementation

**Comment by BoD** [comment]
Thanks for replying. Indeed I didn't notice this doc. It would be great if this was indicated in the main README. 

But preferably this artefact should be with the rest of them - any reason why it's not?

**Comment by martinbonnin** [comment]
I would prefer pushing everything to mavenCentral. There's a ticket open for that: https://github.com/apollographql/apollo-android/issues/1130.

**Comment by martinbonnin** [comment]
@sav007 do you have an option to set in the bintray console to opt-in jcenter forwarding ? 

https://www.jfrog.com/confluence/display/BT/Central+Repositories#CentralRepositories-IncludingyourPackageinJCenter

**Comment by sav007** [comment]
There is still open ticket for bintray support, as promoting to jcenter is not working for the coroutines package somehow.

**Comment by martinbonnin** [comment]
Any update from bintray ? I just bumped to 1.0.2 and the problem is still there.

**Comment by bernardog** [comment]
As of today, gradle can't find it . This is what I have:

`maven { url "https://dl.bintray.com/apollographql/android" }
 maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }`

and

`implementation "com.apollographql.apollo:apollo-coroutines-support:1.0.1"`

**Comment by ovestoerholt** [comment]
Any progress on this? Or a workaround?

**Comment by martinbonnin** [comment]
The workaround is to use:

```
repositories {
  maven { url "https://dl.bintray.com/apollographql/android" }
}
dependencies {
  implementation "com.apollographql.apollo:apollo-coroutines-support:1.2.1"
}
`

The files should be there: 

https://dl.bintray.com/apollographql/android/com/apollographql/apollo/apollo-coroutines-support/1.2.1/

**Comment by martinbonnin** [comment]
`apollo-coroutines-support` is now on jcenter :)

https://jcenter.bintray.com/com/apollographql/apollo/apollo-coroutines-support/1.2.2/
