### ISSUE TITLE
A simple query not working when using Kotlin generation

### ISSUE THREAD

**Issue by BoD** [apollographql/apollo-android#1327]
When using Kotlin models (`generateKotlinModels = true`), I have this simple query (Github API) that doesn't work:
```
query userInfo {
    viewer {
        login
        name
        email
    }
}
```

Here's what sent:
```
{
	"operationName": "UserInfoQuery",
	"variables": {},
	"extensions": {
		"persistedQuery": {
			"version": 1,
			"sha256Hash": "02346c9b17d8c14210a44f13f04339ea5e5e87c16148a1a532c0987ec80b29c0"
		}
	},
	"query": "query userInfo {  viewer {    __typename    login    name    email  }}"
}
```

and here's the results:
```
{
	"errors": [{
		"message": "No operation named \"UserInfoQuery\""
	}]
}
```

If I revert back to Java models, the correct operationName is sent:
```
{
	"operationName": "userInfo",
	"variables": {},
	"extensions": {
		"persistedQuery": {
			"version": 1,
			"sha256Hash": "02346c9b17d8c14210a44f13f04339ea5e5e87c16148a1a532c0987ec80b29c0"
		}
	},
	"query": "query userInfo {  viewer {    __typename    login    name    email  }}"
}
```

Known issue?

**Comment by nzakharchenko** [comment]
We have exactly the same problem. In Kotlin data class the operation name actually doesn't match the query name.

**Comment by nzakharchenko** [comment]
@BoD actually I've found how to fix it. 
Problem is with semantic naming. Check this section in the documentation - https://github.com/apollographql/apollo-android#semantic-naming

So as I understand the query should be named with `Query` in the end. To disable it you could use this  `useSemanticNaming = false` configuration in your gradle.

But, what is also important, the name should start from capital letter!

I guess this should be fixed somehow 🤔 Otherwise it becomes hard to share a `*.graphql` file between platforms 🤔

**Comment by BoD** [comment]
Thanks for replying. I guess the problem is that semantic naming is automatically set to true when using kotlin model generation, which is surprising and not indicated in the documentation.

**Comment by kovac777** [comment]
same issue

**Comment by sav007** [comment]
I was fixed with https://github.com/apollographql/apollo-android/pull/1308

Either try snapshot or wait for next release

**Comment by Voto** [comment]
I ran into the same issue and as the 1.0.1-SNAPSHOT build brings more problems I made a workaround:

```kotlin
// make your on class an let 99% of code "by" delegate through generated apollo code
class FixedListUsers : Query<ListUsers.Data, ListUsers.Data, Operation.Variables> by ListUsers() {

    /**
     * the generated code make "ListUsers" here with a "L" which lets the query fail 
     **/
    override fun name(): OperationName = OperationName { "listUsers" }  /

}
```
