### ISSUE TITLE
Inheriting classes not generated when they repeat a field from the interface

### ISSUE THREAD

**Issue by RomainPiel** [apollographql/apollo-android#1329]
On version 1.0.0, when I have the following types:
```graphql
type Query {
  get_foo(): Foo!
}
interface Foo {
  a: String!
}
type Bar implements Foo {
  a: String!
}
```

then when I request:
```graphql
get_foo {
  foo {
    a
    ... on Bar {
      __typename
    }
  }
}
```

* `Bar` does not get generated
* The following query gets generated, which is not valid GraphQL:
```graphql
get_foo {
  foo {
    a
    ... on Bar
  }
}
```

**Comment by RomainPiel** [comment]
Edit: I later found that it's an issue specific to `__typename`. I still feel like the type should get generated and that the generated query should stay valid.

**Comment by sav007** [comment]
`__typename` is very special field and treated as a hint for exact type of the object.

Plus in case of inline fragments if code gen sees that all requested fields are from the base interface it doesn't generates the child as it doesn't make any sense, you have access to all fields from the parent.
