### ISSUE TITLE
@Nullable list generated for a non-null array

### ISSUE THREAD

**Issue by romainpiel** [apollographql/apollo-android#1330]
I found a weird thing when building my query. Say that you have the following schema:
```graphql
type Query {
  get_foos(): [Foo!]!
}
interface Foo {
  a: String!
  b: String!
}
type Bar implements Foo {
  a: String!
  b: String!
}
```

Now say that we define the following query:
```graphql
get_foos {
  foo {
    a
    ... on Bar {
      b
    }
  }
}
```

In the generated code, `get_foos()` returns a `@Nullable List<Foo>`.

Now for this query:
```graphql
get_foos {
  foo {
    a
  }
}
```
In the generated code, `get_foos()` returns a `@NotNull List<Foo>`.

Is that an expected behaviour?

**Comment by sav007** [comment]
I believe this issue is fixed.
