### ISSUE TITLE
Failed to parse http response when receiving unexpected interface type response

### ISSUE THREAD

**Issue by chalermpong** [apollographql/apollo-android#1344]
On version 1.0.0, when I have the following types:
```graphql
type Query {
  blocks(): [Block!]!
}
interface Block {
  index: Int!
  featured: Boolean!
}
type BlockParagraph implements Block {
  index: Int!
  featured: Boolean!
  content: String!
}
```
and my app has these 2 queries, both queries doing the same thing, only different that `BlockV2` is using Fragment.
```graphql
query BlockV1 {
  blocks {
    index
    featured
    ... on BlockParagraph {
      content
    }
  }
}
```
```graphql
query BlockV2 {
  blocks {
    ... BlockFragment
  }
}
fragment BlockFragment on Block {
  index
  featured
  ... on BlockParagraph {
    content
  }
}
```
Later, I add another implementation of `Block` below
```graphql
type BlockParagraph2 implements Block {
  index: Int!
  featured: Boolean!
  content: String!
  content2: String!
}
```
Without updating app with the new schema, `BlockParagraph2` is considered an unexpected type of interface `Block`. 

Anyway, `BlockV1` is still able to handle `BlockParagraph2` and parse it to just a normal `Block`. Great!!!

But `BlockV2` is unable to handle `BlockParagraph2` and gives an error message `Failed to parse http response`

I have a look in generated code. The query `BlockV2` has these lines of code which prevent it from fallback the unexpected `BlockParagraph2` type to `Block`
```java
@Override
public @NotNull Fragments map(ResponseReader reader, @NotNull String conditionalType) {
  BlockFragment blockFragment = null;
  if (BlockFragment.POSSIBLE_TYPES.contains(conditionalType)) {
    blockFragment = blockFragmentFieldMapper.map(reader);
  }
  return new Fragments(Utils.checkNotNull(blockFragment, "blockFragment == null"));
}
```
Questions
- What is the expected behaviour when client received an unexpected type like this? Should it failed like `BlockV2` or handle the unexpected type as its based interface like `BlockV1`?
- If the expected behaviour is `BlockV1`. Can we remove these `POSSIBLE_TYPES` checking from generated code? I think by removing this checking, `BlockV2` will be working the same way as `BlockV1`.

**Comment by sav007** [comment]
Yeah, seems like an issue for this particular case. We wanted to be too smart for the nullability in case of fragments and this is the context https://github.com/apollographql/apollo-android/issues/382

Not really sure how to properly handle this case.

**Comment by chalermpong** [comment]
I would prefer this case to be handled like `BlockV1` so I can write my code to handle unexpected type gracefully like this.
```kotlin
when (blockFragment) {
  is BlockFragment.AsBlockParagraph -> // Handle Paragraph
  is BlockFragment.AsBlahBlahBlah -> // Handle BlahBlahBlah
  else -> // Handle unknown block type gracefully
}
```

The parser should only failed when there is a critical incompatibility such as when it found null value for non-nullable field. In this case "Failed to parse http response" will be suitable. Does this make sense?

**Comment by sav007** [comment]
After looking into it more carefully, it seems that what we need to do is check if the fragment is defined on the same type as the parent field (in the example above with `BlockV2 ` query the fragment `fragment BlockFragment on Block` is defined on the base interface `Block`) we shouldn't even generate this check `BlockFragment.POSSIBLE_TYPES.contains(conditionalType)` as it will always correctly resolve fragment that defined on the interface. I'm going to work on this fix.
