### ISSUE TITLE
Apollo uses internal OkHttp APIs

### ISSUE THREAD

**Issue by ZacSweers** [apollographql/apollo-android#1347]
This is using non-public API and causes compatibility issues. Case and point - `DiskLruCache.create` no longer works in the soon-to-be-released OkHttp 4. The entire `DiskLruCache` is actually internal to OkHttp, I think it would be best if this were just copied directly in rather than used from OkHttp

**Comment by digitalbuddha** [comment]
Wow good find I guess that was an oversight. Want to pr it in for some internet points?

**Comment by ZacSweers** [comment]
yep can do
