### ISSUE TITLE
Unresolved reference ApolloSqlHelper and SqlNormalizedCacheFactory

### ISSUE THREAD

**Issue by teknolojia** [apollographql/apollo-android#1349]
Just added these lines in my project but they just can't be resolved. 
I get red color with message **unresolved reference ApolloSqlHelper** and **unresolved reference SqlNormalizedCacheFactory**
```
       //Create the ApolloSqlHelper.
        val apolloSqlHelper = ApolloSqlHelper.create(App.appContext, "myDb")

        //Create NormalizedCacheFactory
        val cacheFactory = SqlNormalizedCacheFactory(apolloSqlHelper)

```
I have these dependencies 
```
    implementation 'com.apollographql.apollo:apollo-http-cache:1.0.0-alpha5'
    implementation "com.apollographql.apollo:apollo-coroutine-support:1.0.0-alpha5"
    implementation 'com.apollographql.apollo:apollo-runtime:1.0.1-SNAPSHOT'
```
What do I miss here for for import to work? Thanks in advance.

**Comment by sav007** [comment]
I believe you missing dep on https://github.com/apollographql/apollo-android/blob/master/apollo-android-support/gradle.properties

**Comment by teknolojia** [comment]
@sav007 Thanks for the comment, But I am a just a beginner. first of all I am using androidX, So should I copy those lines to my gradle.properties?

**Comment by sav007** [comment]
you have to add `mplementation 'com.apollographql.apollo:apollo-android-support:1.0.0-alpha5'`

**Comment by rikardocarvajal** [comment]
I added the implementation with apollo-android-support:1.0.0-alpha5 but it doesn´t work

**Comment by teknolojia** [comment]
`    implementation 'com.apollographql.apollo:apollo-android-support:1.0.1'
`
@rikardocarvajal  add that line it works

**Comment by ridhi129** [comment]
I using apollo version 1.1.1 in my android app and added the above line to resolve ApolloSqlHelper import - implementation 'com.apollographql.apollo:apollo-android-support:{apollo_version}' but its not working. 
@sav007 Any idea what I am missing?

**Comment by jigneshjain1** [comment]
No
