### ISSUE TITLE
Add custom type mapping to classes with generics support

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#135]
I would be nice if user is able to map custom type to class with generics, so to have smth like this:

```
apollo {
  generateClasses = true
  customTypeMapping {
    OptionalString = "com.fernandocejas.arrow.optional.Optional<String>"
  }
}
```

**Comment by digitalbuddha** [comment]
Maybe it there is also a way to define a wrapper type so that any Optional field gets put into an Optional<T> where T = String/Long/Boolean

**Comment by sav007** [comment]
Not sure if the benefit of this is worth the complexity of changes required to codegen. Closing for now.
