### ISSUE TITLE
Unresolved reference: FileUpload

### ISSUE THREAD

**Issue by Dragons0458** [apollographql/apollo-android#1351]
Hello! I am trying to upload files with the plugin, but android studio shows me that the FileUpload class does not exist, any solution? Thank you!

```
implementation "com.apollographql.apollo:apollo-android-support:1.0.0"

implementation "com.apollographql.apollo:apollo-runtime:1.0.0"

implementation "com.apollographql.apollo:apollo-http-cache:1.0.0"

implementation "com.apollographql.apollo:apollo-rx2-support:1.0.0"
```

PD: I'm working with Kotlin

**Comment by martinbonnin** [comment]
FileUpload was added after 1.0.0, you can try with the SNAPSHOT versions:

    buildscript {
    repositories {
        jcenter()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
    dependencies {
        classpath 'com.apollographql.apollo:apollo-gradle-plugin:1.0.1-SNAPSHOT'
    }
    }

**Comment by Dragons0458** [comment]
Hello! thank you very much for your help!

I included the dependencies but I get the following error:
ERROR: Failed to resolve: com.apollographql.apollo: apollo-runtime: 1.0.1-SNAPSHOT

Do you know why? Thank you!

**Comment by Dragons0458** [comment]
My apologies, I was missing the following:

allprojects {
     repositories {
         ...
         maven {
             url 'https://oss.sonatype.org/content/repositories/snapshots/'
         }
         ...
     }
}

I hope they will soon release the final version with the upload of files.

Thank you so much for everything!

Successes!
