### ISSUE TITLE
Add ability to update connection params

### ISSUE THREAD

**Issue by arendjr** [apollographql/apollo-android#1356]
Currently, we are able to specify the connection params for subscription transports when we build the apolloClient instance using the `subscriptionConnectionParams()` method. Unfortunately, there's no way to update the connection params after this point. This is problematic if a token that I specified initially expires at some point during a session and then needs to be updated in case the connection is interrupted and needs to be reestablished.

The JS version of Apollo solves this problem by allowing the connection params to be specified as a factory function in addition to a static object.

**Comment by nokite** [comment]
Thanks for working on this @sav007 !

**Comment by arendjr** [comment]
Great, thanks very much!
