### ISSUE TITLE
Make queries path configurable

### ISSUE THREAD

**Issue by lwasyl** [apollographql/apollo-android#1360]
Recent change that [added support for gql files](https://github.com/apollographql/apollo-android/commit/425d597f227a0f0e01886f2771d77988b51387c5#diff-0c49908ff8287a495dcfac2d77f2b685) broke our workflow, where we share a repository which contains both `schema.graphql` and `schema.json` files with schema definitions, and `queries/` folder with `.graphql` files with queries. 

Previously we already changed schema file from `graphql` extension to `gql`, because of the `graphql/schema.gql: The schema definition is not executable.` error. However due to newly added support for `gql` files, we now can't generate classes at all, due to inflexibility regarding Apollo's gradle plugin configuration.

So it would be good to allow configuration of not only schema file, but also queries directory, instead of hardcoding current `**/*.[graphql|gql]`.

**Comment by sav007** [comment]
Is there any reason why client queries along with schema json can be placed into different sub folder, like `graphql/client/com/sample/*.[graphql|gql|json]`?

**Comment by lwasyl** [comment]
The main thing is that since the repo (schemas, queries etc) is shared, we'd be introducing some hierarchy that doesn't make much sense for non-android users. 

Another thing that would work for us would be excluding `schema.[graphql|gql]` from files passed to the compiler. I see that `schema.json` name is hardcoded, if `schema.graphql` normally shouldn't be passed to the compiler then perhaps it would make sense as well?

**Comment by sav007** [comment]
Will it make sense for you if plugin provides configuration to exclude files by pattern so that you can exclude `**/*.gql` for your project in apollo plugin configuration?

**Comment by lwasyl** [comment]
Sure, any way of allowing that would work
