### ISSUE TITLE
Add Pretty Printer

### ISSUE THREAD

**Issue by AllanWang** [apollographql/apollo-android#1369]
Is it possible to add a pretty printer to the generated classes?

An example can be a string with one field per line, and indent appropriately for nested data.
I understand that we can probably parse the string output or use reflection, but it would be nice to have it out of the box

**Comment by sav007** [comment]
>Is it possible to add a pretty printer to the generated classes?

Sorry but what do you mean? Generated classes are formatted well. with the common Java / Kotlin code styles. Is there any example you can provide where you think the generated code is not formatted?

**Comment by AllanWang** [comment]
I don't mean the generated code itself. I mean a `toString()` function or variant that can generate a prettified output of the graphql result. What I wish to see is essentially the output you'd get from the graphql explorer. Currently, all the fields are added in one line, which becomes hard to read for longer queries. I'd be willing to contribute if people are open to this feature

**Comment by sav007** [comment]
Agh you mean the GraphQL operation source but isn't this formatted?
https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/hero_name/TestQuery.java#L28

**Comment by AllanWang** [comment]
That part is, but `toString()` is not

https://github.com/apollographql/apollo-android/blob/a1cd963f632e2a5d333b9d34e90107b9b5e6733f/apollo-compiler/src/test/graphql/com/example/hero_name/TestQuery.java#L121-L129

**Comment by sav007** [comment]
hm, I don't know this is the default implementation of toString used by any generation lib.
Any PR is welcome to add support for Java code generation.

**Comment by AllanWang** [comment]
Do you mind linking me to the relative file for `toString`? It doesn't seem to be present in the kotlin codegen folder

**Comment by sav007** [comment]
I believe this https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/Util.kt#L109

**Comment by AllanWang** [comment]
Closing this for now to reduce some clutter in your issue list. If I manage to do this I will submit a PR
