### ISSUE TITLE
Codegen broken within last few hours

### ISSUE THREAD

**Issue by AllanWang** [apollographql/apollo-android#1372]
It appears as though a recent change has broken imports for `1.0.1-SNAPSHOT`.
My project suddenly started failing to build, and reverting to old commits didn't work either.

Looking in the class folder, it appears as though `CustomTypes` are properly generated. However, gradle wouldn't pick up on the usage. The IDE itself complains that it isn't there, though autocompletion still works.

Attaching relevant Travis logs:
* `CustomTypes` not found: https://travis-ci.com/AllanWang/GitDroid/builds/115743236

**Comment by AllanWang** [comment]
Judging by the commit history, I'd imagine the fault lies in https://github.com/apollographql/apollo-android/commit/a1cd963f632e2a5d333b9d34e90107b9b5e6733f, and it might be because the apollo tasks comes after the project?

**Comment by mikeccuk2005** [comment]
I did not understand why he put this into `1.0.1-SNAPSHOT` when it is supposed to be snapshot on the next number
[sona repo listing](https://oss.sonatype.org/content/repositories/snapshots/com/apollographql/apollo/apollo-android-support/) Updated on Sun Jun 16 23:40:59 UTC 2019

I had 2 projects run on apollo-android, none of them is able to compile `Unresolved reference: graphql`
Some of the build files were not properly built.

**Comment by hatched-mariusz** [comment]
You can quickly solve the issue by force adding gen dir to the classpath: 
`sourceSets {
        main {
            java {
                srcDirs 'src/main/java'
                srcDirs 'build/generated/source/apollo/classes'
            }
        }
    }`

**Comment by sav007** [comment]
Sorry guys we have made some changes to our gradle plugin that caused this issue.
Are your projects is Kotlin projects?

If yes, is this fix works for you: https://github.com/apollographql/apollo-android/pull/1374/commits/8882237cfa40e07955dac83e5f88b30c5f776d88

**Comment by AllanWang** [comment]
That does seem to fix it. I'll close the issue for now since it seems to be resolved
