### ISSUE TITLE
Unmappable character for encoding Cp1251 during classes generation

### ISSUE THREAD

**Issue by altairmizuchi** [apollographql/apollo-android#1375]
![unmappable issue](https://user-images.githubusercontent.com/7736121/59651597-fd3ca500-91bc-11e9-8231-552536062429.jpg)
During new classes generation, we encounter error messages about unmappable characters. Although everything works fine after that those warnings/errors cause some anxiety) Is there a way to get rid of it?

**Comment by sav007** [comment]
Could you pls try the latest version 1.1.0. Closing for now but feel free to reopen.
