### ISSUE TITLE
Unresolved reference: GithubRepositoryCommitsQuery

### ISSUE THREAD

**Issue by Tangpj** [apollographql/apollo-android#1377]
**apollo-kotlin-sample can‘t run
My ide version is Android Studio Preview 3.5 Bate4
The log is as follows**

e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/ApolloRxService.kt: (75, 16): Cannot infer a type for this parameter. Please specify it explicitly.
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/ApolloRxService.kt: (76, 89): Unresolved reference: GithubRepositoryCommitsQuery
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (5, 46): Unresolved reference: GithubRepositoriesQuery
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (6, 46): Unresolved reference: GithubRepositoryCommitsQuery
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (7, 46): Unresolved reference: GithubRepositoryDetailQuery
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (8, 46): Unresolved reference: fragment
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (18, 58): Unresolved reference: RepositoryFragment
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (19, 66): Unresolved reference: GithubRepositoryDetailQuery
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (20, 53): Unresolved reference: GithubRepositoryCommitsQuery
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (23, 37): Unresolved reference: RepositoryFragment
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (24, 45): Unresolved reference: GithubRepositoryDetailQuery
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (25, 32): Unresolved reference: GithubRepositoryCommitsQuery
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (33, 74): Unresolved reference: GithubRepositoriesQuery
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (33, 111): Unresolved reference: RepositoryFragment
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/data/GitHubDataSource.kt: (34, 70): Unresolved reference: it
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/repositories/MainActivity.kt: (13, 46): Unresolved reference: fragment
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/repositories/MainActivity.kt: (68, 46): Unresolved reference: RepositoryFragment
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/repositories/RepositoriesAdapter.kt: (8, 46): Unresolved reference: fragment
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/repositories/RepositoriesAdapter.kt: (12, 49): Unresolved reference: RepositoryFragment
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/repositories/RepositoriesAdapter.kt: (14, 26): Unresolved reference: RepositoryFragment
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/repositories/RepositoriesAdapter.kt: (28, 27): Unresolved reference: RepositoryFragment
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/repositories/RepositoriesAdapter.kt: (34, 34): Unresolved reference: RepositoryFragment
e: /Users/tangpj/AndroidStudioProjects/apollo-android-master/apollo-kotlin-sample/src/main/java/com/apollographql/apollo/kotlinsample/repositories/RepositoriesAdapter.kt: (34, 64): Unresolved reference: RepositoryFragment

**Comment by sav007** [comment]
There is a temp fix https://github.com/apollographql/apollo-android/pull/1374/commits/8882237cfa40e07955dac83e5f88b30c5f776d88

But we should keep looking into our gradle plugin changes that caused this issue.

**Comment by Tangpj** [comment]
@sav007 can run, thanks!
I will continue to pay attention to it.
