### ISSUE TITLE
Cannot create custom type wrapper from `Date` to `java.util.Date`

### ISSUE THREAD

**Issue by AllanWang** [apollographql/apollo-android#1380]
This relates to the github api.

Currently, it seems like creating a custom adapter from `Date` to `java.util.Date` does not work.

To give an example, an adapter for `DateTime` works fine:

```kt
internal object DateTimeApolloAdapter : CustomTypeAdapter<Date> {

    override fun encode(value: Date): CustomTypeValue<*> = CustomTypeValue.fromRawValue(value)
    override fun decode(value: CustomTypeValue<*>): Date {
        return try {
            val date = value.value as String
            SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.ENGLISH).parse(date)!!
        } catch (e: Exception) {
            e.printStackTrace()
            Date()
        }
    }
}
```

To create the date adapter, we simply change the formatting string and add it

```kt
ApolloClient.builder()
    .serverUrl(GRAPHQL_URL)
    .httpCache(ApolloHttpCache(cacheStore))
    .okHttpClient(okHttpClient)
    .addCustomTypeAdapter(CustomType.URI, UriApolloAdapter)
    .addCustomTypeAdapter(CustomType.DATE, DateApolloAdapter)
    .addCustomTypeAdapter(CustomType.DATETIME, DateTimeApolloAdapter)
    .addCustomTypeAdapter(CustomType.HTML, ObjectApolloAdapter)
    .build()
```

However, the following problems occur:

---

With the date adapter added, apollo complains that it cannot find the adapter.

---

If we instead replace `java.util.Date` with some other class, such as 

```kt
class DateWrapper(val date: Date)
```

To give it a different type, apollo will find the adapter and complain that it cannot be cast to `java.util.Date`. The referenced code does indeed still use `Date`.

(Just tried again and now it complains it can't find it, [reference code](https://github.com/AllanWang/GitDroid/pull/3/commits/768dbdcf1b84122f37045243fb3c7a2ae410f872))

---

If we use

```kt
class DateWrapper(date: Long) : Date(date)
```

Apollo will still complain that it cannot find the adapter.

---

Without any adapter, apollo complains that it cannot be converted to an object (kotlin)

---

Lastly, using `java.lang.String` as output seems to work fine.

Is there some default setting here that is conflicting?

**Comment by sav007** [comment]
Could you pls elaborate on:
>With the date adapter added, apollo complains that it cannot find the adapter.

Is there any exception you see? Mind to provide stacktrace.

**Comment by AllanWang** [comment]
I tried again on the same commit and my newest build and now they both seem to be working. From what I remember before, the runtime error was the same as if I had not added an adapter at all. As a note, the app was using `1.0.1-SNAPSHOT`, so I'm not sure if anything changed, but I will provide an update if this occurs again.
