### ISSUE TITLE
*.iml problem with Android Studio

### ISSUE THREAD

**Issue by AllanWang** [apollographql/apollo-android#1381]
It appears as though apollo constantly generates the following in the *.iml file:

```
<sourceFolder url="file://$MODULE_DIR$/build/generated/source/apollo/classes" isTestSource="true" generated="true" />
```

note that beforehand, there is another line:

```
<sourceFolder url="file://$MODULE_DIR$/build/generated/source/apollo/classes" isTestSource="false" generated="true" />
```

where `isTestSource` is false.

The line with `isTestSource="true"` seems to suggest to the IDE that the generated classes can only be used in the test folder, making it complain for all usages in the source.
If we remove that line, everything works, but it gets reset whenever the project is cleaned/built.

**Comment by twobeeronebread** [comment]
Thanks @AllanWang this worked as a workaround for me too.

**Comment by sav007** [comment]
Is that happening on pure kotlin project?

**Comment by AllanWang** [comment]
Yes

**Comment by sav007** [comment]
I believe it was fixed, closing for now.
