### ISSUE TITLE
Generate Kotlin model not working.

### ISSUE THREAD

**Issue by parthmg** [apollographql/apollo-android#1382]
I tried to generate Kotlin model classes but the build failed with an exception.

	Caused by: java.lang.IllegalArgumentException: couldn't make a guess for __schema
	at com.squareup.kotlinpoet.ClassName$Companion.bestGuess(TypeName.kt:369)
	at com.apollographql.apollo.compiler.codegen.kotlin.ObjectTypeKt.getCompanionObjectSpec(ObjectType.kt:65)
	at com.apollographql.apollo.compiler.codegen.kotlin.ObjectTypeKt.typeSpec(ObjectType.kt:21)
	at com.apollographql.apollo.compiler.codegen.kotlin.OperationTypeKt.typeSpec(OperationType.kt:77)

And the settings in my gradle file are

	apollo {
	    schemaFilePath = "/src/main/graphql/schema.json"
	    outputPackageName = "com.app.appname.graphql"
	    generateModelBuilder = true
	    customTypeMapping = ['Date': "java.util.Date"]
	    generateKotlinModels = true
	}

My schema file is in the path mentioned.
If I disable generateKotlinModels then it works.
I am using version `1.0.0`

How can I fix this issue?

**Comment by sav007** [comment]
Do you have in the schema.json object type called `__schema`?

**Comment by juancruzgs** [comment]
I have a similar issue, but in my case it fails with the error: `Cause: couldn't make a guess for __type`
I'm trying to run this query, where `State` is an Enum and I want to get its values:

```
query StatesQuery {
  __type(name: "State") {
    enumValues {
      name
    }
  }
}
```

It just fails when trying to generate the kotlin models (Java implementation is working ok):

```
apollo {
    generateKotlinModels = true
}
```

**Comment by sav007** [comment]
So you do have object type with the name prefixed with `__`, we will try to figure this out as meantime work around try to use alias if it helps: https://graphql.github.io/learn/queries/#aliases

**Comment by juancruzgs** [comment]
That workaround works, thank you!
This is what I did:

```
query StatesQuery {
  type: __type(name: "State") {
    enumValues {
      name
    }
  }
}
```

Consider that those types (`__type`, `__schema`) are part of the introspection system and are present in all the schemas (they are not defined by the user).
https://graphql.org/learn/introspection/

**Comment by sav007** [comment]
That interesting how it's even possible as IR generation should have failed earlier before actual Kotlin model generation with the message:
```
Name "__hero" must not begin with "__", which is reserved by GraphQL introspection.
    at assertValidSchema (/usr/local/lib/node_modules/apollo-codegen/node_modules/graphql/type/validate.js:82:11)
...
```

**Comment by sav007** [comment]
This is a restriction of Apollo codegen, as workaround aliases should be used.
