### ISSUE TITLE
Error on graphql response when minifyEnabled true

### ISSUE THREAD

**Issue by dhruba1986** [apollographql/apollo-android#1388]
I am getting unexpected data on graphql response when minifyEnabled. If I set minifyEnabled false then everything works fine. Do I need to set any procured rule to enable minifyEnabled.
![Screenshot 2019-06-25 at 7 05 39 PM](https://user-images.githubusercontent.com/20789588/60102911-3d32f780-977c-11e9-88d2-e1610cbc42c6.png)
![Screenshot 2019-06-25 at 7 06 18 PM](https://user-images.githubusercontent.com/20789588/60102955-52a82180-977c-11e9-9132-fd15ea419eed.png)

**Comment by sav007** [comment]
I believe you should configure to ignore any models generated by apollo plugin

**Comment by kateile** [comment]
@dhruba1986 Hi, I would like to know how you resolved this

**Comment by tasomaniac** [comment]
Hi we use minifyEnabled with no special configuration and no issues so far. 

Can you post your actual issue?

**Comment by dhruba1986** [comment]
I got JSON api response as some random key value pair like "b, c, d, e" as key. I already attached an image of the response in my original question. This happen only on when minifyEnable, otherwise api response is as expected key value pair.

**Comment by dhruba1986** [comment]
> Hi we use minifyEnabled with no special configuration and no issues so far.
> 
> Can you post your actual issue?

I got JSON api response as some random key value pair like "b, c, d, e" as key. I already attached an image of the response in my original question. This happen only on when minifyEnable, otherwise api response is as expected key value pair.

**Comment by tasomaniac** [comment]
If you have all generated code under a certain package you can try doing in your Proguard config

```
-keepnames com.example.my.api.packge.**
```

**Comment by dhruba1986** [comment]
> If you have all generated code under a certain package you can try doing in your Proguard config
> 
> ```
> -keepnames com.example.my.api.packge.**
> ```

thanks a lot, it works. I think this should be mentioned in documentation.

**Comment by tasomaniac** [comment]
Definitely makes sense to put this into docs. Actually, it is also possible to automate this since Apollo already knows the packages created.
