### ISSUE TITLE
Use buildSrc to add the built plugin to the sample classpath

### ISSUE THREAD

**Issue by marwanad** [apollographql/apollo-android#139]
instead of pulling it from maven

https://docs.gradle.org/current/userguide/organizing_build_logic.html#sec:build_sources

**Comment by felipecsl** [comment]
This is fixed by #125 no?

**Comment by marwanad** [comment]
It's for [this](https://github.com/apollographql/apollo-android/blob/master/apollo-sample/build.gradle#L4) line.

We'll be using it on the local version of the gradle-plugin. 
It's pretty much the equivalent of `compile project()` but in a way that works for the plugin.

**Comment by felipecsl** [comment]
nice!

**Comment by martinbonnin** [comment]
@marwanad I was to a meetup with a gradle talk yesterday (https://www.meetup.com/Android-Paris/events/237671621/, sorry in french).

@melix talked about composite builds, which might help us to use the plugin directly from the sample app.

**Comment by marwanad** [comment]
@martinbonnin thanks for sharing! I'm taking a look at the docs now.  Seems like a better alternative than adding the plugin under `buildSrc` since only one module will need it.

**Comment by marwanad** [comment]
We decided a while ago that `apollo-sample`should use the maven artifacts instead of the project dependencies.

#433 added a script that converts `apollo-integration` to a composite build to run the tests on the project version of the plugin.
