### ISSUE TITLE
Represent Union Types as Sealed Classes when generating Kotlin models

### ISSUE THREAD

**Issue by AOrobator** [apollographql/apollo-android#1390]

**Comment by sav007** [comment]
There is an issue regarding this:

https://pl.kotl.in/P8wl-jOKL

That means for sealed class implementations we should nest them that what we want to avoid, as we tried nesting classes in the past and it was looking cumbersome the nesting level can get very deep

**Comment by AOrobator** [comment]
Seems like making the sealed class top-level fixes this:

https://pl.kotl.in/acOr8owf9

Have anything against making them top level classes?

**Comment by sav007** [comment]
Top level class will lead to class name collision (redeclaration class), as you can't have multiple top level classes with the same names defined in different files. And you can easily run into this scenario if you have multiple queries requesting the same object.

**Comment by tho-graf** [comment]
Sealed Classes would improve the dev experience so much.

Could you do it like this example? https://pl.kotl.in/Oda2_p8Oe

**Comment by sav007** [comment]
That will work for sure, but it leads to another issue: deep nested class names for example for very simple query the name could be 'Query.Data.Hero.Friend.Droid.Episode' . In real world real production Graphql schema is way complicated, especially when it comes to Relay implementation of pagination (edges, node). From our past experience this is not really pleasent to read name of deep nested class that occupies whole screen.

**Comment by tho-graf** [comment]
I see. We are importing Episode (or in my Example C oder D) directly. You have to import it like that everytime you use it.
But IMO the typesafty / dev experience is worth it.

**Comment by martinbonnin** [comment]
Small update about this:

Kotlin 1.5 [sealed interfaces](https://zsmb.co/sealed-goodies-coming-in-kotlin-1-5/) _might_ make the codegen easier...

**But**

... sealed classes do not work anymore if there are GraphQL interfaces in the mix:

```
union Animal = Cat | Lion | Turtle | Python
interface Pet {
  name: String!
}

query {
  animal {
    ... on Pet {
      name
    }
    ... on Cat {
      meow
    }
    ... on Lion {
      roar
    }
  }
}
```

So the general case is not easy to model. It might be possible with Fragments as interfaces but it's not easy...

**Comment by StylianosGakis** [comment]
So currently, with a very simple union type with two alternatives, our only option is getting the two classes as individual nullable fields, despite the fact that we might know that one of them can't be null.
How are people handling this currently, just asserting non nullability "!!" on one of them after seeing which one of the two isn't null? This doesn't seem to be in the scope of 3.0.0 either, which just makes it a tiny bit annoying to work with such union types.

**Comment by martinbonnin** [comment]
@StylianosGakis in 3.x, you can opt-in [`responseBased` codegen](https://github.com/apollographql/apollo-android/blob/dev-3.x/design-docs/Codegen.md) in your build.gradle file:

```
apollo {
  codegenModels.set("responseBased")
}
```

This will not generate sealed classes just yet but might be a bit closer to what you're looking for. For the query:

```graphql
query {
  animal {
    ... on Cat {
      meow
    }
    ... on Lion {
      roar
    }
  }
}
```

It will generate:

```kotlin
interface Animal
class CatAnimal: Animal
class LionAnimal: Animal
class OtherAnimal: Animal
```

Which you can then use like this:

```kotlin
when (data.animal) {
  is CatAnimal -> // do something with meow
  is LionAnimal -> // do something with roar
  else -> // This is a new type that wasn't known at compile time, do something with it or throw an error 
}
```

I think at this point making `Animal` a sealed interface should be relatively straightforward. Note that sealed interfaces will not remove the need for a fallback `else -> ` branch up there as adding new types to an union should be a backward compatible change. But the `sealed` modifier will express the intent a bit better. We'll add this in 3.x

**Comment by StylianosGakis** [comment]
That is awesome, so much better than what we have right now for sure. Very happy with the approach you took for this!
Looking forward to play around with it. What do you say is the limiting factor making it an opt-in at the moment?

**Comment by martinbonnin** [comment]
Because `responseBased` codegen unrolls fragments and generates interfaces for polymorphic types in addition to the implementation, it can generate significantly more code (see https://github.com/apollographql/apollo-android/issues/3144). There's no silver bullet unfortunately. It's either that or the more compact `operationBased` codegen but that doesn't have all the type information. You can read more about it there: https://github.com/apollographql/apollo-android/blob/dev-3.x/design-docs/Codegen.md

**Comment by martinbonnin** [comment]
`3.0.0-rc01` is now [released](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-rc01) with sealed interfaces.
