### ISSUE TITLE
Not getting a conflated channel

### ISSUE THREAD

**Issue by fluxxion82** [apollographql/apollo-android#1392]
I'm using the new apollo coroutine extensions (version 1.0.0), but I don't think I'm getting a conflated channel despite setting the channel capacity to be conflated. Here is an example of a call I'm making:

```
fun apiCall(accessToken: String, param: String): ReceiveChannel<Foo> {
        return apolloClient.mutate(
            BarMutation.builder().param(param).build()
        ).toChannel(Channel.CONFLATED).map {
            Foo(it?.field)
        }
    }
```
and when I'm debugging, it looks like the receive channel that is returned is a `RendezvousChannel`, and doesn't behave like a conflated channel. I've tried setting the capacity to conflated and unlimited, but it's the same result. It's my understanding that only conflated and unlimited are supported, so is there something else I'm missing?

**Comment by sav007** [comment]
As soon as query execution is finished channel is going to be closed. There is no much benefit of using conflated channel for queries. Conflated channels makes sense for query watchers only.

**Comment by sav007** [comment]
Closing.
