### ISSUE TITLE
Apollo Client is not compatible with OKhttp v4.0.0

### ISSUE THREAD

**Issue by ahmadmuhsink** [apollographql/apollo-android#1394]
Apollo client is not compatible with OkHttp v4.0.0 because of Apollo Cache tried to access `DiskLruCache` create method that now behind Companion and without `@JvmStatic` annotation

https://github.com/apollographql/apollo-android/blob/a19c7a38f142cab6ee56d983247d920bc91abaff/apollo-http-cache/src/main/java/com/apollographql/apollo/cache/http/DiskLruHttpCacheStore.java#L126

**Comment by digitalbuddha** [comment]
https://github.com/apollographql/apollo-android/pull/1357
