### ISSUE TITLE
Generated code contains "unchecked" warnings.

### ISSUE THREAD

**Issue by atexit** [apollographql/apollo-android#1395]
We enable `-Werror` and `-Xlint:unchecked` on all our ~~java~~ Android java projects. 

When upgrading to 1.0.0, our builds started failing in compile, due to the generated code for ResponseFieldMarshaller using this construct where `similarPrograms` is of type `List<ProgramPageQuery.SimilarProgram>`
```java 
writer.writeList($responseFields[1], similarPrograms, new ResponseWriter.ListWriter() {
    @Override
    public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
        for (Object item : items) {
            listItemWriter.writeObject(((SimilarProgram) item).marshaller());
        }
    }
});
```
This causes the compiler to emit a warning about an unchecked method invocation:

> [unchecked] unchecked method invocation: method writeList in interface ResponseWriter is applied to given types
required: ResponseField,List<T>,ListWriter<T>
found: ResponseField,List<SimilarProgram>,<anonymous ListWriter>
where T is a type-variable:
T extends Object declared in method <T>writeList(ResponseField,List<T>,ListWriter<T>)

and our build fails due to -Werror.
This is caused by ListWriter now being generic, and expecting a specific element type. 

Expected behaviour here is that the generated code should instead be
```java
writer.writeList($responseFields[1], similarPrograms, new ResponseWriter.ListWriter<ProgramPageQuery.SimilarProgram>() {
    @Override
    public void write(List<ProgramPageQuery.SimilarProgram> items, ResponseWriter.ListItemWriter listItemWriter) {
        for (ProgramPageQuery.SimilarProgram item : items) {
            listItemWriter.writeObject(item.marshaller());
        }
    }
});
```

If this isn't possible due to type erasure, union types or something else outside of your control, the emitted code should instead suppress the "unchecked" warning.

**Comment by sav007** [comment]
Have you tried this configuration in your build gradle:
```
apollo {
    ...
    suppressRawTypesWarning = "true"
}
```

**Comment by atexit** [comment]
@sav007 Yes, we turned on suppressRawTypesWarning, but it did not suppress the unchecked warnings as far as we can tell.

**Comment by atexit** [comment]
@sav007 I just wanted to confirm that setting suppressRawTypesWarning to true does not silence the [unchecked] warnings. Turning suppressRawTypesWarning off generates a bunch of [rawtypes] warnings, in addition to the "unchecked method invocation" / "unchecked conversion" warnings that I've mentioned above.

**Comment by atexit** [comment]
@sav007 Thank you!
