### ISSUE TITLE
ApolloParseException with Kotlin Models

### ISSUE THREAD

**Issue by AOrobator** [apollographql/apollo-android#1397]
When using Kotlin models, I get an ApolloParseException on server errors because MyMutation.Data#wrapData expects a non-null type. However, when generating Java models, I don't get this error because there isn't null-checking around the Java version of #wrapData. I would imagine that the Data would always be nullable as an error response may not have Data.

Expected behavior is the Java behavior of not checking for null and instead using a nullable type for the input to #wrapData

**Comment by sav007** [comment]
I guess it was fixed with https://github.com/apollographql/apollo-android/pull/1303

**Comment by sav007** [comment]
Will be released soon

**Comment by AOrobator** [comment]
Closing this out as it's released in 1.0.1
