### ISSUE TITLE
Input type object constructor and input type object builder are not generated as public

### ISSUE THREAD

**Issue by semirzahirovic** [apollographql/apollo-android#1398]
In our project we need to add couple of `mutations`. 
Here is non-complex version of what we do:
```
mutation UpdateActionMutation($actionUpdate: ActionUpdate!, $actionId: String!) {
    updateAction(actionUpdate: $actionUpdate, actionId: $actionId) {
        id
    }
}

type ActionUpdate {
     field1: String,
     field2: String
     etc
}
```
Here is part of `schema.json`
```
  "kind": "INPUT_OBJECT",
  "name": "ActionUpdate",
```

Obviously, if we want to use the `mutation`, we need to send `ActionUpdate` to UpdateActionMutation builder. Problem is that in the generated code, `ActionUpdate` **constructor** and `ActionUpdate` **Builder** are **not** public.

`ActionUpdate` is generated into `ourPackageName/type` package, while `schema.json` is placed in `graphql/ourPackageName` package. Because of this, there is no way to create `ActionUpdate` object, to send it to UpdateActionMutation builder.

Is this a bug? Should `ActionUpdate` constructor or `ActionUpdate.Builder` be generated as `public`? 

Or we are missing something?

**Comment by sav007** [comment]
there is a static function generated that you should call, for example:
https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/input_object_type/type/ColorInput.java#L68

**Comment by semirzahirovic** [comment]
@saav Thanks!
