### ISSUE TITLE
Cannot use fragment on null and nonnull fields of same type

### ISSUE THREAD

**Issue by AllanWang** [apollographql/apollo-android#1403]
May relate to https://github.com/apollographql/apollo-android/issues/1145?

From Github's graphql, there are events `PullRequestCommit` and `MergedEvent`. The first one has field `commit: Commit!`, and the second one has field `commit: Commit`.

I made a fragment on `Commit`, and used it for both types.

However, apollo complains:
`Fields "commit" conflict because they return conflicting types Commit! and Commit. Use different aliases on the fields to fetch both if this was intentional.`

Is this intentional, or something that's unsupported? Couldn't getting fragments in one return a nullable field and not in the other?

**Comment by sav007** [comment]
Yeah that a restriction on Apollo GraphQL code gen itself, try to use aliases to workaround this.
