### ISSUE TITLE
Better error messages for validating GraphQL

### ISSUE THREAD

**Issue by AOrobator** [apollographql/apollo-android#1411]
Right now I'm creating a .graphql mutation and I get the following error from the Android Gradle Plugin:

`Validation of GraphQL query document failed`

As I'm new to GraphQL, this message is unhelpful. Ideally I would get a message indicating what went wrong on what line. For example, UnknownType UserDto in YourMutation.graphql Line 42

**Comment by AOrobator** [comment]
https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/ covers this. Closing this out.

**Comment by RethinavelPillai** [comment]
How come this could be the answer for the question. @AOrobator

**Comment by AOrobator** [comment]
The plug-in will highlight in red any unknown entities, giving you a visual clue of where you went wrong and what doesn't match the given schema
