### ISSUE TITLE
Kotlin generated models faulty import of String

### ISSUE THREAD

**Issue by nicusorflorin** [apollographql/apollo-android#1424]
on Apollo 1.0.1 version if I turn on the kotlin model generations, the generated query models have an **"import String"** which should be **"import kotlin.String"** in the body of the model it is used properly, only the import is broken

**Comment by sav007** [comment]
That is really strange, as it generated as `import kotlin.String`, for example: https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/hero_name/TestQuery.kt#L16

I can guess it might be related to custom types, but could you please provide more specifics for your case.

**Comment by nicusorflorin** [comment]
what kind of specifics you have in mind? it happens for all generated models, I am using kotlin plugin vers: 1.3.31, android studio and gradle: 3.4.1

**Comment by vikrama** [comment]
I'm on 1.0.1, kotlin 1.3.41 (also tried with 1.3.31) and gradle 3.4.1, and it correctly imports `kotlin.String` for me. @nicusorflorin, do you have anything like this in your gradle file? 
```
customTypeMapping = [
    "Long": "java.lang.Long",
    "Timestamp": "kotlin.String"
]
```

**Comment by sav007** [comment]
@nicusorflorin could you pls provide your apollo plugin configuration?

**Comment by nicusorflorin** [comment]
@sav007 
``` 
apollo({
    setCustomTypeMapping(
            mapOf("ID" to "String",
                    "Id" to "String",
                    "Date" to "java.util.Date"
            ))
    setGenerateModelBuilder(true)
})
```

that was it, changed to kotlin.String in the mapping and all is good now :), thx
