### ISSUE TITLE
What's the status of kotlin class generation? 

### ISSUE THREAD

**Issue by k-misztal** [apollographql/apollo-android#1425]
What's the status of Kotlin class generation? The `README` file says it's subject to change. When is it planned to release the final/stable version of that feature? 

_This issue should be labeled with the_ `Question` _label._

**Comment by sav007** [comment]
It's should be ok, we keep fixing some small issues but the overall the structure of generated models should be stable now.

**Comment by sav007** [comment]
I guess we can close this.
