### ISSUE TITLE
Using root query with Custom CacheKeyResolver

### ISSUE THREAD

**Issue by jwongoSF** [apollographql/apollo-android#1429]
My use case involves implementing a a resolver like so:

```
mKeyResolver = object: CacheKeyResolver() {
            /**
             * called when populating cache
             */
            override fun fromFieldRecordSet(field: ResponseField, recordSet: MutableMap<String, Any>): CacheKey {
                val id: String? = (recordSet as LinkedHashMap<String, *>)["id"]?.toString()
                val typename: String? = recordSet["__typename"] as String
                return formatCacheKey(id, typename)
            }

            /**
             * Called when reading cache (maybe?)
             */
            override fun fromFieldArguments(field: ResponseField, variables: Operation.Variables): CacheKey {
                return formatCacheKey(field.resolveArgument("id", variables) as String,
                    field.resolveArgument("__typename", variables) as String)
            }
        }

/**
     * Configures the cache normalization for the ApolloClient cache.
     * Cache normalization only occurs for query objects that contain both the
     * `id` and `__typename` fields. Other fields are only cached based on their
     * path within the root query.
     */
    private fun formatCacheKey(id: String?, typeName: String?): CacheKey {
        if (id == null || typeName == null) {
            return CacheKey.NO_KEY
        }
        return CacheKey.from("$id:$typeName")
    }
```
I'm able to successfully write to the cache but the issue arises when I try to get data from the cache using an operation with a CACHE_ONLY policy. The query itself requires no arguments so when the `fromFieldArguments` method is called within the resolver, a null is returned even though the data is in the cache. This is expected given my implementation of `formatCacheKey`.

It's worth noting that if a resolver isn't added to the client, Apollo gets data from the cache using the default behavior of finding the data using the QUERY_ROOT. But it seems like if the resolver is implemented, this behavior is eliminated. Is there a way to achieve this default behavior using a custom resolver?

**Comment by sav007** [comment]
I'm trying to figure out the issue you are describing.

In order to do this could you please do this: dump the cache by calling `com.apollographql.apollo.cache.normalized.NormalizedCache#dump` and then prettify  if by calling `com.apollographql.apollo.cache.normalized.NormalizedCache#prettifyDump`. 

Attach the prettified dump so I can take a look.

**Comment by jwongoSF** [comment]
To sum it up, right now I'm returning `CacheKey.NO_KEY` if objects don't have `id` and `__typename` fields. Is there a way I can tell Apollo to use QUERY_ROOT to locate the object instead? The data exists in the cache before and after I try hitting the cache.

Cache dump:
```
OptimisticNormalizedCache {}
    LruNormalizedCache {
      "me" : {
        "__typename" : Me
        "person" : CacheRecordRef(1020:Person)
      }
    
      "1009:Organization" : {
        "__typename" : Organization
        "id" : 1009
        "roles" : [
          EMPLOYEE
          MOBILE_ADMIN
        ]
      }
    
      "QUERY_ROOT" : {
        "me" : CacheRecordRef(me)
      }
    
      "1020:Person" : {
        "__typename" : Person
        "id" : 1020
        "firstName" : Employee
        "lastName" : User
        "jobTitle" : Brand Manager
        "organizations" : [
          CacheRecordRef(1009:Organization)
        ]
      }
    }
```

**Comment by sav007** [comment]
For `QUERY_ROOT` Apollo won't call your resolver as it handled internally:
https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/cache/normalized/RealApolloStore.java#L376

So in your example it will load this root record:
```
 "me" : CacheRecordRef(me)
```

Then, as you return `CacheKey.NO_KEY` if no `id` and `__typename` provided, the cache key in this case will be calculated by default builder:
https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/field/CacheFieldValueResolver.java#L53

https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/cache/normalized/RealCacheKeyBuilder.java#L44

Another point is that your custom `CacheKeyResolver ` to fetch cached data will be called only once to resolve  root node for query from this record set:
```
 "me" : CacheRecordRef(me)
```
after that Apollo cache knows how to resolve the references to sub nodes,  for example:
```
"me" : {
        "__typename" : Me
        "person" : CacheRecordRef(1030:Person)
      }
```
for `person` sub node there is ref `CacheRecordRef(1030:Person)`.

From the dump you provided I can see that there is no such `"person" : CacheRecordRef(1030:Person)` recordset in the cache:

```
"me" : {
        "__typename" : Me
        "person" : CacheRecordRef(1030:Person)
      }
"1020:Person" : {
        "__typename" : Person
        "id" : 1030
        "firstName" : Employee
        "lastName" : User
        "jobTitle" : Brand Manager
        "organizations" : [
          CacheRecordRef(1009:Organization)
        ]
      }

```

**Comment by jwongoSF** [comment]
Sorry the cache recordset inconsistency is from my failed attempt to spoof the original values earlier but I assure you the actual references in the cache is correct and works. I also figured out why I'm getting null. It turns out that `formatCacheKey` wasn't being called due to an unchecked exception not being caught in `field.resolveArgument("id", variables) as String`. I was trying to cast a `null` to a `String`. Changing both parameters to the format `field.resolveArgument("id", variables)?.toString()` yields expected behavior. Thanks for the help!
