### ISSUE TITLE
:app:installApolloCodegen` gradle task spends long exec. time

### ISSUE THREAD

**Issue by dogscar** [apollographql/apollo-android#1435]
Every execing 'app:installApolloCodegen' task takes about an hour. My system environment is Win10. But on my mac, everything is normal.

**Comment by sav007** [comment]
you can try to local pre-installed code gen npm to speed up https://github.com/apollographql/apollo-android#use-system-pre-installed-apollo-codegen

**Comment by dogscar** [comment]
yes, i have config it.
but the first build  or rebuild still spend  1 hour. my network is ok.
There's nothing problem with my code. i have test official  and other people's cod.
what task does the installApolloCodegen exec?  just only ' npm install ..'?


https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloCodegenInstallTask.groovy

  @Override
  void exec() {
    Utils.deleteDirectory(installDir.get().getAsFile());

    writePackageFile(apolloPackageFile.get().getAsFile());

    setArgs(Lists.newArrayList("install", "apollo-codegen@" + APOLLOCODEGEN_VERSION, "--save", "--save-exact"));
    getLogging().captureStandardOutput(LogLevel.INFO);

    super.exec();
  }



the same pc（dual system ，win10 & mac）, the same network, Why does it only work properly  on the MAC

**Comment by tasomaniac** [comment]
So if you configure system level installation, the task you mention is not even supposed to run. Please do that and report which task takes long. Thanks.

**Comment by sav007** [comment]
Please try latest version with a new code generation engine https://github.com/apollographql/apollo-android/releases/tag/1.1.0
