### ISSUE TITLE
Upload not working under proguard

### ISSUE THREAD

**Issue by kateile** [apollographql/apollo-android#1436]
I have 2 mutations one with single image upload functionality and other one with multiple images upload functionality. when I don't use proguard all of them works just fine  but  when proguard is enabled the one with multiple(as list of images) break.
 I use 
```
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
``` 

Is there any rule that I should add in proguard especially for upload functionality?
Note: Proguard is fine in all other quaries and mutations except for that with multiple images.

How I build input
```
        val uploadList = mutableListOf<FileUpload>()

        val product = ProductInput.builder()
                .images(uploadList)
                .build()
```
Error printed in the logs is 
```
-images: [null, null, null, null, null], 
h: [{}, {}, {}, {}, {}] }; 
Field \"h\" is not defined by type ProductInput.","locations":[{"line":1,"column":29}]
```
I believe **h** is meant to be **images** and those five nulls are images. Any help will be appreciated

**Comment by levivas** [comment]
Hi @kateile did you solve problem, because I have the same.

**Comment by martinbonnin** [comment]
@levivas apollo-android shouldn't require any specific proguard rule. Can you give more details about your error?

**Comment by martinbonnin** [comment]
@levivas ooooopsie, I just bumped into https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloServerInterceptor.java#L262.

So contrary to my former belief, there **is** some reflection in `apollo-android`

The below in your proguard.txt should fix the issue:

```
-keep class * extends com.apollographql.apollo.api.Input
```

Let me know if it worked.
