### ISSUE TITLE
'enableAutoPersistedQueries' not preventing Auto Persisted Queries when set to false.

### ISSUE THREAD

**Issue by stonestclair** [apollographql/apollo-android#1437]
Auto Persisted Queries are disabled on our GraphQL server, so I've had to disable it in the Android ApolloClient like so: 
`private ApolloClient apolloClient = ApolloClient.builder().enableAutoPersistedQueries(false).serverUrl(API_URL).okHttpClient(okHttpClient).build();`

However, when querying our GraphQL server, the ApolloClient is still sending the Auto Persisted Queries.

**Comment by vikrama** [comment]
https://github.com/apollographql/apollo-android/issues/1322 - Fixed

@stonestclair Which version are you on? I don't see that behavior in 1.0.1

**Comment by stonestclair** [comment]
apollo-runtime:1.0.1

**Comment by sav007** [comment]
super strange as `enableAutoPersistedQueries` even set to false by default. Could you please double check the http logs sent to server to confirm that you see `persistedQuery` in raw body.

I just checked with Apollo sample app, wasn't able to reproduce.
