### ISSUE TITLE
Question - Is it possible to serialise the apollo-client?

### ISSUE THREAD

**Issue by Lavanyagaur22** [apollographql/apollo-android#1441]
While implementing offline support in one of the android libraries, when the app is in the background we need to make server calls whenever net comes with the mutations made by the client while he/she was offline. Now for doing so, we need to have an apollo client in our library that does the scheduled work. Is there a way that we can use the apollo client provided by the user to do the same? (serialize apollo client, store in a DB and de-serialize it to use it in the background)?

**Comment by digitalbuddha** [comment]
No you cannot serialize an apollo client. You would need to make a new instance again
