### ISSUE TITLE
Document Apollo Espresso integration

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#1444]
I've realized that Apollo Android has Espresso Idling Resources integration. 

Would be amazing to document the usage of it.

**Comment by sav007** [comment]
But before we should verify if it's up-to-date and still working as it was quite a while since last time we looked into it.

**Comment by tasomaniac** [comment]
Just used it yesterday. Worked as expected. 🖖

**Comment by sav007** [comment]
Should we close?

**Comment by tasomaniac** [comment]
The Integration works fine but it is not documented. We should keep this open. Maybe `help-wanted` label would be good

**Comment by martinbonnin** [comment]
We've been using that for a while now. I'll add something to the README.md

**Comment by martinbonnin** [comment]
I spoke too fast, we actually used our own implementation of IdlingResource :grimacing: . We should certainly change to the provided one.

Anyways, Pull Request is there (with other things inside like dropping rxjava1, coroutines, etc...): https://github.com/apollographql/apollo-android/pull/1525
