### ISSUE TITLE
Custom Scalars not binding correctly

### ISSUE THREAD

**Issue by tmtrademarked** [apollographql/apollo-android#1445]
I'm having trouble getting custom scalars to work properly in our project, and I can't for the life of me figure out what's different between our setup and the guidelines here in this project. But for some reason, whenever I build, the `CustomType` class is generated with two defined scalar types, `ID` and `URL` - but the mapping for `URL` is not what I want it to be.

It doesn't seem to matter what I change the gradle declarations to be. No matter if I add new classes, or change the name/type of the classes in the gradle file, we get the same output for CustomType. This makes me suspect my project is misconfigured somehow, but it's not at all obvious to me how. Any help on how to debug this would be very much appreciated!

```
CustomType.java

public enum CustomType implements ScalarType {
  URL {
    @Override
    public String typeName() {
      return "Url";
    }

    @Override
    public Class javaType() {
      return Object.class;
    }
  },

  ID {
    @Override
    public String typeName() {
      return "ID";
    }

    @Override
    public Class javaType() {
      return String.class;
    }
  }
}
```

In our build.gradle for the library project where this lives:

```
apply plugin: 'com.apollographql.android'
apollo {
    customTypeMapping = [
            'URL' : 'java.net.URL'
    ]
}
```

In our schema files:
```
schema.graphql:
"""A valid URL, transported as a String"""
scalar Url

schema.json:
{
        "kind": "SCALAR",
        "name": "Url",
        "description": "A valid URL, transported as a String",
        "fields": null,
        "inputFields": null,
        "interfaces": null,
        "enumValues": null,
        "possibleTypes": null
      },
```

We're using Apollo version 1.0.0 (`com.apollographql.apollo:apollo-runtime:1.0.0` and `com.apollographql.apollo:apollo-gradle-plugin:1.0.0`).

**Comment by sav007** [comment]
One thought is that in schema the type is capitalized not uppercased `Url` but in apollo gradle config it uppercased `URL`.

**Comment by tmtrademarked** [comment]
I've tried changing that, and it doesn't seem to make a difference in what is generated.

**Comment by tmtrademarked** [comment]
I stand corrected - it *absolutely* does change what is generated. In fact, that seems to solve this completely. I must have not looked closely enough after updating the gradle file. That is embarrassing - but thank you for pointing that out!

**Comment by tmtrademarked** [comment]
I think I can close this now - thanks again for the help! For any future seekers who find this, it looks to me like Apollo automatically generates a CustomType binding Scalars to Object if there is no mapping present. The plugin doesn't throw an error if you mistype the name like I did, but if you match the name exactly, it should work just fine.
