### ISSUE TITLE
Automatically add Proguard config for generated classes

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#1468]
As per discussion in #1388 Apollo can actually generate Proguard configuration for the generated classes. This will allow easier usage when `minifyEnabled` is turned on. 

Google R8 team recently added the ability to provide additional config by making use of META-INF. This can also be used by code generating annotation processor. Since Apollo Android is a Gradle plugin, the setup might be non-conventional.

**Comment by martinbonnin** [comment]
Do we know what minification breaks ? I would expect the models/parsers to be robust to minification since they don't use any reflection. Or do they ?

**Comment by tasomaniac** [comment]
Just like I mentioned in the original issue, we are not using any rules for the code generated by Apollo. It was useful for the user who created the original issue. That's why I opened this. 

Before starting this work, it would be good to verify that this is actually needed.

**Comment by perchrh** [comment]
I suggest adding the androidx Keep annotation to the source files Apollo generates. This keeps them from getting minified. 
https://developer.android.com/reference/androidx/annotation/Keep

**Comment by martinbonnin** [comment]
It would be nice to add a test for that. I don't see why R8 would break anything but maybe I'm missing something.

Also @perchrh we probably don't want to add an Android dependency to the generated models as they also work without Android. We could make this optional I guess but I wouldn't do it unless absolutely required.

**Comment by tasomaniac** [comment]
Libraries can add such annotations similar to androidx's Keep. Its a good trick. You can basically have any annotation. And then you will add a proguard rule that keeps the classes annotated with that particular annotation.

**Comment by martinbonnin** [comment]
Should we close this issue? I don't think any proguard/r8 rules are required for generated models as reflection is not used.

**Comment by tasomaniac** [comment]
I would say yes. I don't think any special rule is needed.
