### ISSUE TITLE
Is it possible to watch the changes to the normalized cache records directly from ApolloStore?

### ISSUE THREAD

**Issue by chalermpong** [apollographql/apollo-android#1473]
Currently, we can read Graphql Fragment directly from ApolloStore like this:  
```kotlin
apolloStore().read(
  UserFragment.Mapper(),
  CacheKey.from("myKey"),
  Operation.EMPTY_VARIABLES
)
```
Is it possible to watch the changes to the fragment, so that the caller get notified when there is a new update? Something similar to `ApolloQueryWatcher`.

**Comment by sav007** [comment]
I guess you can try to register own `RecordChangeSubscriber` via `com.apollographql.apollo.cache.normalized.ApolloStore#subscribe`

**Comment by chalermpong** [comment]
I just have a look at `ApolloStore#subscribe` today. 
`ApolloStore#subscribe` get notify on every change, but I want to get notified only on the change that affect my target `Fragment`. 

Is it a good idea to have `watch` function in `ApolloStore`?
Then it is possible to watch the Fragment like this:
```java
apolloStore().watch(
    UserFragment.Mapper(),
    CacheKey.from("myKey"),
    Operation.EMPTY_VARIABLES
).enqueueAndWatch(object: ApolloStoreOperation.Callback<UserFragment> {
    override fun onSuccess(result: UserFragment?) {
        // Get notified when UserFragment get updated
    }
    override fun onFailure(t: Throwable?) {
        
    }
})
```

If there is nothing against this idea, I would like to help on this feature.

**Comment by olivierg13** [comment]
That would be a really awesome feature actually! 
Observability is really nice to have for certain use cases.

Looking at how `Room` is doing internally, they're invalidating any active LiveData when a change in a "watched" table happens (by table name, logic can be seen in `androidx.room.InvalidationTracker`).
If Apollo supported something similar (LiveData invalidation per Fragment, and even per Key), that would be really cool!

Wdyt?

**Comment by teodorpenkov** [comment]
Any news about this one? :)

**Comment by teodorpenkov** [comment]
In the world of android where we don't own the creation of objects such as activity, fragment and architecture_component::viewmodel it will be really helpful.

**Comment by martinbonnin** [comment]
@teodorpenkov Improving the cache is pretty high in the [ROADMAP](https://github.com/apollographql/apollo-android/blob/main/ROADMAP.md). Real-life use case would be super helpful to make sure the new APIs will work for your environment. Could you ellaborate more on how you plan to use `Store.watchFragment()` and especially why query watchers would not work?

**Comment by teodorpenkov** [comment]
Let's say we have master -> detail relationship.
On the master page we paginate through some data. Tapping on an item open its details, from there we could perform some update operations. The changes are propagated to the master screen via query watchers, but not propagated to the details without some kind of imperative reloading.

On Android it's pretty painful to pass more complex objects between screens, google's shared view model suggested approach is also weird because the master -> detail relationship might be very complex (given that details perform updates etc.).

**Comment by martinbonnin** [comment]
Thanks for the details!

> On the master page we paginate through some data. Tapping on an item open its details, from there we could perform some update operations.

I'm guessing you have one big query for the master page that also loads all the details?

```
query GetPage($page: Int!) {
   items(page: $page) {
    # these are the details 
    id
    title
    thumbnail
    upvotes
  }
}

query GetDetail($id: String!) 
```

> The changes are propagated to the master screen via query watchers, but not propagated to the details without some kind of imperative reloading.

You could use a query watcher for the details page as well:

```
query GetItem($id: String!) {
  item(id: $id) {
    id
    title
    thumbnail
    upvotes
  }
}
```

Then you could use a watcher there as well. incrementing the upvotes would trigger both the master and details watchers. Would that work?

**Comment by teodorpenkov** [comment]
Yes, that's an option, but opening details will make extra query to the server unless I manually update the cache for each node in the master query.

**Comment by martinbonnin** [comment]
> Yes, that's an option, but opening details will make extra query to the server unless I manually update the cache for each node in the master query.

Ideally, a good `CacheKeyResolver` would make it possible to load the details without a network roundtrips. There are some details there: https://www.apollographql.com/docs/android/essentials/normalized-cache/

This API is not easy to grasp so that's definitely an area where we want to make it easier but for this specific use case, I think that'd be the easiest solution.

**Comment by chalermpong** [comment]
Hi @teodorpenkov 

I solved this problem by using the `queryWatcher`, thus I don't need this feature anymore.

For master/detail screen, I use `CacheKeyResolver` below. 

```kotlin
val resolver = object : CacheKeyResolver() {
  override fun fromFieldRecordSet(field: ResponseField, recordSet: MutableMap<String, Any>): CacheKey { 
    return formatCacheKey((recordSet["id"] as? String))
  }

  override fun fromFieldArguments(field: ResponseField, variables: Operation.Variables): CacheKey {
    return formatCacheKey(field.resolveArgument("id", variables) as? String)
  }

  private fun formatCacheKey(id: String?): CacheKey {
    return if (id == null || id.isEmpty()) {
      CacheKey.NO_KEY 
    } else {
      CacheKey.from(id)
    }
  }
}
```
With this code, every record with the field `id` will be stored in ApolloStore with id as its key. Also, every query which contains field `id` will be looked up for a corresponding record in ApolloStore. So when you query `item(id: 'someId')`, it will return the record with 'someId' in ApolloStore.

By the way, I'm not sure if this solution will always working in future release. apollo-ios doesn't resolve cache key like this and I can't use this solution in iOS. 

@martinbonnin Do you have any suggestion about this solution?

**Comment by martinbonnin** [comment]
@chalermpong sorry for the mega delay... We maintain strong backward compatibility during major releases so it should continue working fine.

In general, adding `store.watchFragment` is interesting but would duplicate a lot of the code that's in `CacheInterceptor` so maybe another way to look at this would be to add `client.watchFragment()` that would use the same pipeline as the queries. Obvisously using anything else than `CACHE_ONLY` would fail as no server would understand the fragment but that could be an unified way of handling this.

**Comment by chalermpong** [comment]
@martinbonnin No problem. My app still working smoothly with `queryWatcher` up until now. Thanks for your great work.

I will close this issue now.
