### ISSUE TITLE
Create Interfaces for Request Variables

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#148]
Currently Pojos are being generated for `Operation.Variables`.  When Pojo Generation is off for Response generation, we should flip to generating interfaces for the request objects as well. This way users can extend the interfaces with AutoValue/Immutables to generate request builders and type adapters for whichever json parser they use.

**Comment by sav007** [comment]
As per our decision to drop interface generation support, this issue not valid anymore, closing
