### ISSUE TITLE
Is it possible to read response's extension field in ApolloInterceptor?

### ISSUE THREAD

**Issue by TSurawanwijit** [apollographql/apollo-android#1483]
In my ApolloInterceptor, Is it possible to read cid field in extensions from parsed response ?

Here is the response:
```
{
  "data": {
    ...
  },
  "extensions": {
    "cid": "xxx"
  }
}
```

**Comment by sav007** [comment]
Unfortunately no, Apollo skips extensions part from deserialization.But I think it can be easily added as part of `com.apollographql.apollo.api.Response`

**Comment by martinbonnin** [comment]
Closed with https://github.com/apollographql/apollo-android/pull/1817
