### ISSUE TITLE
Version 1.0.2 not availlable in JCenter

### ISSUE THREAD

**Issue by Sparow199** [apollographql/apollo-android#1492]
Hello, 
I think that there is an issue with the release v1.0.2 which isn't available on the main repository on JCenter, v1.0.1 does.
The jar is available at this repository: https://dl.bintray.com/apollographql/android/
JCenter gives us a very easy sync feature with Maven central, it could be interesting to enable it ? 

Thanks for this amazing project :)

**Comment by martinbonnin** [comment]
1.0.2 is on jcenter at http://jcenter.bintray.com/com/apollographql/apollo/apollo-gradle-plugin/1.0.2/

There's an issue with the coroutines-support artifact. See https://github.com/apollographql/apollo-android/issues/1325 for details. 

For the rest, it should work with 1.0.2

**Comment by Sparow199** [comment]
Hi,
Unfortunately, I'm using Maven on my project, so i need the
apollo-runtime.jar which isn't available on JCenter with v1.0.2 but only
v1.0.1.
I always update my orjject dependency without any issue until this latest
release.
Regards

**Comment by martinbonnin** [comment]
apollo-runtime:1.0.2 is available on jcenter: http://jcenter.bintray.com/com/apollographql/apollo/apollo-runtime/1.0.2/

Or are you expecting it on mavenCentral ? (https://repo.maven.apache.org/maven2) ?

**Comment by Sparow199** [comment]
Great, JCenter is enough but Maven central could be a good thing to add.

**Comment by martinbonnin** [comment]
MavenCentral is on the todo list: https://github.com/apollographql/apollo-android/issues/1130

**Comment by Sparow199** [comment]
Currently, I'm publishing artifacts to JCenter and to avoid the overhead of
Maven central. I created an account in Maven central Nexus and I enabled
the syncing feature in my Bintray account. That's all. Why you didn't use
this way ? The issue is so old.
Regards

**Comment by sav007** [comment]
Dup of #1130
