### ISSUE TITLE
New code generator does not run schema validation

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#1497]
The npm codegen used to run schema validation before running the actual code generation. To be honest, it was really strict. Especially in a case where your schema is really big and has problems in places where you don't even query, it would fail the build with such messages:

```
> Task :network:generateMainApolloIR FAILED
Error: Interface field FooItemInterface.title expects type String! but BaritemInterface.title is type String.
```

In this example, we have inconsistent nullability types between 2 interfaces that are used interchangably. 

When the new codegen is activated, schema verification is not run and this is not detected.

**Comment by sav007** [comment]
Yeah this kind of improvements I want to add.
I assume this is argument validation?

**Comment by tasomaniac** [comment]
If you refer validation of argument in `.graphql` files, this was more than that. Basically npm tool runs validation of the full schema.

For us this has been actually annoying (although helpful). Our backend team is not running the same validation tool. Every now and then, we would update the schema and end-up having validation issues on types/queries that we don't even use.

**Comment by sav007** [comment]
I guess most of validation issues were fixed in latest release, so closing this for now. But if you find any new one pls reopen.

**Comment by tasomaniac** [comment]
Hmm, this was the schema validation. It was a preliminary step before generating code. Js code used to do this. It is gone now. If that's fine, closing is ok.
