### ISSUE TITLE
__typename requirement added to generated response class where codegen hasn't added it to query

### ISSUE THREAD

**Issue by kassim** [apollographql/apollo-android#151]
(possibly an issue of apollo-codegen and not the android class compiler)

The `__typename` requirement `Field.forString("__typename", "__typename", null, false)` is added to generated classes where the generated query string has not had `__typename` inserted - this means responses aren't parsed properly as its stated as non-optional so throws an exception during parsing

**Recreation steps:**
in the sample app, add  `apollo {generateClasses = true}` to the build.gradle, and add the following query to the project 
https://github.com/apollographql/apollo-android/pull/141/files#diff-227b6003770dee5470c3375525cbdc2b

you'll see that the while you can find no generated `QUERY_DEFINITION` or `FRAGMENT_DEFINITION` with `__typename`, you still have the requirement added to the `Node` inner class of AllStarships

Seemingly in this instance, the type name would not be required as there aren't multiple fragments placed together in the query (thus the client should know what to expect), so one solution would be to check whether there are multiple fragments before placing the type name requirement code

**Comment by martijnwalraven** [comment]
Yeah, `apollo-codegen` only added `__typename` to a selection set when it couldn't statically determine the object type. This is a nice optimization, but it isn't worth the extra complexity I think, so I changed it to always add `__typename` (as the Apollo JS client also does).

Updating to `apollo-codegen` 0.10.5 should fix your problem.

**Comment by kassim** [comment]
thanks!
