### ISSUE TITLE
Wrong release name, tag OK (TAG : 1.1.0, Release name : v1.0.1)

### ISSUE THREAD

**Issue by bellierjonathan** [apollographql/apollo-android#1524]
Wrong release name : 
-> TAG : 1.1.0 (OK) 
-> Release name : v1.0.1 (Wrong)

=> https://github.com/apollographql/apollo-android/releases

I know it's not really a issue, but I didn't know where I had to post this 🙂

**Comment by sav007** [comment]
thx! :)
