### ISSUE TITLE
1.1.1-SNAPSHOT not exist on maven

### ISSUE THREAD

**Issue by georgehadly-marleyspoon** [apollographql/apollo-android#1527]
Could not find com.apollographql.apollo:apollo-gradle-plugin:1.1.1-SNAPSHOT when changing it to 1.0.3-SNAPSHOT it'll work fine. I assume that 1.1.1 is the same as 1.0.3.

**Comment by martinbonnin** [comment]
Version 1.1.0 was released a few hours ago. Maybe 1.1.1-SNAPSHOT hasn't reached sonatype servers yet or the CI build failed. That should eventually work.

**Comment by martinbonnin** [comment]
Ok my bad, the snapshot upload is indeed broken :(

https://travis-ci.org/apollographql/apollo-android/builds/575607083
```
Skipping snapshot deployment: wrong JDK. Expected 'oraclejdk8' but was 'openjdk8'.
```

Pull request opened there: https://github.com/apollographql/apollo-android/pull/1528/files

**Comment by georgehadly-marleyspoon** [comment]
Thank you so much. Actually the reason i am using 1.1.1-SNAPSHOT because bitrise faild with older release so i am waiting for the new one and am doing the primary tests in our app.

The related issue -> https://github.com/apollographql/apollo-android/issues/1265

**Comment by martinbonnin** [comment]
Can you try with version `1.1.0` ? It uses a new codegen that doesn't rely on `installApolloCodegen`.

**Comment by georgehadly-marleyspoon** [comment]
@martinbonnin i am still facing the same problem with version 1.1.0 but with version 1.0.3-SNAPSHOT the build succeed.

```
module.js:457
    throw err;
    ^
Error: Cannot find module '/bitrise/src/app/build/apollo-codegen/node_modules/apollo-codegen/lib/cli.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by sav007** [comment]
It should be available soon, as snapshot deployed after PR is merged to master. I've just merged the PR.

**Comment by sav007** [comment]
Should be there now.
