### ISSUE TITLE
Error when building project

### ISSUE THREAD

**Issue by HugoLiconV** [apollographql/apollo-android#1545]
When I'm building the project I'm getting this error: 

```
com.apollographql.apollo.compiler.parser.GraphQLDocumentParseException: 
Failed to parse GraphQL file .../schema.json.graphql (3:7)
Unsupported token `{`
```

and this is the schema.json file
```graphql
query {
  getUsers {
    id
    name
    lastName
  }
}
```

**Comment by narayananiyer86** [comment]
I'm getting the error while building too. Here is the error 

com.apollographql.apollo.compiler.parser.GraphQLDocumentParseException: 
Failed to parse GraphQL file C:\Users\Narayanan KA\Downloads\Android projects\Kickstarter\app\src\main\graphql\activity.graphql (2:35)
Unsupported token `}`
