### ISSUE TITLE
Unable to generate ApolloClasses when switching from 1.0.0 to 1.10

### ISSUE THREAD

**Issue by snijsure** [apollographql/apollo-android#1549]
I switched over from apollo version 1.0.0 to 1.1.0 when I run command ./gradlew  generateApolloClasses

I am getting following error

> Task :app-ui:generateDebugApolloClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app-ui:generateDebugApolloClasses'.
> Failed to parse GraphQL schema introspection query from `/users/subodh/app/android/app-ui/src/main/graphql/com/myapp/android/data/schema.json`

I have schema.json located in src/main/graphql/com/myapp/android/data/schema.json I also have queries, fragments in their individual directories under src/main/graphql/com/myapp/android/data/

Any ideas what could be going wrong. I am using Android gradle plugin 3.5.0,  and gradle version 5.4.1

**Comment by Matej-Hlatky** [comment]
I had same issue with `v1.1.0` while `v1.0.x` was OK. After using `v1.1.1` this problem no longer occur.

**Comment by sav007** [comment]
Yeah, pls try the latest release 1.1.1
