### ISSUE TITLE
The link to the instructions for adding custom types do not work

### ISSUE THREAD

**Issue by BWoodfork** [apollographql/apollo-android#1552]
The wiki here - https://github.com/apollographql/apollo-android/wiki

Has instruction links on adding custom types and non of the links work. I'm having issues converting a GraphQL DateTime to a Joda DateTime currently and was hoping the instructions would be useful.

**Comment by martinbonnin** [comment]
You can find some information in the main README.md: https://github.com/apollographql/apollo-android#custom-scalar-types
