### ISSUE TITLE
Fragments don't respect package names

### ISSUE THREAD

**Issue by AOrobator** [apollographql/apollo-android#1556]
Similar to https://github.com/apollographql/apollo-android/issues/1522, when I declare a fragment  in a particular package, it is ignored and put in com.mytoplevelpackage.fragment.

**Comment by martinbonnin** [comment]
@AOrobator can you check if this has changed in 1.1.x compared to 1.0.x ? If I'm not mistaken, fragments are shared between operations so they have always used the package name of the `schema.json` file

**Comment by AOrobator** [comment]
@martinbonnin This has not changed b/w 1.1.x and 1.0.x. Ideally I can pick and choose the package structure for fragments, as well as mutations and queries

**Comment by sav007** [comment]
Closing as it will be addressed as part of the new plugin.
