### ISSUE TITLE
Is it possible to have virtual field in apollo-android ?

### ISSUE THREAD

**Issue by MarcBrout** [apollographql/apollo-android#1580]
Is it possible to have a virtual field in apollo-android, like described [here](https://www.apollographql.com/docs/tutorial/local-state/#adding-virtual-fields-to-server-data)?

If not, what are the best practices, if any, to manage local states with graphql?

**Comment by sav007** [comment]
Well it's not so simple as it in JS client. It requires to support custom resolver first.
Plus not sure that using Apollo with custom resolvers and virtual fields as the source of state for the app is a good idea. Apollo android is more like network/data layer rather than app state.

**Comment by MarcBrout** [comment]
Okay, thank for the answer.

I think we'll manage some parts of the data state with Room. Synchronizing everything will be kind of challenging I guess.

**Comment by sav007** [comment]
Closing, out of date.
