### ISSUE TITLE
Common fields for interfaces no longer generated with new compiler

### ISSUE THREAD

**Issue by hedvigoscar** [apollographql/apollo-android#1582]
Hi,

We're having an issue where the new compiler is not generating common fields. I'm having a little trouble expressing the issue properly so I will just link to the offending code:

```graphql
query ChatMessages {
  messages {
    ... ChatMessageFragment
  }
}

subscription ChatMessage {
  message {
    ... ChatMessageFragment
  }
}

fragment ChatMessageFragment on Message {
  globalId
  id
  header {
    fromMyself
    statusMessage
    editAllowed
    pollingInterval
    richTextChatCompatible
  }
  body {
    ... on MessageBodySingleSelect {
      type
      choices {
        ... on MessageBodyChoicesSelection {
          type
          value
          text
          selected
          clearable
        }
        ... on MessageBodyChoicesLink {
          type
          value
          text
          selected
          view
          appUrl
          webUrl
        }
        ... on MessageBodyChoicesUndefined {
          type
          value
          text
          selected
        }
      }
    }
    ... on MessageBodyCore {
      type
      text
    }
    ... on MessageBodyFile {
      file {
        signedUrl
      }
    }
    ... on MessageBodyText {
      keyboard
      placeholder
    }
    ... on MessageBodyNumber {
      keyboard
      placeholder
    }
    ... on MessageBodyParagraph {
      id
      text
      type
    }
    ... on MessageBodyAudio {
      id
    }
  }
}
```

`MessageBodyCore` is implemented for every case of the `MessageBody` union, as can be seen here in the schema definition: https://github.com/HedvigInsurance/giraffe/blob/master/src/schema.graphqls#L79

With the previous compiler, the fields `text` and `type` were present on the generated `ChatMessageFragment.Body`-type, but with the new compiler they are not.

**Comment by hedvigoscar** [comment]
It appears that I cannot apply labels myself but I would classify this as `Type: compiler` and `Type: Bug`

**Comment by hedvigoscar** [comment]
I tried adding `apollographql.useExperimentalCodegen=false` in `gradle.properties` (this is where I'm supposed to set it, right?) but it did not appear to resolve the issue.

**Comment by sav007** [comment]
>Common fields for interfaces no longer generated

Are you folks switched to use Kotlin model generation instead of Java?

**Comment by hedvigoscar** [comment]
We are not, but we can absolutely test it out!

For reference, our code is open source and can be found at https://github.com/hedviginsurance/android

**Comment by hedvigoscar** [comment]
I've tested it out now and the same issue persists - I have to explicitly treat the types as `MessageBodyCore`, despite this type being implemented on all possible types for the field `Message.body`.

**Comment by hedvigoscar** [comment]
Additionally, there seems to be some loss of information with multiple inline fragments - only one actually seems to be generated, which I'd consider to be more serious than the parent issue

**Comment by sav007** [comment]
I believe it was fixed with the latest snapshot version.
