### ISSUE TITLE
Add a `generatePublicClassMembers` option.

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#159]
I know this may sound a bit controversial and I totally get the argument behind immutable classes...

... but the world is sometimes imperfect and being able to directly touch the pojos could be very helpful in some occasions. 

I have in mind a use case where the data from the query is displayed in a listView together with data coming from somewhere else. Being able to programmatically instantiate DroidDetails.Data and set its appropriate data.specy.name members would come in handy.

**Comment by sav007** [comment]
@martinbonnin with POJO you have public constructor, is it what you refer to?

**Comment by martinbonnin** [comment]
Do I ? I can only find constructors that take an instance of `ResponseReader reader`

**Comment by sav007** [comment]
Oh sorry it's will be available after PR #156 is merged

**Comment by martinbonnin** [comment]
Ah cool, will look into that.

**Comment by sav007** [comment]
`apollo-compiler:0.2.1-SNAPSHOT` generates public constructor that can be used to manually instantiate model classes. Closing.
