### ISSUE TITLE
Would like a way to manually get transformed query document

### ISSUE THREAD

**Issue by DSteve595** [apollographql/apollo-android#1597]
I'm dealing with an API that has persisted operations, but doesn't support Apollo's APQ. I have to manually upload a manifest of the queries. If I do this using the human-friendly .graphql queries, they're missing the `__typename`s needed, and the operation hashes don't match.
I'd like a way to get the `__typename`'d query documents at build time. They're present in the generated query classes.

**Comment by sav007** [comment]
This feature request is very dangerous, we can't just arbitrarily allow query document manipulation as if we do user can easily messed it up. We have issue to remove unnecessary request of `__typename`  fields, include them only in case inline fragments and fragments. Will it solve this issue?

**Comment by DSteve595** [comment]
I'm not suggesting they be modifiable by the user. Just a read-only output.
Reducing `__typename`s wouldn't solve our issue, as any difference between the user-typed query and the one that Apollo sends will result in a different hash. Adding fragments to the document changes the hash too.

**Comment by sav007** [comment]
Agh, so the idea is to get the graphql query generated by Apollo into some place where you can fetch them?

**Comment by DSteve595** [comment]
Exactly.
