### ISSUE TITLE
JsonArray Parsed as String

### ISSUE THREAD

**Issue by jcnoriega** [apollographql/apollo-android#1600]
I have a column in my database which is of type Jsonb. Now that column stores a json array. This is the data i want to insert:
` "[
          {
            "accuracy": 13.653,
            "latitude": 28.6200792,
            "longitude": 77.37838401,
            "timestamp": "1562596317880"
          },
          {
            "accuracy": 13.653,
            "latitude": 28.62012189,
            "longitude": 77.37840301,
            "timestamp": "1562596318691"
          }]" `

Now, what gets inserted is the following: 
`[{\"accuracy\":3.9,\"latitude\":33.576615,\"longitude\":-111.83568333333332,\"timestamp\":\"2019-09-13T12:17:04.247-07:00\"},{\"accuracy\":3.9,\"latitude\":33.576615,\"longitude\":-111.83568333333332,\"timestamp\":\"2019-09-13T12:17:05.228-07:00\"}]"`

Here is my CustomType Adapter function:

`override fun encode(value: JsonArray): CustomTypeValue<*> {
                return CustomTypeValue.GraphQLJsonString(value.toString())
            }`

I cant use GraphQLJson as it needs a map in its constructor, and i need an Array. So i guess this is a possible bug, as i cant find a way to insert a json array in my database. Or is there something im missing?

**Comment by sav007** [comment]
I'm a little confused from the description of issue. Am I right regarding following:
- You have custom scalar type in GraphQL that is a string but the content is JSON array
- You want to decode / encode map data structure
- Not sure regarding DB, how is DB related to Apollo

**Comment by jcnoriega** [comment]
Hi @sav007 ! Let me re phrase.
In Hasura, I have a column named values, which is of type Jsonb. My Android app, collects gps poisitions for 30 seconds, and then sends it to our server in the form of a JsonArray. Now, I've been having problems trying to send that array, as i mentioned above, when I check in Hasura, that column has a String and not and array.
I want to make a mutation that inserts this:
`"[ { "accuracy": 13.653, "latitude": 28.6200792, "longitude": 77.37838401, "timestamp": "1562596317880" }, { "accuracy": 13.653, "latitude": 28.62012189, "longitude": 77.37840301, "timestamp": "1562596318691" }]"`

But i get this:
`"[{\"accuracy\":3.9,\"latitude\":33.576615,\"longitude\":-111.83568333333332,\"timestamp\":\"2019-09-13T12:17:04.247-07:00\"},{\"accuracy\":3.9,\"latitude\":33.576615,\"longitude\":-111.83568333333332,\"timestamp\":\"2019-09-13T12:17:05.228-07:00\"}]"`

How can i achieve this?

**Comment by sav007** [comment]
Cleanup, closing.
