### ISSUE TITLE
Bug: Can't query `__type` on type `Query`

### ISSUE THREAD

**Issue by ruizmarc** [apollographql/apollo-android#1604]
After upgrading to apollo-android 1.1.3, when trying to generate classes I'm getting the following error:

```
Failed to parse GraphQL file /Users/myuser/android-app/app/src/main/graphql/types.graphql (2:4)
  Can't query `__type` on type `Query`
  ----------------------------------------------------
  [1]:query getNameTypesEnum {
  [2]:    __type(name: "NameTypes") {
  [3]:        nameTypeValues: enumValues {
  ----------------------------------------------------

```

The content of the file is the following: 

```
query getNameTypesEnum {
    __type(name: "NameTypes") {
        nameTypeValues: enumValues {
            name
        }
    }
}
```

With Apollo 1.0.2 it was working fine it seems a regression from previous version.

**Comment by sav007** [comment]
Could you please check if you do have `__type` field on `Query` object in your schema?

**Comment by ruizmarc** [comment]
I have just checked my schema.json and it doesn't seem I have any field called ```__type```under Query fields

**Comment by sav007** [comment]
then it's a valid error, you are trying to request a field that doesn't exist. Either  your schema is not up to date, or query is wrong.

**Comment by ruizmarc** [comment]
But this is the way to query all enum values. I’m doing this way on apollo-angular and Apollo-iOS, and it was working properly on Apollo-Android 1.0.2.

How am I supposed to query all enum values then?

**Comment by sav007** [comment]
Ic, so you are trying to run introspection query via Apollo, interesting.
