### ISSUE TITLE
Modify generated code visibility in Kotlin

### ISSUE THREAD

**Issue by NitroG42** [apollographql/apollo-android#1605]
It would be useful to be able to change default visibility of apollo generated class to be able to set *internal* visibility so using apollo in a child module of a project won't "leak" class in modules that import it. 
It would affect Fragment, Mutation, Query, etc...

I don't think i would be useful in java (or maybe be able to choose package or public visibility).

It should be a Gradle Configuration like 
```
apollo {
  generateKotlinModels = true
  kotlinVisibility = "internal"
}
```
It should changes all generated code visibility, to avoid difficult implementation.

It would be useful for my current project but maybe I'm the only one, what do you think ?

**Comment by sav007** [comment]
That seems like reasonable feature request.
