### ISSUE TITLE
Support for replacing query with operation ID

### ISSUE THREAD

**Issue by tmtrademarked** [apollographql/apollo-android#1607]
This is a slightly specific feature request, but I'm curious if other users have a need for something like this as well. In our tech stack, we use a Rails server running the GraphQL Pro ruby gem (https://graphql.pro), which implements persisted queries slightly differently than Apollo's Auto Persisted Queries feature.

We're trying to figure out if there's a good way to use the rest of the Apollo client side stack here, but basically just swap out the persisted query on our side. Technically, this is pretty easy if you can control where the server request gets written - you just need to *not* write the "query" into the JSON, and instead provide "operationID" with a value.

So I think the more generalizeable form of this feature request is something like "Allow us to plug into ApolloServerInterceptor and replace the query body with a key/value of the application's choosing." On our end, we can easily map from the operation name to the appropriate value to send - there's just no obvious way to hook into the server interceptor that I can see, since it's the last interceptor in the stack.

What does this community think? I don't think such a feature would be particularly difficult to implement, and it would definitely enhance our ability to use this stack. I'm happy to propose some sort of interface/design here for feedback if there's interest, but don't want to waste anyone's time barking up a tree that's either not worthwhile, already been solved, or otherwise not valued here.

**Comment by tmtrademarked** [comment]
As I dig a little further, this may already be supported today via an ApplicationInterceptor. It seems like the combination of an interceptor that sets the `sendQueryDocument` field and a custom Operation wrapper could possibly provide the mechanism I need here. I'll investigate this further.

**Comment by DSteve595** [comment]
Similar scenario here. I think it might be possible to do this with a custom re-implementation of `ApolloNetworkInterceptor`, but that might break the chain and potentially cause other problems.

**Comment by DSteve595** [comment]
Did some deeper digging. I think the best way to achieve this is to use a custom client, avoiding `ApolloClient` entirely. This seems counter-intuitive, but apollo-runtime's public API exposes almost everything needed to run the queries ourselves.

Here's an example of manually running a query with OkHttp:
```kotlin
val scalarTypeAdapters = ScalarTypeAdapters(emptyMap())

fun <D : Operation.Data, T, V : Operation.Variables, O : Operation<D, T, V>> execute(
  operation: O,
  usePersistedId: Boolean = true
): Response<T> {
  return Request.Builder()
    .url("https://gql.yourapi.example/")
    .post(createApolloRequestBody(operation, usePersistedId))
    .build()
    .let(okHttpClient::newCall)
    .execute()
    .let { httpResponse ->
      OperationResponseParser(operation, operation.responseFieldMapper(), scalarTypeAdapters)
        .parse(httpResponse.body!!.source())
    }
}

private fun <D : Operation.Data, T, V : Operation.Variables, O : Operation<D, T, V>> createApolloRequestBody(
  operation: O,
  usePersistedId: Boolean
): RequestBody {
  val content = run {
    val buffer = Buffer()
    JsonWriter.of(buffer).use { writer ->
      writer.serializeNulls = true
      writer.beginObject()
      if (usePersistedId) {
        writer.name("operationID").value(/* Your operation's persisted ID */)
      } else {
        writer.name("query").value(operation.queryDocument())
        writer.name("operationName").value(operation.name().name())
      }
      writer.name("variables").beginObject()
      operation.variables().marshaller()
        .marshal(CustomInputFieldWriter(writer, scalarTypeAdapters))
      writer.endObject()
      writer.endObject()
    }
    buffer.readByteString()
  }
  return content.toRequestBody("application/json".toMediaTypeOrNull())
}
```

The only missing piece is `CustomInputFieldWriter`; this should basically be an implementation of `InputFieldWriter` similar to `InputFieldJsonWriter`, but using your json library of choice. I used Moshi, which was mostly a drop-in replacement, switching the `JsonWriter` import from apollo-runtime's to Moshi's.

Works well on my end.

**Comment by tmtrademarked** [comment]
I actually ended up finding a pretty simple way to achieve this myself which requires a bit less custom work on our end. Since Apollo uses OkHttp under the hood, the easiest way to do this is by simply leveraging OkHttp's interceptor stack.

So when we create our ApolloClient, we add an interceptor to the stack that knows how to manipulate these queries. It reaches into the json body and swaps it out from under the ApolloClient before it makes it to our server. (This is also useful if there's other annotations/headers/etc that you wish to send along to your server)

I think this can probably be closed now, unless there's a strong need to actually implement some better support in the Apollo client itself. Any objections from the community?

**Comment by martinbonnin** [comment]
I think it would make sense to have an option on the `ApolloClient`:

```
/**
 * If you're using persisted queries, pass true to skip sending the queryDocument to your server and instead rely on operationId.
 */
fun ApolloClient.skipQueryDocument(boolean skip) {
}
```

That would save some CPU cycles and (most likely ?) allow R8/proguard to strip `Operation.queryDocument()`

**Comment by sav007** [comment]
Should it be in `ApolloCall.skipQueryDocument(boolean skip)` instead of global configuration? Or sending operation id instead of query document is used for all queries?

**Comment by martinbonnin** [comment]
> Should it be in ApolloCall.skipQueryDocument(boolean skip) instead of global configuration?

Yea, global configuration is certainly better, I don't think this needs to be changed at runtime.
