### ISSUE TITLE
Drop :apollo-converters:moshi support

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#161]
Apollo retrofit response converter based on Moshi library is no longer supported in favour of POJO converter. Drop module `:apollo-converters:moshi` and make POJO to be default one.
Rename module `:apollo-converters:pojo` -> `:apollo-converter`

**Comment by kassim** [comment]
you mean request converter? the Moshi converter plugin doesn't have response conversion

I was about to post an issue about a namespace / class labelling issue (Moshi converter being `com.apollographql.android.ApolloConverterFactory` while POJO being `com.apollographql.android.converter.pojo.ApolloConverterFactory`) but equally support dropping of the Moshi converter

In my opinion it would be nice to have the default converter support the previous format of
`@POST("/") Observable<Response<FilmsData>> allFilms(@Body Films query);`
that the Moshi plugin provided, as this current format
`@POST("/") Observable<Response<Films.Data>> allFilms(@Body OperationRequest<Operation.Variables> query);` 
doesn't seem as presentable

**Comment by sav007** [comment]
@kassim you can always create own class that extends `OperationRequest` like `FilmsRequest extends OperationRequest<Films.Variables>` and then pass  `allFilms(@Body FilmsRequest request)`
