### ISSUE TITLE
NumberFormatException: For input string: "null"

### ISSUE THREAD

**Issue by mahdidelavar** [apollographql/apollo-android#1613]
when i use generateKotlinModels , apollo cannot generate models correctly 

```
          "inputFields": [
            {
              "name": "latitude",
              "description": null,
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "Float",
                  "ofType": null
                }
              },
              "defaultValue": "null"
            },
            {
              "name": "longitude",
              "description": null,
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "Float",
                  "ofType": null
                }
              },
              "defaultValue": "null"
            }
          ],
```
This is part of  my schema.json that default value set to "null" for latitude and longitude 

When i use ```generateKotlinModels = true```  I am getting compile error ```java.lang.NumberFormatException: For input string: "null"```
But when i use java models that's ok 

I resolved this issue with change default value to "0.0" but i think it's not a best solution because "defaultValue": "null" set to all of my inputs

**Comment by sav007** [comment]
Well technically this is an issue with the schema, as instead of `"defaultValue": "null"` it must be `"defaultValue": null`
