### ISSUE TITLE
Add data about customTypeMapping to META-INF

### ISSUE THREAD

**Issue by budius** [apollographql/apollo-android#1621]
This is a follow-up to my previous PullRequest (https://github.com/apollographql/apollo-android/pull/1592#issuecomment-533121804)

To make the sharing of custom type adapters streamlined and easier to implement, ideally, the apollo-gradle plugin would:

- create `META-INF/apollo.mappings` file and add there information about the declared custom mappings; (those would be added to `jar` and `aar` files)
- read the file `META-INF/apollo.mappings` from the dependencies and process the information declared there the same way as declared directly on `build.gradle`.

That way any custom mapping applied to a "network" module, would get automatically injected on projects that uses this dependency.

**Comment by martinbonnin** [comment]
Hi @budius! I know it's been a super long time but have you looked at [multi module support](https://www.apollographql.com/docs/android/advanced/multi-modules/) ? That should allow you to share the custom types from modules in the the same root project. 
Publication is not handled yet but that could be done if you're having a use case.

**Comment by martinbonnin** [comment]
I'm going to close this one now that multi-modules support is out. Please leave a comment if that doesn't work for you and I'll reopen it.

**Comment by budius** [comment]
hi @martinbonnin thanks for the feedback and sorry I took forever to reply.
Reality is, my current projects don't use graph-ql anymore, but to be honest I'm looking forward to use the tech again in the future.
