### ISSUE TITLE
Multiple type validation in new compiler

### ISSUE THREAD

**Issue by vladyslavverbytskyi** [apollographql/apollo-android#1628]
I have a query, that receives list of nodes of multiple types. And these types contain different fields:
```
fragment messagesListResponse on Driver {
    messages(after: $after, before: $before, first: $first, last: $last, filters: $filters) {
        edges {
            cursor,
            node {
                ...centerMessage
                ...driverMessage
            }
        }
    }
}

fragment centerMessage on IncomingMessage {
    id,
    title,
    body,
    type,
    status,
    sendTime,
    expirationTime
}

fragment driverMessage on OutcomingMessage {
    id,
    body,
    sendTime
}
```

It worked well with an old compiler, but it doesn't work with a new one.
As I understand, the reason for that is in different approaches:

Here is a generated mapper's code of the old compiler version:
```
public static final class Mapper implements FragmentResponseFieldMapper<Fragments> {
        final CenterMessage.Mapper centerMessageFieldMapper = new CenterMessage.Mapper();

        final DriverMessage.Mapper driverMessageFieldMapper = new DriverMessage.Mapper();

        @Override
        public @NotNull Fragments map(ResponseReader reader, @NotNull String conditionalType) {
          CenterMessage centerMessage = null;
          DriverMessage driverMessage = null;
          if (CenterMessage.POSSIBLE_TYPES.contains(conditionalType)) {
            centerMessage = centerMessageFieldMapper.map(reader);
          }
          if (DriverMessage.POSSIBLE_TYPES.contains(conditionalType)) {
            driverMessage = driverMessageFieldMapper.map(reader);
          }
          return new Fragments(centerMessage, driverMessage);
        }
      }
```

And here is the same part, but with a new version:
```
public static final class Mapper implements FragmentResponseFieldMapper<Fragments> {
        final CenterMessage.Mapper centerMessageFieldMapper = new CenterMessage.Mapper();

        final DriverMessage.Mapper driverMessageFieldMapper = new DriverMessage.Mapper();

        @Override
        public @NotNull Fragments map(ResponseReader reader, @NotNull String conditionalType) {
          CenterMessage centerMessage = centerMessageFieldMapper.map(reader);
          DriverMessage driverMessage = driverMessageFieldMapper.map(reader);
          return new Fragments(centerMessage, driverMessage);
        }
      }
```

As we can see, using previous version, Apollo checks validity of the type and always return `Fragment` with either one of objects or 2 nulls.

But newest version does't have that checking part. So it tries to map response to all available types, but fails, because these models contain different field, so when, for instance, `OutcomingMessage` is available in reader, it tries to crate `centerMessage` using that reader. `OutcomingMessage`  contains own preset of fields, so mapper consumes id, because id is available in `OutcomingMessage` as well, but it fails when trying to access to `title` field, because it doesn't exist for that type of object.

Is it an expected behavior, that new code generator skips that check part or you're planning to restore it in next releases?

**Comment by sav007** [comment]
Could you please try the snapshot version as it supposed to be addressed via https://github.com/apollographql/apollo-android/pull/1608

**Comment by vladyslavverbytskyi** [comment]
Have tried.
Snapshot version 1.2.0 works correctly, generates the same code as in the previous version of mapper.
