### ISSUE TITLE
CustomTypeAdapter not working as expected

### ISSUE THREAD

**Issue by BreSmit521** [apollographql/apollo-android#1634]
Version: 1.1.3

Issue: I am receiving a DateTime object from a server and am attempting to parse as a Date but every time the object returns I get a parse exception: 
`
java.lang.IllegalArgumentException: Can't map GraphQL type: DateTime to: class java.util.Date. Did you forget to add custom type adapter?
`

build.gradle:
`
apollo {
  customTypeMapping = ["DateTime": "java.util.Date"]
}
`

ApolloClient:
![image](https://user-images.githubusercontent.com/12717711/65792120-b4d04400-e128-11e9-994a-5292830e00ba.png)

CustomTypeAdapter (Yes I realize the value on this is not what I'm receiving from server, just trying to get it to work first):
![image](https://user-images.githubusercontent.com/12717711/65792142-c0236f80-e128-11e9-8d08-bd40f5377f00.png)

If you need any more information let me know.  Thanks in advance.

Edit: Formatting

**Comment by sav007** [comment]
Smth not right, it looks like your adapter wasn't added to the client. Is there anyway you can check that ApolloClient instance has this adapter you add? Second guess could you check that generated `CustomType.DATETIME` has correct `typeName== DateTime `

**Comment by BreSmit521** [comment]
The Apollo Client does have the adapter but the class that's listed is of whatever the parent class the adapter is located in. Also, I did verify the type is correct in the generated Custom Type file

**Comment by BreSmit521** [comment]
No breakpoints within the CustomTypeAdapter that I passed in are hitting either.  Also, I did try implementations in both Java and Kotlin just to be sure, both had the same results

**Comment by sav007** [comment]
Is it possible to see generated query and the full stack trace of exception?

**Comment by BreSmit521** [comment]
I will verify tomorrow.  But I do believe I narrowed down the issue.  This appears to only happen when the client(s) are injected via Koin.  I started a small app from scratch and everything worked as expected then when I moved the Apollo and OkHttpClients to a koin module the error returned.

**Comment by budius** [comment]
@BreSmit521 I made a PR for that exact issue https://github.com/apollographql/apollo-android/pull/1592
I'm kind of waiting for it go get released too. In the meantime, I've added to the server API a `addGraphQAdapter()` method so the module can re-register for their own types.

**Comment by BreSmit521** [comment]
@budius That's awesome news! Thanks a lot for the reply and I will keep an eye on that PR
