### ISSUE TITLE
Default parameters fail to be generated for Input Types

### ISSUE THREAD

**Issue by AOrobator** [apollographql/apollo-android#1652]
Apollo v1.2.0

I have an `input` type in my schema with default parameters.

```graphql
input ObjectQuery {
  count: Int! = 20
  order: Sort! = DESC
}
```

The Kotlin models generated from this schema don't have these default parameters.

**Comment by hameno** [comment]
I think I'm getting a related error, it generated the following code which fails to compile:

    val properties: Input<List<PropertyInput>> = Input.optional(listOf(""))

Schema:

``` 
input PropertyInput {
    key: String!
    value: String!
}
input Filter {
    properties: [PropertyInput!] = []
}
```

**Comment by sav007** [comment]
@AOrobator super strange, we do have tests for this: https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/input_object_type/type/ReviewInput.kt

Could you please check that schema json has those default values for `ObjectQuery`?

@hameno It's a different error, I will take a look.

**Comment by AOrobator** [comment]
@sav007 I can verify that `ObjectQuery` specifies default values in schema.json. Let me know if I can provide additional info

**Comment by sav007** [comment]
@AOrobator may I get `schema.json` file somehow? You can DM it in slack.

**Comment by sav007** [comment]
@hameno PR to fix your issue is up https://github.com/apollographql/apollo-android/pull/1659

**Comment by sav007** [comment]
@AOrobator was this issue for Java or Kotlin models?

**Comment by AOrobator** [comment]
Kotlin models

**Comment by AOrobator** [comment]
Don't think I can send over my schema. I'll work on reproducing with a sample schema

**Comment by AOrobator** [comment]
Here's a snippet of the schema

```json
{
  "kind": "INPUT_OBJECT",
  "name": "ObjectQuery",
  "description": "",
  "fields": [],
  "inputFields": [
    {
      "name": "field1",
      "type": {
        "kind": "NON_NULL",
        "name": null,
        "ofType": {
          "kind": "SCALAR",
          "name": "String",
          "ofType": null
        }
      },
      "defaultValue": null
    },
    {
      "name": "field2",
      "type": {
        "kind": "SCALAR",
        "name": "String",
        "ofType": null
      },
      "defaultValue": null
    },
    {
      "name": "start",
      "type": {
        "kind": "SCALAR",
        "name": "String",
        "ofType": null
      },
      "defaultValue": null
    },
    {
      "name": "order",
      "description": "",
      "type": {
        "kind": "NON_NULL",
        "name": null,
        "ofType": {
          "kind": "ENUM",
          "name": "Sort",
          "ofType": null
        }
      },
      "defaultValue": "DESC"
    },
    {
      "name": "count",
      "type": {
        "kind": "NON_NULL",
        "name": null,
        "ofType": {
          "kind": "SCALAR",
          "name": "Int",
          "ofType": null
        }
      },
      "defaultValue": "20"
    }
  ],
  "interfaces": [],
  "enumValues": [],
  "possibleTypes": []
}
```

`field2` and `start` both have default parameters when code is generated.
