### ISSUE TITLE
Update normalized cache with results from a mutation

### ISSUE THREAD

**Issue by japplin** [apollographql/apollo-android#1655]
Looking at the apollo android documentation I don't see a reference to it supporting this functionality: https://www.apollographql.com/docs/android/essentials/mutations/

**Comment by sav007** [comment]
Sorry not sure I understand what functionality is not supported? Mutation operations do update normalized cache.

**Comment by japplin** [comment]
I thought I'd read on the apollo site that it isn't supported on android, but I can't seem to find that on the site anymore. It was just an issue on my end and it's working now. Sorry about the noise.
