### ISSUE TITLE
Update sample app to be aligned with iOS

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#166]
See https://github.com/apollographql/frontpage-ios-app

**Comment by nubstick27** [comment]
Hello, I would love to contribute for this Issue. I am thinking to port the `frontpage-ios-app` to the `apollo-sample` directory.

**Comment by marwanad** [comment]
The sample iOS app uses the frontpage-server https://github.com/apollographql/frontpage-server which isn't hosted publicly. It would require running a local instance of that server.

Closing for now.
