### ISSUE TITLE
Issue when use apollo with Clean Architecture

### ISSUE THREAD

**Issue by minhbnt-1512** [apollographql/apollo-android#1661]
I use clean architecture with 3 modules are `data`, `domain`, `app`. I tried to generate Kotlin classes from .graphql files. But I can only generate them successfully when I added the Apollo plugin below the `com.android.application` plugin in module `app`. If I add the Apollo plugin below the `com.android.library` plugin in module `data` then Kotlin classes aren't generated.

**Comment by martinbonnin** [comment]
That should work. Obviously your .graphql files must be in the same module as the one where you apply the apollo plugin. But it should work. Can you provide a small sample that reproduces your issue if it does not ?

**Comment by sav007** [comment]
Cleanup, closing.
