### ISSUE TITLE
how to parse timestamp or isoDate.

### ISSUE THREAD

**Issue by teknolojia** [apollographql/apollo-android#1669]
I have a query which returns timestamp or isoDate using [type-graphql](https://typegraphql.ml). Every time I included those fields in query I get this error `failed to parse http response`.

I tried this line but it doesn't work:
```
apollo {
    customTypeMapping = [
         "Date" : "java.util.Date"
    ]
}
```

**Comment by martinbonnin** [comment]
You will also need to register the adapter. See https://github.com/apollographql/apollo-android#custom-scalar-types

**Comment by sav007** [comment]
Cleanup, closing.
