### ISSUE TITLE
Update Readme to reflect new api 

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#167]
Since the sample app was changed to use GitHub api, we should update the Readme to have a corresponding sample.

**Comment by dmathewwws** [comment]
I can help with this and #297, let me know if/when the RC1 api is stable enough for me to update the readme.

**Comment by digitalbuddha** [comment]
Its stable update away ☺️ I'll make changes if anything else needs it

**Comment by marwanad** [comment]
closed by #378.
