### ISSUE TITLE
Is is possible to send default language of device in all query 

### ISSUE THREAD

**Issue by HoussemHfaidh** [apollographql/apollo-android#1670]
i want to send the language of device in all query or mutation graphql

**Comment by sav007** [comment]
Could you please elaborate more on this? Do you mean default value for arguments (if yes then they must be defined in your GraphQL schema, otherwise you always need to provide them)

**Comment by HoussemHfaidh** [comment]
i want to add Add LANGUAGE in header

**Comment by Sparow199** [comment]
I think that you have to take a look to OkHttp client and add an interceptor in order to inject the LANGUAGE header in each sensed query.
https://stackoverflow.com/questions/32196424/how-to-add-headers-to-okhttp-request-interceptor

**Comment by sav007** [comment]
You can provide your own OkHttp client `com.apollographql.apollo.ApolloClient.Builder#okHttpClient` with custom interceptor.
