### ISSUE TITLE
singularization of names ending with a

### ISSUE THREAD

**Issue by jporcelli-tt** [apollographql/apollo-android#1686]
Is there a flag to not have the kotlin code gen change classes that end with a to end with um?

**Comment by martinbonnin** [comment]
You have `apollo.useSemanticNaming`. Is this what you are looking for ?

**Comment by jporcelli-tt** [comment]
yes that would be nice. I have classes that end with a, e.g. Cta, and there getting renamed to Ctum

**Comment by sav007** [comment]
Yeah the issue that it's very hard to handle this case, our rule for your case is: `"([ti])a$" to "$1um"`

https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/Inflector.kt#L31

Not really sure how to handle this as `Cta` is not a word even. You can always try to use alias with different name to avoid this.

**Comment by jporcelli-tt** [comment]
Other people I work with on iOS have had similar complaints for different words, naming. I think making this optional would be best. Is there a reason that this is necessary to do?

**Comment by martinbonnin** [comment]
@jporcelli-tt Do you still have the problem on 1.3.0 ?

**Comment by sav007** [comment]
Closing, out of date.
