### ISSUE TITLE
Generation of nested structures with the same name results in compiler errors

### ISSUE THREAD

**Issue by nubstick27** [apollographql/apollo-android#169]
There appears to be an issue with nested structures which define the same name multiple times. 

Briefly, a structure such as:
```
mutation UpvotePost($postId: Int!) {
  upvotePost(postId: $postId) {
    ...PostDetails
  }
}
```

results in a generated class like:
```
public final class UpvotePost implements Mutation<UpvotePost.Variables> {
    public static class Data implements Operation.Data {
        public static class UpvotePost { ... }
    }
}
```

which has a compilation error.

**Comment by sav007** [comment]
We are going to use the same logic for resolving dup names by adding `$` as suffix, so in this case we ate going to have `UpvotePost$`
