### ISSUE TITLE
for each not applicable to type

### ISSUE THREAD

**Issue by Sora236** [apollographql/apollo-android#1690]
I tried fetching the Data from a query and wanted to use a for-each loop like in your example:
located @ [https://github.com/apollographql/apollo-android#consuming-code:](https://github.com/apollographql/apollo-android#consuming-code)

for (FeedQuery.Data.Feed feed : dataResponse.data().feed()) {

but when I try it, androidstudio tells me that for each is not applicable to the type from my dataresponse. Is it because of something related to the API that I am using (Smash.gg)? I also cant seem to use .Data.Feed, I can only use .Data.Mapper or .Data.class

this is the error I am getting: [http://puu.sh/EuI3z/cb7f7e3dd1.png](http://puu.sh/EuI3z/cb7f7e3dd1.png)

This is the first time I am using an API/queries in general so I am sorry if my questions seem stupid but I dont know where else to ask.

Thank you for your time

**Comment by martinbonnin** [comment]
According to https://developer.smash.gg/docs/examples/queries/tournaments-by-videogame, you'll most likely need to interate on `tournaments.nodes()`

**Comment by Sora236** [comment]
> According to https://developer.smash.gg/docs/examples/queries/tournaments-by-videogame, you'll most likely need to iterate on `tournaments.nodes()`

Thanks a lot, that was part of the issue, they actually updated the API in the meanwhile and when I tried fixing the code with your help, Androidstudio assisted me in fixing the rest. Now it works, this is the working result: [http://puu.sh/EuKY0/c0a3856fc6.png](http://puu.sh/EuKY0/c0a3856fc6.png)
