### ISSUE TITLE
Add ErrorPolicy to the Android Library

### ISSUE THREAD

**Issue by Wumpkins** [apollographql/apollo-android#1700]
Hi, 

I am looking to handle GraphQL errors gracefully when there is partial data available, rather than completely error out. I found this online (https://www.apollographql.com/docs/react/data/error-handling/), but it seems that it only applies to the React library. I looked through the Android code base for Apollo and did not find anything similar. If there exists some way to handle errors gracefully, please let me know. Otherwise I would be very grateful if we could add some similar feature to the Android library.

Thanks!

**Comment by martinbonnin** [comment]
As far as I can tell, you can use `com.apollographql.apollo.api.Response.errors()` to get the list of errors. Would that work for you ?

**Comment by Wumpkins** [comment]
Yes it works. Thanks!
