### ISSUE TITLE
ApolloSchemaIntrospectionTask is no longer available.  what is the alternative?

### ISSUE THREAD

**Issue by felixchez** [apollographql/apollo-android#1701]
try to upgrade to the latest v1.2.0 and found out that `ApolloSchemaIntrospectionTask` is not available anymore.  What will be the alternative for creating a task in gradle for using pre-installed apollo-codegen?

**Comment by martinbonnin** [comment]
Cross posting from https://github.com/apollographql/apollo-android/issues/928:

@felixchez if you're willing to try the snapshots and the incubating plugin, there's a downloadXYZSchema task: https://github.com/apollographql/apollo-android#incubating-plugin

**Comment by gshcherb** [comment]
@martinbonnin For some reason I cannot reference `service` dsl tag in 1.2.1 release, but it works well if I switch to incubating `1.2.1-SNAPSHOT` version.

**Comment by martinbonnin** [comment]
@gshcherb what is the error you get ?

**Comment by gshcherb** [comment]
If I just specify 
`classpath "com.apollographql.apollo:apollo-gradle-plugin:1.2.1"`

it gives me 

`> Could not find method service() for arguments [test, build_ds8arb4a7liclz9gw4nxu3fm3$_run_closure2$_closure9$_closure16@3979b797] on object of type com.apollographql.apollo.gradle.ApolloExtension.
`

with the same gradle files

`classpath 'com.apollographql.apollo:apollo-gradle-plugin-incubating:1.2.1-SNAPSHOT'` works fine though.

**Comment by martinbonnin** [comment]
`service` is only in the incubating plugin so you will have to use `com.apollographql.apollo:apollo-gradle-plugin-incubating:1.2.1`  for the time being.

**Comment by sav007** [comment]
As Martin said it will be fixed with a new incubating plugin. Closing for now.

**Comment by adrian-baker** [comment]
What about inspecting a .graphqls schema thats on the local file system? This was our approach in previous versions.
