### ISSUE TITLE
Better RxJava understanding/docs

### ISSUE THREAD

**Issue by tir38** [apollographql/apollo-android#1704]
I'm following the limited RxJava support docs https://github.com/apollographql/apollo-android#rxjava2-support

I don't quite understand why a `StoreOperation` maps to a `Single` and `Calls` and `Queries` map to `Observables`. IIUC a store operation is a hit to the local cache, whereas calls and queries are remote requests. What if I expect my remote request to return a single response, not a stream of responses? Should that not also be mapped to a `Single`?

**Comment by martinbonnin** [comment]
The reason is that `Queries` will return several values: usually one for the cached response and one for the network response.

**Comment by tir38** [comment]
What if I only want a network response? I.e. if I know the value is not cached yet? Can I still use a `Single`?

**Comment by martinbonnin** [comment]
Yes, you can use all the RxJava magic for that. Stuff like `Observable.toSingle()`, etc...

**Comment by tasomaniac** [comment]
Closing this since the new docs are little better. This behavior is also documented in it's javadoc. Since there is no guarantee that it will return a Single object, the Return type cannot be a Single. 

As Martin mentioned, RxJava has couple of operations to convert to Single type.
