### ISSUE TITLE
PROBLEM with Subscriptions

### ISSUE THREAD

**Issue by arnaumartifont** [apollographql/apollo-android#1706]
I have a situation that using a subscription x2 or more times that is being called with the same parameters and throws the error "already subscribed", I understand that if I disposed the previous subscription there is no active subscription at this point right? this is a problem i'm not relating it now but this wouldn't have to happen.
The big problem comes when I want to use the same subscription call again with new parameters and this subscription doesn't work anymore, it gets "subscribed" but doesn't throw any response when it have to or error or anything, the Web Socket is still open (other subscriptions still working).

**Comment by sav007** [comment]
In order to execute the same subscription after it disposed you can call `com.apollographql.apollo.ApolloSubscriptionCall#clone`

**Comment by arnaumartifont** [comment]
Already tried that and it doesn't solve the problem,  also both approaches using it through Rx2Apollo and without it, the problem persists, the thing is the subscription works fine until it throws an error when is already subscribed and if I try a new same subscription of the same type (ApolloSubscriptionCall) with other parameters it doesn't work.

**Comment by arnaumartifont** [comment]
@sav007 Do you have any other suggestion or is it really a bug to solve?

**Comment by sav007** [comment]
Could you please provide a sample of parameters for your query?

**Comment by ruizmarc** [comment]
I'm faceing this same issue:

1. First subscription works (let's call it pointsSubscription).
2. I dispose the subscription
3. I subscribe again to pointsSubscription with same params that I did in 1.
4. I get  "already subscribed" error. (I don't think I should receive this error, as subscription 1 was disposed. 
5. I subscribe to pointsSubscription with different params than 1 and 3. 
6. I never receive any update from the subscription. (It is a problem with the lib, as there are updates happening while subscribed, but not receiving them)

So, from my point of view, we have two problems here: 2 and 6.

**Comment by sav007** [comment]
> I dispose the subscription

How do you dispose it? Are you sure that it was disposed? As `already subscribed` means that subscription is still active.

Meantime I'm trying to replicate this issue locally on sample app, but for now with no luck.

**Comment by sav007** [comment]
Alright I guess I have explanation what is going on here:
1. It seems that there is some race condition on your side, as it looks that previous subscription is not disposed before you add a new one (with the same subscription) that leads to `already subscribed` error.
2. Because second subscription failed, internally it will  call `unsubscribe`, that will unsubscribe first active subscription as well (these 2 subscriptions have the same internal id that is used to track active subscriptions).

I will check if we can lift the restriction on having unique subscriptions, I think it makes sense to be able to have multiple subscriptions with the same query.

**Comment by arnaumartifont** [comment]
Yes thanks, I focused more explaining the second problem being the subscription unusable after the problem you just mentioned occurred.
