### ISSUE TITLE
Catching Exceptions from coroutines

### ISSUE THREAD

**Issue by fluxxion82** [apollographql/apollo-android#1709]
I'm having an issue catching ApolloExceptions when using coroutines. I've been using `toChannel()` recently, but updated to the latest version to get `toFlow()` extensions, but when I surround the apollo class with try/catch blocks, I'm not able to catch any ApolloExceptions. I recently read a blog post where they were calling `toDeferred().await()` and they said transport errors will be thrown in await, but all the ApolloExceptions are ending up in my default unhandled exception handler. I'm putting layers of try/catch blocks around everything I can think of but can't catch anything. If I use the ApolloCall.Callback with `enqueue`, I can get exceptions from the `onFailure` method. When using the coroutine extensions, one of the exceptions I'm trying to catch is coming from the ApolloParseInterceptor's parse method and I feel like I should be catching it. Is there anything I'm missing or any suggestions on what I can try?

**Comment by fluxxion82** [comment]
So I seem to catch the exception when I change the caching policies to NETWORK_ONLY from CACHE_AND_NETWORK, but somehow an exception is getting threw and getting caught in the default uncaught handler sometimes. It's inconsistent when I catch the exception and when i don't. The stack trace looks the same so I have no idea what's going on.

**Comment by martinbonnin** [comment]
We have a basic test for a parsing error there: https://github.com/martinbonnin/apollo-android/blob/1dab62c25b271846117c439aebb4afa266be17cd/apollo-integration/src/test/java/com/apollographql/apollo/CoroutinesApolloTest.kt#L78.

Can you reproduce this error all the time ? If yes, any chance you could share a code snippet ?

**Comment by fluxxion82** [comment]
The test is setting the response code to 200, but the exceptions we're expecting are 4xx and 5xx...not sure if that matters. Also, slightly different from that the test is our apolloCall looks like this: 

```
apolloClient.query(EpisodeHeroNameQuery(Input.fromNullable(Episode.EMPIRE)))
    .httpCachePolicy(HttpCachePolicy.NETWORK_FIRST)
    .responseFetcher(ApolloResponseFetchers.CACHE_AND_NETWORK)
    .toChannel() // been using toDeferred().await() lately but I think this also works the same
```
and with those caching policy values I don't seem to catch any of the exceptions but when I change the cache policies to `NETWORK_ONLY`, I seem to catch exceptions sometimes.
I am able to reproduce the issue consistently in our code base. However, I can't share that code. I can try to see if I can reproduce the issue in those tests. There are some cases that might be tricky to reproduce, but hopefully I'll reproduce at least one of the cases.

**Comment by fluxxion82** [comment]
I'm having a lot of trouble getting the repo/sample project running...something about an NDK toolchain for a certain ABI. I'll try to find time to create a test project that hopefully recreates this issue.

**Comment by martinbonnin** [comment]
Having a test case would be great. Also, slightly related but I think there are too many extensions for coroutines. I was considering deprecating the `toChannel` extensions to use only Flows now that they are stable. Maybe we could focus our efforts there ?

**Comment by edenman** [comment]
Any progress on this?  I'm currently using deferred/await but I'd like to switch to Flow so I can start using `CACHE_AND_NETWORK` but I can't tell how to handle `ApolloNetworkException`/`ApolloHttpException` in those cases

**Comment by edenman** [comment]
Got it working!

```
fun <T> ApolloCall<T>.toMyResponseFlow(): Flow<MyResponse<T>> {
  return toFlow()
    .map { response -> response.toMyResponseWrapper() }
    .catch { e ->
      val exceptionResponse = exceptionToMyResponseWrapper(e)
      if (exceptionResponse == null) {
        // Unknown exception type: re-throw it.
        throw e
      } else {
        emit(exceptionResponse)
      }
    }
    .filterNotNull()
}
```

**Comment by edenman** [comment]
(I would be very in favor of deprecating `toChannel` and adding `toFlow` to https://www.apollographql.com/docs/android/advanced/coroutines/ )

**Comment by sav007** [comment]
Closing.
