### ISSUE TITLE
Gradle DSL method not found: 'compileOnly()'

### ISSUE THREAD

**Issue by moun3iim** [apollographql/apollo-android#1718]
I'm trying to add apollo-android to my android project (Kotlin) and I've faced this error
```
Gradle DSL method not found: 'compileOnly()'
Possible causes:
The project 'My Application' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
Upgrade plugin to version 3.5.1 and sync project

The project 'My Application' may be using a version of Gradle that does not contain the method.
Open Gradle wrapper file

The build file may be missing a Gradle plugin.
Apply Gradle plugin
```
it's happen when I add these dependencies to my project's `build.gradle`
```
dependencies {
  compileOnly 'org.jetbrains:annotations:13.0'
  testCompileOnly 'org.jetbrains:annotations:13.0'
}
```
any help on how to fix it?

**Comment by moun3iim** [comment]
thanks it works

**Comment by Achmad979** [comment]
I also have problems like this, maybe you can help

[build.zip](https://github.com/apollographql/apollo-android/files/5288308/build.zip)

**Comment by martinbonnin** [comment]
@Achmad979  I'm not seeing any usage of Apollo in the zip file you sent. Is this problem related to Apollo? If yes, can you open a new issue with the full stack trace of the error you are seeing? If not, you can find more help about Gradle in the [community slack](https://gradle.com/slack-invite) or in the [forums](https://discuss.gradle.org/)
