### ISSUE TITLE
Build error with custom Bool type

### ISSUE THREAD

**Issue by AgneseBussone** [apollographql/apollo-android#1719]
Hello,

I'm getting this error when updating to the latest version:
`Variable fetchLocation of type Bool! used in position expecting type Boolean!`
The query looks like this
```
query Bootstrap($fetchLocation: Bool!) {
  estimatedGeolocation @include(if: $fetchLocation) {
    latitude
    longitude
    accuracyRadius
    city
    postalCode
    countryCode
  }
  config {
    supportedCountries {
      code
    }
  }
}
```

In my schema there is a custom `Bool` type that is mapped in the gradle file like this
```
apollo {
    customTypeMapping = [
            "Bool" : "java.lang.Boolean",
            [other custom types]
    ]
    suppressRawTypesWarning = true
}
```
I tried to change it to `Boolean!`, but then it says `Unknown variable type Boolean!`

I didn't have any problem up to version `1.0.2`, it started appearing from version `1.1.0`.

Am I missing out something?
Thank you!

**Comment by sav007** [comment]
Well, this is interesting issue. The issue that `@include(if: $fetchLocation)` expects always to be boolean but with your custom scalar type we can't really figure out during code generation that it will be resolved to Boolean type.

Is there any reason to not make passed variable as `$fetchLocation: Boolean!`?

**Comment by AgneseBussone** [comment]
> Is there any reason to not make passed variable as `$fetchLocation: Boolean!`?

When I try to replace it with `Boolean`, I get different errors depending on the apollo version:
- `1.0.2`: `Validation of GraphQL query document failed`
- `1.2.0`:  `Unknown variable type Boolean!`

**Comment by AgneseBussone** [comment]
I don't have this problem anymore.

Currently, I have 2 apollo clients with different endpoints and schemas, one for our legacy system and one for the new one.
The old schema used a custom `Bool` instead of `Boolean` (I don't know why). I didn't want to migrate the old queries quite yet, but turned out to be the easiest solution for this problem.

Thanks!
