### ISSUE TITLE
Add Default Adapters for custom types

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#172]
Right now, having a `DateTime` custom type fails because the generated classes try to reference `type.DateTime;`. I would like to have a default adapter that I could use to map DateTime or other custom types to a string so that I can do parsing client side.

**Comment by sav007** [comment]
I guess we can downgrade priority of this issue to low, as this is really nice to have

**Comment by sav007** [comment]
We can close this as if mapping for custom type is not specified, field will be generated with type and value will be one of supported JSON types: String, Boolean, Number.
