### ISSUE TITLE
Incubating Plugin: schemaFilePath configuration no longer valid, and error is misleading

### ISSUE THREAD

**Issue by DSteve595** [apollographql/apollo-android#1726]
This no longer works:
```groovy
service('myservice') {
    schemaFilePath = 'path/to/schema.json'
}
```
This error is given:
```
apollo.schemaFilePath is not supported anymore as it doesn't work for multiple services.
Please use a service instead:
apollo {
  service("github") {
    schemaFilePath = "src/main/graphql/com/reddit/schema.json"
    rootPackageName = "null"
  }
}
```
This is because #1715 introduced a breaking change for `service.schemaFilePath`: the property in `Service` is now called `schemaPath`. `schemaFilePath` is still a property in `ApolloExtension`, so setting it inside the service (by following the suggestion in the error) actually sets it for the plugin, which then fails the deprecation check.

This affects 1.2.1 and IMO a 1.2.2 is needed.

**Comment by DSteve595** [comment]
cc @martinbonnin @sav007

**Comment by martinbonnin** [comment]
Yikes, I forgot to update the error message. It should read:

```
apollo.schemaFilePath is not supported anymore as it doesn't work for multiple services.
Please use a service instead:
apollo {
  service("github") {
    schemaPath = "com/reddit/schema.json"
    rootPackageName = ""
  }
}```

I'll fix that. 

Ideally, I'd also like to output an error if users calls `ApolloExtension` methods/property from a `service {}` block as it's most likely not what they had in mind but I'm not sure if this is doable.

Do you really think a 1.2.2 is needed? This should only affect users of the incubating plugin and I guess some level of breaking changes are ok there (until we promote to non-incubating) ?

**Comment by DSteve595** [comment]
>Do you really think a 1.2.2 is needed?

Good point that it only affects the incubating plugin. But I can't imagine this will help adoption/testing of the incubating plugin. Following the clearly-stated example will result in it not working, and the only recourse is to either check the plugin source, or log `service.properties` and figure out what needs to be set.

**Comment by DSteve595** [comment]
>output an error if users calls ApolloExtension methods/property from a service {} block

I feel like I remember seeing a mechanism for exactly this in Kotlin a few years ago; being able to define scopes for lambda member resolution so that things from outer lambdas aren't accidentally accessed. Groovy has resolution strategies, which also seem to be for exactly this.

**Comment by martinbonnin** [comment]
Fix for the error message: https://github.com/apollographql/apollo-android/pull/1728

**Comment by martinbonnin** [comment]
To prevent resolving methods/properties in parent scopes: https://github.com/apollographql/apollo-android/pull/1740
