### ISSUE TITLE
Variable of type Int used in position expecting type Int64Bit

### ISSUE THREAD

**Issue by zulandar** [apollographql/apollo-android#1734]
Currently using apollo 1.2.0 with Kotlin/Android development.

When running the following query;

```
query user($id: Int) {
    users(id: $id) {
        entities {
            name
            enabled
        }
    }
}
```

`Variable "$id" of type "Int" used in position expecting type "Int64Bit".`

I've attempted moving this to Long and recompiling but then received `Can't map GraphQL type: Long to: class java.lang.Object`

**Comment by sav007** [comment]
If I'm not wrong but argument `id` defined in the schema with custom scalar type of `Int64Bit`. What you have to do is to declare `query user($id: Int64Bit)`. Then you should follow instructions on how to setup adapter for  GraphQL custom scalar types.

https://github.com/apollographql/apollo-android#custom-scalar-types

**Comment by zulandar** [comment]
@sav007 that worked. Thank You.
