### ISSUE TITLE
Unknown variable type `Upload!`

### ISSUE THREAD

**Issue by Mangosir** [apollographql/apollo-android#1738]
define this mapping in  my app build.gradle file
```groovy
apollo {
        customTypeMapping = [
                "Upload" : "com.apollographql.apollo.api.FileUpload"
        ]
    }
```
Create graphql mutation

```graphql
mutation SingleUpload($file: Upload!) {
  singleUpload(file: $file) {
    id
    path
    filename
    mimetype
  }
}
```

then, build the project,I thought it would succeed.
well,i get build error

```
Unknown variable type `Upload!`
----------------------------------------------------
[1]:
[2]:mutation SingleUpload($file: Upload!) {
[3]:  singleUpload(file: $file) {
----------------------------------------------------
```
 
so，How to fix it，please

**Comment by sav007** [comment]
Does your GraphQL schema define custom scalar type `Upload `?

**Comment by martinbonnin** [comment]
@Mangosir you'll most likely need to get the scalar type used by your schema. It might be `Upload` but looking at that error, it is most likely something else.

**Comment by sh3lan93** [comment]
I think your schema didn't have the Upload scalar type, try to search for Upload in your schema.json file if you find it so I am wrong.

**Comment by Mangosir** [comment]
> I think your schema didn't have the Upload scalar type, try to search for Upload in your schema.json file if you find it so I am wrong.

you are right! thanks

**Comment by knixer** [comment]
I get the same error when I try to create a mutation with the Upload type in Android. 
I have added this to my app gradle build file:
```
apollo {
    customTypeMapping = [
            "Upload" : "com.apollographql.apollo.api.FileUpload"
    ]
}
```

In my schema.json file that I extracted from the server I found this text related to Upload:
```
{
        "kind": "SCALAR",
        "name": "Upload",
        "description": "The `Upload` scalar type represents a file upload promise that resolves an object containing `stream`, `filename`, `mimetype` and `encoding`.",
        "fields": null,
        "inputFields": null,
        "interfaces": null,
        "enumValues": null,
        "possibleTypes": null
      }
```
In my schema.graphql-file on the server I have added "scalar Upload". And I use the typeDefs option when creating an the Apollo server. 

Still, I get an error when trying to add the type within a mutation.

What am I missing here?
