### ISSUE TITLE
Maven support to generate java classes

### ISSUE THREAD

**Issue by swarnimsuman** [apollographql/apollo-android#1741]
I'm trying to use apollo-android for my java(maven) project, i don't see any plugin for maven to generate java classes using schema.json and query.

**Comment by sav007** [comment]
Maven is not currently supported, only gradle. The only way right now I think of is to run manually compiler via command line.

**Comment by martinbonnin** [comment]
Duplicate with https://github.com/apollographql/apollo-android/issues/1178

**Comment by SundaresanGanapathy** [comment]
can you give me the steps to generate maven artifact from the github fork?
