### ISSUE TITLE
"Can't parse `Array` value, expected array"

### ISSUE THREAD

**Issue by nicusorflorin** [apollographql/apollo-android#1742]
On apollo version 1.2.1 i get the above mentioned error in one of my fragments
specifically this line   ``` outer (filters:{nodeTypes: ChannelFeatureCollection}) { ```

**Comment by martinbonnin** [comment]
Can this be the same issue as https://github.com/apollographql/apollo-android/issues/1731 ?

**Comment by nicusorflorin** [comment]
@martinbonnin i believe so, is there a workaround available? the 1.2.1-SNAPSHOT did not have this problem

**Comment by martinbonnin** [comment]
Looking at that other issue, it looks like `outer (filters:{nodeTypes: [ChannelFeatureCollection]}) {` could work.

**Comment by nicusorflorin** [comment]
that worked, thank you
