### ISSUE TITLE
Method onCompleted does not exist

### ISSUE THREAD

**Issue by awilkin87** [apollographql/apollo-android#1744]
According to `ApolloCall.Callback` documentation for `onResponse`: 
> Depending on the ResponseFetcher used with the call, this may be called multiple times. onCompleted() will be called after the final call to onResponse.

However, there is no method `onCompleted`. I assume this is an error in the documentation (copy/paste from `ApolloSubscriptionCall`). Can I assume `onResponse` is only called once for `ApolloCall`?

I'm using version 1.2.1.

**Comment by sav007** [comment]
Yeah it's outdated docs, what are you looking for is `com.apollographql.apollo.ApolloCall.Callback#onStatusEvent` and particularly  `com.apollographql.apollo.ApolloCall.StatusEvent#COMPLETED`

https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/ApolloCall.java#L92

**Comment by awilkin87** [comment]
Thanks! Am I correct in understanding I only need to worry about multiple calls to `onResponse` if using `CACHE_AND_NETWORK`?

**Comment by sav007** [comment]
Yeah, as far as I remember whenever there is an error or completed we terminate Apollo call. So yes multiple calls to onResponse for `CACHE_AND_NETWORK `.

**Comment by sav007** [comment]
Cleanup, closing.
