### ISSUE TITLE
Failed to resolve: com.apollographql.apollo:apollo-coroutines-support:1.2.1

### ISSUE THREAD

**Issue by huhx0015** [apollographql/apollo-android#1745]
I am unable to bring in the `com.apollographql.apollo:apollo-coroutines-support` dependency in Android Studio, encountering this issue:

`ERROR: Failed to resolve: com.apollographql.apollo:apollo-coroutines-support:1.2.1
Show in Project Structure dialog
Affected Modules: app`

I have added `https://dl.bintray.com/apollographql/android` as a repository source at the project level, as per instructions found here: https://github.com/apollographql/apollo-android/tree/master/apollo-coroutines-support

```groovy
    repositories {
        google()
        jcenter()
        maven { url "https://dl.bintray.com/apollographql/android" }
        maven { url "https://maven.fabric.io/public" }
    }
```
Oddly, `com.apollographql.apollo:apollo-coroutines-support:1.2.1` can be found here, but for some reason, Gradle is unable to resolve this:

https://dl.bintray.com/apollographql/android/com/apollographql/apollo/apollo-coroutines-support/1.2.1/

**Comment by martinbonnin** [comment]
This seems to work now. Are you still having the issue ?

**Comment by lromanob** [comment]
yes still have the issue

**Comment by martinbonnin** [comment]
What is the error exactly ? 

Also, you can try adding the coroutines artifact in case it's not there already:

`implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2"`

**Comment by lromanob** [comment]
`ERROR: Failed to resolve: com.apollographql.apollo:apollo-coroutines-support:1.2.1
Show in Project Structure dialog
Affected Modules: app`

build.gradle

`repositories {
        google()
        jcenter()
        maven { url "https://dl.bintray.com/apollographql/android" }
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin_version"
        classpath "com.apollographql.apollo:apollo-gradle-plugin:$versions.apolloVersion"
    }

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$versions.kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.0.2'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'com.google.android.material:material:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2"


    ////Third part library
    //apollo
    implementation "com.apollographql.apollo:apollo-android-support:$versions.apolloVersion"
    implementation "com.apollographql.apollo:apollo-runtime:$versions.apolloVersion"
    implementation "com.apollographql.apollo:apollo-coroutines-support:$versions.apolloVersion"
}



`

**Comment by martinbonnin** [comment]
You should have 2 `build.gradle`:

rootProject/build.gradle:
```
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin_version"
        classpath "com.apollographql.apollo:apollo-gradle-plugin:$versions.apolloVersion"
    }
```

rootProject/app/build.gradle:
```
    repositories {
        google()
        jcenter()
        maven { url "https://dl.bintray.com/apollographql/android" }
    }
    dependencies {
        implementation "com.apollographql.apollo:apollo-coroutines-support:$versions.apolloVersion"
    }
```

**Comment by lromanob** [comment]
Thanks for the observations @martinbonnin i fixed my gradle files as your said.

but still got the same error:

`ERROR: Failed to resolve: com.apollographql.apollo:apollo-coroutines-support:1.2.1
Show in Project Structure dialog
Affected Modules: app`

**Comment by martinbonnin** [comment]
Interesting. Can you share a sample repository ? I have no problem with this one: https://github.com/martinbonnin/testApolloCoroutines

**Comment by lromanob** [comment]
sure, is a sample for learn about the library https://github.com/lromanob/CountriesApolloCoroutines

**Comment by martinbonnin** [comment]
It works fine once you add `maven { url "https://dl.bintray.com/apollographql/android" }`

https://github.com/lromanob/CountriesApolloCoroutines/commit/f2b03b52c3558fc399462c8492f72bed1f44f842
