### ISSUE TITLE
Option for configuring test source set

### ISSUE THREAD

**Issue by blaugold** [apollographql/apollo-android#1747]
I'm using this plugin for e2e testing of a GraphQL server and would love the have the option to configure the test source set. I want to prevent that the code generated for the tests is included in the final jar and keep test resources separate. At as a workaround I'm putting all the e2e tests their own gradle sub project, which works fine, but it would be nice to not have to setup a multi project. 

In the source of the incubating version of the plugin I have seen some todo comments related to including the test source set. Maybe this use case helps with considering whether or not that would be a useful feature to implement.

**Comment by martinbonnin** [comment]
Definitely. I would suggest the following:

```
// test files should be in:
src/test/graphql/com/example/schema.json
src/test/graphql/com/example/query.graphql
```

And then the generated models should only be in the test classpath. Would that work for you ?

**Comment by blaugold** [comment]
That would be perfect.

**Comment by martinbonnin** [comment]
Initial support is there: https://github.com/martinbonnin/apollo-android/commit/4998fae69e64e01d081c47222d5163682644e10f.

I'm not opening a Pull Request as there are already a couple in flights that this commit will need to depend on.

**Comment by martinbonnin** [comment]
Pull request: https://github.com/apollographql/apollo-android/pull/1764

**Comment by blaugold** [comment]
Thanks for implementing this, looking forward to the next release.
