### ISSUE TITLE
Rebuild the generated classes if build.gradle changes

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#175]
If you change

    customTypeMapping {
        DateTime = "java.util.Date"
    }

to

    customTypeMapping {
        DateTime = "java.util.Date2"
    }

then 'Sync Project'
then 'Build'

then the generated code is still referencing java.util.Date (it should reference java.util.Date2)

**Comment by marwanad** [comment]
More context: Since the build output directory doesn't get modified if you edit `build.gradle`, Gradle still thinks the task is up-to-date because it previous outputs haven't been modified so you need to clean before building in that case.
