### ISSUE TITLE
Unsupported tokens in input

### ISSUE THREAD

**Issue by grazioli** [apollographql/apollo-android#1758]
I am using apollo-android GraphQL (Gradle plug-in version 1.2.1) to post data to a server. I have downloaded the schema.json file from the server and written a .graphql file with a mutation. Since I need to pass objects from the App I defined some inputs as follows.

input Location {
    lat: Float!
    lon: Float!
}

input SensorParams {
    sources: [Int]
    exposition: Float
    location: Location!
}

mutation InsertSessionResults(
    $location: Location!) {
    insertSession(session: {
        name: $name
    }) {
        id
    }
}

However when I build the App I get the following error: Failed to parse GraphQL file. Unsupported token '!'

If I remove the two '!' from Location, the process gives the same error for the '[' char.

Reading the doc I understand that both characters are allowed in input definition to request a non-null value and to set a list type respectively. Any hint on what may cause the error?

**Comment by martinbonnin** [comment]
You don't need to declare the structure of your inputs in your .graphql Files. Apollo-android will generate the model for you. You only need to declare the mutation (see https://graphql.org/learn/queries/#mutations).

**Comment by grazioli** [comment]
I see, thanks for the explanation.

**Comment by grazioli** [comment]
I managed to solve the problem, but now when I build the project one of the generated classes presents an error. Schema.json contains a custom type named date as follows

{
    "name": "bestBefore",
    "description": "",
    "type": {
         "kind": "NON_NULL",
        "name": null,
        "ofType": {
            "kind": "SCALAR",
            "name": "Date",
            "ofType": null
        }
    },
    "defaultValue": null
}

The generated automatically class that uses such a custom type presents the "expected class or package" error for the second parameter of writeCustom method. E.g., writer.writeCustom("bestBefore", type.CustomType.DATE, bestBefore);

Any hint on the reason?

**Comment by martinbonnin** [comment]
You have an exemple for a custom date adapter there: https://github.com/apollographql/apollo-android#custom-scalar-types

**Comment by grazioli** [comment]
Thanks, I followed the guide and added

apollo {
    customTypeMapping = [
        "Date" : "java.util.Date"
    ]
    suppressRawTypesWarning = true
}

to the app level build.gradle file then I have register the custom adapter and added it to the Apollo Client Builder as

DateFormat df = DateFormat.getDateInstance();

CustomTypeAdapter dateCustomTypeAdapter = new CustomTypeAdapter<Date>() {
            @Override public Date decode(CustomTypeValue value) {
                try {
                    return df.parse(value.value.toString());
                } catch (ParseException e) {
                    throw new RuntimeException(e);
                }
            }

            @Override public CustomTypeValue encode(Date value) {
                return new CustomTypeValue.GraphQLString(df.format(value));
            }
        };

apolloClient = ApolloClient.builder()
                .serverUrl("...")
                .okHttpClient(okHttpClient)
                .addCustomTypeAdapter(CustomType.DATE, dateCustomTypeAdapter)
                .build();

but I still have the same error in the generated class. In addition, the build output reports "cannot find symbol variable CustomType", buth the class exists. Am I missing something?

**Comment by martinbonnin** [comment]
Maybe you're missing the `apollo-runtime` in your dependencies ?

**Comment by grazioli** [comment]
I found the problem. Basically the generated classes are placed in a "build" dir subfolder named "type" as displayed by the following image (KitInput is the generated class with the error).

![Schermata 2019-11-12 alle 13 56 49](https://user-images.githubusercontent.com/11957109/68673723-af05b500-0554-11ea-8cd5-d145df98ba01.png)


Unfortunately, the KitInput input object contains a field named "type", so in the generated KitInput class the `type.CustomType.DATE` line is not considered as the path to CustomType class inside "type" folder, but as an attribute of the object representing the field... Is there a way, maybe through Gradle settings, to change the name of the generated files folder?

**Comment by martinbonnin** [comment]
You can change the package name of the generated models by putting your graphql in a subdirectory:

`src/main/graphql/com/example/Queries.graphql`

That should allow you to resolve potential name clashes.

**Comment by grazioli** [comment]
The graphql file is already in a subdirectory which does not include the clashing name. In fact query and mutation classes are generated in a folder having the correct name, but classes representing input types are placed in another folder on the same level named type (the clashing one). The following image displays the tree structure of the project.

![Schermata 2019-11-12 alle 15 54 10](https://user-images.githubusercontent.com/11957109/68681995-b1700b00-0564-11ea-81e9-0b77f9f8ace2.png)

**Comment by martinbonnin** [comment]
Can you try putting schema.json in the same subdirectory ? (`src/main/graphql/com/test_apollo_graphql`)

**Comment by grazioli** [comment]
I tried and the result is that the type folder has been created again, but inside test_apollo_graphql.

![Schermata 2019-11-12 alle 16 08 05](https://user-images.githubusercontent.com/11957109/68683172-a28a5800-0566-11ea-9156-4a759c106c3e.png)
