### ISSUE TITLE
Throwing ApolloNetworkException for cached results on offline

### ISSUE THREAD

**Issue by toboklee** [apollographql/apollo-android#1765]
Not sure if this is a known issue or an intended behaviour.... 

First, I cache the result using `HTTPCachePolicy.NETWORK_FIRST`;  however, the result contains graphql error.
Then, I turn off all network (offline mode), I make the same request. It throws 
```
ApolloNetworkException: Failed to execute http call
```
I am guessing this is due to the retry mechanism...
Is there any way to ignore the error and return the result?

I tried adding cache header to `okHttpClient` but no luck :(

Thanks all in advance!

**Comment by sav007** [comment]
Graphql errors are not cached, so if your query failed cache will be empty.

**Comment by toboklee** [comment]
@sav007 
Thanks for getting back!

However, if im querying for a resource with 2 different ids and only one of them contains the error, shouldn't it be returning at least the one that has no error?

**Comment by sav007** [comment]
Apollo doesn't support partial response (query payload and error in the same response), as in this case we can't guarantee non-nullability for fields.

**Comment by sav007** [comment]
closing out of date.
