### ISSUE TITLE
Support return raw JSON

### ISSUE THREAD

**Issue by minhbnt-1512** [apollographql/apollo-android#1771]
Apollo Android Client returns classes that are auto-generated by apollo. This is weird because after query I have to map the auto-generated classes (Ex: GetUserQuery.Data) to the data model (Ex: UserData). What can I do to the query return raw JSON instead of auto-generated classes? With JSON, I can parse it to the data model easier.

**Comment by martinbonnin** [comment]
@minhbnt-1512 this is actually one of the main advantages of using `apollo-android`. Using the generated models guarantee that they match your graphql schema (nullable/nonnullable types and type safety in general). 

If you don't want that, I guess you could simply use a http client like OkHttp but you lose a lot of benefits of using `apollo-android`

**Comment by wulf0r** [comment]
I agree that using generated classes to have the responses well-typed is exactly what want apollo to do. 

However, I think making the raw response json available is still needed.

My usecase is that Shopify's GraphQL  returns "extension" fields for every request and these fields needed to deal with server-side throtteling. Ex:

```
    "extensions": {
        "cost": {
          "requestedQueryCost": 1,
          "actualQueryCost": 1,
          "throttleStatus": {
             "maximumAvailable": 1000,
             "currentlyAvailable": 999,
             "restoreRate": 50
           }
        }
    }


I can't include this in my queries as it will give an error so I will just have to get via the raw response

**Comment by martinbonnin** [comment]
I see. Could you somehow could use an interceptor (either okhttp or apollo) for this ?

**Comment by wulf0r** [comment]
Yes, that's how I ended up solving it :) Of course this code needs the approtriate data classes to work but this should get anyone started that has the same issue:

     OkHttpClient.Builder().addInterceptor {chain ->
            val original = chain.request()
            val builder = original.newBuilder().method(original.method(), original.body())
            builder.header("X-Shopify-Access-Token", accessToken )
            var response = chain.proceed(builder.build())
            val body = response.body() ?: return@addInterceptor response
            do {
                val bodyText = response.peekBody(Long.MAX_VALUE).charStream().readText()
                val json = Gson().fromJson(bodyText,ResponseJson::class.java)
                if( json.errors?.any { it.isThrottledError() } == true) {
                    with(json.extensions.cost) {
                        val neededAvailable = requestedQueryCost - throttleStatus.currentlyAvailable
                        val timeToWaitInMS = min(floor(neededAvailable / throttleStatus.restoreRate) * 1000, 500.0)
                        sleepAtLeast(timeToWaitInMS.roundToLong())
                        response = chain.proceed(builder.build())
                    }
                } else break
            } while(true)
            response
        }


What would be amazing if I could tell apollo that I expect a certain structure in addition to the query and have apollo return it in resonse.getData()  :)

**Comment by sav007** [comment]
Hm, didn't know that extensions is part of the spec for even response https://github.com/graphql/graphql-spec/blob/master/spec/Section%207%20--%20Response.md

Yeah we can try to  do the same as we did for errors and custom attributes, so we can look for `extensions` field and read them as dictionary.

Could you please provide an example of full response you have with extensions?

**Comment by wulf0r** [comment]
of course :)

Simple product query:
    query {
      products(first:1) {
        edges {
          node {
            title
          }
        }
      }
    }

Gives result:
    {
      "data": {
        "products": {
          "edges": [
            {
              "node": {
                "title": "schniesel.Alhena Mini"
              }
            }
          ]
        }
      },
      "extensions": {
        "cost": {
          "requestedQueryCost": 3,
          "actualQueryCost": 3,
          "throttleStatus": {
            "maximumAvailable": 1000,
            "currentlyAvailable": 997,
            "restoreRate": 50
          }
        }
      }
    }
