### ISSUE TITLE
[Documention] add documentation and sample code for Subscriptions 

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#1772]
See https://github.com/apollographql/apollo-android/pull/1768

We are missing documentation and/or sample code for subscriptions. It would be nice to add that.

**Comment by kisidav** [comment]
It would be necessary not just nice! Could you guys fill this page?
https://www.apollographql.com/docs/android/advanced/subscriptions/

**Comment by martinbonnin** [comment]
Documentation is now available at https://www.apollographql.com/docs/android/v3/essentials/subscriptions/
