### ISSUE TITLE
[Apollo-Android] How to get error data when fromCache = true

### ISSUE THREAD

**Issue by fairlyNguyen** [apollographql/apollo-android#1774]
I need to handle some error cases, but I don't know how to get error data when the response from cache file.

**Comment by fairlyNguyen** [comment]
No need

**Comment by sav007** [comment]
> he response from cache file.

Not sure if I got this, do you mean HTTP cache or normalized cache?

Apollo doesn't cache GraphQL error responses.

**Comment by fairlyNguyen** [comment]
@sav007 Sorry, please ignore my question. I'm thinking wrong way to controlling my logic.
Anyway thanks for the reply.
