### ISSUE TITLE
I got ["defined": true] on sending parameters for each fields for some users 🤷🏽‍♂️

### ISSUE THREAD

**Issue by bellierjonathan** [apollographql/apollo-android#1776]
Hello

**Summary**
On sending parameters to the backend side some android users in production are sending `"defined": true` for each fields. 🤨

**Parameters sent :** 

![Capture d’écran 2019-11-15 à 17 14 10](https://user-images.githubusercontent.com/5746542/68958837-2d6c8c00-07cd-11ea-8d34-c36b079322c6.png)

I saw there is a class called Input.java in Apollo Android library with `defined` field. I think it's related to this ?

![Capture d’écran 2019-11-15 à 17 22 20](https://user-images.githubusercontent.com/5746542/68958697-eb434a80-07cc-11ea-96e3-4675c907383a.png)

I don't understand why it's not all users and why we cannot reproduce this.

**mutation**
![Capture d’écran 2019-11-15 à 17 29 47](https://user-images.githubusercontent.com/5746542/68959585-99032900-07ce-11ea-9350-7d52494c4ff6.png)

Another example we use `JodaTime` object for dates. When `startDate` is sent it's serializing all the object like this : 

![Capture d’écran 2019-11-15 à 17 38 42](https://user-images.githubusercontent.com/5746542/68959786-12028080-07cf-11ea-8686-8df7de0c29e2.png)

We use this mapping types : 
```
apollo {
    useJavaBeansSemanticNaming = true
    customTypeMapping = ['DateTime': "org.joda.time.DateTime", 'Time': "org.joda.time.DateTime", 'Date': "org.joda.time.DateTime"]
}
```
**Version**
`1.0.1`

**Comment by sav007** [comment]
It's pretty old version, could you please try the latest one 1.2.1?

**Comment by bellierjonathan** [comment]
We will try to update soon but we cannot reproduce this bug we will wait after this in production if its coming back with the last release of android apollo.

**Comment by sav007** [comment]
Closing for now.

**Comment by bellierjonathan** [comment]
We update apollo android client to `1.2.1` and several users still getting this bug. It's really difficult to debug and understand why we get `defined`.
