### ISSUE TITLE
Generate build warning for deprecated field usage

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#1778]
**Is your feature request related to a problem? Please describe.**
It will be nice to give users a way to detect any usage of deprecated fields during build time.

Some users would probably create a lint check to fail if deprecated fields are found.

**Describe the solution you'd like**
During build generate Gradle warning with location of deprecated field and description of reason taken from schema.

**Comment by martinbonnin** [comment]
Don't we have deprecation on fields already ? (https://github.com/apollographql/apollo-android/blob/4e0f70adc3de7fa26b937aa332c78266ea8a8b78/apollo-compiler/src/test/graphql/com/example/deprecation/TestQuery.kt#L69).

That should generate a warning during `compileKotlin/compileJava` that users can use to fail if they want to ?

**Comment by sav007** [comment]
That's true, I was thinking about maybe write kind of generate one full report as a warning in the build logs. But yeah maybe you are right, it doesn't make sense.

**Comment by sav007** [comment]
Closing for now.
