### ISSUE TITLE
com.apollographql.apollo.exception.ApolloHttpException: HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by mukulkumar1703** [apollographql/apollo-android#1785]
**Summary**
Hello, I am getting below exception after running the application.
com.apollographql.apollo.exception.ApolloHttpException: HTTP 500 Internal Server Error

**Description**
Query : query getMyuser ($Id: Int!) {
    user(id: $Id) {
        name
        email
    }
}

Code : 

        GetMyuserQuery  getMyuserQuery = GetMyuserQuery.builder().id(1).build();
        apolloClient.query(getMyuserQuery).enqueue(new 
        ApolloCall.Callback<GetMyuserQuery.Data>() {
            @Override
            public void onResponse(@NotNull Response<GetMyuserQuery.Data> response) {
                Log.d("onResponse Response", response.toString());
            }
            @Override
            public void onFailure(@NotNull ApolloException e) {
                Log.d("onFailure Response", e.toString());

            }
        });

Response: 

com.apollographql.apollo.exception.ApolloHttpException: HTTP 500 Internal Server Error

Although the query is working fine if I run it on the browser but when I run the application it's giving me the above error. Please let me know what I am doing wrong here. Any help would be appreciated.

**Version**
implementation 'com.apollographql.apollo:apollo-runtime:1.2.1'
classpath 'com.apollographql.apollo:apollo-gradle-plugin:1.2.1'

**Comment by sav007** [comment]
Not sure that this issue related to Apollo, seems like it's entirely on your server side implementation.

**Comment by sav007** [comment]
closing out of date.
