### ISSUE TITLE
Getting HttpParseException when using ApolloClient with HttpCache configuration

### ISSUE THREAD

**Issue by ridhi129** [apollographql/apollo-android#1786]
**Summary**
I am getting HttpParse Exception when I configure HttpCache in the apolloclient. Without the HttpCache setup I am able to successfully see the response.

**Description**
**Apollo Client setup** 

```
private val apolloClient: ApolloClient by lazy {
        ApolloClient.builder()
            .serverUrl(endpoint)
            .okHttpClient(client.newBuilder().addInterceptor(interceptor).build())
            .httpCache(ApolloHttpCache(diskLruHttpCacheStore))
            .build()
    }
```

**Request -**

```
override fun getData(params: T, observer: Observer<Response<T.Data>>): Disposable {
    val request: ApolloCall<T.data> = apolloClient
        .query(params(some context))
        .httpCachePolicy(HttpCachePolicy.CACHE_FIRST)
    return Rx2Apollo.from(request)
        .observeOn(observeOn)
        .subscribeOn(subscribeOn)
        .subscribeObserver(observer)
}
```

**Exception stack trace**

```
com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse(ApolloServerInterceptor.java:125)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.EOFException: End of input
        at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.nextNonWhitespace(BufferedSourceJsonReader.java:946)
        at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.doPeek(BufferedSourceJsonReader.java:332)
        at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.beginObject(BufferedSourceJsonReader.java:169)
        at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:82)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53) 
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse(ApolloServerInterceptor.java:125) 
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Version**
Apollo version - 1.1.1

**Comment by edenman** [comment]
I also ran into this when trying to add the Instabug http interceptor to my OkHttp instance.  Can't tell if the bug is in the Instabug interceptor or the `DiskLruHttpCacheStore` class https://github.com/Instabug/Instabug-Android/issues/259

**Comment by mrctrifork** [comment]
Reproduced today with version 1.2.3

**Comment by sav007** [comment]
hey folks, to clarify is this issue happens when you provide custom okHttp with custom interceptor to Apollo client?

**Comment by edenman** [comment]
@sav007 exactly

**Comment by mrctrifork** [comment]
This is the initialization code for apollo client

<img width="648" alt="imagen" src="https://user-images.githubusercontent.com/45353144/72724072-a1872f80-3b82-11ea-95d2-2ea0007e98f3.png">


And this is the OkHttpClient initialization
<img width="501" alt="imagen" src="https://user-images.githubusercontent.com/45353144/72724122-bebbfe00-3b82-11ea-8fbc-b39ff62e4c32.png">

**Comment by sav007** [comment]
@mrctrifork is it possible to take a look at your `UserAgentInterceptor`, `AppAuthInterceptor` interceptor implementations? And another question how do you add those interceptor via `addInterceptor` or `addNetworkInterceptor`?

**Comment by mrctrifork** [comment]
Sure. I add these interceptors with `addInterceptor` as you can see in the lazy initializer in the last screenshot.

<img width="766" alt="imagen" src="https://user-images.githubusercontent.com/45353144/73430488-82389100-433e-11ea-8f2f-6a5d59b8cac9.png">

<img width="547" alt="imagen" src="https://user-images.githubusercontent.com/45353144/73430594-ba3fd400-433e-11ea-9ebb-3155e4e3d4b5.png">

**Comment by sav007** [comment]
Hey folks, sorry I couldn't reproduce this issue on any of our sample app. I tried several different combinations of OkHttp interceptors (network and application) but couldn't catch the culprit.

It could be that one of the custom interceptors  closes request prematurely. 

Could someone please provide a sample app (or modify existing  apollo sample) where this issue is reproduced, other than that I can't really help you.

**Comment by rudas23** [comment]
Just add this to the sample app and it will show the parse error. It's using the OkHttp standard logging interceptor. Note that .BODY is needed as level.
(Could a problem with the OkHttpLogging library)

```
val logInterceptor = HttpLoggingInterceptor { message ->
      Log.d("OkHttp", message)
    }.apply {
      level = HttpLoggingInterceptor.Level.BODY
    }

...
val okHttpClient = OkHttpClient.Builder()
        .addNetworkInterceptor { chain ->
          val request = chain.request().newBuilder()
              .addHeader("Authorization", "bearer ${BuildConfig.GITHUB_OAUTH_TOKEN}")
              .build()

          chain.proceed(request)
        }
        .addInterceptor(logInterceptor)
        .build()
...

// Directory where cached responses will be stored
    val file = File(applicationContext.filesDir, "apolloCache")
    // Size in bytes of the cache
    val size = 1024 * 1024.toLong()
    // Create the http response cache store
    val cacheStore = DiskLruHttpCacheStore(file, size)

    ApolloClient.builder()
        .serverUrl(baseUrl)
        .normalizedCache(sqlNormalizedCacheFactory, cacheKeyResolver)
        .okHttpClient(okHttpClient)
        .httpCache(ApolloHttpCache(cacheStore))
        .build()


```

**Comment by mrctrifork** [comment]
That's a really nice catch… I absolutely forgot about the logging interceptor which I have from the OkHttp dependency.

```groovy
implementation "com.squareup.okhttp3:logging-interceptor:4.2.1"
```

Here's the instantiation:

<img width="550" alt="imagen" src="https://user-images.githubusercontent.com/45353144/75666630-6e9e8400-5c76-11ea-83e4-72a63d33dd9d.png">

**Comment by sav007** [comment]
Ok, here is an update on this issue. 

I finally found where is the issue, this issue happens when:
1. When app is freshly installed (or when there is no cached response)
2. When `HttpLoggingInterceptor` is added to OkHttp
3. Log level is set to BODY

The issues is that `HttpLoggingInterceptor ` when logging response body requests whole response https://github.com/square/okhttp/blob/master/okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.kt#L244-L246
that causes `ApolloParseInterceptor` to fail as there was a bug in our http cache: we didn't properly buffer original response, so instead of giving buffered response to `ApolloParseInterceptor` we give it non-buffered, that obviously will fail as response already was read from the source.

Fix is comming.

**Comment by mcossenas** [comment]
It is possible to have the latest version of the Android Apollo Client  available via JCenter. Currently 1.4.1 is the only version I can see and would like at least 1.4.3 if not 1.4.4 so that I can have a fix for this issue.
