### ISSUE TITLE
Execute raw graphQL query

### ISSUE THREAD

**Issue by sh3lan93** [apollographql/apollo-android#1787]
I have a case in which I want to create a raw graphQL query because there are some dynamic inputs I will submit to query so I want to create the string representation for this query. 

**Example:**
```
query{
  products(sort: {price: DESC}){
    
  }
}
```

This query will be changed upon the user selection for sort options this maybe looks like: 

```
query{
  products(sort: {rating: DESC}){
    
  }
}
```

So when using apollo run time I can't achieve a behaviour like this, so I came again across README files and get the apollo-api for make such behaviour but the README no sufficient for understanding how to implement such behaviour.

I will appreciate your help for this issue, I had asked this question on StackOverflow but no one gets the answer to my question.

Thanks in advance.

**Comment by martinbonnin** [comment]
Can you copy/paste your generated model ? (Query.java or Query.kt) ? You should have some options to pass the parameters to the query as needed.

**Comment by sh3lan93** [comment]
did you mean the generated class from apollo code generation?

**Comment by martinbonnin** [comment]
> did you mean the generated class from apollo code generation?

Yes, it should contain everything needed to do your query

**Comment by sh3lan93** [comment]
Here are the two generated classes for same query but different inputs 
[Archive.zip](https://github.com/apollographql/apollo-android/files/3863861/Archive.zip)

**Comment by martinbonnin** [comment]
Thanks ! Could you use parameters ? 

```
query GetProducts($sort: Sort) {
   products(sort: $sort) {
      [...]
   }
}
```

Then you can decide to sort by price/rating by passing a different parameter.

**Comment by sh3lan93** [comment]
** Sort ** isn't a scalar type in the schema

**Comment by martinbonnin** [comment]
I assumed that non-scalar parameters were supported but I never actually tried. I'll try to make a small snippet to see if it works.

**Comment by sh3lan93** [comment]
the query has dynamic input fields for sort: 
```
query{
	product(sort: {price: DES}){
	}
}
```
and this can be changed during runtime to
```
query{
	product(sort: {brand_name: DES}){
	}
}
```
the brand_name and price are defined in the schema itself so I have to select one of them depending on user selection.
So when user select price I should execute the query with price option and when user selects the brand_name I should execute the query with brand_name option and so on.

**Comment by martinbonnin** [comment]
Non-scalar parameters are supported:

```graphql
query GetAdvisories($identifier: SecurityAdvisoryIdentifierFilter) {
  securityAdvisories(identifier: $identifier) {
    totalCount
  }
}

{
  "identifier": {"type": "CVE", "value": ""}
}
```
translates to:

```kotlin
        val query = GetAdvisories(identifier = Input.optional(SecurityAdvisoryIdentifierFilter(type = SecurityAdvisoryIdentifierType.CVE, value = "")))
```

**Comment by tasomaniac** [comment]
I would expect this to be supported as well. In your schema, are these 2 type share a common parent type?

**Comment by sh3lan93** [comment]
> I would expect this to be supported as well. In your schema, are these 2 type share a common parent type?

In my query, I should submit an argument of type **ProductSortInput** which includes different fields to be submitted like rating, price and then decides to make sorting by descending or ascending. did you get the idea?

**Comment by martinbonnin** [comment]
Apollo should generate a `ProductSortInput` model that you can configure and then pass to your query.

**Comment by sh3lan93** [comment]
Yes, I have figured out that after a lot of tries. I was assuming ProductSortInput not generated by Apollo. Thanks for your help 👌
