### ISSUE TITLE
Creating custom type adapter  [question]

### ISSUE THREAD

**Issue by dualcnhq** [apollographql/apollo-android#1792]
I have this response:

```
{
      "price": 10,
      "customer_details": {
        "last_name": "Doe",
        "first_name": "John"
      }
}
```

I want to parse a `jsonb` object which is in this case is `customer_details` from the GraphQL response, so I tried to use/create a custom type adapter.

```
val jsonbCustomTypeAdapter = object : CustomTypeAdapter<String> {
      override fun decode(@NotNull value: CustomTypeValue<*>): String {
        return value.toString()
      }

      override fun encode(value: String): CustomTypeValue<*> {
        return CustomTypeValue.GraphQLJsonString(value)
      }
}
```

but i'm getting: `Can't map GraphQL type: jsonb to: class java.lang.Object. Did you forget to add custom type adapter?` 

here's  the `schema.json`

```
{
    "name": "customer_details",
    "description": null,
    "args": [
         {
             "name": "path",
             "description": "JSON select path",
             "type": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
              },
              "defaultValue": null
         }
    ],
   "type": {
       "kind": "SCALAR",
       "name": "jsonb",
       "ofType": null
    },
    "isDeprecated": false,
    "deprecationReason": null
}
```

I'm also having troubles parsing the `numeric` value of the response: `price`; i'm tried this one:

```
val numCustomTypeAdapter = object : CustomTypeAdapter<String> {
      override fun decode(@NotNull value: CustomTypeValue<*>): String {
        return value.value.toString()
      }

      override fun encode(value: String): CustomTypeValue<*> {
        return CustomTypeValue.GraphQLString(value)
      }
}
```

**Comment by martinbonnin** [comment]
Did you configure the `apollo {}` block with `customTypeMapping` in your `build.gradle` ?

**Comment by dualcnhq** [comment]
yes i did, not sure though if this is correct:

```
apollo {
    useSemanticNaming = true
    customTypeMapping = [
            "uuid" : "java.lang.String",
            "id": "java.lang.String",
            "price": "java.lang.Integer",
            "jsonb": "java.lang.String"
    ]
}
```

also it seems that now i also need to parse `float8` which i have no idea how to do that
`Can't map GraphQL type: float8 to: class java.lang.Object. Did you forget to add custom type adapter?`

**Comment by dualcnhq** [comment]
it's kinda weird that it shows like this in the logs which is not ideal: `price=com.apollographql.apollo.response.CustomTypeValue$GraphQLNumber@aa4ca78`

**Comment by sav007** [comment]
from logs you probably missing mapping for custom scalar type `float8 ` in apollo config

**Comment by dualcnhq** [comment]
is there an example to follow on how to create custom type adapters for different scalar types? 
the current documentation only have a sample for a date type

**Comment by dualcnhq** [comment]
this was solved when i updated to version `1.2.2` 

however, i have this `Object`:
```
address={zip=WC2H 0EW, city=London, line_1=London, line_2=  Soho Greater London England, country=GB, contact_num=+447123456789, location_type=residential}
```

and when i converted it using Gson, here's a snippet to my code:

```
val gson = Gson()
val addressDetails = data.address().toString()
Log.d(TAG, "strAddressDetails: $addressDetails")
val reader = JsonReader(StringReader(addressDetails))
reader.isLenient = true
val addressDetails: Address =
  gson.fromJson(addressDetails, Address::class.java)
```

i encountered this error:

```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 134 path $.address.zip
        at com.google.gson.Gson.fromJson(Gson.java:947)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at com.google.gson.Gson.fromJson(Gson.java:817)
```

it seems that once the `space` in `zip` key was read, it caused the error.
any inputs about this?

**Comment by sav007** [comment]
Hey sorry for the delay but what is the type of `data.address()`?
If custom scalar type is missing and if the server returns JSON object than by default it's mapped to `Map<String, Object>`. Obviously `Map<String, Object>.toString()` won't return JSON string.

**Comment by sav007** [comment]
To proper support GraphQL JSON custom scalar types, you need to setup custom type adapter.
In your case of `address` the value passed in `com.apollographql.apollo.response.CustomTypeAdapter#decode` will be `com.apollographql.apollo.response.CustomTypeValue.GraphQLJsonObject` where you can take `Map<String, Object> value` and deserialize it to `Address` by `Gson` from raw `Map`

**Comment by sav007** [comment]
Closing, out of date.
