### ISSUE TITLE
How to get access to raw JSON of response? [question]

### ISSUE THREAD

**Issue by NatElkins** [apollographql/apollo-android#1800]
Currently I'm using generated Kotlin classes to access a GraphQL API.  At one point, I need to get access to the response type in JSON form.  If I used Jackson to serialize it to JSON, it usually works just fine, unless I'm using fragments.  If I'm using fragments, I get something similar to the following:

```json
{
        "__typename": "Channel",
        "fragments": {
            "commonChannelInfo": {
                "__typename": "Channel",
                "id": "96895296-a3ec-45c3-bc85-2ff229cb5fde",
                "name": "#lips",
                "description": "Crowd favorites sealed with a kiss 💋",
                "facets": [
                    "Makeup"
                ],
                "subscription_status": false,
                "answered_users": [
                    {
                        "__typename": "User",
                        "avatar": "329b29b8-cae9-4c0d-9f01-3c36ad3b4fe2"
                    },
                    {
                        "__typename": "User",
                        "avatar": "329b29b8-cae9-4c0d-9f01-3c36ad3b4fe2"
                    },
                    {
                        "__typename": "User",
                        "avatar": "329b29b8-cae9-4c0d-9f01-3c36ad3b4fe2"
                    },
                    {
                        "__typename": "User",
                        "avatar": "329b29b8-cae9-4c0d-9f01-3c36ad3b4fe2"
                    }
                ],
                "stats": {
                    "__typename": "ChannelStats",
                    "question": 647,
                    "answer": 1525,
                    "subscription": 610
                }
            }
        }
    }
```

If I were using "normal" GraphQL, the fragments property wouldn't be there.  Is there a way to get access to what the GraphQL is responding with directly?  Or alternatively, is there a known workaround?

Thanks!

**Comment by martinbonnin** [comment]
If you really need, you can access the raw json from an okhttp interceptor. But apollo-android should give you access to all the data from your queries using a typesafe API, which is usually better than using Jackson or something else to parse json. Is there a specific use case where you need access to the json from some data that is not in your query ? 

See also https://github.com/apollographql/apollo-android/issues/1771

**Comment by NatElkins** [comment]
@martinbonnin Thanks for the tip, I'll give that a try.  It's not about the data per se, it's about the shape of the data, I have a need to have it represented as JSON (in the same way that it gets returned by GraphQL if you were to access it directly).  Other times it's useful to have it in the type safe API, because I need to apply some kind of transofm

So it looks like I can access the raw response via the interceptor...do you know if I can pass it along to the final result somehow?  Or do I only have access to it within the context of the interceptor?

**Comment by martinbonnin** [comment]
> do you know if I can pass it along to the final result somehow? Or do I only have access to it within the context of the interceptor?

It's mostly available from the context of the interceptor. If you need it somewhere else, you'll have to add support for that manually.
