### ISSUE TITLE
ApolloIdlingResource is never idle when used with query watchers

### ISSUE THREAD

**Issue by lwasyl** [apollographql/apollo-android#1805]
We're using `ApolloIdlingResource` in Espresso tests. It worked well with `ApolloQueryCall`s, but when we transitioned to `ApolloQueryWatcher` for the queries, Espresso tests always hang on the `ApolloIdlingResource` since it's never idle.

I understand it's a tricky situation, because technically a `watcher` is not _idle_ until it's cancelled. However that makes `ApolloIdlingResource` completely useless in Espresso tests, since we'd also like to test specifically the watcher integration (elements getting updated etc.) and besides it just doesn't make sense to cancel it early.

So my question is, is `ApolloIdlingResource` inherently incompatible with query watchers, or it can be made to e.g. idle after first response arrives? It does make some sense in my mind, but I haven't throught it through very much. Pinging @VisheshVadhera since I see you in other idling resource discussions here :)

**Comment by tasomaniac** [comment]
This definitely looks like a bug. I never used `ApolloQueryWatcher` myself. If you could provide some code or even help us reproduce it on our sample project, that would be awesome. Thanks.

**Comment by odlund** [comment]
This added test should show the issue: 
https://github.com/apollographql/apollo-android/commit/1913146c323b548506cbebbaf91ae55d95150b41
