### ISSUE TITLE
Apollo and coroutines

### ISSUE THREAD

**Issue by 7Fab** [apollographql/apollo-android#1808]
**Summary**
I am trying to use Apollo with coroutines. Although it works perfectly with toDeferred, sometimes it throws fatal errors that crash my app even if surrounded by try and catches.
In some other parts of the app I use enqueue and overwrite the onFailure to properly manage the issue, but with the coroutines seems impossible with the current implementation. 

This is causing several problems for my users. Am I missing something from the usage of the coroutine support?

**Comment by martinbonnin** [comment]
Can you share a stacktrace of such a crash ?

**Comment by 7Fab** [comment]
Sure, this is one instance from the play dashboard
```
com.apollographql.apollo.exception.ApolloHttpException: 
  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse (ApolloParseInterceptor.java:105)
  at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse (ApolloParseInterceptor.java:53)
  at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse (ApolloServerInterceptor.java:125)
  at okhttp3.RealCall$AsyncCall.run (RealCall.kt:138)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
```
And this from bugsnag
```com.apollographql.apollo.exception.ApolloHttpException · HTTP 500
ApolloParseInterceptor.java:105com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse	
ApolloParseInterceptor.java:53com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse	
ApolloServerInterceptor.java:125com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse	
RealCall.kt:138okhttp3.RealCall$AsyncCall.run	
ThreadPoolExecutor.java:1167java.util.concurrent.ThreadPoolExecutor.runWorker	
ThreadPoolExecutor.java:641java.util.concurrent.ThreadPoolExecutor$Worker.run	
Thread.java:764java.lang.Thread.run```

If you know bugsnag, it separates exception by handled and unhandled. I have some legacy code that uses .enqueue with the callback and overrides onFailure, same 500 server error happens but it's categorised ad "handled", so the app won't crash. While in my new repositories using coroutines, these errors manage to crash it

**Comment by martinbonnin** [comment]
Thanks. There are a few other issues about exception handling and coroutines so we might be into something. It does work ok in unit tests (https://github.com/apollographql/apollo-android/blob/1dab62c25b271846117c439aebb4afa266be17cd/apollo-integration/src/test/java/com/apollographql/apollo/CoroutinesApolloTest.kt#L78) so the setup has to be more complex than that. 
Not sure it's related but still worth a shot, are you on latest versions of coroutines and kotlin  ? (1.3.2 + 1.3.61)

**Comment by martinbonnin** [comment]
Also: are you able to reproduce this locally or is this only something you see in BugSnag/GooglePlay ?

**Comment by 7Fab** [comment]
That is the main issue, I can't reproduce it locally. So I have been chasing ghosts for the past couple of weeks as for some reason (probably related to our backend) these types of issues increased.

I am for kotlin, just saw that for coroutines we are on 1.3.1. I'll see if that helps too!

**Comment by gunjitdhawan** [comment]
Any update on this?

**Comment by sav007** [comment]
From the stack trace is super unclear where is the issue, but I assume it's related how the coroutines is used on client side not in Apollo. If you take a look at the definition of Apollo  `toDeferred` it super trivial:
```
 val deferred = CompletableDeferred<Response<T>>()

  deferred.invokeOnCompletion {
    if (deferred.isCancelled) {
      cancel()
    }
  }
  enqueue(object : ApolloCall.Callback<T>() {
    override fun onResponse(response: Response<T>) {
      deferred.complete(response)
    }

    override fun onFailure(e: ApolloException) {
      deferred.completeExceptionally(e)
    }
  })

  return deferred
```

**Comment by gunjitdhawan** [comment]
Change extension function "toDeferred" as below:

`fun <T> ApolloCall<T>.toDeferred(): Deferred<Response<T>> {
    val deferred = CompletableDeferred<Response<T>>()

    deferred.invokeOnCompletion {
        if (deferred.isCancelled) {
            cancel()
        }
    }
    enqueue(object : ApolloCall.Callback<T>() {
        override fun onResponse(response: Response<T>) {
            deferred.complete(response)
        }

        override fun onFailure(e: ApolloException) {
            var builder = Response.builder<T>(operation())
                    .errors(arrayListOf(Error(e.localizedMessage, null, null)))
                    .build()

            deferred.complete(builder)
        }

        override fun onCanceledError(e: ApolloCanceledException) {
            var builder = Response.builder<T>(operation())
                    .errors(arrayListOf(Error(e.localizedMessage, null, null)))
                    .build()

            deferred.complete(builder)
        }

        override fun onNetworkError(e: ApolloNetworkException) {
            var builder = Response.builder<T>(operation())
                    .errors(arrayListOf(Error(e.localizedMessage, null, null)))
                    .build()

            deferred.complete(builder)
        }

        override fun onParseError(e: ApolloParseException) {
            var builder = Response.builder<T>(operation())
                    .errors(arrayListOf(Error(e.localizedMessage, null, null)))
                    .build()

            deferred.complete(builder)
        }

        override fun onHttpError(e: ApolloHttpException) {
            var builder = Response.builder<T>(operation())
                    .errors(arrayListOf(Error(e.localizedMessage, null, null)))
                    .build()

            deferred.complete(builder)
        }

        override fun onStatusEvent(event: ApolloCall.StatusEvent) {
            super.onStatusEvent(event)
        }
    })

    return deferred
}`

**Comment by koyinusa** [comment]
I have an extension function that uses coroutine. 
Maybe someone else can find this usable.
`suspend fun <T> ApolloCall<T>.execute() = suspendCoroutine<Response<T>> { continuation ->

    enqueue(object : ApolloCall.Callback<T>() {
        override fun onResponse(response: Response<T>) {
            continuation.resume(response)
        }
        override fun onFailure(error: ApolloException) {
            continuation.resumeWithException(error)
        }

        override fun onNetworkError(e: ApolloNetworkException) {
            //This should not be calling super because super calls failure
            //super.onNetworkError(e)
            val response = Response.builder<T>(operation())
                .errors(arrayListOf(com.apollographql.apollo.api.Error(e.localizedMessage, null, null)))
                .build()
            continuation.resume(response)
        }
    })
}
`
