### ISSUE TITLE
Custom Persisted Query ID

### ISSUE THREAD

**Issue by boopathi** [apollographql/apollo-android#1834]
**Is your feature request related to a problem? Please describe.**

We are unable to use the apollo android client for persisted-queries because we use a different way to apollo's automated persisted queries. The main problem is that we generate different IDs for our queries.

**Describe the solution you'd like**

A way to customize the ID generation logic for persisted-queries - possibly as a parameter to `generateApolloClasses` task.

Right now the ID generation logic is doing the following steps (as of this writing) as I observed. 

1. Select the Query with operation name and corresponding fragments
1. Add `__typename` to all selection sets. 
1. Minify the GraphQL code
1. Generate Sha256 of this minified code.

https://github.com/apollographql/apollo-android/blob/19fdfdab6c3a5f1b53b338c8828570d1d245f744/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/ast/builder/OperationTypeBuilder.kt#L32 

Here, in this line of code, it would benefit us if there is a way to override this behavior by providing a custom ID generator (which we can use to get the ID from a service or from some other CLI).

**Comment by martinbonnin** [comment]
I'm closing this one as it seems very similar to https://github.com/apollographql/apollo-android/issues/1794. Please reopen if I'm missing something.
