### ISSUE TITLE
Wrongfully generated Kotlin objects

### ISSUE THREAD

**Issue by Pantkowsky** [apollographql/apollo-android#1838]
**Summary**
Apollo generates a lowercase `data class` model. 

**Description**
Schema specifies a uppercase type, however the generated model is a lowercase `data class`. This is experienced in a `GraphqlFragment`.

**Version**
`1.2.2`

We have a type `Child` in our GraphQL `schema.json`. It is defined as:

`
type Child {
  id: UUID!
  (...)
}
`

The code generation however creates the model as:

`
data class child(
    val __typename: String,
    val id: Any
  ) {
    ...
}
` 

Because of that, there is an import in the `GraphqlFragment` that looks like `import Child` which is incorrect. In addition, inside the `operator fun invoke(...)` there is a compilation error since the reader expects object of type `Child` instead of `child`:

```
val children = reader.readList<child>(RESPONSE_FIELDS[2]) {
        it.readObject<Child> { reader ->
          Child(reader)
        }

      }
```

**Comment by martinbonnin** [comment]
Maybe same bug as https://github.com/apollographql/apollo-android/issues/1560 ?

**Comment by Pantkowsky** [comment]
Can't tell. I'm reporting types, not field names. 

Interesting thing is, from all of the types that we have in our schema, only this particular one experiences this problem. Furthermore, this issue is non-existent when generating `Java` models instead of `Kotlin` ones. 

We have a similar type `Spouse`, which is generated correctly:
```
type Spouse {
  id: UUID!
  (...)
}
```

```
val spouse = reader.readObject<Spouse>(RESPONSE_FIELDS[1]) { reader ->
        Spouse(reader)
      }
```

**Comment by EricKuck** [comment]
I've had the same issue, specifically with `child`. As a temporary workaround I used an alias to rename it to something else, which worked great.

**Comment by tasomaniac** [comment]
There is this list of irregular words to turn words into singular form. Can you check if these words are the reason by trying something else than `child / children`?

```
private fun irregular(): List<Pair<String, String>> {
  return listOf(
      "person" to "people",
      "man" to "men",
      "goose" to "geese",
      "child" to "children",
      "sex" to "sexes",
      "move" to "moves")
}
```
