### ISSUE TITLE
Generated Java code using internal classes 

### ISSUE THREAD

**Issue by robcolburn** [apollographql/apollo-android#1842]
**Summary**
Hi there, I'm using a collection of scripts from a former author that manually invoke the compiler in a similar fashion to ApolloCodegenTask.groovy, however from Java code. Then generated code seems to attempt to use internal API. Formerly this collection of scripts used apollo-android 1.0.0, and I'm attempting to update that code to 1.2.1 or 1.2.2.

**Description**
The new generated code seems to want to make use of internal classes. Should I be trying to get compiler to not do this with arguments? Or, should I try to vend these internal classes publicly to the app.

```
import com.apollographql.apollo.api.internal.Mutator;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;
```

Here are some examples I'm seeing

```java
      public Builder userLists(@NotNull Mutator<List<UserList.Builder>> mutator) {
        Utils.checkNotNull(mutator, "mutator == null");
        List<UserList.Builder> builders = new ArrayList<>();
        if (this.userLists != null) {
          for (UserList item : this.userLists) {
            builders.add(item != null ? item.toBuilder() : null);
          }
        }
        mutator.accept(builders);
        List<UserList> userLists = new ArrayList<>();
        for (UserList.Builder item : builders) {
          userLists.add(item != null ? item.build() : null);
        }
        this.userLists = userLists;
        return this;
      }
```

```java
  @Override
  @NotNull
  public Response<FollowCount.Data> parse(@NotNull final BufferedSource source,
      @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
    return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
  }
```

```java
  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forList("userLists", "userLists", new UnmodifiableMapBuilder<String, Object>(2)
      .put("id", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "userId")
        .build())
      .build(), true, Collections.<ResponseField.Condition>emptyList())
    };
```

**Version**
1.2.x - though there is more internal use in 1.2.2 than 1.2.1

**Comment by martinbonnin** [comment]
Are you using the same version for `apollo-runtime` and `apollo-gradle-plugin` ?

**Comment by robcolburn** [comment]
I’m building the operations from `apollo-compiler`, and the client is probably `apollo-runtime`, and is in my case.

This collection of scripts is in a shared company repo, so I’m not certain if other consumers are using it differently. That said, I don’t mind saying, “if you want to use the new version, you have to use it with Apollo runtime”

**Comment by martinbonnin** [comment]
The version of `apollo-compiler` used to generate the models has to match with the version of `apollo-runtime` (or `apollo-api`) used to consume them. We could enforce this in the gradle plugin but I'm not sure we can display an error message if calling the compiler manually without the gradle plugin.

**Comment by lehoanglu0ng** [comment]
I face the same issue today and yes as @martinbonnin said, update or add 

> implementation("com.apollographql.apollo:apollo-runtime:1.2.2")

 to dependencies in build.gradle (the one has apply plugin: 'com.apollographql.android') should fix this.
