### ISSUE TITLE
Support hash-only queries in GraphQL Subscriptions

### ISSUE THREAD

**Issue by ketulshah1947** [apollographql/apollo-android#1850]
**Is your feature request related to a problem? Please describe.**
Currently, Apollo sends the hashed query in the "id" field and full-text query in the "query" field as part of WebSocket message (Reference: OperationClientMessage.Start.writeToJson()). At Wayfair, for security purposes, we want to avoid full-text queries and send only hashed ones. Is there any existing support available for it? If not, and if allowed, I would like to implement it.

**Describe the solution you'd like**
We can accept a parameter from the project Gradle file to decide whether to use a hashed-only query or not. Based on that field we can avoid full-text queries. So it will only send hash over WebSocket. Even if connection is not secure, the query will not be compromised.

**Comment by sav007** [comment]
Not sure if this makes sense but you can try to use query auto persistence feature for this by setting `enableAutoPersistedQueries = true`, here is what it does:
- Apollo will try to send query without query document just with  `extensions { sha256Hash `
- It will send another request with query document only when the GraphQL server returns error such as `PersistedQueryNotFound` or `PersistedQueryNotSupported`

I guess in your case if your server doesn't have auto persisted query feature then technically it should work, though this workaround looks very hacky.

**Comment by ketulshah1947** [comment]
@sav007 I tried but it only works in query and mutation. For subscription cases, it doesn't work. Do you have any insight on it?

**Comment by sav007** [comment]
Yeah, subscriptions is not supported at the moment, sorry I missed this part in the issue description. I think we can add it. I can take a look after the holidays.

**Comment by ketulshah1947** [comment]
@sav007 Sure. I can create PR if you like.
