### ISSUE TITLE
Better error message for "Subscription manager is not configured"

### ISSUE THREAD

**Issue by tir38** [apollographql/apollo-android#1853]
**Is your feature request related to a problem? Please describe.**
I'm trying to setup a subscription for the first time and I'm getting this error:

`
java.lang.IllegalStateException: Subscription manager is not configured
`

**Describe the solution you'd like**

This is not super useful. Maybe add some context on how to resolve it or at least link to the documentation on where to read more about fixing this error.

**Comment by tasomaniac** [comment]
Unfortunately our documentation on Subscriptions are very scarce. It would be really good if you can provide some more details on this. For example: what was the configuration issue you had when you had this error?

**Comment by tir38** [comment]
Sorry I don't remember exactly where I was in the process when I saw this. FWIW we have subscriptions working now.

**Comment by tasomaniac** [comment]
Would you consider contributing to the documentation with the learnings you had? Thanks.
