### ISSUE TITLE
Deprecated field build error

### ISSUE THREAD

**Issue by mastro1984** [apollographql/apollo-android#1855]
**Summary**
I obtain a "Validation of GraphQL query document failed" with deprecated field and ofType null in schema

 

**Description**
if build with schema with this filed

```
{
              "name": "url",
              "description": null,
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": true,
              "deprecationReason": "Use `previewUrl` field"
            },
```

I obtain "Validation of GraphQL query document failed"
If build with this field ( ofType not null )
```
{
              "name": "url",
              "description": null,
              "args": [],
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
                }
              },
              "isDeprecated": true,
              "deprecationReason": "Use `previewUrl` field"
            },

```
Same schema with iOS sdk , I don't occurred any kind of problem

Any idea? 

**Version**
Provide a version of library on which the problem occurred.
classpath 'com.android.tools.build:gradle:3.4.0'
classpath 'com.apollographql.apollo:apollo-gradle-plugin:1.0.0'

implementation 'com.apollographql.apollo:apollo-runtime:1.0.1' 
implementation 'com.apollographql.apollo:apollo-http-cache:1.0.0'

**Comment by tasomaniac** [comment]
Please try with the latest version of Apollo. I believe this is fixed.

**Comment by mastro1984** [comment]
HI @tasomaniac, i confirm version 1.2.2 solved it.
Many thanks, best reguards.
