### ISSUE TITLE
RxJavaExtensions rxQuery and rxMutate operate on original call

### ISSUE THREAD

**Issue by dmitriev2000** [apollographql/apollo-android#1861]
**Summary**
`ApolloClient.rxQuery` and `ApolloClient.rxMutate` extensions do not configure original call and pass original one instead

**Description**
If we look at one of the extensions:
```
inline fun <D : Operation.Data, T, V : Operation.Variables> ApolloClient.rxQuery(
    query: Query<D, T, V>,
    configure: ApolloQueryCall<T>.() -> Unit = {}
): Observable<Response<T>> = query(query).apply(configure).rx()
```

We can see that `.apply(configure)` returns the original call from `query(query)` hence whatever I do within `configure` lambda will be ignored. 

The same applies to all other methods that use `configure` lambda.

**Version**
1.2.2

**Proposal**
Lambda should return a new `ApolloQueryCall` object and it could look like this:

```
inline fun <D : Operation.Data, T, V : Operation.Variables> ApolloClient.rxQuery(
    query: Query<D, T, V>,
    configure: ApolloQueryCall<T>.() -> ApolloQueryCall<T> = { this }
): Observable<Response<T>> = query(query).configure().rx()
```

**Comment by sp00ne** [comment]
The pattern implemented for the apollo calls is that it returns a new instance with the added option. So this seems very much like a bug to me 🤔
