### ISSUE TITLE
Error : arameter specified as non-null is null: method com.apollographql.apollo.compiler.DeprecatedPackageNameProvider.<init>, parameter 

### ISSUE THREAD

**Issue by anshulagarwal06** [apollographql/apollo-android#1871]
**Summary**
 Task :fantasy:generateLiveDebugApolloClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fantasy:generateLiveDebugApolloClasses'.
> Parameter specified as non-null is null: method com.apollographql.apollo.compiler.DeprecatedPackageNameProvider.<init>, parameter schemaPackageName

**Description**
I am getting above error while generating apollo graph ql query

**Version**
Version 1.2.2

**Comment by martinbonnin** [comment]
@anshulagarwal06 what is the layout of your graphql and schema files ? It should be something like this:

```
src/main/graphql/com/example/query.graphql
src/main/graphql/com/example/schema.json
```

**Comment by anshulagarwal06** [comment]
Thanks @martinbonnin . 
It solved this issue
