### ISSUE TITLE
Add documentation for ResponseFetcher API

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#1876]
After closing #1082, I've seen that we are missing documentation on `ResponseFetcher` API. The JavaDocs on this API is actually quite good 👇 

https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/fetcher/ApolloResponseFetchers.java

We should add more info about this into `caching.md` docs.

**Comment by martinbonnin** [comment]
Documentation is now available at https://www.apollographql.com/docs/android/v3/caching/normalized-cache/#setting-a-fetch-policy
