### ISSUE TITLE
Migrate IdlingResources to AndroidX

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#1877]
ApolloIdlingResources still uses old `android.support` libraries. It works fine thanks to Android's Jetifier. 

But still, it would be good to migrate now. 

The module name is called `apollo-espresso-support`. It would be good to use this chance to rename it to `apollo-idling-resource`. Since this will be a breaking change, it would be easier for consumers with module name change.

**Comment by martinbonnin** [comment]
There are other places were we could migrate to androidx, as well do everything at once, right ? `apollo-android-support` and samples mainly
