### ISSUE TITLE
Inline fragment with interface gets generated as Kotlin data class

### ISSUE THREAD

**Issue by vikrama** [apollographql/apollo-android#1886]
**Summary**
An Interface in the schema is generating a new Kotlin data class post-version-upgrade. Say, we use a field in the interface to sort the data after network response and then send it to UI layer, typecasting it to any other implemented classes throws a runtime error.

I did go over all the release notes, but not sure if I missed to read certain changes with inline fragments.

**Description**
From our _schema.json_

```
{
  "kind": "INTERFACE",
  "name": "CollectionItemBase",
  "fields": [
    ...
  ],
  "possibleTypes": [
    {
      "kind": "OBJECT",
      "name": "Implementation1",
      "ofType": null
    },
    {
      "kind": "OBJECT",
      "name": "Implementation2",
      "ofType": null
    },
    {
      "kind": "OBJECT",
      "name": "Implementation3",
      "ofType": null
    }
  ]
}

{
  "kind": "OBJECT",
  "name": "Implementation1",
  "fields": [
    ...
  ],
  "interfaces": [
    {
      "kind": "INTERFACE",
      "name": "CollectionItemBase",
      "ofType": null
    }
  ]
} .. and similar declaration for Implementation2 and Implementation3.

{
  "kind": "UNION",
  "name": CollectionItem",
  "possibleTypes": [
    {
      "kind": "OBJECT",
      "name": "Implementation1",
      "ofType": null
    },
    {
      "kind": "OBJECT",
      "name": "Implementation2",
      "ofType": null
    },
    {
      "kind": "OBJECT",
      "name": "Implementation3",
      "ofType": null
    }
  ]
}
```

This is the sample query
```
queryName(id: $id, context: $context) {
    items {
        ... on CollectionItemBase {
            <fields>
        }
        ... on Implementation1 {
            <more fields>
        }
        ... on Implementation2 {
            <more fields>
        }
        ... on Implementation3 {
            <more fields>
        }
    }
}
```

Before upgrade the generated code didn't create CollectionItemBase as a data class, but now it does. This is creating significant number of runtime typecasting errors.

Before upgrade _Query.kt_
```
data class Item(
 <all fields in interface CollectionItemBase>
 val inlineFragment: ItemCollectionItem?
)
interface ItemCollectionItem { }
data class Implementation1(): ItemCollectionItem
data class Implementation2(): ItemCollectionItem
data class Implementation3(): ItemCollectionItem
```

Newly generated _Query.kt_
```
data class Item(
   <no fields from interface CollectionItemBase>
   inlineFragment: ItemCollectionItem
)
interface ItemCollectionItem { }
data class CollectionItemBase(
  <all fields in schema interface CollectionItemBase>
): ItemCollectionItem
data class Implementation1(): ItemCollectionItem
data class Implementation2(): ItemCollectionItem
data class Implementation3(): ItemCollectionItem
```
Because of the above change, once the network response is typecast to CollectionItemBase, data sorted and sent to UI layer, we're not able to typecast it to other Implementations.

**Version**
I recently upgraded from v1.0.1 to v1.2.2

**Comment by sav007** [comment]
Yeah, so with a latest release we migrated to new GraphQL code gen that is more faster and doesn't require Node JS but with some limitation, like for instance this one.

One recommendation is to try re-arrange the order of inline fragments in your query, first should go more concrete implementations: `Implementation1,2,3` and the last one should be base `CollectionItemBase`. The order of inline fragments will affect on how they parsed from the response, in your case:
```
queryName(id: $id, context: $context) {
    items {        
        ... on Implementation1 {
            <more fields>
        }
        ... on Implementation2 {
            <more fields>
        }
        ... on Implementation3 {
            <more fields>
        }
       ... on CollectionItemBase {
            <fields>
        }
    }
}
```
I hope this might help if I understood the issue right.
In any-way we will try to think how migrate the logic from old codegen to new one.

**Comment by sav007** [comment]
I think this not an issue any you can get access to all possible inline fragments in Kotlin models now.
