### ISSUE TITLE
Class is not abstract and does not implement abstract member

### ISSUE THREAD

**Issue by manwinder123** [apollographql/apollo-android#1898]
**Summary**
- Upgraded from 1.0.0-alpha5 to 1.2.2 and the generated kotlin files give me this error, I get it on all of my graphql queries, I also get the same issue if apollo generates java files

**Description**
- ``` Class 'GeneralQuery' is not abstract and does not implement abstract member @NotNull public abstract fun parse(@NotNull p0: BufferedSource, @NotNull p1: ScalarTypeAdapters): Response<GeneralQuery.Data!> defined in com.apollographql.apollo.api.Query ```

**Version**
v1.2.2

**Comment by martinbonnin** [comment]
Can you quickly check if you're using 1.2.2 for the gradle plugin `apollo-gradle-plugin`as well as `apollo-runtime` ? That sounds like both are not in sync.

**Comment by rourkepoulton99** [comment]
If your using parcelize, you might have a plugin error  which might me using the wrong depencies. 
I saw this great answer which worked for me. 
1. Go to gradle app module
2. Outside of the android block before the depencies add this :
androidExtensions {
experimental = true
features = ["parcelize"]
}
3. Make sure you have these plugins applied:
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
