### ISSUE TITLE
float8 in .graphql generates java.lang.Float

### ISSUE THREAD

**Issue by tir38** [apollographql/apollo-android#1905]
**Summary**
We have a .graphql with some `float8` input arguments

`query GetEvents($limit: Int!, $timestamp: float8) {... }`

When apollo generates java classes to call, it expects a `java.lang.Float`

```
public final class GetEventsQuery
    public Builder timestamp(@Nullable Float timestamp) {
        this.timestamp = Input.fromNullable(timestamp);
        return this
    }
    ...
}
```

The problem is that float8 is 64 bit but `java.lang.Float` is only 32 bit. So we lose some precision when converting our timestamps to `Float`. Instead Apollo should generate `java.lang.Double` which has 64 bit precision.

```
public Builder timestamp(@Nullable Double timestamp) {
    this.timestamp = Input.fromNullable(timestamp);
    return this
}
```

**Version**

Apollo Gradle Plugin 1.2.0
com.apollographql.apollo:apollo-runtime:1.2.0
com.apollographql.apollo:apollo-rx2-support:1.2.0 (this prob doesn't matter)

**Comment by tir38** [comment]
Actually I'm curious why this is happening. IIUC apollo should be mapping float to double

https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/JavaTypeResolver.kt#L27

**Comment by sav007** [comment]
GraphQL doesn't support scalar type `float8` out of the box https://graphql.org/learn/schema/#scalar-types. That tells me that you probably have apollo gradle configuration that maps `float8` into `Float`?

**Comment by tir38** [comment]
Yes thanks you are absolutely correct.
