### ISSUE TITLE
Unsupported token '['

### ISSUE THREAD

**Issue by Kwasow** [apollographql/apollo-android#1909]
I've created the .graphql file and placed it in the appropriate directory. Now trying to rebuild the project I'm getting the error: `Unsupported token '['`

Here is the wider output of my build:

ERROR
Unsupported token '['

[1]:type Query {
[2]:  videos: [Video]
[3]:  podcasts: [Podcast]

Here is my graphql file I've created from the graphql I downloaded from the server:

type Query {
  videos: [Video]
  podcasts: [Podcast]
}

type Thumbnail {
  high: String
}

type Video {
  id: String
  title: String
  description: String
  topic: String
  channel: String
  date: String
  thumbnail: Thumbnail
  video: String
  audio: String
  tags: [String]
  shareState: Int
  scheduledDate: String
}

type Podcast {
  id: String
  title: String
  description: String
  topic: String
  channel: String
  date: String
  thumbnail: Thumbnail
  audio: String
  shareState: Int
}

I've created my schema.json using this tool:
https://transform.tools/graphql-to-introspection-json

I'm using these versions:
classpath 'com.apollographql.apollo:apollo-gradle-plugin-incubating:1.2.3'
implementation 'com.apollographql.apollo:apollo-runtime:1.2.3'
implementation 'com.apollographql.apollo:apollo-android-support:1.2.3'

My app is in Java

**Comment by sav007** [comment]
could you please share the `schema.json` and  GraphQL query? It looks like either the content of `schema.json` is invalid or your query.

**Comment by Kwasow** [comment]
Here is my schema.json:
[schema.json.txt](https://github.com/apollographql/apollo-android/files/4077320/schema.json.txt)
Here is my graphql:
[FeedQuery.graphql.txt](https://github.com/apollographql/apollo-android/files/4077329/FeedQuery.graphql.txt)
And here is a graphql I downloaded from the server:
[schema.graphql.txt](https://github.com/apollographql/apollo-android/files/4077330/schema.graphql.txt)
I modified the server one to create my ow version

**Comment by sav007** [comment]
Your graphql query is not valid query, pls check the GraphQL specs: https://graphql.org/learn/queries/
