### ISSUE TITLE
ResponseFetcher CACHE_AND_NETWORK not working

### ISSUE THREAD

**Issue by manwinder123** [apollographql/apollo-android#1911]
**Summary**
- Hello friends :)

- Came across `CACHE_AND_NETWORK` `ResponseFetcher`, it does exactly what I need. I am only using queries (I assume what is inside the query doesn't matter as long as it's a query and not a mutation?). When I set breakpoints in `CacheAndNetworkFetcher` I find that there are always cache misses.

**Description**
- I have tried using `httpCachePolicy` of `HttpCachePolicy.CACHE_FIRST`, `HttpCachePolicy.NETWORK_FIRST`, and no `httpCachePolicy`, while using the `ResponseFetcher`. All result in the same issue that there is a cache miss in `CacheAndNetworkFetcher`. When I set the `httpCachePolicy` to `CACHE_FIRST` the response's `fromCache` function (`Response<GeneralQuery.Data>`) returns true so the the response is being cached but the `ResponseFetcher` still says there is a cache miss. The response fetcher does work as intended though, based on `onStatusEvent` function in `ApolloCall.Callback` I do get a `ApolloCall.StatusEvent.SCHEDULED`, then `ApolloCall.StatusEvent.FETCH_CACHE`, then `ApolloCall.StatusEvent.FETCH_NETWORK`.

- Should I be using a different type of cache, I am using HTTP cache with Apollo, maybe a different cache policy?

- Thanks for any help :)

**Version**
1.2.2

**Update**
- Here is my cache related code: 

```
        val file = File(File(App.context.cacheDir.toURI()), "apollo")
        val size = Constants.GRAPHQL_CACHE_SIZE

        val cacheStore = DiskLruHttpCacheStore(file, size)
        val apolloCache = ApolloHttpCache(cacheStore)
```
- Don't think it matters but I have an interceptor on my `OkHttpClient`

**Comment by sav007** [comment]
Apollo has 2 types of caching:
- http cache based purely on http response payload cache,  as a key it uses hash from request payload to be sent to the server, it is not normalized cache  - means query doesn't share cached data
- normalized cache , means query sharing the same cache storage and can see the same data.

First thing I would suggest to disable http cache, as it looks like the issue with normalized cache. If you see the same issue let me know, we can debug together, I will need your query and wiill send instructions how to dump the content of normalized cache

**Comment by tasomaniac** [comment]
Here is the test case for `CACHE_AND_NETWORK`: https://github.com/apollographql/apollo-android/blob/master/apollo-integration/src/test/java/com/apollographql/apollo/internal/fetcher/CacheAndNetworkFetcherTest.java

According to `BaseFetcherTest` class, the cache is initialized like with this `       .normalizedCache(new LruNormalizedCacheFactory(EvictionPolicy.NO_EVICTION), new IdFieldCacheKeyResolver())`

Can you see if it is similar to what you've been doing. Or even better, it would be good if you can add a test case for reproducing the issue.

**Comment by manwinder123** [comment]
@sav007  @tasomaniac thanks for the help I made the switch, removed http cache and switched to normalized in memory cache with sql cache chained:
```
    val apolloSqlHelper = ApolloSqlHelper.create(App.context, "apollo_db")
    val sqlCacheFactory = SqlNormalizedCacheFactory(apolloSqlHelper)
    val memoryFirstThenSqlCacheFactory = LruNormalizedCacheFactory(
            EvictionPolicy.NO_EVICTION
    ).chain(sqlCacheFactory)
```

I still have http cache on my OkHttp Client, I wonder if that is causing issues:
`OkHttpClient.Builder().cache(Cache(File(App.context.cacheDir, "okhttp"), Constants.CACHE_SIZE))`. I have tested it without the OkHttp cache and it still acts the same way, read more below.

In memory cache works as long as the app is open but also works when I hit back on my android app and open the app but obviously doesn't work if I close the app and go into airplane mode. The SQL cache unfortunately didn't work offline. I checked the cache resolver and it is returning keys when using in memory, sql, and both in memory & sql cache:

```
private fun apolloCacheResolver() = object: CacheKeyResolver() {
        override fun fromFieldRecordSet(field: ResponseField, recordSet: MutableMap<String, Any>): CacheKey = formatCacheKey(recordSet["__typename"].toString())

        override fun fromFieldArguments(field: ResponseField, variables: Operation.Variables): CacheKey = formatCacheKey(field.resolveArgument("__typename", variables).toString())

        fun formatCacheKey(id: String?): CacheKey {
            return if (id == null || id.isEmpty()) {
                CacheKey.NO_KEY
            } else {
                CacheKey.from(id)
            }
        }
    }
```
In the `onResponse` method inside `ApolloCall.Callback<T>` I am only seeing 1 call per request, in the test files provided there are 2 calls to `onResponse`, 1 for cache, 1 for network. 

Why would the sql cache not work for me, maybe the data that is returned by my queries isn't supported?

**Comment by manwinder123** [comment]
Any updates on this @sav007 @tasomaniac :)

**Comment by tasomaniac** [comment]
I wanted try this with our project to see what happens. I don't think I will have time soon. It would be great if you can reproduce this either on an open source project or in our sample. Otherwise, it is not easy to figure out what's wrong.

**Comment by manwinder123** [comment]
I'll try doing that :)

**Comment by tasomaniac** [comment]
@manwinder123 any updates? Since we have a working test cases, it would be really good to have a reproducible project to see what's going on here.

**Comment by manwinder123** [comment]
> @manwinder123 any updates? Since we have a working test cases, it would be really good to have a reproducible project to see what's going on here.

Ya apparently one of the latest updates fixed the issue. We're able to use normalized cache. Thanks ☺
