### ISSUE TITLE
Is there a method that I can use to check if my subscription is already subscribed

### ISSUE THREAD

**Issue by SaurabhKukreja** [apollographql/apollo-android#1918]
**Summary**
I am adding subscriptions from a service and every time I bind to a service I am subscribing to subscriptions. and if its there, I get an error saying Subscription already added. 

is there a method that I can use to check if my subscriptions are already running fine?

**Comment by sav007** [comment]
` I get an error saying Subscription already added.` is this error message coming from the server?

**Comment by sav007** [comment]
closing out of date.
