### ISSUE TITLE
Gradle error from generateApolloClasses

### ISSUE THREAD

**Issue by yusufa2z** [apollographql/apollo-android#1927]
**Summary**
When I follow the steps in the readme, the generateApolloClasses step fails.

**Description**
The step 
> ./gradlew :generateApolloClasses

Gives the error 

> Task 'generateApolloClasses' not found in root project 'My Application'.

When I run
> ./gradlew tasks

It shows generateApolloClasses as one of the available Apollo tasks. If I then run Gradle with the --info option, it gives some complaint about an enum:
> Analytics other plugin to proto: Unknown plugin type com.apollographql.apollo.gradle.ApolloPlugin expected enum COM_APOLLOGRAPHQL_APOLLO_GRADLE_APOLLOPLUGIN

**Version**
Apollo Plugin version 1.2.3
Gradle version 6.1-rc-1

**Comment by tasomaniac** [comment]
Can you try without colon before the task name?

**Comment by martinbonnin** [comment]
The Analytics warning is unrelated. I have it as well, it seems to come from the Android Gradle Plugin: https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/profile/AnalyticsUtil.java?autodive=0%2F#383

**Comment by ys1382** [comment]
@tasomaniac you are right, removing the colon fixed the issue, although the colon is in the readme. Perhaps it is a change for Gradle 6?

**Comment by martinbonnin** [comment]
That was a mistake, sorry. Fix is there: https://github.com/apollographql/apollo-android/pull/1950/files

**Comment by tasomaniac** [comment]
@ys1382 colon prefix means root project in Gradle. It is not a change with Gradle 6. It basically depends on how you setup the project. Without colon, it searches for the given task everywhere.
