### ISSUE TITLE
[Code Generation] enums generated in non-deterministic order in CustomType.java

### ISSUE THREAD

**Issue by anoopc1** [apollographql/apollo-android#1928]
**Summary**

`apollo` gradle-plugin generates classes with slightly different source-code when clean build is performed multiple times on the same commit.

This can lead to inconsistent cache-keys for the targets transitively affected by these source files (and negatively impacts effectiveness of remote build-cache for us).

**Example:**
Enums generated in `CustomType.java` are in different order between two builds (`DATETIME ` & `JSON` enums).
- [gist-file-content-build-1](https://gist.github.com/anoopc1/69747405a2b84f0bdf66a528820ebd22)
- [gist-file-content-build-2](https://gist.github.com/anoopc1/0ce06419169f278d1963e21d7d101639)
---
I suspect this is because `CustomTypes` class ([apollo-android::AST.kt](https://github.com/apollographql/apollo-android/blob/6d309a6125e0d15e595e10bc2f1d3b86e889622d/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/ast/AST.kt#L3)) uses regular `Map` instead of `SortedMap` and code-generation ([apollo-android::CustomTypes.typeSpec()](https://github.com/apollographql/apollo-android/blob/6d309a6125e0d15e595e10bc2f1d3b86e889622d/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/codegen/kotlin/CustomType.kt#L16)) iterates over it in a non-deterministic order.

**Version**
`1.2.3`

**Comment by sav007** [comment]
Very strange, as Kotlin by default uses linked hash set / map that preserves order for any operations like union, map, etc. So `CustomTypes(map: Map<String, String>)`  uses linked hash map implementation of Map. 

Another strange thing is that I couldn't reproduce this issue on our test fixtures. I will keep investigating but as for now that super strange.

**Comment by sav007** [comment]
Agh, I didn't pay attention that it's Java code generation that uses old AST builder.

**Comment by anoopc1** [comment]
Yes, this is for `Java` code generation. I should have mentioned that explicitly (my bad 😞).
@sav007 Is there an easy fix for this issue?
