### ISSUE TITLE
Broken documentation link to now deprecated Gradle Plugin

### ISSUE THREAD

**Issue by louistsaitszho** [apollographql/apollo-android#1929]
**Summary**
There is no longer any link to the deprecated gradle plugin documentation, but the link is still there in the introduction page.

**Description**
After the changes in #1914, in the [introduction page](https://www.apollographql.com/docs/android/#getting-started), `Gradle Plugin (soon to be deprecated)` links to the doc new plugin, while the `Incubating Gradle Plugin` links to "Page not found".

Do you want to recreate the old document back, or just remove it all together?

**Version**
N/A

**Comment by martinbonnin** [comment]
Sorry about that. There's a disconnect between docs in master (1.3.0) and the latest release (1.2.3).  You can access the 1.2.3 documentation at https://github.com/apollographql/apollo-android/blob/v1.2.3/doc/plugin-configuration.md
