### ISSUE TITLE
Document inlineFragment removal in migration guide

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#1934]
It looks like https://github.com/apollographql/apollo-android/pull/1891 removed `.inlineFragment`  ? It was nice to be able to do the below:

```kotlin
when (hero.inlineFragment) {
    is Hero.AsHuman -> ...
    is Hero.AsDroid -> ...
}
```

I believe a few users will bump into this, we should document it in https://github.com/apollographql/apollo-android#migrating-to-13x

**Comment by tasomaniac** [comment]
Was it intentional though?

**Comment by martinbonnin** [comment]
I'm not sure and I'm not super familiar with that part. Maybe @sav007 will know ?

**Comment by sav007** [comment]
Yes this changes were intentional, I will provide release notes and update docs to mention reasons of these changes
