### ISSUE TITLE
Add default value for __typeName in generated Kotlin model objects

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-android#1936]
```
  data class MyEntity(
    val __typename: String,
    val id: Int
  )
```
For creating mock response objects, it would be helpful to not have to specify the `__typename`, especially since Fragments are now verifying the `__typename` when parsing the json.  Any chance we could update the codegen to give a default value for this field?  I'm happy to do the PR if this would be acceptable

**Comment by martinbonnin** [comment]
I bumped into that as well. I was using `POSSIBLE_TYPES[0]` but this is not available in 1.3.0 anymore.

**Comment by sav007** [comment]
@martinbonnin is there any other use case where you used `POSSIBLE_TYPES `?

**Comment by martinbonnin** [comment]
Creating mock objects was the only use case where I used `POSSIBLE_TYPES`. It felt a bit like a hack so I don't mind too much seeing it go away but having a way to get the `__typename` of a model would be nice.

**Comment by edenman** [comment]
How would folks feel about just removing it from the constructor entirely? Doesn’t seem like you’d ever actually want to pass in a different value

**Comment by sav007** [comment]
We can't just remove it as it heavily used in normalized cache. But we can definitely make it optional.

**Comment by tasomaniac** [comment]
I think @edenman meant removing only from the constructor. It would still stay as a property and would be part of de/serialization.

**Comment by edenman** [comment]
(finally updated and wanted to say my mock mode implementation thanks you for this change!)
