### ISSUE TITLE
Documentation mirroring

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#1941]
The documentation contains a few duplicates at the moment, mainly https://www.apollographql.com/docs/android/essentials/get-started/ that duplicates a lot of the content from https://github.com/apollographql/apollo-android/blob/master/README.md.

We could make apollographql.com mirror github.com. The idea would be to add a script that preprocesses the markdown files before building the gatsby site:
* Copy README.md to ~index.mdx~ gettting-started.md. 
* Add the title headers needed by gatsby.
* Strip the link to apollographql.com from README.md like okhttp does: https://github.com/square/okhttp/blob/master/deploy_website.sh#L55
* Fix relative links.

This way we'll have the same documentation on both sites.

**Comment by ralphie9224** [comment]
@martinbonnin are you working on this or can I give it a go?

**Comment by martinbonnin** [comment]
@ralphie9224 go for it !

**Comment by ralphie9224** [comment]
@martinbonnin what's the best way to test this?

**Comment by martinbonnin** [comment]
@ralphie9224 The changes on master get deployed automatically. If you want to test on your fork, you'll need to setup a netlify account. The configuration is in this file: https://github.com/apollographql/apollo-android/blob/master/netlify.toml

**Comment by tasomaniac** [comment]
Sorry, I accidentally closed. Should this be close, tho?

**Comment by martinbonnin** [comment]
Yep, it's good to close now 👍
