### ISSUE TITLE
Gradle plugin marker artifact is not synced to jcenter

### ISSUE THREAD

**Issue by technoir42** [apollographql/apollo-android#1946]
**Summary**
Gradle plugin marker artifact is published to Apollo bintray repository but not synced to jcenter.

**Description**
I am able to apply the plugin using Gradle plugins DSL only if I add Apollo's bintray repository to the list of plugin repositories:
```gradle
plugins {
    id "com.apollographql.apollo" version "1.3.0"
}
```

```gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
        jcenter()
        maven { url "https://dl.bintray.com/apollographql/android" }
    }
}
```

Please link this package 
https://bintray.com/apollographql/android/com.apollographql.apollo.gradle.plugin to jcenter so it could be used without adding Apollo's repository.

**Version**
1.3.0

**Comment by martinbonnin** [comment]
Unfortunately, Bintray does not allow packages without a binary file like jar, aar, etc... to be promoted to jcenter. See https://github.com/apollographql/apollo-android/pull/1933 for a few more details.

I reached out to their support to see if that can be fixed.

We also publish to the Gradle plugin portal so ultimately, you should be able to pick up the marker artifact from there. Unfortunately, version 1.3.0 is still pending approval at the moment. It will be available there ultimately: https://plugins.gradle.org/plugin/com.apollographql.apollo

**Comment by technoir42** [comment]
Oh great, Gradle Plugin Portal is even better! Feel free to close this issue.
