### ISSUE TITLE
operationIdGenerator not working in onCompilationUnits

### ISSUE THREAD

**Issue by louistsaitszho** [apollographql/apollo-android#1948]
**Summary**
`operationIdGenerator` not working in `onCompilationUnits`

**Description**
Continuation of #1849: I want to override the operation ID, but this time also based on the variant (e.g. turn it into compiler error on release build), which mean I would like to provide `operationIdGenerator` inside `onCompilationUnits` to access `variantName`. However, it doesn't seem to be working.

Example: [this repo](https://github.com/louistsaitszho/TestApollo), which pulls the schema & query from the [kotlin sample](https://github.com/apollographql/apollo-android/tree/master/samples/kotlin-sample/src/main/graphql/com/apollographql/apollo/kotlinsample). In gradle, it has been configured as follow: 

```groovy
apollo {
    generateKotlinModels = true
    onCompilationUnits {
        operationIdGenerator = new com.apollographql.apollo.compiler.OperationIdGenerator() {
            String apply(String operationDocument, String operationFilepath) {
                return "CompilationUnits " + varientName
            }

            String version = "v5000"
        }
    }
}
```

According to [the doc](https://www.apollographql.com/docs/android/essentials/plugin-configuration/#apolloextension-services-and-compilationunits), things in `CompilationUnit` should override `Service` and `ApolloExtension`, i.e.

- Expectation: `GitHubRepositoriesQuery` contains `OPERATION_ID` of `CompilationUnits ${variantName}`

- Reality: It falls back to the default hash(`d7e037c5b4f5ccf0f3645dd02be41f4b7dea24829b23d729cbfedf103de5a963`)

Is it because [it always falls back to the one provided by `ApolloExtension`?](https://github.com/apollographql/apollo-android/blob/v1.3.0/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/internal/ApolloPlugin.kt#L196)

**Version**
1.3.0

**Comment by martinbonnin** [comment]
> Is it because it always falls back to the one provided by ApolloExtension?

Nice catch. I'm not sure why there was an exception for operationIdGenerator.
