### ISSUE TITLE
Add ability to prefetch raw response. 

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#195]
To fulfill background update/syncing it would be nice to be able to defer parsing until data is read rather than when it is downloaded.  The idea is to have a mechanism to prefetch graph responses but not yet inflate into models.  Maybe this can be rolled into into the cache implementation.

Use Case:
NY Times wants to download all the days articles overnight and store them for offline use.  There is no reason to inflate the models prior to storing as a user may not see the data before it will become stale.  When a user opens a screen apollo client should be able to inflate the json for a particular query and then return it to the user.

This feature would ideally separate "apollo downloader" from "apollo parser"  allowing a user to download a query result but never inflate it.

**Comment by martijnwalraven** [comment]
I think this feature could be implemented in terms of a response cache. If we give the network interface the ability to prefetch responses without parsing them, we could then store them on disk and have future requests read them from there.

A response cache is obviously less flexible than a normalized cache, because it is tied to a particular query and variables. But it seems like a good fit for use cases like this.

**Comment by digitalbuddha** [comment]
Response cache sounds reasonable. I'd still want to be able to utilize a normalized cache as well if possible. This would be bytes caching while the normalized one can be pojo caching imo

**Comment by martijnwalraven** [comment]
Yep, that's exactly what I had in mind. When you read a response from the response cache and parse it into model types it will be normalized and put into the cache as usual.

**Comment by digitalbuddha** [comment]
Basic Idea:
Since we are using `OKHTTP` we should exploring making an ApolloCacheInterceptor for full request/response caching.    I see this working as:
We implement a Request/Response Cache on disk, for each request the `Cache` can return a `Record` which will contain a`RecordState` == {FRESH, STALE, MISSING}.  

**On new query request if cache is:**
- FRESH -> Return cached response
- STALE -> Hit Network, Update Cache, If network error return stale response (Network before Stale)
- MISSING -> Hit network update cache

When the Interceptor is instantiated Users can pass in an `ExpirationDuration` which will drive the Stale logic.

Additionally, we need a way to pass in a flag `FORCE_NETWORK` to bust through the cache on a per request basis.  Initial proposal is to have a flag when creating a query `new Query(TRUE|FALSE)` which will drive the response caching policy.  We would also need a way to clear the cache, say if a user logs out of an account.

Ideally we would also create a new ApolloClient public api
`void prefillCache(query)`
`Callback prefill(query)`

This would allow the prefilling of the request/response cache in a raw form without ever having to fill the normalized cache.

https://github.com/square/okhttp/wiki/Interceptors

**Comment by digitalbuddha** [comment]
We should use the concept of a `MirrorSource` to split a okhttp `BufferedSource` into 2, allowing us to stream data to the response cache and parser concurrently.

Implementation:
https://gist.github.com/digitalbuddha/18019a61a0d15eb9f7f53f03685418bb

**Comment by digitalbuddha** [comment]
@sav007 one more thing that we need is a way to cache without parsing the whole "prefetch" aspect.  I think we need a way to do `apollCall.prefetch()` which would be a void sync fetch

**Comment by sav007** [comment]
@digitalbuddha for prefetch I was thinking to have different call like:
```
public interface ApolloPrefetchCall<T extends Operation.Data> {

  @Nonnull Response<T> execute() throws IOException;

  @Nonnull ApolloCall<T> enqueue(@Nullable Callback<T> callback);

  void cancel();

  @Nonnull ApolloCall<T> clone();

  interface Callback<????> {
    void onResponse(@Nonnull ????);

    void onFailure(@Nonnull Exception e);
  }
```
