### ISSUE TITLE
Null variable on request breaks caching 

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-android#1954]
**Summary**
`CacheFieldValueResolver` can't find cached results when a query parameter/variable is null. 

**Description**
Been seeing some unexpected cache misses in my logcat.  I set a breakpoint on `CacheFieldValueResolver` line 101 (where it throws an NPE). 
The root record has this:
```
entries({"location":5570,"scope":"mine"}) -> {ArrayList@8554} size = 0
```
But the `fieldKey` is:
```
entries({"location":5570,"scope":"mine","status":null})
```
I'm building the query like this:
```
    val query = EntriesQuery(
      locationId = id,
      scope = if (onlyShowMine) "mine" else "all",
      status = status.apiStatus.toInput())
```
where apiStatus is a nullable kotlin field.  

Looks like `RealCacheKeyBuilder` calls `setSerializeNulls(true)` which is why the value is included when looking up the value.  Not sure what is responsible for the fieldKey in the root record not having the `"status":null`

**Version**
Apollo 1.3.0 using Kotlin codegen.
Kotlin 1.3.61
AGP 3.5.3

**Comment by sav007** [comment]
@edenman sorry for the delay

Not really sure what is happening here as serialization of `Input` types is guarded by condition to check if it was defined or not before marshalling it, [for example](https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/input_object_type/type/ReviewInput.kt#L113-L115)

So in your case `status.apiStatus.toInput()` for status `null` will return `Input.absent` and `RealCacheKeyBuilder` should omit it during building a cache key.

Could you please put a breakpoint in `com.apollographql.apollo.internal.cache.normalized.RealCacheKeyBuilder#resolveVariableArgument` for `} else if (resolvedVariable instanceof InputType) {` branch and see how `status` is going to be marshalled (check the result of `inputFieldMapWriter.map()`).

**Comment by edenman** [comment]
np, I know yall are busy. Here's what the debugger looks like when processing the `status` variable:

<img width="1215" alt="Screen Shot 2020-02-10 at 4 54 41 PM" src="https://user-images.githubusercontent.com/1063557/74193824-13a0e080-4c26-11ea-8fef-6912ae4cd68d.png">

**Comment by edenman** [comment]
maybe it's a problem with the Kotlin codegen?  Here's what the `valuesMap()` method looks like:
```
    override fun valueMap(): Map<String, Any?> = mutableMapOf<String, Any?>().apply {
      this["locationId"] = locationId
      this["scope"] = scope
      if (status.defined) this["status"] = status.value
    }
```

**Comment by martinbonnin** [comment]
Hi 👋 I'm pretty confident this would work with Apollo Android 3 codegen. Can you try the [release candidate](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-rc01) and let us know how that goes?

**Comment by edenman** [comment]
I left this job a year and a half ago, sorry!

**Comment by martinbonnin** [comment]
Completely fair 😄  !
Thanks for the update! I'll close this issue for now! All the best for the (not so) new job!
