### ISSUE TITLE
Identifier 'yield' is reserved

### ISSUE THREAD

**Issue by And-smile** [apollographql/apollo-android#1957]
**Summary**
Error during build kotlin application: Identifier 'yield' is reserved. Use backticks to call it: `yield` 

**Description**
I have field called 'yield' in graphql query.
I generate sources using:	
./gradlew generateApolloSource
with generateKotlinModels=true

**Version**
v1.3.0

**Comment by sav007** [comment]
You can always use aliases, but agree this is a bug.

**Comment by tasomaniac** [comment]
I would expect this to be handled by KotlinPoet library. It would be a nice feature for them.

**Comment by And-smile** [comment]
@sav007 thanks for the tip with aliases.
