### ISSUE TITLE
Unsupported token `[`

### ISSUE THREAD

**Issue by littlecienbak** [apollographql/apollo-android#1962]
Hello!

I got an error from my auto generated schema.json.graphql from the code below:

`type Chat {
    room: [Room!]!
}`

error message:

Failed to parse GraphQL file <file path>\schema.json.graphql (9:10)
Unsupported token `[`
----------------------------------------------------
[8]:type Chat {
[9]:    room: [Room!]!
[10]:}
----------------------------------------------------

**Comment by littlecienbak** [comment]
I thought I got an answer at issue [#1909](https://github.com/apollographql/apollo-android/issues/1909). I copied the query from the playground, still got this error.

**Comment by littlecienbak** [comment]
[schema.json.graphql.txt](https://github.com/apollographql/apollo-android/files/4145983/schema.json.graphql.txt)
[Uploading schema.json.txt…]()
[Uploading EmployeeQuery.graphql.txt…]()

**Comment by littlecienbak** [comment]
[EmployeeQuery.graphql.txt](https://github.com/apollographql/apollo-android/files/4145987/EmployeeQuery.graphql.txt)
[schema.json.graphql.txt](https://github.com/apollographql/apollo-android/files/4145988/schema.json.graphql.txt)
[schema.json.txt](https://github.com/apollographql/apollo-android/files/4145989/schema.json.txt)

**Comment by martinbonnin** [comment]
Can you remove the '.graphql' extension from your schema file ?

The plugin expects a `schema.json` and some `.graphql` query files. It looks like it's trying to compile your `schema.json.graphql` as a query file which isn't going to work

**Comment by littlecienbak** [comment]
Thanks, It works. But can I still have the `schema.json.graphql` in my directory without getting error? It kinda help me a lot.

**Comment by littlecienbak** [comment]
Thanks, It works. But can I still have the schema.json.graphql in my directory without getting error? It kinda help me a lot.

**Comment by martinbonnin** [comment]
@littlecienbak you can if you tweak `CompilerParams.schemaFile` and `CompilerParams.graphqlSourceDirectorySet`. See https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/api/CompilerParams.kt#L132

It's a more complex use case but you should be able to do something like:

```
apollo {
    schemaFile = file("src/main/graphql/com/example/schema.json.graphql")
    graphqlSourceDirectorySet.srcDir("src/main/graphql")
    graphqlSourceDirectorySet.exclude("**/schema.json.graphql")
}
```

It may vary depending your configuration so don't take that as gospel.
