### ISSUE TITLE
response.extensions() is always null

### ISSUE THREAD

**Issue by oscar-ko** [apollographql/apollo-android#1964]
**Summary**
response.extensions() is always null

**Description**
I was trying to get the extension fields in the errors block. Every field seems ok... response.data(), response.hasErrors()... However, response.extensions() is always null. It's useful when chekcing the exception type.

Here is the okHttp body:
---->D/OkHttp: {"errors":[{"message":"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.","**_extensions_**":{"guards":[],"category":"authentication"},"locations":[{"line":1,"column":46}],"path":["login"],...

But when I checked the logs by using the followings: Log.d(TAG,"extensions are:"+ response.extensions().toString())  / Log.d(TAG,"errors are:"+ response.errors().toString()),  
The extension field is always null.  It even disappeard in the customAttributes block...

----> extensions are:null
D/AuthDataModel: errors are:[Error{message='The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.', locations=[Location{line=1, column=46}], customAttributes={path=[login], trace=[{file=C:\wamp\laravel\vendor\joselfonseca\lighthouse-graphql-passport-auth\src\GraphQL\Mutations\Login.php...

Here is the complete errors in json format: [errors_json.txt](https://github.com/apollographql/apollo-android/files/4146669/errors_json.txt)
![errors](https://user-images.githubusercontent.com/33344160/73593619-1c682700-4541-11ea-9027-0b0eaaada1d9.png)
**Version**
Apollo-android v1.3.0
Kotlin / Android Studio 3.5.3

**Comment by sav007** [comment]
From your response I see that `extensions` is a part of error, means you should probably check `com.apollographql.apollo.api.Error#customAttributes` instead.

**Comment by oscar-ko** [comment]
Thank you very much for your kind help.
