### ISSUE TITLE
Fragments fail to select on an interface that is different from the response interface

### ISSUE THREAD

**Issue by gsabran** [apollographql/apollo-android#1975]
**Description**

Let's consider
```graphql
# schema
interface FooInterface {
  foo: String
}
interface BarInterface {
  bar: String
}
type FooBar implements FooInterface & BarInterface {
  foo: String
  bar: String
}
type Query {
  getFoo: FooInterface
}
schema {
  query: Query
}

# query
query GetFoo {
  getFoo {
    foo
    ... on BarInterface {
      bar
    }
  }
}
```
The codegen fails saying ```Fragment cannot be spread here as objects of type `FooInterface` can never be of type `BarInterface` ``` which is inaccurate.

Maybe related to https://github.com/apollographql/apollo-android/pull/1633

**Comment by sav007** [comment]
I might missing something here but:
- `getFoo: FooInterface'
-  `BarInterface` is not a subtype of `FooInterface`
-  `FooBar ` is not used by anyone

So looks like error is legit or sample is not valid.

**Comment by gsabran** [comment]
Hum. I don't think there's a notion of subtype in GQL, only types that conform to interfaces, and unions that are a list of types.

`getFoo: FooInterface` means that the result of `getFoo` will be any type that conforms to interface `FooInterface`. For instance the result could be a `FooBar`. So it is possible to have an inline fragment on `BarInterface`.

The compiler could maybe throw an error if none of the types implementing `FooInterface` didn't implement `BarInterface`, even though this is not forbidden by the GQL specs afaik.

**Comment by sav007** [comment]
https://spec.graphql.org/June2018/#sec-Interfaces

**Comment by gsabran** [comment]
Thanks for fixing! 🎉
