### ISSUE TITLE
incompatible types in generated code

### ISSUE THREAD

**Issue by justtonytone** [apollographql/apollo-android#1976]
Hello,

I am using the maven plugin (https://github.com/aoudiamoncef/apollo-client-maven-plugin), in case that makes any difference.

The code that gets generated contains a java error:

```java
          writer.writeList($responseFields[20], objects, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              // Error on Object below: Error:(732,34) java: incompatible types: java.lang.Object cannot be converted to com.example.graphql.client.QueryResourceQuery.Object
              for (Object item : items) {
                listItemWriter.writeObject(((Object) item).marshaller());
              }
            }
          });
```

This looks like it's due to our graphql schema having a return field named `objects`, which generates a `public static class Object` and so the for loop up above perhaps should be using `java.lang.Object`. Aliasing the field in the query seems to be a pretty simple fix. Is this the expected behavior?

**Comment by sav007** [comment]
Yeah it's GraphQL schema object type `Object` is clashing with Java reserved word. Will investigate how to fix this

**Comment by sav007** [comment]
meantime you can try to use aliases to fix this clash
