### ISSUE TITLE
Auto Generate ApolloConverterFactory with response mappers

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#198]
The setup process seems a little unwieldy to have to register a new ResponseMapper for each new query.  It would be nice to leverage code gen to make the process easier.  Initial proposal is to generate `MyApolloConverterFactory` which will already have the response mappers registered. This way adding a new query does not mean that I need to make changes to my restadapter.

**Comment by martinbonnin** [comment]
That would be very handy indeed, I always forget to register these responseFieldMappers...

**Comment by sav007** [comment]
How about we will generate for POJO:

```
public abstract class ResponseFieldMappers {
  Map<Type, ResponseFieldMapper> MAPPERS = Collections.unmodifiableMap(
      new HashMap<Type, ResponseFieldMapper>() {
        {
          put(AllPlanets.Data.class, new AllPlanets.Data.Mapper(AllPlanets.Data.FACTORY));
          put(ProductsWithDate.Data.class, new ProductsWithDate.Data.Mapper(ProductsWithDate.Data.FACTORY));
          put(ProductsWithUnsupportedCustomScalarTypes.Data.class,
                new ProductsWithUnsupportedCustomScalarTypes.Data.Mapper(ProductsWithUnsupportedCustomScalarTypes.Data.FACTORY));
        }
      }
  );

  private ResponseFieldMappers() {
  }
}
```

And now instead of:
```
new ApolloConverterFactory.Builder()
            .withResponseFieldMapper(AllPlanets.Data.class, new AllPlanets.Data.Mapper(AllPlanets.Data.FACTORY))
            .withResponseFieldMapper(ProductsWithDate.Data.class, new ProductsWithDate.Data.Mapper(ProductsWithDate
                .Data.FACTORY))
            .withResponseFieldMapper(ProductsWithUnsupportedCustomScalarTypes.Data.class,
                new ProductsWithUnsupportedCustomScalarTypes.Data.Mapper(ProductsWithUnsupportedCustomScalarTypes.Data.FACTORY))
            .withCustomTypeAdapter(CustomType.DATETIME, dateCustomTypeAdapter)
            .build()
```

we will have this:
```
new ApolloConverterFactory.Builder()
            .withResponseFieldMappers(ResponseFieldMappers.MAPPERS)
            .withCustomTypeAdapter(CustomType.DATETIME, dateCustomTypeAdapter)
            .build()
```

So you will do it only once and no need to register new mappers, they will be added by generated to ResponseFieldMappers.MAPPERS

@martinbonnin @digitalbuddha is it works for you?

**Comment by martinbonnin** [comment]
:+1:  Works for me

**Comment by digitalbuddha** [comment]
Me too! Great idea

**Comment by chrisvis** [comment]
The generated `ResponseFieldMappers` class seems not to be put in the correct package, unlike the other generated files, therefore I am not able to use it

**Comment by martinbonnin** [comment]
Ahah, I just made the same comment in the PR thread: https://github.com/apollographql/apollo-android/pull/202

**Comment by martinbonnin** [comment]
And while I'm at it, the fragments are generated in the `fragment` package, which is a bit strange, would be nice to be able to put them in com.example.apollo or whatever same package as the rest of the generated classes.

**Comment by chrisvis** [comment]
I had this patch as a solution, but its not very elegant since it just uses the file path of the first found operation as the package name:

```diff
diff --git a/apollo-compiler/src/main/kotlin/com/apollographql/android/compiler/GraphQLCompiler.kt b/apollo-compiler/src/main/kotlin/com/apollographql/android/compiler/GraphQLCompiler.kt
index e5fd66c..fd49f9c 100644
--- a/apollo-compiler/src/main/kotlin/com/apollographql/android/compiler/GraphQLCompiler.kt
+++ b/apollo-compiler/src/main/kotlin/com/apollographql/android/compiler/GraphQLCompiler.kt
@@ -61,8 +61,9 @@ open class GraphQLCompiler {
         }

     if (!context.abstractType) {
+      val packageName = operations.first().filePath.formatPackageName();
       val typeSpec = ResponseFieldMappersTypeBuilder(operationJavaClasses).build()
-      JavaFile.builder(irPackageName, typeSpec).build().writeTo(outputDir)
+      JavaFile.builder(packageName, typeSpec).build().writeTo(outputDir)
     }
   }
```

**Comment by martinbonnin** [comment]
This is all because the IR file is directly under the `graphql` directory. 

`formatPackageName` transforms 'src/main/graphql/com/example/fileName' to 'com.example', which is empty if there's no 'com/example'... So everything would be fine if the IR file were in a subdirectory. Not really sure what we want for an arborescence there...

https://github.com/sav007/apollo-android/blob/66e4e1e4c042bda2a24cdc1a23cb2de2721004d3/apollo-compiler/src/main/kotlin/com/apollographql/android/compiler/GraphQLCompiler.kt#L69

**Comment by martinbonnin** [comment]
Also, I would be happy to enforce all operations to be in the same directory, I don't see a use case to have subdirectories but maybe I'm missing something. In my case, I even have all the operations in the same file :-D

**Comment by martinbonnin** [comment]
For the record, and to reflect the slack discussion, everything works fine if you put your schema.json file next to your .graphql files

**Comment by chrisvis** [comment]
Thanks, putting the file there works for me! Maybe it should be changed there in the example app as well.

**Comment by sav007** [comment]
@chrisvis @martinbonnin Here is the logic:

1. Package for operation (query) defined by the relative path of graphql file from `../graphql/..` folder. So if *.graphql file path is  `/Projects/apollostack/apollo-android/apollo-sample/src/main/graphql/com/example/GithuntFeedQuery.graphql` the package will be `com.example` for GithuntFeedQuery.java

2. Pckage for type that can be used across different queries (fragments, enum types etc.) defined by the the relative path of schema file from `../graphql/..` folder + suffix `fragment` or `type`.
So for fragments if schema file is under `/Projects/apollostack/apollo-android/apollo-sample/src/main/graphql/schema.json` the package will be `fragment`

But I see your point, `ResponseFieldMappers` is generated under relative path of schema file only (without any suffix). I will create issue to put `ResponseFieldMappers` to package define by file path to schema + `mapping` suffix.
