### ISSUE TITLE
Unknown type "Upload" 

### ISSUE THREAD

**Issue by knixer** [apollographql/apollo-android#1984]
I get the error 'Unknown type "Upload"' when I try to create a mutation with the Upload type in Android. 
I have added this to my app gradle build file:
```
apollo {
    customTypeMapping = [
            "Upload" : "com.apollographql.apollo.api.FileUpload"
    ]
}
```

In my schema.json file that I extracted from the server I found this text related to Upload:
```
{
        "kind": "SCALAR",
        "name": "Upload",
        "description": "The `Upload` scalar type represents a file upload promise that resolves an object containing `stream`, `filename`, `mimetype` and `encoding`.",
        "fields": null,
        "inputFields": null,
        "interfaces": null,
        "enumValues": null,
        "possibleTypes": null
      }
```
In my schema.graphql-file on the server I have added "scalar Upload". And I use the typeDefs option when creating an the Apollo server. 

Still, I get an error when trying to add the type within a mutation.

I have been able to send a file to the server through Altair: 
https://github.com/prisma-labs/graphql-playground/issues/597#issuecomment-492585110
So I know that things work on the server.

What am I missing here for the Android app?

PS I didn't know if I should have created a new issue or commented on this closed issue: https://github.com/apollographql/apollo-android/issues/1738

**Comment by sav007** [comment]
Is this error comes during project compilation? Or it's comming from the server?

**Comment by knixer** [comment]
> Is this error comes during project compilation? Or it's comming from the server?

While creating my mutation in a .graphql file in android studio.  When I write "updateUser(...,$avatar: Upload)" the Upload text gets red and when I hover over it the message 'Unknown type "Upload"' appears.

**Comment by sav007** [comment]
What version of library are you currently using?

**Comment by knixer** [comment]
> What version of library are you currently using?

I implement this in app build gradle: com.apollographql.apollo:apollo-runtime:1.0.2

**Comment by knixer** [comment]
I tend to get a lot of errors in my .graphql-files but they execute anyway. I submit a visual example
<img width="844" alt="githubExampleGraphqlCalls" src="https://user-images.githubusercontent.com/16081341/74282530-9908bb80-4d20-11ea-883c-3c6cc18f219b.png">

When I do a mutation with the graphql-file that uses the "Upload" scalar I get the error:  `
W/System.err: com.apollographql.apollo.exception.ApolloNetworkException: Failed to execute http call
W/System.err: Caused by: java.io.FileNotFoundException: content:/media/external/file/74/ORIGINAL/NONE/253392188 (No such file or directory)`
This error is however due to the fact that I try to use a photo taken with the camera in my mutation. And the photo is not found even if it is the right path.

**Comment by sav007** [comment]
1.0.2 is kind old version, is it possible for you to migrate to latest version 1.3.1?

**Comment by knixer** [comment]
> 1.0.2 is kind old version, is it possible for you to migrate to latest version 1.3.1?

Yes, I did that now and I still have the same result. 

<img width="667" alt="UpdatedToApollo131" src="https://user-images.githubusercontent.com/16081341/74314495-cd5a9700-4d75-11ea-9e78-9e9ddfb40198.png">

**Comment by sav007** [comment]
sorry, but you are showing the raw GraphQL query. I'm not really sure what Android Studio plugin are you using to get GraphQL syntax support. Apollo doesn't provide any IDE plugin.

**Comment by knixer** [comment]
> sorry, but you are showing the raw GraphQL query. I'm not really sure what Android Studio plugin are you using to get GraphQL syntax support. Apollo doesn't provide any IDE plugin.

Yes, I just wanted to clarify what I meant. Is there anything you want to know? I updated to the latest version:   com.apollographql.apollo:apollo-runtime:1.3.1

**Comment by knixer** [comment]
> sorry, but you are showing the raw GraphQL query. I'm not really sure what Android Studio plugin are you using to get GraphQL syntax support. Apollo doesn't provide any IDE plugin.

I use the one that you wanted me to migrate to. 'com.apollographql.apollo:apollo-gradle-plugin:1.3.1'

**Comment by knixer** [comment]
My solution:
In Android Studio click on the "GraphQL" bar at the bottom. 
When you hover over the Endpoint-error it tells you to click on the + sign and to add and configure the .graphqlconfig-file. 
In the file, I changed the "Default GraphQL Endpoint" value to the right URL. 

I will close this issue
