### ISSUE TITLE
Retrying failed requests with Flow.retry 

### ISSUE THREAD

**Issue by ifeomaro** [apollographql/apollo-android#1986]
Hello 👋 .

I have a request that needs to be retried when there's a failure:

```kotlin
apolloClient
    .query(MyAwesomeQuery())
    .toFlow()
    .retry(retries = MAX_RETRY_COUNT)
    .flowOn(dispatcher)
```

However, retrying the request results in an `IllegalStateException "Already Executed"` error from `Retrofit` which is [expected](https://stackoverflow.com/a/35094488/2688283) since a `Retrofit` call can only be executed once. When I add `clone()` to the request, I still get the same error.

```kotlin
apolloClient
    .query(MyAwesomeQuery())
    .clone()
    .toFlow()
    .retry(retries = MAX_RETRY_COUNT)
    .flowOn(dispatcher)
```

What is the expected behavior for `ApolloQueryCall.clone()`?

I'm not able to add a label, but this is a question.

**Comment by sav007** [comment]
Looks like we need to do `ApolloCall.clone` inside the flow creation:
```
fun <T> ApolloCall<T>.toFlow(capacity: Int = Channel.UNLIMITED) = flow {
...
clone().enqueue(ChannelCallback(channel = channel))
```

**Comment by sav007** [comment]
I will take this issue.
