### ISSUE TITLE
com.apollographql.apollo.exception.ApolloNetworkException: Failed to execute http call

### ISSUE THREAD

**Issue by knixer** [apollographql/apollo-android#1988]
Here are parts of the error message:
```
W/System.err: com.apollographql.apollo.exception.ApolloNetworkException: Failed to execute http call
W/System.err:     at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onFailure(ApolloServerInterceptor.java:120)

W/System.err: Caused by: java.io.FileNotFoundException: content:/media/external/file/74/ORIGINAL/NONE/253392188 (No such file or directory
W/System.err:     at java.io.FileInputStream.open(Native Method)
W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:146)

```

Below is the code that makes the error. ImageUri is of type Uri and is received from the user when selecting a photo on the phone.

```
var avatar: FileUpload? = null;

        ImageUri?.let{

            val fileUri = ImageUri.path.toString().split("/-1/1/")[1]
            avatar = FileUpload("jpeg", File(fileUri))

        }

        val updateUser = UpdateUserMutation.builder()
                .email(email)
                .name(username)
                .avatar(avatar)
                .build()

        AS.apolloClient.mutate(updateUser).enqueue(object: ApolloCall.Callback<UpdateUserMutation.Data>(){
            override fun onFailure(e: ApolloException) {...}
```
I'm doing something wrong when handling the path to the photo. Does somebody have a clue?

**Comment by sav007** [comment]
Something wrong with the file `fileUri` you provided to upload and apollo can't get access to it:
`Caused by: java.io.FileNotFoundException: content:/media/external/file/74/ORIGINAL/NONE/253392188 (No such file or directory`

**Comment by knixer** [comment]
> Something wrong with the file `fileUri` you provided to upload and apollo can't get access to it:
> `Caused by: java.io.FileNotFoundException: 

Yes, one needs to get the real absolute path somehow. I manage to solve this by using this in kotlin:

`fun getPath(uri: Uri): String? {
        var projection = arrayOf(MediaStore.Images.Media.DATA);
        var loader = CursorLoader(this, uri, projection, null, null, null);
        var cursor = loader.loadInBackground();
        val column_index = cursor?.getColumnIndexOrThrow(MediaStore.Images.Media.DATA);
        cursor?.moveToFirst();
        return cursor?.getString(column_index!!);
    }`

it is inspired by this answer: https://stackoverflow.com/a/7726604 .

**Comment by knixer** [comment]
Yes, one needs to get the real absolute path somehow. I manage to solve this by using this in kotlin:

```
    fun getPath(uri: Uri): String? {
        var projection = arrayOf(MediaStore.Images.Media.DATA);
        var loader = CursorLoader(this, uri, projection, null, null, null);
        var cursor = loader.loadInBackground();
        val column_index = cursor?.getColumnIndexOrThrow(MediaStore.Images.Media.DATA);
        cursor?.moveToFirst();
        return cursor?.getString(column_index!!);
    }
```

it is inspired by this answer: https://stackoverflow.com/a/7726604 .

I will now close this issue.
