### ISSUE TITLE
AWS AppSync rejects subscription websocket upgrade request from ApolloClient

### ISSUE THREAD

**Issue by simonmarshall** [apollographql/apollo-android#1992]
**Summary**
AWS AppSync rejects our subscription request from ApolloClient when it tries to upgrade its connection to a websocket.

**Description**
After successfully creating a connection to AWS AppSync via its OkHttpClient, the ApolloClient tries to upgrade its connection to a websocket.  AWS AppSync rejects the request with a 400 Bad Request.

**Version**
com.apollographql.apollo:apollo-runtime:1.3.1

We’re using the ApolloClient (see https://www.apollographql.com/) from a Java service (using apollo-android aka com.apollographql.apollo:apollo-runtime:1.3.1) to access our AWS AppSync/GraphQL endpoint.  This works fine for queries and mutations, and I can get data from AWS AppSync without any issue.  However, for subscriptions, AWS AppSync rejects the websocket upgrade request, and I cannot figure out why.  It’s not a network issue, at least not on our side, as the request is making it through to AWS.  I'm using the same (sanitised) endpoint for queries, mutations and subscriptions: api-pseudo-host.appsync-api.us-east-1.amazonaws.com/graphql

The schema has the following (sanitised) types:
```
type Mutation {
	create(input: CreateInput!): Result
}

type Subscription {
	onCreate(
		a: String,
		b: String,
		c: String,
		d: String,
		e: String
	): Result
		@aws_subscribe(mutations: ["create"])
}
```
We're creating the connection like this:
```
	OkHttpClient okHttpClient = new OkHttpClient.Builder()
			.proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("our-proxy.com", 80)))
			.addInterceptor(chain -> chain.proceed(chain.request().newBuilder().header("x-api-key", "***").build()))
			.build();
	ApolloClient client = ApolloClient.builder()
			.serverUrl("https://api-pseudo-host.appsync-api.us-east-1.amazonaws.com/graphql")
			.okHttpClient(okHttpClient)
			.subscriptionTransportFactory(new WebSocketSubscriptionTransport.Factory( "wss://api-pseudo-host.appsync-api.us-east-1.amazonaws.com/graphql", okHttpClient))
			.build();
```
(Normally I would use `authenticator()` - I use `addInterceptor()` here for debugging purposes so there is only one REST call for the authentication to succeed.)

Looking at CloudWatch, I see the following (sanitised) entries when I do the subscription for an instance of the OnCreateSubscription Java class (compiled from the above script) via the ApolloClient:
```
d42b3a5a-94d7-4665-8dd4-876fc5e0c20c Begin Request
d42b3a5a-94d7-4665-8dd4-876fc5e0c20c Invalid Get Request: Query: null, Operation: null, Variables: null
{"logType":"RequestSummary","requestId":"d42b3a5a-94d7-4665-8dd4-876fc5e0c20c","graphQLAPIId":"3eyxmgqpjzedbimhfcgmo4qqvq","statusCode":400,"latency":11000000}
d42b3a5a-94d7-4665-8dd4-876fc5e0c20c Request Headers: {x-amzn-ErrorType=[MalformedHttpRequestException]}
d42b3a5a-94d7-4665-8dd4-876fc5e0c20c Response Headers: {sec-websocket-protocol=graphql-ws, cloudfront-viewer-country=US, x-forwarded-proto=https, upgrade=websocket, x-forwarded-port=443, x-forwarded-for=192.175.226.14, 70.132.33.79, sec-websocket-version=13, via=1.1 7dc4818c830423900ae855831181d2b8.cloudfront.net (CloudFront), cloudfront-is-smarttv-viewer=false, x-amzn-trace-id=Root=1-5e440443-b6b681ce52ff916ebf30857a, cloudfront-is-desktop-viewer=true, cloudfront-is-tablet-viewer=false, x-api-key=***, host=api-pseudo-host.appsync-api.us-east-1.amazonaws.com, connection=upgrade, sec-websocket-key=UngxCvE4y/03UkuvI4+s4Q==, cloudfront-forwarded-proto=https, x-amz-cf-id=FrXlzc16M2aSP-c6bBm01-j9n99k_X_kM0aTh_DcCE99i4uhGOz36w==, accept-encoding=gzip, user-agent=okhttp/3.12.2, cloudfront-is-mobile-viewer=false}
d42b3a5a-94d7-4665-8dd4-876fc5e0c20c End Request
```

I'm not sure what to make of the "Invalid Get Request: Query: null, Operation: null, Variables: null" entry.  Should one of them be non-null for a subscription?  The way I read the response headers, it is the response to the websocket upgrade request, which I would not expect to contain, eg, a query.

I don't create the request directly; the ApolloClient+OkHttpClient handles that.  Debugging the upgrade request, I can see the request has the following (sanitised) properties:
```
url=https://api-pseudo-host.appsync-api.us-east-1.amazonaws.com/graphql
method=GET
body=null
headers=Sec-WebSocket-Protocol: graphql-ws
  Cookie: 
  Upgrade: websocket
  Connection: Upgrade
  Sec-WebSocket-Key: UngxCvE4y/03UkuvI4+s4Q==
  Sec-WebSocket-Version: 13
  x-api-key: ***
  Host: api-pseudo-host.appsync-api.us-east-1.amazonaws.com
  Accept-Encoding: gzip
  User-Agent: okhttp/3.12.2
```
This is what I would expect of the upgrade request.  The response has the following (sanitised) properties:
```protocol=http/1.1
code=400
message=Bad Request
url=https://api-pseudo-host.appsync-api.us-east-1.amazonaws.com/graphql
body=null
headers=Content-Type: application/json;charset=UTF-8
  Content-Length: 135
  Connection: close
  Date: Wed, 12 Feb 2020 13:57:23 GMT
  x-amzn-RequestId: d42b3a5a-94d7-4665-8dd4-876fc5e0c20c
  x-amzn-ErrorType: MalformedHttpRequestException
  X-Cache: Error from cloudfront
  Via: 1.1 7dc4818c830423900ae855831181d2b8.cloudfront.net (CloudFront)
  X-Amz-Cf-Pop: IAD89-C1
  X-Amz-Cf-Id: FrXlzc16M2aSP-c6bBm01-j9n99k_X_kM0aTh_DcCE99i4uhGOz36w==
```
So my question is: what is wrong with the websocket upgrade request that leads AWS to reject it?

**Comment by sav007** [comment]
Not really sure how to help you here. 
From looking into the response from AWS:
`x-amzn-ErrorType: MalformedHttpRequestException`

Is there any documentation regarding the AWS AppSync? Double check that url is right.

**Comment by simonmarshall** [comment]
hi @sav007 - yes, you're right, the url is different: subscription urls use `appsync-realtime-api`, rather than `appsync-api`.  with that change, i can get the connection to succeed, though subscription events are not actually coming through.  i'll have to dig in to see why that is...

**Comment by kodehash** [comment]
Hi @simonmarshall , How did you get the appsync-realtime-api ? The AWS console only has one Api . Any help here would be appreciated.

**Comment by ko-deloitte** [comment]
With the latest upgrade tried setting up and running appsync subscriptions with apollo client - https://github.com/kodehash/appsync-nodejs-apollo-client/tree/master
