### ISSUE TITLE
how to handle "com.apollographql.apollo.exception.ApolloHttpException: HTTP 503" 

### ISSUE THREAD

**Issue by nkollu** [apollographql/apollo-android#1995]
**Summary**
how to handle com.apollographql.apollo.exception.ApolloHttpException: HTTP 503

io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | com.apollographql.apollo.exception.ApolloHttpException: HTTP 503 

**Description**
This is the client 
  private fun createClient(storeAuth: StoreAuth): ApolloClient {
        val httpLoggingInterceptor = HttpLoggingInterceptor()
        httpLoggingInterceptor.level = HttpLoggingInterceptor.Level.BODY

        val baseUrl = BuildConfig.GRAPHQL_URL 

        val okHttpClient = UnsafeOkHttpClient.getUnsafeOkHttpClient(storeAuth)

        return ApolloClient.builder()
                .serverUrl(baseUrl)
                .okHttpClient(okHttpClient)
                .addCustomTypeAdapter(CustomType.DATE, customAdapterForDate)
                .addCustomTypeAdapter(CustomType.DATETIME, customAdapterDateTime)
                .build()
    }

**Version**
Latest version

**Comment by sav007** [comment]
Can you show me please how you create query Apollo call?

**Comment by nkollu** [comment]
graphql -->

mutation login ($email: String!,$password: String!){
    logIn(email:$email, password:$password){
        token
    }
}


    fun authentication(email: String, password: String): Observable<Response<LoginMutation.Data>>   

  @SuppressLint("CheckResult")
    override fun authentication(login: String, password: String): Observable<Response<LoginMutation.Data>> {
        apiClientProvider.invalidate()
        val authMutation = apiClientProvider.getApiClient()
                .mutate(LoginMutation(login, password))
        return apolloRxHelper
                .from(authMutation)
    }

in Viewmodel
  @SuppressLint("CheckResult")
    fun loginAuth(login: String, password: String): MutableLiveData<Resource<LoginMutation.Data>> {

        val loginResource = MutableLiveData<Resource<LoginMutation.Data>>()
        loginRepository
                .authentication(login, password)
                .subscribeOn(rxSchedulers.io())
                .observeOn(rxSchedulers.androidMainThread())
                .doOnSubscribe { loginResource.postValue(Resource.loading<LoginMutation.Data>(null)) }
                .doOnNext { handleSucessResponse(it, loginResource) }
                .doOnError { error ->
                    loginResource.postValue(Resource.error<LoginMutation.Data>(error))
                }
                .subscribe()

        return loginResource
    }

in Activity
this.viewModel!!.loginAuth(input_email.text.toString(), input_password.text.toString()).observe(this, Observer { processLogin(it!!)

**Comment by sav007** [comment]
Please check the documentation of RxJava, you missing error handler in  `.subscribe()` operator call.
http://reactivex.io/documentation/operators/subscribe.html
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L12197
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L12133-L12135
