### ISSUE TITLE
Job Cancellation Exception

### ISSUE THREAD

**Issue by msya** [apollographql/apollo-android#2005]
**Summary**

I am getting a `kotlinx.coroutines.JobCancellationException: Job was cancelled; job=StandaloneCoroutine{Cancelled}` exception when I use the `toFlow` method on the Apollo client.

**Description**

This repo https://github.com/msya/ApolloAndroidPlayground has an example app that shows the problem. I have a repo that creates an Apollo client and uses the `toFlow` extension to get the Flow. 

```
class Repo {

    fun getData(): Flow<Response<TestQuery.Data>> {
        val client = ApolloClient.builder().serverUrl("https://api.kivaws.org/graphql").build()
        return client.query(TestQuery.builder().build()).toFlow()
    }
}
```

I also have a ViewModel that launch a coroutines in the view model scope. In this coroutine, I am collecting from the Flow. 

```
class MyViewModel: ViewModel() {

    private val repo = Repo()

    val scope = CoroutineScope(Dispatchers.Main)

    fun getData() {
        scope.launch {
            repo.getData()
                .collect {
                    println(it)
                }
        }
    }

    fun cancel() {
        scope.cancel()
    }

}
```

However, if I call cancel on the Job returned by the coroutine. I am getting the cancellation exception - `kotlinx.coroutines.JobCancellationException: Job was cancelled; job=StandaloneCoroutine{Cancelled}`. In the activity below, I am canceling the call explicitly on a button click.

```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val model: MyViewModel by viewModels()

        make_request?.setOnClickListener {
            model.getData()
        }

        cancel?.setOnClickListener {
            model.cancel()
        }

    }
}
```

I suspect this problem is due to the clone method in the `callbackFlow` in the `toFlow` extension. If you remove the clone method, the exception does not occur. 

**Version**
1.3.2

**Comment by martinbonnin** [comment]
For some context, the `clone` was added to address this bug: https://github.com/apollographql/apollo-android/issues/1986

**Comment by diegocunhawarren** [comment]
Hey @martinbonnin, looking the changes regarding this issue, the class `ApolloSubscriptionCall` has the same issue about emit when the channel is closed, I created a custom extension like yours and just fixed to me!

**Comment by CureleaAndrei** [comment]
Hi, found the same issue in ApolloCall<>.await(). I think there should be a scope.isActive check. What do you think ?

**Comment by martinbonnin** [comment]
@CureleaAndrei can you share your apollo version and the stacktrace?

**Comment by basithp** [comment]
@CureleaAndrei Facing the same issue on `ApolloCall<>.await()`. was it fixed. I am using the version "2.5.9"
