### ISSUE TITLE
Minor annoyance: "Cannot resolve symbol 'OperationIdGenerator'" but compile correctly

### ISSUE THREAD

**Issue by louistsaitszho** [apollographql/apollo-android#2008]
**Summary**
<img width="680" alt="Screen Shot 2020-02-21 at 11 38 28" src="https://user-images.githubusercontent.com/3873011/75027364-bff08b80-549e-11ea-9370-a0d215e8cb8e.png">

**It compiles**, but kinda annoying

**Description**
In Android Studio, `OperationIdGenerator` is always red, but it compiles correctly. Not sure if it is a Android Studio problem, or apollo problem (maybe needs to `api` instead of `implementation` compiler in the gradle plugin?)

**Version**
Apollo 1.3.2
Android Studio 3.5.3

**Comment by martinbonnin** [comment]
> maybe needs to api instead of implementation compiler in the gradle plugin

That sounds like it. Do you mind opening a PR ?
