### ISSUE TITLE
custom JSON scalar types loses quotes after decoding

### ISSUE THREAD

**Issue by Thecrazyskull** [apollographql/apollo-android#2012]
**Summary**
The server uses custom JSON scalar types for certain objects. Since it's a JSON, the quotes around the keys & values should persist but with apollo 1.3.0 they don't.

**Description**
With the upgrade to Apollo 1.3.0, the JSON object loses its quotes around the keys & values, making the JSON validation/parsing fail if one of the values (or keys) contains a space. This was not the case with Apollo 1.2.0. To give a clear view of the problem, here is the code (same for Apollo 1.2.0 and 1.3.0) for decoding:

    override fun decode(value: CustomTypeValue<*>): JSONObject {
        android.util.Log.e("TEST", "value=${value.value}")
        return JSONObject(value.value.toString())
    }

With Apollo 1.2.0, this was the output of the log statement:

`value={"follow_accept_notification":true,"event_invite_notification":true,"user_discovery_match_notification":false,"event_announce_notification":true,"reservation_decline_notification":true,"follow_request_notification":true,"rating_request_notification":true,"event_invite_verify_request_notification":true,"reservation_accept_notification":true}`

With Apollo 1.3.0, this is the output of the log statement:

`value={follow_accept_notification=true,event_invite_notification=true, user_discovery_match_notification=false, event_announce_notification=true, reservation_decline_notification=true, follow_request_notification=true, rating_request_notification=true, event_invite_verify_request_notification=true, reservation_accept_notification=true}` 

I'm not sure if I'm doing something wrong or if this is a bug. Either way I would really appreciate any help. For the time being I have downgraded my project back to Apollo 1.2.0.

**Version**
Apollo version 1.3.0

**Comment by sav007** [comment]
Well, I guess that you get `com.apollographql.apollo.api.CustomTypeValue.GraphQLJsonObject` as an argument in `decode(value: CustomTypeValue<*>)` function and if you look at what is `value` for `CustomTypeValue.GraphQLJsonObject#value` you will find that it's plain `Map`. 

Obviously by calling `Map.toString` you get what you see in the logs.

**Comment by AgneseBussone** [comment]
Hello,
I'm having a similar issue with a custom Json type and probably it's related to the same problem.

In the main brach everything is working as expected: I have the custom json type mapped as
`apollo {
    customTypeMapping = [
            "MyData" : "java.lang.String"
    ]
}`
then in the code I just take the string and create a json obj from it
`            JSONObject document = new JSONObject(documentStr);
`
I don't have any custom type adapter set for it and the string contains the `"` char. Apollo version is `1.0.1`

In the feature branch I've updated the apollo version to `1.3.2` following the migration guide. I'm doing the very same operations, but now the string returned by apollo doesn't contain any `"`.
I've noticed that in the generated class there are these methods
```
  @Override
  @NotNull
  public Response<MyQuery.Data> parse(@NotNull final BufferedSource source,
      @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
    return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
  }

  @Override
  @NotNull
  public Response<MyQuery.Data> parse(@NotNull final BufferedSource source) throws
      IOException {
    return parse(source, ScalarTypeAdapters.DEFAULT);
  }
```
that are not present in the generated class for the main branch.
Am I missing something due to the migration?

**Comment by sav007** [comment]
Merged.

**Comment by anup1245** [comment]
Hi,
Im still facing this issue on 2.2.0

private CustomTypeAdapter<LinkedTreeMap> dataMapTypeAdapter = new CustomTypeAdapter<LinkedTreeMap>() {

        @Override
        public LinkedTreeMap decode(@NotNull CustomTypeValue value) {
            return new Gson().fromJson(value.value.toString(), LinkedTreeMap.class);
        }

        @Nonnull
        @Override
        public CustomTypeValue encode(@Nonnull LinkedTreeMap value) {
            return new CustomTypeValue.GraphQLString(new Gson().toJsonTree(value).getAsJsonObject().toString());
        }
    };

value is of type LinkedHashMap and after converting to string it comes as {test=value}
