### ISSUE TITLE
Remove synthetic accessors from generated Kotlin code

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-android#2018]
**Is your feature request related to a problem? Please describe.**
I am turning on lint on my project for the first time, and it's warning about access to`RESPONSE_FIELDS` requiring a synthetic accessor.  Given how repetitive json parsing is, this seems like it might actually be a good performance win to fix.
<img width="824" alt="Screen Shot 2020-02-25 at 4 58 27 PM" src="https://user-images.githubusercontent.com/1063557/75291497-55b64e80-57f0-11ea-8e25-e23fb13b6eeb.png">

**Describe the solution you'd like**
No synthetic accessor requirement.  Not 100% the best way to achieve that or I'd PR it myself.

**Comment by edenman** [comment]
This is probably not a huge deal, sounds like R8 gets rid of most/all of these at least in Dagger's case: https://github.com/google/dagger/issues/635

**Comment by tasomaniac** [comment]
The solution that this lint check requires is actually to remove `private` modifier. In the generated code, we definitely wouldn't want to do that since it would expose those. Closing this for now. I would recommend disabling this check for generated code.
