### ISSUE TITLE
kotlinx.coroutines.flow.internal.AbortFlowException: Flow was aborted, no more elements needed

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-android#2020]
**Summary**
Race condition-y bug afaict.  Not 100% reproducible, but sometimes when using `ApolloCall.toFlow()` I see this crash.  There's no stacktrace which is bonkers.
```
         AndroidRuntime  E  FATAL EXCEPTION: Apollo Dispatcher
                         E  Process: com.myapp.app.debug, PID: 3313
                         E  kotlinx.coroutines.flow.internal.AbortFlowException: Flow was aborted, no more elements needed
```

Based on my very novice understanding, the issue is likely that toFlow's `onResponse` callback is calling `offer` even after the Flow has been cancelled/closed.

**Version**
coroutines 1.3.3
apollo 1.3.2

**Comment by edenman** [comment]
I'm gonna try changing to this:
```
        if (!isClosedForSend) {
          offer(response)
        }
```
I still haven't been able to get the apollo dev environment working or I'd try to write a failing test and put this in as a fix.

**Comment by martinbonnin** [comment]
Can you try the snapshots ? This was hopefully fixed in https://github.com/apollographql/apollo-android/pull/2007.

**Comment by martinbonnin** [comment]
Should be fixed in the latest [Apollo Android 3 version](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-rc01)
