### ISSUE TITLE
How to cancel current request

### ISSUE THREAD

**Issue by fairlyNguyen** [apollographql/apollo-android#2034]
**Is your feature request related to a problem? Please describe.**
I apply viewpager and when the user open a detail view, I call a request. But at this time I swipe to the next view and it call new one request. I want to cancel first request to save performance.

**Describe the solution you'd like**
Hi,
I want to cancel the current (1) request when I call the new one (2) request (The request 2 is the same as request 1)

How I init apollo client
`apolloClient = ApolloClient.builder() .serverUrl(baseUrl + "graphql" + Constants.SLASH + requestType) .okHttpClient(okHttpClient) .addCustomTypeAdapter(CustomType.JSON, customTypeAdapter) .httpCache(new ApolloHttpCache(cacheStore)) .build();`

**Comment by fairlyNguyen** [comment]
@sav007 ,
Could you explain more? I can't find cancel method on this.

![Screenshot from 2020-03-06 12-29-11](https://user-images.githubusercontent.com/17351016/76055422-306ed080-5fa6-11ea-81c3-81b1368ce7d0.png)

**Comment by sav007** [comment]
https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/ApolloCall.java#L25

https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/util/Cancelable.java

**Comment by fairlyNguyen** [comment]
Thank you for point it out!

**Comment by fairlyNguyen** [comment]
I try to cancel old requests but still get a response. May cancel not work.

**Comment by fairlyNguyen** [comment]
@sav007 
How I request:
      ```
getStoryQuery = GetStoryQuery.builder()
                .id(articlesID).build();
       apolloClient.query(getStoryQuery)
                .httpCachePolicy(HttpCachePolicy.NETWORK_FIRST).enqueue(callback);
```
How I cancel:
     ` apolloClient.query(getStoryQuery).cancel();`
It still can't cancel request
