### ISSUE TITLE
Reopen: Android Apollo (GraphQL) autogeneration issue with Kotlin #1953

### ISSUE THREAD

**Issue by sneronovAdviqo** [apollographql/apollo-android#2035]
The ticket #1953 was closed with notes that fix will be in version 1.3.1, but bug is still there even in version 1.3.2.
Please take a look to [Android Apollo (GraphQL) autogeneration issue with Kotlin #1953](https://github.com/apollographql/apollo-android/issues/1953)

**Comment by sneronovAdviqo** [comment]
the error is the same that I had when I created the issue ticket

**Comment by sav007** [comment]
Is it possible to take a look at your code generate class  where this error is reproduced?

**Comment by sneronovAdviqo** [comment]
`// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.adviqo.shared.app

import com.adviqo.shared.app.type.CustomType
import com.apollographql.apollo.api.Input
import com.apollographql.apollo.api.InputFieldMarshaller
import com.apollographql.apollo.api.InputFieldWriter
import com.apollographql.apollo.api.Operation
import com.apollographql.apollo.api.OperationName
import com.apollographql.apollo.api.Query
import com.apollographql.apollo.api.Response
import com.apollographql.apollo.api.ResponseField
import com.apollographql.apollo.api.ResponseFieldMapper
import com.apollographql.apollo.api.ResponseFieldMarshaller
import com.apollographql.apollo.api.ResponseReader
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser
import com.apollographql.apollo.internal.QueryDocumentMinifier
import com.apollographql.apollo.response.ScalarTypeAdapters
import com.apollographql.apollo.response.ScalarTypeAdapters.DEFAULT
import java.io.IOException
import kotlin.Any
import kotlin.Array
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.jvm.Throws
import kotlin.jvm.Transient
import okio.BufferedSource

@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter")
data class MembersQuery(
  val mandatorNo: Int,
  val memberNoFilter: Input<List<Int?>> = Input.absent(),
  val memberId: Input<String> = Input.absent(),
  val page: Int,
  val size: Input<Int> = Input.absent()
) : Query<MembersQuery.Data, MembersQuery.Data, Operation.Variables> {
  @Transient
  private val variables: Operation.Variables = object : Operation.Variables() {
    override fun valueMap(): Map<String, Any?> = mutableMapOf<String, Any?>().apply {
      this["mandatorNo"] = mandatorNo
      if (memberNoFilter.defined) this["memberNoFilter"] = memberNoFilter.value
      if (memberId.defined) this["memberId"] = memberId.value
      this["page"] = page
      if (size.defined) this["size"] = size.value
    }

    override fun marshaller(): InputFieldMarshaller = InputFieldMarshaller { writer ->
      writer.writeInt("mandatorNo", mandatorNo)
      if (memberNoFilter.defined) {
        writer.writeList("memberNoFilter", memberNoFilter.value?.let { value ->
          InputFieldWriter.ListWriter { listItemWriter ->
            value.forEach { value ->
              listItemWriter.writeInt(value)
            }
          }
        })
      }
      if (memberId.defined) writer.writeString("memberId", memberId.value)
      writer.writeInt("page", page)
      if (size.defined) writer.writeInt("size", size.value)
    }
  }

  override fun operationId(): String = OPERATION_ID
  override fun queryDocument(): String = QUERY_DOCUMENT
  override fun wrapData(data: Data?): Data? = data
  override fun variables(): Operation.Variables = variables
  override fun name(): OperationName = OPERATION_NAME
  override fun responseFieldMapper(): ResponseFieldMapper<Data> = ResponseFieldMapper {
    Data(it)
  }

  @Throws(IOException::class)
  override fun parse(source: BufferedSource, scalarTypeAdapters: ScalarTypeAdapters): Response<Data>
      = SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters)

  @Throws(IOException::class)
  override fun parse(source: BufferedSource): Response<Data> = parse(source, DEFAULT)

  data class Member(
    val __typename: String,
    val memberNo: String,
    val mandatorNo: Int?,
    val firstName: String?,
    val lastName: String?,
    val memberId: String?,
    val memberIdView: String?,
    val email: String?,
    val memberTypeNo: Int?,
    val country: String?,
    val birthdate: String?,
    val gender: String?,
    val language: String?,
    val expert: Boolean?
  ) {
    fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller {
      it.writeString(RESPONSE_FIELDS[0], __typename)
      it.writeCustom(RESPONSE_FIELDS[1] as ResponseField.CustomTypeField, memberNo)
      it.writeInt(RESPONSE_FIELDS[2], mandatorNo)
      it.writeString(RESPONSE_FIELDS[3], firstName)
      it.writeString(RESPONSE_FIELDS[4], lastName)
      it.writeString(RESPONSE_FIELDS[5], memberId)
      it.writeString(RESPONSE_FIELDS[6], memberIdView)
      it.writeString(RESPONSE_FIELDS[7], email)
      it.writeInt(RESPONSE_FIELDS[8], memberTypeNo)
      it.writeString(RESPONSE_FIELDS[9], country)
      it.writeString(RESPONSE_FIELDS[10], birthdate)
      it.writeString(RESPONSE_FIELDS[11], gender)
      it.writeString(RESPONSE_FIELDS[12], language)
      it.writeBoolean(RESPONSE_FIELDS[13], expert)
    }

    companion object {
      private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.forString("__typename", "__typename", null, false, null),
          ResponseField.forCustomType("memberNo", "memberNo", null, false, CustomType.ID, null),
          ResponseField.forInt("mandatorNo", "mandatorNo", null, true, null),
          ResponseField.forString("firstName", "firstName", null, true, null),
          ResponseField.forString("lastName", "lastName", null, true, null),
          ResponseField.forString("memberId", "memberId", null, true, null),
          ResponseField.forString("memberIdView", "memberIdView", null, true, null),
          ResponseField.forString("email", "email", null, true, null),
          ResponseField.forInt("memberTypeNo", "memberTypeNo", null, true, null),
          ResponseField.forString("country", "country", null, true, null),
          ResponseField.forString("birthdate", "birthdate", null, true, null),
          ResponseField.forString("gender", "gender", null, true, null),
          ResponseField.forString("language", "language", null, true, null),
          ResponseField.forBoolean("expert", "expert", null, true, null)
          )

      operator fun invoke(reader: ResponseReader): Member {
        val __typename = reader.readString(RESPONSE_FIELDS[0])
        val memberNo = reader.readCustomType<String>(RESPONSE_FIELDS[1] as
            ResponseField.CustomTypeField)
        val mandatorNo = reader.readInt(RESPONSE_FIELDS[2])
        val firstName = reader.readString(RESPONSE_FIELDS[3])
        val lastName = reader.readString(RESPONSE_FIELDS[4])
        val memberId = reader.readString(RESPONSE_FIELDS[5])
        val memberIdView = reader.readString(RESPONSE_FIELDS[6])
        val email = reader.readString(RESPONSE_FIELDS[7])
        val memberTypeNo = reader.readInt(RESPONSE_FIELDS[8])
        val country = reader.readString(RESPONSE_FIELDS[9])
        val birthdate = reader.readString(RESPONSE_FIELDS[10])
        val gender = reader.readString(RESPONSE_FIELDS[11])
        val language = reader.readString(RESPONSE_FIELDS[12])
        val expert = reader.readBoolean(RESPONSE_FIELDS[13])
        return Member(
          __typename = __typename,
          memberNo = memberNo,
          mandatorNo = mandatorNo,
          firstName = firstName,
          lastName = lastName,
          memberId = memberId,
          memberIdView = memberIdView,
          email = email,
          memberTypeNo = memberTypeNo,
          country = country,
          birthdate = birthdate,
          gender = gender,
          language = language,
          expert = expert
        )
      }
    }
  }

  data class Data(
    val members: List<Member?>?
  ) : Operation.Data {
    override fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller {
      it.writeList(RESPONSE_FIELDS[0], members) { value, listItemWriter ->
        value?.forEach { value ->
          listItemWriter.writeObject(value?.marshaller())
        }
      }
    }

    companion object {
      private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.forList("members", "members", mapOf<String, Any>(
            "mandatorNo" to mapOf<String, Any>(
              "kind" to "Variable",
              "variableName" to "mandatorNo"),
            "memberNoFilter" to mapOf<String, Any>(
              "kind" to "Variable",
              "variableName" to "memberNoFilter"),
            "memberId" to mapOf<String, Any>(
              "kind" to "Variable",
              "variableName" to "memberId"),
            "page" to mapOf<String, Any>(
              "kind" to "Variable",
              "variableName" to "page"),
            "size" to mapOf<String, Any>(
              "kind" to "Variable",
              "variableName" to "size")), true, null)
          )

      operator fun invoke(reader: ResponseReader): Data {
        val members = reader.readList<Member>(RESPONSE_FIELDS[0]) {
          it.readObject<Member> { reader ->
            Member(reader)
          }

        }
        return Data(
          members = members
        )
      }
    }
  }

  companion object {
    const val OPERATION_ID: String =
        "b3fee455a09363e89006252f651d2cf66e83aee4d8342b47ae9b6226cf9976ee"

    val QUERY_DOCUMENT: String = QueryDocumentMinifier.minify(
          """
          |query MembersQuery(${'$'}mandatorNo: Int!, ${'$'}memberNoFilter: [Int], ${'$'}memberId: String, ${'$'}page: Int!, ${'$'}size: Int) {
          |  members(mandatorNo: ${'$'}mandatorNo, memberNoFilter: ${'$'}memberNoFilter, memberId: ${'$'}memberId, page: ${'$'}page, size: ${'$'}size) {
          |    __typename
          |    memberNo
          |    mandatorNo
          |    firstName
          |    lastName
          |    memberId
          |    memberIdView
          |    email
          |    memberTypeNo
          |    country
          |    birthdate
          |    gender
          |    language
          |    expert
          |  }
          |}
          """.trimMargin()
        )

    val OPERATION_NAME: OperationName = OperationName { "MembersQuery" }
  }
}
`

**Comment by sneronovAdviqo** [comment]
![Screenshot 2020-03-10 at 11 26 27](https://user-images.githubusercontent.com/50866520/76303428-037e2e80-62c2-11ea-9ca2-26543eabc704.png)

**Comment by sneronovAdviqo** [comment]
The error is relevant for all versions, including the latest version 1.3.3

**Comment by sneronovAdviqo** [comment]
@sav007 , is there anything to say back to me?

**Comment by sav007** [comment]
Sorry for the delay, lost track of this issue.

Are you sure you using the latest version of the Apollo plugin? Asking because looking into the code you provided I can't find evidence that it's the latest version, for example this is how it should look like:
https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/input_object_type/TestQuery.kt#L41-L51

Notice bunch of `this@`

**Comment by sneronovAdviqo** [comment]
<img width="1668" alt="dependences" src="https://user-images.githubusercontent.com/50866520/77002300-93277b00-695b-11ea-8040-ca667e63d83c.png">
<img width="1670" alt="generated_file" src="https://user-images.githubusercontent.com/50866520/77002316-99b5f280-695b-11ea-9972-770a41c8e8f8.png">

**Comment by sneronovAdviqo** [comment]
I hope this is enough for an evidence. If you need some thing else, just tell what I have to provide.

**Comment by sav007** [comment]
What about the Apollo gradle plugin itself `apollo-gradle-plugin`?

**Comment by sav007** [comment]
make sure you are have this
```
plugins {
  id "com.apollographql.apollo" version "1.3.3"
}
```

**Comment by sneronovAdviqo** [comment]
<img width="1670" alt="Screenshot 2020-03-19 at 08 50 01" src="https://user-images.githubusercontent.com/50866520/77043870-addf0b80-69be-11ea-9a51-07aaf3d6aac1.png">

**Comment by martinbonnin** [comment]
@sneronovAdviqo can you check without the gradle cache ?  Clean your build and re-run your usual gradle command with `--no-build-cache` ?

(https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_enable)

**Comment by sneronovAdviqo** [comment]
I already do it with --no-build-cache, because otherwise I have somehow duplication of generated classes. So, with parameter --no-build-cache the result the same.

**Comment by sneronovAdviqo** [comment]
@sav007 , @martinbonnin , any ideas?

**Comment by martinbonnin** [comment]
@sneronovAdviqo not really, sorry. Any chance you can create a small repo that reproduces the problem ?

**Comment by sav007** [comment]
Could you please also provide info on AS version and  what Gradle version are you on

**Comment by sneronovAdviqo** [comment]
Tried on Android Studio 4.0 Beta 3 / Android Studio 3.6.1
Gradle: 
- classpath 'com.android.tools.build:gradle:3.5.3'
- distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.1-all.zip

Also, I tried the latest version for Apollo:
Plugin:
   classpath 'com.apollographql.apollo:apollo-gradle-plugin:1.4.1'
Dependencies: 
    implementation "com.apollographql.apollo:apollo-runtime:1.4.1"
    implementation "com.apollographql.apollo:apollo-android-support:1.4.1"
    implementation "com.apollographql.apollo:apollo-http-cache:1.4.1"
    implementation "com.apollographql.apollo:apollo-rx2-support:1.4.1"

**Comment by sneronovAdviqo** [comment]
@martinbonnin , @sav007 , I had created a simple project and I have invited you to the repo. Please, check it.

**Comment by martinbonnin** [comment]
@sneronovAdviqo I get this error when trying to build the app:

``` 
~/git/adviqoapollotest$ ./gradlew :app:assembleDebug

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > nombre d'arguments incorrect
   > KotlinJvmAndroidCompilation with name 'debugAndroidTest' not found.
   > Task with name 'compileDebugAndroidTestKotlin' not found in project ':app'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 668ms
```

Any clue what this can be?

**Comment by martinbonnin** [comment]
Never mind, it works well with gradle 6.2.2....

**Comment by sneronovAdviqo** [comment]
@martinbonnin take a look to the screen shot, why generating of the code (parameters of class) particularly with linking to class and particularly not? So, the error particularly getting again.
<img width="1205" alt="Screenshot 2020-05-05 at 18 18 23" src="https://user-images.githubusercontent.com/50866520/81089651-e69a5c00-8efc-11ea-87b8-1a3e09c51078.png">

**Comment by sneronovAdviqo** [comment]
The problem is getting when I am migrating from Java-code-generation to Kontlin-code-generation

**Comment by sneronovAdviqo** [comment]
@martinbonnin @sav007 do you have something to say?

**Comment by martinbonnin** [comment]
@sneronovAdviqo it's working well for me. I updated your sample repo: https://github.com/martinbonnin/adviqoapollotest/tree/test (latest commit at the moment is: https://github.com/martinbonnin/adviqoapollotest/commit/97c216bf69612abfaebde41d6aa4fb1476e630c9)

I ran `./gradlew :app:assembleDebug`

Maybe try with  `--no-build-cache` ?

**Comment by sneronovAdviqo** [comment]
After 3 hours dancing with "buben" it started to work. But I do not know why it was sawing my brain... I did everything, as well as ./gradlew :app:assembleDebug with --no-build-cache parameter. 
"I updated your sample repo" - this project was compiling without problem, but my working project not. And, I already mentioned, that probably the issue was after switching from generateKotlinModels.set(false) to generateKotlinModels.set(true). And the problem was not once.

**Comment by martinbonnin** [comment]
To summarize, I think there are two issues here:

1. `size` fields resolving to the wrong scope. This was fixed by #1958 and #2122
2. Gradle cache issues. Sometimes wrong files are being fetched from the Gradle cache and we end up with Java/Kotlin duplicates and/or stale files. See also #2043  for a similar bug report.

I'm closing this issue as 1. should be good now. Do not hesitate to reopen if needed. 
Let's continue the discussion in #2043 for Gradle cache issues

**Comment by NathanWA** [comment]
This occurs on version 2.2.0. 
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:generateBciDebugServiceApolloSources'.
....
Caused by: java.lang.NumberFormatException: For input string: "null"
	at com.apollographql.apollo.compiler.parser.GraphQLDocumentParser.normalizeValue(GraphQLDocumentParser.kt:725)

Unlike other posters, I have NO IDEA what line of the schema, fragments, or queries is triggering this.  
Because it won't tell me.

**Comment by martinbonnin** [comment]
@NathanWA can you try with version `2.2.2` and open a separate issue if the issue is still there?

**Comment by nobelxavier1507** [comment]
I am seeing the same issue with apollo-runtime version 2.5.6 and apollo-client-maven-plugin version 3.3.1

**Comment by martinbonnin** [comment]
@nobelxavier1507 can you open a separate issue and post the GraphQL query that trigger the error there?
