### ISSUE TITLE
Kotlin & Java files being generated

### ISSUE THREAD

**Issue by KyleDBoyd** [apollographql/apollo-android#2036]
Hey all! Been using the library for awhile and loving it 💪 

**Summary**
I recently tried to uptake the kotlin model generation.

```
apollo {
    setGenerateKotlinModels(true)
}
```

This works well, but it also generates the Java class which results in a duplicate class error.

**Description**
Queries and schema live in `src/main/graphql/{package}/`

**Version**
1.3.2

**Comment by sav007** [comment]
Did you try to clean, maybe it was left overs from previous build?

cc @martinbonnin

**Comment by KyleDBoyd** [comment]
Yeah, I cleaned & delete the entire build directory in the module that contained the Java + Kotlin files 😕

**Comment by martinbonnin** [comment]
```
setGenerateKotlinModels(true)
```

I would not expect this to work on 1.3.2. I believe this changed to 

```
generateKotlinModels.set(true)
```

Can you double check your plugin version matches the `apollo-api` version ?

Also can you share thee structure of your build direcrtory ? it should be something like

```
build/generated/source/apollo/debug/service
```

**Comment by KyleDBoyd** [comment]
@martinbonnin Thanks for the quick reply!

I did also try `generateKotlinModels.set(true)`, but no luck there. According to the 1.3.x migration guide, this adjustment should only matter if you are using a `.kts` build file.

I've confirmed that my `apollo-gradle-plugin` is also `1.3.2`.

My build directory is `build/generated/source/apollo/debug/service/{package}` as you described above. Within the package there are files (Java & Kotlin) for each `graphql` query file. There is also a `type` with all of the generated ENUMs & inputs (Java & Kotlin).

**Comment by martinbonnin** [comment]
> According to the 1.3.x migration guide, this adjustment should only matter if you are using a `.kts` build file.

Indeed, Groovy still allows `setGenerateKotlinModels()` 👍 

> Within the package there are files (Java & Kotlin) for each graphql query file

Can you check the following?

* Only run one task: `./gradlew :module:generateDebugServiceApolloSources`
* Disable caching: `./gradlew :module:generateDebugServiceApolloSources --no-build-cache`

**Comment by KyleDBoyd** [comment]
Happy Monday! It was a gradle cache issue 🤦‍♂ Thanks @martinbonnin !

**Comment by sudansh** [comment]
I am still facing this issue. 
apollo version: 1.4.3
gradle: 6.3

`apollo {
generateKotlinModels.set(true)
}`

**Comment by martinbonnin** [comment]
@sudansh can you try deleting your gradle directory (`rm -rf ~/.gradle`) and re-run your task with `--no-build-cache` ?  Does it still happen ?

**Comment by sudansh** [comment]
thanks. this fixed it.
