### ISSUE TITLE
Parse field arguments from IR and supply to generated mapper fields

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#206]
We need field arguments to properly generate cache-keys for fields in a normalized cache. These field arguments need to have variable values resoled at run-time.

Simple Example of IR arguments:

```
	"source": "query TestQuery($episode: Episode, $includeName: Boolean!) {\n  hero(episode: $episode) {\n    __typename\n    name @include(if: $includeName)\n  }\n  human(id: \"1000\") {\n    __typename\n    name\n    height(unit: FOOT)\n  }\n}",
			"fields": [
				{
					"responseName": "hero",
					"fieldName": "hero",
					"type": "Character",
					"args": [
						{
							"name": "episode",
							"value": {
								"kind": "Variable",
								"variableName": "episode"
							}
						}
					],
					"fields": [
						{
							"responseName": "name",
							"fieldName": "name",
							"type": "String!",
							"isConditional": true
						}
					],
					"fragmentSpreads": [],
					"inlineFragments": []
				},
				{
					"responseName": "human",
					"fieldName": "human",
					"type": "Human",
					"args": [
						{
							"name": "id",
							"value": "1000"
						}
					],
					"fields": [
						{
							"responseName": "name",
							"fieldName": "name",
							"type": "String!"
						},
						{
							"responseName": "height",
							"fieldName": "height",
							"type": "Float",
							"args": [
								{
									"name": "unit",
									"value": "FOOT"
								}
							]
						}
					],
					"fragmentSpreads": [],
					"inlineFragments": []
				}
			],
			"fragmentsReferenced": []
		}
	],

```

However, per the graphql spec, arguments can nest. Therefore, a variable could be buried at the bottom of a long argument chain.

More Complex example:
```
"source": "query ComplexArguments($stars: Int!) {\n  author(input: {thoughts: \"yeah\", input: {stars: $stars}}) {\n    __typename\n    id\n  }\n}",
			"fields": [
				{
					"responseName": "author",
					"fieldName": "author",
					"type": "User",
					"args": [
						{
							"name": "input",
							"value": {
								"thoughts": "yeah",
								"input": {
									"stars": {
										"kind": "Variable",
										"variableName": "stars"
									}
								}
							}
						}
					],
					"fields": [
						{
							"responseName": "id",
							"fieldName": "id",
							"type": "Int!"
						}
					],
					"fragmentSpreads": [],
					"inlineFragments": []
				}
			],
			"fragmentsReferenced": []
		}

```

Anytime we see an object of the structure { "kind": "Variable", {"variableName": "stars"} } we will want substitute the run-time variable value.

**Comment by BenSchwab** [comment]
For the variable resolution I see two options:

1) Pass the IR Map as-is as the "arguments" on `Field`, and have the Reader resolve the variables before they are needed to generate the cache-key.
   
I don't see much value in processing the IR value during code-gen in this case, as it already encodes the information will need in a sane manner. I would suggest just a one-one mapping to a Java Map.

2) Follow the iOS approach 
```
 public init(reader: GraphQLResultReader) throws {
      createReview = try reader.optionalValue(for: Field(responseName: "createReview", arguments: ["episode": reader.variables["episode"], "review": reader.variables["review"]]))
    }
```

where the generated code holds the dynamic mapping logic of accessing the reader's variables.

Option (2) would require moving a Mapper's `fields` to a variable inside  the `map` function (which is essentially equivalent to the `init` function in the iOS code).


If moving the fields is a viable option, my preference would be for (2), barring everything else being equal, similarity across clients is a plus.

**Comment by BenSchwab** [comment]
@sav007 Did a little more investigation into the issue we talked about earlier today.

**Comment by sav007** [comment]
I would go with option 1 as it requires a little changes to how our Field read from response. With option 2, it requires drastically changes on how we generate Mappers plus streaming parsing is not possible anymore. I still want to make streaming parsing work for fragments, have some thoughts.

**Comment by sav007** [comment]
Plus I have some thoughts about how to make `ResponseJsonStreamReader` to work with cache.
How about this: in `com.apollographql.android.converter.ResponseJsonStreamReader#read` we accumulate values for fields in Map. And when we finish reading we can call `Cache.store(map)`.

For Field objects we will return `com.apollographql.android.converter.ResponseJsonStreamReader#nextObject` not only the object value but cache key that we can use to make reference in parent object.
