### ISSUE TITLE
Use AnimalSniffer to detect Java compatibility issues

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#2060]
Now that we are moving to Kotlin, we should use AnimalSniffer to detect compatibility issues. I first saw this with OkHttp codebase. They use it make sure the library is compatible down to Android 5. 

Here are some links:
https://github.com/xvik/gradle-animalsniffer-plugin
https://github.com/square/okhttp/blob/97a5e7a9e0cdafd2bb7cbc9a8bb1931082aaa0e4/build.gradle#L144

**Comment by martinbonnin** [comment]
> They use it make sure the library is compatible down to Android 5

Isn't this what `minSdkVersion` is for ? If we're using an Android API from < minSdkVersion, shoudln't we get a compile error ?

**Comment by tasomaniac** [comment]
That's true only if you use Android library Gradle plugin. Except for the Android support module, none of the modules are Android.

**Comment by tasomaniac** [comment]
Closing this now since it looks like we are ok.
