### ISSUE TITLE
CacheAndNetworkFetcher always reports "fromCache() == true"

### ISSUE THREAD

**Issue by giantramen** [apollographql/apollo-android#2064]
I am using the CacheAndNetworkFetcher and I am getting responses from the cache and network (verified by inspecting payloads) but on the response, the .fromCache() is always true, even though I know it's coming from the server.

**Comment by tasomaniac** [comment]
@BenSchwab do have any idea about this? Thanks

**Comment by sav007** [comment]
That looks weird as we have test for this: https://github.com/apollographql/apollo-android/blob/master/apollo-integration/src/test/java/com/apollographql/apollo/internal/fetcher/CacheAndNetworkFetcherTest.java#L45-L50

**Comment by sav007** [comment]
@giantramen by any chance are you setup Apollo with http cache as well? As it can explain why you see this.

Http cache is handled on OkHttp layer. Even you think it hits network it might handled by http cache.

**Comment by giantramen** [comment]
@sav007 We use OkHttp but I don't think that's the issue, I can clearly tell the data isn't from any cache because the data changes every time we request it from the server.

**Comment by giantramen** [comment]
I was running 1.2.0, this seems to be fixed in 1.4.5.
