### ISSUE TITLE
RxJava3 support?

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#2068]
Should Apollo Android support RxJava3?

It would actually be very easy. The question is whether if we want to or not?

**Comment by tasomaniac** [comment]
If anybody is using RxJava3 and Apollo together (or interested in), please thumbs up 👍 this issue.

**Comment by xghita** [comment]
> Should Apollo Android support RxJava3?

why not?

**Comment by martinbonnin** [comment]
Closed with https://github.com/apollographql/apollo-android/pull/2304
