### ISSUE TITLE
Misleading docs - RxJava2 integration 

### ISSUE THREAD

**Issue by Gilwe** [apollographql/apollo-android#2074]
**Summary**
in https://www.apollographql.com/docs/android/advanced/rxjava2/  it says that subscriptionCall is converted to Observable but in your code it convert to Flowable

**Comment by tasomaniac** [comment]
Thanks for the report. This is fixed in https://github.com/apollographql/apollo-android/commit/de30037e1084f7853459fffc8cb121153155d4cb
