### ISSUE TITLE
 The documentation for Coroutines is missing new extensions on the latest version 1.3.3

### ISSUE THREAD

**Issue by zachburt05** [apollographql/apollo-android#2077]
**Summary**
The [Coroutine Support Documentation](https://www.apollographql.com/docs/android/advanced/coroutines/) is missing new extensions.

**Description**
The new Coroutines extensions found in `CoroutinesExtensions.kt` are: 

`fun <T> ApolloSubscriptionCall<T>.toFlow(): Flow<Response<T>>`
`fun <T> ApolloCall<T>.toFlow()`
`fun <T> ApolloQueryWatcher<T>.toFlow()`
`fun <T> ApolloSubscriptionCall<T>.toFlow(): Flow<Response<T>>`

**Version**
apollo-coroutines-coroutines v1.3.3

I would be more than happy to make a pull request to add these extensions to the docs real quick!

**Comment by martinbonnin** [comment]
@zachburt05 pull requests are very welcome. Do not hesitate to remove the `toChannel` documentation that was deprecated in favor of `Flows`
