### ISSUE TITLE
Unsupported token `:`

### ISSUE THREAD

**Issue by Mingela** [apollographql/apollo-android#2080]
**Summary**
Trying to follow a tutorial from https://www.apollographql.com/docs/graphql-subscriptions/subscriptions-to-schema/ 
```
type Comment {
  id: String
  content: String
}

type Subscription {
  commentAdded(repoFullName: String!): Comment
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
```

and I keep getting 

```
Unsupported token `:`
  ----------------------------------------------------
  [6]:type Subscription {
  [7]:    commentAdded(repoFullName: String): Comment
  [8]:}
  ----------------------------------------------------
```

Please provide any ideas since the documentation is not really exhaustive on validation.

**Version**
1.3.3

**Comment by sav007** [comment]
You provided a wrong GraphQL query (it's a GraphQL schema). Please see https://graphql.org/learn/queries/  for more details

**Comment by sav007** [comment]
Or here is another example of valid GraphQL subscription syntax https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/subscriptions/TestOperation.graphql

**Comment by Mingela** [comment]
Thank you! I was able to fix the error using the example. Additionally I needed to generate `.graphql` from my `schema.json` that could be done using IDEA plugin.
Now the gradle task behaves strange as well. It says `Unsupported token `!`` for any appearance in that auto generated file. Okay, I removed all the `!` and now it says `Unsupported token `implements`` =_= Is it normal, how to proceed then?
