### ISSUE TITLE
Failed to resolve: com.apollographql.apollo:apollo-http-cache-api:1.4.0

### ISSUE THREAD

**Issue by lukas1** [apollographql/apollo-android#2099]
**Summary**
Trying to use release 1.4.0 (same for 1.4.1), user gets error
`Failed to resolve: com.apollographql.apollo:apollo-http-cache-api:1.4.0` (or `1.4.1` respectively)

**Description**
It really seems, that the package is not published:
https://jcenter.bintray.com/com/apollographql/apollo/

It's missing in the list of packages (at time of writing this issue)

**Version**
`1.4.0`, `1.4.1`. Likely caused by https://github.com/apollographql/apollo-android/commit/dd10f00cf3dc43b63213685e0b926dffd5c34162#diff-ef9a0d4e10d6314c5aad5f1e6b1b8bee , this commit created new artifact, but it seems like, uploading it to jcenter doesn't work.

**Comment by aoudiamoncef** [comment]
Hi, 
I have the same issue both il local and CircleCI.

**Comment by LarsEliasNielsen** [comment]
Does any of the previous releases work?

**Comment by lukas1** [comment]
yes, `1.3.3` worked

**Comment by lukas1** [comment]
the difference is, that in `1.3.3` they didn't have this package `apollo-http-cache-api`

it's new and from what I understand, it's related to Kotlin Multiplatform

**Comment by tagrudev** [comment]
Any solution for this one 🤔 ?

**Comment by lukas1** [comment]
**everyone** Seems to be resolved now, package has been uploaded

**Comment by martinbonnin** [comment]
Sorry about that, there's a manual step to promote packages to jcenter that took a bit of time.

If this ever happens again, you can use  `https://dl.bintray.com/apollographql/android` as a repo. This is the repo where artifacts are uploaded before being promoted to jcenter.
