### ISSUE TITLE
graphql gives errors but the code works fine

### ISSUE THREAD

**Issue by abdelkawi** [apollographql/apollo-android#2100]
![error](https://user-images.githubusercontent.com/26113573/77491392-4e617f80-6e46-11ea-95bc-4ade114ed6ff.png)

the code runs fine but when add new line of code gives an error

**Comment by lukas1** [comment]
What kind of error? This report is not very specific. Can you run the same query without errors in some other GraphQL tool?

**Comment by abdelkawi** [comment]
@lukas1  sorry for that , 
after searching i found that i have to put ".graphqlconfig"  file , 
when i add it , the errors gone .
