### ISSUE TITLE
Apollo-Android is not compatible with the Android Studio

### ISSUE THREAD

**Issue by jamesweb1** [apollographql/apollo-android#2103]
**Summary**
Apollo-Android is not compatible with the Android Studio.

**Description**
I try to using GraphQL in my Android project in Android Studio. It works when I put `schema.json` in the graphql folder but all .graphql indicate the errors with `Unknown type...`.

After, I try to add the `.graphqlconfig` and generate the `schema.graphql`, and the errors are still there. I don't know the difference between `schema.json` and `schema.graphql`. Should I keep both of them? And how can I edit .graphql file correctly in the Android Studio without error?

[error image](https://imgur.com/c2tqe8x)

**Version**
1.3.2

**Comment by sav007** [comment]
Sorry but you probably confused here with completely different and unrelated to Apollo AS plugin, I can guess this plugin is https://plugins.jetbrains.com/plugin/8097-js-graphql might be wrong.

Apollo is just for code generation from the provided `. graphql ` files and `schema.json`. We don't provide any integration with AS / IDEA, means no validation-autocompletion in IDE.

**Comment by tasomaniac** [comment]
Should this be closed?

**Comment by AhmadAlhajKarim** [comment]
install apollo globally instead of locally so
npm install -g apollo 
That worked for me!
