### ISSUE TITLE
Gradle config: task is skipped when schemaFile is an absolute path

### ISSUE THREAD

**Issue by zhuhaow** [apollographql/apollo-android#2104]
**Summary**
If schemaFile is set to an absolute path, no matter what, no error or generation will happen.

**Description**
Can be reproduced by using

```
apollo {
    service("someservice") {
        schemaFile.set(file("/anything_here"))
        sourceFolder.set("com/myproject")
        rootPackageName.set("com.myproject")
    }
}
```

There will be no error and no code will be generated, no matter the schema file exists or not. (But it can not be a folder otherwise there would be error).

If I remove `schemaFile.set(file("/anything_here"))` and copy the schema file to the `sourceFolder`, then everything will work fine.

I found this issue because our project used a schema file generated by another gradle task.

It took me a lot of time to find a solution since the task is only registered `afterEvaluate`, but finally I came up with 
```
tasks.withType(com.apollographql.apollo.gradle.internal.ApolloGenerateSourcesTask) {
    dependsOn "generateSchema"
}
```
then we can reference the schema file by the variable defined by that task.

I logged to check the the path passed in for schemaFile is correct (which is an absolute path) and the generated file was there but there is simply no code generated.

Then I noticed the absolute path will simply make the whole code generation skipped

```
> Task :tools:seed:generateIntegrationSeedApolloSources NO-SOURCE
Skipping task ':tools:seed:generateIntegrationSeedApolloSources' as it has no source files and no previous output files.
:tools:seed:generateIntegrationSeedApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) completed. Took 0.016 secs.
:tools:seed:generateIntegrationApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) started.

> Task :tools:seed:generateIntegrationApolloSources UP-TO-DATE
Skipping task ':tools:seed:generateIntegrationApolloSources' as it has no actions.
:tools:seed:generateIntegrationApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) completed. Took 0.0 secs.
:tools:seed:generateMainSeedApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) started.

> Task :tools:seed:generateMainSeedApolloSources NO-SOURCE
Skipping task ':tools:seed:generateMainSeedApolloSources' as it has no source files and no previous output files.
:tools:seed:generateMainSeedApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) completed. Took 0.017 secs.
:tools:seed:generateMainApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) started.

> Task :tools:seed:generateMainApolloSources UP-TO-DATE
Skipping task ':tools:seed:generateMainApolloSources' as it has no actions.
:tools:seed:generateMainApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) completed. Took 0.0 secs.
:tools:seed:generateTestSeedApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) started.

> Task :tools:seed:generateTestSeedApolloSources NO-SOURCE
Skipping task ':tools:seed:generateTestSeedApolloSources' as it has no source files and no previous output files.
:tools:seed:generateTestSeedApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) completed. Took 0.017 secs.
:tools:seed:generateTestApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) started.

> Task :tools:seed:generateTestApolloSources UP-TO-DATE
Skipping task ':tools:seed:generateTestApolloSources' as it has no actions.
:tools:seed:generateTestApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) completed. Took 0.0 secs.
:tools:seed:generateApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) started.

> Task :tools:seed:generateApolloSources UP-TO-DATE
Skipping task ':tools:seed:generateApolloSources' as it has no actions.
:tools:seed:generateApolloSources (Thread[Execution worker for ':' Thread 9,5,main]) completed. Took 0.0 secs.
```

**Version**
1.3+

**Comment by tasomaniac** [comment]
`file` is a function under Project and supposed to be used for Project files. For absolute file path, can you try to instantiate regular java File. Like `new File("/absolutePath")`

**Comment by zhuhaow** [comment]
Hi @tasomaniac, I tried to use `new File` but nothing changes.

**Comment by tasomaniac** [comment]
I've looked at the tests. If you put your absolute path as String into `sourceFolder`, then it will work. If you have only 1 `schemaFile` in that folder, that schema should be discovered automatically.

**Comment by zhuhaow** [comment]
Thank you @tasomaniac . I tried to copy everything to a folder and set the `sourceFolder` and it worked great.

BTW, is `schemaFile` not working in this case by design or a bug?

**Comment by tasomaniac** [comment]
I guess we need to do better at documentation. `sourceFolder` is good if you have a custom folder where you have everything in there. Using `schemaFile` together with that would be tricky.

**Comment by tasomaniac** [comment]
The new plugin supports connecting outputs of another task into either schemaFile or GraphQL sourceSet. 

Here is an example test where we do this. If you have another task, you can connect the output of that task into the input of Apollo tasks. 

https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/test/kotlin/com/apollographql/apollo/gradle/test/LazyTests.kt#L29
