### ISSUE TITLE
Read GraphqlFragment from normalized cache with Kotlin generated models

### ISSUE THREAD

**Issue by peterplamenovpenchev** [apollographql/apollo-android#2111]
### Summary

I am currently building an android app for educational purposes. Essentially what this app does is the following:

1. It targets the Github GraphQL API via Apollo
2. It has 2 screens: repository list & details
3. When the app starts the list is loaded
4. When an item is clicked the user is redirected to the details

What I have found out is that I cannot load a `GraphqlFragment` from the normalized cache when I am using Kotlin generated models while the same is possible if the models are in Java. Here is my setup:

### Versions

build.gradle
```
ext.kotlin_version = '1.3.71'
dependencies {
    classpath 'com.android.tools.build:gradle:3.6.1'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath 'com.apollographql.apollo:apollo-gradle-plugin:1.4.0'
}
```

app/build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'com.apollographql.apollo'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

dependencies {
    ...
    implementation 'com.apollographql.apollo:apollo-runtime:1.4.0'
    implementation 'com.apollographql.apollo:apollo-rx2-support:1.4.0'
    ...
}
```

### Query

```
query Repositories($org: String, $after: String) {
  organization(login: $org) {
    repositories(first: 20, after: $after) {
      nodes {
        ... RepositoryDetails
      }
      pageInfo { hasNextPage endCursor }
    }
  }
}

fragment RepositoryDetails on Repository {
  id
  name
  description
  primaryLanguage { name color }
  pullRequests(states: [OPEN]) { totalCount }
  viewerHasStarred
  stargazers { totalCount }
  viewerSubscription
  watchers { totalCount }
}
```

### Outcomes
1. `Java` mode:
```
apollo {
    generateKotlinModels = false
    generateModelBuilder = true
}
```

The consuming code is the following:

```
val disposable = client.apolloStore.read(
  RepositoryDetails.Mapper(),
  CacheKey.from(id),
  Operation.EMPTY_VARIABLES
).rx().subscribe( ... ) // Successfully emits a `GraphqlFragment` if in store
```

2. `Kotlin` mode:
```
apollo {
    generateKotlinModels = true
}
```

The consuming code is the same, but right now it cannot compile because of the missing `Mapper` class which is a crucial parameter if we want to extract an arbitrary `GraphqlFragment` by `id` from the normalized cache:

```
val disposable = client.apolloStore.read(
  RepositoryDetails.Mapper(), // this Mapper is missing from the code-gen
  CacheKey.from(id),
  Operation.EMPTY_VARIABLES
).rx().subscribe( ... )
```

### Questions

1. Is there a valid reason for this discrepancy in the code-gen?
2. Will the `Mapper` be part of a future code-gen and feature parity improvement?
3. Is there a workaround for reading `GraphqlFragment`s from the normalized cache?

Thanks in advance!

**Comment by sav007** [comment]
You can do this by:
```
client.apolloStore.read(
  ResponseFieldMapper { RepositoryDetails(it) },
  CacheKey.from(id),
  Operation.EMPTY_VARIABLES
....
```

Agree that this is not very obvious and we should fix it.

**Comment by peterplamenovpenchev** [comment]
Awesome, I can confirm that the proposed code is working. Somehow I missed this. Thanks for the help!
