### ISSUE TITLE
Migrate coroutines-support module to Kotlin multiplatform

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#2121]
Migrate coroutines-support module to Kotlin multiplatform

**Comment by tasomaniac** [comment]
While working on #2120 I realized that `coroutines-support` depends on runtime and that will need to be migrated first.

**Comment by martinbonnin** [comment]
Is this still required? Since `apollo-runtime-kotlin` will expose a coroutines-first API, I don't think `apollo-coroutines-support` needs to be multiplatform.

**Comment by tasomaniac** [comment]
I agree. Should this module actually be deprecated at some point?

**Comment by martinbonnin** [comment]
I was thinking of deprecating it once `apollo-runtime-kotlin` reaches feature-parity with `apollo-runtime`
