### ISSUE TITLE
How to implement and plugin a interceptor/filter for the client?

### ISSUE THREAD

**Issue by xma000** [apollographql/apollo-android#2131]
How can I implement an interceptor/filter for a GraphQL Android client? How can I configure the client instance to use it. In the interceptor, I need to access both `errors` in the GraphQL response and HTTP headers.

The iOS client has `HTTPNetworkTransportDelegate`s for this purpose.

**Comment by designatednerd** [comment]
It's actually a lot easier in Android, you should be able to use an [`ApolloInterceptor`](https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/interceptor/ApolloInterceptor.java) for this.

**Comment by xma000** [comment]
@designatednerd Thanks for the pointer. I see that `InterceptorResponse` passed to `Callback#onResponse` contains both the parsed GraphQL response and the HTTP response. I guess that serves the need.
