### ISSUE TITLE
Make kotlin-sample project use generated Kotlin models

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#2134]
Current Kotlin sample uses Java code generation. Enable Kotlin code generation and update usages accordingly.

**Comment by SubhrajyotiSen** [comment]
Can I pick this up?

**Comment by tasomaniac** [comment]
Please go ahead. That would be awesome.

**Comment by tasomaniac** [comment]
Hey, just a heads-up. #2189 will migrate the samples to AndroidX. That's a minimal change and only imports change. You might have some conflicts.

**Comment by SubhrajyotiSen** [comment]
Thanks for the heads up. I have done a rebase.
I will submit a PR shortly
