### ISSUE TITLE
Create function to prepare request body

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#2137]
This is a follow-up on this conversation. https://github.com/apollographql/apollo-android/pull/2136#pullrequestreview-387798354

### TODO

Create a function on Operation class to convert it to Json to be used in request body.

This JSON conversion should be done according to the code we already have in `apollo-runtime`: https://github.com/apollographql/apollo-android/blob/58e17b960fdc181d04d904b616a80e80bb8ff453/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloServerInterceptor.java#L210

Ideally it should be used in there + in iOS sample.

After this is done, please update the docs accordingly: https://www.apollographql.com/docs/android/advanced/no-runtime/

**Comment by sav007** [comment]
@tasomaniac I can take it if you haven't started yet

**Comment by tasomaniac** [comment]
I haven't started on any of them yet. Please go ahead 👍
