### ISSUE TITLE
Replace Retrofit with Apollo Client

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#214]
Retrofit was a good idea at the time but is starting to slow us down.  We will mimic 

- [ ]  Create a Design Document for Apollo Client Api 
- [x] Create Call Interface
- [ ]  Create an RxJava Adapter to allow apollo client to return Observable<Response>
- [x] Move Converter to Apollo Client #216 
- [x] Remove the current Retrofit Implementation #216

**Comment by sav007** [comment]
@digitalbuddha can we close this ticket?

**Comment by digitalbuddha** [comment]
The rx stuff has a separate ticket.
