### ISSUE TITLE
License metadata broken

### ISSUE THREAD

**Issue by dsvensson** [apollographql/apollo-android#2140]
The release jars files do not inform the MIT license that at least GitHub has assigned to this project, which prevents automatic tooling for classifying this project, using for example: 

https://github.com/jk1/Gradle-License-Report

...but I guess any tool would have the same problem.

**Comment by tasomaniac** [comment]
Do you know from which version is it broken?

**Comment by tasomaniac** [comment]
Will be fixed with 2.0
