### ISSUE TITLE
Kotlin & Java both are being generated 

### ISSUE THREAD

**Issue by sudansh** [apollographql/apollo-android#2141]
**Summary**
using the below generates kotlin classes
```
apollo {
    setGenerateKotlinModels(true)
}
```
but it also generates the Java class which results in a duplicate class error.

**Description**
The bug https://github.com/apollographql/apollo-android/issues/2036 seems to be closed. But I am still facing that problem. I have tried  rebuilding, manually deleting cache

**Version**
1.4.3

**Comment by sav007** [comment]
cc @martinbonnin

**Comment by sudansh** [comment]
this fixed it 
https://github.com/apollographql/apollo-android/issues/2036#issuecomment-609874087
