### ISSUE TITLE
Breaking change: CustomTypeAdapter/CustomTypeValue has moved packages

### ISSUE THREAD

**Issue by hedvigoscar** [apollographql/apollo-android#2143]
**Summary**
`CustomTypeAdapter` and `CustomTypeValue` (and possibly more classes) have moved packages in 1.3.3 => 1.4.0, constituting a breaking change. This is unexpected as there has only been a minor version increase, and breaking changes are generally expected for major version increases

**Description**
Issue was probably introduced in https://github.com/apollographql/apollo-android/pull/1985

**Version**
1.4.0 and up

**Comment by tasomaniac** [comment]
Sorry about that. This is a mistake from our side. Going to close this since we cannot really fix this anymore. 2.0 is already released.
