### ISSUE TITLE
Convert apollo-normalized-cache module to Kotlin

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#2144]
Convert apollo-normalized-cache module to Kotlin

**Comment by tasomaniac** [comment]
Couple Pull Requests merged for this issue and allowed easier integration of SqlDelight. Feel free to pick this up and continue migrating more to Kotlin

**Comment by SubhrajyotiSen** [comment]
Hi. Can I pick this up?

**Comment by SubhrajyotiSen** [comment]
Also, would be better to do it in batches or all remaining java files at one go?

**Comment by tasomaniac** [comment]
Hi, I've tackled part of this in couple of PRs. I think this is good to take over.

Please do not touch the `api` and `sqlite` modules of the normalized cache. I have a local branch converting them to multiplatform. 🎉

You can help by converting from `normalized-cache` module. Please keep changes small and make sure there are almost not changes in the test sources (to ensure backward compatibility)

**Comment by martinbonnin** [comment]
Closed with https://github.com/apollographql/apollo-android/pull/2457
