### ISSUE TITLE
Unable to generate classes for recursive tree structures

### ISSUE THREAD

**Issue by me-hek** [apollographql/apollo-android#2156]
Hi,

I am having issues generating classes with below error. 

### **Can't query _Info_ on type _Info_**

_**Code Sample**_

_Info.graphqls_
extend type Query {
listSomeInfo(userId: String!): [Info!]
}

type **Info** {
id: ID!
name: String!
desription: String!
children: [**Info**!]
parent: **Info**
}

_Info.graphql_
```
query ($userId: String!) {
  listSomeInfo(userId: $userId) {
    id
    name
    desription
    children: Info {
      id
      name
      children: Info {
        id
        name
      }
      parent: Info {
        id
        name
      }
    }
  }
}
```

**Comment by sav007** [comment]
Looks like your query is not valid, please see https://graphql.org/learn/queries/#aliases

Instead of `children: Info` probably want you want is `info:children`

**Comment by sav007** [comment]
Seems like there is no issue. Closing for now, but feel free to reopen if needed.
