### ISSUE TITLE
Move converter to Apollo client

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#216]
Part of master ticket #214 

- [ ] Merge :apollo-converter into :apollo-runtime.
- [ ] Rename `Apollo` to `ApolloClient`
- [ ] Change `ApolloClient` initialization to accept user `OkHttpClient` instead `Retrofit`
- [ ] Add graphql server endpoint as a parameter to `ApolloClient` initialization
- [ ] Introduce API calls to perform query execution in `ApolloClient`:
  - `void fetch(Query, Callback<Operation.Data>)` - async (aligned with iOS API)
  - `void fetch(Query, Callback<Operation.Data>, Handler callbackHandler)` - async (aligned with iOS API)
  - `void perform(Mutation, Callback<Operation.Data>)` - async (aligned with iOS API)
  - `void perform(Mutation, Callback<Operation.Data>, Handler callbackHandler)` - async (aligned with iOS API)
  - `Operation.Data execute(Operation)` - sync (this call user can wrap with Rx)
- [ ] Merge logic from `ApolloRequestBodyConverter` and `ApolloResponseBodyConverter` into `ApolloClient`

**Comment by digitalbuddha** [comment]
Have you given thought to how async will work? Will apollo make a thread?  If so we should allow user to pass in their own executor.

**Comment by digitalbuddha** [comment]
Also if you make fetch with callback void, you won't have a way to prevent memory leak.  Ideally you need to return a subscription or disposable or something similar to allow user to cancel which would drop callback reference
