### ISSUE TITLE
multi dimensional array(geoJSON) in response gets parsed as generic object and toString() of that object is returned in the response

### ISSUE THREAD

**Issue by aritraBhattacharya** [apollographql/apollo-android#2165]
**Summary**
**multi dimensional array gets parsed as generic object and toString() of that object is returned in the response:**
I have a multi dimensional array containing geoJson data of a house. No matter what I do in my response this array is getting parsed as a generic object and a string is getting returned (returned by toString method of that object) in the response:

**Description**
The structure of data in the query response:
```
{
 .....
 .....
 .....
 .....
"boundary": {
            "type": "Polygon",
            "coordinates": [
              [
                [
                  -122.213648094587,
                  38.4062644361016
                ],
                [
                  -122.213614681217,
                  38.406252301868
                ],
                [
                  -122.213584424141,
                  38.4062358195175
                ],
                [
                  -122.21355822815201,
                  38.40621548193219
                ]
              ]
            ]
}
}
```

But when I'm debugging the data returned, this array is coming in this form:`boundary=com.apollographql.apollo.response.CustomTypeValue$GraphQLString@3e60401`
the property boundary is described in schema as:
```
          {
            "name": "boundary",
            "description": "",
            "type": {
              "kind": "SCALAR",
              "name": "GeoJSON",
              "ofType": null
            },
            "defaultValue": null
          } 
```

**Version**
1.0.0-alpha5

**Comment by sav007** [comment]
>1.0.0-alpha5 

You should probably try the latest version.

Also you have to setup custom scalar type mapping. If you want your `GeoJSON ` to be mapped into some data structure please follow the guides how to setup custom scalar type mapping.

**Comment by aritraBhattacharya** [comment]
Hi Sav007 I tried mapping it to an array but that was causing parse error, as of now I'm converting the whole data to string.
