### ISSUE TITLE
How to cache only selected responses?

### ISSUE THREAD

**Issue by piotr-pawlowski** [apollographql/apollo-android#2176]
How can I cache only responses from selected queries? I don't want to cache all queries because of security and privacy.
Thanks

**Comment by sav007** [comment]
There is API  `ApolloQueryCall#cacheHeaders` where you can set `CacheJeaders.builder().addHeader(ApolloCacheHeaders.DO_NOT_STORE, "true").build()` to skip cache response for both http and normalized cache
