### ISSUE TITLE
ERROR: Failed to resolve: com.apollographql.apollo:apollo-normalized-cache:1.4.4

### ISSUE THREAD

**Issue by piotr-pawlowski** [apollographql/apollo-android#2180]
How can I download normalized-cache?

**Comment by martinbonnin** [comment]
`apollo-normalized-cache` is a fairly new addition and shouldn't be needed in the `1.4.x` branch. You'll only need it from version `2.0.0+`. 
The docs in master are a bit ahead of time. You can use `apollo-android-support` for the time being. More details there: https://github.com/apollographql/apollo-android/blob/7fcf620cca20bc26f93ac523bc4b10a3e8f703c6/docs/source/essentials/caching.md

**Comment by tasomaniac** [comment]
Sorry for early update on the docs. Will close this for now since we are close to be releasing 2.0
