### ISSUE TITLE
Out of Memory: Metaspace during apollo-gradle-plugin tests

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#2184]
See https://github.com/apollographql/apollo-android/pull/2175#issuecomment-614393777, we're having Metaspace issues again. 

It looks like this is a Classloader leak somewhere. Right now the workaround is to fork a new Gradle instance more often but we should investigate the root cause behind this.

**Comment by tasomaniac** [comment]
Looks like this is not happening anymore. It could be that the test execution is longer now. Even with that, I'm not sure if this is high priority.
