### ISSUE TITLE
SqlNormalizedCache encryption

### ISSUE THREAD

**Issue by piotr-pawlowski** [apollographql/apollo-android#2185]
Is there any way to encrypt sql cache? Can I use ApolloStore somehow?

**Comment by tasomaniac** [comment]
Once 2.0.0 is released you will be able to instantiate the `SqlNormalizedCacheFactory` with a custom `SupportSQLiteOpenHelper.Factory` to be able to provide encryption. 

The code will looks something like by using the saferoom library https://github.com/commonsguy/cwac-saferoom

```
val state = SQLCipherUtils.getDatabaseState(context, DB_NAME)
if (state == UNENCRYPTED) {
    SQLCipherUtils.encrypt(context, DB_NAME, "passphrase".toCharArray())
}

SqlNormalizedCacheFactory(context, DB_NAME, SafeHelperFactory("passphrase".toCharArray()))
```
