### ISSUE TITLE
SqlNormalizedCache: support for useNoBackupDirectory flag

### ISSUE THREAD

**Issue by piotr-pawlowski** [apollographql/apollo-android#2186]
Please add to ApolloSqlHelper option useNoBackupDirectory that would prevent from backup a database. This option is available in AndroidSqliteDriver from sqldelight: 

https://github.com/cashapp/sqldelight/blob/master/drivers/android-driver/src/main/java/com/squareup/sqldelight/android/AndroidSqliteDriver.kt#L49

**Comment by martinbonnin** [comment]
Would it make sense to have an API where users can provide a `AndroidSqliteDriver` to the `SqlNormalizedCacheFactory` ?

The constructor is already there already: https://github.com/apollographql/apollo-android/blob/master/apollo-normalized-cache-sqlite/src/main/java/com/apollographql/apollo/cache/normalized/sql/SqlNormalizedCacheFactory.kt#L9

Maybe it's just a matter of making it public ?

**Comment by piotr-pawlowski** [comment]
It is a good idea to make `SqlNormalizedCacheFactory` API more flexible. `SqlNormalizedCacheFactory` could receive  `AndroidSqliteDriver` directly or `ApolloSqlHelper` as default value.

**Comment by tasomaniac** [comment]
That was my first implementation. But then I wanted to keep backward compatibility with AndroidSqlHelper. 

It's super easy to expose the constructor to take `SqlDriver`. Not only it will allow you pass those extra params but it will also make Multiplatform integration easier.

The issue is that I really want to keep SqlDelight as implementation detail and not expose it to consumers. Users might be using other persisting libraries and might be confusing to expose it as a transitive dependency.

**Comment by tasomaniac** [comment]
Btw, can you not disable backup behavior by providing backup descriptors? It's more defined here
 https://developer.android.com/guide/topics/data/autobackup

**Comment by piotr-pawlowski** [comment]
I understand that you do not want to expose internal dependecies (it's a good practice), but on the other hand you reduce possible configurations. So maybe wrap AndroidSqlHelper builder with your own ApolloSqlHelper builder.

> Btw, can you not disable backup behavior by providing backup descriptors?

Of course I can, but it's overhead when I need autobackup enabled with disabled sql backup. So there are 3 ways:
1. Save sql in no_backup folder (like Jetpack WorkManager) 
2. Write my own fullBackupContent with BackupAgent (it's overhead)
3. Write my own SqlNormalizedCache based on AndroidX SqlLite and existing SqlNormalizedCache.

**Comment by tasomaniac** [comment]
You are just in time. I just prepared a PR to provide these as additional constructor params.
