### ISSUE TITLE
How to implement offset based pagination in android with kotlin coroutines

### ISSUE THREAD

**Issue by pratthama-appdesk** [apollographql/apollo-android#2191]
There are no docs or tutorials that implements pagination in android
Can you guys help?

**Comment by martinbonnin** [comment]
I usually do this using regular requests and adapters. Most of GraphQL APIs use [connections](https://graphql.org/learn/pagination/#complete-connection-model), which support either paged-based pagination or cursor-based pagination.

Are you looking into integrating with the paging library or something else ?

**Comment by pratthama-appdesk** [comment]
Hi, thanks for the reply.
I have a limit and offset based server and I was looking through Apollo docs and read that it supports Pagination using fetchMore but the android docs link me to react .
and there is no written article or tutorial on this
I just want to implement the Pagination , I read about jetpack paging library but their docs were for Rest API and I am not sure how to do it
can you tell how to do this?

**Comment by martinbonnin** [comment]
If you have it working with REST, GraphQL isn't much different, you would pass `offset` and `limit` parameters to your GraphQL request:

Something like:
```
query Page($limit: Int!, $offset: Int!) {
    items(limit: $limit, offset: $offset) {
        nodes {
            id
            name
            ...
        }
    }
}
```

**Comment by pratthama-appdesk** [comment]
yeah I have got that, the issue is how to implement this to load data

**Comment by pratthama-appdesk** [comment]
any help regarding the implementation?

**Comment by martinbonnin** [comment]
@pratthama-appdesk the implementation isn't different than any other non-paginated query. You pass `limit` and `offset` parameters and retrieve data.
