### ISSUE TITLE
[Suggestion] Use Androidx annotations and not Jetbrains annotations for Java

### ISSUE THREAD

**Issue by ubarua123** [apollographql/apollo-android#2201]
**Is your feature request related to a problem? Please describe.**
You guys are using org.jetbrains.annotations for `NotNull` and `Nullable` which messes with Android Lint checker. It marks methods even though they are NotNull as nullable. 

**Describe the solution you'd like**
Androidx annotations are correctly reported by Lint. Use androix.annotation package. Though for kotlin its not needed.

**Comment by martinbonnin** [comment]
Apollo-android is used outside Android so it might be weird pulling the android annotations.

We could add a `androidAnnotated` option to the [nullableValueType](https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/api/CompilerParams.kt#L88). Would that work ?

**Comment by tasomaniac** [comment]
Android lint checks should be already supporting many different Nullable annotation types. Funny enough, Android team has 3 different Nullables 😊: Platform one, support lib and AndroidX.

Can you give an example of what the issue you currently have?

**Comment by ubarua123** [comment]
So there is this code segment in one of the generated files:
<img width="809" alt="Screenshot 2020-04-22 at 10 16 14 AM" src="https://user-images.githubusercontent.com/8141308/79941672-74e4fb80-8482-11ea-8877-4ecf2a06f83c.png">


Even though it has a `NotNull`, lint still complains.

<img width="728" alt="Screenshot 2020-04-22 at 10 13 25 AM" src="https://user-images.githubusercontent.com/8141308/79941503-1586eb80-8482-11ea-94e7-53b91e06b7cb.png">

That's the issue I am facing. 
Well, I mean it hasn't broken any code as such. Your library works perfect. Still I thought I bring it to your notice.

**Comment by Cliabhach** [comment]
@ubarua123 Can you show the source code of `fullHandle.userProfile()`? Based on the recommended replacement, I suspect that lint is trying to tell you that the return value from `userProfile()` is nullable.

**Comment by tasomaniac** [comment]
Hi, it looks like that it is actually working. The warning is not about `fragments()` but for `userProfile()`.

Calling fragments function can result on a NullPointer because `userProfile`s return type is marked as `@Nullable`. Can you check?

**Comment by tasomaniac** [comment]
No worries. Please don't hesitate to open any issue in the feature of you notice something else
