### ISSUE TITLE
`toFlow()` emits only single value from Query watcher

### ISSUE THREAD

**Issue by mateuszkwiecinski** [apollographql/apollo-android#2207]
**Summary**
`rx()` does not complete observable on `COMPLETED` event, but `toFlow()` does. 

**Description**
After changing from [RxJava based extension](https://github.com/apollographql/apollo-android/blob/master/apollo-rx2-support/src/main/java/com/apollographql/apollo/rx2/Rx2Apollo.java#L58) to [Flow based one](https://github.com/apollographql/apollo-android/blob/master/apollo-coroutines-support/src/main/kotlin/com/apollographql/apollo/coroutines/CoroutinesExtensions.kt#L58) I stopped getting any further updates via returned Flow. I get only single, initial value and collection job immediately completes. 
AFAICS https://github.com/apollographql/apollo-android/pull/2102 fixed behavior when `COMPLETED` events are emitted, but `toFlow()` extension kinda relied on the flawed behavior.

**Version**
2.0.0

**Comment by hedvigoscar** [comment]
Could this be the root cause of #2145 ?

**Comment by mateuszkwiecinski** [comment]
Huh, it could be, however the change I'm reffering to was introduced in version `1.4.3` and you menitoned you're able to reproduce it on `1.4.0` 🤔 
You can verify the behavior by adding your own extension and removing the [onStatusEvent override](https://github.com/apollographql/apollo-android/blob/master/apollo-coroutines-support/src/main/kotlin/com/apollographql/apollo/coroutines/CoroutinesExtensions.kt#L70)

**Comment by hedvigoscar** [comment]
On second thought I think the issue might be unrelated 🤔
