### ISSUE TITLE
Question: What is the best way to update Normalized cache after a mutation?

### ISSUE THREAD

**Issue by mishra-himanshu** [apollographql/apollo-android#2208]
I am performing these steps in sequence to update my normalized cache after a mutation but the operations seem to take time.

- mutate
- read-cache
- modify cache
- write and publish cache to notify the watcher

Wanted to check if there is a better way to achieve this?

**Comment by sav007** [comment]
Not sure if that will help but there is https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/ApolloClient.java#L140

basically you mutate cache before (optimistic update) request executed. If request fails it will rollback changes if success it will commit.

**Comment by mishra-himanshu** [comment]
Thanks for the suggestion, I will give optimistic updates another try but some of the mutations do not return the same type that I want to update in Cache.

**Comment by sav007** [comment]
>but some of the mutations do not return the same type that I want to update in Cache.

There is no way around to do this otherwise. Looks the only option is how you doing it right now,  read from the cache / update / write it back to the cache.
