### ISSUE TITLE
Put Everything Into the Requested Package

### ISSUE THREAD

**Issue by commonsguy** [apollographql/apollo-android#221]
Given this GraphQL document:

```
query getAllTrips {
  allTrips {
    ...commonFields
    startTime
    priority
    duration
    creationTime
  }
}

fragment commonFields on Plan {
  id
  title
}
```

located in `src/main/graphql/com/commonsware/graphql/trips/api/TripServer.graphql`, with `apollo-android` 0.2.1, and with a schema pulled from https://graphql-demo.commonsware.com/0.1/graphql, we wind up with `GetAllTrips` in `com.commonsware.graphqltrips.api`, which makes sense.

However, we also get:

- `fragment.CommonFields`
- `type.Priority`
- `ResponseFieldMappers` (outside of any Java package)

These might collide with other code in the app or in other libraries. Shouldn't these all be somewhere inside `com.commonsware.graphql.trips.api`? For example:

- `com.commonsware.graphql.trips.api.fragment.CommonFields`
- `com.commonsware.graphql.trips.api.type.Priority`
- `com.commonsware.graphql.trips.api.ResponseFieldMappers`

Issue #107 is related, insofar as the code used to generate `.fragment` as the package. If I were a betting man, I'd bet that the plan was for that to be appended to the base package name. The fix (issue #108) brought us what 0.2.1 has.

My apologies if I'm missing something somewhere.

**Comment by digitalbuddha** [comment]
The fragments and types are based on where the schema file was found. So, if the project structure is:

`src/main/graphql/schem.json`. The fragments and types will be under `import fragment` and `import type`.

To have them under the api namespace, the schema file should live under `src/main/graphql/com/example/api/schema.json`

ResponseFieldMapper will go away in next version.

**Comment by commonsguy** [comment]
Ah, OK. I understand. Sorry for cluttering up the issue tracker, and thanks for the info!

**Comment by digitalbuddha** [comment]
Clutter away!  Will serve as bank of answers until we move to SO
