### ISSUE TITLE
Failed to apply plugin [id 'com.apollographql.apollo']  apollo-android requires Gradle version 6.0 or greater

### ISSUE THREAD

**Issue by piotr-pawlowski** [apollographql/apollo-android#2224]
I cannot build project after migration to version. 2.0.0

`Failed to apply plugin [id 'com.apollographql.apollo']
   > apollo-android requires Gradle version 6.0 or greater`

**Comment by martinbonnin** [comment]
This error is expected. If I remember correectly, Gradle 6 was required mainly for gradle metadata.
It should work well if you bump your Gradle version to 6.0.0+

**Comment by piotr-pawlowski** [comment]
From docs: 

>Gradle 6.x recommended. In 5.x, Gradle Metadata needs to be enabled by putting this into settings.gradle enableFeaturePreview("GRADLE_METADATA")

It doesn't work.

**Comment by giantramen** [comment]
I ran into the same issue, enableFeaturePreview("GRADLE_METADATA") didn't work so had to upgrade to Gradle 6.

**Comment by martinbonnin** [comment]
@piotr-pawlowski does it work for you if you update to Gradle 6 ?

**Comment by piotr-pawlowski** [comment]
Yes, it works. Thank you!
