### ISSUE TITLE
Cache not updating record for the same CacheKey

### ISSUE THREAD

**Issue by PierLucaLW** [apollographql/apollo-android#2231]
After migrating to 2.0.0 the cache seems to not override the record for the same key anymore.

I'm using the `SqlNormalizedCacheFactory` with a null database name so that it clears everytime the app is killed. I did update the factory instance creation and the dependency as per the migration guide.

What I'm expecting, and this was working up to 1.4.5, is that when returning the same CacheKey in `fromFieldRecordSet` of the `CacheKeyResolver` this will update the record for that key with the current recordSet.
What's happening instead is that when I try to retrieve it from the cache it always picks the first record saved.

I manually trigger the cache with a call to `apolloStore.write(operation, operationData).execute()` as I'm getting the data I want to use to update it as a response of a mutation. I tried with `writeAndPublish` but the result is the same.

The only workaround I found is to always clear all the cache before with `apolloStore.clearAll().execute()` but this is not ideal. Seems also that `apolloStore.remove(CacheKey.from(id)).execute()` doesn't work to remove a single key. It actually seems that the call to remove is performed after the one to write.

**Comment by tasomaniac** [comment]
Hi, would be possible to share some of you code. Especially the CacheKeyResolver would be useful. I have some ideas but it would be good to reproduce this with a test case.

**Comment by sav007** [comment]
Also is it happening to SQL cache only? Have you tried just in memory cache such as `LruNormalizedCache`?

**Comment by PierLucaLW** [comment]
@tasomaniac here it is
```
class ApolloCacheKeyResolver : CacheKeyResolver() {
    override fun fromFieldRecordSet(field: ResponseField, recordSet: Map<String, Any>): CacheKey {
        if (recordSet.containsKey("my_id") && field.responseName == "my_response") {
            val id = recordSet["my_id"] as String
            return CacheKey.from(id)
        }
        return CacheKey.NO_KEY
    }

    override fun fromFieldArguments(field: ResponseField, variables: Operation.Variables): CacheKey {
        return when (field.responseName) {
            "my_response" ->
                if ((variables.valueMap()["my_id"]?.toString()).isNotNullOrEmpty()) {
                    CacheKey.from(variables.valueMap()["my_id"].toString())
                } else CacheKey.NO_KEY
            else -> CacheKey.NO_KEY
        }
    }
} 

@sav007 haven't tried with `LruNormalizedCache`  since this logic was already in place  and working for previous versions ideally wanna keep it as it was, unless there's a reason to use the Lru in this specific case

**Comment by PierLucaLW** [comment]
I think the issue might be here in the else branch of `SqlNormalizedCache`
```
override fun performMerge(apolloRecord: Record, cacheHeaders: CacheHeaders): Set<String> {
    val oldRecord = selectRecordForKey(apolloRecord.key())
    return if (oldRecord == null) {
      cacheQueries.insert(apolloRecord.key(), recordFieldAdapter.toJson(apolloRecord.fields()))
      emptySet()
    } else {
      oldRecord.mergeWith(apolloRecord).also {
        if (it.isNotEmpty()) {
          cacheQueries.update(oldRecord.key(), recordFieldAdapter.toJson(oldRecord.fields()))
        }
      }
    }
  }
```
I guess that should be
```
 oldRecord.mergeWith(apolloRecord).also {
        if (it.isNotEmpty()) {
          cacheQueries.update(it.key(), recordFieldAdapter.toJson(it.fields()))
        }
      }
```
