### ISSUE TITLE
Memoize mappers 

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#224]
Currently we create a new instance of mappers anytime we make a request. Ideally we would Memoize the mappers within ApolloClient do that we can reuse them of same mapper is required

**Comment by sav007** [comment]
@brianPlummer what the state of this ticket? if don't mind I can fix it

**Comment by brianPlummer** [comment]
@sav007 so sorry, i've gotten behind in life and won't get to this for a few days.  if you feel like taking it on, please do.  my apologies.

**Comment by sav007** [comment]
@brianPlummer no worries at all
