### ISSUE TITLE
generateApolloSources takes too long time to generate Kotlin model classes

### ISSUE THREAD

**Issue by developer--** [apollographql/apollo-android#2243]
**Is your feature request related to a problem? Please describe.**

My problem is that when I'm generating Kotlin model classes from graphql schema.json (~5MB) it takes about 12 minutes from my machine 
processor: i9
RAM: 16GB
os: macOS Catalina 10.14.5

But if I ran this generation from windows pc RAM 8GB, i5, without ssd it takes ~1 hour.

I'm interested what can be done to improve apollo class generation build speed, cause when my teammate builds it for iOS it takes less than a  minute ( schema.json file is same ).

`apollo version 2.0.1`

**Comment by martinbonnin** [comment]
On my 2018 Core i5 8GB MacBook pro, generating the sources for https://github.com/martinbonnin/github-graphql-sample takes ~400ms (build scan there: https://scans.gradle.com/s/423mgtaloumce).
There are not a lot of queries but the schema is the 3.5MB github schema so that's already something. 12min sounds really high. Is there any chance you can share a build scan ?

**Comment by martinbonnin** [comment]
Also maybe it's a specific query that takes some time. If you could share them, that'll help a lot. 

If not, can you bisect and remove queries progressively to see if the time spent depends linearly on the queries if some specific query take more time.

**Comment by developer--** [comment]
I can ensure that removing some of graphql files decreases build time from 15m to 2-3 m, but I'm interested why this problem doesn’t have for iOS

**Comment by martinbonnin** [comment]
Any chance you can share your schema ?

**Comment by developer--** [comment]
Here is the schema.json
https://drive.google.com/file/d/1X6X2HTY0Z37EVh7Od-oGrse5GdN_nTXQ/view?usp=sharing

**Comment by martinbonnin** [comment]
Thanks ! I started a small repo there to investigate the issue: https://github.com/martinbonnin/testCodegenPerf

So far it contains 2 small queries and it's working well on my laptop. Can you try on your machine ? And possibly add more queries to see which onees take a long time to generate ?

**Comment by developer--** [comment]
Thanks, I will try, but also I have to tell you that this problem only acquired about a week ago, when some query files added, and this problem is not only for me, every teammate has same problem, but iOS team members doesn't have any problem with build time

**Comment by developer--** [comment]
I'm testing your repo:
without added queries it took ~200 ms
Than I started to add queries one by one, I found one query, which took build 2m 52s to complete 
```

mutation createAddress($address:AddressInput!) {
    createAddress(input:{address:$address}) {
        address {
            ...addressDetails
        }
    }
}
fragment addressDetails on Address {
    id
    firstName
    lastName
    address
    address2
    state
    countryByCountryCode {
        name
        code
        phoneCodes
    }
    city
    zipcode
    phone
    types
}

```

**Comment by martinbonnin** [comment]
Thanks for the sample query. Plugging a debugger shows that the `AddressInput` references a lott of types and a lot of time is spent in `Schema.Type.InputObject.usedTypes`. @sav007 any idea how to optimize that ?

**Comment by sav007** [comment]
Yeah, `AddressInput` is a crazy object, it has referenced (via nested refs as well) 1/2 of all possible type declared in this 3.6Mb schema file, not sure if this is great GraphQL schema.

Will try to think how we can optimize but.... processing 2Mb of deep first traversing graph is not nice.

**Comment by developer--** [comment]
I see it is fixed, thanks for your effort. I'm interested, where I should make changes to my side? what should be updated?

**Comment by martinbonnin** [comment]
It'll be fixed in the next the next release. In between, you can use snapshot. 2.0.3-SNAPSHOT should have it. See https://github.com/apollographql/apollo-android#releases for more details
