### ISSUE TITLE
Migration from 1.4.5 to 2.0.1 produces errors

### ISSUE THREAD

**Issue by sneronovAdviqo** [apollographql/apollo-android#2247]
After change the version of the Apollo client I have next errors:
1. Unresolved reference: DEFAULT. F.e. in import "import com.apollographql.apollo.api.ScalarTypeAdapters.DEFAULT"
2. In generated class: "Type mismatch.
Required:String
Found:String?"
3. In generated class: "Class 'ExpertListingsQuery' is not abstract and does not implement abstract member public abstract fun parse(byteString: ByteString): Response<ExpertListingsQuery.Data> defined in com.apollographql.apollo.api.Query"
4. In generated class: "Interface OperationName does not have constructors"
5. In generated class: "Class 'ID' is not abstract and does not implement abstract member public abstract fun className(): String defined in com.example.adviqoapollotest.type.CustomType"
5. In generated class: "'javaType' overrides nothing"

Before version migration - were no these problems.

Plugin version:  classpath("com.apollographql.apollo:apollo-gradle-plugin:1.4.5")
Library version:  implementation("com.apollographql.apollo:apollo-runtime:2.0.1")

You can clone [the example project ](https://github.com/sneronovAdviqo/adviqoapollotest.git) and check it.

**Comment by sav007** [comment]
You should always keep `Plugin version`  the same as runtime, please update plugin version to `2.0.1`

**Comment by sneronovAdviqo** [comment]
Thank you for the hint.
Please, add the information (with accent on it) to the description of implementation.

**Comment by tasomaniac** [comment]
This should be caught by the Gradle plugin too. That is something @martinbonnin added in the past. I wonder if that is not working?

**Comment by martinbonnin** [comment]
Indeed, I guess that happens because the check only looks into the current project but in @sneronovAdviqo the plugin was added to the classpath of the rootProject.

**Comment by martinbonnin** [comment]
Follow up PR there: https://github.com/apollographql/apollo-android/issues/2247
