### ISSUE TITLE
Making old versions of the Apollo libs available.

### ISSUE THREAD

**Issue by mcossenas** [apollographql/apollo-android#2255]
**Summary**
Making old versions of the Apollo libs available.

**Description**
Currently our project does not want to upgrade to okHttp version 4 so hence we will not be upgrading to the latest version 2.0.0 of Apollo. However I do want a bug fix which is in Apollo 1.4.5 but this seems like it is not available via jcentre. Could some of the more recent versions please be made available via jcentre or could you please tell me where I'm able to access these older versions. Thanks

**Comment by martinbonnin** [comment]
1.4.5 should be on jcenter at : https://jcenter.bintray.com/com/apollographql/apollo/apollo-api/1.4.5/

Are you missing a specific module ?

**Comment by mcossenas** [comment]
Hey @martinbonnin thanks for your quick reply.

Found the issue. Android Studio was running in offline mode. For some reason I was able to grab 2.0.0 but not 1.4.5. One of life's mysteries. 

All good now so will close this issue. Thanks again for your help.
