### ISSUE TITLE
A way to send common query input parameters in all queries

### ISSUE THREAD

**Issue by abhishekvuclip** [apollographql/apollo-android#2262]
Hello Team,

Is there a way to send common query parameters instead of having it in all queries as input.

In below examples $geo:String, $country:String are common input parameters, which I would like to avoid passing as query parameter which a developer is forced to add in pass in all queries though query mainly needs id or statusId.
Instead I could store it some where and send in all queries from a common place.

Example 

```graphql
query activate($id:String, $name: String, $geo: String, $country: String){
    activate(
        input: {
            id:$id
            name: $name
            geo: $geo
            country: $country
        }
    )
}

query status($statusId: String, $geo: String, $country: String){
    activate(
        input: {
            statusId: $statusId
            geo: $geo
            country: $country
        }
    )
}
```

**Comment by martinbonnin** [comment]
I don't think there is something like this at the moment. You can do it in code if you really want to enforce the same `geo` and `country` parameters:

```
class QueryFactory(val geo: String, val country: String) {
  fun activate(id: String, name: String) = ActivateQuery(id, name, geo, country)
  fun status(statusId: String) = StatusQuery(statusId, geo, country)
}
```

**Comment by martinbonnin** [comment]
I'm closing this issue. Please leave a message if you want me to reopen it.
