### ISSUE TITLE
error: cannot find symbol import com.apollographql.apollo.api.ScalarTypeAdapters;

### ISSUE THREAD

**Issue by Parilar** [apollographql/apollo-android#2263]
**Summary**
I've upgraded my android project to the new apollo package and many classes are missing.
Cleaning Project and rebuild produce this error

error: cannot find symbol import com.apollographql.apollo.api.ScalarTypeAdapters;

**Description**
The following imports are missing 

import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.InputFieldMarshaller;
import com.apollographql.apollo.api.internal.InputFieldWriter;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;

**Version**
apollo-gradle-plugin:2.0.3
apollo-runtime:1.2.1

**Comment by martinbonnin** [comment]
The versions of `apollo-gradle-plugin` and `apollo-runtime` should match, else the runtime will not match the generated code. Can you bump `apollo-runtime` to `2.0.3` ?

**Comment by Parilar** [comment]
thx that worked. Android studio said that 1.2.1 is the newest
