### ISSUE TITLE
apollo-link-rest, for REST APIs through GraphQL, on mobile?

### ISSUE THREAD

**Issue by Tweener** [apollographql/apollo-android#2264]
Hi,
I'm looking for a way to use REST APIs inside GraphQL queries, on Android and iOS.

I've seen there is a [apollo-link-rest](https://www.apollographql.com/docs/link/links/rest/) library which seems to be only available for frontend apps.
I was just wondering if there was any plan in the roadmap to create this library for Android and iOS as well?

Cheers!

**Comment by sav007** [comment]
Not really sure if there is any benefit for introducing this feature. It's complicated due to the nature of strongly typed language Kotlin / Java unlike JavaScript. In fact, on Android Retrofit is default REST API client. 

Is there any practical use case where link rest is better than Retrofit?

**Comment by Tweener** [comment]
Hi @sav007,
Thanks for your reply.

We were thinking about using GraphQL for clients to write queries/mutations that will communicate with a REST API. The idea was to avoid having a GraphQL service backend-side and only use REST, but clients of this API can still use GraphQL, if they want to, because of its many advantages (ie. fetching data from multiple domain sources in one single query).

Retrofit, to my knowledge (so I might be wrong 😄), does not allow us to do so.

For us to move towards that direction means all API clients must be able to handle GraphQL with REST. That's why I wanted to ask if there was something on Android (and iOS as well) before going further.

Hope I explained myself clear enough!

**Comment by martinbonnin** [comment]
> fetching data from multiple domain sources in one single query

Although `apollo-link-rest` is "used" as a single query, it will make multiple HTTP calls behind the scenes:

From https://www.apollographql.com/docs/link/links/rest/#custom-fetch: 

> To resolve your GraphQL queries quickly, Apollo will issue requests to relevant endpoints as soon as possible. This is generally ok, but can lead to large numbers of REST requests to be fired at once; especially for deeply nested queries.

**Comment by Tweener** [comment]
Ah yes, thanks for the info @martinbonnin !
I guess that would be fine for us, if there is the equivalent of a `apollo-link-rest` on Android one day. It'll be our responsibility to make sure we don't perform too many REST requests.

**Comment by martinbonnin** [comment]
Closing as "out of scope". 

If you _really_ want something like this, you could look into [CacheResolver](https://github.com/martinbonnin/apollo-android/blob/d77b73f6f387ab474045f0db3c568d251ef55932/apollo-normalized-cache-api/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/api/CacheResolver.kt#L12) that allows you to return arbitrary data for some fields (see the [test builders doc](https://www.apollographql.com/docs/android/v3/advanced/test-builders/#configuring-default-field-values) for an example usage) . Coupled with [client side schema extensions](https://github.com/apollographql/apollo-android/blob/40e341ff35ca7666744a37a71cf0459c5ff915c8/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo3/gradle/api/Service.kt#L77), this _could_ be used to run arbitrary REST request in response to a GraphQL query. 

This is not completely straightforward but also not the main point of Apollo Android. Apollo Android is designed as a GraphQL client and we'd like to keep the usage focused to that part for now.
