### ISSUE TITLE
Kotlin Generated Code Not Building Properly

### ISSUE THREAD

**Issue by Mprice12337** [apollographql/apollo-android#2268]
**Summary**
Generated Kotlin Queries no longer building successfully. 

**Description**
The Generated Query calls "import com.apollographql.apollo.api.ScalarTypeAdapters.DEFAULT" but the system flags ".DEFAULT" as an unresolved reference. Works fine on 1.4.5 but on all the 2.x.x versions this error seems to be happening to me.

**Version**
2.0.3

**Comment by martinbonnin** [comment]
Can you check your versions of `apollo-gradle-plugin` and `apollo-runtime` They should both match for the generated code to reference the corresponding runtime.

**Comment by Mprice12337** [comment]
That was the issue, still had the Version 1.4.1 for the `apollo-gradle-plugin`. Updated and working now.
Thanks,
