### ISSUE TITLE
Regarding multiple queries run like compose in react

### ISSUE THREAD

**Issue by shivaambi** [apollographql/apollo-android#2271]
Is there any built-in feature available to run multiple queries in android graph ql library which are dependent on each other like compose.

```js
const userQuery = gql`query User { user { id } }`;
const stuffQuery = gql`query SomeOtherStuff($id: ID) { someOtherStuff(id: $id){ stuff } }`;

export default compose(
  graphql(userQuery, { name: 'userData' })
  graphql(stuffQuery, { name: 'stuffData', options: ({userData:{id}={}}) => ({variables: {id}}) }),
)(YourComponent)
```

**Comment by martinbonnin** [comment]
I *think* the Android equivalent would use coroutines. Something like?

```kotlin
val user = apolloClient.newCall(UserQuery()).toDeferred().await()
val otherStuff = apolloClient.newCall(SomeOtherStuff(user.data.id)).toDeferred().await()
```

There is no support for combining queries in the Android ApolloClient itself but it should be simple enough to do it using either coroutines or RxJava.

**Comment by martinbonnin** [comment]
@shivaambi I'm closing this issue, please leave a comment if you want me to reopen it.

**Comment by jackmoxley** [comment]
We have a need for this.

**Comment by martinbonnin** [comment]
@jackmoxley can you elaborate a bit more? Coroutines make it really easy to combine/sequence different calls. Can you share your use case?
