### ISSUE TITLE
apolloClient.query(..   Not enough information to infer type variable D

### ISSUE THREAD

**Issue by luisDMosquera** [apollographql/apollo-android#2276]
val apolloClient = ApolloClient.builder()
            .serverUrl("https://xxxxxxxxxxxxx:nnnnn")
            .okHttpClient(
                OkHttpClient.Builder()
                    .connectTimeout(30, TimeUnit.SECONDS)
                    .writeTimeout(30, TimeUnit.SECONDS)
                    .readTimeout(30, TimeUnit.SECONDS)
                    .build()
            )
            .build()

        apolloClient.query(GetEducacionesQuery.builder().build())
            .enqueue(object : ApolloCall.Callback<GetEducacionesQuery.Data>() {

                override fun onResponse(response: Response<GetEducacionesQuery.Data>) {
                    if (!response.hasErrors()) {
                        // Here response().data() contains the data you requested
                        Log.d("CUE", "Response: ${response.data}")
                    } else {
                        Log.d("CUE", "Request Failure ${response.errors}")

                    }
                }

                override fun onFailure(e: ApolloException) {
                    e.printStackTrace()
                }
            })
Problems:
apolloClient.query(..         query is underlined "Not enough information to infer type variable D"

apolloClient.query(GetEducacionesQuery.builder()....   builder is in red "Unresolved reference: builder" 

2.0.2
Provide a version of library on which the problem occurred.

**Comment by luisDMosquera** [comment]
Similar to bug #1866, but I can't understand the solution.

**Comment by sav007** [comment]
Is there any reason why you don't configure Apollo gradle plugin to generate Kotlin models?

**Comment by luisDMosquera** [comment]
sav007, there are no special reason, Is my first intent with graphql in android and I wish to work with kotlin.
The content of .graphql file is:

query GetEducaciones {
    educaciones{
        descEduc
        codEduc
    }
}

Thanks in advance.
Luis,

**Comment by luisDMosquera** [comment]
I have continued fiddling with this problem and found that in build.gradle (project) I have used version 2.0.1 in classpath "com.apollographql.apollo: apollo-gradle-plugin: 2.0.1"
whereas in build.gradle (app) I have used 2.0.2, I have changed the version in build.gradle (project) to 2.0.2.
Also in build.gradle (app) I had written two copies of "apply plugin: 'kotlin-android-extensions'" I have deleted one of them.
By synchronizing the project the problems have remained.
I also deleted:
apollo
     generateKotlinModels.set (true)
}
from the build.gradle (app) module and I synchronized again, but the problem continues.
I am going to continue looking for that this problem occurs, if you can help me in advance thank you very much. !!

Luis.

**Comment by luisDMosquera** [comment]
> Is there any reason why you don't configure Apollo gradle plugin to generate Kotlin models?
I did not know that it had to be configured for kotlin, how would it be?
I add some comments:
I have continued fiddling with this problem and found that in build.gradle (project) I have used version 2.0.1 in classpath "com.apollographql.apollo: apollo-gradle-plugin: 2.0.1"
whereas in build.gradle (app) I have used 2.0.2, I have changed the version in build.gradle (project) to 2.0.2.
Also in build.gradle (app) I had written two copies of "apply plugin: 'kotlin-android-extensions'" I have deleted one of them.
By synchronizing the project the problems have remained.
I also deleted:
apollo
     generateKotlinModels.set (true)
}
from the build.gradle (app) module and I synchronized again, but the problem continues.
I am going to continue looking for that this problem occurs, if you can help me in advance thank you very much. !!

Luis.

**Comment by martinbonnin** [comment]
@luisDMosquera if you're using Kotlin codegen, there is no `builder()` method on generated models, mainly because Kotlin has named parameters.

Maybe try

```
apolloClient.query(GetEducacionesQuery())
``` 
?

**Comment by luisDMosquera** [comment]
> @luisDMosquera if you're using Kotlin codegen, there is no `builder()` method on generated models, mainly because Kotlin has named parameters.
> 
> Maybe try
> 
> ```
> apolloClient.query(GetEducacionesQuery())
> ```
> 
> ?

martinbonin, thanks is the solution, !!!!!!

**Comment by luisDMosquera** [comment]
I used the solution of martinbonin:
if you're using Kotlin codegen, there is no builder() method on generated models, mainly because Kotlin has named parameters.

Maybe try

apolloClient.query(GetEducacionesQuery())
