### ISSUE TITLE
Caching partial responses upon errors

### ISSUE THREAD

**Issue by podarsmarty** [apollographql/apollo-android#2280]
**Summary**
Incorrect caching behavior with errors.

**Description**
I think this issue is super similar to https://github.com/apollographql/apollo-android/issues/2202 with the same root cause. I am utilizing CACHE_FIRST to hit my api with an aliased request in order to hit the same api twice with different request params. If one of these requests succeeds but the other one results in a 500 error both data and errors are populated correctly. However, this partial data response is cached as the total response with no indication of the error. If/when a retry is triggered we will now fetch the partial response from the cache.

I would expect the partial response to not be stored in the cache, or that this partial response due to an error is stored with the error and logic results in it being a cache miss. Not entirely convinced that caching an error response and returning it should be expected behavior.

**Version**
1.45

**Comment by sav007** [comment]
So just to clarify, when you hit network you get partial data along with the GraphQL errors in the response, something similar to this:
```
{
  "data": {
     "query" : {
       .....
     }
  },
  "errors": [
    {
      "message": null,
      "locations": null,
      "code":"userNotFound",
      "path":"loginWithPassword"
    }
  ]
}
```
And you don't want to store partial data into the cache?

**Comment by podarsmarty** [comment]
@sav007 yup that is correct
