### ISSUE TITLE
Application interceptor only created once

### ISSUE THREAD

**Issue by juliafu1** [apollographql/apollo-android#2285]
**Is your feature request related to a problem? Please describe.**
I created a custom interceptor like this: 

```kotlin
class OperationRegistryInterceptor(private val logger: ApolloLogger) : ApolloInterceptor {
    @Volatile
    private var disposed = false

    override fun interceptAsync(
        originalRequest: InterceptorRequest,
        chain: ApolloInterceptorChain,
        dispatcher: Executor,
        callBack: ApolloInterceptor.CallBack
    ) {
        ...
        chain.proceedAsync(newRequest, dispatcher, object : ApolloInterceptor.CallBack {
            override fun onResponse(response: InterceptorResponse) {
                if (disposed) return
                callBack.onResponse(response)
                callBack.onCompleted()
            }
       ...
        })
    }

    override fun dispose() {
        disposed = true
    }
}
```

Then I created this interceptor when creating ApolloClient:
We have one ApolloClient for the whole app. 

```kotlin
fun apolloClient(): ApolloClient {
        return with(ApolloClient.builder()) {
            addApplicationInterceptor(OperationRegistryInterceptor(logger))
            ...
            build()
}
```

We have a use case that we send requests when user drags a map. When user moves the map to a new location, we need to cancel the old request and issue a new request with new location data. Thus we need to call `dispose()`manually in the code. 

For this OperationRegistryInterceptor, I found that `disposed` is set to be true for the first request. Then the following requests do not come back with any data because there seems to be no way that this is reset to be false. 

I checked the build-in interceptors such as ApolloServerInterceptor. All of them are created as new objects in prepareInterceptorChain() of RealApolloCall thus when a new request is issued, disposed is set to be false.

I think the ideal way to solve this is to be able to create a new object of OperationRegistryInterceptor when there is a new request, the same way as the built-in interceptors. I did not see a way to do this cleanly.

**Describe the solution you'd like**
Can the ApplicationInterceptor behave the same as build-in interceptors? Basically a new object is created per request.

**Comment by martinbonnin** [comment]
I guess there should be a `apolloInterceptorFactories` parameter to `ApolloClient` ?

```
interface ApolloInterceptorFactory {
  fun newInterceptor(): ApolloInterceptor
}

  ApolloClient(HttpUrl serverUrl,
      Call.Factory httpCallFactory,
      ...
      List<ApolloInterceptor> applicationInterceptors,
      List<ApolloInterceptorFactory> applicationInterceptorsFactories,
      ...
```

**Comment by juliafu1** [comment]
Yeah having `ApolloInterceptorFactory` would be helpful.
