### ISSUE TITLE
Code generation takes forever for some mutations

### ISSUE THREAD

**Issue by lriebandt** [apollographql/apollo-android#2286]
**Summary**
Code generation for some of my schema's mutation takes forever with the new code generator, but works with npm code generator.

**Description**
I upgraded from 1.0.0 to 2.0.3.
The generation for my mutations worked fine with version 1.0.0 and the old npm code generator.
But when using versions 1.2.0 and above, the generateMainServiceApolloSources task won't finish. 
I figured out that code generation of my *UpdateInput classes causes this issue. 

You can find the schema and a mutation in this repo:
https://github.com/lriebandt/github-graphql-sample

**Version**
1.2.0 to 2.0.3

Thank's for your help

**Comment by sav007** [comment]
I guess it was fixed as part of https://github.com/apollographql/apollo-android/pull/2257

Could you please check the latest snapshot version?

@martinbonnin do you know if above PR was released?

**Comment by lriebandt** [comment]
Hi @sav007  
I already saw #2257, but thought it was released with 2.0.3.
But it wasn't:
https://github.com/apollographql/apollo-android/tree/v2.0.3

When using 2.0.3-SNAPSHOT the code generation works just fine.

Thank you for your help!

**Comment by martinbonnin** [comment]
This will be in 2.0.4 that I'm planning to release soon.
