### ISSUE TITLE
Schema download issue

### ISSUE THREAD

**Issue by sevaktahmazyan** [apollographql/apollo-android#2287]
I create task to download schema when gradle is build. 

```
task downloadSchem (type: Exec) {
    commandLine './gradlew', "downloadApolloSchema -Pcom.apollographql.apollo.endpoint=myurl -Pcom.apollographql.apollo.schema=my_path/schema.json"
}
```
But after executing this task I got below error

Task ''downloadApolloSchema' '-Pcom.apollographql.apollo.endpoint=myurl -Pcom.apollographql.apollo.schema=my_path/schema.json'' not found in root project 'android-XXX'.

**Comment by martinbonnin** [comment]
Do you apply the apollo plugin in the rootProject ? You might have to specify the module:

```
:module:downloadApolloSchema
```

But if you're doing this from your gradle scripts, you can use the Task directly:

```kotlin
tasks.register("downloadSchema", ApolloDownloadSchemaTask::class.java) {
    endpointUrl.set("https://")
    schemaFilePath.set("src/main/graphql/com/example/schema.json")
}
```

**Comment by sevaktahmazyan** [comment]
What is 'ApolloDownloadSchemaTask' class. It is not not available in gradle script. Or I must create that class. If it is so from which Apollo class I must extend it. 
Note: The apollo client works fine in project. I have properly configure it. I just want automatically download schema.json. 

Do you have some example for that?

**Comment by martinbonnin** [comment]
> What is 'ApolloDownloadSchemaTask' class. It is not not available in gradle script.

`ApolloDownloadSchemaTask` is the task that takes care of executing the introspection query and saving the result to a `schema.json` file. It should be available from your Gradle scripts. Maybe try with the fully qualified name:

```
tasks.register("downloadSchema", com.apollographql.apollo.gradle.internal.ApolloDownloadSchemaTask::class.java) {
    endpointUrl.set("https://")
    schemaFilePath.set("src/main/graphql/com/example/schema.json")
}
```

**Comment by sevaktahmazyan** [comment]
There are no any 'internal' package only this two
<img width="984" alt="Screen Shot 2020-05-21 at 2 51 38 PM" src="https://user-images.githubusercontent.com/20276983/82552227-c4e2db00-9b72-11ea-8ab3-02bea4c70aa5.png">

and both with this classes
<img width="1070" alt="Screen Shot 2020-05-21 at 2 51 51 PM" src="https://user-images.githubusercontent.com/20276983/82552291-d9bf6e80-9b72-11ea-852a-877fbab80e2a.png">

**Comment by martinbonnin** [comment]
What version of `apollo-android` are you using ? The `ApolloDownloadSchemaTask` is only available with version 1.3+.

**Comment by sevaktahmazyan** [comment]
<img width="501" alt="Screen Shot 2020-05-21 at 4 08 40 PM" src="https://user-images.githubusercontent.com/20276983/82557749-6111df80-9b7d-11ea-8119-59118091a05f.png">

**Comment by martinbonnin** [comment]
`AndroidTaskConfiguratorFactory` was a class from the old Gradle plugin, it shouldn't be there in 2.0.3 anymore. So I guess something is wrong in your IDE/Gradle configuration. 

`com.apollographql.apollo` is the new plugin ID so that part looks good. Do you have the old plugin dependency in your `buildscript {}` block or `buildSrc/build.gradle.kts` maybe ?

A example of how it should work: https://github.com/martinbonnin/github-graphql-sample/blob/f9ac731b61208daf1558fd0328069896b2f01f42/app/build.gradle.kts#L92

```
> git clone https://github.com/martinbonnin/github-graphql-sample
> cd github-graphql-sample/
> git checkout f9ac731b61208daf1558fd0328069896b2f01f42
> echo "ext.githubToken='YOUR_GITHUB_TOKEN'" > app/github.properties
>  ./gradlew downloadSchema
```

**Comment by martinbonnin** [comment]
I'm closing this issue, please leave a message if you want me to reopen it.

**Comment by sevaktahmazyan** [comment]
Sorry for late answer.
I checked your example. But I can not register below task

`tasks.register("downloadSchema", com.apollographql.apollo.gradle.internal.ApolloDownloadSchemaTask::class.java) {
    endpointUrl.set("https://api.github.com/graphql")
    schemaFilePath.set("src/main/graphql/net/mbonnin/githubgraphqlsample/schema.json")
    headers.set(mapOf("Authorization" to "Bearer ${githubToken()}"))
}`

Below Is my gradle configuration apollo plugin updated as well.

<img width="559" alt="Screen Shot 2020-07-09 at 17 54 55" src="https://user-images.githubusercontent.com/20276983/87048870-52ef4f80-c20d-11ea-9363-894804f014ca.png">

and below what is only available

<img width="692" alt="Screen Shot 2020-07-09 at 17 47 03" src="https://user-images.githubusercontent.com/20276983/87048947-6bf80080-c20d-11ea-8914-30d4d5e03703.png">

**Comment by martinbonnin** [comment]
A sample is there: https://github.com/martinbonnin/apollo-android-samples/blob/8320bb095671d8d06dc5c78306e9b31cb5e4a0c7/download-schema-task/build.gradle#L10:

```
tasks.register("downloadSchema", com.apollographql.apollo.gradle.internal.ApolloDownloadSchemaTask) {
    endpoint = "https://apollo-fullstack-tutorial.herokuapp.com/"
    schemaRelativeToProject = "src/main/graphql/net/sample/schema.json"
}
```

But if you're mainly looking for a way to download the schema.json from the command-line, I recommend you use the task that is registered by the plugin automatically:

```
./gradlew downloadApolloSchema --endpoint "https://apollo-fullstack-tutorial.herokuapp.com/" --schema src/main/graphql/net/sample/schema.json
```

**Comment by sevaktahmazyan** [comment]
Yes I check the sample but "com.apollographql.apollo.gradle.internal.ApolloDownloadSchemaTask"  not found you can see in above picture that  after "com.apollographql.apollo" path only available ".api" package ".gradle" does not available

**Comment by sevaktahmazyan** [comment]
Thanks after moving this part to top-level gradle file I can dowload the schema.json file.

**Comment by teodorpenkov** [comment]
I've implemented something similar but stumbled upon some weird gradle issue 
`java.lang.NoClassDefFoundError: Could not initialize class okhttp3.internal.Util`

I've got this code

```
tasks.register("downloadSchema", com.apollographql.apollo.gradle.internal.ApolloDownloadSchemaTask) {
  it.endpoint = "http://localhost:3000/graph/token"
  it.schemaRelativeToProject = "app/src/main/graphql/baba.json"
  it.setHeader(["Authorization: Bearer${obtainToken()}".toString()])
}
```

I've tried with the latest gradle plugin version - 6.8.3 and still no success, any suggestions?

**Comment by martinbonnin** [comment]
@teodorpenkov that sounds like Gradle has 2 different versions of OkHttp in the classpath. If you're using `buildSrc`, make sure to put `com.apollographql.apollo:apollo-gradle-plugin` in the `buildSrc` dependencies so that dependency resolution can happen. If not, try `./gradlew buildEnvironment` to check where the two OkHttp versions might come from.

**Comment by teodorpenkov** [comment]
@martinbonnin that's what I thought too but unfortunately there is only 1 version :( 
The funny thing is I tried with a previous version of gradle and it worked fine, but then compose didn't work 🤷 

Have you tried Android studio that includes the beta of jetpack compose + apollo's schema introspection task? 
Gradle version - 6.8.2
Android Gradle Plugin - 7.0.0-alpha10

I also found this issue here which seems related https://github.com/JetBrains/gradle-intellij-plugin/issues/522

**Comment by martinbonnin** [comment]
> unfortunately there is only 1 version

Yeaaa, `buildEnvironment` might be wrong sometimes (see https://github.com/gradle/gradle/issues/8301). Also, there are 2 build environments: `./gradlew buildEnvironment` and `./gradlew :app:buildEnvironment`. 
My guess is that your root project has okio `1.x` (most likely `1.13.0` ?). And this get loaded in the build classpath before the one from the apollo plugin (requires 2.x something)? 

If that's still happening, can you upload a small reproducer somewhere?

**Comment by teodorpenkov** [comment]
https://github.com/teodorpenkov/BuildEnvironmentIssue

**Comment by martinbonnin** [comment]
@teodorpenkov this should fix it: https://github.com/martinbonnin/BuildEnvironmentIssue/commit/af3ee390635ceb049835a1244b16e33d35344605

**Comment by teodorpenkov** [comment]
totally fixed it, thanks :)

**Comment by teodorpenkov** [comment]
Any ideas why does this happen? It's working on previous gradle version 🤷

**Comment by martinbonnin** [comment]
@teodorpenkov it's linked to how Gradle deals with classloaders. I'm not 100% sure how that works. There's some info in the links below:

* https://gradle-community.slack.com/archives/CA745PZHN/p1616102285005900
* https://github.com/gradle/gradle/issues/8301#issuecomment-503198340
* https://dev.to/autonomousapps/a-crash-course-in-classpaths-build-l08

**Comment by Drjacky** [comment]
> java.lang.NullPointerException (no error message)

This works:
```groovy
./gradlew :common:models:downloadApolloSchema --endpoint='https://blah/etc' --schema=`pwd`/common/models/src/main/graphql/com/example/schema.graphqls
```

But this doesn't:
common -> models -> build.gradle.kts:
```kotlin
plugins {
...
    id("com.apollographql.apollo3").version("3.2.1")
}

apollo {
    packageName.set("com.example")
    generateKotlinModels.set(true)
}

tasks.register("downloadSchema", com.apollographql.apollo3.gradle.internal.ApolloDownloadSchemaTask::class.java) {
    endpoint.set("https://blah/etc")
    schema.set("common/models/src/main/graphql/com/example/schema.graphqls")
}
```

**Comment by BoD** [comment]
Hi @Drjacky!

If you want to set the endpoint url and schema location, you can instead configure the task by declaring an `introspection` block as show [here](https://www.apollographql.com/docs/kotlin/advanced/plugin-configuration#downloading-a-schema).

**Comment by sam43** [comment]
> tasks.register("downloadSchema", com.apollographql.apollo.gradle.internal.ApolloDownloadSchemaTask::class.java) {
>     endpointUrl.set("https://")
>     schemaFilePath.set("src/main/graphql/com/example/schema.json")
> }

Is it available for apollo v3 (3.7.1) yet? If yes I would like have some reference. the `ApolloDownloadSchemaTask` class is unresolved here. @martinbonnin

**Comment by martinbonnin** [comment]
@sam43 it is still there but the package named changed to `com.apollographql.apollo3.gradle.internal`:

```
com.apollographql.apollo3.gradle.internal. ApolloDownloadSchemaTask
```

Because this is an internal class, I'd recommend using the `introspection {}` block. You can read more about it there: 
 https://www.apollographql.com/docs/kotlin/advanced/plugin-configuration/#downloading-a-schema

**Comment by sam43** [comment]
Thanks @martinbonnin. And How to add auth header into the task while downloading the schema using CLI.

**Comment by martinbonnin** [comment]
The `introspection {}` block has a header property:

```kotlin
apollo {
  service("starwars") {
    packageName.set("com.starwars")

    // This will create a downloadStarwarsApolloSchemaFromIntrospection task
    introspection {
      endpointUrl.set("https://your.domain/graphql/endpoint")
      // The path is interpreted relative to the current project here, no need to prepend 'app'
      schemaFile.set(file("src/main/graphql/com/example/schema.graphqls"))
      headers.put("Authorization", "Bearer $token")
    }
  }
}
```

**Comment by AdieOlami** [comment]
@martinbonnin the introspection does not download for me.

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-parcelize'
    id 'com.google.dagger.hilt.android'
    id 'kotlin-kapt'
    id 'com.apollographql.apollo3'
}

dependencies {
    // Apollo
    implementation "com.apollographql.apollo3:apollo-runtime:$apollo_version"
    implementation "com.apollographql.apollo3:apollo-normalized-cache-sqlite:$apollo_version"
}

apollo {
    service("service") {
        packageName.set("co.xx.xy")

        introspection {
            endpointUrl.set("https://api.com/query")
            schemaFile.set(file("src/main/graphql/schema.graphqls"))
//            // headers.put("key","val")
        }
    }
}

Then my Project level build.gradle

buildscript {
    ext {
        apollo_version = '3.8.0'
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '7.4.2' apply false
    id 'com.android.library' version '7.4.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.10' apply false
    id 'com.apollographql.apollo3' version "$apollo_version" apply false
}

My download does not work at all.

I have tried registering a task but nothing still
