### ISSUE TITLE
Drop Streaming Support

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#229]
This Issue is for discussion of dropping streaming support. Currently we do not use streaming when fragments are in query.  The proposal is to not use streaming parsing anywhere. The advantage is a far simpler cache implementation. When running performance testings at NYTimes, I was able to download 12 1.7mb queries without spiking more than 25mb of data.

👍 means you would like to drop it, 👎 means you want to keep it

**Comment by felipecsl** [comment]
If we already can't do streaming when using fragments (which should be the case most of the time), then the benefit/complexity ratio sounds really poor. I'd recommend 🔥  it

**Comment by digitalbuddha** [comment]
I'm with you, I thought fragments would be much more rare but it seems like you can't write anything without having a fragment in it.

**Comment by martijnwalraven** [comment]
Hmmm, it sounds like it may not be worth the complexity. If we still feel it is important, there may be ways of doing streaming even with fragments though, with some changes to the execution model I've been working on for the iOS client. (Basically, we now rely on a runtime representation of the query, so we can collect all the fields from fragments before starting the parsing.)
