### ISSUE TITLE
Using the NETWORK_ONLY ApolloResponseFetcher writes to cache

### ISSUE THREAD

**Issue by sridhar-vadlamani-ck** [apollographql/apollo-android#2291]
**Summary**
I was hoping this is the parallel to iOS's `.fetchIgnoringCacheCompletely` policy. Is there any way I can prevent writes to the db? For our use-case, we only want to write certain queries to disk. Pretty certain writing to cache when not required is a performance hit.
**Version**
2.0.3

**Comment by martinbonnin** [comment]
You can use [ApolloCacheHeaders.DO_NOT_STORE](https://github.com/apollographql/apollo-android/blob/7261de18d3f11879f74ae268dca935c886913191/apollo-normalized-cache-api/src/commonMain/kotlin/com/apollographql/apollo/cache/ApolloCacheHeaders.kt#L12) to skip writing to the cache.

**Comment by sridhar-vadlamani-ck** [comment]
Where does that cache header go? Could you point to any documentation which mentions that please?

**Comment by martinbonnin** [comment]
I'm not sure there is documentation for that at the moment, that's definitely something that can be  improved. In the meantime, you can use it like this:

```
val query = apollo.query(query)
    .cacheHeaders(CacheHeaders.builder()
        .addHeader(ApolloCacheHeaders.DO_NOT_STORE, "true")
        .build()
    )
```

**Comment by sridhar-vadlamani-ck** [comment]
Thanks!
