### ISSUE TITLE
Use of absolute string path breaks generateSources task remote cacheability

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#2293]
**Summary**

Input property [rootFolders](https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/internal/ApolloGenerateSourcesTask.kt#L84) is referenced as an [absolute path string ](https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/internal/ApolloPlugin.kt#L129).

If you use a gradle remote cache absolute paths may differ based on the machine used for the build.

**Description**
I believe we could change this to a `ConfigurableFileCollection` similar to [graphqlFiles](https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/internal/ApolloGenerateSourcesTask.kt#L78) fix the issue

**Version**
1.4.5, but pretty sure this is still on master.

**Comment by martinbonnin** [comment]
Good catch, thank! The reason `rootFolders` is a `ListProperty<String>` and not a `List<DirectoryProperty>` is that, in theory at least, the `src/main/graphql` folder can contain something else that `.graphql` files and we want the task to stay `UP-TO-DATE` even if an unrelated file changes. 
[This PR](https://github.com/apollographql/apollo-android/pull/2294) changes the paths so they are relative and the task can be relocable
