### ISSUE TITLE
Facing issue in network policy cache-and-network graphql

### ISSUE THREAD

**Issue by akshaytaywade** [apollographql/apollo-android#2297]
In fetch policy cache-and-network' it always throws esult--> {"loading":true,"networkStatus":1,"stale":true} I want to read the data from cache if data is already available in cache if not then call network operation. below is my code apollo.create({ link: httpLink.create({uri: 'https://o5x5jzoo7z.sse.https

 }), cache: new InMemoryCache(), defaultOptions: { watchQuery: { fetchPolicy: 'cache-and-network', errorPolicy: 'all', }, query: { fetchPolicy: 'network-only', errorPolicy: 'all', }, // mutate: { // errorPolicy: 'all' // } } }); ngOnInit() { this.apollo .watchQuery({ query: gql{ rates(currency: "USD") { currency rate } } }) .valueChanges.subscribe(result => { console.log('result-->',JSON.stringify(result)); console.log('result-->',result.data['rates']); // this.rates = result.data; this.rates = result.data && result.data['rates']; this.loading = result.loading; this.error = result['error']; }); } }

**Comment by martinbonnin** [comment]
@akshaytaywade that sounds like an issue for https://github.com/apollographql/apollo-client, not apollo-android.

**Comment by martinbonnin** [comment]
I'm closing this issue, please leave a comment if you want me to reopen.
