### ISSUE TITLE
Need of Realm for Normalize Cache

### ISSUE THREAD

**Issue by ADI-tya-P** [apollographql/apollo-android#2303]
**SQLlite is too slow for queries**.
It would be such as great HTTP request but weak in Local data Needs.
A needed Features for Android Developers

**Comment by martinbonnin** [comment]
Hi! Thanks for the suggestion! I'm curious what led you to the conclusion that SQLite was too slow. Do you have any numbers you can share ? 

If needed, a realm normalized cache could be done by implementing the `NormalizedCache` API like it is done for the sqlite one.

**Comment by tasomaniac** [comment]
I would also be against this to make it part of the library. Also because SQL operations are done in background thread, this should not be a problem. Also as @martinbonnin mention, it can be potentially implemented by users if it is really needed
