### ISSUE TITLE
ConcurrentModificationException In RealSubscriptionManager.onTransportConnected() 

### ISSUE THREAD

**Issue by Saravana-Gunaseelan** [apollographql/apollo-android#2310]
**Summary**
There seems to be a ConcurrentModificationException in the onTransportConnected() present in RealSubscriptionManager class.

**Description**

```
01-30 18:00:02.135  6970 11145 E AndroidRuntime: java.util.ConcurrentModificationException
01-30 18:00:02.135  6970 11145 E AndroidRuntime: 	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
01-30 18:00:02.135  6970 11145 E AndroidRuntime: 	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
01-30 18:00:02.135  6970 11145 E AndroidRuntime: 	at com.apollographql.apollo.internal.subscription.RealSubscriptionManager.onTransportConnected(RealSubscriptionManager.java:261)
01-30 18:00:02.135  6970 11145 E AndroidRuntime: 	at com.apollographql.apollo.internal.subscription.RealSubscriptionManager$SubscriptionTransportCallback$1.run(RealSubscriptionManager.java:519)
01-30 18:00:02.135  6970 11145 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-30 18:00:02.135  6970 11145 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-30 18:00:02.135  6970 11145 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)`
```

**Version**

~~apollo-runtime:2.0.3~~ apollo-runtime:1.2.3

**Comment by martinbonnin** [comment]
If you can reproduce, can you set a breakpoint when the exception happens? It *looks* like this happens on an access to [RealSubscriptionManager.subscriptions](https://github.com/apollographql/apollo-android/blob/3e122b4ff44fff3109911dd24177aeddce5d3426/apollo-runtime/src/main/java/com/apollographql/apollo/internal/subscription/RealSubscriptionManager.java#L256) but the line numbers do not really match so I'm not sure. Also `subscriptions` accesses are synchronized so this should *theorically* not happen.

If you ever manage to hook a debugger in this exception, it would be interesting to know if other threads are also accessing RealSubscriptionManager at the same time.

**Comment by Saravana-Gunaseelan** [comment]
Sorry my mistake the error logs are from an older version apollo-runtime:1.2.3. 

In the latest version 2.0.3, this occurs in line 268 in RealSubscriptionManager.

The `subscriptions` are accessed outside the synchronized block.

<img width="666" alt="Screen Shot 2020-06-04 at 9 07 48 AM" src="https://user-images.githubusercontent.com/53452295/83767200-f6fc3e80-a642-11ea-82fd-0b77d3cf5f2a.png">
