### ISSUE TITLE
Custom Types not getting generated even though they have been added in build.gradle

### ISSUE THREAD

**Issue by kesh-1139** [apollographql/apollo-android#2314]
I have defined my custom type in `build.gradle` as shown below:

```
apollo {
        generateKotlinModels.set(true) // or false for Java models
        customTypeMapping = [
                "PersonDetail": "com.task.databasepoc.models.Person"
        ]
    }
```
My Schema also contains the field name `PersonDetail`, I have attached my part of schema

```
 "kind": "OBJECT",
          "name": "PersonDetail",
          "description": null,
```
I have tried deleting `Custom Types` file and rebuilding again, I have also tried deleting build folder and recreating again. Nothing is working.

Custom Type consists only `ID` and my types are not coming.

Can you please let me know what mistake am I making?

I have added following dependencies and using kotlin:
```
implementation 'com.apollographql.apollo:apollo-runtime:2.0.3'
    implementation 'com.apollographql.apollo:apollo-android-support:2.0.3'
    implementation 'com.apollographql.apollo:apollo-coroutines-support:2.0.3'
```
I am using below classpath:

```
classpath "com.apollographql.apollo:apollo-gradle-plugin:2.0.3"
```
I have defined the custom type adapter as shown below:

```
object TypeAdapter : CustomTypeAdapter<Person> {
        override fun decode(value: CustomTypeValue<*>): Person {
            return value as Person
        }

        override fun encode(value: Person): CustomTypeValue<*> {
            return CustomTypeValue.fromRawValue(value)
        }


    }
```
I am trying to build the apolloclient as shown below:

```
 return ApolloClient.builder()
            .serverUrl("serverUrl")
            .okHttpClient(okHttpClient)
            //.addCustomTypeAdapter(CustomType, TypeAdapter)
            .build()
```
I am not able to find the custom scalar CustomType.PersonDetail.

Please help me with this as I am stuck.

**Comment by martinbonnin** [comment]
Hi and thanks for reaching out! Can you try to run your build with `--no-build-cache`? This sounds awfully like https://github.com/apollographql/apollo-android/issues/2043

**Comment by kesh-1139** [comment]
@martinbonnin  I tried running this command
```
rm -rf $HOME/.gradle/caches/
```
and rebuilding again. But still same issue.

**Comment by martinbonnin** [comment]
Thanks for the quick response. 

Looking at your schema:
```
          "kind": "OBJECT",
          "name": "PersonDetail",
          "description": null,
```

To describe a scalar type, it should be this instead:

```
          "kind": "SCALAR",
          "name": "PersonDetail",
          "description": null,
```

Usually, regular objects are consumed with the auto-generated models. Is there a reason you want to  map them to another type ?

**Comment by kesh-1139** [comment]
@martinbonnin 
Actually my requirement I need to store the response locally I am using room database for the same.
Now I have to convert the response received from GraphQL to Room entity objects.
1. Is there any direct way to use this?
2. Instead of generating models from Graphql can I use models that I have created for Room Database?

Since I have to store the data in Room Database I am trying to convert all required to fields to the type of model that I have created for Room Database.

Please let me know if you have any queries?

**Comment by martinbonnin** [comment]
It's not possible to generate Room annotated models with Apollo-Android. You can however map the generated models to your Room models.

Another path you can consider is using the [Apollo cache](https://www.apollographql.com/docs/android/essentials/caching/) to store your objects locally.

**Comment by kesh-1139** [comment]
@martinbonnin 
Thanks for that link will have a look.
I am trying to map firstName which is defined as shown below in schema

```
{
              "name": "firstName",
              "description": null,
              "args": [],
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
                }
              }
```
and by mapping in build.gradle is

```
customTypeMapping = [
                "firstName": "com.task.databasepoc.models.Person"
        ]
```
Even now I am not seeing custom type, can you please tell me the issue with schema and what needs to be changed for this. As you can see type is SCALAR.

**Comment by martinbonnin** [comment]
`firstName` here is a builtin `String` scalar type. `customTypeMapping` is for custom scalar types.
Mapping a `firstName` to anything else that a `String` isn't very useful as it cannot really get any simpler than that.

**Comment by kesh-1139** [comment]
@martinbonnin 
Also can you please provide any sample links for writing adhoc-mappers, it will be very much helpful.

**Comment by martinbonnin** [comment]
You can take a look at this repository: https://github.com/BoD/apollo-graphql-android-sample/blob/master/app/src/main/kotlin/com/example/graphqlsample/ui/repository/list/RepositoryListViewModel.kt#L23

It transforms a generated model to a UI model named `SimpleRepositoryUiModel`

**Comment by martinbonnin** [comment]
I'm closing this issue, please leave a message if you want me to reopen it.
