### ISSUE TITLE
Outdated start-up documentation for apollo-android

### ISSUE THREAD

**Issue by evantaurusta** [apollographql/apollo-android#2317]
**Summary**
So I'm trying to include `apollo-android` as a client library for my kotlin based project. However, the `gradlew` task given in the docs doesn't recognize "module" in my project. Even though, the docs clearly state: https://www.apollographql.com/docs/android/essentials/get-started/#downloading-a-schemajson-file

**Description**
I have to remove the `:module` path from the gradlew. cli command before i'm able to download my schema.json. It would be great if the doc can be updated as well.

**Version**
apollo-gradle-plugin:2.1.0
apollo-run-time:2.1.0

**Comment by martinbonnin** [comment]
@evantaurusta can you check https://www.apollographql.com/docs/android/essentials/get-started/#downloading-a-schemajson-file ? It should be good now.

**Comment by evantaurusta** [comment]
looks great! I think we can close this Issue now
