### ISSUE TITLE
Make ApolloAutoPersistedQueryInterceptor configurable

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#2330]
**Is your feature request related to a problem? Please describe.**

The current implementation of `ApolloAutoPersistedQueryInterceptor` has the expectation that a missing registered query will surface in the graphql errors, however some servers may choose to surface this error through an http status code, such as 400.

For the retry behavior this interceptor is easiest to manage if it is placed near the end of the chain. If one used a standard interceptor to enable this, then it would run before response fetcher interceptors, and the retry logic would trigger these interceptors to run twice.

**Describe the solution you'd like**

Allow a user to specify an override to when building an Apollo client to have a custom interceptor be used for the `ApolloAutoPersistedQueryInterceptor` . This allows users to change behavior if necessary, but still place the interceptor in the proper location for retries.

```
public Builder persistedQueryInterceptor(@NotNull ApolloInterceptor interceptor) {
```

**Comment by BenSchwab** [comment]
Also I am curious as to why Apollo only allows persisted queries and not persisted mutations?

```
if (operation instanceof Query && enableAutoPersistedQueries) {
      interceptors.add(new ApolloAutoPersistedQueryInterceptor(logger, useHttpGetMethodForPersistedQueries));
    }
```
While you couldn't send the mutation as a `get` request, it still seems possible to send the operation id as the body instead of the graphql document to improve performance.

**Comment by martinbonnin** [comment]
@BenSchwab what about a more generic interceptor API:

```kotlin
  /**
   * Returns the default interceptors used by ApolloClient internally to handle cache, 
   * persisted queries, network, etc...
   */
  fun defaultInterceptorFactories(): List<ApolloInterceptorFactory> {
    
  }

  /**
   * Set the interceptor factories to use in this ApolloClient
   * 
   * Note that this will replace all the interceptors, including the default ones so it is the caller
   * responsibility to call `defaultInterceptorFactories()` and keep/replace the needed interceptors
   */
  fun setInterceptorFactories(interceptorFactories: List<ApolloInterceptorFactory>) {

  }
```

About Automatic Persisted Queries and mutations, that sounds like an oversight. I don't see any reason not to allow this.

**Comment by BenSchwab** [comment]
@martinbonnin that sounds good to me 👍

**Comment by martinbonnin** [comment]
I ended up going the initial "specific" route of adding an interceptor just for persisted operation instead of exposing all the interceptors. Mainly because the current interceptors capture a lot of variables in `ApolloClient` and `RealApolloCall` and it would have been a pain to abstract all that. Let me know what you think.
