### ISSUE TITLE
AbstractMethodError exception from RealCacheKeyBuilder

### ISSUE THREAD

**Issue by ahetawal-p** [apollographql/apollo-android#2333]
**Description**
Setting up a query which looks like this :
```
mutation TrackUserActivity($input:TrackEventsInput!) {
  trackEvents(input:$input){
      __typename,
      completed
  }
}
```
And the expect output is something like this
```
{
  "data": {
    "trackEvents": {
      "__typename": "TrackEventsPayload",
      "completed": true
    }
  }
}
```
And my apollo client is setup like this 

```
ApolloClient.builder()
                .serverUrl(url)
                .okHttpClient(okHttpClient)
                .normalizedCache(LruNormalizedCacheFactory(EvictionPolicy.NO_EVICTION), object : CacheKeyResolver() {
                    override fun fromFieldRecordSet(field: ResponseField, recordSet: Map<String, Any>): CacheKey {
                        val id = (recordSet["id"] as? String)
                        return if (id != null) {
                            CacheKey.from(id)
                        } else {
                            CacheKey.NO_KEY
                        }
                    }

                    override fun fromFieldArguments(field: ResponseField, variables: Operation.Variables): CacheKey {
                        return CacheKey.NO_KEY
                    }
                })
```
With the above setup everytime I run it, I am seeing the error below:
![Screen Shot 2020-06-04 at 2 57 17 PM](https://user-images.githubusercontent.com/8919529/83814887-034cbf80-a674-11ea-9631-fd1e91b3bc9d.png)

Any ideas what is wrong with this query.

**Version**
2.1.0

**Comment by tasomaniac** [comment]
Hi, it looks like it is because of a bug resulting from our Kotlin conversion. To avoid it, you could go back to 1.4.x version. We will try our best to include a fix for this in the next version.

**Comment by ahetawal-p** [comment]
Thanks @tasomaniac, going back 1.4 now would be hard for us, as we have build lot of new stuff on top of 2.0 version. 
It would be super helpful if you could prioritize this for the next upcoming release.

**Comment by martinbonnin** [comment]
@ahetawal-p can you try with version 2.2.0 ?

**Comment by ahetawal-p** [comment]
Thanks @martinbonnin. I just tried and it resolved my issue. Thank you so much for the quick fix. ❤️
