### ISSUE TITLE
Subscription Link is broken

### ISSUE THREAD

**Issue by PritishSawant** [apollographql/apollo-android#2334]
The subscription link is broken for Apollo docs

**Comment by martinbonnin** [comment]
Sorry about that, the documentation contained `TODO` and removed as part of [reorganizing the docs](https://github.com/apollographql/apollo-android/pull/2292). I removed it in #2340 and will add proper documentation. You can follow https://github.com/apollographql/apollo-android/issues/1772 for updates.
