### ISSUE TITLE
Count 'n' must be non-negative, but was -2.

### ISSUE THREAD

**Issue by wooyukit** [apollographql/apollo-android#2338]
**Description**
After upgraded the apollo version from 1.0 to 2.1, built the app and it showed "Count 'n' must be non-negative, but was -2." error message. It is related to `GraphQLDocumentSourceBuilder.kt` line 93 string with indents problem.

**Comment by wooyukit** [comment]
I don't know which query caused the issue. May be I can give you one sample.

```
query ArticleListQuery($name: String!, $limit: Int!, $offset: Int!, $excludeEntityIds: [String]!) {
    queue(filter: {name:$name}){
        entityId
        entityUuid
        name
        items(limit: $limit, offset: $offset, exclude: {entityIds: $excludeEntityIds}) {
            ... on Article {
                ...ArticleLite
            }
            ... on Video {
                ...VideoLite
            }
        }
    }
}
```

**Comment by sav007** [comment]
hi @wooyukit sorry for the delay, but we couldn't reproduce this issue on provided sample.
Is it still a valid issue?

**Comment by sav007** [comment]
I put a potential fix, but TBH if you see this issue looks like your GraphQL query is no valid.

**Comment by martinbonnin** [comment]
There is a [workaround for this](https://github.com/apollographql/apollo-android/commit/6c7e785551924916a1bc9de3403975920ac23222) in 2.x and 3.x uses a [SDLWriter](https://github.com/apollographql/apollo-android/blob/d77b73f6f387ab474045f0db3c568d251ef55932/apollo-ast/src/main/kotlin/com/apollographql/apollo3/ast/SDLWriter.kt#L9) to avoid this.
