### ISSUE TITLE
Apollo RxJava3 support not found

### ISSUE THREAD

**Issue by sh3lan93** [apollographql/apollo-android#2346]
**Question.**
RxJava3 dependency not found, when trying to add rxjava3 dependency `com.apollographql.apollo:apollo-rx3-support:x.y.z` failed to resolve the dependency.
https://bintray.com/apollographql/android/apollo-rx3-support/_latestVersion (404 not found)

**Comment by martinbonnin** [comment]
@sh3lan93 sorry about that, the version is not released yet. It'll be in version 2.1.1, I'll try to release it shortly. In the meantime, you can test using the snapshots: 

```
  repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
  }
```
(see [the README](https://github.com/apollographql/apollo-android#releases)) for more details.

**Comment by sh3lan93** [comment]
@martinbonnin I have added the maven url to module build.gradle and still can't resolve the dependency

**Comment by martinbonnin** [comment]
Did you change the version to `2.1.1-SNAPSHOT` ? The jar is available there: https://oss.sonatype.org/service/local/repositories/snapshots/content/com/apollographql/apollo/apollo-rx3-support/2.1.1-SNAPSHOT/apollo-rx3-support-2.1.1-20200609.094526-18.jar

**Comment by sh3lan93** [comment]
@martinbonnin yes this fix my issue 🚀 but is there any stable version for this rather than using snapshot one?

**Comment by martinbonnin** [comment]
There should be a 2.1.1 soon :). You can watch this repo to be notified of releases. I'm hoping to make one today or tomorrow.
