### ISSUE TITLE
Why WebSocketSubscriptionTransport doesn't have a public constructor? 

### ISSUE THREAD

**Issue by k-misztal** [apollographql/apollo-android#2347]
**Why `WebSocketSubscriptionTransport` doesn't have a public constructor?**

I want to implement my own `SubscriptionTransport.Factory` to connect to GraphQL subscriptions. I need it because the URL I connect to may change dynamically and existing implementation is not enough for me. Being more precise I need to add a query parameter to the subscription URL, which is dynamic. 

Implementation of `WebSocketSubscriptionTransport.Factory` is final, so I can't override it. The only options I have is to either use reflection (which is ugly but that's what I'm gonna do to invoke package-private constructor) or implement my own `SubscriptionTransport` (which would be pretty stupid). 

Is there any particular reason why you didn't make the constructor public? If not, can you make it public in upcoming releases?

**Comment by martinbonnin** [comment]
That sounds reasonable to me. Would you be willing to open a pull request for this?

**Comment by k-misztal** [comment]
Sure. That's going to be the tiniest contribution in the history of open source 🤣

**Comment by martinbonnin** [comment]
small streams make big rivers :)
