### ISSUE TITLE
Migrating from 1.0.0 to 2.1.0 ignores @include annotation

### ISSUE THREAD

**Issue by GauravP123** [apollographql/apollo-android#2351]
**Summary**
I am upgrading apollo SDK from 1.0.0 to 2.1.0. In the latest version generated model ignores the @include annotation form the fragment.

**Version**
`2.1.0`

**Description**
Query

```
query ProductDetailsQuery($frontPage : Boolean = false,$id: int) {
  details(id: $id) {
    ... on Product @include(if: $frontPage) {
      size
      name
      link
    }
    id
    description
}
```

We are using the above query on the Home screen for various scenarios.
1st scenario: we are passing `frontPage=true` 
2nd scenario: we are sending `frontPage=false`

The previous version(1.0.0) generates the following model 

` final @Nullable Integer size;`

But after migration, it's generating 

` final Integer size;`

Because of this in the 2nd scenario we are getting the following exception `cause: java.lang.IllegalStateException: corrupted response reader, expected nonnull value for size`. 

it was working fine with `1.0.0`.

Any changes in a model generation logic when we use `@include`?

**Comment by GauravP123** [comment]
Any plan to release this fix?

**Comment by martinbonnin** [comment]
Releases typically happen every couple of weeks. If you want to try before the next one, you can use the snapshots. See [the releases section of the README](https://github.com/apollographql/apollo-android#releases) for more details on how to use SNAPSHOTS.

**Comment by GauravP123** [comment]
Hi,
Have we changed a model generation logic?
`v2.2.1` creates the following class

      public interface Product {
    @NotNull String __typename();

    @NotNull String description();

    ResponseFieldMarshaller marshaller();

      final AsProduct.Mapper asProductFieldMapper = new AsProduct.Mapper();

      final AsProduct1.Mapper asProduct1FieldMapper = new AsProduct1.Mapper();
    
  }

to access, size have to do
`((ProductDetailsQuery.AsProduct)ProductDetailsQuery.Data.product()).size()`

and size is 
`    final int size;
`
its not `@Nullable`

 why are we creating 2 FieldMapper `AsProduct,AsProduct1`

Whereas on the older version 1.0.0
`ProductDetailsQuery.Data.product().size`
and size is nullable

**Comment by GauravP123** [comment]
@martinbonnin @sav007 may I know what is the best practice here

**Comment by martinbonnin** [comment]
@GauravP123 are you still using that same query?

```graphql
query ProductDetailsQuery($frontPage : Boolean = false,$id: int) {
  details(id: $id) {
    ... on Product @include(if: $frontPage) {
      size
      name
      link
    }
    id
    description
}
```
I would expect that query to produce a single `AsProduct` that can be consumed like: 

```kotlin
data.details.asProduct()?.size
data.details.id
```

Getting `AsProduct1` from the above queries sounds weird, let me know if that's the case and I'll dig more.

**Comment by GauravP123** [comment]
I am using a different query. I have shared the above query as an example. 
with `v1.0.0 `it was working properly and ` int size` is nullable 
`v2.1.0` it was generating `final int size` n its non-null and able to access it `ProductDetailsQuery.Data.product()).size()`
`v2.2.0` able to access it viva `((ProductDetailsQuery.AsProduct)ProductDetailsQuery.Data.product()).size()` n`final int size` n its non-null

**Comment by martinbonnin** [comment]
I think this is the expected behaviour. I believe the `size` field itself is not optional. What is optional is whether to include the inline fragment or not. In Java you can check whether `product()` is an instance of `AsProduct` to access it fields.

Is there something you cannot do with version `2.2.0` ?

**Comment by GauravP123** [comment]
yeah, `size` is not optional but when we use `@include` previously(v1.0.0) it was creating @Nullable

**Comment by martinbonnin** [comment]
Yep, this changed. I don't have the exact reason why on top of my head but I'm pretty sure there must have been a good reason. Maybe it's because a given field can be included in multiple inline fragments as well as in the parent field at the same time.

**Comment by GauravP123** [comment]
we are using ` generateModelBuilder.set(true)` not the kotlin one coz of this `data.details.asProduct()` is not available We have to type case but somehow it's not working. Let me check if get something
