### ISSUE TITLE
[Codegen] Uniformize inline fragments code?

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#2354]
When the inline fragment is on the same type as the field and does not contain `@include` directives, there is currently a shorthand that allows to skip the `asXyz` construct and access fields directly as if they were requested in the parent field instead. Would it make sense to uniformize everything so the API is more consistent even if more verbose?

```
query {
   hero {
     ... on Character {
       name
      }
   }  
}

// can be used with:
data.hero.name
```

```
query {
   hero {
     ... on Droid {
       name
      }
   }  
}

// can be used with:
data.hero.asDroid?.name
```

```
query HeroQuery($withDetails: Boolean!) {
   hero {
     ... on Character @include(if: $withDetails) {
       name
      }
   }  
}

// can be used with:
data.hero.asCharacter?.name
```

See https://github.com/apollographql/apollo-android/pull/2352 for more details

**Comment by sav007** [comment]
Yeah, let;s keep it open for now and see how thing will go with new codegen, as it's going to fix this issue out of the box.

**Comment by martinbonnin** [comment]
Fixed with the [various codegen modes](https://www.apollographql.com/docs/android/v3/advanced/response-based-codegen/):

* operationBased always uses `onXyz()`
* responseBased never uses `onXyz()` but instead the caller has to cast or use `when` on the correct response shape.
