### ISSUE TITLE
ability to append operationName in http post url for debugging purpose

### ISSUE THREAD

**Issue by mwajeeh** [apollographql/apollo-android#2370]
**Problem**
Right now if you analyze your network requests through a tool like 'Charles' then all you see is your base url used for post request. It is cumbersome to open request/response detail to know what is the content of that post. This is needed during development when you have 100s of api calls happening and you want to analyze what that call is about.

**Solution**
Ability to append `operationName` in post url (like get urls) either at library level or through interceptors. I like the ability to modify url through interceptors because then developers can append anything they like in the `serverUrl` e.g. `http://baseurl.com/graphql?query=authenticate&newUser=false`. If this is possible in existing library then please point me the right direction. Thanks, 

Relevant code in httpGetUrl `com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor#httpGetUrl`
`urlBuilder.addQueryParameter("operationName", operation.name().name());`

**Comment by martinbonnin** [comment]
Could you use the `X-APOLLO-OPERATION-NAME` header? As far as I remember, this is added in `ApolloServerInterceptor` before it reaches the okhttp client. So you could add a OkHttp interceptor to get it from the headers and append it as query parameter?

**Comment by mwajeeh** [comment]
Wow, didn't know about this header. I was in the middle of writing okhttp interceptor which reads the whole body and parses operation name. Seems like `X-APOLLO-OPERATION-NAME` will do just fine.

**Comment by mwajeeh** [comment]
Sharing my interceptor if someone needs it.
```
import okhttp3.Interceptor
import okhttp3.Response

class OperationNameInterceptor : Interceptor {

    override fun intercept(chain: Interceptor.Chain): Response {
        var request = chain.request()
        try {
            val operationName = request.header("X-APOLLO-OPERATION-NAME")
            if (operationName != null) {
                request = request.newBuilder().url(request.url.newBuilder().addEncodedQueryParameter("operation", operationName).build()).build()
            }
        } catch (t: Exception) {
            //ignore
        }

        return chain.proceed(request)
    }
}
```
