### ISSUE TITLE
Retrieve Response Http Headers and inject inside the Operation.Data

### ISSUE THREAD

**Issue by sbilello** [apollographql/apollo-android#2389]
Hi Everyone!
I have a graphQL API to query that requires `HTTP request headers` for each request and that returns the relative HTTP response headers 
I found the response to half of the problem that I am trying to solve from https://github.com/apollographql/apollo-android/issues/2030#issuecomment-647873074
It looks like I can use the method provided by https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/RealApolloCall.java#L178-L183 to add the request header for each request and now I was wondering how I can map the `HTTP response headers` to the POJO class that implements an `Operation.Data`. https://github.com/apollographql/apollo-android/blob/master/apollo-api/src/commonMain/kotlin/com/apollographql/apollo/api/Operation.kt#L40
Maybe I am missing something and it is already there in some bean property?

**Comment by martinbonnin** [comment]
Hi! You can get the HTTP response headers from `response.executionContext`:

```
    val response: Response<YourQuery.Data> = //... get a response using ApolloClient
    val httpContext = response.executionContext[OkHttpExecutionContext.KEY]
    httpContext?.response?.headers?.forEach {
        println("${it.first}=${it.second}")
    }
```

This is a fairly new API and it will most likely require a recent version. Also, it's not documented yet but it should certainly be added somewhere. Let me know if it worked and I'll add it.

**Comment by sbilello** [comment]
<img width="1601" alt="Screen Shot 2020-06-23 at 11 36 44 AM" src="https://user-images.githubusercontent.com/1815376/85443208-d63e4f00-b545-11ea-9f80-3661aed9719b.png">
I am using `apollo-api-jvm:2.2.1` Is it only in kotlin such support?

**Comment by sbilello** [comment]
```   
      final OkHttpExecutionContext context = response.getExecutionContext().get(OkHttpExecutionContext.KEY);
        Optional.ofNullable(context)
            .map(OkHttpExecutionContext::getResponse)
            .map(okhttp3.Response::headers)
            .map(Headers::toMultimap)
            .orElse(Collections.emptyMap());
``` 
This is the solution. I upgraded the apollo-runtime to 2.2.1

**Comment by martinbonnin** [comment]
Hi! 

Glad to hear that retrieving the HTTP response headers is working 👍 

Regarding `OKHttpInterceptors`, I'm not sure to understand what you are using them for. Can you elaborate a bit more? To change the headers on an `ApolloCall`, you can use `ApolloCall.requestHeaders()` without a `OkHttpInterceptor`

**Comment by sbilello** [comment]
Yes, the headers problem is solved.
```
ApolloCall<V> apolloCall = ApolloClient.builder()
        .serverUrl(String.format(myProperties.getServerUrl(), locale.getCountry(), locale.toLanguageTag()))
        .okHttpClient(okHttpClient)
        .build()).query(operation);
```
I am referring to this snippet as you can see I would need to change the serverUrl for each request to add the `java.util.Locale` depending on the user request.
 `myProperties.getServerUrl` is something like `https://mygreatgraphqlserver/blablabla?country=%s&language=%s` and I wanted to avoid to generate an `ApolloClient Bean` for each request, or the ApolloClient bean is designed by taking in consideration that you can have a new one for each request?

**Comment by martinbonnin** [comment]
Ah yes, there's no way to change the `serverUrl` per-request. What you can do is create a "generic" `ApolloClient` and use `ApolloClient.newBuilder()` to change the `serverUrl` without instantiating a new `OkHttpClient` every time:

```kotlin
// Initial generic client
ApolloClient genericClient = ApolloClient.builder()
        .serverUrl("dummyUrl")
        .okHttpClient(okHttpClient)
        .build()

// When you want to change the serverUrl:
ApolloClient apolloClient = genericClient.newBuilder()
        .serverUrl("https://your.real/url")
        .build()

```
