### ISSUE TITLE
Pagination in Java

### ISSUE THREAD

**Issue by vikas115m** [apollographql/apollo-android#2391]
Hi Team,

Can you please let me know how to implement pagination in apollo java client when invoking an graphQL service

There is no proper documentation and all refers to reacts page or 404 page

Please help me with some sample / some document for pagination based on pageSize

**Comment by martinbonnin** [comment]
Hi @vikas115m 

There is a query with cursor-based pagination in [the tutorial](https://github.com/apollographql/apollo-android-tutorial/blob/fd2466e256f984eb718ac7a25e57388030d15c77/app/src/main/graphql/com/example/rocketreserver/LaunchList.graphql#L2):

```graphql
query LaunchList($cursor: String) {
  launches(after: $cursor) {
    cursor
    hasMore
    launches {
      id
      site
      mission {
        name
        missionPatch(size: SMALL)
      }
    }
  }
}
```

The rest of the tutorial is in Kotlin but as far as writing the queries themselves, it should be similar. For integrating with an Adapter and/or RecyclerView, it depends what frameworks you want to use. If you're using Java, I would recommend looking into [RxJava3](https://github.com/ReactiveX/RxJava) and/or the [Paging Library](https://developer.android.com/topic/libraries/architecture/paging?authuser=2)

**Comment by vikas115m** [comment]
Hi @martinbonnin 

Thanks for your reply

We are using apollo client in an normal java project , we are not using android

I was wondering if we need to call the apollo client in an recursive way based on requestData page size ?

**Comment by martinbonnin** [comment]
I'm not sure what you mean by `requestData page size`, can you elaborate a bit more? 

Usually, there are 2 ways to do pagination:
* cursor-based (as above): the page contains a cursor and you can request items after the cursor.
* offset-based: you give a start position (offset) and number of items (page size) and the server returns data at that position.

In all cases, no recursion should be needed, you would just iterate until you have enough results.

**Comment by vikas115m** [comment]
requestDate page size refers to Query Variable in query variables the API accepts page size as a parameter
Is there any example for offset-based? also we are using sync API of apollo

**Comment by martinbonnin** [comment]
> Is there any example for offset-based?

It's also a Kotlin project but this query uses offsets for pagination:

https://github.com/BoD/apollo-graphql-android-sample/blob/master/app/src/main/graphql/com/example/graphqlsample/queries/UserRepositoryListQuery.graphql#L6

> also we are using sync API of apollo

Not sure what you mean. The Apollo Android API is asynchronous by default. Did you make it synchronous?

**Comment by vikas115m** [comment]
Hi @martinbonnin 

Thanks your information ,  was able to implement pagination using offset .
