### ISSUE TITLE
Plugin error: "Cannot change dependencies of dependency configuration" 

### ISSUE THREAD

**Issue by hitherejoe** [apollographql/apollo-android#2393]
**Summary**

After applying the "com.apollographql.apollo" plugin in a multiplatform library module I'm hitting this error when trying to build:

`A problem occurred configuring project ':shared:SharedAuthentication'.
> Failed to notify project evaluation listener.
   > Cannot change dependencies of dependency configuration ':shared:SharedAuthentication:androidApi' after it has been included in dependency resolution.
   > Cannot change dependencies of dependency configuration ':shared:SharedAuthentication:androidTestApi' after it has been included in dependency resolution.
   > Cannot change dependencies of dependency configuration ':shared:SharedAuthentication:iosApi' after it has been included in dependency resolution.
   > Cannot change dependencies of dependency configuration ':shared:SharedAuthentication:iosTestApi' after it has been included in dependency resolution.
   > Cannot change dependencies of dependency configuration ':shared:SharedAuthentication:iosCompileKlibraries' after it has been resolved.
   > Cannot change dependencies of dependency configuration ':shared:SharedAuthentication:iosTestCompileKlibraries' after it has been resolved.
   > Cannot change attributes of dependency configuration ':shared:SharedAuthentication:iosApiElements' after it has been resolved`

**Version**

Apollo: 2.2.1
Kotlin: 1.3.72 

**Description**

This happens whenever trying to build the project. The branch where this is occurring is available [here](https://github.com/hitherejoe/minimise/tree/task/graphql).

- [Module build.gradle file](https://github.com/hitherejoe/minimise/blob/task/graphql/shared/SharedAuthentication/build.gradle.kts)
- [Project build.gradle file](https://github.com/hitherejoe/minimise/blob/task/graphql/build.gradle)

I've double checked against the sample and can't quite spot anything that might be misconfigured in my project. Maybe there is a bug causing this problem with the plugin, so thought it was worth raising!

**Comment by martinbonnin** [comment]
Thanks for sending this! 

We have some code in the plugin that [ensures the compiler version matches the runtime version](https://github.com/apollographql/apollo-android/blob/39a8243beb200441204a45b7da31fd5f44f1a350/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/internal/ApolloPlugin.kt#L263) else some weird crashes occur. 

This code resolves the configurations at configuration time but it looks like the Kotlin plugin also want to change some constraints on dependencies and in your case, this would happen too late. I'm not 100% sure how these thing work but I'll look into it, maybe make `checkVersion` lazy itself.

In the meantime, applying the `multiplatform` plugin after the `apollo` one seems to do the trick.

**Comment by hitherejoe** [comment]
Thanks @martinbonnin  - looks like that does that trick for now :)
