### ISSUE TITLE
Quick question about 3rd party Open Source used

### ISSUE THREAD

**Issue by hrieke** [apollographql/apollo-android#2394]
Hello guys,

Can you write up a little blurb on what open source you use / mixed in?
By my count, I found 23 files with the Apache License 2.0 from Google (?) and Square (Okhttp, Okie).

Thank you,

**Comment by martinbonnin** [comment]
What form would you like this to take? A flat list will be hard to keep in sync and might also not cover all use cases. Depending the modules you opt-in or not, the list of dependencies will change.

There are a few plugins that get the list of open source licenses from the Gradle dependencies:
- https://github.com/jaredsburrows/gradle-license-plugin
- https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin

They will most likely be more scalable and maintainable and keep the gradle configuration as a single source of truth.

**Comment by hrieke** [comment]
Open source uses open source.  This is a very good thing.  Keeping track of what is being included is good code hygiene.
You do (sometimes) credit Okhttp (along with version number, nice!), and the Google Guava / Android Development kit are fairly simple to figure out.
But it would be super nice if you guys say in the directories where these included files are a notice / readme / license file that says "You will find Google's Guava, version a.b.c".
This way if a CVE comes out for one of these packages included, we can look at it and see if we're also impacted.
Thank you.

**Comment by martinbonnin** [comment]
You can find a list of all the dependendencies at https://github.com/martinbonnin/apollo-android/blob/master/gradle/dependencies.gradle

This are the dependencies used by Apollo Android

**Comment by hrieke** [comment]
These files contain a Google Guava Copyright notice;
java/com/apollographql/apollo/api/internal
>>Absent.java
>>Optional.java
>>Present.java
java/com/apollographql/apollo/api/graphql/internal
>>OptionalTest.java

These are not an included jar file from the gradle build.

**Comment by martinbonnin** [comment]
Got it! I got confused with Gradle dependencies but there are files included from other projects as well. 

I don't have enough history in the project to know the exact version these files are coming from. I guess you're looking at comments similar to https://github.com/apollographql/apollo-android/blob/06acab79ca711901cf22fb1dcf431f35145caedd/apollo-http-cache/src/main/java/com/apollographql/apollo/cache/http/internal/FileSystem.java#L40 ?

**Comment by hrieke** [comment]
No problem; just ask around and see if this is something that can be done.
Thank you for your attention to this question!

**Comment by martinbonnin** [comment]
@hrieke I'm going to close this one as there is only so much we can do for the existing code. I will definitely include more comments for the new code!

**Comment by hrieke** [comment]
Awesome and Thank you.
Happy Coding!
