### ISSUE TITLE
[Performance] Move normalized ApolloStore write transactions to background thread.

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#2402]
**Question.**

We noticed a significant performance regression (particularly on large responses) after the Apollo 2.x upgrade, and the switch  [androidx/sqldelight](https://github.com/apollographql/apollo-android/pull/2158) database while using the normalized sql cache.

Part of this can be mitigated by running the database actions in a [transaction](https://github.com/apollographql/apollo-android/pull/2158/files#diff-626cc33cc6e124578a410f489be79d86L93) like the old sql cache, but even with that we noticed a perf hit with the new db.

A more complete solution is to make the `ApolloCacheInterceptor` perform the [response saving](https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloCacheInterceptor.java#L73) on a new thread - there may be a minute risk that a new request that is executed after a response of a previous request will read before the first request has dispatched it's save, but that seems quite unlikely, and the worst case is that you get a cache miss.

Overall it seems pretty safe as:

1) The [Store is already thread safe ](https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/RealApolloStore.java#L179)

2) All side effects of saving a response are [already dispatched on a new thread](https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloCacheInterceptor.java#L178)

Does anyone see any issues with making this change?

**Comment by martinbonnin** [comment]
We should be able to reach the same performance without adding new threads, right? 

Or is there a more fundamental difference between SQLDelight and the Android DB? I'm always a bit reluctant to adding threads if not 100% necessary as it's another source of race conditions and sneaky bugs.

**Comment by BenSchwab** [comment]
I know the lack of the transaction is one reason of the slowdown, I need to do a bit more research into what else changed. Agree that we should optimize performance of the database regardless.

However, from a design perspective, it doesn't seem correct that a database write blocks an already parsed response from being used. We have been searching for a while why migrating to GraphQL generally causes performance to regress on a page, and I am pretty sure this is the cause.

**Comment by martinbonnin** [comment]
I've made a [small benchmark](https://github.com/martinbonnin/apollo-android-samples/tree/master/cache-performance) that writes a query to the cache 100M times. The [query](https://github.com/martinbonnin/apollo-android-samples/blob/613c9dc2e554ce23fecc2307061d9d9f6989554e/cache-performance/cache-1-4/src/main/graphql/net/sample/lib/all.graphql#L5) is a list of Github repositories containing "lorem ipsum" in the description.

Results are (run on a Pixel 3 XL):

* 1.4.5 -> 12417ms to write 100M queries
* 2.2.1 -> 13544ms to write 100M queries

That's ~10% slower if I do the maths right. Is that the same level of degradation you observe on your end?

**Comment by BenSchwab** [comment]
We saw a 4 second P95 slowdown parsing slow down

**Comment by BenSchwab** [comment]
@martinbonnin So I dug a bit deeper into the issue - before the 2.1.0 upgrade, we actually had our normalized cache configured wrong, and were only getting the in memory cache. So the upgrade was more akin to re-enabling the sql cache.

We have some queries with 2000 records, which means we are performing 2000 read/write operations on a sql database. It does make sense that re-enabling a transaction will help a bit and could account for the 10% profile change you see (particularly on the write path), but that volume of operations is definitely going to result in a perf hit compared to not using the sql cache.

Blocking a response by up to 4 seconds by enabling sql cache seems like pretty compelling support for moving forward with making the apollo store operations non-blocking (or at least a configurable option).

**Comment by BenSchwab** [comment]
Will explore more if we can improve the efficiency of the sql cache in general. A 4 second operation on a non-blocking thread isn't fantastic either.

**Comment by BenSchwab** [comment]
A couple things about the performance example need to be updated:

1) `execute` is never called on the write operation, so it isn't doing anything
2) The dispatcher needs to be set to be blocking to simulate the api which is used while writing a response, as the write operation api uses a dispatcher


After making those changes, and dropping the iterations down to 100 I get (At cache record size of ~1000):
- 1.4.5 -> 80258 millis or 802ms per operation
- 2.2.1 -> 81505 millis or 815 ms per operation

So there doesn't seem to be a big performance difference between versions, but 800ms overhead is substantial

**Comment by BenSchwab** [comment]
[Adding back the transaction block](https://github.com/BenSchwab/apollo-android-samples/commit/8d46a68fbca55da3be28ed3f56b82d167408358c) brought the performance to a comparable 429 ms per operation. I'll go ahead an put up a PR to fix that.

**Comment by martinbonnin** [comment]
Regarding making the writes non-blocking, we should keep the guarantee that a read after a write returns the updated value:

```
val response1 = client.query(SomeQuery()).responseFetcher(ApolloResponseFetchers.NETWORK_ONLY).toDeferred().await() // returns as soon as the network response is received and writes the cache in the background
val response2 = client.query(SomeQuery()).responseFetcher(ApolloResponseFetchers.CACHE_ONLY).toDeferred().await() // should always succeed, no matter the timings
```

Maybe it can work with some kind of "memory-barrier" that waits until all writes are performed before a read can be done?

**Comment by BenSchwab** [comment]
So long as the dispatcher that is used with Apollo executes tasks in the order they are submitted, I think we can achieve the ordering requirement pretty easily if we change ApolloInterceptor to use [enqueue vs execute](https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloCacheInterceptor.java#L116) when it [reads from cache](https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloCacheInterceptor.java#L61).

This would mean that a cache write is guaranteed to be enqueued before any subsequent cache read. (Additionally the store employs a read/write lock, but it does seem like we need to guarantee the write starts before a later read)

**Comment by BenSchwab** [comment]
Other less pressing ideas of how to improve performance:
- batch all the record reads in the normalized cache (unverified, but I imagine reading a [row one at a time in a loop](https://github.com/apollographql/apollo-android/blob/master/apollo-normalized-cache-sqlite/src/commonMain/kotlin/com/apollographql/apollo/cache/normalized/sql/SqlNormalizedCache.kt#L58) is slower than selecting the entire set)
- have a more robust read/write lock system, that allows reads while a disjoin write is occurring. I believe that even if we offload this expensive work to a new thread, multiple operations executed in close succession face a risk where the expensive write blocks the read, essentially delaying the read by the original cost of the write we see in this thread
