### ISSUE TITLE
Mock Apollo client Response

### ISSUE THREAD

**Issue by vikas115m** [apollographql/apollo-android#2410]
Hi Team,

Is there any sample for mocking Apollo response in java ?

Any sample java code would  be highly appreciated

Let me know in case of any details required

**Comment by martinbonnin** [comment]
`apollo-integration` has some examples of using [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver) to mock responses using json fixtures. You can take a look at [IntegrationTest.java](https://github.com/apollographql/apollo-android/blob/1b58e4876d93731870d3ae80b500d2b8cbd731b6/apollo-integration/src/test/java/com/apollographql/apollo/IntegrationTest.java#L89) for an exemple.

**Comment by vikas115m** [comment]
Hi @martinbonnin ,

Thank you for the info

Can you please let me know which version of mockserver is being used ?

**Comment by vikas115m** [comment]
thanks for your time I was able to mock the data using mock server :)
