### ISSUE TITLE
3.0.0 wishlist

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#2425]
A list of potential changes that would go in a 3.0.0 release below. This is mostly brainstorming at the moment, feel free to add or comment the general direction here. For detailed discussions about a specific topic, go to the corresponding issue (or create one)

- [ ] Kotlin runtime (#2222)
- [ ] default to Kotlin models (#2424)
- [ ] cache improvements (#2331)
- [ ] multi-modules (#1973)
- [ ] generate fragments as interfaces
- [ ] remove BigDecimal as an intermediate representation and expose a ScalarTypeAdapter instead 
- [ ] remove `@ApolloExperimental`
- [ ] remove deprecated fields
- [ ] inline GraphQL
- [ ] more?

Questions:
- [ ] remove Gradle plugin variant handling? 
- [ ] cleanup test variant handling
- [ ] add a streaming API?
- [ ] add validation for extra fields?
- [ ] rename operationOutput?

**Comment by mrctrifork** [comment]
Can we get compatibility with the [Absinthe's implementation of GQL](https://github.com/absinthe-graphql/absinthe)? By the time being queries and mutations work perfectly! Subscriptions and FileUploads, I am afraid not 😅

**Comment by martinbonnin** [comment]
@mrctrifork I would suggest making it a separate pull request that we can link here if there's enough demand. Also, if you can include the endpoint of a working server, that'd be neat so we can test easily.

**Comment by martinbonnin** [comment]
Closing this in favor of [ROADMAP.md](https://github.com/apollographql/apollo-android/blob/main/ROADMAP.md) and [milestones](https://github.com/apollographql/apollo-android/milestones). Feel free to comment on the individual issues and leave 👍  to help with priorization.
3.x development has started in [dev-3.x](https://github.com/apollographql/apollo-android/tree/dev-3.x)

**Comment by martinbonnin** [comment]
Hi @mrctrifork ! It's been a while but if you're still interested in Absinthe support, @ajacquierbret has an awesome integration with ApolloClient, including subscriptions. You can read more at https://github.com/apollographql/apollo-kotlin/issues/3809

**Comment by mrctrifork** [comment]
I've been reading all updates on the linked issue. I am greatly excited and can't wait to try it out in the next project we need such tooling 🚀 .

Thank you very much for your efforts and great tool you've put out there
