### ISSUE TITLE
Improve documentation on normalized cache

### ISSUE THREAD

**Issue by lbg-reggar** [apollographql/apollo-android#2429]
**Is your feature request related to a problem? Please describe.**
Currently, [iOS](https://www.apollographql.com/docs/ios/caching/) and [React](https://www.apollographql.com/docs/react/caching/cache-interaction/) have a lot more detailed information about how the normalized cache works and how one can interact with it. The Android documentation should be updated to include this.

**Describe the solution you'd like**
Android documentation includes:
* How the default cache key is defined
* How to configure the cache keys
* How to interact with cached data

**Comment by martinbonnin** [comment]
The preview of the docmentation is available there: https://deploy-preview-2433--apollo-android-docs.netlify.app/docs/android/essentials/normalized-cache/
Pull request: https://github.com/apollographql/apollo-android/pull/2433

Let me know if that helps

**Comment by lbg-reggar** [comment]
Thanks for the quick turnaround @martinbonnin . Looks good so far might be helpful to add any recommendations around the `ApolloStore` like updating or removing (as opposed to the catch-all `clearNormalizedCache()`)?

**Comment by martinbonnin** [comment]
@lbg-reggar I added a small section about `ApolloStore`. I don't want to commit too much there since this is typically something that can be improved and might change in the near future. See https://github.com/apollographql/apollo-android/issues/2331.

Out of curiosity, is this an API that you are using already? Would you share some details about your use case to make sure it's addressed by any new API?

**Comment by lbg-reggar** [comment]
@martinbonnin Thanks for doing that, really appreciated.

We are early on our GraphQL journey so just learning the realm of possibility. Essentially, an illustratrative use-case would be:
* We have a library that contain shelves that contain a selection of books (with chapters and pages)
* We have the ability to add/remove books and move them between shelves
* After updating we want a way to invalidate the cache for those books rather then invalidating the app-wide normalized cache

We are essentially thinking about storing everything with their ID's as the CacheKey. We can then use `apolloClient.apolloStore.remove([SHELF_ID])` when we know a shelf has been updated, rather than `apolloClient.clearNormalizedCache()`. Another option, would be to retrieve the shelf as part of the
mutation call, but then it requires the shelf modification screen to know which fields other parts of
the application are using.

Hope that all makes sense.

**Comment by martinbonnin** [comment]
That makes perfect sense. Thanks for the explanations 👌 .
