### ISSUE TITLE
Add RxJavaApollo wrappers

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#243]
Since we dropped Retrofit, Rxjava support is no longer free.  We need to create some sort of wrappers for apollo which would allow user to return RxJava observables.  Since there is a dependency on RxJava we will need to make call adapters. There will be an ApolloRx1Adapter and an ApolloRx2Adapter.

**Comment by digitalbuddha** [comment]
First implementation is to only support `Observable` there will be follow up issues to support `Single`.

**Comment by digitalbuddha** [comment]
After a bit of discussion on slack:

- We will be building adapters in the style of `CallAdapter<T>`.  
- We will have ApolloClient<T> register an adapter<T>, if non registered default will be used for `newCall`
- We will create override <T> newCall(operation,CallAdapter<T>) so that users can use many call adapters

**Comment by digitalbuddha** [comment]
Adapters won't work do to use not being able to do R<T> in java. Here's the backup plan https://gist.github.com/digitalbuddha/3c1dbccf059f0279e46e540b2c5fd89e

**Comment by marwanad** [comment]
Closed by #341
