### ISSUE TITLE
Caused by: java.lang.ClassFormatError: Too many arguments in method signature in class file type/WhateverWhereInput

### ISSUE THREAD

**Issue by bernerha** [apollographql/apollo-android#2431]
**Summary**
The generated `XXWhereInput` class has to many Arguments.

**Version**
2.2.2

**Description**
We have a kotlin project and couldn't add any more fields to our graphql model because it can't be handled because of too many arguments in the java generated code.

So we thought the switch to kotlin generated code might help.
It doesn't :)

The graphql model consists of 17 direct attributes and 12 links to other models which none of them is larger than die culprit one.
The generated data class has 256 constructor parameters...
Every doable operation (gt,lt,...) is a extra parameter, is this necessary? 

Is there any possibility to strip this class down? Ignore some of the doable operations on the graphql schema?

**Comment by bernerha** [comment]
Maybe the schema.json is to big?. We removed some objects from the json an it works.
But this doesn't feel like the way it should work.

**Comment by bernerha** [comment]
We build a gradle task which removes the unnecessary objects from the schema.json. Works so far.
But maybe you have another solution.

**Comment by sav007** [comment]
Unfortunately there is no other way except strip the schema itself. For any input object we can't really know upfront what arguments are you going to use in your mutation so we must generate input object with all fields. But could you try smth else, try to use inline input objects, like this sample:

```
query TestQuery($episode: Episode, $stars: Int!, $greenValue: Float!) {
  heroWithReview (
    episode: $episode,
    review: {
      stars: $stars,
      favoriteColor: {
        red: 0
        green: $greenValue
        blue: 0
      }
    },
    listOfInts: [$stars, $stars]
  ) {
    name
  }
}

```

**Comment by bernerha** [comment]
Thank you for this hint. We will try it.
