### ISSUE TITLE
new ResponseReader.kt in ver. 2.0.0 is not compatible with generated classes

### ISSUE THREAD

**Issue by azubchenko** [apollographql/apollo-android#2432]
**Summary**
Kotlin version of ResponseReader is not compatible with the classes generated based on the schema.

**Version**
Starting from 2.0.0 up to 2.2.2

**Description**
Upgraded from 1.4.3. to 2.2.2 and it appears that java version of ResponseReader was substituted with Kotlin version.
I'm ok with that, but if java version always returned non-null field value for the fields, kotlin version may return null:
```
interface ResponseReader {
  fun readString(field: ResponseField): String?
....
}
```
versus how it was:
```
public interface ResponseReader {
  String readString(ResponseField field);
...
}

```

But, the constructor of the class may take an 'id' value that cannot be null, and it's described as NON_NULL in schema.
And in the code generated we see something like this:
```
data class MyCustomRecord(
    val __typename: String = "MyCustomRecord",
    val id: String,
    val recordId: String?
  ) // neither __typename, nor id fields can be nullable

```
and the code for instantiation of this class with the help of ResponseReader:
```
operator fun invoke(reader: ResponseReader): MyCustomRecord = reader.run {
        val __typename = readString(RESPONSE_FIELDS[0]) // String?
        val id = readString(RESPONSE_FIELDS[1]) // String?
        val recordId = readString(RESPONSE_FIELDS[2])
        MyCustomRecord(
          __typename = __typename, // cant compile case val __typename is of String? type
          id = id, // cant compile case val id is of String? type
          recordId = recordId
        )
      }

```
Any solutions on this?
Thanks!

**Comment by martinbonnin** [comment]
The [test cases](https://github.com/apollographql/apollo-android/blob/c1f0050ea805df7b017ea553a086396159e141f2/apollo-compiler/src/test/graphql/com/example/introspection_query/TestQuery.kt#L109) generate a `!!` do make sure fields are not nullable but maybe there's something else.

Before we dive further, can you rerun your build with `--no-build-cache`? I've seen weird cases with stale generated files, especially when changing the plugin version.

**Comment by azubchenko** [comment]
Rerun it - same stuff, no changes in the code generated.

How come test classes are generated with _**!!**_ ?

**Comment by martinbonnin** [comment]
> How come test classes are generated with !! ?

That's a very good question!! Is there any chance you can share your schema.json and graphql query?

**Comment by azubchenko** [comment]
Unfortunately, I can not give the whole schema.json(as the project is under NDA). But I can provide piece describing MyCustomRecord entity:
`{"kind":"OBJECT","name":"MyCustomRecord","description":null,"fields":[{"name":"id","description":null,"args":[],"type":{"kind":"NON_NULL","name":null,"ofType":{"kind":"SCALAR","name":"String","ofType":null}},"isDeprecated":false,"deprecationReason":null},{"name":"index","description":null,"args":[],"type":{"kind":"NON_NULL","name":null,"ofType":{"kind":"SCALAR","name":"Int","ofType":null}},"isDeprecated":false,"deprecationReason":null},{"name":"code","description":null,"args":[],"type":{"kind":"SCALAR","name":"String","ofType":null},"isDeprecated":false,"deprecationReason":null},{"name":"trackId","description":null,"args":[],"type":{"kind":"SCALAR","name":"Float","ofType":null},"isDeprecated":false,"deprecationReason":null},{"name":"type","description":null,"args":[],"type":{"kind":"NON_NULL","name":null,"ofType":{"kind":"SCALAR","name":"String","ofType":null}},"isDeprecated":false,"deprecationReason":null},{"name":"caption","description":null,"args":[],"type":{"kind":"SCALAR","name":"String","ofType":null},"isDeprecated":false,"deprecationReason":null},{"name":"requireCompletion","description":null,"args":[],"type":{"kind":"SCALAR","name":"Boolean","ofType":null},"isDeprecated":false,"deprecationReason":null},{"name":"skippableByAdmin","description":"Whether this card can be skipped from OMM or not. Full list of skippable cards can be fetched from admin => settings => skippableCardTypes API","args":[],"type":{"kind":"NON_NULL","name":null,"ofType":{"kind":"SCALAR","name":"Boolean","ofType":null}},"isDeprecated":false,"deprecationReason":null},{"name":"state","description":null,"args":[],"type":{"kind":"NON_NULL","name":null,"ofType":{"kind":"OBJECT","name":"EntityState","ofType":null}},"isDeprecated":false,"deprecationReason":null},{"name":"recordId","description":null,"args":[],"type":{"kind":"SCALAR","name":"String","ofType":null},"isDeprecated":false,"deprecationReason":null}],"inputFields":null,"interfaces":[{"kind":"INTERFACE","name":"IMyCard","ofType":null}],"enumValues":null,"possibleTypes":null}`

As you may see the, the **id** field is explicitly marked as NON_NULL in schema, but **recordId** is not. That is why I get error for the **id**.
Where in schema can I look up for the definitions that influence **__typename** field generation?

**Comment by martinbonnin** [comment]
[`__typename` is an implicit field](https://spec.graphql.org/June2018/#sec-Type-Name-Introspection) of type `String!`. 

Can you share your `.graphql` query? Feel free to change names, I'm mainly looking at the structure of the query, whether it contains directives, fragments, inline fragments, etc...

**Comment by azubchenko** [comment]
Hi, Martin
Here it is, nothing fancy really:
```
mutation AddCustomRecordCard($card_id: String!, $timeStamp:GraphQLDateTime!) {
    me {
        path{
            level{
                step{
                    card(cardId:$card_id){
                        addMoodMeterRecord(input:{timeStamp:$timeStamp})
                        { id, moodRecordId }
                    }
                }
            }
        }
    }
}
```

The problem is not just in this mutation, but the whole project stopped compiling. This problem is all over the place, in every query in every mutation.

**Comment by martinbonnin** [comment]
Thanks for providing that!

I made a small repo to try to reproduce something as similar as possible to your schema. It is there https://github.com/martinbonnin/apollo-android-samples/tree/master/error-on-non-nullable-fields. 

Can you try it and see if you catch anything weird in there or if you can modify it to make it fail? Running `./gradlew assembleApolloSources` will generate the models. So far I haven't been able to reproduce (they always contain `!!`). One thing that _could_ maybe have an impact is the `IMyCard` interface? But TBH, if it happens for all your objects, it's certainly something else. 

A few other things to try:

* removing options from your `apollo {}` Gradle block? Is there any specific configuration there?
* add a simple field to your schema and verify that it works as expected: the field should be non-nullable in the generated model and the parsing code should assert it with `readString(RESPONSE_FIELDS[0])!!`
* If it doesn't work, it certainly means the problem is not in the schema. Maybe a KotlinPoet conflict or something else. 
* If it works, there must be something in the schema that makes the compiler fail. Try "bisecting" your schema: remove fields/interfaces until you find

**Comment by azubchenko** [comment]
Hi, Martin,

Thanks for you sample project, I will definitely give it a whirl!

As for the suggestions:
- this is the only stuff I have in apollo{} block
```
apollo {
    generateKotlinModels.set(true)
    customTypeMapping = ["GraphQLDateTime": "java.lang.Long"]
}
```
- schema is server-side generated and I'm afraid I'm not that familiar with the format of how to defined instances/fields into it, but I will give it a tray

**Comment by martinbonnin** [comment]
In case you're still investigating this, the latest version ([2.2.3](https://github.com/apollographql/apollo-android/releases/tag/v2.2.3)) includes support for SDL schemas which will be easier to work with if you want to experiment with your schema. 

You can convert your `schema.json` to `schema.sdl` with a tool like https://github.com/potatosalad/graphql-introspection-json-to-sdl. Then adding/removing fields should be way easier.

**Comment by azubchenko** [comment]
That is very very helpful! Thanks a lot!
Unfortunately, I'm a bit overloaded right now, but I'm looking into it asap.
