### ISSUE TITLE
Http request failed with status code 400

### ISSUE THREAD

**Issue by Klaudas** [apollographql/apollo-android#2437]
**Question.**

Hello,

Our team has written data layer with Kotlin-Native and using it across both Android and iOS platforms. Android queries seems to work properly, however in iOS requests fails with:

```
Request: common.GetUserQuery@2bf94d8
ApiQL : Request query document: query GetUser { currentUser { __typename user { __typename id emailAddress contact { __typename firstName lastName address { __typename country } } userRoles { __typename name } locale termsOfUseAccepted } } }
ApiQL : Request query variables: {}
ApiQL : Request error com.apollographql.apollo.ApolloHttpException: Http request failed with status code `400`
```

Logs don't show much. Any ideas on how to expand logging and get more insight?

**Comment by martinbonnin** [comment]
In these cases, I would setup a [Charles Proxy](https://www.charlesproxy.com/) or any other proxy, run the iOS and Android code and compare the requests. Watch for different HTTP headers, method and/or body.

If proxying isn't an option, you can dump the whole request with a [OkHttp HttpLogginInterceptor](https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor) on Android, like [here](https://github.com/RumiRajbhandari/GraphqlDemo/blob/0f36c557bf4b31c70c7d152eed91c061542ffa69/app/src/main/java/com/example/rumi/apollodemo/MyApolloClient.kt#L18) for an example. 

I'm not sure how to do the same thing on iOS. @designatednerd any ideas?

**Comment by martinbonnin** [comment]
@Klaudas any luck with a proxy? Looking at NSURLSession, I found https://github.com/muukii-archive/HTTPLogger. Maybe that can help you dump the request on iOS if a proxy is not feasible?

**Comment by martinbonnin** [comment]
I'm closing this issue, please leave a message if you want me to reopen it.
