### ISSUE TITLE
SDK version mismatch

### ISSUE THREAD

**Issue by GauravP123** [apollographql/apollo-android#2438]
We have an app that uses 1 SDK. Both are using apollo-android. On the app side, we have started migrating SDK version from `1.0` to `2.0` whereas SDK is still using `1.0`. We are getting following the crash. 

is this happening coz of version mismatch if yes anyway to prevent 

```
 java.lang.AbstractMethodError: abstract method "com.apollographql.apollo.api.internal.ResponseFieldMapper com.apollographql.apollo.api.Operation.responseFieldMapper()"
        at com.apollographql.apollo.internal.ResponseFieldMapperFactory.create(ResponseFieldMapperFactory.java:21)
        at com.apollographql.apollo.internal.RealApolloCall.prepareInterceptorChain(RealApolloCall.java:381)
        at com.apollographql.apollo.internal.RealApolloCall.<init>(RealApolloCall.java:125)
        at com.apollographql.apollo.internal.RealApolloCall$Builder.build(RealApolloCall.java:542)
        at com.apollographql.apollo.ApolloClient.newCall(ApolloClient.java:374)
        at com.apollographql.apollo.ApolloClient.query(ApolloClient.java:156)
        at com.product.network.graphql.ApolloGraphQl.getProductQuery(ApolloGraphQl.kt:166)```

**Comment by martinbonnin** [comment]
Hi! Thanks for reaching out! A few questions:

> We have an app that uses 1 SDK. 

Did you mean "2" SDKs?

> migrating SDK version from 1.0 to 2.0

Can you use `apollo-android` version `2.2.2`? Version `2.0.0` had a number of issues that could trigger these kind of errors.

Other things worth considering:

* Do you know what version of `apollo-runtime` gets resolved by Gradle? You can have this by typing `./gradlew :app:dependencies`
* If that does end up being some incompatibility of having `1.x` and `2.x` together on the classpath, I don't see any other option than relocating the dependency. There are some explanations in the [shadow plugin doc](https://imperceptiblethoughts.com/shadow/configuration/relocation/) but I have never done this myself. It might be easier to upgrade everything to `2.x`.

**Comment by GauravP123** [comment]
We are using `2.2.2`
We have the app which uses SDK `implementation(name: 'testsdk', ext: 'aar')`
App using apollo `2.2.2` and testsdk is using `1.0.0`

**Comment by martinbonnin** [comment]
Do you have control over `testsdk`? The simplest path there might be to upgrade that to using `apollo-android` `2.2.2` as well.

**Comment by GauravP123** [comment]
yeah that the plan but just want to know if any other alternative. we are using `generateModelBuilder = true` and with `2.2.2` we are migrating to `generateKotlinModels.set(true)` so its lot of code changes coz java to kotlin conversion

**Comment by martinbonnin** [comment]
You can use Kotlin models in the app and Java models in `testsdk` if that helps:

```kotlin
// app/build.gradle.kts
apollo {
   generateKotlinModels.set(true)
}

// testsdk/build.gradle.kts
apollo {
   generateKotlinModels.set(false)
}
```

The `apollo-api` and `apollo-runtime` modules are compatible with both Java and Kotlin models.

**Comment by GauravP123** [comment]
yeah but with java, I am getting wired issue 
https://github.com/apollographql/apollo-android/issues/2351#issuecomment-652857391
