### ISSUE TITLE
CacheKey Resolver doesn't work

### ISSUE THREAD

**Issue by OmarAlgo** [apollographql/apollo-android#2445]
My cache key resolvers looks like this:
```
val resolver: CacheKeyResolver = object : CacheKeyResolver() {
            override fun fromFieldRecordSet(field: ResponseField, recordSet: Map<String, Any>): CacheKey {
                return if (recordSet.containsKey("id") && recordSet["id"]!=null) {
                    val typeNameAndIDKey = recordSet["__typename"].toString().toLowerCase() + "." + recordSet["id"]
                    CacheKey.from(typeNameAndIDKey)
                } else {
                    CacheKey.NO_KEY
                }
            }

            override fun fromFieldArguments(field: ResponseField, variables: Operation.Variables): CacheKey {
                return CacheKey.NO_KEY
            }
        }
```

for the query which looks like this:
```
query GetData($userid: ID!) {
  unfinishedCompositions(input: {
    userId: $userid,
    includeMetadata: true
  }) {
    count,
    results {
      id,
      sections {
        status
      },
      metadata {
        status,
        submissionInfo {
          destinations,
          tryAllDest
        },
        submissionStat {
          warning {
            type,
            message
          },
          finalDest
        },
        appointment {
          id,
          reason,
          startsAt
        },
        patient {
          id,
          person {
            firstName,
            middleName,
            lastName
          }
        }
      },
      createdAt
    }
  }
}
```
I am using ApolloResponseFetchers.CACHE_FIRST. The response is always fetched from the network and never from the cache.

**Comment by martinbonnin** [comment]
Thanks for the detailed bugreport! Can you try simplifying the query to see where the problem happen?

Does the problem happen with:

```graphql
query GetData($userid: ID!) {
  unfinishedCompositions(input: {
    userId: $userid,
    includeMetadata: true
  }) {
    count
  }
}
```

And with: 

```graphql
query GetData($userid: ID!) {
  unfinishedCompositions(input: {
    userId: $userid,
    includeMetadata: true
  }) {
    count,
    results {
      id,
      createdAt
    }
  }
}
```

Also, I just merged a more [detailed documentation about the normalized cache](https://www.apollographql.com/docs/android/essentials/normalized-cache/) that you may find useful. Let me know if it helped.

**Comment by OmarAlgo** [comment]
Hey Thanks for looking into it. 
I was able to get the response from cache when i used :
```
query GetData($userid: ID!) {
  unfinishedCompositions(input: {
    userId: $userid,
    includeMetadata: true
  }) {
    count
  }
}
```
and 
```query GetData($userid: ID!) {
  unfinishedCompositions(input: {
    userId: $userid,
    includeMetadata: true
  }) {
    count,
    results {
      id,
      createdAt
    }
  }
}
```
as you rightly pointed out to simplify the query. So I kept on narrowing down the problem to a point where caching failed when I included metadata into the query like this:
```
query GetData($userid: ID!) {
  unfinishedCompositions(input: {
    userId: $userid,
    includeMetadata: true
  }) {
    count,
    results {
      id,
 metadata {
        status    
      }
      createdAt
    }
  }
}
```

**Comment by martinbonnin** [comment]
I _think_ that should work. Maybe there's another request in between that changes the cache and triggers the MISS?

To debug, you can dump the cache:

```kotlin
            val dump = apolloClient.apolloStore.normalizedCache().dump()
            println("dump: " + NormalizedCache.prettifyDump(dump))
```

That should write something like:
```
LruNormalizedCache {
  "unfinishedCompositions({"input":{"includeMetadata":"true","userId":"user0"}})" : {
    "__typename" : Composition
    "count" : 0
    "results" : [
      CacheRecordRef(result.42)
      CacheRecordRef(result.43)
    ]
    "createdAt" : 1970
  }

  "QUERY_ROOT" : {
    "unfinishedCompositions({"input":{"includeMetadata":"true","userId":"user0"}})" : CacheRecordRef(unfinishedCompositions({"input":{"includeMetadata":"true","userId":"user0"}}))
  }

  "result.43" : {
    "__typename" : Result
    "id" : 43
    "metadata" : CacheRecordRef(result.43.metadata)
  }

  "result.43.metadata" : {
    "__typename" : Metadata
    "status" : someMetadata
  }

  "result.42.metadata" : {
    "__typename" : Metadata
    "status" : someMetadata
  }

  "result.42" : {
    "__typename" : Result
    "id" : 42
    "metadata" : CacheRecordRef(result.42.metadata)
  }
}
```

**Comment by OmarAlgo** [comment]
Yeah you were absolutely right. There are two request which run simultaneously and the second one is messing up the cache. It goes like:
```
query GetNotes($orgId: ID!, $userId: ID!) {
  macros(input: {
    orgId: $orgId,
    userId: $userId,
    includeFields: true
  }) {
    count,
    results {
      id,
      userId,
      tags {
        name {
          value,
          aliases
        },
        type
      },
      blocks {
        secId,
        secName,
        content,
        fields {
          name {
            value,
            aliases
          },
          type
        }
      }
    }
  }
}
```
which gives me dump something like
```
LruNormalizedCache {
      "Macro.70e918b8" : {
        "__typename" : Macro
        "id" : 70e918b8
        "userId" : 03d295e8
        "tags" : [
          CacheRecordRef(Macro.70e918b8.tags.0)
        ]
        "blocks" : [
          CacheRecordRef(Macro.70e918b8.blocks.0)
        ]
      }
    
      "QUERY_ROOT" : {
        "macros({"input":{"includeFields":"true","orgId":"61b2bf20","userId":"03d295e8"}})" : CacheRecordRef(macros({"input":{"includeFields":"true","orgId":"61b2bf20","userId":"03d295e8"}}))
      }
    
      "Macro.b18d5fcd.tags.0.name" : {
        "__typename" : SlotName
        "value" : Normal Physical Exam
        "aliases" : [
          normal-physical
        ]
      }
    
      "Macro.70e918b8.tags.0.name" : {
        "__typename" : SlotName
        "value" : Brief Review of Systems
        "aliases" : [
          brief-review
        ]
      }
    
      "macros({"input":{"includeFields":"true","orgId":"61b2bf20","userId":"03d295e8"}})" : {
        "__typename" : QueryMacrosPayload
        "count" : 2
        "results" : [
          CacheRecordRef(Macro.70e918b8)
          CacheRecordRef(Macro.b18d5fcd)
        ]
      }
    
      "Macro.b18d5fcd.tags.0" : {
        "__typename" : Tag
        "name" : CacheRecordRef(Macro.b18d5fcd.tags.0.name)
        "type" : MACRO_NAME
      }
    
      "Macro.b18d5fcd" : {
        "__typename" : Macro
        "id" : b18d5fcd
        "userId" : 03d295e8
        "tags" : [
          CacheRecordRef(Macro.b18d5fcd.tags.0)
        ]
        "blocks" : [
          CacheRecordRef(Macro.b18d5fcd.blocks.0)
        ]
      }
    
      "Macro.70e918b8.tags.0" : {
        "__typename" : Tag
        "name" : CacheRecordRef(Macro.70e918b8.tags.0.name)
        "type" : MACRO_NAME
      }
    }
```
I am unable to figure out the issue in here.

**Comment by martinbonnin** [comment]
Just making sure I got this right, what you're doing is:

```
GetData // goes to the network
GetNotes // goes to the network
GetData // should go to the cache but goes to the network instead
```
?

Since you're only querying for `id` on `result`, this will be the only field to be normalized. All the others will be duplicated. Usually, it's best if all objects contain an `id` but it shouldn't prevent caching nevertheless.

I noticed the cache key in your last exemple starts with an uppercase letter and your initial `CacheKeyResolver` would use lowercase instead. Maybe that's a hint. If not, you can dump the cache after each step and try to see from there what field might be missing.

**Comment by OmarAlgo** [comment]
I am individually running all graphql calls so that I get to know which call voids the cache. Also I am not using lowercase now in the cacheKeyResolver. So what I am doing is:
```
GetNotes // goes to the network
GetNotes // should go to the cache but goes to the network 
```
If the number of ```macros``` returned in the ```GetNotes``` query are few i.e, 2 in the example dump I showed in the previous comment, then the cache works like a charm. But I tried this query when the number of ```macros``` returned were around 30+ then the cache failed. The problem in this I think after printing the dump after every call as you said is that the ```CacheRecordRef``` in the root of the query is missing in the dump. The weird part is that it happens only when the number of records returned are greater than 10 else it works fine. Any clue is appreciated.

**Comment by martinbonnin** [comment]
It's hard to tell without a way to reproduce. You can try to add breakpoints to [CacheFieldValueResolver](https://github.com/apollographql/apollo-android/blob/8c1f69bd21af97574875cab2791b1065f4c31dd7/apollo-normalized-cache/src/commonMain/kotlin/com/apollographql/apollo/cache/normalized/internal/CacheFieldValueResolver.kt), lines 42 and 54 are the actual places where the cache miss would happen. From there you'll be able to find the cache key that is missing, maybe that'll give a hint.

**Comment by OmarAlgo** [comment]
So I have figured out the issue here. As per the documentation earlier, the size of LruNormalizedCacheFactory was 1024*10 bytes because of which the cache was evicted and hence the cache miss. Just read in the latest update of the documentation you made to take is 10 mb i.e, 10*1024*1024 and it resolved the issue. Thanks for the help!

**Comment by martinbonnin** [comment]
That makes a lot of sense 👍 . I'll add a note to the troubleshooting guide.
