### ISSUE TITLE
With CACHE_AND_NETWORK, don't provide network results if same as cache results

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-android#2448]
**Is your feature request related to a problem? Please describe.**

Yes, currently I get a callback with the data twice—once with the cache data, and once with network data, even when they're the same. Which means to avoid unnecessary rerenders, I have to do a check like this: 

https://github.com/GraphQLGuide/guide-android/commit/09fbfec63a86f743399f986cac304918a04e1f96

**Describe the solution you'd like**

Perhaps the general solution is: when watching any query, if I've received certain data, I don't want to receive that same data again. (Regardless of whether identical data comes in from the NETWORK of a CACHE_AND_NETWORK, or another overlapping query elsewhere in the app, or even a mutation/cache edit that sets identical data.)

**Comment by martinbonnin** [comment]
Hi! I think issues like deduplication and debounce are better addressed by frameworks like `RxJava` and/or `coroutines` who have specialised methods for this. For an example, with coroutines, it would be as easy as:

```kotlin
apolloCall.toFlow(). distinctUntilChanged().collect {
    // update UI here
}
```

Since the generated models are data classes, that would work out of the box.

**Comment by martinbonnin** [comment]
@lorensr would that be ok with you? I'd really like to keep the apollo-android API as small and focused as possible. I'll close this issue if that's ok.

**Comment by lorensr** [comment]
Sounds good! Thank you ☺️
