### ISSUE TITLE
For input string: "null" error in trying to build with gradle plugin. 

### ISSUE THREAD

**Issue by NathanWA** [apollographql/apollo-android#2450]
**Summary**
I get this error once I update to 2.2.x from 1.0.2
For input string: "null" 

No further explanation seems to be available. 
No indication of whether this is from schema.json, fragments.graphql, queries.graphql. 

**Version**
2.2.2

**Description**
The exact cause is not known. I get this message during build. 

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:generateBciDebugServiceApolloSources'.
	....
Caused by: java.lang.NumberFormatException: For input string: "null"
	at com.apollographql.apollo.compiler.parser.GraphQLDocumentParser.normalizeValue(GraphQLDocumentParser.kt:724)
	at com.apollographql.apollo.compiler.parser.GraphQLDocumentParser.usedTypeDeclarations(GraphQLDocumentParser.kt:652)
	at com.apollographql.apollo.compiler.parser.GraphQLDocumentParser.parse(GraphQLDocumentParser.kt:27)
	at com.apollographql.apollo.gradle.internal.ApolloGenerateSourcesTask.taskAction(ApolloGenerateSourcesTask.kt:130)

*Add context about the problem here. How it happened and how to reproduce it:  
I am not sure.
It has a very large schema.json. 
There are 68 lines with "defaultValue": "null". I don't know which one it doesn't like. 
If I could find out how to find file and line where error occurs, I can post more information.

**Comment by martinbonnin** [comment]
How did you generate your `schema.json`? Did you get it with introspection or something else? 

I think it should be `defaultValue: null` instead of `defaultValue: "null"`. We could be lenient to this but it's better to fix the issue at its roots.

**Comment by NathanWA** [comment]
It is from the server using ./node_modules/apollo/bin/run schema:download 
 It does say Warning: apollo update available from 2.27.0 to 2.28.3.

**Comment by NathanWA** [comment]
I can confirm that it does appear to be the introspection query at the server that is returning the lines that say defaultValue: "null"
I do not know what version they have on the server. A colleague is checking into it.

**Comment by martinbonnin** [comment]
Can you check if the server schema contains arguments definitions such as:

```graphql
type Hero {
  # the url of the avatar with an optional width parameter. If width is no passed, will use 500
  avatar(width: Int = null): String 
}
```
?

The default value could be interpreted as a `"null"` string, which makes no sense here since it's an Int

**Comment by martinbonnin** [comment]
@NathanWA any luck fixing that on the server-side?

**Comment by chadalton** [comment]
@martinbonnin On the server we do have some nullable floats that send back these different default values that is causing an issue. We use .NET Core and the GraphQL Conventions library to generate the schema, but nothing looks incorrect unless having nullable floats is a problem. Do you know why the last version of apollo didn't have an issue with this schema?

**Comment by NathanWA** [comment]
Chad has changed some things on the server side. 
Yet we still get the error. 
How can we find out what line this error is on? 
It's difficult to find out what part of the schema it is rejecting. 
Besides floats, are there other we should look at.

**Comment by martinbonnin** [comment]
@NathanWA, I think that will happen for all numeric values (floats/ints) as long as there is `"defaultValue": "null".`  in your introspection schema. You can do a search and replace `"defaultValue": "null".` -> `"defaultValue": null.` in your schema.json to confirm that it is the problem.

**Comment by martinbonnin** [comment]
https://github.com/apollographql/apollo-android/pull/2490#pullrequestreview-459566664 has just been merged and will be included in the next release. Can you try with the [snapshots](https://github.com/apollographql/apollo-android#releases) to confirm it works as expected?

**Comment by NathanWA** [comment]
Sure thing. 
I think I need more instructions on how to use a snapshot. 
It says to use this. 
repositories {
  maven { 
    url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
  }
}

But don't I also have to modify some other parts of the build.gradle?

**Comment by martinbonnin** [comment]
Thanks!

You'll need to add the repository in 2 places, your main `build.gradle.kts` for runtime dependencies and also your `buildscript {}` block or `settings.gradle.kts` depending how you apply the plugin. 

Then you'll need to use the latest SNAPSHOT version from https://github.com/apollographql/apollo-android/blob/master/gradle.properties#L2. Right now it's `2.2.4-SNAPSHOT`. 

That should be all that's needed, let me know how that goes.

**Comment by NathanWA** [comment]
This generated code but got two compiler errors from generated code:
Type inference failed. Expected type mismatch: inferred type is Input<String> but Input<GeoLocationInput> was expected
Type inference failed. Expected type mismatch: inferred type is Input<List<String>> but Input<List<RegistrationIdentifierInput?>> was expected
These are probably from these schema portions. 
          {
            "name": "location",
            "description": null,
            "type": {
              "kind": "INPUT_OBJECT",
              "name": "GeoLocationInput",
              "ofType": null
            },
            "defaultValue": "null"
          }
          {
            "name": "identifiers",
            "description": null,
            "type": {
              "kind": "LIST",
              "name": null,
              "ofType": {
                "kind": "INPUT_OBJECT",
                "name": "RegistrationIdentifierInput",
                "ofType": null
              }
            },
            "defaultValue": "null"
          },

**Comment by martinbonnin** [comment]
That looks like another issue. Can you check your classpath for `Input` classes that could nameclash with `com.apollographql.apollo.api` ?

**Comment by NathanWA** [comment]
I don't think there is anything clashing with it. 

The only suggestions it makes are Renderscipt or the apollo Input<V>.
We are not using renderscript. 
![Screen Shot 2020-08-07 at 11 25 10 AM](https://user-images.githubusercontent.com/1120121/89676606-ccc43880-d8a0-11ea-88f8-9b1682b5ca94.png)

**Comment by martinbonnin** [comment]
Interesting. Do you use Kotlin 1.4-rc or the new type inference by any chance? https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-4-m1-released/#new-type-inference

**Comment by NathanWA** [comment]
Kotlin version is 1.3.72
