### ISSUE TITLE
Required Field

### ISSUE THREAD

**Issue by lbg-reggar** [apollographql/apollo-android#2466]
**Is your feature request related to a problem? Please describe.**
It would be great to have the concept of a required field for caching purpose. Say, for example, you take the strategy to use `_id` as the cache key, it would be nice to have that automatically added to the query whenever it is available.

**Describe the solution you'd like**
It seems likely you could add a list of required fields to `ApolloExtension`, they are then automatically added to the queries iff it exists on that field (like `__typename`).

**Comment by martinbonnin** [comment]
Hi 👋 ! This feature seems similar to https://github.com/apollographql/apollo-android/issues/1977. Would you be ok if we move the discussion over there?

**Comment by lbg-reggar** [comment]
Didn't see that issue, but yeah this issue seems like a duplicate of that.
