### ISSUE TITLE
[apollo-api] move BigDecimal to a custom scalar adapter

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#2468]
I'm wondering whether it makes sense to remove the `BigDecimal` intermediate that we have in `apollo-api` at the moment given that GraphQL only has 32 bit integers and 64 bit doubles. 

That would simplify the code, potentially make it a bit faster and also help for multiplatform support (https://github.com/apollographql/apollo-android/pull/2467).

If users need more precision, they could define a CustomScalar adapter. We could even provide a default implementation to help onboarding.

**Comment by omainegra** [comment]
Is help wanted here? Is someone working on it already? This will greatly simplify the work needed to support JS

**Comment by martinbonnin** [comment]
@omainegra I started looking into this in https://github.com/apollographql/apollo-android/pull/2473 but I'm still not 100% clear what needs to be done. The main issue is that we currently read the whole json before mapping it to the model so at the time [we read the value from the json](https://github.com/apollographql/apollo-android/blob/58e17b960fdc181d04d904b616a80e80bb8ff453/apollo-api/src/commonMain/kotlin/com/apollographql/apollo/api/internal/json/ResponseJsonStreamReader.kt#L107), we don't know yet if that will end up in a Double, Int or CustomScalar field. 

It's working at the moment because we're guaranteed that `BigDecimal` can hold all values without losing precision but if we were to remove this intermediate, I think we would have to rewrite a lot of the parsing log to "pull" data from the parser rather than consume a `Map`. That might be doable but that seems complex.

**Comment by omainegra** [comment]
Yes, it looks more complex than I thought. maybe rewriting the parsing logic is better in the long term

**Comment by martinbonnin** [comment]
This is fixed in `3.0.0-alpha01`. `BigDecimal` has been moved to a custom adapter in [`apollo-adapters`](https://github.com/apollographql/apollo-android/blob/f91d351139213964d833189189d28337d98cf2c3/apollo-adapters/README.md). 

JS support is still ongoing. Let's follow up in this PR if needed: https://github.com/apollographql/apollo-android/pull/3208
