### ISSUE TITLE
Gradle Apollo plugin task

### ISSUE THREAD

**Issue by SivarajSubramanian1** [apollographql/apollo-android#2472]
**Is your feature request related to a problem? Please describe.**
In the ApolloPlugin, tasks are registered after the projects are evaluated. This makes harder for any other plugins to register dependency on apollo plugins. We created a plugin as a work around (current apollo plugin is not supporting that feature yet) to support fragments across multi module, but we are not able to register the dependency with apollo plugin as Gradle afterEvaulates are processed in random order. Gradle team also recommends not to register tasks in the afterEvaulate Block. 

**Describe the solution you'd like**
Move the task creation away from afterEvaluate block and have them in the apply method. Happy to pick this change, if your team is fine with this proposed change

**Comment by martinbonnin** [comment]
Thanks for reaching out! 

The main reason we need `afterEvaluate {}` at the moment is to handle the `generateKotlinModels` parameter which is used during task registration an is unfortunately not populated until the project is evaluated.

I've been investigating 2 solutions to this:

1. register all possible Java/Kotlin tasks and enable the appropriate ones lazily (https://github.com/apollographql/apollo-android/pull/1845). This approach significantly complexifies the plugin code, which is already complex, so I'd like to avoid it if possible.
2. use different plugin ids for Java and Kotlin: `com.apollographql.apollo-kotlin` and `com.apollographql.apollo-java`(https://github.com/apollographql/apollo-android/pull/2399). This approach would simplify the plugin code at the cost of a slightly more complex onboarding. One could even argue that being able to separate Java and Kotlin codegen could be a feature. That being said, that would most likely be a breaking change and require a major version bump.

Back to your original issue of supporting fragments multi-modules, there is an issue open about it: https://github.com/apollographql/apollo-android/issues/1973. It's definitely something that should be done inside the plugin.  If you have some ideas how to do it, feel free to join the discussion over there.

**Comment by SivarajSubramanian1** [comment]
Thanks @martinbonnin for the clarification.
