### ISSUE TITLE
Undeliverable exception when using with Rxjava 2

### ISSUE THREAD

**Issue by bacteria323** [apollographql/apollo-android#2479]
When using with Rxjava 2, there is an undeliverable exception even when error handler is set:

`
The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.apollographql.apollo.exception.ApolloNetworkException: Failed to execute http call
`

**Comment by martinbonnin** [comment]
Thanks for reaching out. Can you share a snippet of how you're using the RxJava extensions?

**Comment by bacteria323** [comment]
It looks similar but I am using it as

```
Rx2Apollo.from(query(<MyCustomQuery>)) // Observable<Response<T>>
                .firstOrError() // Convert the observable to a single
```

**Comment by martinbonnin** [comment]
Thansk, I'll give it a shot.

**Comment by bacteria323** [comment]
After a little more digging I found this is a problem with RxJava2. Exceptions are not swallowed after the observable is terminated so the socket timeout exceptions from apollo are being thrown as undeliverable exceptions. A global error handler has to be set so that the exceptions can then be further filtered and / or discarded.

**Comment by martinbonnin** [comment]
Glad that you found a solution. When the observable is disposed, the `ApolloCall` [should be cancelled](https://github.com/apollographql/apollo-android/blob/3d7e5ffcc1cfa7c0428f5bb42084e8919fbacea9/apollo-rx2-support/src/main/java/com/apollographql/apollo/rx2/Rx2Apollo.java#L92) and the socket timeout exception shouldn't be delivered so maybe there's something to investigate there as well. Do not hesitate to reopen this issue if it happens again.
