### ISSUE TITLE
Tweak the `ScalarType` API

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#2486]
Following up on https://github.com/apollographql/apollo-android/pull/2473#issuecomment-664906541, I didn't realise that the default adapters were use to save users to call `addCustomTypeAdapter`:

 Some adapters like `java.util.Date` currently have to be manually added using `addCustomTypeAdapter` while others like `com.apollographql.apollo.api.FileUpload` are registered automatically. 

We could instead declare the implementations and let the user register them as needed:

```kotlin
// build.gradle.kts
apollo {
   customTypeMapping.set(mapOf("TimeStamp" to "java.lang.Long"))
}

// Apollo.kt
apolloClientBuilder.addCustomTypeAdapter(CustomType.TimeStamp, ApolloCustomTypeAdapter.LongAdapter)
```

This makes everything explicit.

**Comment by tasomaniac** [comment]
What is the benefit of removing them? `FileUpload` type is added automatically to make it more convenient I guess. File upload feature is also weird anyways :)

**Comment by martinbonnin** [comment]
> What is the benefit of removing them?

Mostly API consistency and discoverability. 

There's a super tiny argument for performance, it might be faster to lookup the correct adapter if the list is small. But I wouldn't bet too much on that, if we do this, I think this would be mostly for API design reasons.

> FileUpload type is added automatically to make it more convenient I guess.

Yep, exactly. The default adapters are a convenience for some use cases. But to me that's some magic that hides how custom adapters are working. It took me a while to figure out why it wasn't required to register an adapter.

Also somewhat related, I think there is a confusion that CustomTypeAdapters could be use to "transform" generated models (and not only scalars), like moshi [custom type adapters](https://github.com/square/moshi#custom-type-adapters). Maybe we should rename to `ScalarTypeAdapter`.

Overall, small changes would make this API hopefully easier to understand.

**Comment by tasomaniac** [comment]
The last part is an important one. I am all for renaming it. Your suggestion is much more clear.

**Comment by martinbonnin** [comment]
We should also throw an error if trying to register a scalar type that's not in the schema: https://github.com/apollographql/apollo-android/issues/2721
