### ISSUE TITLE
Multiple schemas in same project - Apollo Android

### ISSUE THREAD

**Issue by pratthama-appdesk** [apollographql/apollo-android#2487]
Can anyone tell me how to use 2 different schemas in one project with 2 different URLs on Android?

**Comment by martinbonnin** [comment]
You can use the `service` method in your Gradle configuration:

apollo {
  service("github") {
    sourceFolder.set("com/github")
    rootPackageName.set("com.github")
  }

  service("fullstack") {
    sourceFolder.set("com/apollographql/fullstack")
    rootPackageName.set("com.apollographql.fullstack")
  }
}

(Sample there: https://github.com/martinbonnin/apollo-android-samples/tree/master/multiple-services)

**Comment by martinbonnin** [comment]
@pratthama-appdesk let us know if you need more information, else I'll close this issue.

**Comment by pratthama-appdesk** [comment]
> @pratthama-appdesk let us know if you need more information, else I'll close this issue.

Hi, thanks for information. 
I wrote an article on medium on getting started with graphql in android with kotlin using coroutines 
https://medium.com/@arora.prattham/graphql-in-android-using-kotlin-with-coroutines-2b00a462e765

P.S you can close the issue. Thanks!

**Comment by karanatwal** [comment]
Hi, I am getting - Could not set unknown property 'rootPackageName' for object of type com.apollographql.apollo3.gradle.internal.DefaultService

**Comment by BoD** [comment]
@karanatwal Since this issue was opened, Apollo Kotlin v3 was released and the syntax has changed a bit. In particular the equivalent of `rootPackageName` is now `packageNamesFromFilePath(rootPackageName)`.
[Here](https://www.apollographql.com/docs/kotlin/advanced/plugin-configuration/#using-multiple-graphql-apis) is the relevant information for v3 in the documentation.

**Comment by istashak** [comment]
Is it possible to have a single Apollo service be composed of multiple SDL files and multiple operation files in different directories? If so, can someone please push me to an example or copy/paste a gradle snippet that demonstrates the magic necessary to make this happen?

**Comment by BoD** [comment]
@istashak If you put your `*.graphql` (operations) and `*.graphqls` (SDL) files in any folder inside `src/main/graphql` and they will be picked up by default.

Note that although multiple SDL files is permitted, only one of them should contain the top level `Query` type.  If you do have several `Query` types then you will need to configure several services.
