### ISSUE TITLE
[Gradle plugin] add an option to fail compilation if a deprecated field is used 

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#2489]
To improve awareness of when deprecated schema fields are used, add a configuration option to the plugin to make the build fail:

```kotlin
apollo {
  failOnDeprecatedFieldUsage.set(true) // defaults to false
}
```

On failure, display the file and line where the field is used.

**Comment by kenyee** [comment]
Would like to have an option to have it show warnings for all usages too.
We have so many in our project that it'll take a while to fix 😔

**Comment by martinbonnin** [comment]
👍  Makes sense, this was my initial thought as well but I'm not sure how widespread it is to use enums in Gradle DSL Apis:

```kotlin
enum class DeprecatedFieldReporting {
  IGNORE,
  WARNING,
  ERROR
}

class CompilerParams {
  val deprecatedFieldReporting: Property<DeprecatedFieldReporting>
}
```

Does that feel ok?

**Comment by kenyee** [comment]
Seems ok to me :-)
Maybe also add an Info level as well?  So it just prints out stuff instead of causing warnings in case people have their builds set to "warning = fail build"...

**Comment by martinbonnin** [comment]
> So it just prints out stuff instead of causing warnings in case people have their builds set to "warning = fail build"...

I had `project.logger.warn("")` in mind for the `WARNING` case. Can this be configured to make the build fail? Or are there any other ways to output warnings you were thinking about?

**Comment by kenyee** [comment]
looks like that should work for warning levels:
https://docs.gradle.org/current/userguide/logging.html#sec:sending_your_own_log_messages

But I think you have to throw a GradleException to get build to fail.  Would also be great to have some sort of standard prefix like "Deprecated GraphQL Field: xxx in file yyyy" that's consistent so it's parseable by CI scripts that build summary page like BuildKite does.
