### ISSUE TITLE
CacheKeyResolver.fromFieldArguments should have access to the type information 

### ISSUE THREAD

**Issue by davidliu** [apollographql/apollo-android#2496]
Somewhat of an offshoot of the issue mentioned here: https://github.com/apollographql/apollo-android/issues/2233#issuecomment-632171723

For schemas that don't have globally unique ids, a common pattern is to use the `typename:id` for the cache key. However, for `fromFieldArguments`, we don't actually have access to the type information (`ResponseField.Type` only refers to the more generic meaning of type (e.g. Object, List, Int, etc.), so we need to do manual conversion from the field's name to the correct type (e.g. "organization" -> "Organization" in the linked comment). This is pretty tedious to do, as well as very brittle (no guarantee that "organization" is actually an "Organization"). It'd be great if we had access to the exact type information that the query was expecting for that field instead.

**Comment by martinbonnin** [comment]
One thought: when `fromFieldArguments` is called we don't know what concrete type the object will be. Therefore `__typename` will not be available. Unless of course the field is always queried on a concrete type, but that's not the general case.

Long story short, we can expose the GraphQL type name, which is, confusingly not `__typename`. We'll have to find a nice name for this.

**Comment by martinbonnin** [comment]
Actually, I just realized this information is available in the `dev-3.x` branch: https://github.com/apollographql/apollo-android/commit/56b4dd4855d1f94cef865a6f7e4c86954b215540

```
(field.type as ResponseField.Type.Named.Object).name
```

**Comment by martinbonnin** [comment]
`3.0.0-alpha01` now allows this:

```kotlin
  final override fun resolveField(field: CompiledField, variables: Executable.Variables, parent: Map<String, Any?>, parentId: String): Any? {
    var type = field.type.leafType()
    // Do something with type.name
    
    return super.resolveField(field, variables, parent, parentId)
  }
```

Note that for interface fields, `type.name` will contain the name of the interface so it will not be able to know in advance the concrete type that will be returned, therefore triggering a cache miss in most cases.
