### ISSUE TITLE
Impl folder was a bad idea :-(

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#250]
I'd like to propose a package structure:
android
-cache
-call
-converter
-util

It would be some things have to be public to hit stuff from converter in call and vice versa but I think for organization it will make sense as we grow larger.

thoughts? @sav007 @martijnwalraven @BenSchwab @brianPlummer

**Comment by sav007** [comment]
Makes sense, only we are going to have 2 caches, so we need 2 packages: one for httpcache another for normalized

**Comment by digitalbuddha** [comment]
Sure we can even do subpackages cache.http, converter.response

**Comment by BenSchwab** [comment]
Fine by me

**Comment by digitalbuddha** [comment]
I'll flip it in am. Thanks guys!!

**Comment by sav007** [comment]
@digitalbuddha @BenSchwab @marwanad 

This list of changes applicable only for `:apollo-runtime` module:

1. `com.apollographql.android` rename to `com.apollographql.apollo`
2.  all *public classes (doesn't mean everything else will be project protected) will be under `com.apollographql.apollo`
3. everything else that we assume not public will be moved to `com.apollographql.apollo.internal`
4. group logically classes under `impl` folder, for example `ApolloInterceptors` move to `com.apollographql.apollo.interceptor` or `com.apollographql.apollo.internall.interceptor` and so on.

**Comment by digitalbuddha** [comment]
I like it
