### ISSUE TITLE
Kotlin 1.4 support (kotlin-ios-x64 cannot be found on XCode)

### ISSUE THREAD

**Issue by tiwiz** [apollographql/apollo-android#2503]
**Summary**
Trying to build with the latest Apollo Multiplatform version, we get this error:

```
The Kotlin source set androidAndroidTestRelease was configured but not added to any Kotlin compilation. You can add a source set to a target's compilation by connecting it with the compilation's default source set using 'dependsOn'.
See https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#connecting-source-sets
w: Skipping "/Users/roberto/.gradle/caches/modules-2/files-2.1/com.apollographql.apollo/apollo-runtime-kotlin-ios-x64/2.2.3/f3251afe05e685012bed87d5b7b2ecde96a7704b/apollo-runtime-kotlin.klib" as it is a pre 1.4 library
e: Could not find "/Users/roberto/.gradle/caches/modules-2/files-2.1/com.apollographql.apollo/apollo-runtime-kotlin-ios-x64/2.2.3/f3251afe05e685012bed87d5b7b2ecde96a7704b/apollo-runtime-kotlin.klib" in [/Users/roberto/AndroidStudioProjects/kotlin-mp-movies, /Users/roberto/.konan/klib, /Users/roberto/.konan/kotlin-native-prebuilt-macos-1.4-rc1-40/klib/common, /Users/roberto/.konan/kotlin-native-prebuilt-macos-1.4-rc1-40/klib/platform/ios_x64].
```

preventing the project from building.

**Version**
2.2.3

**Description**
We added the sample code to reproduce the issue - https://github.com/playground4devs/kotlin-mp-movies/pull/2/files

**Comment by martinbonnin** [comment]
Hi! Thanks for linking a reproduction project 👍 

In that case, the apollo native libraries are not built fot 1.4 yet so you'll need to compile your project with Kotlin 1.3.72. I'm not 100% clear if we build with 1.4-rc but that doesn't feel super safe, we'll most likely do it once 1.4 reaches stable. 

More details there: https://discuss.kotlinlang.org/t/build-gradle-dependency-from-source/17408/6

**Comment by martinbonnin** [comment]
Thinking a bit more about this, I think we could start using 1.4-rc in the SNAPSHOTS so that we're ready when 1.4 ships.

**Comment by tiwiz** [comment]
Hey @martinbonnin thanks for the suggestion! Downgrading to 1.3.72 made it work, thank you!

**Comment by martinbonnin** [comment]
Version 2.3.1 is compiled against Kotlin 1.4
