### ISSUE TITLE
Query request doesn't work on Android 6 and 5

### ISSUE THREAD

**Issue by Edwhis** [apollographql/apollo-android#2516]
**Summary**
As title says - query request doesn't work on Android 6 and Android 5

**Version**
2.2.3

**Description**
I'm using kotlin multiplatform library for my project. Everything seems to be working fine on Android 7 and up, but query requests doesn't work on Android 6 and Android 5.  Mutation requests works as expected!
App is not crashing, but before every query logcat prints:
`Rejecting re-init on previously-failed class java.lang.Class<com.apollographql.apollo.network.http.ApolloHttpNetworkTransport$toHttpPostRequest$1$1>
`
I checked profiler and tried RequestBin - requests are not fired from phone. Any ideas?

**Comment by martinbonnin** [comment]
Thanks for reaching out! 

This is most likely coming from [this usage of `Map.forEach()`](https://github.com/apollographql/apollo-android/blob/1465640c4bd8920a3755d0df62b09e6ae568c262/apollo-runtime-kotlin/src/jvmMain/kotlin/com/apollographql/apollo/network/http/ApolloHttpNetworkTransport.kt#L174) that is a JDK8-only API, most likely not supported by older versions of Android. 

It's easy to replace that call and we should do it. I'm also curious if there are ways to detect at build time such usages to make sure this does not happen again.

In the meantime, you can enable these API by using desugaring like described there: https://developer.android.com/studio/write/java8-support#library-desugaring

**Comment by Edwhis** [comment]
Thanks, it worked!
