### ISSUE TITLE
Android Paging3 Support

### ISSUE THREAD

**Issue by nicusorflorin** [apollographql/apollo-android#2519]
**Is your feature request related to a problem? Please describe.**

Cannot hook a Watcher to a PagingSource.

**Describe the solution you'd like**

The Arhitecture Components Library Paging3 changed how things get sent into adapter. A PagingSource is necessary that contains a suspend function called load. Here we are supposed to hook the api call in a synchronous way. This is not possible with a Watcher which provides us with a toFlow() method only. I would like to be able to have a watcher in my PagingSource so it triggers a reload if any item is changed

**Comment by martinbonnin** [comment]
Hi! Unfortunately, I don't see an elegant way to do this for the time being. The closest would be to create a new coroutine scope from `PagingSource.load()` and call `PagingSource.invalidate()` when the second watcher result is collected. But that would most likely leak the watcher since there's no way of knowing when the DataSource is cancelled.

Room uses weak references to mitigate that: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/room/runtime/src/main/java/androidx/room/paging/LimitOffsetDataSource.java#74

I'm personally not a fan of weak references but if there's no other option, I guess it's something we could add to get a better pagination experience.

**Comment by nicusorflorin** [comment]
Yeah, paging2 was using callbacks which worked without issue with apollo. I was thinking something similar with the invalidate approach, I was hoping for something that would not result in extra calls being made. Can we expect a workaround/solution soon? At least in an alpha version?

**Comment by martinbonnin** [comment]
Would you be able to share your Paging2 code or pseudo code? I can try to convert that to Paging3.

**Comment by nicusorflorin** [comment]
Not easily there are multiple abstraction levels with business logic and the like but basically:
`
open class SearchDataSourceFactory<T : CoreRecyclerViewItem>(
        private val graphqlApi: GraphqlApi,
        private val parserFunc: (List<SearchQuery.Edge>) -> List<T>,
        private val filters: List<NodeType>? = null,
        private val searchText: String? = null,
        subscriptions: CompositeDisposable,
        queryErrorEvent: SingleLiveEvent<QueryError>) : RxDataSourceFactory<T>(subscriptions, queryErrorEvent) {

    /**
     * Call Api, parse the response and invoke callback.
     * If IllegalStateException, call handleSignaled
     */
    override fun load(cursor: String?, pageSize: Int, callback: BaseDataSource.AbstractLoadCallback<T>,
                      handleSignaled: (Disposable) -> Unit): Disposable {

        return graphqlApi.getNodesService().searchFilterItems(searchText,
                filters = Filters(nodeTypes = Input.fromNullable(filters)),
                pageSize = pageSize, cursor = cursor)
                .subscribeWith(object : DefaultDisposableObserver<Response<SearchQuery.Data>>() {

                    override fun onNext(response: Response<SearchQuery.Data>) {

                        if (response.hasErrors()) {
                            callback.onError(QueryError(0, graphErrors = response.errors?.toGraphErrorList(), operation = response.operation()))
                        }

                        try {
                            val items = parserFunc.invoke(response.data()?.items ?: emptyList())
                            callback.onResult(items, nextPageCursor(response))
                        } catch (e: IllegalStateException) {
                            handleSignaled.invoke(this)
                        }
                    }

                    override fun onError(e: Throwable) {
                        callback.onError(QueryError(0, e))
                    }
                })
    }

    private fun nextPageCursor(response: Response<SearchQuery.Data>): String? {
        val pageInfo = response.data()?.pageInfo
        val hasNextPage = pageInfo?.hasNextPage ?: false
        return if (hasNextPage) pageInfo?.lastCursor as? String else null
    }
}`

It made use of the PageKeyedDataSource, whose load functions received a callback that could be called asynchronously. It isn't a nice solution either, but we hadn't found a better one at that time. That's why we want to switch to Paging3 to cleanup the code as well.

**Comment by martinbonnin** [comment]
Thanks!!

```
open class SearchDataSourceFactory<T : CoreRecyclerViewItem>([...],  subscriptions: CompositeDisposable,)
```

I guess the `subscriptions` up there is where you keep all active subscriptions and you somehow have a way of managing the lifecycle of these subscriptions outside the adapters/paging?

The closest I can think right now is to create a new coroutines scope to invalidate when the watcher emits for the second time:

```kotlin
        val deferred = CompletableDeferred<List<Int>>()
        scope.launch {
            apolloClient.query(..).toFlow().collectIndexed { index, value ->
              if (index == 0) {
                  deferred.complete(value)
              } else {
                  invalidate()
                  cancel()
              }
            }
        }
        return deferred.await()
```

You would then have to manage the `scope` manually and cancel it appropriately. Also, I'm not 100% sure of how the deferred would cancel up there but I think something along these lines might work.

**Comment by nicusorflorin** [comment]
Tried it, but it doesn't really work since the collect is being called for subsequent pages load too, which trigger the invalidate which triggers the reload, and basically we have a loop that loads the first page again and again

**Comment by martinbonnin** [comment]
> Tried it, but it doesn't really work since the collect is being called for subsequent pages load too, which trigger the invalidate which triggers the reload, and basically we have a loop that loads the first page again and again

Shouldn't you stop receiving updates after the first one ?

* load 3 pages of data
* something changes on page 3
* the watcher for page 3 emits a new list -> this calls invalidate
* all 3 watchers are cancelled
* the 3 pages get loaded again
* as long as nothing changes data, there shouldn't be any update?

**Comment by nicusorflorin** [comment]
Yeah there is a bug in my code.

**Comment by martinbonnin** [comment]
Closing this issue, please leave a message if you want me to reopen it.

**Comment by axiel7** [comment]
Has anyone managed to successfully implement this?
