### ISSUE TITLE
Feature Request: Streaming Json parser

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#2523]
This is a feature request to make the Json parsing logic use a single pass "streaming" (or "pull") parser, (like Moshi uses for an exemple). This would make Json parsing faster compared to the current approach.

Our current parser parses in two passes:
* a [first pass](https://github.com/apollographql/apollo-android/blob/905620cd98dfb5cbb07b5a540558c1cc761c45e1/apollo-runtime/src/main/java/com/apollographql/apollo/response/OperationResponseParser.java#L94) where the Json is converted to a `Map`
* a [second pass](https://github.com/apollographql/apollo-android/blob/905620cd98dfb5cbb07b5a540558c1cc761c45e1/apollo-runtime/src/main/java/com/apollographql/apollo/response/OperationResponseParser.java#L97) where the `Map` is converted to the generated models.

This was made because current fragments could contain the same field multiple times and it is impossible to "go backwards" and re-read the same field multiple times in a streaming parser. With the work from @sav007 for modelling fragments as interfaces  (#2478), switching to a streaming parser might become possible.

A benchmark comparing Apollo `SimpleOperationParser` to Moshi ([benchmark source](https://github.com/martinbonnin/apollo-android-samples/blob/e7f093ebae93e032f009a6b343230f3995f8b27d/android-perf/src/main/java/com/perf/MainActivity.kt#L22)) gives the following results:

``` 
Benchmark Apollo 3.63ms
Benchmark Moshi  1.60ms
```

That's the average time to parse a 52kB json on a Pixel 3XL averaged 100 times. A lot of factors come into play but there are reasons to think the performance could be greatly improved by switching to a streaming parser. Another benefit is that the type of the field will most likely be known at the time we parse the Json so we won't have to convert to/from `BigDecimal` or other intermediate types anymore (see #2468).

**Comment by martinbonnin** [comment]
@sav007 can we close this one?

**Comment by sav007** [comment]
Closing, I was thinking that we can migrate `RealResponseReader ` to stream parser but we blocked right now by `ResponseNormalizer` so we can't touch `RealResponseReader` now.
