### ISSUE TITLE
How to pass data/metadata to ApolloInterceptor or Okhttp.Interceptor?

### ISSUE THREAD

**Issue by zoopolitic** [apollographql/apollo-android#2527]
**Question.**

There is an ability in OkHttp to attach the metadata to the request by using `Request.tag(Class<*>)` function, this data can be then accessed in the interceptor itself. Since retrofit uses proxy `OkHttpCall` class to perform the operation it allows passing okhttp tag via `@Tag` annotation.

Is there some mechanism in Apollo client to pass data to either `ApolloInterceptor` or directly to the `OkHttp.Interceptor`. This data will only be used in the interceptor itself. The use case is when I want to have some configuration on a per-request basis.

Thanks

**Comment by martinbonnin** [comment]
Hi! As far as I know, there's no way to attach arbitrary `@Tags` like retrofit is doing. 

What you can do is use `ApolloQueryCall.Builder.requestHeaders()` to add headers that you can read (and even remove if you don't want them to be transmitted) in your interceptor. This will allow you to pass arbitrary Strings to your interceptor. If you really need arbitrary objects, you could use this string as a key and store your objects in another map. Not a perfect solution but that could do the trick while we figure out a more flexible api.

**Comment by zoopolitic** [comment]
Headers are what I have in mind atm, but it only allows strings while I need arbitrary objects as you mentioned. Thanks for the response

**Comment by zoopolitic** [comment]
@martinbonnin If I go with a map approach I definitely want to bind the lifetime of the map to the lifetime of the `ApolloClient` and lifetime of each entry in the map to the lifetime of the `InterceptorChain`. Any suggestions of how to do this?

I see the `ApolloCallTracker` class but can't find a way to get an instance of it

**Comment by martinbonnin** [comment]
>  I definitely want to bind the lifetime of the map to the lifetime of the ApolloClient and lifetime of each entry in the map to the lifetime of the InterceptorChain

The only way I can see at the moment is do handle the lifecycle outside apollo something like:

```kotlin
// Some global thread safe map
val map: MutableMap<String, Any>()
map.put(requestUuid, myObj)
apolloClient.query(query).toFlow().collect {
   // do something with the results 
}
map.remove(requestUuid)
```

I know this is not great but it _should_ work.
