### ISSUE TITLE
RealApolloCall.toBuilder() does not respect useHttpGetMethodForQueries

### ISSUE THREAD

**Issue by ubuntudroid** [apollographql/apollo-android#2529]
**Summary**
When using `RealApolloCall.toBuilder()` the state of the `useHttpGetMethodForQueries` property is not set.

**Version**
2.3.0

**Description**
Steps to reproduce: call `RealApolloCall.toBuilder()` and check the returned builder. It doesn't take over the state of `useHttpGetMethodForQueries` from the original call instance.

The fix is quite simple, just call `useHttpGetMethodForQueries(useHttpGetMethodForQueries)` when constructing the builder.

I'll provide a PR.

**Comment by ubuntudroid** [comment]
@tasomaniac any idea when the next release will be? We rely on GET requests for our CDN to work properly and won't be able to roll out until this fix has made it into a release.

**Comment by martinbonnin** [comment]
I'm hoping to make a Kotlin 1.4 release as soon as SqlDelight is available, hopefully soon-ish. 

In the meantime, any change you can use [ApolloClient.useHttpGetMethodForQueries](https://github.com/apollographql/apollo-android/blob/edda84c4ec76a995064cb42dce5a565fff6b6869/apollo-runtime/src/main/java/com/apollographql/apollo/ApolloClient.java#L724) as a workaround?

**Comment by ubuntudroid** [comment]
That unfortunately doesn't work for us as we are using `toBuilder()` to modify requests (which are configured via the configuration of the `ApolloClient`). So we are always running into the bug. :(

**Comment by martinbonnin** [comment]
Got it. Let's wait until tomorrow night in hopes of a 1.4 SQLDelight release and if not there I'll make a patch release?

**Comment by ubuntudroid** [comment]
That would be awesome, thanks a lot! 🙏

**Comment by ubuntudroid** [comment]
@martinbonnin Seems sqldelight has released their update. :)

**Comment by martinbonnin** [comment]
Yup, I'm on it, bintray is painfully slow but the first artifacts should be appearing on jcenter at the moment...

**Comment by martinbonnin** [comment]
And everything has made it to jcenter, let me know how it goes.

**Comment by ubuntudroid** [comment]
Looking good, many thanks! 🚀
