### ISSUE TITLE
Is it possible to use apollo-android v2 with Gradle 5?

### ISSUE THREAD

**Issue by RyPope** [apollographql/apollo-android#2536]
[The docs for v2 say that][1] 

> Gradle 6.x recommended. In 5.x, Gradle Metadata needs to be enabled by
> putting this into settings.gradle
> enableFeaturePreview("GRADLE_METADATA")

Which says that 6.x is simply recommended, but when I try to use Gradle 5 I get the error

    apollo-android requires Gradle version 6.0 or greater

Is there a workaround for this? Upgrading to Gradle 6 is not an option for my project right now.

[Here is the change][2] in apollo that bumps the minimum required Gradle version

  [1]: https://www.apollographql.com/docs/android/essentials/migration/#migrating-to-2x
  [2]: https://github.com/apollographql/apollo-android/commit/c5fee8e015ec18fd4e56510fe49c23cccf0add44#diff-bf25993eb69e5ccf9c0a98ed2a93eaf8R17

**Comment by martinbonnin** [comment]
I don't think there's a workaround to use Gradle 5 with version 2.3.0. 
I can check tomorrow if there's a way to disable the check (by adding a special plugin option) but that would require a new version in all cases. 
Can you detail a bit more why upgrading your project to Gradle 6 is not an option? I was under the impression that the upgrade should be transparent most of the times but if it's not, we should plan for longuer support periods.

**Comment by RyPope** [comment]
I work at a larger organization that has its own build system and manages dependencies internally so updating is just a little slower and for a major dependency like Gradle it requires some effort.

**Comment by martinbonnin** [comment]
It turns out it should be possible to run the plugin with 5.6. See https://github.com/apollographql/apollo-android/pull/2539

Anything lower than 5.6 will fail and as Gradle moves forward, I would strongly advise to update to more recent versions. The more you wait, the more effort will be needed to upgrade.

**Comment by RyPope** [comment]
I appreciate the prompt fix @martinbonnin ! Our Gradle 6 upgrade is most certainly underway but sometimes these things are easier said than done.
