### ISSUE TITLE
Cannot find generated code using apollo in android studio kotlin

### ISSUE THREAD

**Issue by IkwanThareq** [apollographql/apollo-android#2552]
**Question.**
Hai, currently i'm using apollo plugin version 2.3.0, and also try using version 2.3.1 same as this guide : https://www.apollographql.com/docs/android/essentials/get-started-multiplatform/ but i still cannot find auto generate code for used as the same graphql name. also i already place the graphql same level with the java, is that any step that i missing ?

<img width="419" alt="Screen Shot 2020-08-30 at 15 45 38" src="https://user-images.githubusercontent.com/26030107/91655018-e4759200-ead7-11ea-9417-bbd4ba6d0508.png">

**Comment by martinbonnin** [comment]
Hi 👋 
After you build your project, the generated files will be in `build/generated/source/apollo/`

**Comment by IkwanThareq** [comment]
Hi 👋 @martinbonnin 
i already check the directory where the code is generated but it's not there just like this :
<img width="427" alt="Screen Shot 2020-08-31 at 02 49 47" src="https://user-images.githubusercontent.com/26030107/91668181-ee79ae00-eb34-11ea-961a-440db8499945.png">

**Comment by martinbonnin** [comment]
Can you share the  contents of `morthie.graphql` ? 

Something else you can try is build with `--no-build-cache`: `./gradlew generateApolloSources --no-build-cache` to make sure this isn't a build cache issue.

**Comment by IkwanThareq** [comment]
Here is the content of mothie.graphql :
![Screen Shot 2020-08-31 at 11 28 21](https://user-images.githubusercontent.com/26030107/91682866-24db1b80-eb7d-11ea-8a26-dd3c1a830cdc.png)

**Comment by martinbonnin** [comment]
Apollo doesn't support unnamed queries, you should give a name to your query like `query GetCharacters` query. I suspect there's something else going on though because it should give an error.  Please let me know if it doesn't.

**Comment by IkwanThareq** [comment]
Ok i already add name to query and i already get the class just like this :
![Screen Shot 2020-09-01 at 21 52 30](https://user-images.githubusercontent.com/26030107/91867242-a033ee80-ec9d-11ea-92c5-b34bdcdee40a.png)
![Screen Shot 2020-09-01 at 21 52 21](https://user-images.githubusercontent.com/26030107/91867274-a88c2980-ec9d-11ea-9bd3-02f9e22b5458.png)

the class name is AnimationQuery is that correct in that path ? but i can't use it. Or should i rebuild again for the project ?

**Comment by martinbonnin** [comment]
`AnimationQuery` sounds good 👍 

You should be able to call it like this:

```kotlin
apolloClient.query(AnimationQuery())
```

Then I would recommend using the [coroutines extensions](https://www.apollographql.com/docs/android/advanced/coroutines/):

```kotlin
val response = apolloClient.query(AnimationQuery())toDeferred().await()
```

**Comment by IkwanThareq** [comment]
i see now i can use the AnimationQuery. Ok i will try use coroutines for access thanks for the support 👍

**Comment by martinbonnin** [comment]
Sounds good 👍 . I'm closing this issue, let me know if you want to reopen it.
