### ISSUE TITLE
Handling ApolloNetworkException caused by java.net.UnknownHostException

### ISSUE THREAD

**Issue by AhmedEssam-SameSystem** [apollographql/apollo-android#2553]
**Question.**
How can I handle : 
**Fatal Exception: com.apollographql.apollo.exception.ApolloNetworkException
Failed to execute http call**
which is caused by : 
Caused by java.net.UnknownHostException
**Unable to resolve host "**.*******.com": No address associated with hostname
okhttp3.Dns$-CC.lambda$static$0**

**Comment by martinbonnin** [comment]
Hi!

If you're using coroutines, you can catch this error by wrapping your query in a `try/catch` block like explained here: https://www.apollographql.com/docs/android/tutorial/08-add-a-details-view/#handle-protocol-errors.

RxJava uses `onError` and callbacks have `onFailure` for error handling. I'm closing this issue, please add a comment if it is not working, I'll reopen it.
