### ISSUE TITLE
[Gradle plugin] Allow gradle configuration for downloadApolloSchema

### ISSUE THREAD

**Issue by ikurek** [apollographql/apollo-android#2556]
**Is your feature request related to a problem? Please describe.**
When downloading GraphQL schema, gradle plugin should allow a default configuration, used when no parameters are provided. This would simplify the usage, and remove need to use separate shell scripts, when using `downloadApolloSchema` from CI/CD workflows. Currently, schema download requires at least four, manually provided parameters:
```bash
./gradlew :app:downloadApolloSchema 
    --service 'name of service'
    --variant 'android build variant'
    --endpoint 'url of endpoint'
    --schema 'path to schema file'
```
These parameters don't change too often during development, and could be configured once inside gradle setup block.

**Describe the solution you'd like**
Apollo configuration could contain specific fields for `downloadApolloSchema`, specified in `apollo {}` block:
```groovy
apollo {
	useSemanticNaming = true
	generateKotlinModels = true
        schemaEndpointUrl = "url of endpoint"
        schemaFilePath = "path to schema file"
}
```
Or work with `service {}` blocks:
```groovy
apollo {
	useSemanticNaming = true
	generateKotlinModels = true
	service("name of service") {
		sourceFolder = "service source folder"
		rootPackageName = "service root package name"
                schemaEndpointUrl = "url of endpoint"
                schemaFilePath = "path to schema file"
	}
}
```
The ability to download schema using only gradle command and specified configuration would simplify CI setup, and create consistent configuration environment for Apollo schema management.

**Comment by martinbonnin** [comment]
Hi 👋 

Can you take a look at `service.introspection`? By default, it should be enough to only specify the endpoint url:

```
apollo {
  service("someService") {
    // ...
    introspection {
      endpointUrl = "https://host.name/graphql"
    }
  }
}
```

This should add a task named `downloadSomeServiceApolloSchema` that downloads the schema.

**Comment by ikurek** [comment]
@martinbonnin I've tried Your solution, and it throws an exception due to missing parameter:
```
No value has been specified for property 'schemaRelativeToProject'
```
I've tried to specify this parameter in `apollo {}`, `service("service name") {}` and `introspection {}` and every time it fails to find required property.
```
Could not set unknown property 'schemaRelativeToProject' for object of type com.apollographql.apollo.gradle.internal.DefaultIntrospection
```
Is there any other thing that needs to be done in order for this to work?

**Comment by martinbonnin** [comment]
Hi! Sorry for the delay! 

The below should work (no need to wrap in `android {}` and replace `schemaFile` with `schemaPath`}:

```groovy
apollo {
    useSemanticNaming = true
    generateKotlinModels = true
    service("myservice") {
        schemaPath = "../schema.json"
        introspection {
            sourceSetName = "main"
            endpointUrl = myGraphqlUrl
        }
    }
}
```

The reason we have both `schemaFile` and `schemaPath` is to support overriding queries for Android variants. `schemaFile` is meant to be used from `onCompilationUnit{}` and `schemaPath` being a string is meant to be used from `service {}` and can be resolved against individual Android variants.

Of course there's usually only one schema per service but our current gradle configuration allows to override the schema...

The more I think about it, the more I believe we could remove variants supports. That'll simplify configuration and reduce build times. And R8 could remove dead code for unused queries if variant specific queries is really needed. 

Let me know if replacing `schemaFile` with `schemaPath` works for you in the short term.

**Comment by ikurek** [comment]
@martinbonnin This works like a charm, thank You very much 😄 But I still think, that these options should be described in the documentation, so they're easier to find and understand.
