### ISSUE TITLE
Fix TODO log me, introduce logger

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#256]
We need to have the way to log internal errors / debug in `:apollo-runtime` module

**Comment by digitalbuddha** [comment]
I vote for Timber especially if we are going android route.

**Comment by sav007** [comment]
@digitalbuddha unfortunately we cant use Timber for runtime module as it depends on Android, but we decided to keep it pure java. So the only way is to provide own interface, and if user wants to enable logging he must implement it, the same way as SqlBrite does:
https://github.com/square/sqlbrite/blob/master/sqlbrite/src/main/java/com/squareup/sqlbrite/SqlBrite.java#L235

And  if we going to have android module we will implement it as: 
https://github.com/square/sqlbrite/blob/master/sqlbrite/src/main/java/com/squareup/sqlbrite/SqlBrite.java#L39

**Comment by digitalbuddha** [comment]
Sounds great!
