### ISSUE TITLE
Multiple schema support

### ISSUE THREAD

**Issue by gayathri-nair03** [apollographql/apollo-android#2565]
I am on version 1.0.0 of graphql on Android. Can i still use multiple schema.json files in my single app? Or do i need to upgrade to 1.3x?

**Comment by martinbonnin** [comment]
Hi! `1.0.0` is pretty old and uses the Groovy gradle plugin. If I remember correctly, you can have multiple schema.json files if you organise them like this:

```
src/main/graphql/service1/schema.json
src/main/graphql/service1/query.json
src/main/graphql/service2/schema.json
src/main/graphql/service2/query.json
```

I would recommend updating to a more recent version that allows to define schemas explicitely though.

**Comment by gayathri-nair03** [comment]
Thanks @martinbonnin For the prompt reply. Also how do I read these schema.json files in my build.gradle?

**Comment by martinbonnin** [comment]
If I remember correctly, you don't need to configure the location of the `schema.json` files in your `build.gradle` files. The plugin had some logic to find them automatically. But again, this was a long time ago and this logic was pretty complex. It's one of the reason we rewrote the gradle plugin in Kotlin. So updating to a more recent version is certainly your best bet.

**Comment by gayathri-nair03** [comment]
Hey @martinbonnin thanks again! We will move to a newer version soon, but for sometime more, we will have to stick to this old version. Hence these doubts.
I made changes as per your suggestions, but the build kept failing because the model classes were not getting generated. Any help here?

**Comment by martinbonnin** [comment]
If you make a small reproducer somewhere I can take a quick look but `1.0.0` is not something we typically support. 

Another option that might be easier until you update is to make a separate module for your second schema.

**Comment by gayathri-nair03** [comment]
@martinbonnin - Some clean builds and a new issue popped up. There are 2 schemas - schema1.json and schema2.json.
Schema is not configured for subscriptions -> this error has been coming for the schema2.json. In the same folder as schema2.json, i have a subscription.graphql file present too. 
any help here?

**Comment by gayathri-nair03** [comment]
Invalid or incomplete schema, unknown type: SubscriptionHasThrowable. Ensure that a full introspection query is used in order to build a client schema.
I have one IntrospectionQuery.graphql in my project.

**Comment by martinbonnin** [comment]
```
Invalid or incomplete schema, unknown type: SubscriptionHasThrowable. Ensure that a full introspection query is used in order to build a client schema
```

That's an error from the old node cli. Not really sure what this is. An "introspection query" is used to get `schema.json` from your backend. Usually it's not something you would add to the queries you use in your project so I don't think you need any `IntrospectionQuery.graphql`

**Comment by gayathri-nair03** [comment]
@martinbonnin - Hey Martin, I made a different sample project in which I bumped up the version to 2.3.1 and used the 2 different schemas and everything worked fine. Project compiled, built and run successfully. Model classes generated properly. 
Then I simply bumped down the version back to 1.0.0 (and made the necessary changes, specified outputPackageName etc), but here the model classes were not generated at all. Not sure why. 
<img width="1678" alt="Screenshot 2020-09-10 at 1 11 47 PM" src="https://user-images.githubusercontent.com/7712040/92696323-51561b00-f367-11ea-883d-f929eacc07e1.png">
<img width="1000" alt="Screenshot 2020-09-10 at 1 13 24 PM" src="https://user-images.githubusercontent.com/7712040/92696404-73e83400-f367-11ea-9316-299aed0ea83f.png">

**Comment by martinbonnin** [comment]
Hi! I'm sorry I won't be able to help much more there. 

Too many things have changed since `1.0.0` and updating your project to a more recent version is the way forward. As said above, if you really really really want to keep `1.0.0`, make two gradle modules for your two different schemas.

**Comment by gayathri-nair03** [comment]
Thanks for all the help!
