### ISSUE TITLE
[FileUpload] Remove reflection

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#2570]
There is some reflection in how we handle `FileUpload`: https://github.com/apollographql/apollo-android/blob/50482e5c8143e9b98acd3a5847b9a18f5501894d/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloServerInterceptor.kt#L239

We should remove it to save users proguard configuration and improve performance. Also this will not work for multiplatform.

**Comment by BreSmit521** [comment]
We're running into an issue with this with R8 is there a temporary workaround until this is released?

**Comment by martinbonnin** [comment]
The below should do it:

```kotlin
-keep class * extends com.apollographql.apollo.api.Input
```

Let me know if it worked, I'll add it to the docs.

**Comment by BreSmit521** [comment]
Thanks for the quick reply!! Unfortunately, after trying this I'm still seeing the same error =\ If it helps at all the specific model we're using is actually the FileUpload model, although not sure if that matters

**Comment by martinbonnin** [comment]
Can you share a stacktrace? I would expect only `Input` subclasses to be affected but maybe there something else.

**Comment by BreSmit521** [comment]
Absolutely,

` {"errors":[{"message":"Variable \"$input\" got invalid value { body: \"\", uploadAttachments: [\"image/jpeg\"], scope: { id: \"05107586-0363-4f16-ac8d-7ff1b03e8090\", type: \"conversation\" }, id: \"f1fe00d8-06df-4188-9162-2b00c825325e\", d: [{}] }; Field \"d\" is not defined by type CreateTextInput. Did you mean id?","locations":[{"line":1,"column":29}],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["GraphQLError: Variable \"$input\" got invalid value { body: \"\", uploadAttachments: [\"image/jpeg\"], scope: { id: \"05107586-0363-4f16-ac8d-7ff1b03e8090\", type: \"conversation\" }, id: \"f1fe00d8-06df-4188-9162-2b00c825325e\", d: [{}] }; Field \"d\" is not defined by type CreateTextInput. Did you mean id?","    at /ronin/node_modules/graphql/execution/values.js:116:15","    at coerceInputValueImpl (/ronin/node_modules/graphql/utilities/coerceInputValue.js:114:9)","    at coerceInputValueImpl (/ronin/node_modules/graphql/utilities/coerceInputValue.js:54:14)","    at coerceInputValue (/ronin/node_modules/graphql/utilities/coerceInputValue.js:37:10)","    at _loop (/ronin/node_modules/graphql/execution/values.js:109:69)","    at coerceVariableValues (/ronin/node_modules/graphql/execution/values.js:121:16)","    at getVariableValues (/ronin/node_modules/graphql/execution/values.js:48:19)","    at buildExecutionContext (/ronin/node_modules/graphql/execution/execute.js:184:61)","    at executeImpl (/ronin/node_modules/graphql/execution/execute.js:89:20)","    at Object.execute (/ronin/node_modules/graphql/execution/execute.js:64:35)","    at /ronin/node_modules/apollo-server-core/dist/requestPipeline.js:249:48","    at Generator.next (<anonymous>)","    at /ronin/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","    at new Promise (<anonymous>)","    at __awaiter (/ronin/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)","    at execute (/ronin/node_modules/apollo-server-core/dist/requestPipeline.js:228:20)","    at Object.<anonymous> (/ronin/node_modules/apollo-server-core/dist/requestPipeline.js:176:42)","    at Generator.next (<anonymous>)","    at fulfilled (/ronin/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]}}}],"extensions":{"tracing":{"version":1,"startTime":"2020-09-15T15:42:37.616Z","endTime":"2020-09-15T15:42:37.620Z","duration":3531874,"execution":{"resolvers":[]}}}}`

Then relevant code that contains the inputs
`CreateTextMutation(
        CreateTextInput(
            id = Input.optional(id),
            body = Input.optional(messageBody),
            uploadAttachments = Input.optional(attachments.map {
              FileUpload(
                  it.contentType, File(it.url).absolutePath
              )
            }),
            scope = Input.optional(
                CreateScopeIdInput(
                    id = scopeId, type = Input.optional(ScopeType.safeValueOf(entityType))
                )
            )
        )
    )`

**Comment by martinbonnin** [comment]
My bad, I mixed `Input` and `InputType`. Can you try the following?:

```
-keep class * implements com.apollographql.apollo.api.InputType
```

**Comment by BreSmit521** [comment]
Thank you so much!! The final exact line that fixed it for me was `-keep class * implements com.apollographql.apollo.api.InputType { *; }` Thanks again for all your help!

**Comment by martinbonnin** [comment]
Thanks for investigating this! Glad to hear it worked. I added a mention to the doc until we can remove reflection altogether: https://github.com/apollographql/apollo-android/pull/2581/files

**Comment by martinbonnin** [comment]
`3.0.0-alpha01` uses [FileUploadAwareJsonWriter](https://github.com/apollographql/apollo-android/blob/34eba7573ee2d7ef78aa875860c8f6c3f3b98510/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/internal/json/FileUploadAwareJsonWriter.kt#L10) to intercept uploads without relying on reflection and shouldn't require any proguard configuration.
