### ISSUE TITLE
Coroutines toDeferred extension doesn't respect structured concurrency 

### ISSUE THREAD

**Issue by R4md4c** [apollographql/apollo-android#2571]
**Summary**
Apollo's client Coroutines Extensions doesn't respect structured concurrency when the parent's job is cancelled. 

**Version**
2.3.1

**Description**

I'm having a flow like this 

```
buttonClicks.mapLatest { buttonType ->
    val queryButtonTypeQuery = getQueryFromButtonType(buttonType)
    apolloClient.query(queryButtonTypeQuery).toDeferred().await()
}.onEach { response ->
    // Do something with response.
}.collect()
```

Let's assume I'm clicking buttons quickly, I'd expected OkHttp cancelling requests in the logs since `mapLatest` cancels the old emission in favor of the new emission. However that never happens. 

On the contrary when using `toFlow().first()` rather than toDeferred() I can see OkHttp cancelling requests in the logs.
`I/okhttp.OkHttpClient: <-- HTTP FAILED: java.io.IOException: Canceled`

On Kotlin's Slack channel @streetsofboston has suggested to remove `toDeferred` and introduce an `await()` function that respects structural concurrency through a `suspendCancellableCoroutine`

```
suspend fun <T> ApolloCall<T>.await(): Response<T> =
        suspendCancellableCoroutine { cont ->
            enqueue(
                object : Callback<T>() {
                    override fun onResponse(response: Response<T>) {
                        cont.resume(response)
                    }
                    override fun onFailure(e: ApolloException) {
                        cont.resumeWithException(e)
                    }
                }
            )
        }
```

**Comment by martinbonnin** [comment]
Thanks for the detailed feedback! 

I'm curious, does that mean it's not possible to achieve structured concurrency using `CompletableDeferred`? I'm not sure why I used `CompletableDeferred` at that time.

In all cases, `await()` would also be more concise so it'd be a double-win 👍 . Do you feel like opening a pull request? I can look somewhere next week else.

**Comment by R4md4c** [comment]
> I'm curious, does that mean it's not possible to achieve structured concurrency using CompletableDeferred? I'm not sure why I used CompletableDeferred at that time.

I think you can, `CompletableDeferred` takes an optional parent in the ctor, so probably you can do `CompletableDeferred(currentCoroutineContext()[Job])` in order to make that deferred cancellable by the parent. 

> In all cases, await() would also be more concise so it'd be a double-win +1 . Do you feel like opening a pull request? I can look somewhere next week else.
I think yes, I can do that, you should expect a PR soon by next week.

**Comment by martinbonnin** [comment]
> I think you can, CompletableDeferred takes an optional parent in the ctor, so probably you can do CompletableDeferred(currentCoroutineContext()[Job]) in order to make that deferred cancellable by the parent.

Got it, thanks for the explanation.

> I think yes, I can do that, you should expect a PR soon by next week.

Awesome 😃  Thanks!
