### ISSUE TITLE
[Bug] Incomplete query cache key

### ISSUE THREAD

**Issue by moshkit** [apollographql/apollo-android#2589]
**Summary**
"RESPONSE_FIELDS" in "Content.Data" class of generated GetContentQuery.kt file contains wrong value for "_or" and "_and" expressions.
As a result, queries with different parameters get wrong cache values and overwrite each other

**Version**
2.3.1

**Description**
Query request should contain "_and" or "_or" expressions with input parameters in it.

Example query:
```graphql
query getContent(
  $vendors: [Int!],
  $tags_filter_1: [Int!],
  $tags_filter_2: [Int!]
) {
  content(
    where:{
      state: {_eq: "available"},
      vendor_id: {_in: $vendors},
      _and : [
        { recipe_tags : { tag_id: {_in: $tags_filter_1}}},
        { recipe_tags : { tag_id: {_in: $tags_filter_2}}}
      ]
    }
  ) {id}
}
```

Generated code:
```kotlin
private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
    ResponseField.forList("content", "content", mapOf<String, Any>(
        "where" to mapOf<String, Any>(
            "_and" to
            "[{recipe_tags={tag_id={_in={kind=Variable, variableName=tags_filter_1}}}}, {recipe_tags={tag_id={_in={kind=Variable, variableName=tags_filter_2}}}}]",            
            "vendor_id" to mapOf<String, Any>(
                "_in" to mapOf<String, Any>(
                    "kind" to "Variable",
                    "variableName" to "vendors"))
        )
    )))
```

The content of "_and" tag is not parsed.

This data is used by [RealCacheKeyBuilder.kt ](https://github.com/apollographql/apollo-android/blob/8e60deee1ce4bb6a54f561921e78579fa2ccaa2f/apollo-normalized-cache/src/commonMain/kotlin/com/apollographql/apollo/cache/normalized/internal/RealCacheKeyBuilder.kt#L34)
for generating unique query key to get valid data from cache.

In current case, cache key generator skip variables in  "_and" block, and queries with different params (tags_filter_1, tags_filter_2) generate the same cache key.

**Solution**
Code generator should expand "_and" field value.
Temporary solution is to edit generated code in project this way:
```
"_and" to mapOf<String, Any>(
    "content_tags1" to mapOf<String, Any>(
        "_in" to mapOf<String, Any>(
        "kind" to "Variable",
        "variableName" to "tags_filter_1")),
    "content_tags2" to mapOf<String, Any>(
        "_in" to mapOf<String, Any>(
        "kind" to "Variable",
        "variableName" to "tags_filter_2"))
)
```

In future versions, should be added possibility to use List<Pair<String,Any>>
Plugin should generate code like this:
```
"_and" to listOf<Pair<String, Any>>(
    "content_tags" to mapOf<String, Any>(
        "_in" to mapOf<String, Any>(
        "kind" to "Variable",
        "variableName" to "tags_filter_1")),
    "content_tags" to mapOf<String, Any>(
        "_in" to mapOf<String, Any>(
        "kind" to "Variable",
        "variableName" to "tags_filter_2"))
)
```

**Comment by alexandrim0** [comment]
Vote for fix!

**Comment by Rangot** [comment]
+1
This fix is highly demanded for our project.

**Comment by martinbonnin** [comment]
Thanks for the bug report! Tentative fix there: https://github.com/apollographql/apollo-android/pull/2592

**Comment by martinbonnin** [comment]
@Rangot @moshkit @alexandrim0 The fix is now merged. Any chance you can confirm it works for you with version 2.4.1-SNAPSHOT ? (See https://github.com/apollographql/apollo-android#snapshots for how to include snapshots repositories)

**Comment by alexandrim0** [comment]
Need some time for checking.
Thank you!

**Comment by moshkit** [comment]
@martinbonnin 

#2610 

 - Code generation is ok
 - Bug with overriding cache keys: fixed!

Thank you a lot!
