### ISSUE TITLE
Is it possible to convert a BigInt graphQL field to a Long one in Kotlin ?

### ISSUE THREAD

**Issue by michgauz** [apollographql/apollo-android#2590]
Hello,

It seems, a `BigInt` graphQL field is converted to `Any` in a generated Apollo Query in Kotlin.

Is this working as intended ?
Is there any break to cast it as a specific known Kotlin class (Maybe `Long`) ?

Thank you

**Comment by martinbonnin** [comment]
Hi! 
GraphQL has no `BigInt` type. To have them mapped as Long in generated models, you'll need to define a CustomTypeAdapter as defined [here](https://www.apollographql.com/docs/android/essentials/custom-scalar-types/)
Let me know if that worked !
