### ISSUE TITLE
Disconnect from Web socket 

### ISSUE THREAD

**Issue by gayathri-nair03** [apollographql/apollo-android#2600]
I am using the apollo graphl library for an android app. Version 1.0.0.
I am using apollo gql subscriptions for a web socket connection and subsequent subscription to a topic. I wanted to know a few things:
1. If the app goes into background, after the web socket connection is established, does the connection stay or does apollo gql kill it? If you do kill it, do you kill it instantly (on app bkgd) or a after x seconds?
2. Is there anyway I can override this behavior? I dont want the web socket connection to be killed after app goes into bkgd. I want to implement that logic myself. Is this possible? 
Pls let me know.

**Comment by martinbonnin** [comment]
Hi !

Apollo Android doesn't know anything about Android lifecycle or when you app goes in the background. In fact you can even run a subscription on the JVM without Android. So as long as you don't cancel your subscription or the app isn't killed, the connection should stay open.

If you don't want your app to be killed when going in the background, I would recommend using a foreground service. You can read more in the [Android documentation](https://developer.android.com/guide/background)

**Comment by gayathri-nair03** [comment]
Thank you @martinbonnin!

**Comment by martinbonnin** [comment]
No worries! Let me know if you need anything else, if not, I'll close this issue.
