### ISSUE TITLE
Option to use kotlin-runtine with coroutines-native-mt

### ISSUE THREAD

**Issue by rantingmong** [apollographql/apollo-android#2619]
**Is your feature request related to a problem? Please describe.**
I'm currently using apollo for a multiplatform project. But using it alongside Ktor bumps Ktor's coroutines version down to 1.3.9 instead of 1.3.9-native-mt, and Ktor is enforcing native-mt usage of coroutines as of version 1.4.1

**Describe the solution you'd like**
Add a gradle version `com.apollographql.apollo:apollo-runtime-kotlin:2.4.0-native-mt` so that apollo and Ktor can use the same coroutines version.

**Comment by martinbonnin** [comment]
Good point. Maybe we should just use `-native-mt` in `apollo-runtime-kotlin` no matter what? `native-mt` is more experimental but as `apollo-runtime-kotlin` is experimental too, maybe it's not a big deal. Any other drawbacks of using `native-mt` instead of the regular artifact?

**Comment by rantingmong** [comment]
As far as I know, there are no obvious API limitations when using `native-mt`, except for the caution of possible memory leaks as specified [here](https://kotlinlang.org/docs/mobile/concurrency-and-coroutines.html#multithreaded-coroutines).

**Comment by martinbonnin** [comment]
I'm confused, the Ktor docs recommends using the single-threaded version there: https://kotlinlang.org/docs/mobile/concurrency-and-coroutines.html#ktor-and-coroutines

> Make sure that you use the single-threaded version of kotlinx.coroutines as a dependency for Ktor. Ktor for macOS and iOS requires this version

Has that changed recently?

**Comment by martinbonnin** [comment]
@rantingmong another way to look at this, can you try forcing the dependency in your project?

```kotlin
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core") {
    version { 
      strictly("1.3.9-native-mt-2")
    }
  }
```

**Comment by rantingmong** [comment]
> I'm confused, the Ktor docs recommends using the single-threaded version there: https://kotlinlang.org/docs/mobile/concurrency-and-coroutines.html#ktor-and-coroutines
> 
> > Make sure that you use the single-threaded version of kotlinx.coroutines as a dependency for Ktor. Ktor for macOS and iOS requires this version
> 
> Has that changed recently?

I think this has changed recently as they are now depending on the `native-mt` variant of coroutines. This also confused me for a while too.

> @rantingmong another way to look at this, can you try forcing the dependency in your project?
> 
> ```kotlin
>   implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core") {
>     version { 
>       strictly("1.3.9-native-mt-2")
>     }
>   }
> ```

I tried doing that as per recommendation by my friend but I got this:

```
Couldn't resolve metadata artifact for ModuleDependencyIdentifier(groupId=org.jetbrains.kotlinx, moduleId=kotlinx-coroutines-core) in configuration ':shared:iosArm64CompileKlibraries'
```

**Comment by martinbonnin** [comment]
> I think this has changed recently as they are now depending on the native-mt variant of coroutines. This also confused me for a while too.

Yup, this was just merged: https://github.com/JetBrains/kotlin-mobile-docs/pull/24

> I tried doing that as per recommendation by my friend but I got this:

```
Couldn't resolve metadata artifact for ModuleDependencyIdentifier(groupId=org.jetbrains.kotlinx, moduleId=kotlinx-coroutines-core) in configuration ':shared:iosArm64CompileKlibraries'
```

Interesting.. Does it say anything more as to why it couldn't find the artifact? Also can you try to run `./gradlew :shared:dependencies` and post the results in a gist?

**Comment by rantingmong** [comment]
Sure will do!

**Comment by rocketraman** [comment]
The best approach seems to be to force Gradle's resolution to the desired version:

```
configurations {
    all {
        resolutionStrategy {
            force("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9-native-mt-2")
            force("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9-native-mt-2")
        }
    }
}
```

**Comment by martinbonnin** [comment]
@rantingmong How did the [above suggestion](https://github.com/apollographql/apollo-android/issues/2619#issuecomment-703046839) go? 
Using Gradle dependency resolution is way easier than having to maintain two different artifacts so unless you've had an issue with this, I'll close this issue.

**Comment by martinbonnin** [comment]
Closing this. Use [the above suggestion](https://github.com/apollographql/apollo-android/issues/2619#issuecomment-703046839) to force the `-native-mt` version of couroutines if you need them.
