### ISSUE TITLE
Wrong license URL in pom

### ISSUE THREAD

**Issue by thifike** [apollographql/apollo-android#2638]
**Summary**
The latest versions of the libraries have invalid license URL in their poms

**Version**
2.4.1

**Description**
https://repo1.maven.org/maven2/com/apollographql/apollo/apollo-api-jvm/2.4.1/apollo-api-jvm-2.4.1.pom :

url is https://raw.githubusercontent.com/apollographql/apollo-android/master/LICENSE which gives a 404.
License is accessible on https://raw.githubusercontent.com/apollographql/apollo-android/main/LICENSE.

Please either change the poms to refer to the correct URL or move LICENSE from "master" to "main".

This issue is also present in:
https://repo1.maven.org/maven2/com/apollographql/apollo/apollo-compiler/2.4.1/apollo-compiler-2.4.1.pom
https://repo1.maven.org/maven2/com/apollographql/apollo/apollo-gradle-plugin/2.4.1/apollo-gradle-plugin-2.4.1.pom

So most likely in every other package as well.

**Comment by martinbonnin** [comment]
Good catch! Will fix that asap.
