### ISSUE TITLE
Is there a lazyQuery?

### ISSUE THREAD

**Issue by PritishSawant** [apollographql/apollo-android#2645]
**Question.**
I have been using apollo client v3 for `Javascript` and they have a concept of `lazyQuery` hook in `ReactJS`. So I would like to ask if there is an equivalent for `lazyQuery`?

**Comment by martinbonnin** [comment]
Hi 👋 There's obviously no react on Android so things are pretty different. From what I understand of [useLazyQuery](https://www.apollographql.com/docs/react/data/queries/#executing-queries-manually), this is used to trigger queries from an event (vs component mounting). This is the default behaviour on Android. Queries won't execute unless you trigger them. Or did you have something else in mind?

**Comment by PritishSawant** [comment]
@martinbonnin Thanks a lot for the info.
