### ISSUE TITLE
Implement serialization standards for Record

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#265]

**Comment by BenSchwab** [comment]
duplicate of https://github.com/apollographql/apollo-android/issues/286

**Comment by digitalbuddha** [comment]
I'm actually going to reopen and do this as prework for #286

**Comment by digitalbuddha** [comment]
Thx! I'm getting there. Feels like I'm coding for a whiteboard interview ☺️

**Comment by BenSchwab** [comment]
Had a feeling that this might be a tricky, hence the very descriptive "no description provided" 😛
