### ISSUE TITLE
retryWhen with subscriptions not working

### ISSUE THREAD

**Issue by gayathri-nair03** [apollographql/apollo-android#2650]
I am using Apollo client SDK for android v1.0.0. 
I am facing an issue while I am trying to retry an Apollo Graphql Subscription. I am using a "retryWithDelay" Kotlin method as follows and I have also added the code block where I am trying to subscribe with a "retryWithDelay".
I am also cloning in the getSubscriptionCall() method ->
return subscriptionClient.subscribe(subscriptionQuery).clone()).map { it.data() }

Use case: The web socket connection is auto closed from the backend after a certain time. When this happens, we get an onError() in the rx stream of android client. Here we have to retry websocket connection and resubscription. This is what im trying to achieve using retryWhen. 

Still, when the ACTUAL RETRY happens, the resubscription is not happening. The log added in the "doOnSubscribe" is printed, but the re-subscription to the query does not happen. At the end of maxRetries, onError callback is called, and the exception thrown is 
 com.apollographql.apollo.exception.ApolloCanceledException: Call is cancelled.

Can you pls check the following code and tell me if I am missing something? The retry is working fine, added logs and checked.

//Attempts a retry for "maxRetries". Each retry will be after
//retryDelayMillis. After final retry, error callback will be called

fun <T> Flowable<T>.retryWithDelay(maxRetries: Int, retryDelayMillis: Int): Flowable<T> {
    var retryCount = 0

    return retryWhen { thObservable ->
        thObservable.flatMap { throwable ->
            if (retryCount < maxRetries) {
                retryCount++
                Flowable.timer(retryDelayMillis.toLong(), TimeUnit.MILLISECONDS)
            } else {
                retryCount++
                Flowable.error(throwable)
            }
        }
    }
}

>>>>>>>>>>>>>>>>>>>>>>

getCompositeDisposable()?.add(getSubscriptionCall()
                            .doOnSubscribe{println("doOnSubscribe called")}
                            .retryWithDelay(5, 1000)
                            .observeOn(AndroidSchedulers.mainThread())
                            .subscribeOn(Schedulers.io())
                            .subscribe({ data -> onSuccess(data) }, { error -> onError(error) })
                    )

**Comment by martinbonnin** [comment]
Hi 👋 . Can you try with version `2.4.1`? There have been a number of fixes since `1.0.0`, most notably https://github.com/apollographql/apollo-android/pull/2587. You will want that if you're using the RxJava extensions.

**Comment by martinbonnin** [comment]
Hi @gayathri-nair03 any news about this? Let us know if we can help with anything. If not, I'll close this next week.

**Comment by martinbonnin** [comment]
Closing this as this should work with `2.4.1` . Let me know if it doesn't and you want me to reopen.
