### ISSUE TITLE
Support for type extensions in schema

### ISSUE THREAD

**Issue by benoitletondor** [apollographql/apollo-android#2656]
Hey there 👋 

In a project I'm working on, we are using type extension, like this:

```
type A {
    field
}

extend type A {
    newField
}
```

Right now, it doesn't work as the codegen doesn't detect any field added in the extension. Do you think it would be possible to handle this?

Many thanks!

**Comment by martinbonnin** [comment]
A simple workaround might be to use an introspection json instead of a SDL json. Can you try downloading an introspection schema with:

```
./gradle downloadApolloSchema --endpoint https://your.graphql/endpoint --schema app/src/main/graphql/com/example/schema.json
```

**Comment by benoitletondor** [comment]
Hey @martinbonnin , thank you once again for your answers.

It might work but relying on introspection is not really an option for that project so I'm afraid it won't work for me, even though it may be a perfectly ok solution for somebody else.
