### ISSUE TITLE
[Perf] Do not calculate http cache key when the http cache is not used

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#2659]
**Summary**
We can improve performance for normalized cache users by not calculating an unused http cache key.

**Version**
Most recent source linked

**Description**
The [ApolloServerInterceptor](https://github.com/apollographql/apollo-android/blob/main/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloServerInterceptor.kt#L152) calculates a cache key for queries based on the post request body. This includes the operation document, and performs and md5 calcuation -- on large queries this is non-trivial.

This occurs because for all queries we [compose the ApolloServerInterceptor with the default httpCachePolicy](https://github.com/apollographql/apollo-android/blob/main/apollo-runtime/src/main/java/com/apollographql/apollo/internal/RealApolloCall.java#L386):
```
private ApolloInterceptorChain prepareInterceptorChain(Operation operation) {
    HttpCachePolicy.Policy httpCachePolicy = operation instanceof Query ? this.httpCachePolicy : null;
```
which is non-null from the [apollo client default](https://github.com/apollographql/apollo-android/blob/main/apollo-runtime/src/main/java/com/apollographql/apollo/ApolloClient.java#L400).

**Description**
Proposed fix: either we should make the default http cache policy null when there is no http cache, or change the code which configures the ApolloServerInterceptor to send `null` for the CachePolicy if there is not cache. e.g.:

```
  private ApolloInterceptorChain prepareInterceptorChain(Operation operation) {
    HttpCachePolicy.Policy httpCachePolicy = operation instanceof Query && this.httpCache != null ? this.httpCachePolicy : null;
```

**Comment by martinbonnin** [comment]
`3.0.0-alpha01` uses a separate `HttpEngine` for HTTP cache so that the [cacheKey computation](https://github.com/apollographql/apollo-android/blob/38856b32418d5d67a129fc817708c253ed8f4392/apollo-http-cache/src/main/kotlin/com/apollographql/apollo3/cache/http/CachingHttpEngine.kt#L27) doesn't happen if no HTTP cache is configured.
