### ISSUE TITLE
Support directives at query and mutation locations

### ISSUE THREAD

**Issue by jorgebay** [apollographql/apollo-android#2661]
The spec allows directives at QUERY and MUTATION locations but code generation doesn't.

For example, the following valid graphql is not supported by the plugin:

```graphql
mutation @myModifier CreateReviewForEpisode($review: ReviewInput!) {
  val1: createReview(review: $review),
  val2: trackReview(review: $review),
}
```

**Comment by martinbonnin** [comment]
Hi! Thanks for the bug report! Just to make sure: this fails at compile time, right? 

I'm asking this because I don't think we have code to handle any operation directives. The only directives we support are `@include` and `@skip`, which are on fields. So any operation directive would most likely be ignored. Or are you expecting `myModifier` to have a specific effect?

**Comment by jorgebay** [comment]
Custom directives can be created and used in `graphql-java`: 

```java
    GraphQLSchema.Builder builder = new GraphQLSchema.Builder();
    // ...

    builder.additionalDirective(
        GraphQLDirective.newDirective()
            .validLocation(Introspection.DirectiveLocation.MUTATION)
            .name("myModifier")
            .build());
```

Then, those can be read from the operation definition during execution:

```java
val directives = environment.getOperationDefinition().getDirectives();
```

But code generation doesn't support it:

```
[ERROR] Failed to parse GraphQL file /path/to/Sample.graphql (1:21)
[ERROR] Unsupported token `InsertProducts`
[ERROR] ----------------------------------------------------
[ERROR] 
[ERROR] [1]:mutation @myModifier InsertProducts(
[ERROR] [2]:    $value: ProductsInput!
[ERROR] ----------------------------------------------------
```

**Comment by martinbonnin** [comment]
> Then, those can be read from the operation definition during execution:

By execution, you mean server side, right? If I understand correctly, if apollo-android would just "pass these directives through", that'll work for your use case, right?

**Comment by jorgebay** [comment]
yes, just blindly pass them through would be great.

**Comment by martinbonnin** [comment]
Thanks for the confirmation 👍 , I'll look into this.

**Comment by martinbonnin** [comment]
Turns out, operation directives need to come **after** the operation name: https://spec.graphql.org/June2018/#OperationDefinition

Everything should work fine if you write to queries like:

```graphql
mutation InsertProducts($value: ProductsInput!) @myModifier {
  id
}
```

Let me know if that worked

**Comment by jorgebay** [comment]
oh my... 🤦 I've just double checked...it works as expected.

**Comment by jorgebay** [comment]
Thanks @martinbonnin for looking into it !
