### ISSUE TITLE
Fragment code-generation should respect module package name configuration.

### ISSUE THREAD

**Issue by Laimiux** [apollographql/apollo-android#2667]
**Summary**
Currently, when using multi-module support (https://github.com/apollographql/apollo-android/pull/2514), child module fragment code always lands in the package specified by the parent module.

**Version**
`2.4.1`

**Comment by martinbonnin** [comment]
Thanks for filing this 👍 . Currently fragments are always put in `${schemaPackageName}.fragment`. It makes sense to generate enums/input types in a single schema-bound location because they're defined in the schema but this is not the case for fragments, we should allow to use the file package name of the file where the fragment is defined instead.

**Comment by rusmichal** [comment]
Hey I also noticed that the child module generates the apollo code too. let me show you my case.

I have two modules: core, and app. For simplifying, the core module keeps the entities, I put the schema file and graphql files in core module: `/core/src/main/graphql/com/xxxx/schema.json` and `/core/src/main/graphql/com/xxxx/core/chat`

I added that part to core gradle file:

```
apollo {
    generateApolloMetadata.set(true)
    generateKotlinModels.set(true)
}
```
The app gradle files has:
```
apollo {
    generateKotlinModels.set(true)
    service("chat") {
        rootPackageName.set("com.xxxx.core.chat")
        sourceFolder = "${rootDir}/core/src/main/graphql/com/xxxx/core/chat"
        schemaPath = "${rootDir}/core/src/main/graphql/com/xxxx/schema.json"
    }
    service("connectionrequests") {
        rootPackageName.set("com.xxxx.core.connectionrequests")
        sourceFolder = "${rootDir}/core/src/main/graphql/com/xxxx/core/connectionrequests"
        schemaPath = "${rootDir}/core/src/main/graphql/com/xxxx/schema.json"
    }
}
```

The problem I see is that the core module generates apollo classes and app does the same. I'v got the conflicts of the classes.

**Comment by martinbonnin** [comment]
Hi @rusmichal ! Thanks for reaching out ! Do you mind opening a separate issue so we can keep the discussion here about Fragments ?
