### ISSUE TITLE
Guard against nullability of HttpCache

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#267]
Currently, we do not force users to add an HttpCache. However, this nullability is not communicated internally.

Code such as this will crash on exceptions when there are no httpcache because the httpCache is null.

```
private <T extends Operation.Data> Response<T> handleResponse(okhttp3.Response response) throws IOException {
    int code = response.code();
    String cacheKey = response.request().header(HttpCache.CACHE_KEY_HEADER);
    if (code < 200 || code >= 300) {
      throw new HttpException(response);
    } else {
      try {
        return responseBodyConverter.convert(response.body());
      } catch (Exception rethrown) {
        httpCache.removeQuietly(cacheKey);
        throw rethrown;
      }
    }
  }

```

We can provide a NO_OP HTTP cache, make HTTPCache nullable, or force the use of HttpCache

**Comment by BenSchwab** [comment]
@sav007 Is this something you want to take a look at?

**Comment by digitalbuddha** [comment]
What do you think of following a similar pattern to okhttp where everything is an interceptor. Maybe I'm oversimplifying but I imagined a httpinterceptor and a cache Interceptor. We can then do the whole chain thing and not worry who is up or downstream from the request/response. That's one of the advantages of having the stateless ApolloClient where ApolloCall has access to both request/response and ability to execute.

**Comment by BenSchwab** [comment]
We are already are leveraging OkHttp's interceptor pattern for executing the network request. But the code linked above falls outside that chain, because the http-cache interceptor has already had it's last say in the chain before the response is parsed into a model.

Are you suggesting a new chain? That might be interesting...

**Comment by BenSchwab** [comment]
![screen shot 2017-03-02 at 8 38 39 pm](https://cloud.githubusercontent.com/assets/1754153/23538491/6650e958-ff88-11e6-8995-170f2d9eabe9.png)

**Comment by BenSchwab** [comment]
So maybe we could have two types of interceptors? One would be request/model interceptors, and the other request/response interceptors
