### ISSUE TITLE
[Plugin] Wrong model generated with inline fragment

### ISSUE THREAD

**Issue by cabtettere** [apollographql/apollo-android#2676]
The generated model for a query with inline fragment misses some fields

Using Apollo Runtime v2.4.1

We have a schema that comprise page that contains generic collections containing generic items.

In a query like:

```graphql
page(id: "homepage") {
  collections {
    items {
      title
      ... on ParticualItem {
        description
      }
    }
    ... on ParticularCollection {
      items {
        ... on ParticularItem {
          image 
        }
      }
    }
  }
}
```
we correctly obtain fields for `ParticularItem`: `title`, `description` an `image`  when inside `ParticularCollection`, `title` and `description` otherwise, running the query on Playground

The same query on Android usign Apollo client lose the field `image` in `ParticularItem` inside`ParticularCollection`.
The generated model for `ParticularItem` do not contains the field `image`

We rely on this kind of optimized query to reduce downloaded data, as our model are quite large, with fields to be used only on specific hierarchy.

Thanks!

**Comment by cabtettere** [comment]
Thanks for the quick response!

In the query generated models there are more than one `asParticularItem*`, but none of them contains the field `image`.

I've tested your workaround, but the new fragment definition is not included in the sended query, so the server raise a 400 error: unknown fragment "itemImage". Of course the fragmente definition is present on the .graphql file.

**Comment by martinbonnin** [comment]
Thanks, I can reproduce the issue, I'll dig more. In the meantime, the below seems to work and produce items with `image` fields. 

```graphql
query GetPage {
  page(id: "homepage") {
    collections {
      items {
        title
        ... on ParticularItem {
          description
        }
      }
      ...particularCollectionFragment 
    }
  }
}

fragment particularCollectionFragment on ParticularCollection {
  items {
    ... on ParticularItem {
      image
    }
  }
}
```

**Comment by cabtettere** [comment]
Thanks for the workaround!
