### ISSUE TITLE
Better error message if BASE_URL doesn't end with /grapql

### ISSUE THREAD

**Issue by dmathewwws** [apollographql/apollo-android#268]
Hey, minor suggestion:

The error message you get when the BASE_URL doesnt end in /graphql is hard to decipher. I also believe the iOS SDK appends /graphql to the end of the BASE_URL by default.

**Comment by sav007** [comment]
Is it part of GraphQL spec that url must be ended with `/graphql`?
Not sure as it completely depends on the routing implementation on the server side

**Comment by stubailo** [comment]
Yeah there are plenty of GraphQL servers that don't have a URL that ends with `/graphql`.

**Comment by sav007** [comment]
Ok, then closing this one.
