### ISSUE TITLE
Way to add request timeout in apollo kotlin multiplatform

### ISSUE THREAD

**Issue by ganesh-4212** [apollographql/apollo-android#2680]
**We don't have a way to set request timeout in Apollo client**
I'm using apollo kotlin multiplatform in my project and it's amazing but i have found that there is no way to set request timeout. Both OkHttp and NSURLConnection supports it currently we have to re-implement the whole NetworkTransport in both android and ios to achieve this.

**Adding requestTimeout parameter ApolloHttpNetworkTransport class**
Adding the requestTimeout parameter would be a good idea.

``` kotlin
val apolloClient = ApolloClient(
      networkTransport = ApolloHttpNetworkTransport(
          serverUrl = "https://api.example.com",
          requestTimeout = 10_000 //10 seconds
       )
 )
```

**Comment by martinbonnin** [comment]
Thanks for opening that up! Do you feel like opening a PR about this? If not, I can look at the same time as https://github.com/apollographql/apollo-android/issues/2665.

**Comment by ganesh-4212** [comment]
Hi @martinbonnin thanks for the quick response. sadly i'll not be able to work on it now.

**Comment by ganesh-4212** [comment]
I think you can take this along with #2665.

**Comment by andrey-nakin** [comment]
@martinbonnin it works, thank you.
