### ISSUE TITLE
[MINOR BUG] toFlow() Kotlin cache watcher fatal crash when no internet connection 

### ISSUE THREAD

**Issue by Nealsoni00** [apollographql/apollo-android#2682]
**Summary**
When launching the application when there is no internet connection, watchers created using the kotlin suggested toFlow() crash the application without any errors logging to the console. 

I am using this style of query watching:
```
  apolloClient.query(BookWithAuthorName()).watcher().toFlow().collect { response ->
      // This will be called every time the book or author changes
  }
```

When I used the java suggested way of watching, it works no issues. 

**Version**
ext.apolloVersion = "2.4.0"
implementation "com.apollographql.apollo:apollo-runtime:$apolloVersion"
implementation "com.apollographql.apollo:apollo-coroutines-support:$apolloVersion"
implementation "com.apollographql.apollo:apollo-normalized-cache:$apolloVersion"
implementation "com.apollographql.apollo:apollo-android-support:$apolloVersion"

**Description**
Git commit that fixed the issue for me:
![image](https://user-images.githubusercontent.com/7013191/96776588-3986a380-13b7-11eb-8e5a-b3213887d54a.png)

**Comment by martinbonnin** [comment]
Hi 👋 ! When using the coroutines extensions, network errors will raise an exception that you can catch to ignore:

```
try {
  apolloClient.query(BookWithAuthorName()).watcher().toFlow().collect { response ->
      // This will be called every time the book or author changes
  }
} catch (e: ApolloException) {
  // an error happened
}
```
See [the android tutorial section about errors](https://www.apollographql.com/docs/android/tutorial/08-add-a-details-view/#handle-protocol-errors) for more details
