### ISSUE TITLE
Allow to omit non-nullable variables if they have a defaultValue

### ISSUE THREAD

**Issue by renclav** [apollographql/apollo-android#2686]
**Is your feature request related to a problem? Please describe.**
I would like to define default values for my query variables inside the query definitions defined in .graphql file/s. Currently this is possible, but the default values are ignored in the generated models.

**Describe the solution you'd like**
The client library follows the spec defined [here](https://graphql.org/learn/queries/#default-variables) which would result in kotlin query models being generated which include default values.

Notes:

1. I use kotlin models and as such, have no awareness of how this may effect java based models.
2. I assume this would be desired for subscriptions and mutations as well (no experience there unfortunately ).

**Comment by martinbonnin** [comment]
@renclav Most of use case should work with #2704. This has been merged and will be available in the `2.4.2-SNAPSHOT` in ~30 min ([ci build](https://github.com/apollographql/apollo-android/actions/runs/333476168)). Any chance you can try the snapshots when they're ready? If everything looks good, I'll make a release next Monday.

In all cases, I'm keeping this issue open (with an updated title) for input object default values, which will require more work.

**Comment by renclav** [comment]
@martinbonnin 2.4.2-SNAPSHOT works well for me 🥳

**Comment by martinbonnin** [comment]
Awesome :). Glad to hear that and perfect timing as I'm preparing the `2.4.2` release. It should be live in a few hours

**Comment by martinbonnin** [comment]
@renclav after some tests, passing the default value as default argument in the model constructor might not be the best way to do it since it will send a GraphQL variable by default, which might be counter intuitive. 

Can you elaborate on why you need the default value in the Kotlin models? Passing `Input.absent()` as was the case before `2.4.2` should still send the default value to your server as part of the GraphQL query. Or did you need the defaultValue somewhere else?

**Comment by martinbonnin** [comment]
I'm going to close this one as not overriding the GraphQL document default variables seems to be the way to go, even for input objects (see #2741). Please leave a message if you want me to reopen it.

**Comment by martinbonnin** [comment]
Reopening this issues as there is more to it. While the solution of passing `Input.absent()` works for variables of nullable types, it doesn't work for variables of non-null type.

```graphql
query launches($id: String! = "83") {
  launch(id: $id) {site}
}
```

will generate 

```kotlin
data class LaunchesQuery(val id: String) { ... }
```

This means there's currently no way to "omit" the variable and let the GraphQL query document "carry" the defaultValue. A potential fix is to make variables with default values optional (in the Kotlin acceptation) as the current optional values  (in the GraphQL acceptation)

**Comment by martinbonnin** [comment]
This should now work as expected in `3.0.0-alpha01`. The corresponding tests are at https://github.com/apollographql/apollo-android/pull/3247/files
