### ISSUE TITLE
Resubscribe on Reconnect to web socket

### ISSUE THREAD

**Issue by gayathri-nair03** [apollographql/apollo-android#2687]
I am using Apollo Grapqhl android lib v1.0.0, using Rx extensions as well. 

In our app's implementation, the Android client itself closes the web socket connection every 5 mins (after it is opened, regardless of whether subscriptions are alive or not).
Say I am on a screen, where the subscription is active and the screen refreshes periodically based on this subscription event's data. While I stay on this screen, my auto close countdown has hit and the connection is closed (whilst the subscription is active). Now, as soon as the connection is closed, I reattempt to connect to the websocket and I am successful. But in this case I am not able to resubscribe. I need to reconnect and resubscribe in this scenario.
When I auto close the connection, I don't get any callback to my subscription (onError of the stream is not triggered). So my subscription screen has no idea if the connection is closed.
This autoclose and reconnect is happening in the transport layer (I have written a custom web-socket-transport class). Whereas the subscription is happening in an Activity/Fragment layer. 

Any workaround here?

**Comment by martinbonnin** [comment]
Hi ! I guess you'll have to signal to the upper layers that the subscription needs to be restarted, maybe by throwing an Exception or something similar. I'm assuming you're implementing your own `SubscriptionTransport`? Can you share your implementation? 
Also I would strongly suggest updating from `1.0.0`, the latest version is `2.4.1` and has a ton of important fixes.

**Comment by martinbonnin** [comment]
Hi! version `2.4.2` is just out with `SubscriptionManager.reconnect()`. Maybe that can help?

**Comment by gayathri-nair03** [comment]
@martinbonnin - We have upgraded to the latest version of Apollo library. Our use cases necessitate that we perform a socket close operation every "x" mins. So we now call, **subscriptionmanager.stop()**
but "stop" clears all subscription records as well. So when we simply reconnect, these subscription records are lost, and we cannot automatically resubscribe when we reconnect. 
Say user is on the screen where the subscription happens. He has subscribed successfully and is able to receive data, but "x" mins have passed and the socket connection closed (as per above use case). Now, when user reconnects to websocket, the subscription records are lost. so this will require a manual resubscription. How is this done?
Do we receive an onError callback for subscription when socket connection is closed when subscription is active?

**Comment by martinbonnin** [comment]
Can you try to replace `subscriptionmanager.stop()` with `subscriptionmanager.reconnect()`? Would that work? Or do you need to keep the WebSocket closed? If you need to keep the WebSocket closed, what would trigger a reconnect?

**Comment by martinbonnin** [comment]
@gayathri-nair03 any new developments here? Did you manage to make it work?

**Comment by martinbonnin** [comment]
Hi 👋 ! I'm going to assume you found a solution and close this bug. If you still have the issue, it's worth checking `3.0.0-alpha01` that has a lot of changes around `WebSockets`
