### ISSUE TITLE
Directive with multiple arguments throws DocumentParseException

### ISSUE THREAD

**Issue by zoolootech** [apollographql/apollo-android#2708]
**Summary**
It appears that apollo-android does not support directives with more than one argument.

**Version**
2.4.1
2.4.2-SNAPSHOT

**Description**
While this is not compliant, let's say a JSON schema contains something like this
```
"directives": [
  {
    "name": "customDirective",
    "locations": [
      "QUERY"
    ],
    "args": [
      {
        "name": "argument1",
      },
      {
        "name": "argument2",
      }
    ]
  }
]
```
The compiler fails with
```
Unsupported token `argument2`
----------------------------------------------------
[1]:query exampleQuery($someValue: String $argument1: String $argument2: String)
[2]:@customDirective(argument1: $argument1 argument2: $argument2) {
[3]:example(
----------------------------------------------------
```
While looking through the code to try to gain some insight, I noticed that `apollo-compiler/src/main/antlr/com/apollographql/apollo/compiler/parser/antlr/GraphQL.g4` contains
```
directive
   : '@' NAME ':' valueOrVariable | '@' NAME | '@' NAME '(' argument ')'
   ;
```
I believe `argument` should be plural since `args` in the schema is a JSON array, and 2.12 of the GraphQL specification shows that multiple arguments are allowed. 

I updated the above to be `arguments` and made some quick changes to `GraphQLParser.DirectivesContext?.parse()` function in `GraphQLDocumentParser.kt` so it would compile and test this idea.

I was able to compile everything, except the Gradle plugin, so I could not personally verify if this actually fixes the problem I am facing.

Hoping that someone can verify that this is a bug, and provide a fix, or provide some guidance on how to work around this.

Thanks!

**Comment by martinbonnin** [comment]
Hi @zoolootech Thanks for sending this. This bug should be fixed in the `dev-3.x` branch. Unfortunately, we're certainly months away from an initial 3.0 release (see [ROADMAP.md](https://github.com/apollographql/apollo-android/blob/main/ROADMAP.md) for all the things that should go in `dev-3.x`) so it's worth fix it in `main` as well. Can you share the Gradle plugin error you had?  Maybe I can help there. 
Also, you can take a look at [what's done in `dev-3.x`](https://github.com/apollographql/apollo-android/blob/dev-3.x/apollo-compiler/src/main/antlr/com/apollographql/apollo/compiler/parser/antlr/GraphQL.g4#L251).

**Comment by zoolootech** [comment]
Thanks for the update @martinbonnin Some good information.

I am starting on a new project and I like what the apollo-android library does, and would like to use it, but this is a blocker for me.  That would be great if a fix could be brought into `main` and be part of a stable v2 release.

As for the Gradle plug in problem, I was trying to publish everything to my local Maven repository with the following
```
./gradlew publishAndroidDebugPublicationToMavenLocal \
   publishDefaultPublicationToMavenLocal \
   publishJvmPublicationToMavenLocal \
   publishApolloGradlePluginPluginMarkerMavenPublicationToMavenLocal
```
I tried to figure out the Gradle tasks through best guesses on their names, but I ended up with an artifact named `com.apollographql.apollo.gradle.plugin`, tried a few more things that I don't remember, then opened this bug report.

**Comment by martinbonnin** [comment]
Thanks ! 

Re: multiple directive arguments, I'll make a quickfix in `main` to support them. That shouldn't be too hard

Re: Gradle plugin, I usually just do: `./gradlew publishToMavenLocal` and that publishes everything automagically. `com.apollographql.apollo.gradle.plugin` is the [marker artifact](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers). You can think of it as a symlink that'll redirect to the actual plugin for the shorthand `plugins {}` syntax. In all cases, `publishToMavenLocal` should publish everything that's needed

**Comment by zoolootech** [comment]
Great, this is good news.  Thank you for the quick fix.  I thought I would try it out, with what I assume is `2.4.2-SNAPSHOT` but after adding the snapshot repository listed on the main page, I get this error when trying to build

```
Execution failed for task ':app:generateDebugRFile'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.apollographql.apollo:apollo-api:2.4.2-SNAPSHOT.
     Required by:
         project :app > com.apollographql.apollo:apollo-runtime:2.4.2-SNAPSHOT
         project :app > com.apollographql.apollo:apollo-coroutines-support:2.4.2-SNAPSHOT
   > Could not find com.apollographql.apollo:apollo-normalized-cache:2.4.2-SNAPSHOT.
     Required by:
         project :app > com.apollographql.apollo:apollo-runtime:2.4.2-SNAPSHOT
```

Are there any other configuration changes I need to do to use the SNAPSHOT?

**Comment by martinbonnin** [comment]
The [SNAPSHOTs](https://github.com/apollographql/apollo-android#snapshots) are in the OSS snapshots repository. To enable them, you'll need to add this repo: 

```
repositories {
  maven { 
    url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
  }
}
```

But version `2.4.2` is just out so you can use that too :)

**Comment by zoolootech** [comment]
Perfect, just updated to `2.4.2` and everything looks like its working now.  Thanks again!
