### ISSUE TITLE
Kotlin models for kotlin 1.4.x generated with Deprecated tags throw errors when building.

### ISSUE THREAD

**Issue by MadJonTurck** [apollographql/apollo-android#2714]
**Summary**
When generating Kotlin models for kotlin 1.4.x generated with Deprecated tags in the schema, errors are thrown in builds, stating that `No value passed for parameter 'message'` to the Deprecated annotation

**Version**
Apollo 2.4.1
Kotlin 1.4.10

**Description**
The interface for the Deprecated annotation seems to have changed in Kotlin 1.4.x, and causes the apollo gradle plugin's deprecated models to throw errors in build. The new interface for Deprecated annotation no longer allows optional parameter for message:

> public annotation class Deprecated(
>     val message: String,
>     val replaceWith: ReplaceWith = ReplaceWith(""),
>     val level: DeprecationLevel = DeprecationLevel.WARNING
> ) 

So when apollo generates a Kotlin model with just `@Deprecated` it fails as it is missing the required message parameter. 

I have created an example project to demonstrate this. To do this I created a simple templated Android app, added the Apollo gradle plugin 2.4.1, bumped kotlin to 1.4.10,  and finally added a demo schema and models demonstrating Deprecation found in this repository:
https://github.com/apollographql/apollo-android/blob/main/apollo-gradle-plugin/testProjects/deprecationWarnings/src/main/graphql/schema.sdl

The example github project can be found here:
https://github.com/mad9000/apollo-kotlin-1.4-deprecated-models

The project can be opened in Android Studio and apollo sources generated from the gradle menu, followed by a build.
Alternatively, and to remove any issues with the kotlin supplied with Android Studio, the build can be run from the command line on Linux/Mac as follows:
`./gradlew generateApolloSources assembleDebug`

This should generate something like this:

> > Task :app:compileDebugKotlin FAILED
> e: REDACTED/AndroidStudioProjects/Kotlin14ApolloDeprecationError/app/build/generated/source/apollo/debug/service/api/GetUserQuery.kt: (127, 6): No value passed for parameter 'message'
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugKotlin'.
> > Compilation error. See log for more details
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 10s
> 30 actionable tasks: 30 executed

Is this an issue with the Apollo gradle plugin, or am I just not supplying sufficient compiler parameters for Kotlin somewhere? 
Alternatively, it seems that Kotlin has updated the interface of the Deprecated annotation with 1.4.x, which might prove problematic for many libraries going forward.

**Comment by martinbonnin** [comment]
Hi ! Thanks for the detailed bug report ! This is an issue in our compiler that did not support the default value of "No longer supported" for GraphQL deprecated directives. That should be fixed with https://github.com/apollographql/apollo-android/pull/2692 that I'm hoping to release next week.

If you get a chance to test with the `2.4.2-SNAPSHOT` version and confirm this is indeed the same issue, that'd be great (see [here](https://github.com/apollographql/apollo-android#snapshots) for more details how to enable the snapshots)

**Comment by MadJonTurck** [comment]
Hi @martinbonnin 

Thanks for the quick reply! I only got a chance to test this out after the weekend: I can confirm the `2.4.2-SNAPSHOT` fixes my issue. Very excited to use kotlin models in my project.

**Comment by MadJonTurck** [comment]
Hi @martinbonnin 

I'm afraid I spoke a bit too soon. 
After moving onto my production project, I applied the snapshot library, and still had the errors around @Deprecated fields. 

After a little bit of investigation, I realised that my schema (a third party schema I have no control over) was defining a Deprecation message, however that message was empty, i.e: `""`

I quickly recreated the issue inside that test repository above, copied here again for reference:
https://github.com/mad9000/apollo-kotlin-1.4-deprecated-models

With these updates to the schema, you will see you still get errors on build for the `name` field and the `USER` enum object. 

```
type User {
  name: String! @deprecated(reason: "")
  address: Address
  role: Role!
}

enum Role {
    USER @deprecated(reason: "")
    ADMIN
    SUPPORT
}
```

I'm sure this is a pretty quick fix, I'm not sure about the contribution rules for this project, but if you point me in the right direction I'm willing to make a pull request.  Alternatively, I may still be doing something wrong?

**Comment by martinbonnin** [comment]
Thanks for catching that! It comes from https://github.com/apollographql/apollo-android/blob/d9039bf023b48c0758ec448d47c0854dc8dabfbe/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/codegen/kotlin/KotlinCodeGen.kt#L44

The Codegen should pass the parameter even if it is blank. A release is planned for today so I went ahead made a quick fix there https://github.com/apollographql/apollo-android/pull/2720 to include in the upcoming version. 
But thanks a lot again for your offer to help and all the investigations. That's greatly appreciated :) !

**Comment by MadJonTurck** [comment]
Thanks for the quick turnaround. I'll jump onto that snapshot later this week.

I have already confirmed everything prior to that worked by string replacing empty deprecation reasons with `null` in the schema I'm working off. 
This works as a stop-gap until I can get the fix off snapshot release; in the meantime I have converted my older Java models into Kotlin, it's great.
