### ISSUE TITLE
Unsupported token `!`

### ISSUE THREAD

**Issue by allmazz** [apollographql/apollo-android#2718]
**Summary**
Unsupported token `!`

**Version**
2.4.1(latest)

**Description**
I have generated schema.json and put it together with schema.graphql in the project. Every time the error Unsupported token`! ` Appears. This is my schema:

```
type Query {
    work(id: ID!): Work #
    user(id: ID!): User #
    users(user_from: Int!, user_to: Int!): [User]
    tag(id: ID!): Tag #
    tags: [Tag] #
}
```

**Comment by martinbonnin** [comment]
Hi 👋 . Can you try naming your file `schema.sdl`? It looks like Apollo is trying to parse it as an operation and not a schema

**Comment by martinbonnin** [comment]
Hi @allmazz I'm going to assume this was a schema vs operation thing and that you got it figured out. Do not hesitate to leave a message if not and I'll reopen this issue.

**Comment by sam43** [comment]
Delete the `schema.graphql` file, it will run! Thank me later
