### ISSUE TITLE
Issue when using coroutines 1.3.9-mt (multithreaded coroutines)

### ISSUE THREAD

**Issue by enyciaa** [apollographql/apollo-android#2722]
**Summary**
The apollo library overwrites the coroutine 1.3.9-mt version specified in a KMM project (expected behaviour) but the suggested way in the KMM docs of getting around this doesn't work.

**Version**
2.4.1

**Description**
1.3.9-mt is used for multithreading. It has a few edge cases so hasn't been merged into the main coroutine branch, but it is actively maintained and used by a few projects (it's currently suggested in the KMM docs).

1.3.9 is technically a newer version than 1.3.9-mt. So gradle resolves 1.3.9 as the coroutine version for the project. The KMM docs suggest using the following to get around the current restriction (which doesn't work and causes a build error in kotlin native when used in tandem with apollo):

```
implementation ("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9-native-mt"){
    version {
        strictly("1.3.9-native-mt")
    }
}
```

But the following works:

```
implementation ("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9-native-mt"){
    isForce = true
}
implementation("apollo-library)
```

It's probably not worth fixing, as multithreaded coroutines should come to the main coroutine branch in the near future. But could be useful to add a section to the KMP docs on apollo?

Also, best I could figure is that the reason strictly doesn't work with apollo is that `apollo-runtime-kotlin-jvm` is internally fetched using strictly which seems to also effect transitive dependencies within `apollo-runtime-kotlin-jvm`? I get this when running a dependency check.
```
org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:{strictly 1.3.9-native-mt} -> 1.3.9-native-mt
\--- releaseCompileClasspath

org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.3.9-native-mt
\--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9-native-mt
     +--- releaseCompileClasspath (requested org.jetbrains.kotlinx:kotlinx-coroutines-core:{strictly 1.3.9-native-mt})
     \--- com.apollographql.apollo:apollo-runtime-kotlin-jvm:2.4.1 (requested org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9)
          +--- releaseCompileClasspath (requested com.apollographql.apollo:apollo-runtime-kotlin-jvm:{strictly 2.4.1})
          \--- com.apollographql.apollo:apollo-runtime-kotlin:2.4.1
               \--- releaseCompileClasspath

```

**Comment by martinbonnin** [comment]
Hi! Thanks for reaching out! 


> It's probably not worth fixing, as multithreaded coroutines should come to the main coroutine branch in the near future

Indeed, as replied in https://github.com/apollographql/apollo-android/issues/2619, there's little value for Apollo Android to do anything there and tweaking dependencies resolution with Gradle is the way to go 👍 

> But could be useful to add a section to the KMP docs on apollo?

Good idea. The [multiplatform getting-started](https://github.com/apollographql/apollo-android/blob/main/docs/source/essentials/get-started-multiplatform.mdx) could use something like this. Do you want to open a PR?

> Also, best I could figure is that the reason strictly doesn't work with apollo is that apollo-runtime-kotlin-jvm is internally fetched using strictly which seems to also effect transitive dependencies within apollo-runtime-kotlin-jvm

I don't think we do anything like that.
