### ISSUE TITLE
Generate sealed classes for union types

### ISSUE THREAD

**Issue by martin-dd** [apollographql/apollo-android#2726]
**Is your feature request related to a problem? Please describe.**
GraphQL schema allows defining unions. Currently the generated code represents the unions as individual classes implementing the same interface. 

**Describe the solution you'd like**
When using unions in GraphQL schema, it would be great to utilize sealed classes feature from Kotlin to simulate those unions. Sealed classes hierarchy represent unions more accurately than regular classes.

**Comment by PatrickDattilio** [comment]
This would allow much cleaner `when` statements over the sealed class, instead of the single parent class with optional fields.

+1 would use today

**Comment by martinbonnin** [comment]
I'm going to redirect to this one that has some discussion already: https://github.com/apollographql/apollo-android/issues/1390
