### ISSUE TITLE
Default string values in mutation inputs are not escaped correctly

### ISSUE THREAD

**Issue by joeboyscout04** [apollographql/apollo-android#2727]
**Summary**
When using `defaultValues` to generate Input<String> objects for mutations, the quotations are not un-escaped correctly, so the default value for the input contains quotations where there shouldn't be any. 

This affects the Kotlin code generation (possibly the Java one also, although I haven't tested that one). 

**Version**
Latest version (master)

**Description**
For example, in this schema (this is an Apollo example), there is a default value of ` "defaultValue": "\"Me\""`.

This server would be expecting a default value of `Me`.  However, when the schema is parsed into Kotlin, the default value is `Input.optional("\"Me\"")`, which would send a default value of `"Me"` (with quotations) to the server. 

```
 {
          "kind": "INPUT_OBJECT",
          "name": "BookInput",
          "description": null,
          "fields": null,
          "inputFields": [
            {
              "name": "title",
              "description": null,
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
                }
              },
              "defaultValue": null
            },
            {
              "name": "author",
              "description": null,
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
                }
              },
              "defaultValue": "\"Me\""
            }
          ],
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": null
        },
```

I've reproduced this in the sample project here: https://github.com/joeboyscout04/apollo-android/tree/default-values-string

I've added a mutation like so:
```
mutation deleteBranch($input: DeleteBranchProtectionRuleInput!) {
	deleteBranchProtectionRule(input: $input) {
		clientMutationId
	}
}
```

And I've updated the schema (on `clientMutationId`...this was the easiest parameter to change) to reflect the default values as described above. 

The generated code resulting shows that the Input<String> for `clientMutationId` would incorrectly include quotations.

```
  val clientMutationId: Input<String> = Input.optional("\"Me\"")
```

I would expect that instead, the default value would be generated as:
```
val clientMutationId: Input<String> = Input.optional("Me")
```

**Comment by martinbonnin** [comment]
Hi 👋  Thanks for sending this! 
I believe this is working as intended? Json can represent string values so there should be no need for additional escaping? Can you point to specifications or other implementation that do this un-escape?

**Comment by joeboyscout04** [comment]
I thought so too, but there's a few things that lead me to believe otherwise:

Firstly, the schema.json examples I've seen have all default values which are `Int`, `Boolean`, and `Array` are also in quotes.  Since JSON handles Int and Boolean values fine without quotes, this implies to me that there's something special about the default values in the schema where they need to be wrapped in quotes (and for strings, this would imply double quotations, since wrapping a JSON string in quotes would lead to the sort of `"\"Value\""` thing I've described).  This would necessitate unwrapping them when converting them into Java/Kotlin models.  

Examples from the kotlin-sample project `schema.json` :

A Boolean
```
                {
                  "name": "withFreeTrialsOnly",
                  "description": "Select only listings that offer a free trial.",
                  "type": {
                    "kind": "SCALAR",
                    "name": "Boolean",
                    "ofType": null
                  },
                  "defaultValue": "false"
                }
```

An Int
```
              "args": [
                {
                  "name": "limit",
                  "description": "How many characters to return.",
                  "type": {
                    "kind": "SCALAR",
                    "name": "Int",
                    "ofType": null
                  },
                  "defaultValue": "200"
                }
              ],
```

A List
```
                {
                  "name": "affiliations",
                  "description": "Array of viewer's affiliation options for repositories returned from the connection. For example, OWNER will include only repositories that the current viewer owns.",
                  "type": {
                    "kind": "LIST",
                    "name": null,
                    "ofType": {
                      "kind": "ENUM",
                      "name": "RepositoryAffiliation",
                      "ofType": null
                    }
                  },
                  "defaultValue": "[\"OWNER\", \"COLLABORATOR\"]"
                },
```

A String
```
            {
              "name": "reason",
              "description": "Explains why this element was deprecated, usually also including a suggestion for how to access supported similar data. Formatted in [Markdown](https://daringfireball.net/projects/markdown/).",
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "defaultValue": "\"No longer supported\""
            }
```

I've also seen a similar issue in other libraries: https://github.com/graphql-java/graphql-java/issues/863

**Comment by martinbonnin** [comment]
Indeed, I ran an introspection query against both the [github API](https://developer.github.com/v4/explorer/) and the [Shopify one](https://shopify.dev/tools/graphiql-storefront-api) and they both "encode" Boolean/Int/Enum values as strings.

The interesting thing is that none of them actually have default String values so it's hard to tell 100%. Especially since there's no ambiguity possible for Boolean/Ints/Enums but there could be for Strings. 

Also, another interesting thing. In one of the exemple you gave from the kotlin-sample:

```
"defaultValue": "[\"OWNER\", \"COLLABORATOR\"]"
```

That's clearly the opposite of the Github schema for enums that encodes enums without quotes: `"[OWNER, COLLABORATOR]"`. Which means there are basically 3 possible ways to encode the defaultValue:

1. plain json value
2. json value serialized to a string
3. graphql value serialized to a string

I wonder if there's a way that we could be "flexible about what we receive" and detect automatically which one is used. I'll keep digging. 

Also, out of curiosity, what server are you using? The answer to that question might in the end to do what the most common implementations do.

**Comment by martinbonnin** [comment]
Ah! I think I found the [spec](https://spec.graphql.org/draft/#sec-The-__InputValue-Type):

```
defaultValue may return a String encoding (using the GraphQL language) of the default value used by this input value in the condition a value is not provided at runtime. If this input value has no default value, returns null.
```
So the correct solution is indeed #3: `graphql value serialized to a string` and we need to decode the GraphQL value.

**Comment by joeboyscout04** [comment]
Any progress on this one?  We get the same error every time we update our GraphQL schema.

**Comment by martinbonnin** [comment]
That's a tough one to fix as it's going to change a bunch of things in the parser and that might be a bit invasive in the current state of things. I'll try to see if there a way to do this without too many side effects.

**Comment by martinbonnin** [comment]
@joeboyscout04 PR there: https://github.com/apollographql/apollo-android/pull/2917

**Comment by joeboyscout04** [comment]
Super nice, thanks!
