### ISSUE TITLE
SDL schema download asks for --service on android client

### ISSUE THREAD

**Issue by nicusorflorin** [apollographql/apollo-android#2728]
**Summary**
Running * ./gradlew downloadApolloSchema --endpoint https://your.graphql/endpoint --schema src/main/graphql/com/example/schema.sdl * asks for -- service on client android  

**Version**
2.4.2

**Description**
Ran the command in the terminal and it gave that error, for json it works fine

**Comment by nicusorflorin** [comment]
Doubled checked, it seems it doesn't work for json either. I assume it's version related in this case?

**Comment by martinbonnin** [comment]
Damn, sorry about that, that has been introduced by https://github.com/apollographql/apollo-android/pull/2712. Relaxing the variant check introduced this ambiguity.  

I'll make a quick fix. In between, you can workaround by adding `--service=service` (or the name of your service if you explicitely set one):

```
./gradlew downloadApolloSchema --endpoint https://your.graphql/endpoint --schema src/main/graphql/com/example/schema.sdl --service=service
```

**Comment by nicusorflorin** [comment]
It's ok i downloaded with 2.4.0 and then updated again :D. but i still cannot use SDL schema, added a new bug for that  #2729

**Comment by martinbonnin** [comment]
@nicusorflorin `2.4.3` has been released with a fix for this issue as well as some fixes for SDL string parsing. The string escape/parsing is a bigger story, which I hope to tackle in the coming days but hopefully `2.4.3` is good enough to let you use SDL schema. Let me know how that goes!
