### ISSUE TITLE
SDL schema cannot be parsed successfully

### ISSUE THREAD

**Issue by nicusorflorin** [apollographql/apollo-android#2729]
**Summary**
 When trying to build with a SDL schema i get: Failed to parse GraphQL file pathto\schema.sdl (2:36)

**Version**
2.4.0. or 2.4.2

**Description**
  Execution failed for task ':graphql-module:generateDebugServiceApolloSources'.
> 
    Failed to parse GraphQL file pathto\schema.sdl (2:36)

    Unsupported token `" to get"`
  ----------------------------------------------------
  [1]:type Query {
  [2]:  media("The password for the "Media" to get" password: String, "The id of the "Media" to get" id: ID!): Media
  [3]:  nop: Int
  ----------------------------------------------------

**Comment by martinbonnin** [comment]
Thank! This description will need triple quotes indeed. I'll fix this too and include that in the next hotfix version. 

```
media("""The password for the "Media" to get" password: String, "The id of the "Media" to get""" id: ID!): Media
```

**Comment by martinbonnin** [comment]
Hi @nicusorflorin 👋  this is fixed in `2.4.4`, were you able to make your SDL schema work?

**Comment by nicusorflorin** [comment]
Hello @martinbonnin, yes indeed i was. Thanks !

**Comment by martinbonnin** [comment]
Awesome glad to hear that :). SDL has been really helpful for us and I hope it can see more widespread adoption in the future :)
