### ISSUE TITLE
How to include the source code of module dependencies when build a new module?

### ISSUE THREAD

**Issue by ludovicroland** [apollographql/apollo-android#2768]
Hello,

I have created a fork of the project in order to create a new module in which one I have a module dependencies to another existing module (the apollo-http-cache one).

I have also edited some classes into the apollo-http-cache and the apollo-http-cache-api modules.

I would like is to release AAR of my module that includes the source code of the transitive module dependencies. Unfortunately when I release my module using the assembleRelease task, the module only contain its own source code.

I can add my AAR as a dependency into a project and the transitive resolution system retrieve automatically the following dependencies:

*  com.apollographql.apollo:apollo-api-jvm:2.4.5
* com.apollographql.apollo:apollo-http-cache:2.4.5
* com.apollographql.apollo:apollo-http-cache-api:2.4.5

But theses dependencies are the original ones and does not contains my edits.

So it is possible to change some properties in order to release a "big" ARR that contains directly the source code of my module and the source code of the 3 module dependencies?

Here the build.gradle.kts file on my module:

```gradle
plugins {
  id("com.android.library")
  kotlin("android")
  kotlin("kapt")

  //deployment plugins
  maven
  `maven-publish`
}

android {
  compileSdkVersion(groovy.util.Eval.x(project, "x.androidConfig.compileSdkVersion").toString().toInt())

  sourceSets["main"].java.srcDir("src/main/kotlin")
  sourceSets["androidTest"].java.srcDir("src/androidTest/kotlin")

  lintOptions {
    textReport = true
    textOutput("stdout")
    ignore("InvalidPackage")
  }

  defaultConfig {
    versionName = "2.4.5"

    minSdkVersion(groovy.util.Eval.x(project, "x.androidConfig.minSdkVersion").toString())
    targetSdkVersion(groovy.util.Eval.x(project, "x.androidConfig.targetSdkVersion").toString())

    testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

    testOptions {
      unitTests.isIncludeAndroidResources = true
    }
  }
}

dependencies {
  implementation(kotlin("stdlib"))
  add("api", project(":apollo-http-cache"))

  add("implementation", groovy.util.Eval.x(project, "x.dep.timber"))
  add("implementation", groovy.util.Eval.x(project, "x.dep.okHttp.okHttp"))
  add("implementation", groovy.util.Eval.x(project, "x.dep.kotlin.coroutinesAndroid"))

  //tests
  add("androidTestImplementation", groovy.util.Eval.x(project, "x.dep.junit"))
  add("androidTestImplementation", groovy.util.Eval.x(project, "x.dep.androidx.testJUnit"))
  add("androidTestImplementation", groovy.util.Eval.x(project, "x.dep.androidx.testRunner"))

  add("androidTestImplementation", groovy.util.Eval.x(project, "x.dep.koin.android"))
  add("androidTestImplementation", groovy.util.Eval.x(project, "x.dep.koin.test"))
  add("androidTestImplementation", groovy.util.Eval.x(project, "x.dep.okHttp.logging"))
  add("androidTestImplementation", groovy.util.Eval.x(project, "x.dep.retrofit.retrofit"))
  add("androidTestImplementation", groovy.util.Eval.x(project, "x.dep.retrofit.moshiConverter"))
  add("androidTestImplementation", groovy.util.Eval.x(project, "x.dep.moshi.kotlin"))
  add("kaptAndroidTest", groovy.util.Eval.x(project, "x.dep.moshi.kotlinCodegen"))
}
```

Thank you advance for your help!

**Comment by martinbonnin** [comment]
Hi 👋 

If you want to have a custom distribution of the project, the best way to do this would be to publish your fork to a different maven repo and put that repo above `mavenCentral/jcenter` when consuming the dependencies. The existing repos are declared there: https://github.com/apollographql/apollo-android/blob/f96b3eca7fa1fe2c79560b378c161012a6c6258d/build.gradle.kts#L137. You can add your own or use `mavenLocal` if you're building locally.

All that being said, can you share why you had to fork? If you could upstream the modifications, that'd be easier for you (no need to handle a custom distribution) and could also benefit others users.

**Comment by ludovicroland** [comment]
Hello @martinbonnin!

Thank you for your answer. 

My new module is distribute on JCenter with its own identifier and package name. But I am trying to do is to build only 1 big artifact with all the needed source instead of publishing 3 artifacts (the new one, the apollo-http-cache custom one and the apollo-http-cache-api custom one).

My edits are very specifics to my need in order to use the cache modules in a very specific way in a no graphQL context 😇 . So create a pull request with these modifications is not a good idea :)

**Comment by martinbonnin** [comment]
I'm guessing you want to shadow `apollo-http-cache` because you can't publish the modified version on jcenter? You could change the group name instead. To something like `com.youtcompany:apollo-http-cache`. We typically don't encourage forking but that would be a way to do it if you really wanted to.

If you prefer a fat jar with bundled `apollo-http-cache`, you'll want to look into the [maven-publish plugin](https://docs.gradle.org/current/userguide/publishing_maven.html). [This article](https://entzik.medium.com/how-to-publish-open-source-java-libraries-to-maven-central-70f9232462f5) gives a good overview of how to create a `Jar` task that bundles the sources and add it to a `MavenPublication`
