### ISSUE TITLE
How to access generated class model from different module ? I got error when to access it.

### ISSUE THREAD

**Issue by jemmycalak** [apollographql/apollo-android#2779]
Error : Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
and Error : Check your module classpath for missing or conflicting dependencie.

**Comment by martinbonnin** [comment]
Hi! We'll need more details to investigate this. Especially, can you tell which supertypes cannot be resolved? 

First thing that comes to mind is a missing `implementation("com.apollographql.apollo:apollo-runtime:2.4.5")` but without more details, it's hard to tell

**Comment by jemmycalak** [comment]
thank you mr martin for respone my question, i have fix my problem with add this line to my module :-)

   apollo {
        generateKotlinModels.set(true)
        generateApolloMetadata.set(true)
    }

    apolloMetadata(project(":data:model"))
    implementation("com.apollographql.apollo:apollo-runtime:2.4.5")
    implementation("com.apollographql.apollo:apollo-api:2.4.5")

**Comment by jemmycalak** [comment]
thank you mr martin for respone my question, i have fix my problem with add this line to my module :-)

   apollo {
        generateKotlinModels.set(true)
        generateApolloMetadata.set(true)
    }

    apolloMetadata(project(":data:model"))
    implementation("com.apollographql.apollo:apollo-runtime:2.4.5")
    implementation("com.apollographql.apollo:apollo-api:2.4.5")

**Comment by martinbonnin** [comment]
Nice, glad to hear that 👍 , have a great day!
