### ISSUE TITLE
Multiplatform FileUpload 

### ISSUE THREAD

**Issue by alterpie** [apollographql/apollo-android#2784]
**Summary**
We're trying to utilize ```FileUpload``` functionality to send images to our backend. We receive `Field 'photo' of variable 'photo' has coerced Null value for NonNull type 'File!'` error message every time we try to do so.

**Version**
2.4.5

**Description**
We have ```scalar File``` in our schema. As documentation states we added ```"File" to "com.apollographql.apollo.api.FileUpload"``` to custom mappings in apollo task as following:
```
apollo {
    customTypeMapping.set(
        mapOf(
            // other mappings
            "File" to "com.apollographql.apollo.api.FileUpload"
        )
    )
}
```
We have following mutation:
```
mutation UploadPhotoMutation($photo: File!) {
    uploadPhoto(photo: $photo)
}
```
and use it like this:
```kotlin
 val fileUpload = object : FileUpload(mimeType, Uri.fromFile(file).path!!) {
                override fun contentLength() = file.length()
                override fun fileName() = file.name
                override fun writeTo(sink: BufferedSink) {
                    sink.writeAll(file.source().buffer())
                }
            }

apolloClient.mutate(UploadPhotoMutation(fileUpload))
            .execute()
            .first()
```
Here is you can see ```operation.variables()``` state during ```OperationRequestBodyComposer.compose``` call. So all variables are present.

![image](https://user-images.githubusercontent.com/10796453/100727998-08e35200-33d8-11eb-9b5c-b72e3ff63d9a.png)

Bus as soon as ```InputFieldJsonWriter.writeCustom``` is called it returns ```GraphQLNull``` value for call customTypeAdapter.encode(value) and writes null to `photo` field.

![image](https://user-images.githubusercontent.com/10796453/100728206-4fd14780-33d8-11eb-9ea3-062f06596dbc.png)

And in default implementation DEFAULT_ADAPTERS for scalarTypeAdapters to which defaults scalarTypeAdapters.adapterFor<Any>(scalarType) call in this case has following code for FileUpload:
```kotlin
 mapOf("com.apollographql.apollo.api.FileUpload" to object : CustomTypeAdapter<FileUpload> {
          override fun decode(value: CustomTypeValue<*>): FileUpload {
            // TODO: is there a valid use case for decoding a FileUpload or should we throw here?
            return FileUpload("", value.value?.toString() ?: "")
          }

          override fun encode(value: FileUpload): CustomTypeValue<*> {
            return GraphQLNull
          }
        })
```
So call to encode will always return GraphQLNull and field `photo` is mapped to null instead of real value

**Comment by alterpie** [comment]
Although worth to mention that we use it in multiplatform module.

**Comment by alterpie** [comment]
After further investigation it seems that problem is json returned from composeRequestBody(scalarTypeAdapters: ScalarTypeAdapters) call in generated UploadPhotoMutation.
It returns `{“operationName”:“UploadPhotoMutation”,“variables”:{“photo”:null},“query”:“mutation UploadPhotoMutation($photo: File!) { uploadPhoto(photo: $photo) }“}`

But it also should contain `map="{\"photo\": [\"variables.photo\"]}"`  and `photo=@"/path/to/image/image.jpg"` as formdata parameters

**Comment by martinbonnin** [comment]
Multiplatform doesn't have support for FileUpload yet. `FileUpload` is working with reflection on the JVM (see #2570) so it'll have to be implemented differently in multiplatform.

**Comment by alterpie** [comment]
Oh, I see, thanks. Btw is `FileUpload` is implemented on iOS? If so we could switch to native versions instead of multiplatform

**Comment by martinbonnin** [comment]
It is! https://www.apollographql.com/docs/ios/mutations/#uploading-directly-with-apollo

**Comment by alterpie** [comment]
thank you so much!

**Comment by designatednerd** [comment]
I also recommend reading [this caveat right above what Martin linked](https://www.apollographql.com/docs/ios/mutations/#an-important-caveat-about-file-uploads) 😇 - that also might be a way to think about file uploads on multiplatform that could be easier to achieve.

**Comment by martinbonnin** [comment]
`3.0.0-alpha01` has multiplatform file upload. See [FileUploadTest](https://github.com/apollographql/apollo-android/blob/88541800883e6d51597105dc1567a54a82bf3645/composite/tests/integration-tests-kotlin/src/commonTest/kotlin/test/FileUploadTest.kt#L24) for usage:

```kotlin
val mutation = UploadMutation(file = Upload.fromFile(file, "image/png"))
```
