### ISSUE TITLE
Generated code and new new Explicit API Mode

### ISSUE THREAD

**Issue by omainegra** [apollographql/apollo-android#2794]
**Is your feature request related to a problem? Please describe.**
Starting from Kotlin 1.4, the compiler offers the explicit API mode for library authors: 
  https://kotlinlang.org/docs/reference/whatsnew14.html#explicit-api-mode-for-library-authors
But the current generated code by the gradle plugins still doesn't support it

**Describe the solution you'd like**
Generate code according to the restrictions in the new explicit API mode

**Comment by martinbonnin** [comment]
`3.x` upgrades KotlinPoet to `1.7.0` that should produce code compatible with the Explicit API Mode: https://square.github.io/kotlinpoet/changelog/#version-170.

I'm not sure how to test this. I'm closing this issue for now. If you find a place where this doesn't work, please reopen and we'll add a specific test and fix.
