### ISSUE TITLE
Gradle Plugin: Calling apollo.customTypeMapping.put does nothing

### ISSUE THREAD

**Issue by ansman** [apollographql/apollo-android#2802]
**Summary**
Calling `customTypeMapping.put` without first calling `set` is ignored.

**Version**
2.4.6 (Gradle 6.7.1)

**Description**
To my surprise Gradle seems to ignore calls such as `MapProperty.put` if the property is not present. Here's some concrete examples:
```kotlin
apollo {
  // Prints `null`
  println(customTypeMapping.orNull)

  customTypeMapping.put("foo", "bar")
  // Prints `null`
  println(customTypeMapping.orNull)

  customTypeMapping.set(emptyMap())
  customTypeMapping.put("foo", "bar")
  // Prints `{foo=bar}`
  println(customTypeMapping.orNull)
}
```

The fix for this is simple, the Apollo Gradle Plugin just needs to set `emptyMap()` as the default value. Using `convention` does not work unfortunately.

The reason why I prefer `put` is because I often set up my Gradle scripts using custom Gradle plugins in `buildSrc` which can add some common default values.

**Comment by ansman** [comment]
This seems related to https://github.com/gradle/gradle/issues/7485

**Comment by martinbonnin** [comment]
Yup, this behaviour is super weird. Recent versions of Gradle have a `MapProperty.convention()` method that allows to set a default value. Tentative fix there: https://github.com/apollographql/apollo-android/pull/2803
