### ISSUE TITLE
Kotlin upgrade to 1.4.20

### ISSUE THREAD

**Issue by enyciaa** [apollographql/apollo-android#2815]
Problem:
Kotlin 1.4.20 is incompatible with 1.4.10 and lower if using the KMP hierarchical structure (most KMP projects). Apollo 2.4.6 is published with 1.4.10 so most projects using KMP won't be able to update kotlin until apollo also updates. [See 1.4.20 update notes, near the bottom](https://blog.jetbrains.com/kotlin/2020/11/kotlin-1-4-20-released/)

Solution:
Is a kotlin update to 1.4.20 planned for either a 2.x version or 3.x version? Would a PR be useful?

**Comment by martinbonnin** [comment]
> Would a PR be useful?

That'd be awesome :) 

> Is a kotlin update to 1.4.20 planned for either a 2.x version or 3.x version? 

It's been a while since the latest release, I'll make a `2.4.7` once this goes in

**Comment by enyciaa** [comment]
Bear with me, I haven't done many open source contributions :) but will give it a shot! Would it be best to branch off of main?

**Comment by martinbonnin** [comment]
Nice :)! Yep, `main` is still the default branch. `dev-3.x` is pretty unstable at the moment.

**Comment by enyciaa** [comment]
Ah so as apollo doesn't use a hierarchical project structure for KMP so this wouldn't actually be an issue 🥇  - going to close

**Comment by martinbonnin** [comment]
I looked into it quickly a few months ago and I think enabling HMPP has to be a "waterfall" right? We can't enable HMPP in apollo-android until all dependencies have it enabled? (see also https://github.com/touchlab/Stately/issues/46)
