### ISSUE TITLE
Plugin fails on Android library projects

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#284]
Change Apollo-integration to `com.android.library` and build.

```Error:Could not get unknown property 'applicationVariants' for object of type com.android.build.gradle.LibraryExtension.```

**Comment by lahari509** [comment]
Still The error is encountering

**Comment by Kolyall** [comment]
Seems you try to use `android.applicationVariants` in `library` module.
Tutorial:
In `app` module use `apply plugin: 'com.android.application'` and `android.applicationVariants` 
In `library` module use `apply plugin: 'com.android.library'` and `android.libraryVariants`
