### ISSUE TITLE
MultiPlatform: why using NSUrlConnection instead of NSUrlSession for iOS?

### ISSUE THREAD

**Issue by dbaroncelli** [apollographql/apollo-android#2845]
Concerning the MultiPlatform project:
https://www.apollographql.com/docs/android/essentials/get-started-multiplatform/

It says that the iOS client uses NSUrlConnection
which has been deprecated by Apple for NSUrlSession

I am writing here, as in the URL, it appears as part of the Android project.
I had written in the Apollo-iOS project:
https://github.com/apollographql/apollo-ios/discussions/1613#discussioncomment-266190
They told me they are using NSUrlSession there

is there any reason why you use NSUrlConnection for the MultiPlatform project?
is there a plan to use NSUrlSession soon?

**Comment by martinbonnin** [comment]
Yikes, it's most likely a leftover of ancient times. The multiplatform code uses NSUrlSession, see https://github.com/apollographql/apollo-android/blob/main/apollo-runtime-kotlin/src/iosMain/kotlin/com/apollographql/apollo/network/http/ApolloHttpNetworkTransport.kt#L84

I'll fix the doc in 2 min! Thanks for reporting this!

**Comment by martinbonnin** [comment]
Closed by https://github.com/apollographql/apollo-android/pull/2847

**Comment by dbaroncelli** [comment]
Great, that was quick!

But something strange happens in the doc page now.
I tested with both Chrome and Safari on MacOS.

When I load this page:
https://www.apollographql.com/docs/android/essentials/get-started-multiplatform/
the link text is "NSUrlSession" for 1 second, and then it becomes "NSUrlConnection"
while the link url is always correct: https://developer.apple.com/documentation/foundation/nsurlsession

**Comment by martinbonnin** [comment]
> the link text is "NSUrlSession" for 1 second, and then it becomes "NSUrlConnection"

Interesting, I have the same thing... Let's keep this ticket open as a reminder to test this again in a couple of hours. Maybe Gatsby/our doc engine has a cache somewhere that needs to be updated. Let's try again a bit later.

**Comment by ansman** [comment]
I'm only getting the `NSUrlSession`, not `NSUrlConnection`.

**Comment by martinbonnin** [comment]
Looks good for me now.
