### ISSUE TITLE
Support for RFC 373 is missing (Interfaces implementing other interfaces)

### ISSUE THREAD

**Issue by desiderantes** [apollographql/apollo-android#2848]
**Summary**
This project does not implement [RFC 373 (Interfaces implementing Interfaces)](https://github.com/graphql/graphql-spec/pull/373)

**Version**
2.4.6

**Description**
When trying to parse a `.graphqls` schema with an interface implementing another interface, the parser fails with the error ```Unsupported token `implements` ```

**Comment by martinbonnin** [comment]
Hi 👋 , I just made a quick test and it looks like this is already working in `dev-3.x`: https://github.com/apollographql/apollo-android/pull/2851

It parses schema and generates models. The code to detect type conditions for fragments seems ok as well.
The GraphQL type hierarchy not being mirrored in the Kotlin type hierarchy, I think that's about everything that is needed?

Is there any chance you could try one of the `3.0.0-SNAPSHOT` to make sure it's working as expected? If everything looks good, this should be reasonnably possible to backport to 2.x.

**Comment by desiderantes** [comment]
Well, my original project uses the gradle project so I had to create a new one, but yes, it parses correctly @martinbonnin

**Comment by martinbonnin** [comment]
Thanks for confirming that, I'll backport for the next 2.x release

**Comment by martinbonnin** [comment]
The fix is now in main so you can test with SNAPSHOT when they come up in ~30min. I'll make a release on monday.
