### ISSUE TITLE
Some questions about MultiPlatform

### ISSUE THREAD

**Issue by dbaroncelli** [apollographql/apollo-android#2853]
Hello everyone, I discovered only this week about your Kotlin MultiPlatform client, which is really exciting!
Having a stable and performant KMP GraphQL client, would really make GraphQL take off forever.
It would simplify app development in general by a huge lot. Very interesting is also the "out of the box" in-memory mechanism.
I have noticed that the project is still "Experimental".
I have a few questions, I would like to ask:

1) Do you already have an ETA for the "Alpha" release?

2) Which are the main issues at the moment?

3) How stable it is on Android and on iOS?

4) Do you expect any soon to start development also for a Kotlin/JS version?

**Comment by martinbonnin** [comment]
Hi 👋 ! Apollo Android has several parts that have various support for KMP. At a high level, it's something like:

1. `apollo-api` (JVM + K/N + JS)
  Code Generation + Json parsing
2. `apollo-runtime` (JVM)
  HTTP + Websockets + HTTP cache + Normalized cache
3. `apollo-runtime-kotlin` (JVM + K/N)
  HTTP + Websockets
  
Both `apollo-runtime` and `apollo-runtime-kotlin` are built on top of `apollo-api`. `apollo-api` is pretty stable and works for JS as well.  If you want type safe models and Json parsing, everything is there.

For the rest (network and cache), `apollo-runtime-kotlin` is the new client targeting multiplatform (`apollo-runtime` is JVM only). I'd say it is pretty stable and you can already use it to do queries, mutations and subscriptions. It's still missing caching though, which we are working on. You can check the roadmap there: https://github.com/apollographql/apollo-android/blob/main/ROADMAP.md. 

I hope that answers the questions, sorry I didn't take them in order! You can also check the KMP sample app there: https://github.com/apollographql/apollo-android/tree/main/samples/multiplatform which is using the Github API

**Comment by dbaroncelli** [comment]
Thanks Martin!
I will definitely start experimenting the 3.0 version in the coming few weeks.
Keep up the great work!
