### ISSUE TITLE
[Cache] [3.x] Normalization could be moved to the ApolloCacheInterceptor

### ISSUE THREAD

**Issue by olivierg13** [apollographql/apollo-android#2861]
The normalization is done today in the ApolloParseInterceptor (line 78), and thus executes while blocking the response callback to the UI.

Since normalization is pretty expensive, we could move the normalization to ApolloCacheInterceptor (line ~134) and benefit from the asynchronous dispatcher when passing `writeToCacheAsynchronously=true`.

**Comment by martinbonnin** [comment]
Closing as it's merged in `dev-3.x`
