### ISSUE TITLE
Multi-module configuration not working

### ISSUE THREAD

**Issue by vlazdra** [apollographql/apollo-android#2872]
Hi, so I am trying to separate the logic for GraphQL code and the main app in my Android app. But with that separation I want to be able to share the Fragments that get generated via the Apollo library based on the schema.

My setup is a multi-module attempt at this, so really hoping something like this is possible.
I have the main **:app** module and I introduced the **:repositories** module in the project. The purpose is that I want to define the **schema.json** and all **queries** inside the :repositories module so that the only thing that get's exposed to the main :app module are only the models only.

The problem I am having is this:
> Cannot access 'com.apollographql.apollo.api.GraphqlFragment' which is a supertype of 'fragment.OverviewModelV2'. Check your module classpath for missing or conflicting dependencies

The setup of the modules is:
```
// :app

plugins {
   ...
   id("com.apollographql.apollo").version("2.5.2")
   ...
}

dependencies {
   ...
    apolloMetadata(project(":repositories"))
    implementation(project(":repositories"))
   ...
}
```

And this is the setup of the module:

```
// :repositories

plugins {
   ...
   id("com.apollographql.apollo").version("2.5.2")
   ...
}

apollo {
   generateKotlinModels.set(true)
   @Suppress("EXPERIMENTAL_API_USAGE")
   generateApolloMetadata.set(true)
}

dependencies {
   ...
    implementation("com.apollographql.apollo:apollo-runtime:2.5.2")
   ...
}
```

I tried following this tutorial: https://github.com/apollographql/apollo-android-tutorial but it seams that my sue case is the other way around a bit.

If anyone could help or direct me to something that might resolve, it would be much appreciated.

**Comment by martinbonnin** [comment]
Hi ! Thanks for reaching out! In your specific case, I don't think you need Apollo "multi-module" support because all your GraphQL files are in the `repository` module, right? You should be able to safely remove the plugin and `apolloMetadata` from your `app` module.

I think the problem is that `apollo-runtime` is not transitively exposed to your `app` module. Can you try to replace: 

```
implementation("com.apollographql.apollo:apollo-runtime:2.5.2")
```

with 

```
api("com.apollographql.apollo:apollo-runtime:2.5.2")
```

**Comment by vlazdra** [comment]
Hi Martin and thanks for such a speedy message! 👍 

Indeed that is true, I can switch the dependency from `implementation` to `api`, but then I get something that I want to avoid, if possible of course.

I wan't to avoid having the ability to have access to the apollo code directly. In other words I want to prevent having the ability to reference the ApolloClient class for example in my `:app` module. I just want to have access to the generated fragments that are in the `:repository` module.

What do you think, is this possible?

**Comment by martinbonnin** [comment]
What you can do is add `apollo-api` as an `implementation` dependency in your `app` module. This is a very small artifact that contains `GraphQLFragment` and a few other support classes but not `ApolloClient`.

**Comment by vlazdra** [comment]
That would solve the problem, yes.
Will do it like that then, thanks for the help much appreciated!
