### ISSUE TITLE
Content-Type: "application/json; charset=utf-8" causes HTTP 422 Unprocessable Entity in graphql-java-spring

### ISSUE THREAD

**Issue by vikrama** [apollographql/apollo-android#2882]
**Summary**
Interceptor sets **Content-Type: application/json; charset=utf-8** that causes SpringMVC based https://github.com/graphql-java/graphql-java-spring to throw a HTTP 422 Unprocessable Entity

**Version**
2.4.6

**Description**
Sending a mutation (POST) to a springmvc based graphql server returns a 422. Figured out that Content-Type is the issue in my case.

Between ApolloCall, ApolloServerInterceptor, ApolloHTTPNetworkTransport, OkHttp's RealCall and a bunch of interceptors there, if a mutation's RequestBody is set with a Content-Type, OkHttp uses that to set the Request Header. 

What I have tried to alleviate this problem:
* Tried setting ApolloMutationCall.RequestHeaders that overrides the Content-Type header to application/json. No luck
* Tried setting application interceptors and also network interceptors that fixes the header in a custom OkHttpClient for ApolloClient. No luck.

**Deprecation of charset=utf-8 in Content-Type header**
https://github.com/spring-projects/spring-framework/issues/22788
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/MediaType.html#APPLICATION_JSON_UTF8

As in the discussions & docs above, [RFC8259](https://tools.ietf.org/html/rfc8259) has made the charset subtype not necessary. All popular browsers have implemented the change. In apollo-android case, I'm not sure if OkHttp has already implemented the change. 

**Temporary fix that works**
Using a custom [GraphQLController](https://github.com/graphql-java/graphql-java-spring/blob/master/graphql-java-spring-webmvc/src/main/java/graphql/spring/web/servlet/components/GraphQLController.java#L48) in the server to handle an incoming Content-Type with charset seems to be the easier (and the only) workaround right now.

**Related bug reports**
https://github.com/apollographql/apollo-android/issues/1571

**Draft PR**
https://github.com/vikrama/apollo-android/pull/1/files

What do you think is the right step forward? If you think OkHttp is where I should be filing this bug against, let me know. Also, if there is any other way around the Apollo application interceptor, OkHttp application & network interceptor that don't seem to work for me, any help is appreciated.

**Comment by martinbonnin** [comment]
Hi ! Thanks for the detailed issue. A few thoughts: 

1. Switching from `apollication/json; charset=utf-8` to`application/json` seems very reasonable to me. Do you mind opening the PR on the repo?
2. OkHttp is fine as it really is doing what we tell it to do so no need to file a bug there.
3. It's a bit weird that the server isn't robust to that as it shouldn't cost much to ignore the charset if it's utf-8. It might be worth trying to understand more why that was done even if ultimately, I agree using `application/json` makes sense.
4. If you're using multiplatform, you should be able to workaround by passing your custom OkHttpClient with interceptors to ApolloHttpNetworkTransport()

**Comment by vikrama** [comment]
Addressed by #2883. PR merged
