### ISSUE TITLE
Please publish 1.x to Maven central

### ISSUE THREAD

**Issue by ber4444** [apollographql/apollo-android#2914]
This is because Bintray, which you relied on, is going away: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by ber4444** [comment]
e.g. we use 1.4.5 but it's not published in central: https://repo1.maven.org/maven2/com/apollographql/apollo/apollo-runtime/

**Comment by martinbonnin** [comment]
I was expecting this one 😅 . We'll do that. If anybody has any pointers how to transfer artifacts, I'll take them!

**Comment by martinbonnin** [comment]
Damn, the old versions poms do not match the MavenCentral requirements (project url and developer information missing...). I'll have to patch that manually.

**Comment by martinbonnin** [comment]
Hi @ber4444 👋 . Version 1.4.5 should now be on mavenCentral. Can you check and confirm it's working for you? If it is, I'll move all the other versions.

**Comment by ber4444** [comment]
perfect, thanks!

**Comment by martinbonnin** [comment]
All versions should now be in, closing this
