### ISSUE TITLE
Add support for passing custom `extensions` in the HTTP body

### ISSUE THREAD

**Issue by 100905067** [apollographql/apollo-android#2922]
**Is your feature request related to a problem? Please describe.**
Currently, we do not have a way to modify **requestBody** in Apollo.   #https://spectrum.chat/apollo/apollo-android/how-to-modify-request-body-extensions-field-in-apollo-android~f2bf28e5-2e86-4c73-8b6e-5b1027f724f2

**Describe the solution you'd like**
A method in ApolloQueryCall to modify request body similar to "requestHeaders".

**Comment by martinbonnin** [comment]
Thanks for filing this! 

I changed the title to include only `extensions`, I don't think we want to add specific APIs for arbitrary body modification? Worst case this can be done through interceptors. `extensions` on the other hand seem pretty handy and something that needs confiuring. 

My initial thought would be to allow passing a custom instance of `OperationRequestBodyComposer`. Maybe with 3.0 execution contexts

**Comment by martinbonnin** [comment]
This is possible in `3.0.0-rc01` by passing a custom `HttpRequestComposer`. See https://github.com/apollographql/apollo-android/pull/3671 for an example.
