### ISSUE TITLE
Missing fragments in generated query

### ISSUE THREAD

**Issue by dominolog** [apollographql/apollo-android#2927]
**Summary**
I can see below error returned from server
`{"errors":[{"message":"Unknown fragment \"UniformTagLevel\".","request_id":"ab4wov0HDwxfNJCgQb7i"},{"message":"Unknown fragment \"UniformTagLevelTeam\".","request_id":"ab4wov0HDwxfNJCgQb7i"},{"message":"Unknown fragment \"UniformTag\".","request_id":"ab4wov0HDwxfNJCgQb7i"}],"extensions":{"completedMs":3}}`

**Version**
2.3.0

**Description**
The code compiles correctly, all kotlin code is generated correctly. Problem is not all fragments are sent with query to server.

**Comment by martinbonnin** [comment]
Hi @dominolog ! Thanks for reaching out and sorry this happened. Can you share your schema and query?
