### ISSUE TITLE
[3.x] Kotlin 1.3 compatibility

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#2931]
The current generated code assumes Kotlin 1.4 and breaks on stuff like trailing comas, we should make sure the generated code works with Kotlin 1.3

**Comment by audkar** [comment]
Is Kotlin Native binary compatible with <1.4? Let's say that Apollo graphql generator generates KT 1.3 compatible code, but Apollo runtime library has dependency on Coroutines library which is compiled with KN 1.4. Will it work?

**Comment by martinbonnin** [comment]
Generally speaking every new Kotlin release requires every native lib and app to be rebuilt.

I didn't look into all the details but binary compatibility is wayyyyy different on native than it is on the JVM. If you're using a native version of apollo build with Kotlin 1.4, you'll most likely have to compile everything with 1.4 including the generated models.

**Comment by martinbonnin** [comment]
It looks like the 1.3 compiler can actually not read metadata from 1.5 so 1.3 compatibility doesn't seem possible at that point. Users will have to update. Also good thing we have [this](https://github.com/apollographql/apollo-android/blob/82cd2bc6c97fe092a20e67912ecdf806421f215d/README.md#L103) in the README.md already.
