### ISSUE TITLE
Kotlin Multiplatform testing

### ISSUE THREAD

**Issue by josephmbeveridge** [apollographql/apollo-android#2942]
**Is your feature request related to a problem? Please describe.**
There is currently no way to test results of queries coming from Apollo in Kotlin Multiplatform due to how the private constructors are defined on objects like `Response.Builder` (note that KMP mocking libraries are basically non-existent and this would require PowerMock or equivalent to handle private access). This makes writing tests for edge cases impossible without adding a layer between the response and your business logic. However, even if you add a middle layer you still want to test the `Response` -> layer edge cases.

**Describe the solution you'd like**
Provide a way to instantiate private classes or a testing setup that allows you to fake responses from Apollo for tests.

**Comment by martinbonnin** [comment]
Hi 👋  

While the `Response.Builder` class is internal, the primary data class constructor is not: https://github.com/apollographql/apollo-android/blob/main/apollo-api/src/commonMain/kotlin/com/apollographql/apollo/api/Response.kt

So the below should work:

```
    val response  = Response(
      operation = operation,
      data = data,
      errors = emptyList(),
      extensions = emptyMap()
    )
```

I 100% agree this is inconsistent and there's no reason for one to be internal and not the other but that should make it possible to fake responses.

Also, a convenient method is [`Operation.parse`](https://github.com/apollographql/apollo-android/blob/edda84c4ec76a995064cb42dce5a565fff6b6869/apollo-api/src/commonMain/kotlin/com/apollographql/apollo/api/Operation.kt#L56). If you have a fake Json, it will parse it and produce a ready to use `Response`, possibly including errors if any.

**Comment by josephmbeveridge** [comment]
🙌 thank you for the quick reply and tips, this should work great

**Comment by martinbonnin** [comment]
Sure thing, let us know how that goes!

**Comment by martinbonnin** [comment]
I'm going to close this one, let me know if you want to reopen.
