### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by wmhtet** [apollographql/apollo-android#297]
I am trying to setup and learn the appolo graphql for android. The readme info and the sample app are different. I  have also run into issue #292 with sample app. I go to the wiki and all the links are 404. Here is one of them.

https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/test/testProject/android/buildScriptFixtures/pojo.gradle#L47

I am very new to graphql and it would help me greatly if the readme, wiki and sample app go in tandem in providing the information.

**Comment by VisheshVadhera** [comment]
- [ ] Quick Start
- [ ] FAQ Section
- [ ] How to create Queries & Mutations
- [ ] Caching Strategies
- [ ] Using fragments

**Comment by GurpreetSK95** [comment]
Hi, I would like to contribute to the project by helping with adding documentation. As apollo-android is a sister-project of apollo-ios, I am thinking of starting by going through its documentation and drawing inspiration from it. Can anyone give more inputs on how I should go ahead?

Thanks.

**Comment by digitalbuddha** [comment]
Please join our slack. There is a link in the Readme. We can discuss in the Android channel

**Comment by tasomaniac** [comment]
These are good suggestions. Looking forward for improvements. 💯 

My short-term suggestion is to just delete the WIKI all together for now. It's not updated for a year now and the links have 404. That's kind of confusing.

**Comment by martinbonnin** [comment]
I just deleted the obsolete wiki. I'm keeping this ticket open to provide some more in-depth guides, either in the wiki or in some other place .

**Comment by martinbonnin** [comment]
See https://github.com/apollographql/apollo-android/pull/1768 for reorganization of the documentation. 

See also https://github.com/apollographql/apollo-android/issues/1773 and https://github.com/apollographql/apollo-android/issues/1772 for adding more documentation for subscriptions/persisted queries. Feel free to open other tickets for areas where you feel documentation is lacking.
