### ISSUE TITLE
Running the kotlin downloadApolloSchema to get schema.json throwing error.

### ISSUE THREAD

**Issue by johnkaita1997** [apollographql/apollo-android#2975]
I am attempting to generate a schema.json using the downloadApolloSchema as mentioned in the docs, but can't seem to get to get around the error below: What am  I  not doing right? I am running this code on the terminal android-studio

The Code:
`gradlew downloadApolloSchema \
  --endpoint="https://api.github.com/graphql" \
  --schema="src/main/graphql/schema/github/schema.json" \
  --header="Authorization: Bearer myactualtoken" `

And here is the error I am getting:

```
E:\Developement\Android Kotlin Projects\IssueTracker>gradlew downloadApolloSchema \
  --endpoint="https://api.github.com/graphql" \
  --schema="src/main/graphql/schema/github/schema.json" \

> Configure project :app
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Task '\' not found in root project 'IssueTracker'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

**Comment by martinbonnin** [comment]
Hi 👋 , it looks like the Google Services plugin is missing its `google-services.json`. Can you try to one as described there: https://developers.google.com/android/guides/google-services-plugin?

**Comment by johnkaita1997** [comment]
Hey @martinbonnin, thanks it is weird because I have the google-services.json file app directory 
![2021-03-03 15_54_54-Window](https://user-images.githubusercontent.com/57174350/109791780-b0367780-7bc7-11eb-8260-bdbb7251a936.png)

**Comment by martinbonnin** [comment]
Ah right, sorry I missed the last part. It looks like gradle is interpreting `'\'` as your task name is the real erro. I'm not super used to using gradle on windows but maybe try everything on one line?

```
>gradlew downloadApolloSchema  --endpoint="https://api.github.com/graphql"  -schema="src/main/graphql/schema/github/schema.json"
```

**Comment by johnkaita1997** [comment]
I can't thank you enough, @martinbonnin, that was the problem I was facing.

**Comment by martinbonnin** [comment]
Nice! Thanks for the follow up 👍
