### ISSUE TITLE
Android Studio 2.3 broke Integration Tests

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#299]
started getting errors `java.io.FileNotFoundException: src/test/graphql/allPlanetsResponse.json (No such file or directory)` when running IntegrationTest.java inside of studio. @brianPlummer has a fix

**Comment by BenSchwab** [comment]
I was also experiencing this. But what's weird is the tests run fine on CI

**Comment by digitalbuddha** [comment]
It's not running locally be cause studio is 2.3

**Comment by marwanad** [comment]
Closed by #300.
