### ISSUE TITLE
__typename differs every time Fragment is read from cache

### ISSUE THREAD

**Issue by leevida** [apollographql/apollo-android#3007]
**Summary**
I have a fragment that I use in a couple of places. Every time I read the Fragment from the cache, the `__typename` differs

**Version**
2.5.4

**Description**
**queries/mutations/fragments:**
```
query ContentContainer($urn: String!) {
    contentContainer(urn: $urn) {
        urn
        title
        imageUrl
        favorite {
            ...FavoriteFragment
        }
    }
}
```

```
mutation UpdateFavorite($urn: String!, $isFavorited: Boolean!) {
    updateFavorite(urn: $urn, isFavorited: $isFavorited) {
        ...FavoriteFragment
    }
}
```

```
fragment FavoriteFragment on Favorite {
    urn
    isFavorited
}
```
**Steps:**
I make a request to ContentContainer. Then I make multiple requests to UpdateFavorite.
Before each request to UpdateFavorite I read from the cache:
```
val responseFieldMapper = FavoriteFragment.Mapper()
val favoriteFragment = apolloStore.read(responseFieldMapper, CacheKey.from(urn), Operation.EMPTY_VARIABLES).execute()
```
The fragment that I get back sometimes has "ContentContainer" and other times has "Favorite" as the `__typename` which makes it hard to work with that field.

**Comment by martinbonnin** [comment]
Thanks for filing this. Can you share how you are writing the fragment into the cache? I would expect reading from the cache to be at least deterministic. Could it be that something else is writing in parallel?

**Comment by leevida** [comment]
Hi, I'm updating the cache optimistically so I'm updating before I make the Mutation request. I think I'm doing everything synchronously since I am calling `execute()`.

```
        val responseFieldMapper = FavoriteFragment.Mapper()
        val favoriteFragment = apolloStore.read(responseFieldMapper, CacheKey.from(urn), Operation.EMPTY_VARIABLES).execute()
        if (favoriteFragment != null) {
            val newFavorite = FavoriteFragment(
                favoriteFragment.__typename(),
                favoriteFragment.urn(),
                isFavorited
            )
            apolloStore.writeAndPublish(newFavorite, CacheKey.from(favorite.urn.urn), Operation.EMPTY_VARIABLES).execute()
        }

        val mutation = UpdateFavoriteMutation(urn, isFavorited)
        apolloClient
            .mutate(mutation)
            .toBuilder()
            .build()
            .rx()
            .subscribe()
```

I'm doing the `read` before the `write` because I don't know what the `__typename()` should be. Is there a best practice for creating a Fragment with a typename without having to read it in the first place?

**Comment by martinbonnin** [comment]
Thanks! If you know the type of your object, you can hardcode it. Looks like in your case, it should be "Favorite"?

**Comment by martinbonnin** [comment]
@leevida any news here? Would passing the typename explicitely work?

**Comment by leevida** [comment]
Hi @martinbonnin , yes, it looks like it's working by using "Favorite" as the __typename. It was a bit confusing with the changing value and had a different bug in the CacheKeyResolver.
```
override fun fromFieldRecordSet(field: ResponseField, recordSet: Map<String, Any>): CacheKey {
                if (recordSet["__typename"] == "ContentContainer" && recordSet["urn"] != null) { // Favorite fragment can have "ContentContainer" as __typename so need to be more specific for ContentContainers
                    return recordSet["urn"] as? String
                }
                return recordSet["id"] as? String
            }
```

Things are working for me, but the changing `__typename` seems to be a bit weird to me. It's hard to know what it represents and if it's stable. All fixed for me though.

**Comment by martinbonnin** [comment]
Thanks for the follow up! We're planning to rework that part significantly in 3.0.0 so I'm going to close this one. If anything becomes blocking again, please leave a message and I'll reopen.
