### ISSUE TITLE
Error while generating code

### ISSUE THREAD

**Issue by TonnyL** [apollographql/apollo-android#3013]
**Summary**
Error info: Failed to parse `path-to-graphql-file`:
`fieldA` cannot be merged with `fieldB`: they have different shapes

Here `fieldA` has the same name with `fieldB`, but different nullability.

**Version**
+ apollo-android: 3.0.0-SNAPSHOT
+ Android Studio: Android Studio Arctic Fox | 2020.3.1 Canary 10
+ Gradle: 6.8.2

**Description**
+ Content of my graphql file:
```graphql
fragment PinnableItem on PinnableItem {
  __typename
   # https://docs.github.com/en/graphql/reference/objects#repository
  ... on Repository {
    owner {
      ... on RepositoryOwner { # non-null
        # A URL pointing to the owner's public avatar.
        avatarUrl
        # The username used to login.
        login
        # The HTTP URL for the owner.
        resourcePath
        # The HTTP URL for the owner.
        url
      }
    }
  }
  # https://docs.github.com/en/graphql/reference/objects#gist
  ... on Gist {
    owner {
      ... on RepositoryOwner { # nullable
        # A URL pointing to the owner's public avatar.
        avatarUrl
        # The username used to login.
        login
        # The HTTP URL for the owner.
        resourcePath
        # The HTTP URL for the owner.
        url
      }
    }
  }
}
```

+ Where to download the schema definition file:
https://docs.github.com/public/schema.docs.graphql

+ Screenshot of detailed error information:
<img width="1285" alt="Screen Shot 2021-03-20 at 19 31 55" src="https://user-images.githubusercontent.com/13329148/111868105-facf3680-89b2-11eb-8722-3ae90840e929.png">

**Comment by martinbonnin** [comment]
Hi @TonnyL 👋  ! I think this is how it is supposed to work? From https://spec.graphql.org/June2018/#sec-Field-Selection-Merging:

```
If typeA or typeB is Non‐Null.
If typeA or typeB is nullable, return false.
Let typeA be the nullable type of typeA
Let typeB be the nullable type of typeB
```

Does it actually work in the Github explorer?

**Comment by TonnyL** [comment]
Thanks for the quick response, you saved my day!

My code above doesn't work in Github explore. But it actually works on an old stable version(2.5.3) of apollo-android. So I thought it might be a bug of new version of apollo-android 😂.

**Comment by martinbonnin** [comment]
Sure thing !
