### ISSUE TITLE
Unsupported token `immediately`

### ISSUE THREAD

**Issue by john-lanticse** [apollographql/apollo-android#3017]
**Summary**
Sorry, I'm still new to GraphQL. I have this part of the GraphQL request,
```
                    asset {
                        id
                        url @transform (width: 1500, immediately: true)
                    }
```
but it never runs because it throws the error Unsupported token `immediately`. I think this is a valid GraphQL and the iOS version seems to be ok. 

**Version**
`apollo-runtime:2.3.1`

**Comment by martinbonnin** [comment]
Can you try moving the directive after the arguments? 

```
                    asset {
                        id
                        url(width: 1500, immediately: true) @transform
                    }
```

**Comment by john-lanticse** [comment]
thank you very much. moving the directive works. 

you can close this if this is not actually a bug.

**Comment by martinbonnin** [comment]
Nice, thanks for the follow up 👍 !
