### ISSUE TITLE
Apollo Client Dispatcher Use of SynchronousQueue

### ISSUE THREAD

**Issue by glacier** [apollographql/apollo-android#3018]
**Question.**

Why does the [default dispatcher](https://github.com/apollographql/apollo-android/blob/87d6d471f427ec79468aa900930daf9c5d965160/apollo-runtime/src/main/java/com/apollographql/apollo/ApolloClient.java#L808-L816) use a  [SynchronousQueue](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/SynchronousQueue.html) as the work queue?

I'm wondering about the motivation behind choosing this type over other types such as a LinkedBlockingQueue. SynchronousQueue will block the producer thread until a consumer takes it. This behavior is likely to add latency to a server-side application that is invoking a GQL service using this Apollo Java client (and I've discovered some evidence of this in one of my projects).

**Comment by martinbonnin** [comment]
Good question, maybe @sav007 will have more insight about this.

In all cases, you should be able to override the default dispatcher with a dispatcher using `LinkedBlockingQueue`:

```
    ApolloClient.builder()
        .dispatcher(ThreadPoolExecutor(0, Int.MAX_VALUE, 60, TimeUnit.SECONDS, SynchronousQueue()))
        .serverUrl("https://...")
        .build()
```

**Comment by martinbonnin** [comment]
@glacier did specifying the dispatcher explicitly reduce latency? I'm hesitant to change the dispatcher given it's a pretty low level change so if the explicit route worked, I'll close this bug.

**Comment by martinbonnin** [comment]
Closing for now as the default dispatcher seems to work well for most of the use cases and is configurable for more advanced use cases. Please leave a message if you want me to reopen.
