### ISSUE TITLE
Enable support for the graphql-ws protocol in apollo-android

### ISSUE THREAD

**Issue by dchappelle** [apollographql/apollo-android#3029]
This is the Android version of the following iOS feature request: https://github.com/apollographql/apollo-ios/issues/1622

graphql-ws seems to be the preferred protocol going forward, replacing subscriptions-transport-ws which has fallen into disrepair in recent years. I would like to see apollo-android adopt this newer protocol.

**Comment by martinbonnin** [comment]
Sounds good 👍 . I'm going to ask the same question as in the iOS issue, is there a server I could test against somewhere? @dchappelle If you're having the issue, any chance your endpoint is public?

**Comment by dchappelle** [comment]
@martinbonnin currently we don't have a public backend for testing but if that changes I'll post it here.

**Comment by martinbonnin** [comment]
Thanks! That'd help tremendously. 
Did you get to the point of trying Apollo Android with your backend, do you know what it currently fails with?

**Comment by dchappelle** [comment]
With a few hacks I was able to get it to work our backend. Basically just had to change "start" to "subscribe", "stop" to "complete" and "data" to "next" and so far so good

**Comment by martinbonnin** [comment]
Linking the PR that introduced `WsProtocol`: https://github.com/apollographql/apollo-android/pull/3102

**Comment by martinbonnin** [comment]
Please test with [3.0.0-alpha01](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-alpha01):

```kotlin
    val apolloClient = ApolloClient(
        networkTransport = WebSocketNetworkTransport(
            serverUrl = "http://localhost:9090/graphql",
            protocol = GraphQLWsProtocol()
        )
    )
```
