### ISSUE TITLE
QueryWatcher crashes when refetch()

### ISSUE THREAD

**Issue by TSurawanwijit** [apollographql/apollo-android#3032]
**Summary**
When using `Rx2Apollo`, `QueryWatcher` will crash immediately when calling `refetch()`.

**Version**
2.5.5

**Description**
When using `Rx2Apollo`, `QueryWatcher` will crash immediately when calling `refetch()`.
```kotlin
java.lang.IllegalStateException: Cannot refetch a watcher which has not first called enqueueAndWatch.
        at com.apollographql.apollo.internal.RealApolloQueryWatcher.refetch(RealApolloQueryWatcher.java:124)
        at com.example.myapplication.MainActivity$onCreate$2.onClick(MainActivity.kt:107)
        at android.view.View.performClick(View.java:6205)
        at android.widget.TextView.performClick(TextView.java:11103)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View$PerformClick.run(View.java:23653)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
Here is my example code:

I create a query watcher as shown below
```kotlin
            val query = MyQuery()

            val watcher = apolloClient.query(query)
                    .toBuilder()
                    .responseFetcher(ApolloResponseFetchers.CACHE_FIRST)
                    .build()
                    .watcher()
                    .refetchResponseFetcher(ApolloResponseFetchers.CACHE_FIRST)

            Rx2Apollo.from(watcher)
                    .observeOn(mainThread())
                    .subscribe(
                            {
                                //Do something
                            },
                            {
                                //Do something
                            }
                    )

```
Then I call `refetch()`
```kotlin
        watcher.refetch()
```

**Comment by martinbonnin** [comment]
Hi @TSurawanwijit, sorry for the late response. Can you give some more details about your use case? 

My understanding is that `refetch` is mostly an API used by `ApolloMutationCall.Builder.refetchQueries()`. 
If you're not doing any mutation, you would usually subscribe exactly like you did and that should start emitting results. Is there a specific reason you call `refetch` ?

**Comment by TSurawanwijit** [comment]
I want queryWatcher to emit the same result again because my code doesn't keep the result from previous emission. I just all refetch when I need it. It was working before I update `apollo` to latest version.

I found the crash come from [this change](https://github.com/apollographql/apollo-android/commit/bca4de4d05cb9bcc30469648eb2dc13d9ad7d455#diff-983742046575d45e63efbf1b9720c754029802c11875162802538823ad2c72d3).

> My understanding is that `refetch` is mostly an API used by `ApolloMutationCall.Builder.refetchQueries()`.

So, can I continue using this `refetch`? The api doesn't tell that it should only be used by `ApolloMutationCall.Builder.refetchQueries()`
```java
/**
   * Re-fetches watched GraphQL query.
   */
  void refetch();
```

**Comment by martinbonnin** [comment]
> I want queryWatcher to emit the same result again because my code doesn't keep the result from previous emission. I just all refetch when I need it.

Thanks for the details! The problem here is a conflict between reactive usages (RxJava) and imperative usages (manually calling `refetch` and having the stream updated as a side effect). Since the watcher is cloned by RxJava, the original one is never executed so it doesn't really make sense to refetch it.

I believe one way to fix this would be to use something like a [`BehaviorSubject`](http://reactivex.io/RxJava/javadoc/io/reactivex/subjects/BehaviorSubject.html) to remember the last emitted value. 

Also, I'm curious why you need a watcher if you control when the updates need to happen. Maybe a simple query would do here?

**Comment by TSurawanwijit** [comment]
OK. I just want to inform you about this crash. I think it would be more friendly for other people if refetch() works correctly on every case: call directly, rx2, rx3, coroutine.

**Comment by martinbonnin** [comment]
Thanks for the heads up! I added a note to the `2.4.0` release where this behaviour changed happened: https://github.com/apollographql/apollo-android/releases/tag/v2.4.0.

Let me know if I can help updating to the new behaviour. If not, I'll close this issue.

**Comment by TSurawanwijit** [comment]
Thank you.
