### ISSUE TITLE
Support enums with different cases

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#3035]
The following enum 

```graphql
enum SomeEnum {
  someValue @deprecated(reason: "use SOME_VALUE instead")
  SOME_VALUE
}
```

fails to compile because it would generate twice the same enum. To fix this we should respect the case of the schema. This is going to be a breaking change so it must be opt-in.

**Comment by martinbonnin** [comment]
This should work now in [3.0.0-alpha01](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-alpha01), closing this issue.

**Comment by atulgpt17** [comment]
Hi @martinbonnin  in version 4.0 it is again creating the enum with PascalCase, is that expected? If yes what was the issue detail for the same?

**Comment by martinbonnin** [comment]
@atulgpt17 we now aim to use the same name in GraphQL and in Kotlin. If that's not the case (no pun intended), please open a separate issue.
