### ISSUE TITLE
Add QueryWatching

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#304]
Proposed changes:

- Add watch to `ApolloCall` : ` @Nonnull ApolloCall<T> watch(@Nullable Callback<T> callback);` (This callback can / will be called multiple times)
- `Watch` first calls `enqueue`, respecting caching preference, and then subscribes to `RealCache`'s changed keys with the queries `dependentKeys` (iff first `execute` is successful)
- Have `CacheStore` return changed keys on write, `RealCache` aggregates and dispatches to subscribers
- In subscribe, if dependent keys !disjoint to change keys, refetch watched query

Note, this will add more logic bloat to `RealApolloCall`

**Comment by sav007** [comment]
`dependentKeys` does it holds all keys been used by query?

**Comment by sav007** [comment]
Could you please elaborate more on `In subscribe, if dependent keys !disjoint to change keys, refetch watched query`. I thought if `ApolloCall` receives notification about dependentKeys changes that it depends on, then we refetch query

**Comment by BenSchwab** [comment]
"In subscribe, if dependent keys !disjoint to change keys, refetch watched query"

Is worded poorly. `ApolloCall` or `ApolloWatcher` will refetch when a dependentKey changes. This occurs when dependKeys for one query is not disjoint from the set of changedKeys from another query.
