### ISSUE TITLE
Using local schema.graphql, getting error "ApolloGraphQL: cannot find schema.[json | sdl]"

### ISSUE THREAD

**Issue by RLEE0731** [apollographql/apollo-android#3083]
We're using a local schema in SDL, instead of puling in schema.json through introspection. The file (schema.graphql) is added to the folder path "./src/main/graphql/com/android/data/", in relation to the Android project directory. 
On build we're getting the error: "ApolloGraphQL: cannot find schema.[json | sdl]". 

One thought is maybe the schema is mal-formatted, however the same schema.graphql file works fine on iOS. Seems like there may be some unexpected handling of local SDL schema on Android side?  Our server does not allow introspection, so this is the only way for us to setup graphql.

**Comment by martinbonnin** [comment]
Hi @RLEE0731 👋 

You'll have to rename your `schema.graphql` file to `schema.sdl`. This is so that it's not confused with other `*.graphql` operation files. Alternatively, you can also use `schema.graphqls` starting with version `2.5.5`

**Comment by RLEE0731** [comment]
ah I see, that did the trick! Thanks for the clarification :)
