### ISSUE TITLE
How to change ApolloDownloadSchemaTask output to ".sdl"

### ISSUE THREAD

**Issue by diogo10** [apollographql/apollo-android#3089]
**Question.**

I have this task:

`
tasks.register("downloadSchema", com.apollographql.apollo.gradle.internal.ApolloDownloadSchemaTask) {
    endpoint = project.properties['graphql.schemaEndpoint']
    schemaRelativeToProject = "src/main/graphql/schema.sdl"
}
`

It does not download the schema on sdl format. Always on json format. Changing to .graphql does not help. It comes as .json format. Do we need to set another param?

**Comment by martinbonnin** [comment]
`ApolloDownloadSchemaTask` will not convert automatically to SDL. 

You can either do that from using `ApolloDownloadSchemaCliTask` (sorry for the Kotlin DSL)

```kotlin
tasks.register("downloadSchema", com.apollographql.apollo.gradle.internal.ApolloDownloadSchemaCliTask::class.java) {
    endpoint.set("https://apollo-fullstack-tutorial.herokuapp.com/graphql")
    schema.set(file("src/main/graphql/schema.sdl").absolutePath)
}
```

or using the APIs directly if you need more flexibility:

```kotlin
tasks.register("downloadSchema") {
    doLast {
        // Retrieve the introspection schema as json
        val introspection = com.apollographql.apollo.gradle.internal.SchemaDownloader.downloadIntrospection(
            endpoint = "https://apollo-fullstack-tutorial.herokuapp.com/graphql",
            headers = emptyMap()
        )

        // then convert it to SDL
        val sdl = okio.Buffer().apply {
            com.apollographql.apollo.compiler.parser.introspection.IntrospectionSchema(
                introspection.byteInputStream()
            ).toSDL(buffer)
        }.readUtf8()

        val schemaFile = file("src/main/graphql/schema.sdl")
        schemaFile.parentFile.mkdirs()
        schemaFile.writeText(sdl)
    }
}
```

**Comment by diogo10** [comment]
Thanks, @martinbonnin. Works as expected
