### ISSUE TITLE
Variant 'apolloCommonMainServiceProducer' in project does not match the consumer attributes

### ISSUE THREAD

**Issue by Saturas89** [apollographql/apollo-android#3098]
Hey, 
I want to use the graphql client in a KMM and generate via gradle plugin the graphql query classes.
But I cant build my project with the dependency apollo-runtime-kotlin in commonMain.
First I got a problem like [this](https://github.com/Kodein-Framework/Kodein-DI/issues/264), so I added their solution snippet, but now i get this error while building:

 > Could not determine the dependencies of task ':checkCommonMainServiceApolloDuplicates'.
  > Could not resolve all task dependencies for configuration ':apolloCommonMainServiceDuplicatesConsumer'.
   > Could not resolve project :.
     Required by:
         project :
      > Variant 'apolloCommonMainServiceProducer' in project : does not match the consumer attributes
        Variant 'apolloCommonMainServiceProducer' capability org.example:my-project:unspecified declares a component, as well as attribute 'com.apollographql.service' with value 'service', attribute 'com.apollographql.variant' with value 'commonMain':
          - Incompatible because this component declares a usage of 'apollo-metadata' of a component and the consumer needed a runtime of a component

Here is my build.gradle.kts:
[build.txt](https://github.com/apollographql/apollo-android/files/6432465/build.txt)

**Comment by martinbonnin** [comment]
Hi 👋  Thanks for reaching out! That part (from https://github.com/Kodein-Framework/Kodein-DI/issues/264):

```kotlin
configurations.all {
    afterEvaluate {
        if (isCanBeResolved) {
            attributes {
                attribute(usage, project.objects.named(Usage::class.java, "java-runtime"))
            }
        }
    }
}
```

will confuse Apollo configurations as the Apollo plugin relies on a `apollo-metadata` usage. What you can do is not overwrite the attributes if it's already there:

```kotlin
configurations.all {
    afterEvaluate {
        if (isCanBeResolved && !attributes.contains(usage)) {
            attributes {
                attribute(usage, project.objects.named(Usage::class.java, "java-runtime"))
            }
        }
    }
}
```

**Comment by Saturas89** [comment]
Thanks a lot that error is gone :)

But now I got the next problem.

` Cannot add a configuration with name 'jsNpm' as a configuration with that name already exists.`

Do you have an idea?

**Comment by martinbonnin** [comment]
Not really sure, sorry. That seems related to the `JS` targets/configuration. Maybe try to ask on the Kotlin slack?

**Comment by martinbonnin** [comment]
I'm going to close this one as the original issue is fixed. Please let me know if you want me to reopen.
