### ISSUE TITLE
Add tvOS target

### ISSUE THREAD

**Issue by wooodenleg** [apollographql/apollo-android#3101]
Hey, we are using Apollo in multiplatform project but after few days of development the common code we've noticed that `iOS != tvOS` 😅 (even though they are the same?). So my feature request is basically to add a `tvOS` build target. 
We've made some research and the only blocker is Okio which does not have `tvOS` target ([issue here](https://github.com/square/okio/issues/930)). After that it's theoretically *"just to add"* the build target.

**Comment by ProVir** [comment]
Hi! Now it's not difficult to add tvOS support, how can I raise the task in priority?

**Comment by martinbonnin** [comment]
@ProVir it's in theory not very difficult (adding the targets there https://github.com/apollographql/apollo-android/blob/0254755bb2b0a516ca3b951d7e6a067d206f9296/build-logic/src/main/kotlin/Mpp.kt#L23). Looks like okio added it with `3.0.0-alpha.6`. One issue is that we can't ship `apollo-android-3.0` with an alpha version of okio so if we pull `okio-alpha` in the dependencies, it means no stable release of apollo android until okio releases too. Maybe it's ok maybe it's not. I'll take a deeper look.

**Comment by wooodenleg** [comment]
Closing this becasue `v3.0.0-beta02` added tvOS targets
