### ISSUE TITLE
Http logging for ApolloHttpNetworkTransport (Kotlin Runtime)

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#3107]
**Is your feature request related to a problem? Please describe.**
There is no easy way right now to setup `ApolloHttpNetworkTransport` with logging http network traffic. The only feasible way is to create a custom instance of `ApolloHttpNetworkTransport` for each platform with preconfigured logging in  `Call.Factory` / `DataTaskFactory`.

**Describe the solution you'd like**
It would be nice if Apollo client would have centralized API to configure networking logging.

**Comment by martinbonnin** [comment]
+1. This also came up on slack lately: https://kotlinlang.slack.com/archives/C01A6KM1SBZ/p1620675645115900

What about a "okhttp-like" interceptors API that would work with HTTP requests instead of GraphQL requests?

**Comment by sav007** [comment]
>What about a "okhttp-like" interceptors API that would work with HTTP requests instead of GraphQL requests?

Yes that will work, the only concern with that if this means we are trying to build KMP version of OkHttp or own version of Ktor :). I would suggest to start with logging, as adding okhttp like interceptors could be a big feature by itself.

**Comment by martinbonnin** [comment]
[3.0.0-alpha01](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-alpha01) has a [LoggingInterceptor](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-alpha01):

```kotlin
    val client = ApolloClient(
        networkTransport = HttpNetworkTransport(
            serverUrl = mockServer.url(),
            interceptors = listOf(LoggingInterceptor())
        )
    )
```
