### ISSUE TITLE
[Apollo Multimodule] Not detecting graphql files - Update documentation

### ISSUE THREAD

**Issue by emilianoalvarez91** [apollographql/apollo-android#3124]
**Is your feature request related to a problem? Please describe.**
The root module must have a `.graphql` file at the same level of the schema.json in order to work with multi modules and this is not documented.

**Describe the solution you'd like**
The [apollo-android-tutorial](https://github.com/apollographql/apollo-android-tutorial/tree/multi-modules) has a module named `graphqlLib` which it has a `queries.graphql` file and through this file the schema  and the graphql files from the `app` are detected. However, if you leave your root module only with the `schema.json` file, the multi module won't work and the graphql files in your separate modules won't be detected. Therefore, to fix this it's needed to add a `placeholder.graphql` empty file next to the `schema.json` file. It would be nice to have this [documented](https://www.apollographql.com/docs/android/advanced/multi-modules/) somewhere 😃

**Comment by martinbonnin** [comment]
Good catch! The task will be skipped with [NO-SOURCE] if no `.graphql` file is present, I'll add a note.

**Comment by martinbonnin** [comment]
PR: https://github.com/apollographql/apollo-android/pull/3125, let me know what you think.

In the long run, we want to improve this [NO-SOURCE]. This was made at a time when there was no multi-module and didn't age super well.
