### ISSUE TITLE
Bad error message for unused arg

### ISSUE THREAD

**Issue by fredells** [apollographql/apollo-android#3130]
**Summary**
- Attempting to build models for a query with an unused argument showed the following error message:
```
Required value 'id' missing at $.results[26]
```

**Version**
2.4.6

**Description**
example query:
```
query FooQuery($unusedArg: Boolean = true) {
  field1
  field2
}
```

**Comment by martinbonnin** [comment]
Hi 👋  GraphQL mandates that all variables are used: https://spec.graphql.org/draft/#sec-All-Variables-Used

If you were to send the FooQuery to a server, it should reject it.

**Comment by martinbonnin** [comment]
@fredells any news? There might be something to do with the error message but I'm not 100% sure what you mean. Can you share what you'd expect the behaviour to be here?

**Comment by martinbonnin** [comment]
Closing this issue, let me know if you want me to reopen it.

**Comment by fredells** [comment]
Oh sorry. I missed your notifications.

Yes I would also expect this to fail but the error message should indicate the actual problem.

Instead of:
```
Required value 'id' missing at $.results[26]
```

Expected:
```
Unused arg $unusedArg at src/graphql/FooQuery.graphql
```

**Comment by martinbonnin** [comment]
@fredells can you share the full stack trace when this happens?

**Comment by martinbonnin** [comment]
Apollo Android 3.x has a unit test for this: https://github.com/apollographql/apollo-android/blob/f0ac8d51b344df7993662a1e1ebb1fb617e0d30e/apollo-compiler/src/test/validation/operation/UnusedVariable.graphql#L1

**Comment by snijsure** [comment]
For client developers is there a way to run this test for all **client** queries and mutations when using Apollo Android 3.x?

**Comment by BoD** [comment]
Hi @snijsure. `failOnWarnings.set(true)` can be set so any warning provokes an error (more context [here](https://community.apollographql.com/t/how-to-catch-variable-is-never-used-errors-via-unit-tests/6395)). We are also going to make this an error instead of a warning in an upcoming release, to be closer to the GraphQL spec.
