### ISSUE TITLE
Parsing nested arrays

### ISSUE THREAD

**Issue by datrixo** [apollographql/apollo-android#3155]
I have problem with parsing field with nested array:
`description: [[FilterDescriptionElement!]]` 

where `FilterDescriptionElement` is:
```
interface FilterDescriptionElement {
  type: String!
}

type TextFilterDescriptionElement implements FilterDescriptionElement {
  displayName: String!
  type: String!
}

type IconFilterDescriptionElement implements FilterDescriptionElement {
  name: String!
  type: String!
}

type ImageFilterDescriptionElement implements FilterDescriptionElement {
  image: String!
  type: String!
}
```

The part of query looks like:
```
      ... on MultiSelectFilterGroup {
        description {
          ... on TextFilterDescriptionElement {
            type
            displayName
          }
          ... on IconFilterDescriptionElement {
            type
            name
          }
          ... on ImageFilterDescriptionElement {
            type
            image
          }
        }
```

Which throws:
`
Cause: not a valid name: As[FilterDescriptionElement!]
`

Any suggestions? Same query works fine on GraphiQL.

**Comment by martinbonnin** [comment]
Looks like a bug in the Java codegen (test case [here](https://github.com/apollographql/apollo-android/commit/3c3d54c4511df93437ee28f8a80bf9b4f69c10bf)). Is there any chance you could switch to Kotlin models? They support that case.

**Comment by datrixo** [comment]
@martinbonnin You'are right. On kotlin models it works correctly. Thanks!

**Comment by martinbonnin** [comment]
Cool. I'm closing this issue for now as we will need to revisit the Java codegen in all cases (see https://github.com/apollographql/apollo-android/issues/2616). Let me know if you want me to reopen.
