### ISSUE TITLE
[3.x] Need to provide dynamic connectionPayload to SubscriptionWsProtocol 

### ISSUE THREAD

**Issue by audkar** [apollographql/apollo-android#3164]
**Is your feature request related to a problem? Please describe.**
Authentication token needs to be provided for `SubscriptionWsProtocol` via `payload`. When token expires and client re-connects new token needs to be used.

**Describe the solution you'd like**
 Currently [SubscriptionWsProtocol](https://github.com/apollographql/apollo-android/blob/dev-3.x/apollo-runtime-kotlin/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/SubscriptionWsProtocol.kt#L15) only accepts value when client is constructed. It would be nice if it would accept `connectionPayload : value|lambda|suspendable lambda` as it is implemented in apollo `js` [counterpart](https://github.com/apollographql/subscriptions-transport-ws/blob/c6fb351fe3d7c7a447438798fab43c268b33036e/src/client.ts#L59)

**Comment by martinbonnin** [comment]
Hi @audkar ! Thanks for the feature request. Can you detail that part:

> When token expires and client re-connects new token needs to be used.

I think it's pretty well established that a 401 error requires a new token using plain HTTP but I'm unsure about websocket. Especially since there's no HTTP code like 401? What should trigger the refresh?

**Comment by audkar** [comment]
This is my first time working with graphql so I am not an authority by any means :smile: 
But in Apollo server [documentation](https://www.apollographql.com/docs/graphql-subscriptions/authentication/) is written that connection is rejected
> In case of an authentication error, the Promise will be rejected, and the client's connection will be rejected as well.

**Comment by martinbonnin** [comment]
I'll try to dig into this. What I'm trying to understand is how much this is a "specified thing" vs "each server will have a different implementation and we'll need to add APIs to customize that".

We can start with your use case. What server are you using? Is it available publicly by any chance?

**Comment by audkar** [comment]
We are using [Hasura](https://hasura.io/docs/latest/graphql/core/databases/postgres/subscriptions/index.html#communication-protocol) which uses same authentication as Apollo server

**Comment by martinbonnin** [comment]
I see, thanks for the feedback! Maybe it's simply a matter of making 

```kotlin
class SubscriptionWsProtocol(
    private val connectionPayload: Map<String, Any?>? = null,
    override val frameType: WsFrameType = WsFrameType.Binary
)
```

instead of 

```kotlin
class SubscriptionWsProtocol(
    private val connectionPayload: () -> Map<String, Any?>? = {null},
    override val frameType: WsFrameType = WsFrameType.Binary
)
```

Could you try with your backend and see if that works?

**Comment by audkar** [comment]
That helps to retrieve payload on `connectionInit()`. But: 
- It would be nice to have `suspend` lambda
- I don't see actual logic which reconnects when server rejects connection.

**Comment by martinbonnin** [comment]
@audkar that should be in the latest  SNAPSHOTs, I'll push a tag soon.

**Comment by martinbonnin** [comment]
[3.0.0-alpha01](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-alpha01) now has a `suspend fun` callback for `subscriptionPayload`. I'm closing this issue.  Feel free to open a new one for reconnections if needed
