### ISSUE TITLE
"Apollo iOS" Error Message in Apollo-Android

### ISSUE THREAD

**Issue by commonsguy** [apollographql/apollo-android#317]
Attempting to add `__typename` to a query results in:

```
:app:generateDebugApolloIR
Apollo iOS inserts __typename automatically when needed, please do not include it explicitly
Validation of GraphQL query document failed
:app:generateDebugApolloIR FAILED
```

However, this is from a Gradle build of an Apollo-Android project, and there are no iOS projects within kilometers of here, AFAIK.

Should these messages be genericized to just "Apollo"? Or should they be platform-aware?

**Comment by digitalbuddha** [comment]
@martijnwalraven could we make the error message more generic, I think this is comming from code gen.
