### ISSUE TITLE
GraphQl SDL conversion tool generates a weird output converting empty String default values

### ISSUE THREAD

**Issue by alcere** [apollographql/apollo-android#3172]
**Summary**
I came across with a weird conversion migrating our GraphQl json schema to sdl where empty string is converted to a value that the compiler doesn't support.

**Version**
2.5.9

**Description**
Migrating a String field with default value equal to empty String defined like this in the json:

```
{
   "name": "comment",
   "type": {
      "kind": "SCALAR",
      "name": "String",
      "ofType": null
   },
  "defaultValue": "\"\""
}  
```

results in:

```
comment: String = """"""""
```

in the .sdl file

This causes a compilation error while running `generateDebugServiceApolloSources` that complains with:

`Unsupported token `"""`

If I manually replace `comment: String = """"""""` by `comment: String = """"""`, everything works fine

**Comment by martinbonnin** [comment]
Yikes good catch! I would have hoped that https://github.com/apollographql/apollo-android/pull/2917 fixed this one but maybe the SDL conversion is different. Will look into it but that might take a bit of time so replacing like you did looks good 👍

**Comment by martinbonnin** [comment]
I took a loot at this this morning, `""""""""` (8 double quotes) is not a valid [GraphQL String value](https://spec.graphql.org/draft/#StringValue) so the SDL writer was wrong. I could verify it's working ok with `3.x`:

https://github.com/apollographql/apollo-android/blob/9ef26ff8fee08e9773a656fbf17d6edc17a0c47c/apollo-compiler/src/test/kotlin/com/apollographql/apollo3/compiler/SdlWritingTest.kt#L96
