### ISSUE TITLE
Input data class arguments with a default value should be generated as `Input.absent()`

### ISSUE THREAD

**Issue by hiltonc** [apollographql/apollo-android#3194]
**Summary**
Input struct parameters are generated differently on Android vs. iOS. If the meaning is "this is the value the client should provide by default", the Android behavior seems correct. If the meaning of the default value is "this is what the server will assume if you provide no value", the iOS behavior seems correct.

**Version**
2.5.9

**Description**
We have the following (abbreviated) in our `schema.json`:

```
{
  "kind": "INPUT_OBJECT",
  "name": "AuthenticateInput",
  "description": null,
  "fields": null,
  "inputFields": [
    {
      "name": "email",
      ...
    },
    {
      "name": "password",
      ...
    },
    {
      "name": "udid",
      ...
    },
    {
      "name": "rememberMe",
      "description": null,
      "type": {
        "kind": "SCALAR",
        "name": "Boolean",
        "ofType": null
      },
      "defaultValue": "false"
    }
  ],
  "interfaces": null,
  "enumValues": null,
  "possibleTypes": null
}
```

This is the initializer of the `AuthenticateInput` data class on Android. Notice here that the default value for `rememberMe` is `Input.optional(false)`.

```
data class AuthenticateInput(
  val email: String,
  val password: String,
  val udid: String,
  val rememberMe: Input<Boolean> = Input.optional(false)
) : InputType {
```

This is the initializer of the `AuthenticateInput` struct on iOS. Notice that the default value for `rememberMe` is `nil` (even though the schema specifies `false`).

```
public init(email: String, password: String, udid: String, rememberMe: Swift.Optional<Bool?> = nil) {
```

The behavior appears to be inconsistent.

I would prefer the iOS behavior because it causes fewer issues in our setup with staging and production environments when a new parameter is added to an old input with a default value. Either way I'm hoping for consistency.

**Comment by hiltonc** [comment]
Cross-posted at https://github.com/apollographql/apollo-ios/issues/1853

**Comment by martinbonnin** [comment]
> it causes fewer issues in our setup with staging and production environments when a new parameter is added to an old input with a default value

Can you elaborate on that? 

>  Either way I'm hoping for consistency.

I'm leaning iOS too as it allows to change the default value without having to recompile the clients.

**Comment by hiltonc** [comment]
> > it causes fewer issues in our setup with staging and production environments when a new parameter is added to an old input with a default value
> 
> Can you elaborate on that?

@martinbonnin Sure thing.

We generate our client code based on the staging schema so that we can work with new API that haven't been deployed to the production schema yet. We prevent these staging API from being used by the client in production with code that guards access to the feature based on environment.

In this particular case, our `AuthenticateInput` did not have a `rememberMe` field in the production schema, but the field was added to the staging schema. The codegen added the field and default value, and everything worked fine in our staging environment. However, the input failed in production because the server rejected the unknown `rememberMe` input field. This was surprising because the client team was unaware that the new input field had even been added, or that any measures would need to be taken to continue functioning in the production environment.

**Comment by martinbonnin** [comment]
Thanks for the details 👍 ! 

In general, code compiled against schema-v2 isn't guaranteed to work with schema-v1 (I think the term is backward compatibility vs forward compatibility but I always mix those two 🙈 ). But I can see how that's surprising and that's yet another reason to use the iOS logic there.

**Comment by hiltonc** [comment]
Awesome, that makes a lot of sense. We look forward to 3.0 then. Thank you!

**Comment by martinbonnin** [comment]
[3.0.0-alpha01](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-alpha01) is out and uses `Optional.Absent()` for input fields. Let us know how that works!

**Comment by hiltonc** [comment]
@martinbonnin It will take more work to adopt it, but I did enough to test the codegen and, sure enough, the field is generated as `val rememberMe: Optional<Boolean?> = Optional.Absent`. Thank you!!
