### ISSUE TITLE
How to upload multi file in one query for Android

### ISSUE THREAD

**Issue by hoangvuanh761993** [apollographql/apollo-android#3197]
I want to upload multiple image files in Android but can't find any documentation for this problem, can anyone help me? Thank you very much

**Comment by martinbonnin** [comment]
Hi @hoangvuanh761993 ! Thanks for reaching out. The documentation for file upload is available there: https://www.apollographql.com/docs/android/essentials/mutations/#uploading-files

It should certainly be a separate entry in the left column. We'll keep this in mind for the next version of the docs. In the meantime, please let me know if the above doc helps or if you have any additional question.

**Comment by hoangvuanh761993** [comment]
Thank @martinbonnin. Upload 1 file is very simple and I did it.  But I want to upload 4, 5 images at a time, I don't see any documentation or examples for that.

**Comment by martinbonnin** [comment]
Gotcha!

I'd expect multiple upload to work when adding more variables:

```graphql
mutation MultipleUpload($file1: Upload!, $file2: Upload!) {
  multipleUpload(file1: $file1, file2: $file2) {
    id
    path
    filename
    mimetype
  }
}
```

```kotlin
SingleUploadMutation(
  file1 = FileUpload("image/jpeg", File("/my/image1.jpg"))
  file2 = FileUpload("image/jpeg", File("/my/image2.jpg"))
)
```

Or if your API takes a list of uploads:

```graphql
mutation MultipleUpload($files: [Upload!]!) {
  multipleUpload(files: $files) {
    id
    path
    filename
    mimetype
  }
}
```

```kotlin
SingleUploadMutation(
  files = listOf(FileUpload("image/jpeg", File("/my/image1.jpg")),  FileUpload("image/jpeg", File("/my/image2.jpg")))
)
```

Let me know how that goes!

**Comment by martinbonnin** [comment]
Hi @hoangvuanh761993 did it work? Anything else I can help with?

**Comment by hoangvuanh761993** [comment]
Ok let me try, thanks you

**Comment by martinbonnin** [comment]
Looks like your API takes a list of files as input. On Android,`GraphQLFile` is `FileUpload` instead. 
If you have a file, you can call `FileUpload.create("image/png", pngFile)`

If you have a byte array or an inputStream instead of a `File`, you can subclass `FileUpload`:

```

class PngFileUpload(val bytes: ByteArray): FileUpload("image/png") {
  override fun contentLength(): Long {
    return bytes.size.toLong()
  }

  override fun writeTo(sink: BufferedSink) {
    sink.write(bytes)
  }
}
```

**Comment by hoangvuanh761993** [comment]
This is my Graphql File

```
mutation CreateChannelMessageFile($userId: String!, $channelId: String!, $content: String!, $files: Upload!) {
    createChannelMessage(input:{userId: $userId, channelId: $channelId, content: $content, files: $files}){
        id
        success
        errorMessage
    }
}
```
it's auto-generates a java class with a constructor like this:

```
public CreateChannelMessageFileMutation(@NotNull String userId, @NotNull String channelId,
      @NotNull String content, @NotNull FileUpload files) {
    Utils.checkNotNull(userId, "userId == null");
    Utils.checkNotNull(channelId, "channelId == null");
    Utils.checkNotNull(content, "content == null");
    Utils.checkNotNull(files, "files == null");
    variables = new CreateChannelMessageFileMutation.Variables(userId, channelId, content, files);
  }
```
I want to know is there a way to keep the same query as above and still be able to upload multiple files or just change query from backend like:


```
mutation CreateChannelMessageFile($userId: String!, $channelId: String!, $content: String!, $files: [Upload]!) {
    createChannelMessage(input:{userId: $userId, channelId: $channelId, content: $content, files: $files}){
        id
        success
        errorMessage
    }
}
```

**Comment by martinbonnin** [comment]
> I want to know is there a way to keep the same query as above and still be able to upload multiple files

You need to change it. This: `$files: Upload!`, cannot work with a list of `FileUpload`

**Comment by hoangvuanh761993** [comment]
ok thanks

**Comment by martinbonnin** [comment]
> change query from backend like

```
CreateChannelMessageFile(... $files: [Upload]!)
```

This one can take a list of `Upload` as input. It has to be one or the other. Your schema cannot have `input.file` be a `Upload!` and `[Upload]!` at the same time. Given how it's working on iOS, I suspect `[Upload]!` is the right type.

**Comment by martinbonnin** [comment]
@hoangvuanh761993 I'll close this one for now. Feel free to leave a message if you want me to reopen.
