### ISSUE TITLE
How to control the location of an SQL normalized cache

### ISSUE THREAD

**Issue by axel-legue** [apollographql/apollo-android#3200]
**Question.**
Hello,

My application creates several normalized SQL caches, one per authentified user of my app. This makes me sure that it is impossible for one cache to be used by two different users.

I currently use the built-in `SqlNormalizedCacheFactory`, instantiated with one unique `name` parameter per user. This gives me one cache on disk per user.

However, I can not destroy caches and generally perform clean up tasks, because I don’t know where those caches are located on disk. I know I can call the `clearNormalizedCache()` method, but this method may leave remains behind it. Generally I don’t quite control what’s on the disk.

Is it possible to instantiate a `SqlNormalizedCacheFactory` with a path to a file or a directory instead of a name? If not, do you have any advice for controlling the location on disk of my SQL caches?

Thank you

**Comment by martinbonnin** [comment]
Hi 👋  Apollo Android uses the Android Framework SQL APIs so I think the dbs should be reachable at a predictable path with `context.getDatabasePath(name: String)`. 

In general though, I'd expect `clearNormalizedCache()` to delete most of the data besides the DB schema and that should really be tiny. Did you experience something else?

**Comment by axel-legue** [comment]
Hello @martinbonnin ,  thank you for your answer. 

This does not quite allow my app to _discover_ the existing databases on disk that were created by previous runs of the app, or previous versions of the app, so it does not quite fulfill the "control what's on the disk" requirement.

Basically, in order to reliably iterate through existing databases, the app would have to remember all the database names that were used in the past. Talk about a practical solution :sweat_smile:

We'll keep on investigating. And we'll report any finding here, should anyone else ask the same question.

**Comment by martinbonnin** [comment]
You could retrieve the directory and iterate through it. If you expect other databases in the folder, prefix them with `"apollo-"`. This way you can do something like:

```kotlin
context.getDatabasePath("unused").parentFile.listFiles().filter { it.name.startsWith("apollo-") }
```

**Comment by groue** [comment]
> You could retrieve the directory and iterate through it.

I can't read in the [documentation of `getDatabasePath`](https://developer.android.com/reference/android/content/Context#getDatabasePath(java.lang.String)) that all databases share the same folder, so this does not look like a reliable solution.

Nothing prevents `getDatabasePath(someName1)` and `getDatabasePath(someName2)` from returning two paths stored in different directories. The only documented guarantee is that `getDatabasePath("foo")` always returns the same relative path.

**Comment by martinbonnin** [comment]
Agreed it's not documented. There has to be some guarantees though for tools like the [Database Inspector](https://developer.android.com/studio/inspect/database) to list all databases. Might be worth investigating how they're doing it.
