### ISSUE TITLE
[3.x] AppSync WS protocol issue

### ISSUE THREAD

**Issue by chrisvis** [apollographql/apollo-android#3205]
**Summary**
The `AppSyncWsProtocol` seems to not work correctly out-of-the-box.

**Version**
v3.0.0-dev13

**Description**
When trying to connect to AppSync using the `AppSyncWsProtocol` I bumped into a couple of issues:
* The default frame type is `WsFrameType.Binary`, but for me, it only works with `WsFrameType.Text`
* The `payload.data` field needs to be stringified JSON, instead of just JSON
* There seams to not be a way yet to generate the `header` query string parameter (as what was present in: https://github.com/apollographql/apollo-android/blob/dev-3.x/deprecated-apollo-runtime-common/src/jvmMain/kotlin/com/apollographql/apollo3/subscription/AppSync.kt)

To mitigate the second issue I am using a CustomWsProtocol, that serializes the JSON using `kotlinx.serialization`:

```kotlin
class CustomAppSyncWsProtocol(private val authorization: Map<String, Any?>) : WsProtocol by AppSyncWsProtocol(authorization, WsFrameType.Text) {
    override fun <D : Operation.Data> operationStart(request: ApolloRequest<D>): Map<String, Any?> {
        return mapOf(
            "type" to "start",
            "id" to request.requestUuid.toString(),
            "payload" to mapOf(
                "data" to Json.encodeToString(AnySerializer, DefaultHttpRequestComposer.composePayload(request)),
                "extensions" to authorization
            )
        )
    }
}
```

I am using the 3.0.0 version because of my desire to use AppSync in Kotlin Multiplatform, the 2.x version implementation of AppSync seems to be JVM only. As far as I could tell this is the only KMP library with AppSync support :)

I am willing to make a PR for this change, however, I might need some help with figuring out how to best to the JSON serialization neatly without adding an extra dependency

**Comment by martinbonnin** [comment]
Thanks for catching this 🙏 

> The default frame type is WsFrameType.Binary, but for me, it only works with WsFrameType.Text

Most likely an oversight, feel free to change the default value in the constructor.

> The payload.data field needs to be stringified JSON, instead of just JSON

Right, good catch. We have `AnyAdapter` in the codebase that can turn any Map, String, List, Number into their equivalent json representation without depending on kotlinx.serialization. Something like below should do it:

```kotlin
    val jsonString = buildJsonString { 
      AnyAdapter.toJson(this, DefaultHttpRequestComposer.composePayload(request))
    }
```

> There seams to not be a way yet to generate the header query string parameter 

Indeed. Might be worth investigating if `okio` has multiplatform base64 (I think it has). Also multiplatform url parsing was pretty limited last time I looked at this but now there is a very simple [`appendQueryParameter`](https://github.com/apollographql/apollo-android/blob/77b4034e08e0981cabb8aa75310f85e3334a9622/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/http/DefaultHttpRequestComposer.kt#L180) that might be enough for this use case.
