### ISSUE TITLE
Failed to generate apollo resources

### ISSUE THREAD

**Issue by TonnyL** [apollographql/apollo-android#3210]
**Summary**
Value cannot be of non-input type String

**Version**
+ apollo: `3.0.0-dev13-SNAPSHOT`
+ gradle: `gradle-7.1-rc-2`
+ agp: `7.1.0-alpha02`

**Description**
+ schema definition: [GitHub GraphQL API public schema](https://docs.github.com/public/schema.docs.graphql)
+ code that error  message mentioned: 
   ```
   """
  Autogenerated return type of CreateDeployment
  """graphql
    type CreateDeploymentPayload @preview(toggledBy: "flash-preview") {  # ⬅️ this is L5544
    """
    True if the default branch has been auto-merged into the deployment ref.
    """
    autoMerged: Boolean
  
    """
    A unique identifier for the client performing the mutation.
    """
    clientMutationId: String
  
    """
    The new deployment.
    """
    deployment: Deployment
  }
   ```
+ Detailed error information:
   >     Caused by: com.apollographql.apollo3.ast.SourceAwareException: e: /Users/path/app/src/main/graphql/schema.graphql: (5544, 50): Value cannot be of non-input type String
   > [5543]:"""
   > [5544]:type CreateDeploymentPayload @preview(toggledBy: "flash-preview") {
   > [5545]:  """
   >	at com.apollographql.apollo3.ast.IssueKt.checkNoErrors(Issue.kt:54)
   >	at com.apollographql.apollo3.ast.ApiKt.toSchema(api.kt:176)
   >	at 
   > com.apollographql.apollo3.compiler.GraphQLCompiler$IncomingOptions$Companion.fromOptions(GraphQLCompiler.kt:248)
	at com.apollographql.apollo3.gradle.internal.ApolloGenerateSourcesTask.taskAction(ApolloGenerateSourcesTask.kt:177)

**Comment by martinbonnin** [comment]
Thanks for the bug report. This happened because the builtin scalar types were added too late when parsing schema directives. A fix is there: https://github.com/apollographql/apollo-android
