### ISSUE TITLE
response headers not available

### ISSUE THREAD

**Issue by UdiOshi85** [apollographql/apollo-android#3211]
Hello,
I've created a MPF library for shared business logic for my iOS & Android apps.

I'm using the following library:
`implementation("com.apollographql.apollo:apollo-runtime-kotlin:2.5.9")`

I'm able to perform a query correctly, but cannot retrieve the response headers.

Here is how i'm initiating the apollo client:
`apolloClient = ApolloClient(networkTransport, scalarTypeAdapters = scalarTypeAdapters)`

Query execution:
val headers = getHeadersMap()
val executionContext = HttpExecutionContext.Request(headers)
apolloClient.query(query).execute(executionContext).collect{ ... }

I'm getting the data correctly but there's no headers in:
`response.executionContext`

I've seen this Thread about retrieving response headers, but looks like the creation of ApolloClient via builder with ok http is not exist in the kotlin runtime library.

appreciate your help

**Comment by martinbonnin** [comment]
Can you share the code that retrieves the headers? I'd expect something like below to give you appropriate headers:

```
val response = apolloClient.query(query).execute()
val headers = response.executionContext[HttpExecutionContext.Response].headers
```

**Comment by UdiOshi85** [comment]
@martinbonnin 
Tried both:
`response.executionContext[HttpExecutionContext.Response]`
&
`response.executionContext[HttpExecutionContext.Response.Key]`

But received null.

in BE side we provide a header like:
`context?.response?.http?.headers?.set('Has-Errors', '0');`

**Comment by martinbonnin** [comment]
Sorry I missed that we have both `ApolloResponse` and `Response`. Turns out the executionContext contains headers in `ApolloResponse` but not in `Response`. I'll make a fix for this. In the meantime, you can add an interceptor as a workaround:

```kotlin
        val addExecutionContextInterceptor = object : ApolloRequestInterceptor {
            override fun <D : Operation.Data> intercept(
                request: ApolloRequest<D>,
                chain: ApolloInterceptorChain
            ): Flow<ApolloResponse<D>> {
                return chain.proceed(request).map {
                    ApolloResponse(
                        it.requestUuid,
                        it.response.copy(executionContext = it.executionContext),
                        it.executionContext
                    )
                }
            }
        }

        val apolloClient = ApolloClient(
            networkTransport = ApolloHttpNetworkTransport(
                serverUrl = "https://...",
                headers = emptyMap()
            ),
            interceptors = listOf(addExecutionContextInterceptor)
        )
```

**Comment by UdiOshi85** [comment]
@martinbonnin Thanks very much for the help, workaround works as expected.
