### ISSUE TITLE
Use Throwable as ApolloInterceptor.CallBack.onFailure() function argument

### ISSUE THREAD

**Issue by sosite** [apollographql/apollo-android#3224]
**Is your feature request related to a problem? Please describe.**
After introducing `ApolloException` https://github.com/apollographql/apollo-android/issues/367 we lost possibility to use `ApolloInterceptor` as mapper for custom network exceptions. It's because of `ApolloInterceptor.Callback.onFailure()` function attribute which is `ApolloException` afterwards.

Map exceptions to custom one is useful when we have few endpoints (GraphQL, REST, etc.) and we want to unify them across api's.

**Describe the solution you'd like**
The best solution will be update `onFailure()` function attribute to pass general `Throwable` in place of `ApolloException`.

**Workaround**
Right now we must extend `ApolloException` for custom network exceptions even if we use them in REST api.

**Comment by martinbonnin** [comment]
Hi 👋 Thanks for reaching out! Could you wrap your custom Exception in an `ApolloException`? Or you could potentially extend `ApolloException` too?

**Comment by sosite** [comment]
Yes but it's against good oop practice when I need to extend from sth when it could be just raw `Throwable`. It's specially suspicious when Retrofit (REST) throws `ApolloExceptions` under the hood :D

**Comment by martinbonnin** [comment]
> It's specially suspicious when Retrofit (REST) throws ApolloExceptions under the hood :D 

Could you wrap the exception in your interceptor instead? 

```kotlin
class RetrofitApolloException(val cause: Throwable): ApolloException("retrofit error", cause)
```

This way retrofit doesn't know anything about Apollo

**Comment by sosite** [comment]
Yes, I use something like this right now. But it's still code smell ;)

**Comment by martinbonnin** [comment]
Note that you don't even have to subclass, you can also use `ApolloException` directly:

```kotlin
callback.onFailure(ApolloException("retrofit error", retrofitThrowable))
```

Relaxing to `Throwable` instead of `ApolloException` would make error handling more awkward at the callsite.  `ApolloException` has 6 direct subclasses so it's relatively easy to distinguish between a HTTP or a Parsing error or get a list of possible failures. 

If the caller were to just receive a `Throwable`, there might be hundreds or thousands of direct and indirect subclasses. Knowing which one to handle would be way more challenging.

**Comment by sosite** [comment]
Maybe just keep `ApolloExceptions` with all it's subclasses but with javadoc/kdoc which would inform about internally usage of `ApolloException` in place of `Throwable`?

**Comment by martinbonnin** [comment]
We could only wrap in a terminal step just before the error reaches the consumer if that's what you're suggesting?

**Comment by sosite** [comment]
Hmm... My general consideration is how to use application interceptor via `.addApplicationInterceptor(errorInterceptor)` to map `ApolloException` to custom one. Right now I do it in that way:
```kotlin
class ApolloCoroutinesErrorHandlingInterceptor : ApolloInterceptor {

    override fun interceptAsync(
        request: ApolloInterceptor.InterceptorRequest,
        chain: ApolloInterceptorChain,
        dispatcher: Executor,
        callBack: ApolloInterceptor.CallBack
    ) {
        chain.proceedAsync(request, dispatcher, object : ApolloInterceptor.CallBack {
            override fun onFetch(sourceType: ApolloInterceptor.FetchSourceType?) {
                callBack.onFetch(sourceType)
            }

            override fun onResponse(response: ApolloInterceptor.InterceptorResponse) {
                val data = response.parsedResponse.orNull()
                when {
                    data == null || data.hasErrors() -> throw MyCustomException1()
                    else -> callBack.onResponse(response)
                }
            }

            override fun onCompleted() {
                callBack.onCompleted()
            }

            override fun onFailure(e: ApolloException) {
                callBack.onFailure(MyCustomException2(e))
            }
        })
    }

    override fun dispose() {}
}
```
where `MyCustomException*` is:
```
open class MyException(
    message: String? = null,
    localizedMessage: String? = null,
    override val cause: Throwable? = null,
) : ApolloException("") {
    // custom stuff with message and localizedMessage
}

class MyCustomException1() : MyException()
class MyCustomException2(cause: Throwable) : MyException(cause = cause)
```
But as you can see `MyException` needs to extend from `ApolloException("")` in place of simple `RuntimeException()` which it's against Torah, Bible and comics ;)
So I need a way to pass any `Throwable` via `callback.onFailure()` 🤔

**Comment by martinbonnin** [comment]
Thanks for the detailed writeup!

```kotlin
            override fun onFailure(e: ApolloException) {
                callBack.onFailure(MyCustomException2(e))
            }
```

Are you saying that the `e` that you receive here is not an instance of `ApolloException` ? If that's the case, that's a big Yikes! Can you identify where the exception is coming from? Can you share the code that involves Retrofit?

**Comment by sosite** [comment]
`e` is `ApolloException` so everything is ok there :)

My problem is that in `callback.onFailure()` I need to use exception which extends from `ApolloException`. I have defined custom exceptions in `domain` module so right now I need to add `implementation com.apollographql.apollo:apollo-api-jvm:2.5.9` dependency in build.gradle specially for it. Did you see know why it's code smell? :)

---

In Retrofit I use sth simillar to this:
```kotlin
class ResultCall<T>(proxy: Call<T>) : CallDelegate<T, T>(proxy) {

    override fun enqueue(callback: Callback<T>) {
        proxy.enqueue(object : Callback<T> {
            override fun onResponse(call: Call<T>, response: Response<T>) {
                when {
                    response.isSuccessful ->
                        try {
                            callback.onResponse(
                                this@ResultCall,
                                response
                            )
                        } catch (exception: Exception) {
                            callback.onFailure(
                                this@ResultCall,
                                MyCustomException1()
                            )
                        }

                    else -> callback.onFailure(
                        this@ResultCall,
                        MyCustomException1()
                    )
                }
            }

            override fun onFailure(call: Call<T>, throwable: Throwable) {
                callback.onFailure(
                    this@ResultCall,
                    MyCustomException2(throwable)
                )
            }
        })
    }
}
```

**Comment by martinbonnin** [comment]
Are you trying to map the `ApolloExceptions` to `DomainException` from an `ApolloInterceptor`? Right now this is not supported as that would change the public API of `ApolloCall.Callback`. You might want to look in `dev-3.x`. Since Kotlin doesn't have checked Exceptions, it might work there.

Else you'll have to to the mapping on top of `ApolloClient`. If you're using Kotlin, it can be done with extension functions:

```kotlin
fun ApolloCall.awaitAndMapExceptions(): Response<T> {
  return try {
    await()
  } catch(e: ApolloException) {
    throw e.toDomainException()
  }
}
```

**Comment by sosite** [comment]
This was my 1st attempt to handle this :)

Right now I close this issue, we'll se if `dev-3.x` fix it
