### ISSUE TITLE
Websocket closed error missing from graphql-ws subscription

### ISSUE THREAD

**Issue by dchappelle** [apollographql/apollo-android#3230]
**Version**
com.apollographql.apollo3:apollo-runtime-kotlin:3.0.0-dev10

**Description**
The issue can be seen when making a subscription (that includes a security token) to a graphql-ws server. If the token is expired, the server will close the WebSocket with a 4401, backend_error – unauthorized (i.e. no cookie or other authentication data). This error is not seen by the apollo-android client though. The only error seen is "ACK not received after x amount of time". The same "ACK..." message is received on each retry. The client needs to know about the websocket being closed in order to stop retries and notify the user.

**Comment by martinbonnin** [comment]
Closed with #3230 now available in `3.0.0-alpha03`
