### ISSUE TITLE
How to generate Java classes for queries/mutations, to be used during Apollo Client operations

### ISSUE THREAD

**Issue by coolprashi06** [apollographql/apollo-android#3234]
We’ve been trying to perform query/mutation operations from one of our Java Maven based client using Apollo Client library which I believe is possible by adding following maven dependency:

<dependency>
   <groupId>com.apollographql.apollo</groupId>
   <artifactId>apollo-runtime</artifactId>
   <version>3.0.0-alpha01</version>
</dependency>

Problem here is this library requires Java specific classes for queries & mutations to be executed upon.
And for the code generation, https://www.apollographql.com/docs/android/essentials/get-started-java/ says all about Gradle Plugin and our Java client is Maven based. I tried using the gradle plugin in one Java gradle based project too but didn’t work as it was looking for Kotlin extension.

After doing some google, I got different maven plugins (not from Apollo) which people have reported to be useful for generation of Java classes. But they doesn’t seem to work well with unions & exclamatory identifier:

 <groupId>com.github.aoudiamoncef</groupId>
				<artifactId>apollo-client-maven-plugin</artifactId>
				<version>4.0.4</version>

 
<groupId>com.github.sparow199</groupId>
				<artifactId>apollo-client-maven-plugin</artifactId>
				<version>3.3.1</version>
 

Can you please help us on generation of Java code using Apollo’s Library for queries/mutations.

**Comment by martinbonnin** [comment]
Hi 👋 . As far as I know, https://github.com/aoudiamoncef/apollo-client-maven-plugin only works with apollo `2.x`

`3.x` doesn't support Java codegen yet (although it is [planned](https://github.com/apollographql/apollo-android/issues/2616))

**Comment by coolprashi06** [comment]
> Hi 👋 . As far as I know, https://github.com/aoudiamoncef/apollo-client-maven-plugin only works with apollo `2.x`.
> 
> `3.x` doesn't support Java codegen yet (although it is [planned](https://github.com/apollographql/apollo-android/issues/2616)).
> 
> Can you try with `com.github.aoudiamoncef:apollo-client-maven-plugin:4.0.4` and `com.apollographql.apollo:apollo-runtime:2.5.9`?

Hi @martinbonnin I used the same configuration in my maven project but still the same issue. Below is my plugin config:

<plugin>
				<groupId>com.github.aoudiamoncef</groupId>
				<artifactId>apollo-client-maven-plugin</artifactId>
				<version>4.0.4</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<skip>false</skip>
							<services>
								
								<lahzouz-complete-api>
									<enabled>true</enabled>
									<addSourceRoot>true</addSourceRoot>
									<sourceFolder>${project.basedir}/src/main/graphql</sourceFolder>
									<schemaPath>${project.basedir}/src/main/graphql/schema.json</schemaPath>
									<includes>
										<include>**/*.graphql</include>
										<include>**/*.gql</include>
										<include>**/*.json</include>
										<include>**/*.sdl"</include>
									</includes>

									<compilationUnit>
										<name>lahzouz</name>
										<outputDirectory>${project.build.directory}/generated-sources/graphql-client/</outputDirectory>
										<generateOperationDescriptors>false</generateOperationDescriptors>
										<operationOutputFile>${project.build.directory}/generated/operationOutput/apollo/operationOutput.json</operationOutputFile>
										<compilerParams>
											<rootFolders>
												<rootFolder>${project.basedir}/src/main/graphql/</rootFolder>
											</rootFolders>
											<generateKotlinModels>false</generateKotlinModels>
											<warnOnDeprecatedUsages>true</warnOnDeprecatedUsages>
											<failOnWarnings>false</failOnWarnings>
											<generateOperationOutput>true</generateOperationOutput>
											<operationIdGeneratorClass>
												com.apollographql.apollo.compiler.OperationIdGenerator$Sha256
											</operationIdGeneratorClass>
											<suppressRawTypesWarning>false</suppressRawTypesWarning>
											<useSemanticNaming>true</useSemanticNaming>
											<nullableValueType>ANNOTATED</nullableValueType>
											<generateModelBuilder>false</generateModelBuilder>
											<useJavaBeansSemanticNaming>false</useJavaBeansSemanticNaming>
											<generateVisitorForPolymorphicDatatypes>false</generateVisitorForPolymorphicDatatypes>
											<rootPackageName>com.lahzouz.graphql.client.lahzouz</rootPackageName>
											<generateAsInternal>false</generateAsInternal>
											<generateApolloMetadata>false</generateApolloMetadata>
											<metadataOutputFile>${project.build.directory}/generated/metadata/apollo/lahzouz/metadata.json</metadataOutputFile>
											<kotlinMultiPlatformProject>false</kotlinMultiPlatformProject>
										</compilerParams>
									</compilationUnit>

									<introspection>
										<enabled>true</enabled>
										<endpointUrl>MY GRAPHQL URL</endpointUrl>
										<schemaFile>${project.basedir}/src/main/graphql/schema.json</schemaFile>
										<connectTimeoutSeconds>10</connectTimeoutSeconds>
										<readTimeoutSeconds>10</readTimeoutSeconds>
										<writeTimeoutSeconds>10</writeTimeoutSeconds>
										<useSelfSignedCertificat>false</useSelfSignedCertificat>
										<useGzip>false</useGzip>
										<prettyPrint>true</prettyPrint>
									</introspection>
								</lahzouz-complete-api>

								
								<lahzouz-min-api>
									<compilationUnit>
										<name>lahzouz</name>
									</compilationUnit>
								</lahzouz-min-api>

							</services>
						</configuration>
					</execution>
				</executions>
			</plugin>

and I had created 2 .graphql files for the queries and placed schema.graphql file inside src/main/graphql directory.
schema.json is auto created when i run "mvn clean install" in the same directory i.e. src/main/graphql 

My schema.graphql uses unions and which is where this plugin complains of unsupported token "="

**Comment by martinbonnin** [comment]
> where this plugin complains of unsupported token "="

Can you share the complete error when this happens?

**Comment by coolprashi06** [comment]
[INFO] --- apollo-client-maven-plugin:4.0.4:generate (default) @ common-orchestration-worker ---
[INFO] Apollo GraphQL Client code generation task started
[INFO] Generating service: lahzouz-complete-api
[INFO] Automatically generating introspection file from: **MY GRAPHQL URL**
[INFO] Read schema file
[INFO] Read querie(s)/fragment(s) files
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.861 s
[INFO] Finished at: 2021-07-13T20:55:34+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.aoudiamoncef:apollo-client-maven-plugin:4.0.4:generate (default) on project common-orchestration-worker: Execu
tion default of goal com.github.aoudiamoncef:apollo-client-maven-plugin:4.0.4:generate failed: 
[ERROR] Failed to parse GraphQL file C:\git_wrkspc\common-orchestration-worker\src\main\graphql\schema.graphql (41:20)
[ERROR] Unsupported token `=`
[ERROR] ----------------------------------------------------
[ERROR] [40]:
[ERROR] [41]:union BooleanResult = BooleanValidation | Failure
[ERROR] [42]:
[ERROR] ----------------------------------------------------

**Comment by martinbonnin** [comment]
Thanks a lot for sending this 🙏 .

Can you rename your `schema.graphql` file to `schema.sdl`? By default, Apollo Android parses `*.graphql` files as operations, not schemas.

**Comment by coolprashi06** [comment]
Now I am getting different error. See this 
![image](https://user-images.githubusercontent.com/11220273/125481367-1fd7027a-f246-484e-9243-e3353c0faf07.png)

**Comment by martinbonnin** [comment]
> No querie(s)/fragment(s) found.

Can you share the contents of `GetUser.graphql` and `GetCompanies` ? Do they contain operations? 

Besides that, the layout of the .graphql files looks good to me but maybe `apollo-client-maven-plugin` is configuring the apollo compiler differently. You might also want to open an issue on https://github.com/aoudiamoncef/apollo-client-maven-plugin.

**Comment by coolprashi06** [comment]
> > No querie(s)/fragment(s) found.
> 
> Can you share the contents of `GetUser.graphql` and `GetCompanies` ? Do they contain operations?
> 
> Besides that, the layout of the .graphql files looks good to me but maybe `apollo-client-maven-plugin` is configuring the apollo compiler differently. You might also want to open an issue on https://github.com/aoudiamoncef/apollo-client-maven-plugin.

Thanks @martinbonnin  I managed to make it work. Thanks for your help!
