### ISSUE TITLE
Unable to resolve apollo client related classes

### ISSUE THREAD

**Issue by coolprashi06** [apollographql/apollo-android#3236]
I am working on Maven based Java project, wanting to use ApolloClient to perform query/mutation on Apollo based graphql server.

Added below dependencies to my pom.xml

`

             <dependency>
			<groupId>com.apollographql.apollo</groupId>
			<artifactId>apollo-runtime</artifactId>
			<version>2.5.9</version>
		</dependency>

		<dependency>
			<groupId>org.jetbrains</groupId>
			<artifactId>annotations</artifactId>
			<version>21.0.1</version>
		</dependency>

`

I able to generate query/mutation specific Java classes using following plugin:

    <plugin><groupId>com.github.aoudiamoncef</groupId><artifactId>apollo-client-maven-plugin</artifactId><version>4.0.4</version> </plugin>

However when I write the code for Apollo Client, I see some unresolvable classes. See attached image. Pls suggest.

![image](https://user-images.githubusercontent.com/11220273/125568676-5caab51d-08b9-4772-8cdc-6389ccb93e17.png)

**Comment by martinbonnin** [comment]
Can you upload a small reproducer project and also your version of IntelliJ ? That might very well be an IDE issue.

**Comment by coolprashi06** [comment]
> Can you upload a small reproducer project and also your version of IntelliJ ? That might very well be an IDE issue.

[apollo-client-example.zip](https://github.com/apollographql/apollo-android/files/6815838/apollo-client-example.zip)

**Comment by coolprashi06** [comment]
I am using IntelliJ IDEA 2020.1.3 (Community Edition)
Build #IC-201.8538.31, built on July 7, 2020

**Comment by martinbonnin** [comment]
Thanks for providing this. Can you try a more recent version of intelliJ ? Things are working well for me with:


IntelliJ IDEA 2021.2 Beta (Community Edition)
Build #IC-212.4638.7, built on July 6, 2021
Runtime version: 11.0.11+9-b1504.8 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8

Kotlin: 212-1.5.10-release-IJ4638.7

**Comment by coolprashi06** [comment]
> Thanks for providing this. Can you try a more recent version of intelliJ ? Things are working well for me with:
> 
> IntelliJ IDEA 2021.2 Beta (Community Edition)
> Build #IC-212.4638.7, built on July 6, 2021
> Runtime version: 11.0.11+9-b1504.8 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 10.15.6
> GC: G1 Young Generation, G1 Old Generation
> Memory: 4096M
> Cores: 8
> 
> Kotlin: 212-1.5.10-release-IJ4638.7

yes the latest version of IntelliJ Idea IDE worked. thanks for the support! :)
