### ISSUE TITLE
Add CacheHeaders

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#326]
We need a way to pass metadata for the cache. Examples might be `TTL` or `offlineCritical`.
This header info will be passed to `CacheStore` for read and writes. As `CacheStore` is user configurable, I feel we should make this CacheHeader a key-value String map. This allows a user to add custom CacheHeaders that make sense for their individual implementation of CacheStore.

Couple options on how to implement for the API:

```
public final class CacheControl {
     public CacheControl(CacheFetchPolicy) ...
     public CacheControl(CacheFetchPolicy, Map<String, String> cacheHeaders)
}

public enum CacheFetchPolicy {
  CACHE_FIRST,
  CACHE_ONLY,
  NETWORK_FIRST,
  NETWORK_ONLY,
}
```

or in `ApolloCall` just: 
```
  @Nonnull ApolloCall<T> cacheControl(@Nonnull CacheControl cacheControl);
 @Nonnull ApolloCall<T> cacheControl(@Nonnull CacheControl cacheControl, @Nullable Map<String, String> cacheHeaders);

```

**Comment by sav007** [comment]
But if we talking about `TTL` that completely on the impl of cache store, when writing response to cache impl of normalized cache store should add this to the record

**Comment by sav007** [comment]
As for `offlineCritical ` I'm not sure that we need this option, you can get this functionality by setting `TTL` to some large value, and cache store will keep records for a long time

**Comment by BenSchwab** [comment]
But don't we want different `TTL` for different requests? Some request (say a message thread) should never be evicted (or at least, have a very low eviction priority). Whereas a temporary search results should be evicted quickly.

**Comment by sav007** [comment]
> But don't we want different TTL for different requests

Should it be defined by request or by record? CacheStore implementation when merge records can attach different TTL for different records. The only that we are missing the type of the record.

> Some request (say a message thread) should never be evicted

What if the message referenced to user, this TTL for messages will be used as TTL for user as well?

**Comment by BenSchwab** [comment]
The message/user case you brought up is the perfect example as to why it needs to be on the request:

If a `message` request stores a `user`, and the `message` is marked as "never expire", we expect that anytime I run that request, it will return -- including the `user`.

However, a different request, this time just for a `user`  may be marked as "ttl 1 minute". Although this request accesses the same record in the normalized cache, the cache should actually return `null` if the record hasn't been updated in more than 1 minute.

The general sentiment I trying to drive at is that TTL to record is many to one, whereas TTL to request is 1:1.
 
There are many variations of how to approach this (we plan to only use offline-critical, and no TTL) -- but fundamentally it seems to me that this metadata belongs to the request -- not the record.

**Comment by sav007** [comment]
Ok if we just pass the `Operation` from `RealApolloCall` to `com.apollographql.android.cache.normalized.RealCache#write` -> `com.apollographql.android.cache.normalized.CacheStore#merge` will it be enough info for user cache store implementation to have TTL per request?

**Comment by sav007** [comment]
The only concern/question now from design perspective `CacheStore` knows about `Operation`, should it?

**Comment by BenSchwab** [comment]
I feel like passing the whole `Operation` is too much information (though it is an option). It would also require hand-coding the TTL requirement for every different operation type on the cache (or, again, attaching some metadata to the operation itself).

On the flipside -- we already have the concept of `CacheControl`, which could easily be passed to the cache. It seems pretty harmless to add a generic (and completely optional) cache control header map to this object.

What do other's think? @digitalbuddha @brianPlummer @marwanad 

cc @martijnwalraven - don't think iOS has this yet, but would appreciate your input. (Also fyi roughly `CacheStore` = ios`NormalizedCache`, `Cache` = ios`Store`. Though, I think there is some value on standardizing names soon.)
