### ISSUE TITLE
v3.0.0: Gradle sync - Could not set unknown property 'customTypeMapping' for extension 'apollo'

### ISSUE THREAD

**Issue by omaksymov** [apollographql/apollo-android#3265]
**Summary**
Gradle sync fails with
> Could not set unknown property 'customTypeMapping' for extension 'apollo' of type com.apollographql.apollo3.gradle.internal.DefaultApolloExtension

when using apollo gradle plugin v3.0.0-alpha02 (or 01)

**Version**
3.0.0-alpha02

**Description**
Trying to migrate from Apollo 2.5.9 to 3.0.0 (alpha02) using instructions at https://www.apollographql.com/docs/android/v3/migration/3.0/#gradle-configuration and can't even try that, because Gradle sync is failing with error message from summary.

build.gradle:
```
ext {
        kotlinVersion = '1.5.20'
        apolloVersion = '3.0.0-alpha02'
}
    
dependencies {
 classpath 'com.android.tools.build:gradle:4.2.2'
 classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
 classpath "com.apollographql.apollo3:apollo-gradle-plugin:$apolloVersion"
}    
```

app/build.gradle:
```
apply plugin: 'com.apollographql.apollo3'
...
apollo {
    packageName.set("...")
    customTypeMapping = [
            "IsoDateTime" : "java.util.Date",
...
            "JSON" : "full.path.to.ApolloJsonScalar"
    ]
}
```

According to https://www.apollographql.com/docs/android/essentials/plugin-configuration/ `customTypeMapping` should be still there. I didn't find any mentions of changes in this area in [release notes](https://github.com/apollographql/apollo-android/releases) as well.

What may be the problem?

**Comment by martinbonnin** [comment]
Indeed, I'd expect that to work. Let me check quickly.

**Comment by martinbonnin** [comment]
My bad, it's been renamed to `customScalarsMapping`:

```groovy
apollo {
    packageName.set("...")
    customScalarsMapping = [
            "IsoDateTime" : "java.util.Date",
...
            "JSON" : "full.path.to.ApolloJsonScalar"
    ]
}
```

I'll add that to the migration guide. 

Thanks for catching this!

**Comment by omaksymov** [comment]
Yes, changing to `customScalarsMapping` worked. Thanks 👍
