### ISSUE TITLE
Cache read locking needs to be done at the request level, not cache level

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#327]
We read a request from the cache in multiple calls - we need to lock for the entire request read, and not on each record read, because another request could acquire the write lock in between reads.

For symmetry, we should move write locker up a level too -- even though writing is only called once for a request.

**Comment by sav007** [comment]
>because another request could acquire the write lock in between reads 

Why this is an issue?

**Comment by sav007** [comment]
> For symmetry, we should move write locker up a level too -- even though writing is only called once for a request.

Isn't it what we have right now: https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/android/cache/normalized/RealCache.java#L44

**Comment by BenSchwab** [comment]
We call read inside the field resolver:

```
private Record valueFor(Record record, Field.ObjectField field) {
    CacheReference cacheReference = fieldValue(record, field);
    return cacheReference != null ? cache.read(cacheReference.key()) : null;
  }
```

This measn read is called many times for one request -- this means we unlock/ lock many times for one request.

Thus, a write could interleave during the request read. This means that for one request half of it's response might be read from the cache before a write changed a bunch of values, and half after the write changed a bunch of values.

**Comment by sav007** [comment]
Oh, wow... you are right, I thought we lock on request level
