### ISSUE TITLE
3.x Java-friendly APIs 

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#3281]
Once we have https://github.com/apollographql/apollo-android/issues/2616, make sure the `apollo-api` artifact and extension functions are easily callable from Java code.

# Default Arguments

The kotlin code makes heavy usage of default arguments:

```kotlin
class ApolloClient @JvmOverloads constructor(
    val networkTransport: NetworkTransport,
    private val customScalarAdapters: CustomScalarAdapters = CustomScalarAdapters.Empty,
    private val subscriptionNetworkTransport: NetworkTransport = networkTransport,
    private val interceptors: List<ApolloInterceptor> = emptyList(),
    override val executionContext: ExecutionContext = ExecutionContext.Empty,
    private val requestedDispatcher: CoroutineDispatcher? = null,
    private val flowDecorators: List<FlowDecorator> = emptyList(),
)
```

Multiple solutions:

1. `@JvmOverloads`
2. `with-ers` and copy
3. Builders

# Extension functions

To better separate concerns, `apollo-runtime` now knows nothing about `normalized-cache`. Using extension functions, this is now relatively transparent in Kotlin:

```koltin
val apolloClient = ApolloClient("https://...").withNormalizedCache(
  normalizedCache = normalizedCacheFactory,
  writeToCacheAsynchronously = true
)
```

This doesn't work in Java anymore so the equivalent code will be:

```java
ApolloClient apolloClient = ApolloClient("https://...")
                                         .withInterceptor(ApolloCacheInterceptor(ApolloStore(normalizedCacheFactory)))
                                         .withExecutionContext(WriteToCacheAsynchronouslyContext(true))
```

An alternative could be to reuse the extension function:

```java
ApolloClient apolloClient = ApolloClient("https://...")
apolloClient = NormalizedCache.configure(apolloClient, normalizedCache, true)
```

Or using builders:

```java
ApolloClient.Builder builder = ApolloClient.builder().serverUrl("...")
NormalizedCache.configure(builder, normalizedCache, true)
ApolloClient apolloClient = builder.build()
```

# Hiding Kotlin parts

Extension functions only visible to Kotlin can be put in file names starting with `-`

**Comment by Siedlerchr** [comment]
#3152 might be relevant here as well, providing proper module information and avoiding split packages

**Comment by hwillson** [comment]
The initially scoped work here has been completed so we'll close this off. Thanks!
