### ISSUE TITLE
"Cannot find symbol" error on queries and mutations with variables in task :app:kaptDebugKotlin

### ISSUE THREAD

**Issue by dizzersee** [apollographql/apollo-android#3292]
**Summary**
All of the sudden I get compile errors like these for my mutations and queries which receive arguments:

```
> Task :app:kaptDebugKotlin FAILED

^app/build/tmp/kapt3/stubs/debug/adapter/NewAnswerMutation_VariablesAdapter.java:6: error: cannot find symbol
public final class NewAnswerMutation_VariablesAdapter implements com.apollographql.apollo3.api.Adapter<NewAnswerMutation> {

```

**Version**

`'com.apollographql.apollo3' version '3.0.0-alpha02'`

**Description**

E.g. one mutation which produces the error looks like this: 
`NewAnswer.graphql`
```
mutation NewAnswer ($input: AnswerInput!) {
    create_answer(input:$input) {
        id
        answer_text
        study_id
        participant_id
        created_at
        updated_at
    }
}
```

Do you have any idea why this might happen?

**Comment by martinbonnin** [comment]
Hi 👋 

I've definitely seen some stale files issues with kapt in the past. Can you try removing all your `build` folder and re-running the build? 
If that doesn't work, is there more context to this error? What is the missing symbol?

**Comment by dizzersee** [comment]
@martinbonnin Thank you for your fast response. 

Unfortunately, removing `build` folder and rerunning the build did not produce a different result. 

The missing symbols are the Mutation and the Query classes, for example with `NewAnswerMutation`, and they are missing in the `*_VariablesAdapter` java files:

```
              ^/app/build/tmp/kapt3/stubs/debug/adapter/NewAnswerMutation_VariablesAdapter.java:6: error: cannot find symbol
public final class NewAnswerMutation_VariablesAdapter implements com.apollographql.apollo3.api.Adapter<NewAnswerMutation> {
                                                                                                       ^
  symbol: class NewAnswerMutation /app/build/tmp/kapt3/stubs/debug/adapter/NewAnswerMutation_VariablesAdapter.java:12: error: cannot find symbol
    public NewAnswerMutation fromJson(@org.jetbrains.annotations.NotNull()
           ^
```

**Comment by dizzersee** [comment]
Oh, a short update: I got the build to succeed like this:

1. Remove the `*.graphql` files of my mutations and queries which produced those errors
2. Remove build folder
3. Rerun the build
4. Re-add those `*.graphql` files I removed in step 1
5. Rerun the build

**Comment by martinbonnin** [comment]
Wait, What? That is surprising... Once you have it to work, does it start failing again if you do something specific like maybe update a graphql file?

**Comment by dizzersee** [comment]
@martinbonnin Yeah, stopped working again. 

Since the last working build I've made some simple changes so `themes.xml` file of the app and changed the theme the app is using. So nothing related to GraphQL. Now I get the same error with missing symbol again.

**Comment by martinbonnin** [comment]
Any change you can upload a small reproducer somewhere? Do you have a stub fro `NewAnswerMutation.java` somewhere in `/app/build/tmp/kapt3/stubs/debug/adapter/` ?

**Comment by dizzersee** [comment]
@martinbonnin 
Here is an application commit where the build problem occurs (unless I use the "workaround" I told you about): 

https://github.com/dizzersee/niresto/tree/07b9bd06e31df061b4471b421307491d66bd2ada

And yeah, `NewAnswerMutation.java` and the java files for other queries and mutations also exist there: [NewAnswerMutation.java](https://gist.github.com/dizzersee/798e79f7c971d68d3f42030878372f9f)

**Comment by martinbonnin** [comment]
Thanks for providing this 🤗! 

It looks like kapt doesn't like root classes. Specify a packageName for your classes:

```kotlin
apollo {
    packageName.set("com.niresto")
    generateKotlinModels.set(true)
}
```

Then delete `build` one more time to remove stale stubs and it should work again.

**Comment by dizzersee** [comment]
@martinbonnin Thanks a lot! :+1: Seems to work now. I'll close this issue for now then.
