### ISSUE TITLE
[RFC] `with-ers` vs `Builders` vs `DSL-like` APIs

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#3301]
The main entry points to Apollo Android are [ApolloClient](https://apollographql.github.io/apollo-android/kdoc/apollo-runtime/com.apollographql.apollo3/-apollo-client.html) and [ApolloRequest](https://apollographql.github.io/apollo-android/kdoc/apollo-api/com.apollographql.apollo3.api/-apollo-request/index.html) and support multiple configuration options. 

The goal of this issue is to investigate different Builder-like APIs and gather community feedback about which one feels the more natural. 

## 1.`with-ers`

This is the current solution. An instance is created first and then copied with additional parameters using `withFoo()` methods:

```kotlin
val apolloRequest = ApolloRequest(query)
                                  .withFetchPolicy(FetchPolicy.CacheFirst)

val apolloClient = ApolloClient("https://example.com/graphql")
                                  .withNormalizedCache(MemoryCache())
                                  .withAutoPersistedQueries()
```

**pros**: 
- simple to implement. 
- immutable

**cons**:
- some (to be measured) performance penalty due to the additional copy
- forgetting to use the return type of a `withFoo()` is an error that is not caught by the compiler. It might be mitigated with an `@CheckReturnValue` annotation (TBC)
- not very widespread? (TBC)

## 2. `Builders`

This is the same as Apollo Android 2.x and uses Java-style builders:

```kotlin
val apolloRequest = ApolloRequest.builder(query)
                                  .fetchPolicy(FetchPolicy.CacheFirst)
                                  .build()
                                  
val apolloClient = ApolloClient.builder("https://example.com/graphql")
                                  .normalizedCache(MemoryCache())
                                  .autoPersistedQueries()
                                  .build()
```

**pros**: 
- this pattern has been used for decades so most likely won't be surprising
- doesn't copy classes
- forgetting to use the return value is not possible by construction

**cons**:
- some more boilerplate to implement as there is now a second mutable `Builder` class with mostly the same properties as the original one.
- slightly more verbose, requires a final `build()` call

## 3. `DSL-like`

This is a solution used by [Ktor](https://ktor.io/docs/client.html#configure-client), Anko and other Kotlin DSL-like APIs. The Kotlin doc has a page for them called [Type-safe builders](https://kotlinlang.org/docs/type-safe-builders.html)

```kotlin
val apolloRequest = ApolloRequest(query) {
                                    fetchPolicy = FetchPolicy.CacheFirst
                                  }
                                  
val apolloClient = ApolloClient("https://example.com/graphql") {
                                    normalizedCache {
                                      cache = MemoryCache()
                                      objectIdGenerator = IdObjectIdGenerator
                                    }
                                    autoPersistedQueries = true
                                  }
```

**pros**: 
- relatively concise
- doesn't copy classes
- forgetting to use the return value is not possible by construction

**cons**:
- some more boilerplate to implement as there is now a second mutable `Builder` class with mostly the same properties as the original one.
- slightly more verbose, requires a {} block
- best practices about this convention do not seem as established as the Builder ones? For example, HTML uses lowercase `html` while Ktor uses CamelCase `HttpClient`
- Not Java Friendly

## Bonus: ApolloRequest vs ApolloCall

Related to the above discussion and independently on the chosen solution (assumed as `.configure()` below for clarity), there's a question whether we should configure on an `ApolloRequest` or an `ApolloCall`.

ApolloRequest is OkHttp like:

```kotlin
val apolloRequest = ApolloRequest(query).configure()

val response = apolloClient.query(apolloRequest)
```

ApolloCall would allow to easily chain calls:

```kotlin
val response = apolloClient.query(query)
                         .configure()
                         .execute()
```

## Resources/Links

* Builders vs DSLs in Coil: https://colinwhite.medium.com/prefer-builders-over-dsls-3dc7fc375d47
* Why `@JvmOverloads` is not a silver bullet for Java compatibility and doesn't allow any arbitrary combination of arguments: https://dzone.com/articles/java-friendly-kotlin-default-arguments
* https://kt.academy/article/ek-constructor
* https://twitter.com/iateyourmic/status/1446503107169509376

## Conclusion 

My early thoughts would be to go with `Builders` because it's a battle tested solution and forces using the return value by construction. But I'd like to avoid changing that too much so will leave this ticket open for some time  before comitting to `Builders` to make sure we're not forgetting anything.

Any thoughts? Preferences? Other solutions? Leave a comment below!

**Comment by audkar** [comment]
For me, DSL looks most natural. (probably biggest cons is for library devs who need to implement it). 

2nd place is for the good old `Builder` pattern. But I don't have a very strong preference between them. Both are good.

However `with-ers` I don't like at all. When using such API I don't know if that mutates the original instance or deep clones it. Is it safe to reuse or not.

**Comment by jfspencerAngel** [comment]
I have a strong preference for the builder pattern, its immediately recognizable, it has fluid discovery, and seems to be a pattern for the ages :) 

 I really don't like the idea of errors passing through the compiler if they can be avoided (huge point against `with-er` api)

I do like the `DSL-like` API, but it is not as easily discoverable as `Builder`

I have a strong preference for the `ApolloCall` style it is more consistent with other fluent apis in Kotlin like Collection chaining (.map.flatmap.fold etc)
