### ISSUE TITLE
Unresolved reference caused by generated files

### ISSUE THREAD

**Issue by jorgenfaunaapp** [apollographql/apollo-android#3306]
Hello guys, I have had a massive headache figuring out how to fix a very annoying 'Unresolved reference' compilation error in my android project. 
Luckily I have finally figured it out and I was wondering if this is expected behaviour, and if not, where I can report it as an issue? I have tried to explain what leads to the 'Unresolved reference' compilation error below and how to reproduce.

_Dagger repo_
Before figuring 'it out' i opened a issue on the dagger repo, where you can see some screenshots as well if needed https://github.com/google/dagger/issues/2799

_The Issue_
In the first compilation (or if a line is changed in all files within the user package), the project would compile successfully. But concurrent builds (without cleaning or changes to all files within the package with same naming as the subfolder in the schema folder) would lead to Unresolved reference errors in my generated files.

It is very hard to debug this issue. I am not sure which library/tool is to blame really, and it is very confusing that Android Studio manages to resolve the paths correctly in some of the compilations.

_What leads to the issue_
I have had several packages in my android project where the name of the package mirror my naming of subfolders in my apollo folders. With the only difference being a different capitalization. The graphql files revolving around the User type are located in a User folder within my schema folder. and my app has a package named user, with a UserViewModel, UserRepository and so on in it as I tried to illustrate below. 

Location for User query
`com.example.myapplication.User.MeQuery`

Android package with viewmodel
`com.example.myapplication.user.UserViewModel`

When compiling my project, a folder with my Android code is created and a folder with my apollo types is created
Android code
`com.example.myapplication.user.UserDataSource_Factory`
Apollo code
`com.example.myapplication.User.MeQuery`

_Steps to reproduce_
MainActivity
```
import com.example.myapplication.user.UserViewModel

class MainActivity : AppCompatActivity() {

    private val userViewModel: UserViewModel by viewModels()

}
```
Location for UserViewModel:
MyApplication/app/src/main/java/com/example/myapplication/user

UserViewModel

```
package com.example.myapplication.user

import androidx.lifecycle.ViewModel
import dagger.hilt.android.lifecycle.HiltViewModel
import javax.inject.Inject

@HiltViewModel
class UserViewModel @Inject constructor(
    private val userRepository: UserRepository
) : ViewModel() {

}
```

Dependency injection of UserViewModel

```
package com.example.myapplication.di

import com.example.myapplication.user.UserRepository
import com.example.myapplication.user.UserViewModel
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent

@Module
@InstallIn(SingletonComponent::class)
class ViewModelModule {

    @Provides
    fun providesUserViewModel(userRepository: UserRepository) : UserViewModel = UserViewModel(userRepository)
}
```

Schema type
```
  type User {
    id: ID!
    username: String!
  }
```

Schema query
```
type Query {
    me: User
}
```
Mutation location
MyApplication/app/src/main/graphql/com/example/myapplication/User/MeQuery.graphql

Android project with the compilation error shown.
As seen in the generated folders there are two paths, leading to the 'Unresolved reference: UserViewModel'
<img width="1978" alt="Screenshot 2021-08-17 at 16 06 39" src="https://user-images.githubusercontent.com/69505339/129740890-252897c7-c289-4644-a2d6-b71d74807e80.png">

**Comment by martinbonnin** [comment]
Thanks for the detailed description! It might be a stretch but is there any chance you can provide a reproducer? It's going to be super hard to dive into this without one.
All in all and in the short term, I'd recommend using lower case directories and package names as it's what most tools are expecting. I also remember some issues about MacOS filesystems being case insensitive which might bring all kinds off problems with up-to-date checks, incremental compilations and more. I think using lowercase everywhere should fix most of these.

**Comment by jorgenfaunaapp** [comment]
Hi @martinbonnin thanks for the response. I have attached a zip folder of an example project where the error occurs. Yeah it might be related to the MacOS filesystem I suppose, naming the folder with lower case also solves the issue.

[MyApplication.zip](https://github.com/apollographql/apollo-android/files/7031110/MyApplication.zip)

**Comment by martinbonnin** [comment]
Thank you so much for the reproducer ! That helps a ton. 

I could reproduce without Apollo or Dagger. This seems to related to Kotlin incremental compilation, I opened a follow up issue there: https://youtrack.jetbrains.com/issue/KT-48797.

As a workaround, you can rename the folder where your GraphQL files are to be lower case or use a different package name for the generated models. I'm going to close this issue for now. Let me know if there's something else I can do.
