### ISSUE TITLE
JSON nesting is limited to 32 levels

### ISSUE THREAD

**Issue by andrewmunn** [apollographql/apollo-android#3308]
**Summary**
Our GraphQL query response JSON is now failing to parse due to exceeding 32 layers of nesting: 

`com.apollographql.apollo.api.internal.json.JsonDataException: Nesting too deep at [path]
`
**Version**
2.5.9
**Description**
Our API is quite complex and has now exceeded the recursion depth. The limit is hardcoded to 32 levels, however Moshi moved to 255 layers in May 2018.

[Here's the line of code in apollo-android]( https://github.com/apollographql/apollo-android/blob/f72c3afd17655591aca90a6a118dbb7be9c50920/apollo-api/src/commonMain/kotlin/com/apollographql/apollo/api/internal/json/BufferedSourceJsonReader.kt#L51). Can the limit in Apollo-Android also be increased to 255?

**Comment by martinbonnin** [comment]
Hi 👋 . That sounds very reasonable to me. Want to do a pull request?

**Comment by martinbonnin** [comment]
I went ahead and made a PR [there](https://github.com/apollographql/apollo-android/pull/3334). It'll be in both next 2.x and 3.x versions.
