### ISSUE TITLE
SubscriptionManager state is automatically changed from Stopped to Disconnected after small delay 

### ISSUE THREAD

**Issue by vkornii** [apollographql/apollo-android#3310]
**Summary**
inactivityTimeoutTimerTask changes SubscriptionManager's state to DISCONNECTED after SubscriptionManager#stop() is called 

**Version**
2.5.9

**Description**
I'm using apollo subscriptions with coroutine extensions. After SubscriptionManager#stop is called, state is changed to STOPPED and all the subscriptions are notified with onComplete callback:
`record.notifyOnCompleted()`. 
This is the reason flow's channel is closed:
```
fun <T> ApolloSubscriptionCall<T>.toFlow(): Flow<Response<T>> = callbackFlow {
  val clone = clone()
  clone.execute(
      object : ApolloSubscriptionCall.Callback<T> {
      ....
        override fun onCompleted() {
          channel.close()
        }
...
      }
  )
  awaitClose { clone.cancel() }
}
```
clone.cancel() calls SubscriptionManager#doUnsubscribe for subscription that not even exists anymore in subscription manager. Current state is STOPPED (not STOPPING) that's why next lines from doUnsubscribe method start inactivity timer:
```
if (subscriptions.isEmpty() && state != SubscriptionManagerState.STOPPING) {
        startInactivityTimer();
      }
```
And, finally, after some delay disconnect() is called from this task and state is changes to Disconnected.

Sadly I can't come up with a workaround for this issue.

**Comment by martinbonnin** [comment]
Thanks for reaching out! 

Can you elaborate on what you'd expect the behaviour to be? What is the reason you're calling `SubscriptionManager#stop()` in the first place?  Would you like `stop()` to keep the subscriptions/Flows active?

**Comment by vkornii** [comment]
hi Martin!

> Can you elaborate on what you'd expect the behaviour to be?
I expect all subscriptions are completed (or maybe terminated) and SubscriptionManager stays in STOPPED state, not switching to DISCONNECTED by itself
>  What is the reason you're calling SubscriptionManager#stop() 
I want to stop all subscriptions and drop ws connection under some circumstances. Like in a reaction to exception or user session error 
>  Would you like stop() to keep the subscriptions/Flows active?
Subscriptions/Flows should be completed for sure. This is how it works now

Thank you for your time

**Comment by martinbonnin** [comment]
Thanks! Something I'm missing is why the state of `STOPPED` vs `DISCONNECTED` matters? Is there some special handling you need to do in one of these states ?

**Comment by vkornii** [comment]
> Is there some special handling you need to do in one of these states ?
Yes. State change event from STOPPED to DISCONNECTED mean SubscriptionManager#start() was called and all pending subscriptions may proceed.

**Comment by martinbonnin** [comment]
> State change event from STOPPED to DISCONNECTED mean SubscriptionManager#start() was called

I see

> all pending subscriptions may proceed.

Pending subscriptions made after the `SubscriptionManager#start()` call, right? Because previous subscriptions are all [removed](https://github.com/apollographql/apollo-android/blob/87d6d471f427ec79468aa900930daf9c5d965160/apollo-runtime/src/main/java/com/apollographql/apollo/internal/subscription/RealSubscriptionManager.java#L235).

Overall, I'm not 100% sure what the semantics should be there. I'm guessing the calls to `stop()/start()` are needed to stop the websocket ? Maybe for battery reasons from onStop/onStart ? If that's the case, could you rely on `stop()/start()` directly instead of the async state?  

```kotlin
override fun onStop() {
    super.onStop()
    
    subscriptionManager.stop()
}

override fun onStart() {
    super.onStart()
    
    subscriptionManager.start()
    scope.launch {
        apolloClient.subscribe(MySubscription()).toFlow().collect { ... }
    }
}
```

**Comment by vkornii** [comment]
> I'm guessing the calls to stop()/start() are needed to stop the websocket ? Maybe for battery reasons from onStop/onStart ?

Yes and yes. I want something like that:

`override fun <S : Subscription<D, T, V>, D : Operation.Data, T, V : Operation.Variables> 
createSubscription(input: S): Flow<T> =
        subscriptionManager
            .activityFlow()
            .flatMapLatest {
                apolloClient.subscribe(input)
                    .toFlow()
                    .map { requireNotNull(it.data) }
            }`

where activityFlow is extension function that returns flow that emits event either on subscribe (app is foreground in this case), either after state change stopped -> disconnected (subscription is recreated after stop()/start() calls)

and flatMapLatest is coroutine alternative to rx's switchMap

**Comment by martinbonnin** [comment]
Where do you call `SubscriptionManager#stop()` in the above example? You'd need a hook somewhere when the current screen/application is not visible or something else. Once you have that, it should be relatively easy to call `SubscriptionManager.start()` in the symmetrical call and you wouldn't need to rely on different states anymore?

**Comment by martinbonnin** [comment]
Thanks for the update!

> The idea behind this code is to stop websocket while app is in background but make it transparent for those consumerts who call createSubscription() method. This means its not necessary, to recreate subscription in fragment (or somewhere else) every time application goes foreground.

The only case where I think this is helpful is if you have a stateful Fragment. Like for an exemple a button that start displaying a newsfeed from a subscription when clicked. In that case, the UI state (==the view hierarchy) will not change during `onPause/onResume` but it is desirable to close/resume the websocket. Checking the UI state from `onResume` is awkward because it leads to code like:

```kotlin
var isSubscriptionRunning = false

fun onButtonPressed() {
  isSubscriptionRunning = true
  scope.launch {
    apolloClient.subscribe(subscription).toFlwo().collect {
      displayNewsItem(it)
    }
  }
}

fun onPause() {
  subscriptionManager.stop()  
}

fun onResume() {
  if (isSubscriptionRunning) {
    scope.launch {
      apolloClient.subscribe(subscription).toFlwo().collect {
        displayNewsItem(it)
      }
    }
  }
}
```
Is this the use case? 

If yes, you're out of luck because `SubscriptionManager#stop()` will forget about active subscriptions so we'll need to find a way to store the subscriptions somewhere and resume them automatically.

**Comment by vkornii** [comment]
hi, 
I've found the real reason my problem appear. Sometimes awaitClose clause is executed before terminate() is called in in RealSubscriptionCall. 
Wrong order:

```
onCompeted()
awaitClose { clone. cancel() }
terminate()
```

Correct order:
```
onCompeted()
terminate()
awaitClose { clone. cancel() }
```

My workaround is to call channel.close() from different coroutine to make sure subscription is terminated by this time.

**Comment by martinbonnin** [comment]
Nice, thanks for the update 👍
