### ISSUE TITLE
Add support for `public final` model fields instead of accessor methods

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#332]
As we have seen with some sample queries, a innocent looking `gql` can generate a lot of methods.

We should consider either allowing a user to specify `apollo { publicFinalFields = true }`, or just move to them altogether.

The main argument for accessor/getter functions is that it allows for the underlying data model to change it's implementation without needed downstream changes. However, afaik, the current graphql spec doesn't require any complicated getter logic.

This should also help with kotlin interop as getters without `get___` will not autoconvert to properties:  https://kotlinlang.org/docs/reference/java-interop.html#getters-and-setters

**Comment by BenSchwab** [comment]
Performance impact: https://developer.android.com/training/articles/perf-tips.html#GettersSetters

**Comment by kassim** [comment]
I like this idea, simply because I prefer the look of accessing fields instead of getter methods, however the opposing argument is usually, (taken from the above article)

> Note that if you're using ProGuard, you can have the best of both worlds because ProGuard can inline accessors for you.

**Comment by sav007** [comment]
From one point of view we can rid off accessor methods as fields are immutable.
But at the same time by doing this we are closing doors for mocking (if I'm right for instance Mockito  doesn't support mock field). I guess the best way to have config option
