### ISSUE TITLE
Support Apple M1 Simulator in KMM builds

### ISSUE THREAD

**Issue by samus** [apollographql/apollo-android#3320]
**Is your feature request related to a problem? Please describe.**
With Kotlin 1.5.30, builds for the iOS simulator on Apple M1 chips are possible but only if all dependencies are producing versions targeting it.  Adding the iOSSimulatorArm64 target to a build.gradle file produces the following error:

> No matching variant of com.apollographql.apollo3:apollo-runtime:3.0.0-dev14 was found. The consumer was configured to find a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64'

**Describe the solution you'd like**
Adding a build target for iOSSimulatorArm64 along with the iosX64 target will allow those on Intel and M1 Macs to test in the simulator.

**Comment by pauldavies83** [comment]
I quickly tried what @martinbonnin suggested, and he's correct in saying that the following upstream dependencies need to also make this change before the `apollo` build can proceed after the change.

`org.jetbrains.kotlinx:kotlinx-datetime`
`com.squareup.okio:okio-multiplatform`
`com.benasher44:uuid:0.2.2`

**Comment by ychescale9** [comment]
Issue for okio: https://github.com/square/okio/issues/986
PR for uuid: https://github.com/benasher44/uuid/pull/118

**Comment by ychescale9** [comment]
[benasher/uuid](https://github.com/benasher44/uuid) now has Apple sillicon targets: https://github.com/benasher44/uuid/releases/tag/0.3.1

**Comment by pauldavies83** [comment]
kotlinx-datetime:0.3.0 has the needed changes now

https://github.com/Kotlin/kotlinx-datetime/releases

i think we are just blocked on `okio` now

**Comment by pauldavies83** [comment]
This was merged in `okio` last night. I have a branch ready to submit for this issue, but it's dependent on the next version bump of `okio`

https://github.com/square/okio/pull/1028

**Comment by ProVir** [comment]
This functionality became available in beta 02, I think you can close the issue.

**Comment by martinbonnin** [comment]
Yup, thanks for the heads up!
