### ISSUE TITLE
"Failed to parse GraphQL" when using SDL and empty string as default value

### ISSUE THREAD

**Issue by francescocervone** [apollographql/apollo-android#3323]
**Summary**
When a field or a query/mutation argument has an empty string (`""`) as default value, Apollo generates an SDL with
`""""""""` and the `generateApolloSources` task fails with `Failed to parse GraphQL file` error.

**Version**
2.5.9

**Description**
Let's say we have a mutation:
```graphql
mutation sample(argument: String = "")
```
Then I run:
```bash
./gradlew downloadApolloSchema
```
Apollo generates the `schema.sdl` as:
```graphql
mutation sample(argument: String = """""""")
```
Then I run:
```bash
./gradlew generateApolloSources
```
and I get the error
```bash
Failed to parse GraphQL file my/file/path Unsupported token `)`
```

---

The issue does not occur when using JSON schema format.

**Workaround**
I have to manually replace all occurrences of `""""""""` with `""""""` in the SDL file after schema download.

**Comment by martinbonnin** [comment]
`3.0.0` is now released, closing this issue.
