### ISSUE TITLE
[3.x] Make it possible to create enum values from `rawValue`

### ISSUE THREAD

**Issue by kubode** [apollographql/apollo-android#3325]
**Is your feature request related to a problem? Please describe.**
In `3.x`, the sealed class is generated from the enum type, but there seems to be no way to generate a sealed class from `rawValue`.
In Android, I want to pass an enum as a screen argument, but the generated sealed class is neither `Serializable` nor `Parcelable`, so I can't pass it directly.
So, I need to pass a `rawValue` to decode it.
However, since there is no way to decode the generated sealed class, I have to write a boilerplate to decode it on the Android side.
I would like Apollo to generate the code to do this decoding.

**Describe the solution you'd like**

Add `<GeneratedEnumType>.Companion.safeValueOf(String)` like `main` branch.
https://github.com/apollographql/apollo-android/blob/7c6e26bbdfd6a22272bf0d93a564a612a4daff75/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/codegen/kotlin/EnumType.kt#L133-L149

**Comment by martinbonnin** [comment]
Hi 👋 , in this case, you can use the enum adapter. Assuming you have a GraphQl enum named `Direction`:

```graphql
enum Direction {
  LEFT,
  RIGHT
}
```

This will generate the sealed class:

```kotlin
sealed class Direction(val rawValue: String) {
 object LEFT : Direction(rawValue = "LEFT")
 object RIGHT : Direction(rawValue = "RIGHT")
  class UNKNOWN__(rawValue: String): Direction(rawValue)
}
```

You can use the generated adapter to decode `rawValue`:

```kotlin
import com.apollographql.apollo3.api.fromJson

val direction = Direction_ResponseAdapter.fromJson(rawValue)
```

**Comment by martinbonnin** [comment]
That being said, and thinking more about this, adding a more discoverable companion method like you suggest is a good idea. Do you want to open a PR?

**Comment by kubode** [comment]
Thank you for your quick response!


> That being said, and thinking more about this, adding a more discoverable companion method like you suggest is a good idea. Do you want to open a PR?

I'll try to make a PR later 👍 

Should the following code be generated?
```kotlin
sealed class Direction(val rawValue: String) {
  object LEFT : Direction(rawValue = "LEFT")
  object RIGHT : Direction(rawValue = "RIGHT")
  class UNKNOWN__(rawValue: String): Direction(rawValue)
  companion object {
    fun safeValueOf(rawValue: String): Direction {
      return when (rawValue) {
        "LEFT" -> Direction.LEFT
        "RIGHT" -> Direction.RIGHT
        else -> Direction.UNKNOWN__(rawValue)
      }
    }
  }
}
```

**Comment by martinbonnin** [comment]
I think we can drop the "safe" there. It's always safe with sealed classes. Worst case, you get an `UNKNOWN` class.

Also ideally, the adapter code should reuse this code so to factor the `when` code: https://github.com/apollographql/apollo-android/blob/0254755bb2b0a516ca3b951d7e6a067d206f9296/apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/codegen/adapter/EnumResponseAdapterBuilder.kt#L60

Besides these 2 things, looks good 👍

**Comment by martinbonnin** [comment]
Something I just realized is that `UNKNOWN__` doesn't implement `hashCode/equals` which can be counter-intuitive. I'll add that as part as a future PR.
