### ISSUE TITLE
Unsupported token `{` 

### ISSUE THREAD

**Issue by vancouverwill** [apollographql/apollo-android#3331]
**Summary**
Unreadable error message does not state where in `schema.json` the problem is despite the json being valid

**Version**
2.5.9

**Description**
* I download the schema as recommend with either: 

  * A my projects schema 
   ```
  ./gradlew downloadApolloSchema --endpoint='http://localhost:5002/graphql' --schema=src/main/java/co/../schema.json
    ```
   *  or with B the sample apollo app on Heroku.
  ```
  ./gradlew downloadApolloSchema --endpoint='https://apollo-fullstack-tutorial.herokuapp.com/' -- 
  schema=src/main/java/co/.../schema.json
  ```
* verify the `schema.json` is valid with `cat src/main/java/co/.../schema.json  | jq .`
* attempt to generate sources with `./gradlew generateApolloSources`
* see below error 
```
Failed to parse GraphQL file ./src/main/java/co/.../schema.json (1:0)                                                    
  Unsupported token `{`                                                                                                                                                                                            
  ---------------------------------------------------- 
```
It says error at character 0 of line 1 which means it doesn't support valid json as I have already checked the json is valid and the error message does not give any more context as to the issue. As it does not seem to support json I tried with the `schema.graphql` style format but then get the error the same as https://github.com/apollographql/apollo-android/issues/2095 

For reference here is my gradle config
```
plugins {
  ...
    id("com.apollographql.apollo").version("2.5.9")
}

dependencies {
   ...
    implementation("com.apollographql.apollo:apollo-gradle-plugin:2.5.9")
    implementation("com.apollographql.apollo:apollo-runtime:2.5.9")
    implementation("com.apollographql.apollo:apollo-coroutines-support:2.5.9")
}


tasks{
    apollo {
        generateKotlinModels.set(false)
        graphqlSourceDirectorySet.srcDir("src/main/java/co/...")
    }
}
```

**Comment by martinbonnin** [comment]
Hi 👋 ! Thanks for reaching out!

> Failed to parse GraphQL  file ./src/main/java/co/.../schema.json 

This is trying to parse the schema as a GraphQL file (and not json). The usual setup is to put your schema under `src/main/graphql/com/example/schema.json` (and not `src/main/java...`)

> I tried with the schema.graphql style format 

To be recognized as SDL, the schema should have a `.graphqls` extension.

It looks like your schema.json is fine but the setup/wiring doesn't detect this. Is there a reason you put the graphql files in `src/main/java` and not `src/main/graphql` ?

**Comment by vancouverwill** [comment]
thanks for the quick reply @martinbonnin . very much appreciated :pray: 

> This is trying to parse the schema as a GraphQL file (and not json). The usual setup is to put your schema under src/main/graphql/com/example/schema.json (and not src/main/java...)

Ahh I see thanks.  I thought by setting up the source directory I could over ride that with `graphqlSourceDirectorySet.srcDir("src/main/java/co/...")`? No worries though, I have moved the schema to under  `src/main/graphql/com/` and it is generating the java in `build/generated/source/apollo/main/service/com/..../*.java` as I had hoped for :smile: 

> To be recognized as SDL, the schema should have a .graphqls extension.

Ahh okay, that's good to know TIL :smile: 

Thanks again for the help, really useful
