### ISSUE TITLE
[dev-3.x] MainContinuation freezing error

### ISSUE THREAD

**Issue by rickclephas** [apollographql/apollo-android#3347]
**Summary**
Querying for data with a frozen `ApolloClient` crashes the iOS app with a freezing exception.

**Version**
The issue is present in `3.0.0-alpha03`. Last known working version is `3.0.0-dev14`.

**Description**
When the `ApolloClient` is frozen so is the `CancellableContinuation` which according to the following line should never happen.
https://github.com/apollographql/apollo-android/blob/ecaad15d88d8af9b8e3dac809f4bc1fb1e9d2e5c/apollo-mpp-utils/src/appleMain/kotlin/com/apollographql/apollo3/mpp/dispatchOnMain.kt#L39

Possible related to #3127.
Also see https://github.com/rickclephas/KMP-NativeCoroutines/issues/10 for some more context and reproduction code by @ychescale9.

**Comment by martinbonnin** [comment]
Thanks for the thorough investigation! Looks like removing the `ensureNeverFrozen` does the job, I relaxed the restriction and added more tests in https://github.com/apollographql/apollo-android/pull/3350.

I was under the impression that a continuation should never be frozen but looks like I was wrong there. I'll try to dig a bit more to get a better understanding of where the failing `freeze()` happens

**Comment by ychescale9** [comment]
Thanks @martinbonnin . I also tried to comment out `ensureNeverFrozen` locally and it's working as expected 👍
