### ISSUE TITLE
IndexOutOfBoundsException in MapJsonReader

### ISSUE THREAD

**Issue by ProVir** [apollographql/apollo-android#3361]
Hi!

For my current schema, I get a strange error when getting data:
`com.apollographql.apollo3.exception.ApolloParseException: Failed to parse GraphQL http network response`
`java.lang.IndexOutOfBoundsException: Index: 10, Size: 1`

This bug was found in alpha04, but it is also reproduced in alpha06.

`names` has a strange index that turns out to be unrelated to it.

![image](https://user-images.githubusercontent.com/7127304/133649634-439ee098-b461-4bfa-bf44-e4a6e2e52eca.png)

**Comment by martinbonnin** [comment]
Thanks for sending this. Any chance you can provide the `.graphql` query and matching `.json` response? This points into a nesting issue when trying to guess the next name.

**Comment by ProVir** [comment]
My request and response data:

[GraphQL Request.txt](https://github.com/apollographql/apollo-android/files/7181077/GraphQL.Request.txt)

**Comment by ProVir** [comment]
I will add to simplify the analysis of the problem: if you comment out both fields , the problem disappears. But it is only necessary to return any of them - it is reproduced again.

![image](https://user-images.githubusercontent.com/7127304/133837575-9c340cd4-a33d-42df-9498-3e9dfaf2fbea.png)

**Comment by martinbonnin** [comment]
Sorry for the delay there. I can reproduce the issue. This is due to `operationBased`/`compat` codegen reading the same object twice asking less fields the second time. Will change this.

**Comment by ProVir** [comment]
I tested in 3.0.0-alpha 07-SNAPSHOT - now it works. Thanks!

**Comment by ProVir** [comment]
@martinbonnin  Tell me, when is release 3.0.0-alpha07 expected? There are a lot of changes in it for me to switch from 3.0.0-alpha04.

**Comment by martinbonnin** [comment]
I was hoping to get the test APIs + Builders in and call that a beta01 but the test APIs are taking longer than expected. I'll release alpha07 today to unblock these issues.

**Comment by martinbonnin** [comment]
`3.0.0-alpha07` is out 🎉
