### ISSUE TITLE
Subscription errors throw an exception on flow collect

### ISSUE THREAD

**Issue by sproctor** [apollographql/apollo-android#3369]
**Summary**
Apollo throws `ApolloSubscriptionServerException: Subscription failed` when when the server responds with an error to a subscription.

**Version**
2.5.9

**Description**
I have an problem (trying to access a field without permission) in my subscription query. The server responds with an appropriate error response. Apollo throws `ApolloSubscriptionServerException: Subscription failed` when the flow is collected. The documentation to find the error message is non-existent, and it's unexpected that the response containing the error isn't emitted in the flow.

Code looks something like:
```kotlin
try {
    val subscriptionFlow = client.subscribe(subscription).toFlow()
    subscriptionFlow.collect { }
} catch (e: ApolloSubscriptionServerException) { }
```

**Comment by martinbonnin** [comment]
Hi 👋 

You should be able to look into `ApolloSubscriptionServerException.errorPayload` to get some more info about what the error was. I'm reluctant to printing it by default as it could potentially be very large or leak personally identifiable information but we could add a hint that it's there? Something like:

```
ApolloSubscriptionServerException: Subscription failed. Check errorPayload for more details.
```

?

**Comment by martinbonnin** [comment]
@sproctor #3381 adds a more detailed error message. I'll close this issue for now. Let me know if you want me to reopen.
