### ISSUE TITLE
Help, cannot infer type-variable(s) D,T,V

### ISSUE THREAD

**Issue by xszconfig** [apollographql/apollo-android#337]
version: 0.2.2-SNAPSHOT
issue: cannot compile
error stack:
error: method newCall in class ApolloClient cannot be applied to given types;
        return checkResponse(apolloClient.newCall(new Unfollow(builder.build())).execute())
                                         ^
  required: Operation<D,T,V>
  found: Unfollow
  reason: cannot infer type-variable(s) D,T,V
    (argument mismatch; Unfollow cannot be converted to Operation<D,T,V>)
  where D,T,V are type-variables:
    D extends Data declared in method <D,T,V>newCall(Operation<D,T,V>)
    T extends Object declared in method <D,T,V>newCall(Operation<D,T,V>)
    V extends Variables declared in method <D,T,V>newCall(Operation<D,T,V>)

**Comment by sav007** [comment]
Did you invalidate cached gradle dependencies ?

**Comment by sav007** [comment]
Because we publishing breaking changes to api module under the same snapshot version, you should refresh your gradle cached dependencies `--refresh-dependencies`
