### ISSUE TITLE
Android API 16-21

### ISSUE THREAD

**Issue by vmosconecds** [apollographql/apollo-android#3377]
Do `apollo-android` have support for working between API 16-21? I don't know if there is a minimum API level to be able to work with it. Thanks!

**Comment by martinbonnin** [comment]
Apollo Android [supports API levels 15+](https://github.com/apollographql/apollo-android). IIRC, you'll need to enable [Java 8 language features](https://developer.android.com/studio/write/java8-support?authuser=1) but that should be the default in the Kotlin plugin these days.

**Comment by vmosconecds** [comment]
Thanks @martinbonnin
