### ISSUE TITLE
Connect to Websocket URL directly (bypass /graphql endpoint)

### ISSUE THREAD

**Issue by seleroy** [apollographql/apollo-android#3387]
**Question.**
Hello,
I am trying to use the ApolloClient (v2.5.9) to create a client to a Websocket subscription. Note that I don't own the server side.

There are 2 URLs used during the connection:
serverUrl=https://endpoint/graphql
wsUrl=wss://websocket-address

I create a client using:
`        ApolloClient client = ApolloClient.builder().serverUrl(serverUrl)
                .okHttpClient(new OkHttpClient.Builder()
                        .addInterceptor(new AuthorizationInterceptor())
                        .build())
                .subscriptionConnectionParams(subscriptionConnectionParams)
                .subscriptionTransportFactory(new WebSocketSubscriptionTransport.Factory(wsUrl, okHttpClient))
                .build();`

The problem I have is that my server expects me to connect to the wss:// url to start the transaction and perform the handshake. But the ApolloClient tries to contact the HTTP endpoint. As far as I know the serverUrl cannot be empty and only accept an url starting by http or https, so I cannot pass the wss:// url as the serverUrl

Is there any way to tell the ApolloClient to target the wsUrl instead of the serverUrl from the start ?
Thank you

**Comment by martinbonnin** [comment]
That would be there: https://github.com/square/okhttp/blob/e1af67f082027dd7811c88434749b7b8f807ceca/okhttp/src/main/kotlin/okhttp3/Request.kt#L173. 

Do you have a specific error or something that would hint at a bad url being passed?

**Comment by martinbonnin** [comment]
> Is there any way to tell the ApolloClient to target the wsUrl instead of the serverUrl from the start ?

Aah, sorry I missed that part. `wsUrl` should be used for subscriptions. If you're not doing any query or mutation, you can pass an unused `serverUrl` like `https://example.com/graphql`. Hope this helps. If that still doesn't work, a proxy capture or stacktrace would be useful to investigate this further.

**Comment by seleroy** [comment]
working, thanks @martinbonnin
