### ISSUE TITLE
Improve handling of Kotlin version incompatibility issues

### ISSUE THREAD

**Issue by BoD** [apollographql/apollo-android#3400]
# Problem

The library is compiled with a certain release of Kotlin, and can be used in projects using Kotlin with at least one 'feature' release below it. For instance, Apollo Android `v1.5.9` uses Kotlin `v1.5.0`, meaning projects using Apollo must at least depend on Kotlin `v1.4.0` but not lower (more information about this [here](https://kotlinlang.org/docs/kotlin-evolution.html#evolving-the-binary-format))

When such incompatibility is encountered, the Kotlin compiler will issue messages such as this:
```
/Users/bod/.gradle/caches/transforms-2/files-2.1/0235401bb5cfc2b448312f6e0240d2ca/jetified-apollo-http-cache-api-2.5.9.jar!/META-INF/apollo-http-cache-api.kotlin_module: 
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
```

This message may not be 100% clear to where the issue comes from.

# Solution
1. The minimum required version of Kotlin should be clearly specified on the project's README file
2. The Apollo Android Gradle plugin could detect such incompatible versions and log a clear warning

**Comment by martinbonnin** [comment]
@BoD I might have closed this one a bit too fast. Is it good or do we need to do something else?

**Comment by BoD** [comment]
No, I think we're good with #3475 👍
