### ISSUE TITLE
Apollo 3: Using reserved name in schema

### ISSUE THREAD

**Issue by denys-meloshyn** [apollographql/apollo-android#3402]
**Summary**
In our schema we have next type:
```
type System {
 ...
}
```
During the build I receive next error:
> error: System is already defined in this compilation unit
import java.lang.System;
^

**Version**
3.0.0-alpha07

**Description**
I know that the easiest solution would be to rename the type but it will require changing other clients 🙂

**Comment by denys-meloshyn** [comment]
Previously it worked just fine 🤷‍♂️ I tried to clear cache couple of time.
`/build/tmp/kapt3/stubs/debug/com/music/graph_ql/apollo/type/System.java`

**Comment by martinbonnin** [comment]
Thanks for all the details! This is a kapt issue: https://youtrack.jetbrains.com/issue/KT-43117

A few possible solutions:
* Switch to KSP if using Room or Moshi, not sure if it's already possible for other annotation processors
* Split your module in two different modules, one with kapt, the other with apollo
* If none of the above works, we could add a workaround to rename `System` to `System_` in the codegen but I'd rather do this as a last resort as it'll require another codegen option that we will have to expose from the Gradle down to the codegen.

**Comment by denys-meloshyn** [comment]
hi @martijnwalraven, yes removing kapt from module helped. I think we can close this issue, thanks for help! 🙌
