### ISSUE TITLE
Kotlin Multiplatform generate the enums as enums, and not sealed classes.

### ISSUE THREAD

**Issue by boldijar** [apollographql/apollo-android#3428]
I'm using apollo with KMM, and for some reasons my enums are generated as sealed classes.
Is there a way to do this? Or the only way is to use the adapter as explained here
https://github.com/apollographql/apollo-android/issues/3325#issuecomment-908273615

I was also looking into this variable - sealedClassesForEnumsMatching - which I am unsure how to use it, and it looks that on KMM project is not defined.

**Comment by BoD** [comment]
Hi!
Sealed class were favored because in addition to when exhaustiveness, they also have the ability to expose the `rawValue`.

May we ask what your use case for enums is? Also can you confirm you are using v3?
