### ISSUE TITLE
Missing Builder in ApolloClient. Ver. 3.0.0-alpha7

### ISSUE THREAD

**Issue by adammach** [apollographql/apollo-android#3440]
Seems there some bug in documentation/code about migration to v. 3.0.0. Right now ApolloClient has no builder (it make sense) but you forgot(?) to add normalizedCache param in constructor, so we cannot build it with cache functionality. https://www.apollographql.com/docs/android/v3/migration/3.0/

**Comment by Jparrgam** [comment]
hi @martinbonnin Do you know if the method still exists in version 3.2.1 I am creating the client in the following way but the method gives me that it does not exist 

![carbon](https://user-images.githubusercontent.com/8985838/165199886-c1feb7b2-3923-4d6c-a504-648d7f8d2262.png)

**Comment by martinbonnin** [comment]
@Jparrgam can you share what is the error you're seeing?

Also double check that you have `apollo-normalized-cache-sqlite` in your dependencies? `normalizedCache()` is an extension function so you'll need to have it or it won't show up

**Comment by martinbonnin** [comment]
Turns out both `apollo-normalized-cache-sqlite` and `apollo-normalized-cache` are required.
