### ISSUE TITLE
How to get query string from Apollo

### ISSUE THREAD

**Issue by ramanpreetSinghKhinda** [apollographql/apollo-android#3469]
**Question 1**
I would want to use Apollo to generate GraphQL query and followed [Android docs](https://www.apollographql.com/docs/android/essentials/get-started-java/) to get started. I see that you provide `ApolloClient` to execute the query however I would want to use my own client and hence I wonder if it's possible to get Query String from the generated model class.

**src/main/graphql/com/example/LaunchDetails.graphql**
```
query MyDetails(
    $withName: Boolean!,
    $withAddress: Boolean!,
    $withAddressCity: Boolean!,
    $withAddressState: Boolean!
) {
    details {
        name @include(if: $withName)
        address @include(if: $withAddress) {
            city @include(if: $withAddressCity)
            state @include(if: $withAddressState)
        }
    }
}

```

**Query 1**
```
String graphQlQueryString = new MyDetails(true, true, true, true).getQueryString()
```

**Result 1**
```
{details { name address { city state }}}
```

**Query 2**
```
String graphQlQueryString = new MyDetails(true, true, true, false).getQueryString()
```

**Result 2**
```
{details { name address { city }}}
```

---

**Question 2**

Also I wonder if it's possible to specify query with multiple boolean params like below:

```
query MyDetails(
    $withName: Boolean!,
    $withAddressCity: Boolean!,
    $withAddressState: Boolean!
) {
    details {
        name @include(if: $withName)
        address @include(if: $withAddressCity OR withAddressState) {
            city @include(if: $withAddressCity)
            state @include(if: $withAddressState)
        }
    }
}

**Comment by martinbonnin** [comment]
Hi @ramanpreetSinghKhinda have you been able to do some progress here?

**Comment by ramanpreetSinghKhinda** [comment]
Thanks for the response @martinbonnin. For now I decided to not use Apollo since the specific use-case is not being addressed. However, if anything changes in future I'll definitely reach out with more details.
