### ISSUE TITLE
Android Tutorial:  --schema and --endpoint options aren't working for downloadApolloSchema task

### ISSUE THREAD

**Issue by aormsby** [apollographql/apollo-android#3470]
**Summary**
For some reason, the provide gradle task to download the Android tutorial schema fails. Well... technically, it succeeds. But it doesn't download anything.
```shell
./gradlew :app:downloadApolloSchema --endpoint='https://apollo-fullstack-tutorial.herokuapp.com/introspectionSchema.json' --schema='app/src/main/graphql/com/example/rocketreserver/schema.json'
```

**Version**
I ran the task with both 2.5.9 and 2.5.10.

**Description**
I wondered if maybe the input values were incorrect, but then I used the deprecated `-Pcom.apollographql.apollo.endpoint` and `-Pcom.apollographql.apollo.endpoint` options. This was successful.

I'd love to think I missed a step or something, but I'm not sure.

**Comment by martinbonnin** [comment]
@aormsby anything else we can help with here?

**Comment by aormsby** [comment]
Nah, worked out well enough

**Comment by jclement92** [comment]
Ran into this issue as well. The path `app/src/main/graphql/com/example/rocketreserver/` did not exist in the initial branch. Added it manually and the download was successful

**Comment by BoD** [comment]
Thanks for reporting it!  We indeed could reproduce the issue this time and fixed the root cause as well as the tutorial instructions so they work with the current version
