### ISSUE TITLE
Reading fragments from apolloStore

### ISSUE THREAD

**Issue by adammach** [apollographql/apollo-android#3484]
Hi,
could you please provide example of reading fragments from apolloStore in ver 3.0.0-beta1 ?
You provide method:
`apolloStore.toRx3ApolloStore().rxReadFragment`
where as parameter Fragment is expected. Generated code extends Fragment.Data. How can I get implementation of Fragment interface. Do we need to implement it ourself?

**Comment by martinbonnin** [comment]
Hi 👋 !

You can use the `generateFragmentImplementations` [Gradle property](https://github.com/apollographql/apollo-android/blob/4b9531f05a9aad6cfcceda5a83b33a79f7ca3abb/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo3/gradle/api/Service.kt#L236)

Then you can read your fragment with:

```
apolloStore.readFragment(fragment, CacheKey(id))
```

We'll add that to the docs!

**Comment by adammach** [comment]
Thanks! One step forward :)

**Comment by Emplexx** [comment]
Hello, I am trying to read a fragment from apolloStore but I am encountering a cache miss exception and I'm not sure what I'm doing wrong
Before trying to read the fragment I have already executed a query that returns that fragment as part of its response 
My fragment 
```
fragment MediaView on Media {
	id
	type

	title {
		userPreferred
		english
		romaji
		native
	}
	coverImage {
		large
	}

	episodes
	chapters
	volumes

	format
	status
	genres
	countryOfOrigin
	seasonYear

	averageScore
	popularity

	startDate {
		year
		month
		day
	}

	isAdult

	bannerImage
}
```

my extra.graphqls
`extend type Media @typePolicy(keyFields: "id")`

Am I doing something wrong? Would be very grateful for help
