### ISSUE TITLE
v3 missing documentation

### ISSUE THREAD

**Issue by BoD** [apollographql/apollo-android#3490]
- [x] Migration guide
- [x] RxJava
- [x] Section "Reading from the store programmatically"
- [x] Declarative cache
- [x] Imperative cache
- [x] File Upload
- [x] Test models
- [x] espresso
- [x] `apollo-ast`
- [x] Introspection and SDL schemas
- [x] Add `dataOrThrow` to the error handling page
- [x] Remove references to Spectrum / replace with Kotlin Slack
- [x] Update structure of the pages / left bar / getting started
- [x] Query Batching

**Comment by martinbonnin** [comment]
Looks like we're done 🎉
