### ISSUE TITLE
Uniformize operation APIs?

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#3494]
Currently we have:

```kotlin
apolloClient.query(query).execute()
apolloClient.mutate(mutation).execute()
apolloClient.subscribe(subscription).execute()
```

I find it weird, especially in the mutation/subscription case we have 2 chained verbs. Should we do this instead?

1.
```kotlin
apolloClient.query(query).execute()
apolloClient.mutation(mutation).execute()
apolloClient.subscription(subscription).execute()
```

or 

2.
```kotlin
apolloClient.queryCall(query).execute()
apolloClient.mutationCall(mutation).execute()
apolloClient.subscriptionCall(subscription).execute()
```

or 

3.
```kotlin
apolloClient.query(query).await()
apolloClient.mutate(mutation).await()
apolloClient.subscribe(subscription).toFlow()
```
Given that 3.0 is coming soon, it's now or never

**Comment by BoD** [comment]
I like this change (favoring the 1st one without "call") because it mirrors the GraphQL syntax.

**Comment by martinbonnin** [comment]
Silly question. Why not keeping the 2.x API?

```kotlin
apolloClient.query(query).await()
apolloClient.mutate(mutation).await()
apolloClient.subscribe(subscription).toFlow()
```

**Comment by BoD** [comment]
Do you mean as a (deprecated) migration helper?

**Comment by martinbonnin** [comment]
> Do you mean as a (deprecated) migration helper?

Not really. What about keeping it for real? Except it doesn't need the imports?

**Comment by BoD** [comment]
So they would be a synonym of `execute`? Or do you mean rename `execute` to use these names instead?

**Comment by martinbonnin** [comment]
> Or do you mean rename execute to use these names instead?

That. 

`apolloClient.mutate(mutation).execute()` feels weird but `apolloClient.mutate(mutation).await()` sounds better to me. The first verb (`mutate`) starts the action, the second (`await`) awaits completion. As a bonus, it reuses the same API as 2.x

**Comment by BoD** [comment]
I see!

I personally prefer `execute` because of its consistency across the 3 operations (less surprising API) but it's pretty much subjective, and I see your point too. One thing: not sure it would be clear that `await` can be called multiple times whereas it makes sense (at least to me!) with `execute`.

**Comment by martinbonnin** [comment]
>  consistency across the 3 operations (less surprising API)

The counter argument can be made that subscriptions are of different kind (Flow) so could use different name. But yea...

>  not sure it would be clear that await can be called multiple times whereas it makes sense (at least to me!) with execute

100% agree, that's a good pont. 

Also now is certainly a good time to think of what this API will look like under defer/stream. What we decide now would have to be somewhat compatible.

**Comment by martinbonnin** [comment]
One more argument for `mutation` instead of `mutate` is that it makes it less tempting to omit the return value if it's not read:

```kotlin
// Might be tempting to call it a day and assume something changed
apolloClient.mutate()

// `mutation` is not an action so it's a hint that execute() is required
apolloClient.mutation().execute()
```

**Comment by BoD** [comment]
Just a reminder of the current situation:

```kotlin
ApolloCall<D: Operation.Data> (abstract)
fun executeAsFlow(): Flow<ApolloResponse<D>>

ApolloQueryCall<D: Query.Data>
suspend fun execute(): ApolloResponse<D>

ApolloMutationCall<D: Mutation.Data>
suspend fun execute(): ApolloResponse<D>

ApolloSubscriptionCall<D: Subscription.Data>
fun execute(): Flow<ApolloResponse<D>>
```

It's still very early on the reflection about defer/stream but it seems to me that we could already go for this naming convention:

- `executeAsFlow` returns Flow
- `execute` returns 1 result (suspend)

This means in the future, for queries and mutations, partial results could be obtained by calling `executeAsFlow` while "traditional" (not defer/stream) can use `execute`

This also means `execute` on `ApolloSubscriptionCall` should probably be deleted for consistency (consumers should use `executeAsFlow` instead).

WDYT?

**Comment by martinbonnin** [comment]
This makes sense. I'm all for deleting `ApolloSubscriptionCall.execute()` (after a short deprecation period...).

About `executeAsFlow`, I'm a bit concerned that `execute()` and `Flow` are somewhat contradictory. `execute` is terminal while flow are cold and need to be collected. Maybe

* `toFlow()` returns Flow
* `execute()` suspends and returns 1 

This is relatively similar to what SQLDelight is doing with [Query.asFlow](https://cashapp.github.io/sqldelight/js_sqlite/coroutines/) (except they're using `as` and not `to`)

**Comment by BoD** [comment]
Good point about the `execute`!  For `to` vs `as`, no real preference for now even though I tend to favor `to` for no particular reason  😅

So it would look like this in `beta-04`:

```
ApolloCall<D: Operation.Data> (abstract)
@Deprecated("use toFlow")
fun executeAsFlow(): Flow<ApolloResponse<D>>
fun toFlow(): Flow<ApolloResponse<D>>

ApolloQueryCall<D: Query.Data>
suspend fun execute(): ApolloResponse<D>

ApolloMutationCall<D: Mutation.Data>
suspend fun execute(): ApolloResponse<D>

ApolloSubscriptionCall<D: Subscription.Data>
@Deprecated("use toFlow")
fun execute(): Flow<ApolloResponse<D>>
```

In a future version, we _may_ need to add `toPartialFlow` (for instance) to handle stream/defer...

**Comment by BoD** [comment]
About checking the return values, I dug a bit:
- there is a `CheckReturn` annotation in [Android](https://developer.android.com/reference/kotlin/androidx/annotation/CheckResult) but we probably don't want to depend on this
- there is an [issue](https://youtrack.jetbrains.com/issue/KT-12719) asking to add a similar one in Kotlin
- it looks like (see screenshot) any annotation named `*CheckReturnValue` would trigger the warning in IntelliJ/AS
- Rx [did this](http://reactivex.io/RxJava/3.x/javadoc/3.1.0/io/reactivex/rxjava3/annotations/CheckReturnValue.html) for instance so we could do this ourselves too

<img width="736" alt="Screen Shot 2021-11-23 at 11 18 45" src="https://user-images.githubusercontent.com/372852/143008389-4a9832f8-b2ff-430f-ac99-a8db5f5df1cb.png">

**Comment by martinbonnin** [comment]
+ 1 on **not** depending on Android annotations.

Not strong opinion about having `ApolloCheckReturnValue`. Let's wait until we have a question/use case before adding it?

**Comment by BoD** [comment]
Closing per #3594
