### ISSUE TITLE
Get the complete response header of ApolloClient 

### ISSUE THREAD

**Issue by mdorreh** [apollographql/apollo-android#3508]
I need to get the **trace-id** from the response header when I request with apolloClient but it seems the response header is missing something here is my ApolloClient: 
```
fun getApolloClient(token: String = ""): ApolloClient {
        val okHttpClient = OkHttpClient.Builder()
            .addInterceptor(AuthorizationInterceptor(token))
            .build()
        return ApolloClient.builder()
            .serverUrl(BuildConfig.BASE_URL)
            .okHttpClient(okHttpClient)
            .build()
    }
```
and this is how to get the response header: 
```
val response = HomeRequestBodyWithoutAuthQuery(lat.toDouble(), long.toDouble(), Input.fromNullable(true)).let{
            api.getApolloClient()
                .query(it)
                .await()
        }

        val httpContext = response.executionContext[OkHttpExecutionContext.KEY]
        Log.i("apolloheader","response Header: ${httpContext?.response?.headers()?.toString()?: ""}")
```
but after getting logs I receive the following log:
```
response Header: Access-Control-Allow-Credentials: true
    Access-Control-Allow-Origin: *
    Content-Type: application/json; charset=utf-8
    Date: Mon, 08 Nov 2021 12:35:28 GMT
    ETag: W/"21a7-B7850wfFe+d/Cn62hUTnKQRvvy0"
    Vary: Accept-Encoding
    Connection: keep-alive
```
although I expect the following that get from network browser:

```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Date: Mon, 08 Nov 2021 11:12:00 GMT
ETag: W/"ab-xpxvmYmhvLHf8RPbX7HE9ku6f7Q"
x-trace-id: 967ee9fd-93ff-4ab8-a17f-6f085853f306
Content-Length: 171
Connection: keep-alive
```
I don't know why there is no **x-trace-id** in the response header from apollo.

**Comment by martinbonnin** [comment]
Hi 👋  Thanks for reaching out ! 

> I expect the following that get from network browser

Are you using the [Android Studio network profiler](https://developer.android.com/studio/profile/network-profiler)? Or something else? 

> I don't know why there is no x-trace-id in the response header from apollo.

That's intriguing indeed, especially since the other headers seem to be present... My first thought would be that maybe `x-trace-id` is a "tooling-specific" header that's not present on the network wire? If you control the backend, can you try to rename it to something else and see if it changes?

**Comment by mdorreh** [comment]
Hi, the answer to your first question is no. I took the second header from my chrome browser.
And for your next question, I should consult with our backend developer. Let me ask him and I get back to you.

**Comment by martinbonnin** [comment]
> I took the second header from my chrome browser.

Is this using Apollo Android or using Apollo Web ? If it's Apollo Web, I'd recommend setting up a HTTP proxy like Charles Proxy to compare similar things

**Comment by mdorreh** [comment]
I'm surprised that I changed the query to another one and I got the trace-id in this request but still not in the first query:
```
response Header: Access-Control-Allow-Credentials: true
    Access-Control-Allow-Origin: *
    Content-Type: application/json; charset=utf-8
    Date: Mon, 08 Nov 2021 13:27:39 GMT
    ETag: W/"33b7-ydWiyUJz+tOSA5E1cvh7QCn0lxo"
    Vary: Accept-Encoding
    x-trace-id: ff170a01-a264-4c04-867f-9db3e4e0ab35
    transfer-encoding: chunked
    Connection: keep-alive
```

**Comment by mdorreh** [comment]
@martinbonnin My bad!!! we have three environments and the first request in the stage environment has no trace -id and I took the trace id from the chrome browser from the dev environment. Please forgive me for bothering you. I really apologize.

**Comment by martinbonnin** [comment]
No problem, glad you got your issue resolved 🎉
