### ISSUE TITLE
Allow queries to be excluded from particular caches

### ISSUE THREAD

**Issue by davidalbers** [apollographql/apollo-android#3540]
**Is your feature request related to a problem? Please describe.**
I have an in-memory LRU cache chained to an on-disk SQL cache:

```
LruNormalizedCacheFactory(evictionPolicy = evictionPolicy).chain(SqlNormalizedCacheFactory(applicationContext))
```

Most of the time I want this because I want most queries saved to disk. However, there are some queries I only want in the in-memory cache.

As an example, we show informational banners in our app. It makes sense to cache those in-memory so they don't constantly reload when navigating between screens. However, it's not necessary to keep them on disk since the information changes frequently. In fact, it could be a bug if the user sees a cached notification from 6 months ago.

**Describe the solution you'd like**
I'd like a cache header that skips the `SqlNormalizedCacheFactory`. I'm thinking along the lines of `DO_NOT_STORE` but more specific

```
val cacheHeaders = CacheHeaders.builder()
    .addHeader(DO_NOT_STORE, SqlNormalizedCache.key)
    .build()
client.query(exampleQuery).toBuilder()
    .cacheHeaders(cacheHeaders)
    .build()
```

Though I could see a few different solutions here and open to anything that helps the original problem.

**Comment by BoD** [comment]
I'm thinking out loud here but I'm wondering if the ability to set an expiration date on cached models would also be a possible path to achieve your use-case?

**Comment by davidalbers** [comment]
Yes, that could work too. This is a good point since it clarifies what I'm looking for. 
The root issue is these "timely" notifications shouldn't be kept permanently while other queries should be kept.

**Comment by martinbonnin** [comment]
Expiration definitely sounds like something that would help here. That's on the roadmap but requires some work though. In the short term, you can always implement your own `NormalizedCache` that has custom headers. Something like:

```kotlin
  class MyCache(val delegate: NormalizedCache): NormalizedCache() {
    override fun merge(record: Record, cacheHeaders: CacheHeaders): Set<String> {
      if (cacheHeaders.hasHeader("DO_NOT_STORE_SQLITE")) {
        return emptySet()
      }
      return delegate.merge(record, cacheHeaders)
    }

    override fun merge(records: Collection<Record>, cacheHeaders: CacheHeaders): Set<String> {
      if (cacheHeaders.hasHeader("DO_NOT_STORE_SQLITE")) {
        return emptySet()
      }
      return delegate.merge(records, cacheHeaders)
    }
  // ...
}
```

**Comment by martinbonnin** [comment]
I'm going to close this one as the solution above should work for the specific problem of exclude some queries from the SQLite cache.

For the more global expiration problem, I just opened https://github.com/apollographql/apollo-android/issues/3566
