### ISSUE TITLE
Apollo kotlin multiplatform caching?

### ISSUE THREAD

**Issue by boldijar** [apollographql/apollo-android#3544]
I'm looking all over this repository trying to find if is possible to use cache features when using apollo with kotlin multiplatform.

Is there a example somewhere, or is just not possible yet?

I'm using Apollo3-beta1 with multiplatform.

**Comment by martinbonnin** [comment]
Yep, you can use the Normalized Cache in multiplatform ([docs](https://www.apollographql.com/docs/android/v3/caching/normalized-cache/)).

The HTTP cache is JVM only so far ([docs](https://www.apollographql.com/docs/android/v3/caching/http-cache/))

**Comment by boldijar** [comment]
How is this supposed to work?
I've added the cache as in the documentation
```
 val apolloClient = ApolloClient.Builder()
        .normalizedCache(MemoryCacheFactory(maxSizeBytes = 10 * 1024 * 1024))
        .addCustomScalarAdapter(UUID.type, UuidAdapter())
        .addCustomScalarAdapter(DateTime.type, LocalDateTimeAdapter())
        .networkTransport( ....

```

And calling the queries like this

```
suspend fun getLeaderboard(cacheOnly:Boolean): LeaderboardModel {
        val query = LeaderboardQuery()
        val response = client.query(query).fetchPolicy(if (cacheOnly)FetchPolicy.CacheOnly else FetchPolicy.CacheFirst).execute().awaitThrowError()
        return UserMappers.leaderboardMapper.convert(response.leaderboard)
    }
    ```
    For some reason after calling the request cache first a few times, and expecting the cache to be saved, calling this method with cache only will give me an error.
    com.apollographql.apollo3.exception.CacheMissException: Object 'QUERY_ROOT' has no field named 'leaderboard'
    
    So how I make sure the cache is saved?

**Comment by martinbonnin** [comment]
Hi 👋 !
That's supposed to work indeed. Can you dump the cache after the `CacheFirst` request to make sure data made it through? From https://www.apollographql.com/docs/android/v3/caching/troubleshooting/, you can dump the cache with:

```kotlin
val dump = apolloClient.apolloStore.dump()
NormalizedCache.prettifyDump(dump)
```

**Comment by boldijar** [comment]
After cache first
```
 OptimisticCache {}
    MemoryCache {
      "leaderboard" : {
        "totalAssignments" : 80
        "completedAssignments" : 43
        "score" : 4050
        "scores" : [
          5750
          4750
          4700
          4600
          4550
          4300
          4200
          4100
          4050
          3800
        ]
      }
    
      "QUERY_ROOT" : {
        "leaderboard" : CacheKey(leaderboard)
      }
    }
```

Now cache only:

 com.apollographql.apollo3.exception.CacheMissException: Object 'QUERY_ROOT' has no field named 'leaderboard'

**Comment by martinbonnin** [comment]
That's weird. Looks like your cache has everything 🤔 .

You can start by putting a breakpoint when the `CacheMissiException` is thrown: https://github.com/apollographql/apollo-android/blob/09e654447c87dd8c4177b796c590878ce8ee380d/apollo-normalized-cache-common/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/internal/CacheBatchReader.kt#L97

Alternatively, if you can put a small reproducer somewhere, I'll look into it. There has to be something we're missing

**Comment by boldijar** [comment]
![image](https://user-images.githubusercontent.com/7826299/141488693-9877877d-353d-46b2-a23a-eaf88bec8760.png)
Actually this is the place where the cache exception is thrown

**Comment by martinbonnin** [comment]
Double checking, is there any chance you could have 2 different `ApolloClient` instances?

**Comment by boldijar** [comment]
Yes, I do have 2 apollo client instances, but I'm pretty sure I'm using for this the one with the cache settings. Is there a problem?

**Comment by martinbonnin** [comment]
It's fine to use 2 `ApolloClient` instances but caching only works if the queries are made on the same instances. If that's the case then it's something else. It's worth double checking the hashCode though, making sure that it's the same for every call.

**Comment by boldijar** [comment]
Where is the hashcode?

**Comment by martinbonnin** [comment]
That's the number in the debugger next to the object. Or I think you can call `apolloClient.hashCode()` on it too. If it's the same number, it's almost guaranteed to be the same instance.

**Comment by boldijar** [comment]
Thank you for your help, you're right, the problem was on the client side, for some reason the whole KMM class that holds the apollo connection was recreated for each call.

**Comment by martinbonnin** [comment]
Nice, thanks for the update!

**Comment by boldijar** [comment]
@martinbonnin does this also have support for updating the cache manually?
similar to what works on react
https://www.apollographql.com/docs/react/caching/cache-interaction/

**Comment by martinbonnin** [comment]
It does have `readOperation`, `writeOperation`, `readFragment` and `writeFragment`. Look at `ApolloStore`: https://apollographql.github.io/apollo-android/kdoc/apollo-normalized-cache-common/com.apollographql.apollo3.cache.normalized/-apollo-store/index.html

I'm less familiar with `cache.modify` but it should be possible too. If you share your use case, we can dive into this together.
