### ISSUE TITLE
Default value for `generateOptionalOperationVariables`

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#3550]
Decide a default value for `generateOptionalOperationVariables`. Currently, it is `false`, meaning that a query like this:

```graphql
# nullable variable
query GetHero($id: String) {
  hero(id: $id) {
    name
  }
}
```

will generate a class like this:

```kotlin
// Notice the absence of Optional<String?>
class GetHeroQuery(id: String?) {
  // ...
}
```

While this means easier and leaner callsites in the vast majority of cases, it doesn't work any more if omitting a variable is required:

```graphql
# bi-directional pagination
query GetHeroes(before: String, after: String)
```

Optional variables can be opted-in with `@optional`:

```graphql
# bi-directional pagination
query GetHeroes(before: String @optional, after: String @optional)
```

But that's not always obvious. Also the query becomes Apollo Android specific as a server will not recognize `@optional`

**Comment by martinbonnin** [comment]
We decided to keep it like this because the vast majority of use cases will require a value. If omitting a value is required, it is possible through either the `@optional` directive (inside the query) or `generateOptionalOperationVariables.set(true)` in Gradle configuration. We will add a doc for that.

**Comment by BoD** [comment]
# Decision log

After some discussion (including with members of the `apollo-ios` team), we have decided to go back to make the default to generate Optionals, while keeping the ability to opt-out/in globally, or on a per-variable basis.

It is reminded that Optionals on operation variables may be needed in some cases, even though we estimate that it should be rare (or that needing them may reflect some kind of a bad practice on the schema).

Pros of generating Optionals **by default** are:
- it is "technically correct" per the GraphQL spec
- it will not be surprising/confusing to users who are used to GraphQL
- when it is needed, a user using the default configuration will **not** need to search the documentation (or use Google/StackOverflow/etc.)
- it is consistent with the `apollo-ios` behavior

Cons:
- this makes the generated code more verbose to use
- in most cases, the Optionals are actually not needed

In the end, a very good argument to keep Optional by default is this "matrix" by @martinbonnin (rephrased here):

- No Optional by default
    - User didn't want Optional => User is happy 🙂 
    - User needed Optional => User is unhappy 😡  (they may have wasted time looking for how to enable it)
- Optional by default
    - User didn't want Optional =>  User is neutral 😐  (they may have to understand the spec and why we did this, which is because it's allowed by the spec)
    - User wanted Optional => User is happy 🙂
