### ISSUE TITLE
Incorrect Variables Get Set When Running Multiple Concurrent Queries

### ISSUE THREAD

**Issue by simon-the-canadian** [apollographql/apollo-android#3554]
**Summary**
I have a single graphQL query that takes a start date and an end date for its variables. I'm using Rx Java to execute the query 3 times with different arguments. What I'm seeing in the network traffic is, once in a while, the variable values get mixed between the 3 queries. I have tried this with Kotlin Flow as well and I'm seeing the same thing. This only happens when I use `combineLatest` which runs the queries concurrently. I also have logged the variables when I get the response (`response.operation.variables().marshal()`) and those have the correct values. But in the network traffic, I can see that the variables are not correct.

**Version**
`apollo-runtime:2.5.10`
`apollo-rx2-support:2.5.10`
`apollo-coroutines-support:2.5.10`

**Description**
```
query getMemberLaborMetrics($metricsInterval: LaborMetricsInterval!, $startDate: Date!, $endDate: Date!) {
    memberLaborMetrics(end: $endDate, interval: $metricsInterval, start: $startDate) {
        ...MemberLaborMetricsFragment
    }
}
```

This is the function that makes the apollo call
```
    fun loadDataStream(timeRange: TimeRange<*>, metricsInterval: LaborMetricsInterval): Flowable<GetMemberLaborMetricsQuery.MemberLaborMetric> {
        val query = client.query(GetMemberLaborMetricsQuery(metricsInterval, timeRange.startTime(), timeRange.endTime()))

        return Rx2Apollo.from(query)
            .toFlowable(BackpressureStrategy.BUFFER)
            .map { response ->
                Timber.e(response.operation.variables().marshal()) // this logs the correct (expected) values
                response.data.memberLaborMetrics.firstOrNull()?.fragments?.memberLaborMetricsFragment
            }
    }
```

Here I'm executing the 3 queries
```
Flowable.combineLatest(
            loadDataStream(TimeRangeModel(clock.getDayStart(), clock.getDayEnd()), LaborMetricsInterval.CUSTOM),
            loadDataStream(week, , LaborMetricsInterval.CUSTOM),
            loadDataStream(currentPayPeriod, , LaborMetricsInterval.CUSTOM)
        ) { dayMetrics, weekMetrics, payPeriodMetrics ->
            Triple(dayMetrics.totalTime(), weekMetrics.totalTime(), payPeriodMetrics.totalTime())
        }
```

One work around I found is to build a new Apollo client for every query I make instead of having a singleton client. But I don't think that should be necessary, right? Another work around I found, is to just execute the 3 queries in their own thread.
This doesn't happen very often, seems like a race condition. I was able to verify that the request variables stored in the response are correct when the problem does occur, to rule out an issue with my app not setting the correct variables.

**Comment by simon-the-canadian** [comment]
Looking at the graphQL requests made in the network traffic, I'm wondering if it could be an issue with the custom types adapter. The startDate and endDate that I pass to `GetMemberLaborMetricsQuery()` are `Long` and I have a type convert that converts the Long epoch time stamp to an ISO string. 

```
class GraphqlTimestampAdapter: CustomTypeAdapter<Long> {
    @SuppressLint("SimpleDateFormat")
    private val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss").apply {
        timeZone = TimeZone.getTimeZone("UTC")
    }

    override fun encode(value: Long): CustomTypeValue<*> {
        val calendar = Calendar.getInstance(TimeZone.getTimeZone("UTC"))
        calendar.timeInMillis = value * 1000L

        return CustomTypeValue.fromRawValue(dateFormat.format(calendar.time))
    }

    override fun decode(value: CustomTypeValue<*>): Long = dateFormat.parse(value.value.toString())!!.time / 1000
}
```

**Comment by martinbonnin** [comment]
Looks like you found the issue. `GraphqlTimestampAdapter` is called from multiple thread ands `SimpleDateFormat` is not thread safe so returning sometimes inconsistent results. You'll need to lock the usages of `dateFormat`. Another option would be to create a separate instance of `SimpleDateFormat` every time but that sounds overkill

**Comment by simon-the-canadian** [comment]
Oh wow, lol. Thank you. I wish I would have realized that.
I'm glad it wasn't a bug in Apollo.

**Comment by martinbonnin** [comment]
Yep, that's a good catch. I didn't realize that either so that's definitely error prone. We'll add some extra documentation about this in the KDoc for future versions
