### ISSUE TITLE
Response body empty when HttpException thrown

### ISSUE THREAD

**Issue by mandrizzle** [apollographql/apollo-android#361]
Our GraphQL endpoint requires OAuth authentication. When we use the apollo client to hit our endpoint and our endpoint returns a status code of `401`, the apollo client throws an `HttpException` with a `okhttp3.Response` object. The problem is, before the exception is thrown, the `Response` is closed. This means when we try to read the body of the `Response` when we try to handle the exception, it is blank.  

This is from `ApolloParseInterceptor#parse` which is where the premature closure of the response happens:
```java
  Util.closeQuietly(response);
  throw new HttpException(response);
```

A solution to this could be to not to add a `Response` to the exception. We can instead create an immutable object, say `NetworkResponse` that has a `responseBody` and `responseCode` that we can add to the exception.

**Comment by BenSchwab** [comment]
How does following Retrofit's HttpException sound: 
https://github.com/square/retrofit/blob/bd8e38d406fff637ed69b1b312a8e439aa28b012/retrofit/src/main/java/retrofit2/HttpException.java

cc @sav007

**Comment by mandrizzle** [comment]
Looking at Retrofits usage of `HttpException` it seems like they don't close the response on error. Also I like the idea of adding a `statusCode` and `message` directly to the exception, assuming `message` is the body of the response.
