### ISSUE TITLE
Query execute prevents process from finishing in 3.0.0 beta 04

### ISSUE THREAD

**Issue by andreaskaltenbach** [apollographql/apollo-android#3619]
**Summary**
Using an Apollo Android Client and performing a query execute will make that the Java process never finishes.

**Version**
3.0.0 beta 04

**Description**

When running the following code, the Java process will terminate correctly with exit code 0:

```
fun main() = runBlocking {

    val apolloClient = ApolloClient.Builder()
        .serverUrl("https://www.google.com")
        .build()

    try {
        val query = apolloClient.query(OrganizationQuery(id = "232"))

//        uncomment line below and the process will never finish with exit code 0
//        val response = query.execute()

    } catch (ex:ApolloHttpException) {
        // Do not care about exceptions in this case :)
        println(ex.message)
    }
    apolloClient.dispose()
}
```
If I uncomment the line which performs the `query.execute()`, the Java program will never terminate. 

Note that I even have to call `apolloClient.dispose()` explicitly. Otherwise the Apollo Client will prevent the process from finishing as well.

Do `ApolloClient` and `ApolloQueryCall` have any resources that need to be cleaned up?

**Comment by martinbonnin** [comment]
One thing that comes to mind is the OkHttp threadpools.

Can you try passing an explicit OkHttpClient and releasing it as in https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/#shutdown-isnt-necessary

**Comment by andreaskaltenbach** [comment]
Thanks for the fast reply @martinbonnin . 
I added the okHttpClient and the cleanup calls in the end but I run into the same problem.

I even tested with Apollo Android 2.5.11 and it seems to be the same thing there.

**Comment by martinbonnin** [comment]
Yep, this rings a bell. Let me try quickly

**Comment by martinbonnin** [comment]
Nope, all seems to work here. Can you check https://github.com/martinbonnin/termination-test/tree/main and see if you can make it hang ?

**Comment by andreaskaltenbach** [comment]
Really strange. Your example is exiting properly. Will have to check what's different compared to my project setup.
Will let you know.
Thanks for your help!

**Comment by martinbonnin** [comment]
Sure thing! If you manage to hook a debugger, it might interesting to see what threads are still running.

Let us know what you find!

**Comment by andreaskaltenbach** [comment]
@martinbonnin I boiled it down to this dependency:
```
implementation("com.apollographql.apollo3:apollo-mockserver:3.0.0-beta04")
```

If I add it to my project, the Java process exits as it should. Removing the line from your project will make your main running forever as well.

Is this dependency adding something that the runtime dependency is not?

**Comment by martinbonnin** [comment]
Good catch! `mockserver` pulls a more recent version of OkHttp. Looks like `3.14.0` and later fixes this issue. 

You can workaround by adding an explicit dependency to your project:

```
dependencies {
  // anything higher than 3.14.0 will do. Might as well use latest
  implementation("com.squareup.okhttp3:okhttp:4.9.1")
}
```

We were discussing with @BoD the opportunity to update OkHttp. Looks like that settles it. Also OkHttp 3 [stop being supported in December 2021](https://square.github.io/okhttp/#requirements), yet another reason to update.

**Comment by martinbonnin** [comment]
Hi @andreaskaltenbach  👋 
Is it ok if we close this issue? `3.0.0-rc01` has the latest version of OkHttp so this should not happen again 🤞

**Comment by andreaskaltenbach** [comment]
Yes, that's fine. I'll update to `3.0.0-rc01` right away!

**Comment by AddictArts** [comment]
This is happening in the latest v3 stable release.

**Comment by BoD** [comment]
(Just a note that this is followed up in #3802 - leaving this one closed for now)
