### ISSUE TITLE
Subscriptions throw exception "java.lang.IllegalStateException: WeSocket queue full"

### ISSUE THREAD

**Issue by sproctor** [apollographql/apollo-android#3634]
**Summary**
Re-subscribing after app goes to sleep throws "java.lang.IllegalStateException: WeSocket queue full".

**Version**
3.0.0-beta04

**Description**
I'm not entirely sure the cause. It happens regularly when my app wakes up causing a crash. I didn't experience it with 2.5.x

Changes:

beta04
```kotlin
val client = ApolloClient.Builder()
            .okHttpClient(okHttpClient)
            .httpServerUrl(context.getString(R.string.graphql_endpoint))
            .webSocketServerUrl(context.getString(R.string.graphql_ws_endpoint))
            .addCustomScalarAdapter(Uuid.type, uuidAdapter)
            .addCustomScalarAdapter(Timestamptz.type, KotlinxInstantAdapter)
            .addCustomScalarAdapter(Numeric.type, BigDecimalAdapter)
            .build()
```

2.5.x
```kotlin
 val client = ApolloClient.builder()
            .serverUrl(context.getString(R.string.graphql_endpoint))
            .okHttpClient(okHttpClient)
            .subscriptionTransportFactory(
                WebSocketSubscriptionTransport.Factory(
                    context.getString(
                        R.string.graphql_ws_endpoint
                    ), okHttpClient
                )
            )
            .addCustomTypeAdapter(CustomType.UUID, uuidCustomTypeAdapter)
            .addCustomTypeAdapter(CustomType.TIMESTAMPTZ, dateCustomTypeAdapter)
            .addCustomTypeAdapter(CustomType.NUMERIC, numericCustomTypeAdapter)
            .build()
```

**Comment by sproctor** [comment]
Related issue from SO https://stackoverflow.com/questions/70008541/handle-network-error-when-using-graphql-subscription-with-apollo-on-android-with

**Comment by martinbonnin** [comment]
Thanks for sending this! I can reproduce. Will work on a fix.

In the meantime. You can copy/paste the [DefaultWebSocketEngine code](https://github.com/apollographql/apollo-android/blob/584d5a5ae94e6deb13568552bfa8d19f389ed588/apollo-runtime/src/jvmMain/kotlin/com/apollographql/apollo3/network/ws/OkHttpWebSocketEngine.kt) and remove the checks at line 86 and 93. And then pass it instead of the builtin `DefaultWebSocketEngine`. That should hide the issue.

I'll update this issue when a fix lands

**Comment by sproctor** [comment]
Sorry for the bad report. It was happening in 3.0.0-beta03 as well, I just hadn't tested enough to notice it. Thanks for your responsiveness to issues.

**Comment by martinbonnin** [comment]
Thanks for reporting them ! 
`beta05` is just out and has a quick fix for this. I'm not 100% clear what the implications are in terms of recovering from the error but at least it'll not crash. I'm keeping this issue open for now. Will update when I have a better understanding of what's going on

**Comment by sproctor** [comment]
I did some testing on 3.0.0-beta05 today. The crash is gone, but instead of crashing, subscriptions fail. I guess the okhttpclient is getting closed somewhere that it wasn't in 2.x. I don't think I've changed anything on my end that would create that behavior.

**Comment by sproctor** [comment]
3.0.0-rc1 seems to be working well for me. Thank you!
