### ISSUE TITLE
I can't generate java code in "generateApolloClasses"

### ISSUE THREAD

**Issue by soundofhorizon** [apollographql/apollo-android#3690]
**Question.**
I read this issue and try command "gradlew :generateApolloClasses".
https://github.com/apollographql/apollo-android/issues/1927

but got error below.
Task 'generateApolloClasses' not found in root project 'someProject'.

how I can fix this?

Similar to #1927, try command "./gradlew tasks", generateApolloClasses is existed.

**Comment by soundofhorizon** [comment]
now my project structure is here
https://gyazo.com/12d134232cf58521243a64ba5750503a

**Comment by martinbonnin** [comment]
Hi 👋!

If you're applying the `com.apollographql.apollo3`, you'll have to invoke the task in that subproject. If you `module` is named `app`, this is going to be something like:

```
./gradlew :app:generateApolloSource
```

Alternatively, Gradle has something called [task selectors](https://docs.gradle.org/current/userguide/command_line_interface.html#executing_tasks_in_multi_project_builds) that execute tasks in multiple subprojects automatically. In that case, you can just run:


```
# Note the absence of column
./gradlew generateApolloSource
```

And this will execute `generateApolloSource` in all subprojects that have it.

**Comment by soundofhorizon** [comment]
Thanks for replying!
I can execute command to doing ./gradlew :app:generateApolloSource 😄
