### ISSUE TITLE
Limit size of SQLStore

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#370]
Currently SQLStore will grow unbounded

**Comment by digitalbuddha** [comment]
Maybe instead of limit we give users an api to clear? Use case: our app should be caching searched for articles in an unbounded way. When a user signs out and a new user signs in we want to clear all the search articles that are cached. Not sure if that makes it complicated.

**Comment by BenSchwab** [comment]
Yeah, totally seems fair to add a `clear` capability.

We are hoping more of a LRU like SQLStore, where we set some acceptable size and store everything until it is reached, and have it auto-evicted. Hard to say what the average client will want, maybe `clear` is sufficient and we can just roll our own `CacheStore`

**Comment by BenSchwab** [comment]
This can be solved by:
clear
https://github.com/apollographql/apollo-android/pull/396

cache headers
https://github.com/apollographql/apollo-android/issues/326
