### ISSUE TITLE
ApolloPrefetch needs to have its own factory interface.

### ISSUE THREAD

**Issue by VisheshVadhera** [apollographql/apollo-android#390]
No need to have `prefetch()` in the `ApolloCall.Factory` interface as I feel that is not its concern at all. Instead we need to have a Factory interface in the ApolloPrefetch interface and move the `prefetch()` inside this one. This would also mean `ApolloClient` also implemeting `ApolloPrefetch.Factory` interface in addition to the `ApolloCall.Factory`.

**Comment by digitalbuddha** [comment]
Seems reasonable. Want to open PR?

**Comment by VisheshVadhera** [comment]
PR coming in a couple of hours!

**Comment by sav007** [comment]
@VisheshVadhera should we close this ticket? And pls in PR description use `Closes #` that after merging it will auto close issue

**Comment by VisheshVadhera** [comment]
I'll keep this mind. Thanks! And yeah we can close this issue.

**Comment by sav007** [comment]
Close via #391
