### ISSUE TITLE
Recommended approach for extension functions?

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#398]
Inevitably, we will need to add utility functions to data classes generated by Apollo. However, currently, the only option I see for these utility functions is a static class. This is unfortunate, for all the many reason static helper classes are disliked. 

I would much rather by able to extend an Apollo data class, and add the utility there. This could be very easy to achieve if codegen ran as an APT. For example:

```
@ApolloDataExtension
HeroExtension extends Hero {
  super(@Nonnull String name);
  
  public firstInitial() {
     return name.characterAt(0);
   }
}
```

Could be used to create a map of DataClass -> ExtensionClass (`{Hero -> HeroExtension`}), and then code-gen could simply swap out the the original extension class with original class. This seems nice because a response may be composed of many different data types, and not all may need extensions. Additionally, when an extension was added, no unnecessary refactoring would be needed because the extension extends the base type.

...But, I believe CodeGen is a gradle plugin and cannot access code annotations?

Would it be feasible to make CodeGen an APT processor?

 Does anyone else have any ideas of how to cleanly add extension logic without descending into utility function hell?

**Comment by BenSchwab** [comment]
Super hacky, but we I think we could have the groovy script run a regex on all .java source files search for @ApolloDataExtension and pull out the extension classname to map to the data class name.

**Comment by sav007** [comment]
So what the problem we want to solve with extension classes? Add some util functions?
If so then you can use delegate pattern (wrapper class), so for example above:
```
class HeroExtension {
  private final Hero hero;
 
  HeroExtension(Hero hero) {
    this.hero = hero;
  }

   public firstInitial() {
     return hero.name.characterAt(0);
   }
 
  ....
}
```

**Comment by BenSchwab** [comment]
Yes, the general problem is to add some utility function.

haha would love to use Kotlin, but not an option until buck support is add :(

The wrapper approach is okay, but I find wrappers to often be clunky, and suffer from the same general problems as util functions.  For example, the code will read some variant of:

```java
fullNameTextView.setText(hero.name);
firstInitialTextView.setText(new HeroExtension(hero).firstInitial);
```
Additionally, discovering the extension class is not straightforward.

This might just be a trade-off that has to be paid for getting model / request objects generated for free, but it feels like a downgrade from our REST client were the object that the response json is parsed into can have whatever utility logic makes sense:

```
java
public class Hero {
   @JsonProperty("name") public String name();
    
    public char firstInitial() {
         name.characterAt(0)
     }
}
```

**Comment by sav007** [comment]
There is another issue, how you will write extension for the class that doesn't exist. You can write extension on existing class. So in your example, Hero doesn't not exist until it generated:
```
HeroExtension extends Hero {
  super(@Nonnull String name);
  
  public firstInitial() {
     return name.characterAt(0);
   }
}
```
So we are looking to running generation twice, first we generate Hero. Second we scan for extension class and regenerate Data to swap Hero to HeroExtension, that seems over engineering.

As for the wrapper you can wrap it early and work with wrapper class:
```
HeroExtension heroExtentsion = new HeroExtension(hero);
Or wrap it on data layer and return the HeroExtension class
...
fullNameTextView.setText(heroExtentsion.hero.name);
firstInitialTextView.setText(heroExtentsion.hero.firstInitial);
```

**Comment by BenSchwab** [comment]
Even if wrapping earlier, the wrapping code bifurcates properties:
 
```java
HeroExtension heroExtentsion = new HeroExtension(hero);
fullNameTextView.setText(heroExtentsion.**hero**.name);
firstInitialTextView.setText(heroExtentsion.firstInitial);
```

The important difference being that you now have two objects you have to search for relevant properties. This may seem minor, but we have data classes with dozens of helper functions.

Also, there is no need to run code generation twice. It would be a source annotation. You can scan source files for `@ApolloDataExtension` _before_ generating code: 

```
@ApolloDataExtension
HeroExtension extends Hero {
}
```
Just produces a string map entry of  `package.Hero` to  `package.HeroExtensions`. It doesn't matter if `package.Hero` has been generated yet. This map can then be used during code gen to re-map where appropriate in one pass.

Granted the developer would likely want to run generation before writing the extension class to get autocompletion. But I would imagine a general flow would default to not use extensions until you need to add utility function, so usually the non-extension class would already exist.

**Comment by sav007** [comment]
> Granted the developer would likely want to run generation before writing the extension class to get autocompletion. But I would imagine a general flow would default to not use extensions until you need to add utility function, so usually the non-extension class would already exist.

Yeah that is valid point. 

Looks fine, and as you mentioned we can scan source code with plugin and build this map.

**Comment by BenSchwab** [comment]
Okay, I'll prototype this, and see how it feels

Not fully convinced that this is the proper road to go down, but should be an interesting experiment non-the-less

**Comment by BenSchwab** [comment]
https://github.com/apollographql/apollo-android/issues/400
