### ISSUE TITLE
Finding out if current request is a query or mutation at interceptor level

### ISSUE THREAD

**Issue by boldijar** [apollographql/apollo-android#4194]
For my current backend, the client needs to send a special header to let the backend know if it's a mutation or a query, before the backend reads the content.
I've been trying to look into the source code and the only place I found this might be possible is DefaultHttpRequestComposer but it's final, and can't be overriden.

Also, been trying to do this in an interceptor, but I am not sure how to get this data from the request.

Thank you!

**Comment by BoD** [comment]
Hi!

Yes, `HttpRequestComposer` is a good way to do this. It is final but can still be used by composition like this:

```kotlin
private class MyHttpRequestComposer(url: String) : HttpRequestComposer {
    private val defaultHttpRequestComposer = DefaultHttpRequestComposer(url)

    override fun <D : Operation.Data> compose(apolloRequest: ApolloRequest<D>): HttpRequest {
        var httpRequest = defaultHttpRequestComposer.compose(apolloRequest)
        if (apolloRequest.operation is Mutation) {
            httpRequest = httpRequest.newBuilder()
                .addHeader("header-name", "header value")
                .build()
        }
        return httpRequest
    }
}
```

Then set it on your client like so:
```kotlin
    val apolloClient = ApolloClient.Builder()
        .networkTransport(
            HttpNetworkTransport.Builder()
                .httpRequestComposer(MyHttpRequestComposer("https://..."))
                .build()
        )
        .build()

```
