### ISSUE TITLE
Gradle plugin should clear stale files

### ISSUE THREAD

**Issue by hzsweers** [apollographql/apollo-android#424]
I've noticed that if I change a file's location (or just plain remove it!) and regenerate, the old files are still there and available until I clean again.

**Comment by martinbonnin** [comment]
Is there a "standard" way to do this ? Or should the plugin just remove all its files before generating new ones ?

**Comment by digitalbuddha** [comment]
Im not convinced that this is different than how java does it. I would assume incremental complication means only being additive. You also have studio caching to think about. I've changed dependency versions and studio cache still shows last version present too.

**Comment by martinbonnin** [comment]
I guess we should also handle `inputs.removed()` there: https://github.com/apollographql/apollo-android/blob/345ac93b43b949c61975e83b93ddc277447816ca/apollo-gradle-plugin/src/main/java/com/apollographql/apollo/gradle/ApolloClassGenTask.java#L39 ?

**Comment by hzsweers** [comment]
ping on this, as it's really frustrating when changing branches

**Comment by ZacSweers** [comment]
actually I think it might be related to build cache, as it continues to try to use this previous state even on subsequent generations

**Comment by ZacSweers** [comment]
confirmed - when I run with `--no-build-cache` it builds successfully
