### ISSUE TITLE
Testing support for ApolloClient

### ISSUE THREAD

**Issue by VisheshVadhera** [apollographql/apollo-android#430]
@digitalbuddha on slack suggested something like this: 

`MockApolloClient.addResponse(jsonStream).build()`

Instead of pulling in Json from other graphql tools it would be nice if we can feed the response directly into the apolloClient which can then return mock responses.

**Comment by sav007** [comment]
I guess we should take a look at https://github.com/square/retrofit/tree/master/retrofit-mock

**Comment by digitalbuddha** [comment]
I'm not sure if that is right pattern. Retrofit uses proxy methods to
implement an interface. Okhttp does not have that same setup. Maybe
something there though...

**Comment by CristianGM** [comment]
Why not using: https://github.com/square/okhttp/tree/master/mockwebserver ?
( we prefer WireMock but it's heavier )

**Comment by digitalbuddha** [comment]
That's what we're doing now but it would be nice to have first class
testing support for stunning responses.

**Comment by AdamMc331** [comment]
Any updates on how we can do this? I've been trying to find a way to stub responses with mockito and a JSON file I've saved but I can't quite pull this off. I could try MockWebServer but I agree some more first class support for stubbing would be nice.

**Comment by AdamMc331** [comment]
I suppose without the JSON file this is helpful: https://github.com/apollographql/apollo-android/issues/678
