### ISSUE TITLE
Cache Fetch Strategy / Cache Header unification proposal

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#432]
Apollo Client has two levels of caching:

- Response cache
- Normalized cache

Each level has their own `CacheControl` (`HttpCacheControl` and `CacheControl`, respectively). HttpCache also has a basic concept of response headers, and the normalized cache may need something similar.

Inherently, having two caches is complex, and many users may only choose to use one. However, the similarity but minor differences between the two cache types will cause confusion. Additionally, we have designed the Apollo caches to be user configurable. For this to be useful, it must be very clear what the responsibility of a custom cache implementation is. 

The first proposal is to separate "FetchStrategy" from "CacheHeaders".

`FetchStrategy` control where data is looked up. These will include:

 ``` 
CACHE_FIRST,

  CACHE_ONLY,

  NETWORK_FIRST,

  NETWORK_ONLY
```

`CacheHeaders` control *how* a response is cached/and or read. For example, a request may include 'offline-critical'. This indicates that this response should be kept around longer than non `offlineCritical` responses. Another common example may be `no-cache`. `no-cache` is different from a fetch strategy, as we may want to use it with any of the above strategies. The difference is with `no-cache` we will not write the response to the cache. We can canonize some of these as standard headers -- but in general we should keep these light. If someone has a specific use case, they can pass in that header, and implement a cache to handle it.

`CacheHeaders` are intentionally designed to be generic (Map of strings internally). This is because they operate on the user configurable cache. 

Conversely, `FetchStrategies` are designed to be closed. They operate in the main logic of ApolloClient, and cannot be configured by user.

One tricky concept with this design is the concept of staleness, as it bridges between `CacheHeaders` and `FetchStrategies`. A cache has every ability to determine staleness based on internal configuration, and `CacheHeaders`. Therefore, a cache will essentially return a tuple:
`<@nullable response, isStale>`.  To drive this home, all a specific cache implementation is is a function: `(CacheHeaders, key) --> <response, isStale>` 

Semantically, if a response isStale it should *not* be returned to the user as a response. However, in the case that the network fails, it is may be desired to return stale data. This logic must be baked into the core apollo client. Therefore, we can include a boolean flag with the fetchStrategy, such as `builder.setFetchStragegy(CACHE_FIRST, shouldUseStaleDataOnError)`.
 
The last concept is eviction. I believe that this should *not* be standardized across http cache and normalized cache, as there are inherent differences between how we may want to evict. A cache should initialized with an appropriate eviction policy. `normalized.lru.evictionpolicy` is a good example.

--------- 

What changes this would entail:

- HTTP cache will loose these two "CacheControl". 

```
  /**
   * Signals the apollo client to first fetch the data from the network request. If the network request fails, then the
   * data is fetched from the http cache even if it has become stale.
   */
  NETWORK_BEFORE_STALE("network-before-stale"),
  /**
   * Signals the apollo client to mark the data in the cache stale whenever a read takes place next.
   */
  EXPIRE_AFTER_READ("expire-after-read");
```

These seem like good changes because I may want to use stale data both in CACHE_FIRST and NETWORK_FIRST. Now, state behavior will be controlled by a boolean.

 `EXPIRE_AFTER_READ` should be configured directly on the instance of the cache, as it is an implementation detail of that cache. I may want to use EXPIRE_AFTER_READ and CACHE_ONLY, currently this is not possible.

- `NormalizedCache` will return `RecordResposne read(String key)` where `RecordResponse` contains `isStale`.
- `ResponseCacheRecord` will have a `isStale` field.

**Comment by BenSchwab** [comment]
@sav007 @digitalbuddha @marwanad And all other contributors, lmk what you think.

**Comment by sav007** [comment]
>Semantically, if a response isStale it should not be returned. However, in the case that the network fails, it is may be desired to return stale data. This logic must be baked into the core apollo client. Therefore, we can include a boolean flag with the fetchStrategy, such as builder.setFetchStragegy(CACHE_FIRST, shouldUseStateDataOnError).

Why we can't have `NETWORK_BEFORE_STALE` one of `FetchStrategies`? That actually the fetch strategy, right?

`EXPIRE_AFTER_READ` I believe should go to default `CacheHeaders`

**Comment by BenSchwab** [comment]
1. We could have `NETWORK_BEFORE_STALE`, but we would also have to add `CACHE_FIRST_THEN_NETWORK_BEFORE_STALE`. The wordiness turns me off, but maybe we can come up with a better name.

2. 

> EXPIRE_AFTER_READ
 I believe should go to default CacheHeaders. 
> 

Agreed.

> Am I right that we will have the same FetchStrategies for both http and normalized caches?
> 
Yes.

> So who will use this flag isStale. 

- As mentioned above, we technically want to be able to have a variant CACHE_FIRST to have the same behavior. Thus, the boolean flag.

Regarding the design
```
cache.read(cacheKey)
cache.readStale(cacheKey)
```
seems like it is a little harder on implementations as the two methods will have a lot of simularity. of course, this can be solved by a level of indirection in the implementation, but seems better to have just one method that returns whether or not the response is stale.

**Comment by sav007** [comment]
Another point.

Right now when user constructs `HttpCache` he provides the `EvictionStrategy` (probably not best name for this) that actually checks if cached response is stale or not.

For normalized cache we have `com.apollographql.apollo.cache.normalized.lru.EvictionPolicy` that represents the configuration for `com.nytimes.android.external.cache.Cache`.

So the question/suggestion can we merge these 2 classes and use `EvictionPolicy` for checking if cache is stale or not. `EvictionPolicy.expireAfterAccess`, `EvictionPolicy.expireAfterWrite` should be enough to say if cached response is stale or not.
