### ISSUE TITLE
Proposal: introduce ApolloCallCanceledException

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#448]
If Apollo call is canceled in the middle of reading response from `okhttp3.Response#body` it will close the connection and throw `throw new IOException("Canceled");` that will be wrapped into `ApolloParseException` that seems not right.

Proposing to introduce `ApolloCallCanceledException` that will be thrown any time when call has been canceled during call execution.

**Comment by sav007** [comment]
cc @BenSchwab @digitalbuddha @marwanad @kassim @VisheshVadhera

**Comment by digitalbuddha** [comment]
Lgtm

**Comment by kassim** [comment]
Sounds good
