### ISSUE TITLE
builder not generated when no request parameters for a query

### ISSUE THREAD

**Issue by commonsguy** [apollographql/apollo-android#449]
Some GraphQL causes Apollo-Android to not code-generate `builder()` on a query Java class. The attached sample project illustrates this. It is a new Android Studio project, from the new-project wizard, with:

- `0.3.0` of the Apollo-Android plugin
- `schema.json` from `apollo-codegen download-schema https://graphql-demo.commonsware.com/0.1/graphql --output schema.json`
- this GraphQL document:

```
query getAllTrips {
  allTrips {
    id
    title
    startTime
    priority
    duration
    creationTime
  }
}
```

The resulting `GetAllTrips.java` generated file does not have a `builder()` method, which seems to run counter to the documentation.

Note that if I substitute the `schema.json` and the `GithuntFeedQuery.graphql` from the `apollo-sample` project, that *does* get a `builder()`, even for this same project. So, it's something about the schema JSON and/or the GraphQL that would appear to be the source (pun lightly intended) of the difficulty.

I can also reproduce this with `0.3.1-SNAPSHOT``, FWIW, though for the attached sample, I wanted to stick to non-snapshot code.

[NoBuilder.zip](https://github.com/apollographql/apollo-android/files/952928/NoBuilder.zip)

**Comment by digitalbuddha** [comment]
Hi Mark, this is something we need to document better. If there are no request parameters one can simply do `new getAllTripsQuery()` rather than `getAllTripsQuery.builder()`. Feel free to add a blurb to the readme for clarity.

**Comment by commonsguy** [comment]
OK, that works &mdash; thanks!

With respect to my adding a blurb... to be honest, I wouldn't know what to do at this junction. `builder()` is not documented, so I do not know where to document the non-`builder()` scenario.

**Comment by digitalbuddha** [comment]
No problem! I'll add something to readme tonight about both variants
