### ISSUE TITLE
Apollo subscriber/observer

### ISSUE THREAD

**Issue by mattfred** [apollographql/apollo-android#450]
I'm attempting to setup Apollo using a subscriber/observer pattern. However, the `onComplete` method is never called. `onNext` is the only thing that is ever called, and it is called once.  Am I missing something?

    // Setup client
    public void init() {
    scheduler = Schedulers.io();
    observeOnScheduler = AndroidSchedulers.mainThread();
    final String BASE_URL = "https://githunt-api.herokuapp.com/graphql";
        apolloClient = ApolloClient.builder()
                .serverUrl(BASE_URL)
                .okHttpClient(okHttpClient)
                .build();
    }

    // Setup Subscription
    public Subscription getFeed() {
    final FeedQuery feedQuery = FeedQuery.builder()
                .type(FeedType.HOT)
                .build();

        ApolloWatcher<FeedQuery.Data> apolloWatcher = apolloClient.newCall(feedQuery).watcher();

        RxApollo.from(apolloWatcher)
                .observeOn(observeScheduler)
                .subscribeOn(scheduler)
                .flatMap(new DataToFlatMap())
                .subscribe(new DataListenerSubscriber());
    }

    private class DataListenerSubscriber extends Subscriber<List<Item>> {
        private List<Item> items;

        @SuppressWarnings("ConstantConditions")
        @Override
        public void onCompleted() {
            Timber.e("Got data!");
        }

        @Override
        public void onError(Throwable e) {
            Timber.e(e.getMessage(), e);
        }

        @Override
        public void onNext(List<Item> items) {
            Timber.e("On Next");
        }

**Comment by digitalbuddha** [comment]
Hello! Thank you for using library. ApolloWatcher is an endless subscription. I think what you want is to wrap an ApolloCall in RxApollo

**Comment by mattfred** [comment]
Can you give me an example of how to do this?

**Comment by mattfred** [comment]
This did fix my issue. Thank you for your quick response.

**Comment by digitalbuddha** [comment]
Converting ApolloCall to a Single:

//Create a query object
EpisodeHeroName query = EpisodeHeroName.builder().episode(Episode.EMPIRE).build();

//Create an ApolloCall object
ApolloCall<EpisodeHeroName.Data> apolloCall = apolloClient.newCall(query);

//RxJava1 Single
Single<EpisodeHeroName.Data> single1 = RxApollo.from(apolloCall);

//RxJava2 Single
Single<EpisodeHeroName.Data> single2 = Rx2Apollo.from(apolloCall);

single1.subscribe(observer) 
single2.subscribeWith(disposableObserver)

**Comment by Ninjaman494** [comment]
@digitalbuddha Where is that code form? `Rx2Apollo.from` returns an `Observable` for `ApolloCall` objects. Is there some other way to get a `Single` from a call?
