### ISSUE TITLE
Introduce store custom resolver

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#451]
Overview of solution:
http://dev.apollodata.com/react/cache-updates.html#cacheRedirect

First step is to be able read cached response for query directly from store.

**Comment by sav007** [comment]
@martijnwalraven could you please share how this works on iOS if it's implemented

**Comment by sav007** [comment]
@BenSchwab @digitalbuddha @helfer I would love to hear any comments / suggestions.

**Comment by sav007** [comment]
Here is some thoughts.

To be able read cached response for operation we need just substitute the way how resolved root cache record for this operation.

#### Step 1
Introduce custom `cacheKey` in `ApolloCall` that will be used in `ApolloCacheInterceptor` where cached root record is being resolved. 

So instead of:
```java
Record rootRecord = cache.read(CacheKeyResolver.rootKeyForOperation(operation).key());
```

To have smth like this:
```java
Record rootRecord;
if (operation has custom cacheKey) {
 rootRecord = cache.read(operation.cacheKey());
} else {
 rootRecord = cache.read(CacheKeyResolver.rootKeyForOperation(operation).key());
}
```

To pass custom cache key to cache interceptor along with operation object we need to introduce internally `Request` object that will be passed between interceptors and it will incapsulate `operation`, `cacheKey`, `cacheHeaders`, `cachePolicy` etc.

#### Step 2
Calculation of cache keys for operation is done as part of parse process inside `ApolloParseInterceptor`.  So why not to use this and simplify the way how user provides this custom `cacheKey`.  

So let say user from the response of this query:

```graphql
query ListView {
  books {
    id
    title
    abstract
  }
}
```
would be able to easily extract cache key (that has been already calculated during parsing):
```java
cacheKey  = response.data.listView.books[0].cacheKey
```

and pass this key as the custom cache key to the detail query:
```graphql
query DetailView {
  book(id: $id) {
    id
    title
    abstract
  }
}
```

In this case we just need to decide how we can store calculated cache keys for parsed response data and provide access to to them.

**Comment by digitalbuddha** [comment]
I'll look over some more. One comment after reading intro. Rather than if (operation has custom cacheKey) {
 rootRecord = cache.read(operation.cacheKey());
} else {
 rootRecord = cache.read(CacheKeyResolver.rootKeyForOperation(operation).key());
}

We should have a default cacheKeyResolver that a use can override. Code would flow nicer.

**Comment by digitalbuddha** [comment]
Ignore my last comment. I misunderstood what you were trying to portray.

**Comment by BenSchwab** [comment]
I don't think I quite follow the idea of allowing the user to pass in the cache key to the detail query. This seems like a burden to the client to make sure they are associating the proper cache key with the detail id (which seem to be both dynamically set), and they would need to do this everytime they make the detail query.

I feel like this needs to be more automatic, and configured once -- i.e. a resolver function like the JS client.

Here's a pretty direct translation of the JS architecture:

We inject `CacheFieldValueResolver` with a set of `CustomResolver` that are configured on `ApolloClient`.

Rough code sketch:
```java
public class CustomResolver {

 abstract class Resolver {
  @Nullable CacheReference resolve(Arguments arguments) { return null};
  @Nullable List<CacheReference> resolveList(Arguments arguments){return null};
 }

 public (String typeFilter, Resolver resolver) {
  ...
 }

}
```

use:

```java

 apolloClient = ApolloClient.builder()
        .serverUrl(BASE_URL)
        .okHttpClient(okHttpClient)
        .normalizedCache(normalizedCacheFactory, cacheKeyResolver)
        .withCustomResolver(new CustomResolver("book", new Resolver({
           @Override
            public void resolve(Arguments arguments) {
                  if (arguments.get("id") != null) {
                      return CacheKey.from("book." + arguments.get("id"));
                  }
                  return null;
            }
          }))
        .build();
```

Then inside `CacheFieldValueResolver` for rootQueries, we give the customResolver's a chance to resolve, before defaulting the normal code.

We should also unify names, and rename `CacheKeyResolver` to `dataIdFromObject` etc.

**Comment by sav007** [comment]
@BenSchwab 

I looked at JS example and I don't like the idea of this:
```java
if (arguments.get("id") != null) {
                      return CacheKey.from("book." + arguments.get("id"));
                  }
```

That seems to much to expect from user as he must know how our response normalization works. 
And how about formatting this kind of cacheKey `hero(episode:JEDI)`.  
I believe this code is literally taken from the `ResponseNormalizer`. 
So without looking into the code of `ResponseNormalizer` how user knows how to correctly  format `CacheKey` ?

And when we parse the response list of, for example, books, we already resolved all cache keys for objects. So why not use this fact and make user's life easier with this:
```java
call.cacheKey(response.data.books.get(10).cacheKey)
```

In this case user don't know the format of keys used in response normalization process.

**Comment by BenSchwab** [comment]
> call.cacheKey(response.data.books.get(10).cacheKey)

But what guarantees that the user has access to the call that made the list? (`response.data.books`). Yes, the call needs to be have been run at *some* point, but what if this is many screens later? What if user visits parent screen, and then deep links into child screen later? 

> That seems to much to expect from user as he must know how our response normalization works.
And how about formatting this kind of cacheKey hero(episode:JEDI).

I could be wrong, but I feel like this is mainly only going to be used in cases where the object has a proper id (generally, response normalization only works in the case of a proper id). The actual JS example is better than my example:

```
customResolvers: {
    Query: {
      book: (_, args) => toIdValue(dataIdFromObject({ __typename: 'book', id: args['id'] })),
    },
```
Here we see that the call delegates to the `dataIdFromObject` function (we currently call `CacheKeyResolver`). We could definitely setup some plumbing to strongly group these two concepts closely together.

What if we had this restriction:

- A `CustomResolver` *has* to call `dataIdFromObject/cacheKeyResolver`. User just has to move arguments into a fieldBlob, which `cacheKeyResolver` expects.

**Comment by sav007** [comment]
@BenSchwab 

> But what guarantees that the user has access to the call that made the list? (response.data.books). 
Well he can always pass the CacheKey object down to the details screen, right?

So if user specifies global custom resolver, does it mean we will always use this cache key for reading/writing records for book object?

 `{ __typename: 'book', id: args['id'] }` I feel this is pure JS approach, here user can make bunch of mistakes `books`, `ID` etc. It's not strong type safe.

>A CustomResolver has to call dataIdFromObject/cacheKeyResolver. User just has to move arguments into a fieldBlob, which cacheKeyResolver expects.

Sorry didn't get this,  so the part of cache key will be stored in blob? but then how to read cache record for such key? And what is blob, DB blob?

I can see the point where user should be able to register global custom resolver, but first we need to think how to make it more type safe and try to take care for correctly formatting cache key and I still believe we need the way to specify the custom cache key per call.

**Comment by BenSchwab** [comment]
> So if user specifies global custom resolver, does it mean we will always use this cache key for reading/writing records for book object?

We would use the normal process for writing the records, as it seems like it wouldn't matter. For reading, i'm not sure if global custom resolvers should be used as a first priority, or a fallback -- either should work.

By `blob` I mean the object source used in the the key resolver. Because normalization currently needs to know the key before parsing the object, we used a `Map`.

 `@Nonnull CacheKeyResolver<Map<String, Object>> keyResolver`

What the JS client does for `CustomResolvers` is that they resolve the key from a "blob" (js object) of field args + the type name. For us, this would be adding properties to a Map<String, Object>.

I agree the the untyped nature feels Javascripty, but unless we rethink our `CacheKeyResolver` to operate in strongly typed world, having `CustomResolvers` do the same doesn't seem horrible.

Also, I don't mind the per-call option -- I just feel the global option would be a bit more robust, and similar to the JS solution, which is a plus for RN interop.

**Comment by sav007** [comment]
@BenSchwab 
Ok after more thoughts about this stuff I agree that we need smth similar to JS. 
Only I feel that our custom resolver implementation should be based on `Field` and be used inside `CacheFieldValueResolver#valueFor(Record record, Field.ObjectField field)`.

So smth like this:
```java
interface CustomCacheKeyResolver {
 CacheReference resolve(Field field, Operation.Variables variables);
}
```

The example of implementation:
```java
class MyCustomCacheKeyResolver implements CustomCacheKeyResolver {
  CacheReference resolve(Field field, Operation.Variables variables) {
    if (field.arguments.contains("id")) {
   // or more specific if (field.fieldName == "book" &&  field.arguments.contains("id")) {
       String key = field.resolveArgument("id", variables);
       return new CacheReference(key);
    } else {
       return null;
    }
  }
}
```

and it will be used in `com.apollographql.apollo.internal.field.CacheFieldValueResolver#valueFor(com.apollographql.apollo.cache.normalized.Record, com.apollographql.apollo.api.Field.ObjectField)`
```java
private Record valueFor(Record record, Field.ObjectField field) {
    CacheReference cacheReference = customCacheKeyResolver.resolve(field, variables);
    if (cacheReference == null) {
      cacheReference = fieldValue(record, field);
    }
    return cacheReference != null ? readableCache.read(cacheReference.key()) : null;
  }
```

**Comment by BenSchwab** [comment]
This looks great! One thing, if possible, would there be a way to easily access the typename of the object that the field belongs on? I think a lot of people will be using something like `book.id` as their keys, if their objects are not guaranteed to have globally unique ids.
