### ISSUE TITLE
Introduce RefetchQuerries for mutations

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#452]
Javascript documentation: http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient.mutate

Use case: There is post feed, and a detail page where you can create a post. When we create the post, there may be no way for the normalized cache to know that the new post belongs to the feed query. One option is to directly write into the store, but an even simpler (albeit less efficient) is to specify "RefetchQueries" for the mutation.

Ideally, we will want to batch all the qurries in the refetch query into one POST call.

**Comment by sav007** [comment]
Is this concept called Live Query?

**Comment by chaudharyzia** [comment]
Hi sir,
Con you tell me the syntax of graphql “Mutation” in android.

**Comment by sav007** [comment]
@chaudharyzia what do you mean by syntax?
