### ISSUE TITLE
Proposal: introduce overloaded version of clone with operation input params as argument

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#453]
Right now `ApolloCall.clone` method just create the exact copy of call. What if for operations that have input variables to have overloaded version of clone that as argument will take operation variables that will create the copy of initial call but with different input variables. Have smth like this:

```java
@Nonnull ApolloCall<T> clone(Operation.Variables variables);
``` 

That will simplify the way if user needs to execute the same query but with just different variables. 

In some way similar to what JS client calls fetchMore http://dev.apollodata.com/react/cache-updates.html#fetchMore

**Comment by sav007** [comment]
@BenSchwab @digitalbuddha @marwanad @martijnwalraven

**Comment by VisheshVadhera** [comment]
@sav007 this would also mean having a clone method in the Operation interface which takes variables as input and produces a cloned Operation which then is going to be used to create a new ApolloCall. This would also mean changes need to be made to the code creating concrete Operation objects. 

Haven't really had a chance to dig deep into the module responsible for creating concrete Operation objects, so just wanted to know if the approach is correct before going ahead with the implementation. Let me know if what I am thinking is the right approach.

**Comment by sav007** [comment]
@VisheshVadhera lets put this on hold as not sure if it worth an effort.

But idea was next:
```java
CollectionProductPageQuery query = CollectionProductPageQuery.builder()
      .perPage(perPage)
      .nextPageCursor(TextUtils.isEmpty(cursor) ? null : cursor)
      .collectionId(collectionId)
      .build();

ApolloCall call = apolloClient.newCall(query).cacheControl(smth);
call.execute ...
```

Later:
```java
 call.clone(call.variables().toBuilder().nextPageCursor(newCursor).build());
```
