### ISSUE TITLE
CacheKeyResolver#resolve annotated with Nonnull that is not correct

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#455]
`com.apollographql.apollo.cache.normalized.CacheKeyResolver#resolve` argument `objectSource` is annotated with `Nonnull` but from `com.apollographql.apollo.internal.reader.RealResponseReader#readObject` 
```java
Object value = this.fieldValueResolver.valueFor(this.recordSet, field);
    this.checkValue(value, field.optional());
    this.readerShadow.willParseObject(value);
```
`value` can be resolved as null, and from `com.apollographql.apollo.internal.cache.normalized.ResponseNormalizer#willParseObject`
```java
public void willParseObject(R objectSource) {
    this.pathStack.push(this.path);
    CacheKey cacheKey = this.cacheKeyResolver.resolve(objectSource);
```

this null value will be passed to `cacheKeyResolver`.

**Comment by BenSchwab** [comment]
Good find!
