### ISSUE TITLE
Proguard rules for generated models?

### ISSUE THREAD

**Issue by hzsweers** [apollographql/apollo-android#459]
It's unclear what proguard rules should be set up for models, if any. In quick testing, proguard borks models out of the box for me, even if I keep everything that's generated.

**Comment by digitalbuddha** [comment]
When you say borks what do you mean? Like any data models where you are serializing keep don't obfuscate is probably the right patten.  Could you kindly give more detail or a sample?  Thank you for opening issue.

**Comment by hzsweers** [comment]
Figured out my issue - `schema.json` was generating into a different directory than I realized. The models do all need to be reflectively serializable - probably worth mentioning somewhere in the README or even generating rules for directly (correct me if I'm missing this somewhere already)

**Comment by sav007** [comment]
Closing?

**Comment by hzsweers** [comment]
was waiting for a response around the idea of mentioning somewhere in the README

**Comment by aditijoshi** [comment]
Are the proguard rules documented somewhere?

**Comment by digitalbuddha** [comment]
There is no reflection I'm still unclear what proguard is needed for. The generated parsers is refer to the models so there is no reason proguard would strip out.

**Comment by sav007** [comment]
@aditijoshi do you have any specific issue with proguarding apollo generated models?

**Comment by aditijoshi** [comment]
I guess my question is more in general for apollo itself. With minify enabled, proguard might be removing methods or classes it shouldn't be, so are there any rules I should be specifying to not run into any issues. For ex. Any classes or attributes I should be keeping and not obfuscating?

**Comment by sav007** [comment]
As Mike pointed out, Apollo is reflection free so you should be fine without any rules for models. But if you run into any issues pls let us know.

**Comment by runningmarina** [comment]
In my case, we would like keep our current http lib and just use the ability of the apollo-android to generate models. It's purpose is to reduce refactor cost (since we have complex internal logic in our http client). 
So we meet the same issue as this one: "how to write the proguard rules?"
Generally, we will implements Serializable interface and keep all such bean classes in proguard rules file.
Could you kindly give us some suggestion for this case?
