### ISSUE TITLE
POST

### ISSUE THREAD

**Issue by mattfred** [apollographql/apollo-android#460]
I read that Apollo is able to do make POST's as well. Is this correct? Where can I find an example of this?

**Comment by digitalbuddha** [comment]
You do a 'mutation' rather than  a query here is an example
```
mutation TestQuery($ep: Episode!, $review: ReviewInput!) {
  createReview(episode: $ep, review: $review) {
    stars
    commentary
  }
}
```

**Comment by mattfred** [comment]
Thank you
