### ISSUE TITLE
Create builder even when no params. 

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#462]
To make the api less confusing lets create a builder even when no params are needed for a query. We should still keep the constructor as a path to creation.

**Comment by alorma** [comment]
Maybe you can add `@Deprecated` to constructor, so it not break the compatibility but remember devs to update it

**Comment by sav007** [comment]
this one on @VisheshVadhera

**Comment by VisheshVadhera** [comment]
Cool, thanks Ivan :).
