### ISSUE TITLE
Add imperative store API

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#467]
Add something similar to what's described there: https://dev-blog.apollodata.com/apollo-clients-new-imperative-store-api-6cb69318a1e3.

The main use case is to be able to update the cache when a mutation is made. It could be complicated so we might want smaller separate tickets here but didn't find one already so I'm using this one to start the discussion.

**Comment by martinbonnin** [comment]
This might or might not be linked to https://github.com/apollographql/apollo-android/issues/452

**Comment by sav007** [comment]
Hey @martijnwalraven does iOS provide this API `readQuery()`, `readFragment()`, `writeQuery()`, and `writeFragment()`?

**Comment by sav007** [comment]
@BenSchwab @digitalbuddha @marwanad 

After a lot of thoughts regarding `writeQuery/writeFragment` to the normalized store here is the proposal.

To be able to write to the store we need to use the same `ResponseNormalizer` that we are using for reading and parsing JSON response in `ResponseReader`. To use `ResponseNormalizer` we need to get access to generated schema `Field` descriptors the same used  in `Mapper` classes. 
So I suggest to do the similar what we did for mappers and update generated models to have following:

First introduce new interface:

```java
public interface ResponseSerializer {

  void serializeScalarField(Field field, Object value);

  void willSerializeObjectField(Field objectField, Map<String, Object> fieldValues);

  void didSerializeObjectField(Field objectField);

  void didSerializeList(List array);

  void willSerializeListElement(int index);

  void didSerializeListElement(int index);

}
```

 Introduce method in `Operation.Data` and `GraphqlFragment`:

```java
interface Data {
    void serialize(ResponseSerializer serializer);
}

public interface GraphqlFragment {
  void serialize(ResponseSerializer serializer);
}
```
Generate implementation of this `serialize` method that will take the value of field in generated model and pass it to `ResponseSerializer`.

The implementation of `ResponseSerializer` internally will delegate calls to `ResponseNormalizer` and build record set.

The implementation of `writeOperation` will be smth like this:
```java
public final class RealApolloStore implements ApolloStore, ReadableStore, WriteableStore {
  
  public void writeOperation(Operation operation) {
    CacheResponseSerializer responseSerializer = new CacheResponseSerializer(responseNormalizer);
    operation.serialize(responseSerializer);
    merge(responseSerializer.records());
  }

}
```

**Comment by sav007** [comment]
After another thought `writeOperation/writeFragment` seems to be non trivial as we basically need to reconstruct the JSON response from the models. And another issue with resolving conflicts, if we allow user to modify models  that has several fragments defined on the same type and set different values to the same fields. 

For now I would rather put this issue on hold and give https://github.com/apollographql/apollo-android/issues/452 higher priority, where we refetch depended queries rather than direct modify cache store.

**Comment by sav007** [comment]
@BenSchwab @digitalbuddha @marwanad 

Hey guys here is a proposal how writing to cache store will change generated classes.
First of all we will introduce new interfaces `ResponseFieldMarshaller` and `ResponseWriter` that will be used in generated classes to delegate marshalling field values:

```java
interface ResponseFieldMarshaller {
  void marshal(ResponseWriter writer);
}
```

```java
interface ResponseWriter {
  void willWriteObject(Field field);
  void writeValue(Field field, Object value);
  void didWriteObject(Field field);
}
```

Example of new generated class:

```java

...

  @Override
  public ResponseFieldMarshaller responseFieldMarshaller() {
    return new Data.Marshaller();
  }

  @Override
  public ResponseFieldMapper<TestQuery.Data> responseFieldMapper() {
    return new Data.Mapper();
  }

...

  public static class Data implements Operation.Data {
    private final Optional<Hero> hero;

    ...

    static final Field[] $fields = {
        Field.forObject("hero", "hero", new UnmodifiableMapBuilder<String, Object>(1)
            .put("episode", new UnmodifiableMapBuilder<String, Object>(2)
                .put("kind", "Variable")
                .put("variableName", "episode")
                .build())
            .build(), true)
    };

    ...

    public static final class Marshaller implements ResponseFieldMarshaller {
      final Hero.Marshaller heroMarshaller = new Hero.Marshaller();

      public void marshal(ResponseWriter writer) {
        writer.willWriteObject($fields[0]);
        heroMarshaller.marshal(writer);
        writer.didWriteObject($fields[0]);
      }
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final Hero.Mapper heroFieldMapper = new Hero.Mapper();

      @Override
      public Data map(ResponseReader reader) throws IOException {
        final Hero hero = reader.readObject($fields[0], new ResponseReader.ObjectReader<Hero>() {
          @Override
          public Hero read(ResponseReader reader) throws IOException {
            return heroFieldMapper.map(reader);
          }
        });
        return new Data(hero);
      }
    }
  }

  public static class Hero {
    private final @Nonnull String __typename;

    private final Optional<String> name;

   ...

    static final Field[] $fields = {
        Field.forString("__typename", "__typename", null, false),
        Field.forString("name", "name", null, true)
    };

    ...

    public static final class Marshaller implements ResponseFieldMarshaller {
      @Override
      public void marshal(ResponseWriter writer) {
        writer.writeValue($fields[0], __typename);
        writer.writeValue($fields[1], name);
      }
    }

    public static final class Mapper implements ResponseFieldMapper<Hero> {
      @Override
      public Hero map(ResponseReader reader) throws IOException {
        final String __typename = reader.readString($fields[0]);
        final String name = reader.readString($fields[1]);
        return new Hero(__typename, name);
      }
    }
  }
}

```

So  fields are going to be used for both: `ResponseFieldMarshaller` and `ResponseFieldMapper`.

Implementation of `ResponseWriter` will accumulate `Field` values internally and the idea is to use the `ResponseNormalizer` to normalize data the same way as we doing during reading.

Pls, let me know what do you think.

**Comment by BenSchwab** [comment]
@sav007 Let me see if I understand the approach properly:

At a high level you are proposing a way to transform a generated model back into a JSON blob via a `Marshaller` abstraction. So for the imperative write api, the user would first manually construct (or edit) a model. Then internally we will marshall it to a json form, and then run it through the same normalization process that we currently do?

**Comment by sav007** [comment]
@BenSchwab yes that's right, except it won't be a JSON blob but dictionary (map).
