### ISSUE TITLE
CustomTypeAdater cannot map to scalar type

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#470]
A GraphQL schema may have a Custom Scalar type that is best represented as a normal scalar type. For example, we might want to do something like this:
 
```
 customTypeMapping {
      SecondaryKey = "java.lang.String"
}
```

However, this would cause the generated code to not work, with errors such as the one below:

```
 final Field[] fields = {
      Field.forCustomType("__typename", "__typename", null, false, CustomType.STRING),
}
```

This is because to determine if a value is a scalar we check the mapped classname _values_, and not the keys:

```
  private fun TypeName.isCustomScalarType() =
      context.customTypeMap.containsValue(toString())

  private fun TypeName.isScalar() = (SCALAR_TYPES.contains(this) || isEnum())
```

So in this case, java.lang.String is considered a CustomType for all strings, because it is a value of `SecondaryKey`. However, what we really want is to only consider it a custom type when `field.type == SecondaryKey`.

Wondering if we should consider changing these functions, to use the key instead of value.

The alternative isn't terrible -- we could create a class "SecondaryKey" that just wraps a String value. But, code would be cleaner if we did not have to unwrap.

@sav007

**Comment by sav007** [comment]
@BenSchwab yes you are right we should use key not value. not sure why it was done in this way :(

**Comment by sav007** [comment]
Will take a look

**Comment by sav007** [comment]
@BenSchwab how did you get this error?

**Comment by sav007** [comment]
nvm I was able to reproduce.
