### ISSUE TITLE
Apollo Gradle plugin -- add okbuck support

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#474]
For OkBuck to work with gradle plugins, you must offer some configuration at plugin evaluation. For example, SQLDelight:
```
  project.plugins.whenPluginAdded { plugin ->
   ...redacted...
    else if (plugin.class.simpleName == "SqlDelightPlugin") {
        applySqlDelightConfig()
      } 
    }
  }
```

```
 private void applySqlDelightConfig() {
    project.android.libraryVariants.all {
      Task okbuckTask = project.rootProject.tasks.getByName("okbuck")
      Task sqlDelightTask = project.tasks.getByName(
          "generate${it.name.capitalize()}SqlDelightInterface")
      okbuckTask.dependsOn(sqlDelightTask)
      project.android.sourceSets."${it.name}".java.srcDirs += [sqlDelightTask.outputs.files[0] as String]
    }
  }
```

This does not work with apollo because there are no apollo tasks on `project.tasks` when plugins are configured.

I believe this is because we register after project evaluation?:

 ```
private void applyApolloPlugin() {
....
 project.afterEvaluate {
      project.tasks.create(ApolloCodeGenInstallTask.NAME, ApolloCodeGenInstallTask.class)
      addApolloTasks()
    }
}
```

whereas sqldelight does it sooner? https://github.com/square/sqldelight/blob/master/sqldelight-gradle-plugin/src/main/kotlin/com/squareup/sqldelight/gradle/SqlDelightPlugin.kt

**Comment by BenSchwab** [comment]
@marwanad Would you be able to help me with this?

**Comment by marwanad** [comment]
Yeah, the tasks will not be there at the `whenPluginAdded` check. Since we don't really do any configuration that happens after project evaluation, I moved them outside of the block in #475.

The tasks ':generateApolloClasses', ':generateApolloIR', ':installApolloCodegen' should now be available.

**Comment by hzsweers** [comment]
@kageiit you mentioned you knew how this should work, want to chime in?

**Comment by kageiit** [comment]
@BenSchwab You can do it in `project.afterEvaluate` instead of `project.plugins.whenPluginAdded` and both the tasks should be created by that point

**Comment by BenSchwab** [comment]
What @kageiit said and https://github.com/apollographql/apollo-android/pull/475 works for me now. Thanks!
