### ISSUE TITLE
Fix javadoc errors in the build logs

### ISSUE THREAD

**Issue by VisheshVadhera** [apollographql/apollo-android#476]
Need to fix frequently occurring java docs errors. See [this](https://travis-ci.org/apollographql/apollo-android/builds/227283443#L1541) for one occurrence of the errors in the build logs. Maybe [this](https://github.com/chrisbanes/gradle-mvn-push/issues/43) might help (as suggested by @marwanad on slack)?

**Comment by jaredsburrows** [comment]
I have tried but got the same warnings:
```
    task androidJavadocs(type: Javadoc) {
      source = android.sourceSets.main.java.srcDirs
      classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
      classpath += files(android.getBootClasspath().join(File.pathSeparator))
      classpath += files("${android.sdkDirectory}/platforms/${android.compileSdkVersion}/android.jar")
      configure(options) {
        links = ["http://docs.oracle.com/javase/8/docs/api/",
                 "http://docs.oracle.com/javase/7/docs/api/",
                 "http://developer.android.com/reference/"]
        linksOffline "http://d.android.com/reference","${android.sdkDirectory}/docs/reference"
        encoding = "utf-8"
        docEncoding = "utf-8"
        charSet = "utf-8"
        if (JavaVersion.current().isJava8Compatible()) {
          addStringOption("Xdoclint:none", "-quiet")
        }
      }
    }
```

**Comment by jaredsburrows** [comment]
@VisheshVadhera I tried adding more docs/references to link. I am thinking the documentation that is auto generated is good enough. We need more README.md docs, etc. Do you think it is ok just to silence these warnings?

CC @digitalbuddha @sav007

**Comment by jaredsburrows** [comment]
Maybe we can include the missing docs like this: https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/build.gradle#L186.

**Comment by martinbonnin** [comment]
Closing this one as it's 3 years old and moving forward we'll switch to dokka
