### ISSUE TITLE
Propagate CacheKeyResolver changes back to the apollo-sample module

### ISSUE THREAD

**Issue by VisheshVadhera** [apollographql/apollo-android#477]
Realized that we forgot to propagate changes made in #458 back to the apollo-sample module due to which latest builds in #475 & #469 are failing (see [this](https://travis-ci.org/apollographql/apollo-android/builds/227810926#L2144) for the exact location of error in the build logs). 

@sav007 Maybe you can help us with this one?

**Comment by marwanad** [comment]
Maybe we should fix through #441.

**Comment by VisheshVadhera** [comment]
Yeah makes sense. Let me see if I can open a PR.
