### ISSUE TITLE
How to update apollo-codegen to the last version?

### ISSUE THREAD

**Issue by gsancho** [apollographql/apollo-android#479]
The **app:installApolloCodegen** task install 0.10.9 version. 

**build.gradle (Project)**
buildscript {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
        mavenCentral()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath 'com.apollographql.apollo:gradle-plugin:0.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**build.gradle(app)**
 // Apollo GrahpQL
    compile 'com.apollographql.android:converter-pojo:0.1.0'
    compile 'com.apollographql.android:api:0.2.2'

**Comment by marwanad** [comment]
Every Apollo version ships with a fixed `apolllo-codegen` version.

0.3.0 uses v0.10.9. 

0.3.1-SNAPSHOT uses v0.10.11 (and that changes as snapshot is being developed on)

**Comment by gsancho** [comment]
its good! @marwanad Look https://github.com/apollographql/apollo-android/issues/465
