### ISSUE TITLE
Fields that are deprecated in the graphql schema should be annotated with `@Deprecated` in the generated code

### ISSUE THREAD

**Issue by ryangardner** [apollographql/apollo-android#488]
If the introspection query has a field marked as `"isDeprecated" : true`, the generated java objects should be marked as `@Deprecated` and the documentation on the fields should use an `@deprecated` javadoc tag (and if a reason is supplied in the introspection query, it should be put into the javadoc tag)

Developers could then update their introspection query results from time to time (maybe even as a step in their CI build) and get warnings in their IDE or their compiler if their underlying graphql query is relying on a deprecated field.

**Comment by sav007** [comment]
GraphQL schema provides even reason why field was deprecated, we need to include this info as well in generated JavaDoc

**Comment by VisheshVadhera** [comment]
@sav007 I'll tackle this one.

**Comment by sav007** [comment]
@VisheshVadhera where are you with this issue?

**Comment by VisheshVadhera** [comment]
I haven't really been able to devote time for this one due to being a bit
busy. I might get back to this in a couple of days.

**Comment by sav007** [comment]
@VisheshVadhera sure np, I will take this issue then as we need to release 0.3.1 next week

**Comment by VisheshVadhera** [comment]
Alright thanks, sounds good to me. I'll try to lend a hand with the PR
review.

**Comment by sav007** [comment]
Blocked by https://github.com/apollographql/apollo-codegen/issues/114
