### ISSUE TITLE
Mutations from graphql file not being generated in a mutations package.

### ISSUE THREAD

**Issue by Cary-Ciccone** [apollographql/apollo-android#490]
Not sure what is going on, just started using apollo-android.  I noticed that when I added my graphql file with a mutation the mutation class was made outside of a package preventing me from accessing it.  Not sure if this is something I did wrong or a bug in the gen.
![capture](https://cloud.githubusercontent.com/assets/12025047/26027912/a7de81de-37e4-11e7-912f-9eb349ddfb00.PNG)

**Comment by digitalbuddha** [comment]
Did you put your mutation file inside of `graphql`folder nested inside folders of what you wanted package to be? Usually this is due to not having proper package folder inside of your GraphQL folder. See sample in repo ☺️

**Comment by Cary-Ciccone** [comment]
@digitalbuddha You are a stud!  Thank you, I completely overlooked that.
