### ISSUE TITLE
Publish jars instead of aars for the android modules

### ISSUE THREAD

**Issue by VisheshVadhera** [apollographql/apollo-android#492]
See this: http://stackoverflow.com/questions/19307341/android-library-gradle-release-jar

**Comment by digitalbuddha** [comment]
What is the purpose of jar instead of aar?

**Comment by VisheshVadhera** [comment]
aar would have made sense if we had android resources in our android modules, but since we don't it, it makes sense to publish jar instead.

**Comment by jaredsburrows** [comment]
@VisheshVadhera Where would you use a Jar that contains Android code besides an Android application?

**Comment by VisheshVadhera** [comment]
We can publish aars, but the android modules don't really contain resources (layouts or strings), so it's fine I believe to instead publish jars.

**Comment by jaredsburrows** [comment]
I understand but since there is Android code in the jar/aar, it can only be consumed by an Android client such as another Android library or an Android application. Why change them from AAR to JAR? I am just not seeing the benefit.

**Comment by VisheshVadhera** [comment]
I don't really have a very strong opinion on aar vs jar. I was leaning slightly towards jar because of what I said above. But if we really don't see any benefit with jar, then we should probably close this issue. @sav007, do you have anything to add here before I close this one?

**Comment by digitalbuddha** [comment]
I vote aar since I think jar would make folks think it will work on just java projects

**Comment by sav007** [comment]
Yeah agree.

**Comment by jaredsburrows** [comment]
I know this is closed. I didn't have a good example before. I wanted to share this: https://github.com/bumptech/glide/issues/2318. We basically prevented issues like this from happening by closing this issue.
