### ISSUE TITLE
False positives on unused(?) input fields, `Apollo: Use of deprecated input field {{ name }}`

### ISSUE THREAD

**Issue by mateuszkwiecinski** [apollographql/apollo-android#4931]
### Version

3.8.1

### Summary

Given following schema
```graphql
type Viewer {
  books(input: BookInput!): [Book]!
}

input BookInput {
  authorId: String
  deprecatedParameter: Int @deprecated(reason: "Not needed anymore")
  plus: String
  couple: String
  of: String
  other: String
  filters: String
}
```
when querying in this specific way, not sure how such "destructuring" form is called:
```graphql
query BooksByAuthor($authorId: String!) {
  viewer {
    books(input: { authorId: $authorId }) {
      id
      name
    }
  }
}
```

then `generateXxxApolloSources` prints warning saying:
>(...)/src/main/graphql/com/example/Repro.graphql: (3, 18): Apollo: Use of deprecated input field `deprecatedParameter`

I decided to report it as a bug mostly because I don't see how the deprecation warning could be easily fixed, it doesn't seem actionable, and AFAICS the deprecated variable is not actually passed anywhere to the backend, I guess one can say it is not _actually_ used

### More context
The alternative is to require passing the whole input object:
```graphql
query BooksByAuthor($input: BookInput!) {
  viewer {
    books(input: $input) {
      ...
    }
  }
}
```
Although, it would be tad worse, as the "descructuring" way enables us to require all parameters needed for the specific query (for example, query can require non-null parameter value even when schema allows passing null, for backwards compatibility).

I guess the schema could be shaped in a more type-safe way (I mean something like github does - [link](https://youtu.be/pJamhW2xPYw?t=577)), but well... its shape is not fully up to me :/ 

### Steps to reproduce the behavior

repro: https://github.com/lwasyl/apollo-playground/tree/deprecation_warnings

### Logs

Build scan: https://scans.gradle.com/s/qnatep7g4xnla

**Comment by BoD** [comment]
Thanks a lot for reporting this! A fix has been merged [here](https://github.com/apollographql/apollo-kotlin/pull/4935).
