### ISSUE TITLE
how to initiate a request with authorization header?

### ISSUE THREAD

**Issue by totothink** [apollographql/apollo-android#497]

**Comment by digitalbuddha** [comment]
Instantiate okhttp with an interceptor. Add your Auth header in the
interceptor. Instantiate apollo client by passing the okhttp instance to
apollo client builder.

**Comment by sav007** [comment]
```java
OkHttpClient httpClient = new OkHttpClient.Builder()
      .addInterceptor(chain -> {
        Request original = chain.request();
        Request.Builder builder = original.newBuilder().method(original.method(), original.body());
        builder.header("Authorization", authHeader);
        return chain.proceed(builder.build());
      })
      .build();

    apolloClient = ApolloClient.builder()
      .okHttpClient(httpClient)
      ....
```

**Comment by Anilkbalakrishnan** [comment]
done the same but the headers are not added to http request

**Comment by vimal-joe** [comment]
public class LocalApolloClient {
    private static final String URL = "http://192.168.1.100/graphql/";
    private static ApolloClient apolloClient;


    public static ApolloClient getApolloClient(String authHeader){
        HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor();
        loggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .addInterceptor(chain -> {
                    Request original = chain.request();
                    Request.Builder builder = original.newBuilder().method(original.method(), original.body());
                    builder.header("Authorization",  authHeader);
                    Log.d("AUTH_TAG", authHeader);
                    return chain.proceed(builder.build());
                })
                .build();

        apolloClient = ApolloClient.builder()
                .serverUrl(URL)
                .okHttpClient(okHttpClient)
                .build();

        return apolloClient;
    }
}

added authHeader but still cant query the current user's data.

**Comment by gouravd** [comment]
in this case doesn't the getApolloClient always returns a client with a constant old authHeader?

**Comment by vimal-joe** [comment]
i solved it.
changing builder.header("Authorization", authHeader);

to

builder.header("Authorization", "JWT" + " " +  authHeader);

**Comment by mshaileshr** [comment]
Hi, I have found that Apollo request post call only, 
Could I pass get the request to HTTP?, Your help will be appreciated.

**Comment by royhay** [comment]
In your code change the line

builder.header("Authorization",  authHeader);

builder = builder.header("Authorization",  authHeader);

**Comment by tasomaniac** [comment]
Putting this example here for reference. Once you create an `ApolloClient`, you can also pass additional headers each time you do a call.

```
apolloClient.query(query)
        .requestHeaders(
            RequestHeaders.builder()
                .addHeader("Authorization", authHeader)
                .build()
        )
        .enqueue(...);
```

Or with RxJava in Kotlin

```
apolloClient.rxQuery(commitsQuery) {
    requestHeaders(
              RequestHeaders.builder()
                  .addHeader("Authorization", authHeader)
                  .build()
    )
}
```

**Comment by preethishp** [comment]
In the latest version of Apollo client, requestHeaders is marked as deprecated. If anyone is looking for the correct way to do it in the latest version, you can do this: 

apolloClient.query(query)
                    .toBuilder()
                    .requestHeaders(
                           RequestHeaders.builder()
                               .addHeader("Authorization", authHeader)
                               .build()
                    )
                    .build()
                    .enqueue(...);

**Comment by MingFang12** [comment]
I am using the last comment, but I am still getting issue because the token. 
Can you help me this issue?

**Comment by BoD** [comment]
@MingFang12 Are you using v2 or v3? For v3, [this section](https://www.apollographql.com/docs/kotlin/advanced/authentication) of the documentation can shed some light on the topic of authentication. Otherwise, in order to help you we will need more information about what exactly you do that is not working (if you can provide a reproducible project or code snippet that would be great).
