### ISSUE TITLE
[Code Generation] Generate interface to be consumed by Retrofit

### ISSUE THREAD

**Issue by felipecsl** [apollographql/apollo-android#50]
The interface should have methods for each of the queries found in the IR files with the correct `Data` types.

**Comment by sav007** [comment]
I gave it a thought how about to let user define (declare) retrofit service interface and feed it to `Apollo` client that will pass to retrofit and create service adapter, so user defines service:

```
public interface QueryService {

    @POST("graphql")
    Call<Query.Data> execute(Query query);
    
    OR
    
    @POST("graphql")
    Observable<Query.Data> execute(Query query);
  }
```
Pass it to: 
```
QueryService service = Apollo.create(QueryService.class)
```

In this case we solve problem with return type, user decides if he wants to use Rx or regular Callback, and we use retrofit for help with that.

**Comment by martijnwalraven** [comment]
Not sure where this fits in the overall design, but I just want to make sure we keep networking and query fetching separate so we can handle caching transparently.

If we follow the iOS design, `ApolloClient` could have something like a `fetch(Query query)` method, and `Query.Data` would  be constructed either from the cache or from a network response. In the latter case, it is the responsibility of a `NetworkTransport` to perform the actual network request and parse the response format.

**Comment by sav007** [comment]
For caching we can have our retrofit CallAdapter, that will be responsible for read/write to cache. Retrofit allows to register multiple call adapters / converters.

**Comment by sav007** [comment]
And we can move construction of retrofit to `Apollo` client because we have to have the control of converter orders, we want our query request / response converter to be first. But we can expose some retrofit config options, like `baseUrl`, `httpClient` and delegate setters to retrofit builder.

**Comment by felipecsl** [comment]
Hmm not sure I agree with that. It sounds to me it's better to have the user provide their own Retrofit instance and instruct them to set our converter to be the first one.
Imagine you have an existing app that already makes heavy usage of Retrofit, not you want to use Apollo, you'll want to keep using the same Retrofit object.

**Comment by sav007** [comment]
Yeah, it's a good case. Well maybe it's not so bad idea to instruct user to add our converter to be the first one

**Comment by sav007** [comment]
@felipecsl is this still valid ticket?

**Comment by felipecsl** [comment]
I'm not sure, we'll have to revisit that. We can keep it around in the meantime I guess.

**Comment by sav007** [comment]
As per our decision to drop retrofit support, this issue not valid anymore, closing
