### ISSUE TITLE
Add possibility to register custom fields in error response

### ISSUE THREAD

**Issue by datrixo** [apollographql/apollo-android#511]
Our backend in error responses adds custom fields. For example:

```
{
  "data": {
    ...
  },
  "errors": [
    {
      "statusCode": 401,
      "error": "Unauthorized",
      "message": "JWT Token not found",
      "timeThrown": "2017-06-06T11:58:54.093Z",
      "data": null
    }
  ]
}
```
Now, it's impossible to reach statusCode in this situation. It's possible to add feature to the lib that could add fields to the mapped error response?

**Comment by sav007** [comment]
Closed via https://github.com/apollographql/apollo-android/pull/506
