### ISSUE TITLE
Retrieving error values

### ISSUE THREAD

**Issue by mattfred** [apollographql/apollo-android#512]
I'm currently using a RxApollo to create a `Subscription` for all network calls.

    public Subscription performSearch(String query) {
        return RxApollo.from(apolloClient.newCall(new SearchQuery(query)))
                .subscribeOn(scheduler)
                .observeOn(observeScheduler)
                .flatMap(new SearchResultsToObject())
                .subscribe(new CustomSubscriber());
    }

However, when the response includes error information, I see no way of getting that data. How can I access the error JSON?

`"data": {
    "query": null
  },
  "errors": [
    {
      "message": "Error Here",
     }.....`

**Comment by sav007** [comment]
Closed via https://github.com/apollographql/apollo-android/pull/447
