### ISSUE TITLE
Add support for query batching

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#513]
Ref docs:
http://dev.apollodata.com/core/network.html#query-batching
https://dev-blog.apollodata.com/query-batching-in-apollo-63acfd859862

**Comment by Radivarig** [comment]
Any news on this?

**Comment by sav007** [comment]
No any updates, not sure what is the priority for this feature. Not all implementations of GraphQL server supports multiple queries execution support. And with client batching (via aliases) seems to me like a workaround.

**Comment by Radivarig** [comment]
I've got a dynamic list of items that needs to be inserted to a table and have thought that mapping each item to a mutation would batch them up and send as an array in a single request. Is there some existing solution I'm missing?

**Comment by Radivarig** [comment]
I'm using postgraphile, last week this plugin was released [postgraphile-plugin-nested-mutations](https://github.com/mlipscombe/postgraphile-plugin-nested-mutations) mentioned in [postgraphile#793](https://github.com/graphile/postgraphile/issues/793), it allows nested mutations, I can now create or connect existing foreign key items from a variable array, all in one query :)

**Comment by mandrizzle** [comment]
I have a solution to this and believe this is possible using only OkHttp interceptors. I am unsure of what the requirements are other than:

 1. There should be a custom batch timing interval and max batch size
 2. Join the queries into a single JSON array for the request
 3. Expect a JSON array as a response and dispatch a response to each item in the same order they came in
 4. If # requests do not match # responses fail the entire batch

What I have not yet done but is still possible by adding custom headers to each request:
 1. Batch queries and mutations separately  
  2. Don't batch certain requests

If the above is all that is needed, I have a working solution and would be willing to submit a PR. If not, what else needs to be handled?

**Comment by DJansse** [comment]
Any update on this topic / discussion? 
We're using Apollo GQL on Web, iOS and Android and are thinking about updating the server to support transport level batching of queries...

Kind regards

**Comment by mandrizzle** [comment]
So from my original comment, I have that implementation working great however, it needs to create a new thread for each request which is not ideal. I am working on a refactor that now sets a custom `CallFactory` to reduce the number of threads required to just one. Just need to test it out and I'll keep y'all updated.

**Comment by imankhdrpst** [comment]
hi @mandrizzle  , Did you have anything implemented, could you post them here ?

**Comment by spawrksvrbo** [comment]
Do we have any updates on this?  Wondering if someone needs support to help get this over the line, it's super helpful to be able to query batch and I'm surprised this has been open for so long.  Would love to know how to help.

**Comment by rocketraman** [comment]
Hasura is another backend that can leverage multiple mutations in a request to ensure all-or-nothing via a db transaction: https://hasura.io/docs/latest/graphql/core/databases/postgres/mutations/multiple-mutations.html.

**Comment by joaquim-verges** [comment]
Took a stab at an implementation here: #3117 if anyone is interested

**Comment by martinbonnin** [comment]
Closed with #3117
