### ISSUE TITLE
ERROR WHEN ADD WHERE

### ISSUE THREAD

**Issue by gsancho** [apollographql/apollo-android#516]
{"errors":[{"message":"Variable \"$where\" got invalid value {\"aND\":[{\"createdAt\":{\"gt\":\"2017-06-08\"}},{\"createdAt\":{\"lt\":\"2017-06-07\"}}]}.\nIn field \"aND\": Unknown field.","locations":[{"line":1,"column":28}],"name":"GraphQLError"}]}

**Comment by sav007** [comment]
Could you please  provide more explanation regarding this, what's wrong?
As well provide the graphql query

**Comment by sav007** [comment]
@gsancho any additional info you can share ^^^?

**Comment by sav007** [comment]
Sorry but we missing more info about this issue, closing for now
