### ISSUE TITLE
Trying to use SNAPSHOT

### ISSUE THREAD

**Issue by mattfred** [apollographql/apollo-android#525]
When trying to use the SNAPSHOT I get this error during the Gradle sync. Any idea of how to fix it?

Error:Failed to resolve: com.apollographql.apollo:apollo-runtime:0.3.2-SNAPSHOT

**Comment by sav007** [comment]
Did you add 
```
buildscript {
  repositories {
    jcenter()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
  }
  dependencies {
    classpath 'com.apollographql.apollo:gradle-plugin:0.3.2-SNAPSHOT'
  }
}
```

To your gradle file?

**Comment by mattfred** [comment]
Yes

**Comment by sav007** [comment]
That very strange as if you go to https://oss.sonatype.org/content/repositories/snapshots/com/apollographql/apollo/apollo-runtime/
you can see it there.

Plus just verified on my sample app, it resolves this dep correctly.
So I would say look into your gradle build file.

**Comment by mattfred** [comment]
I'll double check with the sample. Thanks
