### ISSUE TITLE
How to convert VO (view object) to PO (persistant object) in Java with GraphQL

### ISSUE THREAD

**Issue by 80998062** [apollographql/apollo-android#533]
Lately I am working on an Android application based on a **[GraphQL](http://graphql.org/learn/)** service.Since **GraphQL** response data is  backed by my existing code, I feel it works exceedingly troublesome with **Java**...( ˉ ⌓ ˉ ๑)﻿﻿

Since I used to convert **JSON** Object to  my Entity class (POJO) by **GSON** or anything else…then I can easily perform database operations such as retrieval...

But now GraphQL has different response data **vary from API to API**

For example the query:

```
{
  book {
    name
  }
}
```

and 

```
{
  book {
    title
    cover
  }
}
```

But those two Book data indeed are the same thing as for me( they are same class I keep in **Java**,I mean)So how can I quickly convert `RequestA.Book` and `Request.Book` to one persistant object which named `Book ` ? 

I find there are `ResponseFieldMapper` and `Field` class in **[Apollo-Android](https://github.com/apollographql/apollo-android)**.,which seems to be helpful but I don't know how to do concrete steps.Any advice on managing the extra work? 

`_(:ｪ 」∠)_ ` I feel painful to write redundant code like **Mapper** a class to another a thousand times ,If any one give me a working example much appreciated.Thanks in advance :D

**Comment by sav007** [comment]
Apollo client generates unique classes per query, that means in your case it will generate 2 different classes for Book entity. We can't merge field set from all queries to have one Book entity, one example of issues with that as we guarantee non-nullability of fields (GraphQL schema defines if field like title can be null or not). So lets say GraphQL schema defined book title as non-null then if we have only one model Book for all queries then all fields are potentially nullable. This is only one reason among others related to fragments etc.

So one recommendation (and this is the best practice) is each layer must have own models. So for example UI layer must have own models (view models), and convert models from one layer to another. So API models (like GraphQL generated models) shouldn't sneak to UI. 

You can find a lot info why this is a good approach. 

In your case create you own Book model and then map generated GraphQL models to your own model.
