### ISSUE TITLE
How to deal with the generic GraphQL scalar value in response?

### ISSUE THREAD

**Issue by 80998062** [apollographql/apollo-android#537]
So for example,if the response data are like this:

```
{
  article :{
    id:"",
    title:"",
    content:{
      paragraph:[
        id:"",
        elements:[{tag: "p", text: "", id: "e099a1"}]
      ]
    }
  }
}

```

It supporsed to have so-called `Article` ,`Content `,`Paragraph` entities in the **GraphQL**'s schema, but as to the `content` node,it's already a `GenericScalar` type,so Apollo can't generate the corresponding class like:

```java
class Content{
  List<Paragraph> paragraphs;
  class Paragraph{
    List<Element> elements;
    ....
  }
}
```

So I have to do extra work on those scalar value,but what's worse: because use **Rx2Apollo**,

 the most origina response data I can get is like this:

```
Content: {paragraphs=[{id=587f6c, elements=[{tag=p, text=not ok, id=e099a1}]}]}
```

It's not  **JSON** data at all (even the value term is  not surrounded by `" "`),so there is certainly much work which is exceedingly troublesome if I want to convert it to **POJO**.

Now I've found  no way to get the *raw* **JSON** sent by the server in response, and **Apollo**

seems to lose its advantages and conveniences in that case.

Although I think our backend developers should take the blame for this ( the response is not well-formated,I mean), but what should I do in my shoes `_(:ｪ 」∠)_`

Any advices , thx in advance :D

**Comment by sav007** [comment]
Yeah that is totally issue with pure designed backend.
Because `Content` defined as a custom scalar type it is sent in the response as plain text `String` not as Json string. I believe first what you need is to check if this is true and ask backed guys to send you as Json string.
