### ISSUE TITLE
Generated method to access inline/referenced Fragment properties differs

### ISSUE THREAD

**Issue by eschlenz** [apollographql/apollo-android#547]
Using version: `0.3.3-SNAPSHOT` (refreshed 7/6/2017 in the AM)

The generated models expose Fragment properties using different naming conventions if you use inline fragments, vs externally referenced fragments.

Expected: I would have expected an `asOffer()` method on `Content`, similar to what I see when I use inline fragments. Instead I get a `fragments()` method. For consistency, and since they are semantically the same thing, shouldn't one or the other be used in both cases?

-------------------------
**Using externally referenced fragments**
-------------------------

I have the following two graphql files:

Main query file: `Search.graphql`

```
query SearchGraphQL($term: String, $retailerId: Int, $limit: Int, $contentTypes: [String]) {
  search(term: $term, retailerId: $retailerId, limit: $limit, contentTypes: $contentTypes) {
   	results {
      id
      type
      display_type
      content {
        id
        type
        name
        link
        sort_order
        ... OfferFragment
      }
    }
  }
}
```

Referenced fragment file: `OfferFragment.graphql`

```
fragment OfferFragment on Offer {
  id
  activated
  amount
  any_brand
}
```

Generated Content class **(NOTE: the `fragments()` method, but no `asXxx()` method):**

```
public static class Content {
    ...
    private final @Nonnull Fragments fragments;

    ...

    public @Nonnull Fragments fragments() {
      return this.fragments;
    }

    ...

    public static class Fragments {
      final @Nullable OfferFragment offerFragment;

      ...
      }
    }
```

-------------------------
**Using inline fragments**
-------------------------

Using a single query with inline fragments: `Search.graphql`

```
query SearchGraphQL($term: String, $retailerId: Int, $limit: Int, $contentTypes: [String]) {
  search(term: $term, retailerId: $retailerId, limit: $limit, contentTypes: $contentTypes) {
   	results {
      id
      type
      display_type
      content {
        id
        type
        name
        link
        sort_order
        ... on Offer {
          id
          activated
          amount
          any_brand
        }
      }
    }
  }
}
```

The generated `Content` class has an `asOffer()` method (as expected), instead of a `fragments()` method.

```
public static class Content {
    ...
    final @Nullable AsOffer asOffer;

    ...

    public @Nullable AsOffer asOffer() {
      return this.asOffer;
    }

    ...
}
```

**Comment by sav007** [comment]
That was done intently and the reason why was inline fragment doesn't have names, so the name of generated model for inline fragment comes from prefix `As` + name of type on which this fragment defined (in your example `Offer` - it's a GraphQL object type). As for fragments, they have names (in your example `OfferFragment`) so the name of generated model will the name that you defined.

**Comment by eschlenz** [comment]
I see what you're saying, and I can see why it is this way. From my perspective, as a client of the generated model classes, I now have two possible ways to get to essentially the same data. That implies having knowledge of the structure of the query, which puts a burden on downstream dependents of the models.

In the case where a referenced (named) fragment is used, could you have both the `fragments()` method as well as an `as[Type]()` method on the models? As I typed that, I'm not sure how I feel about it. It would at least give clients a common way to get at the data regardless of how they chose to use fragments.

Thoughts?

**Comment by sav007** [comment]
Did you consider that in case of regular fragments you can specify multiple fragments on the same type at the same query. For example:
```
query SearchGraphQL($term: String, $retailerId: Int, $limit: Int, $contentTypes: [String]) {
  search(term: $term, retailerId: $retailerId, limit: $limit, contentTypes: $contentTypes) {
   	results {
      id
      type
      display_type
      content {
        id
        type
        name
        link
        sort_order
        ... OfferShortFragment
        ... OfferDetailFragment
      }
    }
  }
}

fragment OfferShortFragment on Offer {
  id
  amount
}

fragment OfferDetailFragment on Offer {
  id
  activated
  amount
  any_brand
}
```
So in this case what names we will have: `AsOffer1`, `AsOffer2` ?
Plus the model of regular fragment is shared between queries, that is the beauty of fragments. 

with inline fragments its different story as they local to query (they can't be shared), yes technically you can in query specify multiple inline fragments but we will merge fields between them and you will get only one `AsOffer`.

**Comment by eschlenz** [comment]
Syntactically that looks like a valid query. Is there a valid use case for referencing two fragments of the same type? Out of curiosity, I tried a similar example to what you provided because I wanted to see what the results would look like.

Query:

```
query SearchGraphQL($term: String, $retailerId: Int, $limit: Int, $contentTypes: [String]) {
  search(term: $term, retailerId: $retailerId, limit: $limit, contentTypes: $contentTypes) {
   	results {
      id
      type
      display_type
      content {
        id
        type
        name
        link
        sort_order
        ... OfferShortFragment
      	... OfferLongFragment

      }
    }
  }
}

fragment OfferShortFragment on Offer {
  id
  name
  amount
}

fragment OfferLongFragment on Offer {
  id
  name
  amount
  activated
  any_brand
}
```

Response:

```
{
  "data": {
    "search": {
      "results": [
        {
          "id": "-100",
          "type": "ContentModule",
          "display_type": "rows",
          "content": [
            {
              "id": "103621",
              "type": "Offer",
              "name": "Heluva Good!® Cheese",
              "link": "retailer/any/offer/103621",
              "sort_order": null,
              "amount": 0.75,
              "activated": false,
              "any_brand": null
            }
          ]
        }
      ]
    }
  }
}
```

It looks to me like the GraphQL server merged the two referenced fragments to return a single superset of results. So in this case you wouldn't need `AsOffer1`, `AsOffer2`... just `AsOffer`.

**Comment by sav007** [comment]
GraphQL specs doesn't restrict to have multiple fragments on the same type in the same query. So why Apollo lib should restrict this and introduce own version of spec, yes maybe it doesn't have a valid case. 

GraphQL server response is optimized, you won't find any query specific instructions in it (like fragments, inline fragments, directives, arguments, variables etc.). This is pure responsibility of client library then to parse it in the shape how query defines (and that pretty much what Apollo doing).

>So in this case you wouldn't need AsOffer1, AsOffer2... just AsOffer.

Yes we could combine all fields from different fragments into one model, but if you pay attention to generated models you will see that we guarantee non-null values. So let's say if GraphQL schema defines that `activated` is non-null, we will generate model with `@Nonull` field annotation.

But in case if we were merging fields into one model that wouldn't possible (`OfferShortFragment`  doesn't request field `activated` but because your suggested model `AsOffer` has all fields including `activated` it will be null even if schema defines it's non optional).

**Comment by sav007** [comment]
Some points is not valid from this doc but it def worth to read https://github.com/apollographql/apollo-android/blob/design-doc/DESIGN.md

**Comment by eschlenz** [comment]
@sav007 Cool. Thanks for the explanation. I think you can close this discussion if you'd like. I appreciate the responses!
