### ISSUE TITLE
Add support for semantic naming

### ISSUE THREAD

**Issue by BenSchwab** [apollographql/apollo-android#551]
on iOS a query like: 
```
query AllStarships {
  allStarships(first: 7) {
    edges {
      node {
        ...starshipFragment
      }
    }
  }
}
```
Would generate a file like class called `AllStarshipsQuery`. This makes sense because the generated object is a thing/noun. when writing the graphql, it often makes sense to omit the Query suffix because the language requires a `query` identifier before the name.

This is important because when we want to whitelist a query iOS may write: 
```
query AllStarships {
}
```
and Android currently may write 
```
query AllStarshipsQuery {
}
```
to generate the same code. However, the whitelist hash would be different.

Not everyone may want to use this semantic naming, so I propose adding it as a gradle plugin flag:
`useSemanticNaming`

cc @kompfner

**Comment by stubailo** [comment]
> However, the whitelist hash would be different.

Is it a problem if iOS and Android generate slightly different queries for you?

**Comment by BenSchwab** [comment]
We haven't decided specifically if iOS and Android will share a common registry, but I could see how it would be convenient to easily check if a specific query is used in android/ios without worrying about different naming conventions
