### ISSUE TITLE
Make sure RealApolloCall doesn't hold reference to user callback after complete or cancel

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#560]
We need to nullify reference to user provided callback in `com.apollographql.apollo.internal.RealApolloCall#enqueue` that if call has been finished or canceled we don't hold the strong reference to user callback any longer.

**Comment by BenSchwab** [comment]
I have to move around some of the cancel/dispose logic in https://github.com/apollographql/apollo-android/pull/556 because of the added `Callback#onComplete` for multi-response fetchers. I can try to fix in that PR.

**Comment by sav007** [comment]
@BenSchwab Yeah I was waiting on your PR to go first anyway and then fix this

**Comment by sav007** [comment]
So I will reassign this to you then
