### ISSUE TITLE
Ability to invalidate cached items by key needed.

### ISSUE THREAD

**Issue by eschlenz** [apollographql/apollo-android#564]
This discussion started in issue #561. @BenSchwab suggested I create a separate issue report for the following:

----

There currently appears to be no way to invalidate specific items in the cache. From what I can tell, it's an all or nothing proposition with only a `clearAll()` type method being exposed to users of the Apollo SDK. There are valid use cases for needing to invalidate specific cached objects.

For example, let's say you had a list/detail situation. A query is executed to get a list of objects for the UI, each with only a few properties to display summary level info for each. The detail UI makes a query for one of the specific objects and includes more properties. Everything loaded so far is cached. If I wanted to invalidate the cache for the one specific object, ideally I could blow it away using its cache key. I guess I would expect that if I did that, the cached list would also become invalidated since it references the single object which was invalidated.

I don't see how one would do something like that with the current SDK. The only options for cache invalidation seem to be to blow everything away. 

To quote @BenSchwab on this topic:

> Can you make a separate issue for deleting single cache entries? We should be able to do something via the imperative store api.

**Comment by sav007** [comment]
@eschlenz 
> If I wanted to invalidate the cache for the one specific object

Just curios do you have any specific use case where you need this? As for list -> details (master - details) as this is a normalized cache the response of will be shared between list and details. So any updates on details will be visible in list.

**Comment by eschlenz** [comment]
@sav007 

> Just curios do you have any specific use case where you need this? As for list -> details (master - details) as this is a normalized cache the response of will be shared between list and details. So any 
updates on details will be visible in list.

I see what you are saying there. If a specific object is updated in the cache, any other data that's referencing it will have the updated version for future use. That's great! But what I'm looking for is the ability to at least manually invalidate a specific object, and have anything referencing it be implicitly invalidated as well.

I'll try to use a real world example. Our API team is in the process of transitioning from a REST API to GraphQL. At the moment, only read operations are provided by our GraphQL server. Write operations are still done through our REST API. So there is a scenario where the user can take action on the "detail" page, which we know will result in modification of that object. We want to invalidate any cached data related to it so that we can fetch a fresh copy from GraphQL. 

Currently we would simply stay on the detail page and make the call to refresh that object. Alternatively, let's say that upon modification of the object with the REST API, we wanted to jump the user back to the list (master) screen. After the REST update, but before taking the user to the list, I might invalidate the updated object knowing that other areas of the app also need to reflect the current state. In doing so I want the invalidation of the single object to implicitly invalidate any cached data that references it.

Another example, which might be relevant to others outside myself, might be "pull to refresh" on the detail screen. If I detect a "pull to refresh" I feel I should have the option to invalidate the cache for the object before attempting the query again, thereby getting a fresh copy. That doesn't seem possible at the moment.

**Comment by sav007** [comment]
Yeah, makes sense. Thx!

**Comment by eschlenz** [comment]
Thanks for the change @sav007!
