### ISSUE TITLE
Handle gracefully null list items

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#565]
As Arrays are just wrappers around other types and other types are nullable by default, a type of [Person] can include null values. To avoid this you can write [Person!]. If you want to ensure the array exists, you'd add [Person!]!. You can keep wrapping wrapped types in this fashion, if you want to return an array of arrays for instance.

**Comment by sav007** [comment]
@martijnwalraven on iOS side are you skip items in the list that `nil` or you add them to array?

**Comment by sav007** [comment]
@digitalbuddha @BenSchwab 
there are 2 ways to solve this: the easiest way just ignore null items or more effort to correctly handle them and null values to the list.

**Comment by digitalbuddha** [comment]
I vote ignore. What else will you do an app code differently? Wouldn't you just ignore null anyway?

**Comment by sav007** [comment]
I see only one case when the order of items matter and you have some specific logic that depends on this condition `list[3] == null`

**Comment by digitalbuddha** [comment]
Relay gives you the nulls. Our web code didn't crash. @sav007 can we make configurable (skip nulls directive)

**Comment by sav007** [comment]
Ok I will skip nulls for now, if someone later really need this we will implement

**Comment by martijnwalraven** [comment]
@sav007: I would say the `null`s are as much a part of the response as other values, so I wouldn't skip them. If you don't want to deal with `null` elements, you should define the list element type as non-null (e.g. `[Person!]`).
