### ISSUE TITLE
Apollo Store as submodule

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#570]
Proposal: extract Apollo store as separate submodule

Motivation: Apollo store became mature and independent thing with own imperative API, we should consider to move it to separate submodule, so `apollo-runtime` will be pure for making network calls, `apollo-store` pure for storing response data. And it will be optional for user in case if he needs only pure network layer.

**Comment by sav007** [comment]
@digitalbuddha @BenSchwab let me know what do you think?

**Comment by sav007** [comment]
<img width="266" alt="screen shot 2017-07-15 at 11 20 43 am" src="https://user-images.githubusercontent.com/902816/28240431-cb2b33fc-694f-11e7-8448-a6883ec40944.png">

All these classes will be moved to this module

**Comment by digitalbuddha** [comment]
Good idea. Was hoping to avoid using it altogether if possible. Sometimes app wants just simple graphql client

**Comment by BenSchwab** [comment]
sgtm

**Comment by sav007** [comment]
Normalized cache is so tightly coupled with the core Apollo runtime that makes almost impossible to extract it as submodule, the effort of doing this is too much than the benefit. Closing it for now.
