### ISSUE TITLE
Remove reflection from request parsing

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#572]
It was observed by a user that large requests lead to lots of reflection creating moshi json adapters through reflection. We need to either generate moshi json adapters or create our own serialization for request objects.  As an example: it took 1200ms to create the Json request string & under 200ms to get a response.

**Comment by sav007** [comment]
it seems we can remove moshi completely and generate marshaller code in the same way as we doing for operation data marshaller
