### ISSUE TITLE
Run subscriptions like queries with IDE plugins

### ISSUE THREAD

**Issue by damianpetla** [apollographql/apollo-android#5745]
### Use case

Right now we cannot run subscriptions with IDE plugin. It returns error
```json
{
  "errors": [
    {
      "message": "subscriptions are not supported over HTTP, use websockets instead",
      "extensions": {
        "path": "$",
        "code": "unexpected-payload"
      }
    }
  ]
}
```
Every time I need to test it I manually change it to `query` and then run.

### Describe the solution you'd like

Would be nice if plugin could call it like query under the hood, maybe with some warning saying it was transformed to query on the fly.

**Comment by BoD** [comment]
Thank you for reporting this!

A way to execute subscriptions in the IDE would be nice, however the challenge is that the underlying protocol for subscriptions is not part of the GraphQL spec, and therefore several protocol exist depending on the server (several WebSocket subprotocols, subscriptions over HTTP, etc.) - so we would need a way to configure the plugin with that information.

The idea you suggest to transform the document into a query is interesting, but wouldn't work in the general case - it would only work for schemas that have the same fields in their Query and Subscription types. I am not sure how common this is.

Side note: this part of the plugin is actually provided by the [GraphQL plugin](https://github.com/JetBrains/js-graphql-intellij-plugin), which Apollo depends on - it may make sense to open an issue there.

**Comment by kkarkal** [comment]
This will be a good feature for the IDE's, Currently we are only able to run queries and mutations, Subscriptions would be great to run.
