### ISSUE TITLE
[Code Generation] Add javadoc to generated classes from description field

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#58]

**Comment by sav007** [comment]
@martijnwalraven does `apollo-codegen` provides `description` field for fields, types in IR.json?

**Comment by martijnwalraven** [comment]
@sav007: It didn't before, but I added it in `apollo-codegen` 0.10.11.

**Comment by sav007** [comment]
We still missing description for operation top level fields in IR:
https://github.com/apollographql/apollo-codegen/issues/90
