### ISSUE TITLE
Slow JSON parsing (Moshi). Explore, or allow for alternative?

### ISSUE THREAD

**Issue by eschlenz** [apollographql/apollo-android#581]
Hey Apollo team,

We were debugging some slowness in querying for GraphQL data. We have some payloads that are a couple of megs in size. Doing some quick method profiling, and looking at your source, it looks like you guys are using the Moshi library to deserialize the JSON. We think some performance gains can be had by using other libraries out there. We are wondering if you have:

a) Would be open to allowing for pluggable alternatives to Moshi. Perhaps Moshi is good for you guys, and Jackson is great for us, but maybe some other team has yet another preference. The ability to plug in a JSON library of choice would be awesome!

b) Considered alternatives. Moshi doesn't seem to be the fastest option out there (Benchmark comparisons here: https://github.com/fabienrenaud/java-json-benchmark). We've had good success with Jackson.

**Comment by digitalbuddha** [comment]
We just merged a pr that will remove moshi parsing of request objects in favor of custom reflection free parsing. Nothing will be faster than generating the writer logic for each query. Could you kindly try on latest snapshot?

**Comment by digitalbuddha** [comment]
The response parsing does not pass through moshi and also uses custom reflection free parsing

**Comment by eschlenz** [comment]
@digitalbuddha Sweet! I'll definitely try it out.
