### ISSUE TITLE
Introduce Optimistic updates for mutations

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#583]
**The problem**: in most cases the result of mutations are well known even before waiting for server response. The idea behind optimistic updates are pretty straight forward, to be able specify `optimisticResponse` for mutation operation that will be temporary saved into memory cache before network response arrives.

**Proposal**: introduce the layer that is basically separate instance of ApolloStore for optimistic updates only and that based on mem cache. Any queries that try to read response from cache will first hit ApolloStore with optimistic updates and if it can't resolve cache response then  will hit regular ApolloStore with normalized cache. The rollback mechanism for optimistic updates should remove them in case if mutation succeed or failed. 

http://dev.apollodata.com/react/mutations.html#optimistic-ui
https://dev-blog.apollodata.com/mutations-and-optimistic-ui-in-apollo-client-517eacee8fb0

**Comment by sav007** [comment]
@BenSchwab @digitalbuddha @martijnwalraven I'm going to start working on this feature so if you have any thoughts, comments pls share

**Comment by BenSchwab** [comment]
I was thinking of a similar approach! Sgtm
