### ISSUE TITLE
Add ability to use CustomTypeAdapter with "regular" scalars (e.g. ID)

### ISSUE THREAD

**Issue by murki** [apollographql/apollo-android#585]
Ideally we should be able to configure the `ApolloClient` to use logic inside a `CustomTypeAdapter` when mapping regular scalar fields, e.g.
```java
return ApolloClient.builder()
    .serverUrl(graphqlEndpoint.toString())
    .okHttpClient(graphQLApolloClient)
    .addCustomTypeAdapter(ScalarType.ID, myIdTypeAdapter) // <--
    .build();
```

**Comment by sav007** [comment]
I wouldn’t make it to be generic, as it will bring a lot of complexity than benefit but I would consider to make exception for ID only.

@digitalbuddha @BenSchwab @martijnwalraven do you think this makes any sense?

**Comment by digitalbuddha** [comment]
Yes keep scope small. Make for only id makes sense to me
