### ISSUE TITLE
Enabling apollo metadata generation for multi-module codegen causes build cache misses

### ISSUE THREAD

**Issue by rohandhruva** [apollographql/apollo-android#5917]
### Version

4.0.0-beta.6

### Summary

We recently enabled multi-module codegen in our project, to modularize our GraphQL usage. After enabling this, we noticed an increase in our build cache misses, and it lined up with when we enabled `generateApolloMetadata.set(true)`. 

After some further investigation, it turns out that the generated `ir.json` and `metadata.json` files are not deterministic: likely because there is no deterministic ordering in JSON, and kotlinx-serialization does not support ordering either.

We are still investigating this, but for now, it seems like it is enough to mark the `ApolloGenerateIrOperationsTask` as a `@CacheableTask`, which is what I've proposed in #5916. In the future, it might be worth considering if we can easily generate `ir.json` and `metadata.json` in a  deterministic manner.

**Comment by martinbonnin** [comment]
Fixed with https://github.com/apollographql/apollo-kotlin/pull/5919
