### ISSUE TITLE
Provide the ability to have multiple modules

### ISSUE THREAD

**Issue by CristianGM** [apollographql/apollo-android#593]
Context: Our current project have multiple modules ( and I'm sure I'm not the only one ).
Each module contains a feature: network requests, GraphQL queries, business logic, and the app module consumes from all of them.

Having modules help feature teams to have decoupled code and also will help doing Instant Apps later.

Is it possible to have the schema.json in one "base" module, and in another modules have the `*.graphql` files?

Having the ability to choose the path of the schema.json from gradle would probably fix the issue even if that's not using the gradle dependencies system ( it won't work if we move from.modules in a single project to maven artifacts ).
Every module can apply the Apollo plugin to generate the requests classes but I don't like the idea of having several copies of the schema.json

**Comment by CristianGM** [comment]
After some discussion on the Slack, some steps:

- sharing the schema.json
- sharing scalar types to avoid duplication
- providing incremental compilation ( using the json as input file for the task? )
- fragments sharing

**Comment by O-labib** [comment]
Can you please clarify how you could solve this problem?

**Comment by castorflex** [comment]
Hey there,
Is fragment sharing still a thing? As far as I understand, there is no way to use Apollo in a multi module application at this moment? May be I couldn't find how to do this, but it seems that every module has to define its own fragments, and Apollo will generate classes for each of them, so we cannot share the generated models among all the feature modules. 
Or may be I missed something?

thanks!

**Comment by martinbonnin** [comment]
@castorflex you're right, fragments from one module cannot be reused in another module at the moment. You can watch #1973  for updates about this issue.
