### ISSUE TITLE
Add `model.newBuilder()` to allow easily cloning data

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#594]
It would be nice to have an easier way to mutate generated classes instances. Calling the constructor becomes very tedious as data becomes more complex and nested. Ideally, given the query below:

    query {
        video {
            channel {
                name
            }
        }
    }

We could change the `name` field with: 

    builder = data().newBuilder();
    builder.video().channel().withName("newName")
    newData = builder.build()

This would be very handy to update the store with

    store.write(operation, newData)

Not sure how it will affect method count though.

**Comment by sav007** [comment]
@digitalbuddha @BenSchwab I'm worry about method count if we generate builder for models and input types along with accessors for model fields. We have compiler config option to generate accessors or not for model fields, and by default it's set to true. What if we set  it by default to false, so we won't generate accessors for fields (I would even drop them at all as all fields are immutable). What do you think?
