### ISSUE TITLE
Cache not working when fields have null values.

### ISSUE THREAD

**Issue by eschlenz** [apollographql/apollo-android#598]
I think there might be a bug preventing objects from being cached. I'll try to summarize. Say we have
the following query:

```
query MyQuery() {
    messages {
      ... MessageFragment
    }
}

fragment MessageFragment on Message {
    id
    title
    description
}
```

And, let's say the GraphQL server returns `null` as the value of `title`, but `id` and `description` have non-null values. When the object Record is created for the cache, it looks like it omits any field with a `null` value. So `id` and `description` end up being the only saved fields on the Record.

When I attempt to run the query again, I would expect it to be pulled successfully from cache. That isn't happening, and the reason appears to be that because `title` could not be found on the Record, it can't fulfill the request. So it goes to the server.

@sav007

**Comment by eschlenz** [comment]
@sav007 I think the problem might be somewhat different than what I described earlier. I think the issue has more to do with the use of compound queries. 

The example I gave form above is fictitious, and just served to demonstrate an example of what I was seeing. A real world example of where the cache seems to be breaking down is the following:

```
query GalleryGraphQL($retailerId: Int, $categoryLimit: Int, $contentMax: Int, $retailerIds: [Int], $offerIds: [Int], $limit: Int, $products: Boolean!) {
  offerCategories(retailerId: $retailerId, limit: $categoryLimit, contentMax: $contentMax) {
      id
      category_type
      type
      collapsible
      default_view_state
      end_time
      expiration
      icon_url
      image_url
      launch
      name
      short_name
      num_preview_items
      raw_category_type
      retailers
      sort_order
      start_time
      content {
        id
      }
  },
  offers(retailerIds: $retailerIds, ids: $offerIds, limit: $limit) {
    ... OfferFragment
  }
}
``` 

Note that there are actually two different queries being combined there ^. In the first query, `content` holds different types of objects, one of which is an `Offer` type. In the second query, we are only asking for `Offer` types. 

I suspect the logic that tries to decide if it can pull everything from cache breaks down with this type of query. Let me know if you need the full queries and response data, and I can send it to you in a DM.

**Comment by sav007** [comment]
@eschlenz Am I right that you are requesting the same resource `Offer` with 2 different sets of fields?

**Comment by sav007** [comment]
Is your case is different from this test case:
`com.apollographql.apollo.NormalizedCacheTestCase#sameHeroTwice`

Query:
```
query SameHeroTwice {
  hero {
    name
  }
  r2: hero {
    appearsIn
  }
}
```

```
{
  "data": {
    "hero": {
      "__typename": "Droid",
      "name": "R2-D2"
    },
    "r2": {
      "__typename": "Droid",
      "appearsIn": [
        "NEWHOPE",
        "EMPIRE",
        "JEDI"
      ]
    }
  }
}
```

This test checks that response from first query is merged with response of second query.
Seems exactly what you doing.

**Comment by eschlenz** [comment]
@sav007 

I think so... just to be sure:

In the query I provided above, the first query `offerCategories` is fetching Category objects. Each Category object contains a list of `content` which can be several types of objects, including the one represented by `OfferFragment`. So basically in that first query we are fetching Categories and their list of Offer IDs.

The second query fetches the full Offer objects that the previous query was referencing.

We do it this way to prevent duplication of Offer objects in the response payload. If we had instead loaded the full Offer objects inside the Category `content` field, then some Offer objects would appear in the response multiple times (2 or more Categories can reference the same Offer). So that second query ensures we only pull exactly one copy of each Offer. Then we can associate them to the Category objects after the load.

**Comment by eschlenz** [comment]
@sav007 

This might have just been an issue with our own cache implementation that we plugged into Apollo. 

If you can't reproduce this, then feel free to close this out. My initial investigation definitely pointed to an Apollo issue, but I also had some bugs on my side. Once I stopped using the compound query and fixed some issues in my cache, things started working. 

At this point all I can say is there **might** be an Apollo issue with compound queries and caching, but I'm not 100% confident in that. If you have an easy way to verify one way or the other, then go for it. Otherwise feel free to close this out rather than waste time on it.

**Comment by sav007** [comment]
I guess I will close it for now, but please if you find that this is an issue on Apollo side then reopen.
I feel like you faced with unsatisfied condition, when second compound query  tries to get fields that are not in the cache yet.

**Comment by jmodrako** [comment]
I think that nulls are omitted in cache because of how `RecordFieldJsonAdapter.toJson()` method works underneath (`JsonUtf8Writer` to be precise, does not serialize nulls). Is there any way to call this method `setSerializeNulls(true)` outside of the apollo-client? And I forgot to mention, that we have LRU memory cache and sql based one, and this on sql is not working properly with nulls.

@sav007 is that what you also have in your setup?
@eschlenz cc ^^

**Comment by sav007** [comment]
Thank you for letting us know, we are going to verify this again.

**Comment by eschlenz** [comment]
@jmodrako 

We only have an LRU cache at the moment. 

I think the issue we were experiencing was due to our own LRU cache implementation. (We needed some custom invalidation logic that the stock solution didn't provide).
