### ISSUE TITLE
Why  slowly   than   before  when i  build the project?

### ISSUE THREAD

**Issue by xiaozhao0331** [apollographql/apollo-android#600]
It  is  so   slowly  than  before ,  what   i   can  do   ?

**Comment by sav007** [comment]
Could you please elaborate on this? What part of framework is slow?

**Comment by xiaozhao0331** [comment]
1.At first ,It is conflict with another  plugin  i   used   now,named "com.antfortune.freeline";   so   i must  abandon  freeline  ;
2.when   i  build the  project   i  found  a  layout "android.support.v7.widget.RecyclerView"  in  Android   is  not work ,  and   i must  updata  my    buildToolsVersion    at least '25.0.0'  then i can build , but   it's    "android.support.v7.widget.RecyclerView"  it's   not   work  too;

**Comment by xiaozhao0331** [comment]
when  i   use  appllo  i  have to updata  the buildToolsVersion   to  25.0.0. but   my old  buildToolsVersion is   24.0.2  ,i dont  know  why  i  couldn't   preview  the  xml    if   the xml   has   layout   belong  to androdi.support........          if   you  have  any idea  please tell me  , thankyou

**Comment by sav007** [comment]
24.0.2 build tools was released almost a year ago (Build Tools, Revision 24.0.3 (September 2016)). I believe eventually you should migrate to new one.

As for `com.antfortune.freeline` could you be more specific what conflict you get?

`android.support.v7.widget.RecyclerView` is not related to this project and it's part of google support library, you probably should ask more appropriate channel for this.

**Comment by sav007** [comment]
Closing as issue is not related to Apollo lib
