### ISSUE TITLE
Error:Execution failed for task ':app:generateDebugApolloIR'.

### ISSUE THREAD

**Issue by jsiva001** [apollographql/apollo-android#601]
I Got this issues when build the project 
Error:Execution failed for task ':app:generateDebugApolloIR'.
> Process 'command '/home/siva/Siva-Workspace/Samples/GraphQl/app/.gradle/nodejs/node-v6.7.0-linux-x64/bin/node'' finished with non-zero exit value 1

**Comment by digitalbuddha** [comment]
Run from command line and do - - info - - stacktrace you should see error.

**Comment by sav007** [comment]
If you such error it means the issue with one of your graphql query

**Comment by droidprofit** [comment]
I have the same issue, but don't know what I'm doing wrong. My graphql file contains only 1 mutation:  
 mutation FetchGetCode($email: String!, $key: String!) {
             get_code(email: $email, key: $key) {
               status,
               message
             }
 }

**Comment by VanJFlorez** [comment]
Hi, try to update your local npm. I get same error having npm 5.6.0, after update to 5.8.0 I get the generated classes...

**Comment by luiss2113-dev** [comment]
Acabo de solucionar este error, en mi schema.json mi mutación estaba como login y contenía dos args que era userId y password, pero en mi shema.gralpql esto variaba, me guié por mi json y reubiqué los campos para hacer lo que la consulta requiere y listo, corrigió mi error
