### ISSUE TITLE
Build failure - \node-v6.7.0-win-x64\node.exe'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by ImGokulM** [apollographql/apollo-android#608]
I have installed Node Js version v6.11.0. But I'm getting the following error. Please help me on this.

Information:Gradle tasks [:apollo-android-support:generateDebugSources, :apollo-android-support:mockableAndroidJar, :apollo-android-support:prepareDebugUnitTestDependencies, :apollo-android-support:generateDebugAndroidTestSources, :apollo-espresso-support:generateDebugSources, :apollo-espresso-support:generateDebugAndroidTestSources, :apollo-espresso-support:mockableAndroidJar, :apollo-espresso-support:prepareDebugUnitTestDependencies, :apollo-integration:generateDebugSources, :apollo-integration:mockableAndroidJar, :apollo-integration:prepareDebugUnitTestDependencies, :apollo-integration:generateDebugAndroidTestSources, :apollo-sample:generateDebugSources, :apollo-sample:mockableAndroidJar, :apollo-sample:prepareDebugUnitTestDependencies, :apollo-sample:generateDebugAndroidTestSources]
Error:Execution failed for task ':apollo-integration:generateDebugApolloIR'.
> Process 'command '<location>\apollo-android-master\apollo-integration\.gradle\nodejs\node-v6.7.0-win-x64\node.exe'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:Total time: 3.551 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by MattiSchnurbusch** [comment]
I'm having the exact same issue tried around with different node versions and tried different order of gradle tasks also. Any Idea how this could be solved?

**Comment by marwanad** [comment]
Can you try running with `--info --stacktrace` and post the output?

**Comment by YkSix** [comment]
```
Successfully started process 'command '/Users/xxx/Documents/FirstGraphQL/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node''
.../graphql/zzz/firstgraphql/GithuntFeedQuery.graphql: Apollo does not support anonymous operations
error: Validation of GraphQL query document failed
:app:generateDebugApolloIR FAILED
:app:generateDebugApolloIR (Thread[Daemon worker,5,main]) completed. Took 0.579 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugApolloIR'.
> Process 'command '/Users/xxx/Documents/FirstGraphQL/app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1
```

**Comment by digitalbuddha** [comment]
You need to name your query like so https://github.com/apollographql/apollo-android/blob/master/apollo-sample/src/main/graphql/com/apollographql/apollo/sample/GithuntFeedQuery.graphql#L1

**Comment by Pkmmte** [comment]
I had this issue with Apollo 0.4.1 and Kotlin 1.1.51 and the only thing that worked was downgrading Kotlin to 1.1.50.

**Comment by nikolasburk** [comment]
@marwanad sorry this is a noob question but what's the command in the terminal that I should add the `--info --stacktrace` option to? and in which directory does it need to be invoked?

**Comment by singhalmanav** [comment]
I'm also getting the same error. I double checked the schema.json and .graphql query file.

Error:org.gradle.process.internal.ExecException: Process 'command 
'......app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1

I'm using apollo v0.4.4 and kotlin v1.2.20. Can anyone tell me why Apollo is throwing this error during code generation?

**Comment by vincenthauser** [comment]
All my queries are named as in https://github.com/apollographql/apollo-android/blob/master/apollo-sample/src/main/graphql/com/apollographql/apollo/sample/GithuntFeedQuery.graphql#L1 so that is *not* the issue.

**Comment by vincenthauser** [comment]
Ok, I have the exact same problem but I could build in command line but not through Android Studio. Running with `--info` in AS's terminal I got this:

```
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\vince\dev\app\build\apollo-codegen\node_modules\apollo-codegen' -> 'C:\Users\vince\dev\app\build\apollo-codegen\node_modules\.apollo-codegen.DELETE'
npm ERR!     at Error (native) parent: 'apollo-android' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```

So for me it seems to be a permissions problem

**Comment by singhalmanav** [comment]
I'm getting this error with Apollo v0.4.4 but the code-gen works fine with v0.4.3.

Error:org.gradle.process.internal.ExecException: Process 'command
'......app/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1

**Comment by wax911** [comment]
Apollo 0.4.4
Ubuntu 17.10
Error:Execution failed for task ':app:installApolloCodegen'.
> Process 'command './app/.gradle/nodejs/node-v6.7.0-linux-x64/bin/node'' finished with non-zero exit value 243

Same issue here as well, even with the sample project, only difference is instead of getting exit value of 1 I get exit value of 243

**Comment by VanJFlorez** [comment]
Pay attention that every query has a name...

**Comment by hatched-nari** [comment]
I had the same issue, and was able to resolve it by naming my query as mentioned above.

**Comment by hopstad** [comment]
@hshahdoost 
Same here man. A variable was changed on the graphql server and I needed to update my query. Therefor also needed to update the schema.json and the shitshow started. 

How did you downgrade the apollo-codegen cli ?

**Comment by hshahdoost** [comment]
@hopstad first make sure you are not using the `apollo` cli (the old `apollo-codegen` has been deprecated and been replaced by this new command). the generated schema by `apollo` cli is not readable by this command.
Then go to this [url](https://www.npmjs.com/package/apollo-codegen) to see the available versions of `apollo-codegen`.

And finally uninstall your current apollo-codegen and install it in the following format
```
npm install apollo-codegen@0.17.0-alpha.1
```
**PS**: by the time I faced this error, Apollo android could not read the schema generated by `apollo` cli command, It might not be like this in the future versions so the best practice would be to first update your library to the latest version and then if it could not read the schema try using `apollo-codegen` command

**Comment by hopstad** [comment]
@hshahdoost 
Thanks mate! You saved my brain from exploding.

Solved by removing apollo and installing the new one. Then using new command for downloading schema : `apollo schema:download --endpoint=https://something.com`

**Comment by hopstad** [comment]
@hshahdoost 

Nevermind.. Still not working. I thought it was, but was wrong. What I did was uninstall apollo and tried the new one (apollo schema:download). The error was now of a different type and said the following:

> GraphQL schema file should contain a valid GraphQL introspection query result

Tried to uninstall again and download a old apollo version (0.20.2) and did the same old "apollo-codegen" and them I'm back to the same error as before:

> error: Validation of GraphQL query document failed

**Comment by hshahdoost** [comment]
@hopstad I kind of got surprised because in your mention above, you were using `apollo` instead of `apollo-codegen`

> Solved by removing apollo and installing the new one. Then using new command for downloading schema : apollo schema:download --endpoint=https://something.com

**Comment by kpjofficial** [comment]
I am facing this error using AWS-Amplify. `apollo` is part of `Amplify` now. I am facing the error like

> error: Validation of GraphQL query document failed

**Comment by kpjofficial** [comment]
> @hshahdoost
> 
> **EDIT**
> Finally fixed. Totally removed everything. npm, apollo etc. Deleted .grade file in Android Studio. Reinstalled everything (apollo-codegen not apollo) and it works now.

.grade file?

**Comment by hshahdoost** [comment]
@kpjofficial no, There is nothing wrong with the .gradle file the `apollo` node command is incompatible with the new apollo android. All you have to do is to the use the old `apollo-codegen` instead. [here is a list of available versions](https://www.npmjs.com/package/apollo-codegen) install the old version and use it to generate your schema file.

**Comment by Nieltz** [comment]
Hey @kpjofficial, I am facing the same issue, which naming conventions have you used to fix it?

**Comment by kpjofficial** [comment]
@Nieltz By naming conventions, I meant to avoid usage of special characters and naming in camelcase but then you can also check 
https://facebook.github.io/graphql/June2018/#sec-Appendix-Notation-Conventions

**Comment by adrian1388** [comment]
> @kpjofficial no, There is nothing wrong with the .gradle file the `apollo` nodejs command is incompatible with the new apollo android. All you have to do is to the use the old `apollo-codegen` instead. [here is a list of available versions](https://www.npmjs.com/package/apollo-codegen) install the old version and use it to generate your schema file.

I recently tried `apollo-codegen`, after receiving the incompatibility of `apollo` result:
`apollo-codegen download-schema http://localhost:8080/graphql/`
but actually, the error says nothing:
`error: Errors in introspection query result:`
...
```
apollo-codegen --version
0.20.2
```
I'm stuck here.

**Comment by jazart** [comment]
Also having the same issue. I installed apollo-codegen to create the schema.json but I'm still getting a build failure with exit code 1.

**Comment by adrian1388** [comment]
Fixed for me:

The schema generated by 
`apollo schema:download --endpoint=http://localhost:8080/graphql`
or
`apollo service:download --endpoint=http://localhost:8080/graphql`

results without the "data" name.

Adding 
```
{
  "data": {
    "__schema": {...}
  }
}
```
with the corresponding spaces, finished the ':generateMainApolloIR' subtask, generating the classes for the queries on *.graphql files successfully.

**Comment by RachitKalra** [comment]
> Fixed for me:
> 
> The schema generated by
> `apollo schema:download --endpoint=http://localhost:8080/graphql`
> or
> `apollo service:download --endpoint=http://localhost:8080/graphql`
> 
> results without the "data" name.
> 
> Adding
> 
> ```
> {
>   "data": {
>     "__schema": {...}
>   }
> }
> ```
> with the corresponding spaces, finished the ':generateMainApolloIR' subtask, generating the classes for the queries on *.graphql files successfully.

Been stuck on this , still not working , can you just walk me through what steps you took , 

Apollo gradle plugin version etc.

:(
