### ISSUE TITLE
Migrate publishing to jcenter

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#617]
Migrate scripts for publishing to jcenter instead of sonatype.
Additionally as @martijnwalraven suggested change package name to `com.apollographql.client`

**Comment by sav007** [comment]
@Pkmmte do you mind to provide feedback why you don't support this idea?

**Comment by digitalbuddha** [comment]
Are we still planning on doing this?

**Comment by sav007** [comment]
We actually did this. Closing
