### ISSUE TITLE
Support for Reactor library

### ISSUE THREAD

**Issue by yschimke** [apollographql/apollo-android#627]
Feature request - low urgency but would be useful to avoid reimplementing the code externally or bridging via RxJava2.  This is a fairly well adopted library that is an alternative to RxJava.

http://projectreactor.io/
https://github.com/reactor/reactor-core

**Comment by yschimke** [comment]
n.b. I'm unable to contribute without a lot of paperwork, and I suspect code in similar in complexity to the single file needed for RxJava2

**Comment by hzsweers** [comment]
Isn't the point of ReactiveStreams that you can interop via the common interface?

**Comment by yschimke** [comment]
Yep, it does work.  A couple of things that can be improved however

1) Avoid an additional library dependency on RxJava2
2) Go straight to Reactor types including Mono (max 1 response) 

I assume mostly a class like this https://github.com/apollographql/apollo-android/blob/master/apollo-rx2support/src/main/java/com/apollographql/apollo/rx2/Rx2Apollo.java

cc @smaldini

**Comment by digitalbuddha** [comment]
Non  of the contributors use reactor and since this is mostly an android lib I am going to close this issue. Feel free to create your own adapters similar to the rx2 one. I do not feel there is any gain from them living in this repo rather than a separate one

**Comment by yschimke** [comment]
FWIW reactor-core is Android O only which is another reason to do this separately.

**Comment by smaldini** [comment]
Yes since we are Android O minimum we should host that separately. We were thinking about backporting an exclusively kotlin-based version for our android friends in the future if there is some interest for it.

**Comment by aoudiamoncef** [comment]
Hi @sav007 @tasomaniac @martinbonnin,

I tried to implement this feature. If you are interested to add it to Apollo Android, I'll be happy to continue working on it.

Thanks

**Comment by aoudiamoncef** [comment]
@smaldini, thanks for your feedback

I'll publish in a separate project ASAP.

It's more interesting for Java/Kotlin backend projects than Android applications.

**Comment by aoudiamoncef** [comment]
Hi @smaldini, 

It could be interesting to reopen this issue ?

**Comment by martinbonnin** [comment]
Given that development will happen in `https://github.com/aoudiamoncef/apollo-reactor-support`, better discuss it over there? 

PS: did you get the wrong `@` mention? Stephane hasn't been active on this ticket since 2017?
