### ISSUE TITLE
Operation state observer

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#632]
After a second thought on #588 and #606  here is the proposal to introduce `StateObserver`.

We are going to ~introduce new~ modify API ~to~ of ~`enqueue` operation~ `Callback`:  ~`void enqueue(StateObserver<T> stateObserver)`~ add a new callback `onStateChanged(State<T> newState)` where `State<T>` :

```
public interface State {
   
    public static final class Scheduled implements State {
    }

    public static final class FetchFromCache implements State {
    }

    public static final class FetchFromNetwork implements State {
    }

    public static final class Response<T> implements State {
      public final Response<T> response;

      public Response(Response<T> response) {
        this.response = response;
      }
    }

    public static final class Completed extends State {
    }
  }
```

~With this approach we leave existent API to `enqueue` operation based on callback and introduce new one that explicitly defined as state observer.~

Please feel free to suggest better naming for API. 

@BenSchwab @digitalbuddha @mandrizzle any thoughts?

**Comment by BenSchwab** [comment]
Couple questions:

what is the use case of have the State wrap the call? 
What would the final use API look like? Would I call `enqueue(ApolloCallback).enqueue(stateObesrver)`

**Comment by sav007** [comment]
> What would the final use API look like? Would I call enqueue(ApolloCallback).enqueue(stateObesrver)

You won't be able to call in this way as first enqueue call will mark as executed and second will fail with an error.

> what is the use case of have the State wrap the call?

There is no really reason I thought that you can potentially have a generic listener to monitor more then one query, so the ref to call is just for info purpose. 

Yeah I will agree with you to extend existent callback just introduce the new `onStateChanged(State<T> newState)` call.

**Comment by digitalbuddha** [comment]
little confused by conversation, I think I'm on same page as Ben where I see this as an optional abstract method that use needs to override in callback. Similar to how rxjava2 has `onSubscribe` now
