### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by dima-ostapovets** [apollographql/apollo-android#636]
Hello. I'm new in graphql / apollo. Is it currently possible to use subscriptions on Android?

**Comment by digitalbuddha** [comment]
Currently apollo android does not support subscriptions. This is a feature that we are hoping to support in the future.

**Comment by michaelspeed** [comment]
this is a very important feature. any way is there a polling interface like react-apollo : startPolling() and stopPolling()?

**Comment by Gregoirevda** [comment]
Any updates??

**Comment by LeeWong** [comment]
Any updates? Thanks.

**Comment by digitalbuddha** [comment]
No, we are open to external contributions. There was some discussion but nothing materialized. No contributor needs the feature currently but it is open source 🙂

**Comment by digitalbuddha** [comment]
If anyone wants to contribute Pls join us on our slack http://www.apollostack.com/#slack in room #androidcore thank you
