### ISSUE TITLE
GraphQLList of GraphQLLists?

### ISSUE THREAD

**Issue by damonaskavio** [apollographql/apollo-android#637]
Good day, I'm having an issue where Android Studio is giving the error `Error:Execution failed for task ':app:generateDebugApolloClasses. com.squareup.javapoet.ParameterizedTypeName cannot be cast to com.squareup.javapoet.ClassName'` when trying to build a query with the following member.
```json
              "name": "myList",
              "description": null,
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "LIST",
                  "name": null,
                  "ofType": {
                    "kind": "LIST",
                    "name": null,
                    "ofType": {
                      "kind": "SCALAR",
                      "name": "Float",
                      "ofType": null
                    }
                  }
                }
              }
```

Only happens when there is a LIST of LISTs. Just wondering is this an issue or is there something that needs to be done on my end? I have tried running the query on my local GraphQL and it has no problems fyi. Thanks for any help.

**Comment by sav007** [comment]
Currently we don't support list of list. But this is an issue for sure.
