### ISSUE TITLE
Upload file(image)

### ISSUE THREAD

**Issue by raderio** [apollographql/apollo-android#640]
Please add an example of how to upload a file(image).

**Comment by sav007** [comment]
What do you mean by that? GraphQL spec doesn't provide such feature. You can upload by using raw OkHttp request.

**Comment by raderio** [comment]
So, you can't upload a image by GraphQL? Instead we should use REST?

**Comment by sav007** [comment]
That's correct, I would even suggest just use raw OkHttp request.
https://github.com/square/okhttp/wiki/Recipes#posting-a-file

**Comment by raderio** [comment]
In graphql-java I get an answer

> You have to (ab)use the context for this.
> When executing an operation, you can optionally provide a context (to graphQl.execute). If you put the uploaded binary (or entire HttpRequest object) there, you can get a hold of it from DataFetcher.

**Comment by raderio** [comment]
https://github.com/facebook/graphql/issues/349#issuecomment-326064720

**Comment by digitalbuddha** [comment]
A pr would be considered. I personally don't believe there is much value over just using the underlying okhttp instance to do the same thing

**Comment by truongsinh** [comment]
I'm making PR https://github.com/apollographql/apollo-android/pull/1182 , but would appreciate somebody help me with the document of usage. Test cases are included

**Comment by sav007** [comment]
Closing. Was added with recent release.
