### ISSUE TITLE
Can I create schema.json automatically using apollo-codegen?

### ISSUE THREAD

**Issue by rnitame** [apollographql/apollo-android#642]
i want to execute apollo-codegen at project build.
Is there a way? 🤔

**Comment by sav007** [comment]
but what do you want to get as the output of codegen?

**Comment by digitalbuddha** [comment]
He wants to have the code gen output a schema in a location that apollo will pickup.

**Comment by sav007** [comment]
I believe we have this gradle task `ApolloSchemaIntrospectionTask`.

**Comment by sav007** [comment]
Example described in description https://github.com/apollographql/apollo-android/pull/461

**Comment by rnitame** [comment]
> He wants to have the code gen output a schema in a location that apollo will pickup.

yes!

@sav007 thanks, i've created task!
by the way, Can I change url / output strings each ProductFlavor?

**Comment by sav007** [comment]
Don't know never tried :)

**Comment by digitalbuddha** [comment]
I don't think you will be able to do this with flavors due to flavors being an android specific construct while apollo gradle plugin does not depend on android plugin.  gradle.properties or cli is probably best you can do to drive the url
