### ISSUE TITLE
Make generateModelBuilder generate deep builders (instead of shallow)

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#643]
Making the generated builders deep would make modifying nested data much easier.

See https://github.com/apollographql/apollo-android/pull/622

**Comment by martinbonnin** [comment]
Something that just crossed my mind: not sure how to represent Nullable nested fields if we make everything a builder

If `data().toBuilder().video().channel()` returns a `Channel.Builder` then it's impossible to set channel to `null`. Unless we make `Channel.Builder.build()` return `null` that seems a bit strange

**Comment by martinbonnin** [comment]
Also I believe the current (shallow) implementation does not work for lists as it just copies the list instead of cloning them.

**Comment by sav007** [comment]
The way how I see this is make a deep copy of builders, so for instance `Data` has a `Hero` field, then `data.toBuilder()` will return a new builder with deep copied hero builder (it will call toBuilder recursively for all nested objects). Then we have smth like this:

```
data.toBuilder()
  .hero(new Hero()) // this way we can assign completely a new instance of Hero or null
  .hero() // will return the Hero.Builder if it's not null
  .name("test")
  .friends()[0] // will return the first item of list of Friend.Builder
  .name("friend1")
  .etc
```

The main drawback of this approach is that we switching the context in chain whenever we call for example `hero()` as after this call we switching to `Hero.Builder` instead of `Data.Builder`

Let me know what do you think

**Comment by martinbonnin** [comment]
Looks good to me. The overloaded `.hero()` method is a nice way to assign null indeed

**Comment by sav007** [comment]
I guess this is would be even better:
```java
public Builder hero(@Nonnull Consumer<Hero.Builder> mutator) {
    Hero.Builder builder = hero != null ? hero.toBuilder() : Hero.builder();
    
    mutator.accept(builder);
    
    this.hero = builder.build();
    return this;
  }

public Builder friends(@Nonnull Consumer<List<Hero.Builder>> mutator) {
    List<Friend.Builder> builders = new ArrayList<>();
    if (this.friends != null) {
        for (Friend item : friends) {
            builders.add(item != null ? item.toBuilder() : null);
        }
    }
    
    mutator.accept(builders);

    List<Friend> friends = new ArrayList();
    for (Friend item : builders) {
        friends.add(item != null ? item.build() : null);
    }
    this.friends = friends;
    return this;
}
```
