### ISSUE TITLE
Query deduplication

### ISSUE THREAD

**Issue by sacrefacker** [apollographql/apollo-android#646]
When two identical queries with identical parameters are requested at the same time, it results in two identical server requests.

It would probably be good if ApolloClient just added the callback from new query to the similar existing query. 

The issue was mentioned in apollographql/apollo-client#956 and apollographql/apollo-client#1070

**Comment by digitalbuddha** [comment]
I believe this is a tough problem to solve and is easier handled in something like a repository layer above apollo client. For instance I use Guava Cache which have a blocking callback for retrieval of values based on a key.
