### ISSUE TITLE
Allow to send optional null value in GraphQL input object types and arguments

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#652]
Current implementation of generation of GraphQL input types doesn't allow to handle 2 states:
- the value explicitly set to `null` and must be sent to server in order to nulify the field
- the value is undefined by default (user didn't set it explicitly but it's null)  so we don't need to send it to the server.

Here is the actual use case, let's say we have `AddressInput` with optional fields `phone`, `email` etc. Some times we want to have partial update so to update only `phone` without touching `email` in this case we don't need even to send `email` to the server. Another case we want to reset the `email` field to `null` so we need to send it.

The proposal is to have some wrapper around this  optional values to keep track if user actually set explicitly value and we need to send it or if it wasn't touched then we don't need to send it. And the API must be explicit in this case.

**Comment by sav007** [comment]
@BenSchwab @digitalbuddha any thoughts?

From @martijnwalraven 
> eah, that definitely gets a bit hairy! in swift I ended up using nested optionals as the representation for input object fields. so that allows you to differentiate between `.null` (value undefined), `.some(.null)` (value is nil) and `.some(.some(<value>))` (value set). it’s pretty natural to use in swift because types are inferred and most conversions get made automatically. the only time you need to worry about this is when you want to pass in an explicit `nil`.
so what you get is `ReviewInput(stars: 5, commentary: nil)` (commentary undefined) vs. `ReviewInput(stars: 5, commentary: .some(nil))` (commentary is `null`)
(`nil` is a literal that represents the `.null` case of an optional)

**Comment by sav007** [comment]
Here is the proposal:
```java
public final static class InputValue<T> {
  public final T data;
  public final boolean defined;

  private InputValue(T data, boolean defined) {
    this.data = data;
    this.defined = defined;
  }

  public static <T> InputValue<T> defined(@Nullable T data) { 
     return new InputValue(data, true);
  }

  public static <T> InputValue<T> undefined() {
     return new InputValue(null, false);
  }  
}
```

That allows to have next logic in serialization part:
```java
if (value.defined) {
  // serialize value.data  even if it's a null
} else {
 // do nothing
}
```

So here is how the generated GraphQL input type `ColorInput` will look like:
```java
public final class ColorInput {
  private final InputValue<Double> green;
  ...
  public static final class Builder {
    ...
    public Builder green(InputValue<Double> green) {
      this.green = green;
      return this;
    }
```

The usage from the user side:
```java
ColorInput.builder()
  .green(InputValue.defined(1.0D)) // will send 1.0
  .green(InputValue.defined(null)) // will send null
  .green(InputValue.undefined()) // won't save anyting
```

**Comment by BenSchwab** [comment]
@sav007 Can `InputValue` be hidden in the generated builder? Seems like user can convey all needed information via builder. To summarize:

To optimize compile safety we would want:
- Non-null fields in builder constructor
- optional (nullable) fields in builder methods

So let's say we have
```
input ColorInput {
  green: Double
  blue: Double!
}
```
We could do
```
ColorInput.builder(1.0D)
     .green(2.0D)
```
For null
```
ColorInput.builder(1.0D)
     .green(null)
```
For undefined
```
ColorInput.builder(1.0D);
```

Internally, the builder could use the `InputValue` you proposed to track nullability for `builder.build` validation.

**Comment by sav007** [comment]
Right, we can hide from user but one case left:
```java
ColorInput.Builder builder = ColorInput.builder();
builder.green(1.0D)
builder.green(null)
...
builder.green(???) // ??? how to reset it back to undefined
```

not sure if it's high important for now to have?

**Comment by BenSchwab** [comment]
Ahh good point.

Seems like we have the following options.
1) Your original proposal (slightly more clunky in the general case, but robust)
2) The pure builder approach (best UX for general experience)

**Comment by sav007** [comment]
let's move with the second for now, and revisit it later

**Comment by BenSchwab** [comment]
Sorry accidentally posted too soon, added third option. But, I don't have strong opinion between them. I suppose if we start with 2, we can always add 3 in a backwards compatible manner.
