### ISSUE TITLE
Allow deserializing models with json files in tests

### ISSUE THREAD

**Issue by scottkennedy** [apollographql/apollo-android#653]
I'm trying to write some unit tests where I need the model objects, but there doesn't seem to be a way of doing this without setting up a mock server that takes in a request, which is a lot of overhead for a unit test.

**Comment by digitalbuddha** [comment]
I'm not sure I understand what you are trying to achieve or what is lacking?

**Comment by sav007** [comment]
You can try to replicate the logic inside server response body parser https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/HttpResponseBodyParser.java#L36

where you `replace response.body().source()` with json string

**Comment by digitalbuddha** [comment]
Can you use mockito?

**Comment by mandrizzle** [comment]
Mocking a JSON model is a lot of effort, I would rather use JSON and deserialize my models from that

**Comment by sav007** [comment]
@mandrizzle any model generated by Apollo including fragments, has a `Mapper` class, that can be used to deserialize from JSON. It has one method `map(ResponseReader)` where response reader can be custom implementation that backed by string json.

**Comment by scottkennedy** [comment]
Do you have any example of a customer reader?

**Comment by sav007** [comment]
I don't have right now, but will come up with smth later this week

**Comment by sidgrover21** [comment]
Guys thanks a lot for this. You've saved a me a lot of effort in my unit tests.
