### ISSUE TITLE
optimize classes generation if we see them identical to have only one

### ISSUE THREAD

**Issue by digitalbuddha** [apollographql/apollo-android#655]
Consider this fragment
Fragment Asset{
Card
... OnVideo{
     Id
}
}

Apollo generates Asset$Card and Asset$Card1 since both asset or video can contain card. Those two fields are actually the same. Our code gen should be smart enough to not generate two classes for Card

**Comment by sav007** [comment]
Yeah, it's definitely nice to have, but at the same time you can use fragment for such case. That's why I guess it's low priority for now.
