### ISSUE TITLE
Gradle plugin not automatically pulling in runtime dependencies

### ISSUE THREAD

**Issue by stephen-workpop** [apollographql/apollo-android#656]
It is my understanding that by including the Apollo Gradle plugin, it should automatically pull in the module level dependencies such as apollo-runtime and apollo-android-support.

**Repro Steps:**
Add the following lines to your top level Gradle file:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.apollographql.apollo:gradle-plugin:0.4.1'
    }
}
```

**Expected Results:**
The Apollo runtime dependencies will automatically be added to the project.

**Actual Results:**
I must add the following lines for all of my Apollo-related imports to resolve:
```
compile "com.apollographql.apollo:apollo-runtime:0.4.1"
compile "com.apollographql.apollo:apollo-android-support:0.4.1"
compile "com.apollographql.apollo:apollo-rx2-support:0.4.1"
```

**Comment by CristianGM** [comment]
I just added the rx2-support and it's working fine with the 0.4.1 in our project, are you sure?
Are you applying the plugin on your module?

**Comment by stephen-workpop** [comment]
The issue might be that I am applying the plugin in a library module. I have two Android apps that build out of one Android Studio project. There is a module for app1, a module for app2, and a module for a library of shared code.

**Comment by jaredsburrows** [comment]
Based on this PR and issue: https://github.com/apollographql/apollo-android/issues/722, I do not believe this plugin will go that route. This makes this plugin harder to maintain by dynamically adding dependencies at configuration time. It is best to manually add them. @digitalbuddha

**Comment by stephen-workpop** [comment]
Thanks @jaredsburrows. Closing this issue.
