### ISSUE TITLE
Input fields of kind List with Default value generates code that cannot compile

### ISSUE THREAD

**Issue by brownpixel** [apollographql/apollo-android#673]
If a schema.json file has an input field of the kind LIST with a default value, the gradle plugin generates code that cannot compile

Example json:
`
"inputFields": [
            {
              "name": "test",
              "description": "test desc",
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
                }
              },
              "defaultValue": "[\"test1\",\"test2\",\"test3\"]"
            }
          ],
`

The generated class would end up with something like:
`List<String> test = [test1, test2, test3];`

**Comment by sav007** [comment]
@martijnwalraven it seems that apollo-codegen ignores the default values for list of enums and broken for list of custom scalar types, having this schema:
```json
{
              "name": "listOfCustomScalar",
              "description": "for test purpose only",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "Date",
                  "ofType": null
                }
              },
              "defaultValue": "[\"2017-04-16\", \"2017-04-17\", \"2017-04-18\"]"
            },
            {
              "name": "listOfEnums",
              "description": "for test purpose only",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "ENUM",
                  "name": "Episode",
                  "ofType": null
                }
              },
              "defaultValue": "[\"JEDI\", \"EMPIRE\"]"
            }
```

generates this IR:
```json
{
					"name": "listOfCustomScalar",
					"description": "for test purpose only",
					"type": "[Date]",
					"defaultValue": [
						false,
						false,
						false
					]
				},
				{
					"name": "listOfEnums",
					"description": "for test purpose only",
					"type": "[Episode]"
				}
```

**Comment by martijnwalraven** [comment]
@sav007: Hmmm, that does seem like a bug. Could you open an issue for this on the `apollo-codegen` repo?

**Comment by sav007** [comment]
https://github.com/apollographql/apollo-codegen/issues/256
