### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by AlphaGao1993** [apollographql/apollo-android#685]
when I add a element or remove a element by a list from Data Class, it throw a UnsupportedOperationException , it obvious that you are using a unmodifiedList implement, So why?

**Comment by sav007** [comment]
All generated data models are immutable, this is the best practise the same way as any other library as AutoValue, Immutable generate models. And if you really want to mutate list then just do this: `new ArrayList(someList)`
