### ISSUE TITLE
Release cadence? 

### ISSUE THREAD

**Issue by eschlenz** [apollographql/apollo-android#691]
Looking at the historical releases, I don't see any kind of regular pattern to the Apollo releases. It appears a release happens at arbitrary times. I'm hoping to start a discussion on this, and to share some information from our perspective.

Our team heavily relies on Apollo. We have identified and shared with the Apollo team several critical bugs, and are very appreciative of how quickly the Apollo team addresses them. One recent issue we reported was fixed a few weeks ago, but we are still waiting on it to be released. Because there is no regular release cadence, nor a schedule to when a release can be expected, we end up checking the Github project every day to see the status. 

We are aware that we could use the SNAPSHOT builds, but this is really not a best practice in my opinion. We, and I'm sure others, would prefer to use stable release builds for our production versions of our app, for obvious reason. 

A best case scenario would be a regular release cadence (ie: every couple of weeks), if possible. At the very least, would you guys consider releasing more frequently than you currently are? And perhaps being more vocal about when the upcoming release is tentatively scheduled for? 

This would be tremendously helpful!

**Comment by digitalbuddha** [comment]
Thanks for using apollo! Sorry for not doing more stable releases. We are going to make a release in next few days. After than we are preparing for version 1.0. For that version we will have package name changes to be more in line with other apollo clients. I'm not sure if biweekly will work as we don't always have new code. We do have a slack channel you can join and if you ever need a release it won't take more than a few days for us to get it up. Let us know if there's anything else we can do to make the process more seamless for you.

**Comment by eschlenz** [comment]
@digitalbuddha Sounds good, thanks!
