### ISSUE TITLE
Could not set unknown property 'schemaFilePath' for object of type com.apollographql.apollo.gradle.ApolloExtension. 

### ISSUE THREAD

**Issue by AlphaGao1993** [apollographql/apollo-android#699]
my apollo config in gradle file, and I'm using version 0.4.1:
```
apollo {
    generateModelBuilder = true
    schemaFilePath = "/path_to_schema_file/my-schema.json"
    outputPackageName = "com.my-example.graphql.api"
}
```

**Comment by sav007** [comment]
I believe that this is a new feature that was introduced in 0.4.2

**Comment by AlphaGao1993** [comment]
oh really? but I see it in before you publish release 0.4.2 haha... and when I upgrade to 0.4.2, it give me such a error:
```
Error:Could not find com.apollographql.apollo:gradle-plugin:0.4.2.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/apollographql/apollo/gradle-plugin/0.4.2/gradle-plugin-0.4.2.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/apollographql/apollo/gradle-plugin/0.4.2/gradle-plugin-0.4.2.jar
    https://jcenter.bintray.com/com/apollographql/apollo/gradle-plugin/0.4.2/gradle-plugin-0.4.2.pom
    https://jcenter.bintray.com/com/apollographql/apollo/gradle-plugin/0.4.2/gradle-plugin-0.4.2.jar
Required by:
    project :
```

**Comment by sav007** [comment]
we changed the artifact id
https://github.com/apollographql/apollo-android#adding-apollo-to-your-project

`apollo-gradle-plugin`

**Comment by AlphaGao1993** [comment]
Now I resolve it, Thank you very much.

**Comment by Nazacheres** [comment]
Greetings! Can not set the path to root project, tried with different ways:
`"${project.rootProject.name}/graphql/schema.json"`
`"${project.rootProject}/graphql/schema.json"`
`"$rootProject/graphql/schema.json"`

What am I doing wrong? 
Should it be relative or somewhy absolute?

**Comment by martygeek** [comment]
has this been resolved?   I am trying to move my schema.json so that it is visible, along with the graphql query files, to both an Android folder and iOS folder.   Setting the schemaFilePath ought to work, but it never builds the expected generated files unless I leave it in src/main adjacent to java/ and res/

Using 1.0.0-alpha5 of Apollo client

**Comment by payalyadav018** [comment]
> Now I resolve it, Thank you very much.

how you resolve it?
