### ISSUE TITLE
Move ApolloCall class into the apollo-api module? 

### ISSUE THREAD

**Issue by hannanabdul55** [apollographql/apollo-android#702]
## Description
Since the `apollo-api` module looks like a module which is supposed to be the front-facing api for the library, it makes sense to have the `Response` which you get back after an `Operation` to also be contained in the same module. It's good that all the Data Access and mutation Objects(like `Query`and `Mutation` is there. But the `apollo-api` library is complete only when the `ApolloCall` as well as the `Callback` objects are there in the same module. In that way, to create an API interface on top of Apollo will require only this one module(with no other dependencies), rather than the entire `apollo-runtime`.

**Comment by digitalbuddha** [comment]
@sav007 can speak on this more, my understanding is that `API` gets used by both the code gen and the runtime but we will do what makes things easiest for community as long as it makes sense

**Comment by hannanabdul55** [comment]
Yeah, if not the entire `ApolloCall` class, at least the internal `ApolloCall.Callback` class would make more sense to reside in the `apollo-api` module rather than being in the runtime one.

**Comment by sav007** [comment]
Is there any use case when you want to use api module without runtime? Api module is completely useless without runtime. Current version of api module is was only designed to be shared between code gen and runtime only.

As for the callback I didn't get it. `Operation` doesn't define any callbacks. `ApolloCall `  defines them. Could you please clarify on that.

**Comment by hannanabdul55** [comment]
Oh sorry about the confusion. `ApolloPrefetch` has its own `Callback` class and does not inherit `ApolloCall`. Isn't that a little odd? Shouldn't it inherit `ApolloCall` class? 
Also regarding your first question, I am trying to create a module to stay as a front facing interface from apollo in a library of my own. The entire `apollo-runtime` would be imported in the main app using my library(even if the library does not use the Apollo runtime). I am just trying to avoid importing the entire `apollo-runtime` along with its dependencies into the library just to keep my interface module lightweight. That is why it would be ideal to have a full fledged `API` module.

**Comment by sav007** [comment]
> Also regarding your first question, I am trying to create a module to stay as a front facing interface from apollo in a library of my own. The entire apollo-runtime would be imported in the main app using my library(even if the library does not use the Apollo runtime). I am just trying to avoid importing the entire apollo-runtime along with its dependencies into the library just to keep my interface module lightweight. That is why it would be ideal to have a full fledged API module.

Makes sense, so you want to move  ApolloCall and other top level interfaces to api module?

> ApolloPrefetch has its own Callback class and does not inherit ApolloCall. Isn't that a little odd? Shouldn't it inherit ApolloCall class?

If you take a look at signature of callback they are different. ApolloPrefetch call doesn't have response, it just notifies about completion. While ApolloCall notifies about the result, Response

**Comment by hannanabdul55** [comment]
@sav007 Yeah I think it would be awesome if we can move it to the `apollo-api` module. Should I go ahead and create a PR for it? Let me know if there are any other modifications which has to be made.

> If you take a look at signature of callback they are different. ApolloPrefetch call doesn't have response, it just notifies about completion. While ApolloCall notifies about the result, Response.  

Thanks for the clarification!

**Comment by sav007** [comment]
Yeah I guess it should be fine, please create a PR for this.

**Comment by hannanabdul55** [comment]
This issue is not applicable now as this will mean a LOT of classes need to be moved. Closing this issue 👍
