### ISSUE TITLE
Issue when queries parameters are set to null

### ISSUE THREAD

**Issue by bryan3005** [apollographql/apollo-android#706]
Hello,
I have some queries that can take null for some argument for exemple :

`query GetReservations($service:ServiceEnum, $status:[ReservationStatusEnum], $startAfter:DateTime) `

In this query I want to be able to not set the startAfter parameter, but setting it to null or even if I don't do .setStartAfter() always get me to the same point => the parameter is not pass is the query, resulting in a error "message": "Variable startAfter hasn\u0027t been submitted".

Doing the same in GraphQL explorer is working as expected (ignoring parameters that are null)

Is there a workaround or something I do wrong ?

Thank you

**Comment by sav007** [comment]
I guess this is an issue, we should do the same as we did for GraphQL input types, wrap nullable values with `com.apollographql.apollo.api.Input`.

**Comment by bryan3005** [comment]
Thank you for the quick reply,
For now I've found a workaround that seems to be working if someone is looking for a quick fix. 
You can set default value to the query parameter so doing something like this should work
`GetReservationsAfterNow($service:ServiceEnum,
  $status:[ReservationStatusEnum], $startAfter:DateTime = null)`

**Comment by RobinMaronierY** [comment]
Hello, I still have this issue with the version 0.4.2 @sav007 Travis failed this fix ?
