### ISSUE TITLE
Gradle plugin breaks on gradle 4.3-rc-1

### ISSUE THREAD

**Issue by hzsweers** [apollographql/apollo-android#708]
I don't have the exact error message handy (at the airport right now), but if you checkout this commit and try to sync in android studio 3.0, it will fail saying something about not being able to find a sources directory for the `:github` module

https://github.com/hzsweers/CatchUp/commit/10d90c1e538d31d7fba05d325da0ea65a8707f2a

**Comment by sav007** [comment]
@marwanad could you pls take a look at this issue?

**Comment by hzsweers** [comment]
This seems to not be an issue in gradle 4.3.1, maybe it was a bug in gradle
