### ISSUE TITLE
Fail when i try to import like a plugin in to the Android studio

### ISSUE THREAD

**Issue by acareagam** [apollographql/apollo-android#715]
Fail when i try to import in to the Android studio. It does not recognize any document.

**Comment by sav007** [comment]
Could you be more specific what exactly you are trying to do?

**Comment by acareagam** [comment]
I am trying to add  the plugin apollographql/apollo-android at my Android
Studio, but when I tryed to import it, the tool answer
"Fail-to-load-plugin-descriptor-from-file"

2017-11-07 20:27 GMT-06:00 Ivan Savytskyi <notifications@github.com>:

**Comment by jaredsburrows** [comment]
@sav007 I am not sure this is a valid issue. Many people are using this plugin with Android Studio today.

**Comment by digitalbuddha** [comment]
Closing for now. Let us know if there's a way we can reproduce
