### ISSUE TITLE
Cache update after mutation

### ISSUE THREAD

**Issue by jcmbappe** [apollographql/apollo-android#716]
Hello,

I do a query in CACHE_AND_NETWORK to retrieve a list of object. 
After doing a mutation on one of those objects I redo the same query in CACHE_ONLY but the date doesn't seem to have been updated.

I tried to do a mutation().refetch(query) but still no change in cache

Is there a workaround or something I do wrong ?

**Comment by sav007** [comment]
Is mutation inserting the new item or updating existing one?

**Comment by sav007** [comment]
At the same time if you specify `refetch(query)` for mutation it should execute after mutation completed. Are you sure you setup the cache correctly ?

**Comment by xiaogegexiao** [comment]
@sav007 Hi I have the same problem currently.

May I ask how to setup the mutation to let it automatically update the query cache? 
Say I have a 
```
class Person {
    String id;
    String name;
}
```

If I use `Rx2Apollo(ApolloClient.mutate(PersonMutation().builder().personId(id).personName(newName).build())).subscribe();`

Then instantly after this, if I call `Rx2Apollo(ApolloClient.query(PersoneQuery.builder().personId(id).responseFetcher(CACHE_FIRST)).subscribe();`

What I got is still the person object with the old name

Thank you. It will be very appreciated if you can help.
