### ISSUE TITLE
Error converting bytecode to dex:

### ISSUE THREAD

**Issue by xulong20130712** [apollographql/apollo-android#720]
Everything is ok but run the project and failed:
Error:Error converting bytecode to dex:
Cause: PARSE ERROR:
class name (***/AllLikeForumsQuery$Builder) does not match path (***/AllLikeForumsQuery$Builder.class)
...while parsing ***/AllLikeForumsQuery$Builder.class
the AllLikeForumsQuery.java(build/generated/source/apollo/....) is generate by apollo.

**Comment by sav007** [comment]
Could you please provide the exact path to AllLikeForumsQuery file?
