### ISSUE TITLE
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

### ISSUE THREAD

**Issue by jaredsburrows** [apollographql/apollo-android#722]
## Problem
Apollo adds to 'compile' configuration when using 'implementation' instead

## Repro steps
Using AGP 3.0.0
Using Gradle 4.3.1

Run `gradlew`

## Warning
```
$ gradlew 

> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

> Task :help 

Welcome to Gradle 4.3.1.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>


BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

## Dependencies for `compile` configuration
```
$ gradlew :app:dependencies --configuration compile

> Task :app:dependencies 

------------------------------------------------------------
Project :app
------------------------------------------------------------

compile - Compile dependencies for 'main' sources (deprecated: use 'implementation' instead).
\--- com.apollographql.apollo:apollo-runtime:0.4.0
     +--- com.google.code.findbugs:jsr305:3.0.1
     +--- com.squareup.okhttp3:okhttp:3.8.1
     |    \--- com.squareup.okio:okio:1.13.0
     +--- com.nytimes.android:cache:2.0.2
     |    \--- com.google.code.findbugs:jsr305:3.0.1
     \--- com.apollographql.apollo:apollo-api:0.4.0
          +--- com.google.code.findbugs:jsr305:3.0.1
          \--- javax.annotation:jsr250-api:1.0

(*) - dependencies omitted (listed previously)


BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

## Relative tests
https://github.com/apollographql/apollo-android/blob/3663041dc1ccc55e80fc55d67a03b161056de886/apollo-gradle-plugin/src/test/groovy/com/apollographql/apollo/gradle/unit/ApolloAndroidPluginSpec.groovy#L111

**Comment by digitalbuddha** [comment]
yup definitely a problem thank you for reporting!

**Comment by jaredsburrows** [comment]
@digitalbuddha Can you just mention in the readme that you need the dependency instead of automatically adding it?

**Comment by digitalbuddha** [comment]
@jaredsburrows want to open a pr and get some internet points?

**Comment by jaredsburrows** [comment]
Sure, I just wanted input from you all first.

**Comment by jaredsburrows** [comment]
@digitalbuddha So I think you should remove the feature to automatically add the runtime dependency and mention in the README.me to add it manually. This way you did not need code to check for "implementation" and/or "compile" based on the associated plugins that applied in the Gradle configuration. What you do you think?

**Comment by digitalbuddha** [comment]
Yes that seems like the right path to go. Remove auto dependency then add documentation to Readme.
