### ISSUE TITLE
Response is slow when caching mechanism is used

### ISSUE THREAD

**Issue by anup1245** [apollographql/apollo-android#726]
I was noticing, from my own tests, that when apollo client is set up with caching, getting the response was considerably slower than when there was no caching policy.

Is the client currently caching the data first before serving the data? And if so, why does it have this policy instead of serving the data first and then caching?

**Comment by sav007** [comment]
Is it normalized cache you refer to?
And could you pls provide some metrics?

**Comment by anup1245** [comment]
Yes, it happens when using normalized cache.
For a query returning around 50 items, which in turn had sub fields(4~6), the time was 2~4 secs per item.

When using http cache, the time was 0.5 sec for an item or sometimes less than 0.5 sec also.
Thanks!

**Comment by digitalbuddha** [comment]
Any chance you can do a trace and send it over. I can then analyze and optimize wherever the issue is.

**Comment by sav007** [comment]
One more question, what kind of cache? SQLlite or just mem?

**Comment by anup1245** [comment]
Using this,
```  ApolloSqlHelper apolloSqlHelper = new ApolloSqlHelper(Core.getApplicationContext(), SQL_CACHE_NAME);
        SqlNormalizedCacheFactory secondaryCache = new SqlNormalizedCacheFactory(apolloSqlHelper);
        NormalizedCacheFactory normalizedCacheFactory = new LruNormalizedCacheFactory(EvictionPolicy.NO_EVICTION)
                .chain(secondaryCache);```

**Comment by anup1245** [comment]
@digitalbuddha how to capture the trace? just logs ?

**Comment by digitalbuddha** [comment]
Easiest is by using the debug options. Somewhere before and after the apollo call Pls put

```
// start tracing 
Debug.startMethodTracing("calc");
// ...
// stop tracing
Debug.stopMethodTracing();

This will generate a  `calc.trace' file and saves it to your phone. You can see the location in Adb logs. Next pull this file from Adb.

You may also need to add <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

My trace files are usually found by
```
cd /storage/emulated/0
find -name *.trace```

Here are the official docs on how to generate and pull the file. https://developer.android.com/studio/profile/generate-trace-logs.html

This would go a long way in us fixing the implementation. Thank you for working with us.

**Comment by sav007** [comment]
Try the snapshot version should be much faster

**Comment by akarekal-coursera** [comment]
@sav007 Thanks for the update.
when is the next release ?

**Comment by xavieramoros** [comment]
I also had a slow query in Android. Graphql server returned the response quickly (some ms) but it took up to 50s to show up in my client.  

I fixed the issue changing apollo-cache-redux for apollo-cache-inmemory. I am not using apollo-android but apollo-client with React Native.
