### ISSUE TITLE
Failed to parse http response

### ISSUE THREAD

**Issue by AlphaGao1993** [apollographql/apollo-android#733]
I know there had a some title issues before, but I think it's not similar question, so I open a new issues:
I got a array of ID type in query, but apollo can not parse this array, when array is empty, everything is ok.
and if I change the name(type) of this array item from ID to String, it works! So could you know why does it happens?

the doc about array in schema.json:
``` json
{
  "name": "child_ids",
  "description": null,
  "args": [],
  "type": {
    "kind": "LIST",
    "name": null,
    "ofType": {
      "kind": "SCALAR",
      "name": "ID",
      "ofType": null
    }
  },
  "isDeprecated": false,
  "deprecationReason": null
}
```
and relatived json data is:
``` json
{
	"__typename": "PhotoType",
	"id": "818287",
	"url": "http://img.kid17.com/teacher/debug/kind_73/7fbdc3c95501992d745d694922e15cb5/pic/818287.jpg",
	"rotation": 0,
	"child_ids": ["35853", "35858"]
}
```
and the exception:
![image](https://user-images.githubusercontent.com/18735052/33162967-21fb53a0-d067-11e7-84bd-c035e8eeacf0.png)

**Comment by sav007** [comment]
That odd, are you using the latest version?
As by default it supposed to be mapped to String

**Comment by AlphaGao1993** [comment]
No, I'm still using version 0.4.1, and I will try latest version again.

**Comment by AlphaGao1993** [comment]
I upgrade apollo to version 0.4.2, and everything becomes OK, that's great!

**Comment by AlphaGao1993** [comment]
I upgraded and everything becomes OK.
