### ISSUE TITLE
Support array custom type adapters

### ISSUE THREAD

**Issue by lincolnq** [apollographql/apollo-android#738]
It is possible to write an implementation of, e.g., `CustomTypeAdapter<byte[]>` but not currently possible to declare it in the `customTypeMapping` section in Gradle:

```
    customTypeMapping['Bytes'] = "byte[]"
```

because you get a traceback like this during code generation

```
Caused by: java.lang.IllegalArgumentException: part 'byte[]' is keyword
	at com.squareup.javapoet.Util.checkArgument(Util.java:64)
	at com.squareup.javapoet.ClassName.<init>(ClassName.java:49)
	at com.squareup.javapoet.ClassName.<init>(ClassName.java:43)
	at com.squareup.javapoet.ClassName.get(ClassName.java:195)
	at com.apollographql.apollo.compiler.UtilKt.toJavaType(Util.kt:86)
	at com.apollographql.apollo.compiler.JavaTypeResolver.resolve(JavaTypeResolver.kt:28)
```

However, Javapoet supports array types, we just aren't parsing them yet in JavaTypeResolver, so we probably should do that. I haven't fully investigated this, but it seems like a relatively easy change from what I can tell so far.

**Comment by sav007** [comment]
Could you pls provide the example of schema with `Bytes `?
But I believe if you map `Bytes ` -> just `byte` you should get `List<Byte>`

**Comment by lincolnq** [comment]
In my case, I need to pass a few pieces of data which are collectively signed. The signature is a 25 byte blob. The schema defines a custom Bytes scalar type which, on the backend, serializes and deserializes as a base64 url-safe string. It is not a list; I think the list would be a substantially worse representation for this case. My adapter in Java just uses android.util.Base64 to decode the string, and that returns a byte[]. All the functions which generate or consume bytes in Java expect byte[]. Obviously it is possible to convert to and from List<Byte> but that's not how I or anyone expect to use byte arrays.

**Comment by sav007** [comment]
Gotcha, yeah make sense.

**Comment by sav007** [comment]
Outdate and not sure if the complexity of changes required to codegen worth the benefit. Closing for now.
