### ISSUE TITLE
Synthetic accessors need to be removed.

### ISSUE THREAD

**Issue by VisheshVadhera** [apollographql/apollo-android#741]
There are right now around 200 synthetic accessor methods in the entire project, which need to be removed in order to reduce the count of methods in the dex file.

**Comment by digitalbuddha** [comment]
I believe you can use android studios analyze feature and a custom configuration to auto fix these. I'll set a reminder to look tomorrow

**Comment by VisheshVadhera** [comment]
Yeah, there is an intellij insepction which gives the total count of synthetic accessors in the project. See [this](https://medium.com/thoughts-overflow/effects-of-javas-synthetic-accessor-methods-in-android-bb67b3bac22e)
