### ISSUE TITLE
Can't map GraphQL type: GenericScalar to: Object.java 

### ISSUE THREAD

**Issue by 80998062** [apollographql/apollo-android#747]
After upgrading to verion `0.4.3`,I found that things go wrong from here:

```java
 if (customTypeAdapter == null) {
      throw new IllegalArgumentException(String.format("Can't map GraphQL type: %s to: %s. Did you forget to add "
          + "custom type adapter?", scalarType.typeName(), scalarType.javaType()));
    }
```

When I use version ` 0.3.1`  there is no such errors occurred,I'm wondering shouldn't this work be done by  **apollo** underneath?

If now we have to write adapter for `GenericScalar`,and how? I've tried this but failed :

```java
class GenericScalarAdapter implements CustomTypeAdapter<Object> {

    private final Gson gson;

    public GenericScalarAdapter(Gson g) {
        gson = g;
    }

    @Override
    public Object decode(String value) {
        Timber.d("decode: ", value);
        return gson.fromJson(value, Object.class);
    }

    @Override
    public String encode(Object value) {
        return gson.toJson(value);
    }
}
```

First,the default scalar type seems to be raw string,and it's not a *well-format* json :

```javascript
{key1=value1, key2=value2}
```

And actually I know the  the specified class to deserialize:

```javascript
class Cover{
  String style;
  String image;
}

```

But in response it's a  scalar type because it represents the leaves of query:

```java
Book{
  title:String
  author:String
  cover:GenericScalar
}
```

So I should use ``gson.fromJson(json,Cover.class)`` because of the Type Erasure feature of Java.But I can't know the type of the object  in the adapter

Any advices? Now I got no way but  downgrading to version ``0.3.1`` 😔

**Comment by sav007** [comment]
`0.3.1` is too old version, a lot has been changed since.

Did you provide mapping in gradle plugin:
```
apollo {
  customTypeMapping['GenericScalar'] = "Object"
}
```
Then it's up to you how to deserialize it from string, if it's bad formatted then it's probably server side issue. What do you accept in `cover`, map?

**Comment by dbof10** [comment]
I hit the same issue https://github.com/apollographql/apollo-android/issues/752

**Comment by 80998062** [comment]
Here is the raw response:
```
{"__typename":"BookNode",","cover":{"code_name":"cover-app-9","pic":"https://static.xinshu.me/assets/images/covers/gallery/18.jpg"},"type":"normal","typesetType":"a5-waterfall-xinshu","template":"a5-waterfall","hook":"{}","typesetName":"A5\u7011\u5e03\u6d41"}
```
It seems `cover` has been formatted as JSON, but Apollo will convert the scalar type into 
```
cover={pic="",code_name=""}

```
> the value I print from the `CustomTypeAdapter` for converting `GenericScalar` to `Object`

And what do you mean on this in  #752 
> I guess the problem here guys that your scalar types are not scalar after all, they are objects.

Is there the `cover` a scalar or object? It appears to be JSON in the response above

I'll try the solutions discussed in #752  and give you feedback later on

Duplicate of #752

**Comment by sav007** [comment]
Closing this one as it duplicate
