### ISSUE TITLE
Add support of subscriptions

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#754]
**Protocol description:** https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md

**Public GraphQL server with subscription support** https://github.com/apollographql/GitHunt-API

**Comment by sav007** [comment]
blocked on https://github.com/apollographql/apollo-codegen/issues/316
cc @martijnwalraven

**Comment by AndreiHarasemiuc** [comment]
Hello, sorry to bother, but do you guys have an ETA on this feature?

**Comment by sav007** [comment]
the PR is up, waiting on review, the only missing part for now are tests and javadocs.
Should be merged soon.

**Comment by bhuvan0616** [comment]
Any update on this feature?

**Comment by devagul93** [comment]
Any update on This?

**Comment by Queike** [comment]
Any update on this feature?

**Comment by pleerock** [comment]
Issue seems to be merged but there are no docs on how to use it?

**Comment by edwrios** [comment]
Any update on this feature?

**Comment by wawhal** [comment]
Hey @sav007 where is this documented?
Couldn't find it anywhere in the docs/README.
