### ISSUE TITLE
Can't initialize variable what type is String

### ISSUE THREAD

**Issue by rnitame** [apollographql/apollo-android#761]
On server (use apollo-server-koa)

```graphql
input xxxInput {
  parser: String = "simple"
}
```

On client (use apollo-android)

```java
    private @Nullable String parser = simple;
```

It happens an error because it is not enclosed in double quotes :(

**Comment by sav007** [comment]
What version of client are you using?

**Comment by rnitame** [comment]
@sav007 v0.4.1

**Comment by sav007** [comment]
Will investigate

**Comment by sav007** [comment]
@rnitame why you can't update to the 0.4.3?

**Comment by rnitame** [comment]
This error happened.
![image](https://user-images.githubusercontent.com/4950792/34192043-aa1ddb54-e58e-11e7-98bb-19494a50c279.png)

**Comment by sav007** [comment]
Just remove it from apollo plugin configuration `generateAccessors`

**Comment by rnitame** [comment]
Thanks! I could update the plugin! Also fixed the error!
