### ISSUE TITLE
How do you use ApolloExceptions?

### ISSUE THREAD

**Issue by rnitame** [apollographql/apollo-android#764]
ApolloExceptions ↓
https://github.com/apollographql/apollo-android/pull/379

I want to sample code.

**Comment by sav007** [comment]
Is any specific question you want to ask?

**Comment by rnitame** [comment]
I want to be error handling using HTTP code or something else (ApolloException etc.)

**Comment by sav007** [comment]
Look for `com.apollographql.apollo.ApolloCall.Callback#onHttpError` you can override in your callback but **you have to close response manually then e.rawResponse().close()**

**Comment by rnitame** [comment]
I see.
By the way, can I use `com.apollographql.apollo.ApolloCall.Callback#onHttpError` when using apollo-rx2-support?
