### ISSUE TITLE
Change nullability annotations to be Jetbrains annotation rather than JSR

### ISSUE THREAD

**Issue by jaredsburrows** [apollographql/apollo-android#769]
Instead of using JSR305, since this is for Android only, can we use the Android Support Annotations for the generated code. This will allow us not to bring in more than annotation library.

**Comment by sav007** [comment]
Well Apollo client was designed to be not Android only but pure java. You can see that no any android dependency present in core modules

**Comment by sav007** [comment]
But we can introduce new option to plugin configuration to support this

**Comment by jaredsburrows** [comment]
@sav007 Thank you. I just figured it is called "apollo-android", it should be specific to Android. So do you want to add a property/method to the existing Gradle extension to the plugin?

**Comment by sav007** [comment]
Yes, it would be great to have it as configuration option to plugin

**Comment by digitalbuddha** [comment]
Apparently the JSR one is going to break Java9 compatibility, lets go to Jetbrains annotations instead
