### ISSUE TITLE
Publish the generated javadoc online

### ISSUE THREAD

**Issue by Caerbannog** [apollographql/apollo-android#773]
The generated javadoc should be published online and easy to find.

The apollo-android javadoc is quite useful, but it's not easy to find for newcomers. The html ouputs of `gradlew javadoc` could be published to a public webserver, and a link added to https://www.apollographql.com/docs/android/

Here is how things curently stand:
- `.travis.yml` runs `.buildscript/deploy_snapshot.sh` for each commit on the `master` branch
- `.buildscript/deploy_snapshot.sh` pushes artifacts to Sonatype here: https://oss.sonatype.org/#nexus-search;quick~apollo-android
- `.buildscript/deploy_snapshot.sh` does not push to github pages because the relevant bits from this blog post have not been copied: http://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/

Here is what could be done if we want to publish the javadoc on Github pages:
- [ ] An apollographql maintainer needs to configure the Github side, following instructions here: http://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/
- [ ] The `.buildscript/deploy_snapshot.sh` script needs to be edited in the master branch like this: https://github.com/Caerbannog/apollo-android/pull/1/files
- [ ] A new `gh-pages` branch will have been created by Github, we will probably need to update it manually with an index.html that links to the ./javadoc/* subdirectories, corresponding to various packages (apollo-api, apollo-runtime, ...)
- [ ] A link to the resulting github page needs to be added in `./docs/source/index.md`

**Comment by digitalbuddha** [comment]
@martijnwalraven is there anywhere we can host javadocs rather than putting them on gh-pages?

**Comment by martinbonnin** [comment]
Apollo Android 3 now publishes the KDoc at https://apollographql.github.io/apollo-android/kdoc/

Closing this issue
