### ISSUE TITLE
Use as pure java without android lock in

### ISSUE THREAD

**Issue by oexza** [apollographql/apollo-android#778]
Is this possible today?

**Comment by digitalbuddha** [comment]
Yes all android stuff is in a single module. Do not add the android support
and you will be good.

**Comment by oexza** [comment]
thanks @digitalbuddha then it makes sense to split this project in two. Apollo-Java and Apollo-android atop the former.

**Comment by digitalbuddha** [comment]
Keeping  different modules in same project makes refactoring and deployment easier. You can add a blurb to Readme if you'd like 🙂
