### ISSUE TITLE
Why include generated schema.json in the app?

### ISSUE THREAD

**Issue by sp00ne** [apollographql/apollo-android#787]
Hi there,

I generally like the structure and works of GraphQL but I don't see the purpose of generating a json and then including it. It sort of defeats one of the main strengths of GraphQL, which is that it's less prone to cause errors due to changes server-side (since we are querying specific things). 

Now I have to generate a new JSON file every time the server decides to do an update? Feels odd.

**Comment by digitalbuddha** [comment]
I'm not sure if this is something specific to apollo android but more how the Graphql spec works. You need to have a contract between server and client. It's what allows compile time validation. For example look at github graphql explorer. It only lets you execute queries that are part of the server schema.

**Comment by digitalbuddha** [comment]
I don't believe it is true to say that graphql is less likely to cause errors with server changes more that you can create  queries without server changes if the query is part of the schema.  Closing

**Comment by sp00ne** [comment]
A contract is something, all fine and dandy but when you have to bundle it in the app it gets volatile. I saw that you can fetch the schema serverside instead of running a codegen and stuff.

Can't you generate it through server-side and then read it when compiling + caching?

**Comment by kuno** [comment]
@digitalbuddha 

We want to use `apollo-android` in our new project, but our backend developer told us that the schema for our graphql api could be changed at any time.


Given such restriction, Is that possible we still able to use `apollo-android` in our project someshow ?
