### ISSUE TITLE
Add benchmarks to the tests

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#791]
We could add benchmarks to see how the parsers compare to moshi/gson/jackson. In addition to being a great showcase of what apollo-android could do, this could be useful to spot possible regressions.

**Comment by digitalbuddha** [comment]
Not crazy about this, benchmarks don't really show whole story.  Maybe Jackson parses faster but adds more method count and slows down other reflection... how do you properly show that in benchmark? I'll leave benchmarking to the json parsing libraries/community
