### ISSUE TITLE
Build fails with GraphQL enum name "new"

### ISSUE THREAD

**Issue by arcane99** [apollographql/apollo-android#792]
Android build fails if a GraphQL enumerator type field has a value with name "new"; error message on build
```
Error:Execution failed for task ':app:generateDebugApolloClasses'.
> not a valid enum constant: new
```

Build is successful if field with enum type with value "new" is removed from query.
To reproduce, create a GraphQL query statement using the following example field:
```
{
          "kind": "ENUM",
          "name": "Location",
          "description": null,
          "fields": null,
          "inputFields": null,
          "interfaces": null,
          "enumValues": [
            {
              "name": "home",
              "description": "Home location.",
              "isDeprecated": false,
              "deprecationReason": null
            },
            {
              "name": "new",
              "description": "New location.",
              "isDeprecated": false,
              "deprecationReason": null
            }
          ],
"possibleTypes": null
 },
```

I suspect that the build fails as "new" is a reserved java word.

**Comment by sav007** [comment]
That's correct, as we can't generate enum constant with this java reserved word. As work around you can ask your API guys to make them uppercase.

@martijnwalraven @digitalbuddha what do you think if we enforce generation enum values  with uppercase? But unfortunately is breaking changes.

I don't see any specs that say enum values must be uppercase in GraphQL: http://graphql.org/learn/schema/#enumeration-types

**Comment by arcane99** [comment]
Thanks for the response. I have limited control on the api spec as I am a
consumer of a companies api. Is there anything that I can change in apollo
code to handle the issue? For example renaming or ignoring of reserved
words on the client side?

**Comment by sav007** [comment]
I'm afraid not but I will have some fix for you soon.
