### ISSUE TITLE
`apolloClient.apolloStore().write()` usage

### ISSUE THREAD

**Issue by mwajeeh** [apollographql/apollo-android#793]
Checkout how easy it is to read a query, add new items to list and write result back in Javascript. 
```
const query = gql`
  {
    todos {
      id
      text
      completed
    }
  }
`;

const data = client.readQuery({
  query,
});

data.todos.push({
  id: 5,
  text: 'Hello, world!',
  completed: false,
});

client.writeQuery({
  query,
  data,
});
```

Similar thing on Android requires you to build data object from scratch because `List`s returned by `RealResponseReader` are unmodifiable and each field is `final`. So you have to create data objects from scratch assigning each field until you reach the `List` field that you actually wanted to modify. So what could have been few lines of code now becomes ~200 lines of code for big data objects making it really hard to use this feature.

Let me know if I am missing anything or if you need something from me to understand what I am talking about.

**Comment by sav007** [comment]
Could you pls give it a try to enable `generateModelBuilder` in apollo gradle config? That will give you builder to be generated for models, like: 

https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/fragment_with_inline_fragment/TestQuery.java#L329

https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/fragment_with_inline_fragment/TestQuery.java#L469

**Comment by mwajeeh** [comment]
`generateModelBuilder` did help reduce it to ~30 lines of code. Thanks.  Wish there was a way to reduce it more though.

PS: Just started using apollo, wanna say I love it.
