### ISSUE TITLE
Support for GET requests

### ISSUE THREAD

**Issue by lucastsantos** [apollographql/apollo-android#797]
Hi,

Is there a way to do GET requests using ApolloClient? From what I've found, only POST requests are supported. A support for it would be very appreciated.

https://github.com/apollographql/apollo-android/blob/3600049e1e4a617ebecf19247dd0b78dcb78f54c/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloServerInterceptor.java#L110-L117

**Comment by digitalbuddha** [comment]
Graphql spec only supports post requests. Get requests are not complaint with graphql.   You could use the same okhttp instance you pass to apollo to do any get requests you need

**Comment by mshaileshr** [comment]
> Graphql spec only supports post requests. Get requests are not complaint with graphql. You could use the same okhttp instance you pass to apollo to do any get requests you need

Is it possible to set GET request in custom interceptor?
