### ISSUE TITLE
build code package name conflict

### ISSUE THREAD

**Issue by celesteshire** [apollographql/apollo-android#799]
in UserInput class ,i have a type field, but it and package name conflict.
this cause i not build

![image](https://user-images.githubusercontent.com/10936195/35191279-d0cfb79a-feb1-11e7-8218-054aef1d2540.png)

![image](https://user-images.githubusercontent.com/10936195/35191289-38631abe-feb2-11e7-861d-5c913cfef105.png)

apollo-android version : 0.4.3
android studio: 3.0.1

**Comment by sav007** [comment]
Couple notes:
1. Put all your graphql files under the folder structure that will reflect the package you want, for example if you put under `/graphql/com/example/apollo` all models will be generated under `com.example.apollo` package.
2. Why can't you add `type` to import section?
