### ISSUE TITLE
List of strings containing nulls is stripped of the null values before being sent through

### ISSUE THREAD

**Issue by AndreiHarasemiuc** [apollographql/apollo-android#801]
This is the relevant part of my schema.

```
type Schedule {
        ...
	occurrences: [OccurrencesInADay]
        ....
}

input ScheduleInput {
	occurrences: [OccurrencesInADayInput]
}

type OccurrencesInADay {
	times: [String]
	timeUnit: Int
}

input OccurrencesInADayInput{
  times: [String]
  timeUnit: Int
}

```

upon building my ScheduleInput to be sent with the request, I add an `ArrayList<OccurrencesInADayInput>` which is populated with an `ArrayList<String>` for its `ocurrences` field. That array of strings contains some strings but also some nulls. Those nulls are stripped out when the actual request is being sent. I'm verifying this with the okhttp3 logging interceptor.

Is this a bug or am I doing something wrong? I need those null values to be there.

**Comment by sav007** [comment]
Well this is a default behaviour of serializer to skip nulls. What is your use case for having nulls in the list?

**Comment by AndreiHarasemiuc** [comment]
I have a schedule type structure

`times: [String` mentioned above is a list of hours of day like so:
["12:45", "23:01", null, "14:21"....]

These hours are appointment times for meetings. A null = appointment without a time. I need that null in the exact place it is in the array.

**Comment by sav007** [comment]
Well can't 100% agree that `null` as a value. As it can mean 2 different states: missing value (user didn't set) or user set it explicitly then it represents a real value. That's why we have introduced `com.apollographql.apollo.api.Input` wrapper for all input fields. Where user can explicitly specify if he wants to send `null` or it's just undefined value.

Anyway this is def an issue.

**Comment by dlleixap** [comment]
Hi all,
I can see this is still happening for, at least, the latest release `v1.0.0-alpha5`.

The data is driven by a `schema` that expects a `List<List<String>>`
```
{
    "name": "data",
    "description": "Formatted data",
        "args": [],
        "type": {
            "kind": "NON_NULL",
            "name": null,
            "ofType": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                    "kind": "LIST",
                    "name": null,
                    "ofType": {
                        "kind": "SCALAR",
                        "name": "String",
                        "ofType": null
                    }
                }
            }
        },
        "isDeprecated": false,
        "deprecationReason": null
}
```

Backend response by using Postman clearly shows a list of string with `null` as part of it:
**["Kids Armoires", "N/A", _null_, "N/A"]**

Android Debug result with no data manipulation:
**["Kids Armoires", "N/A", "N/A"]**

Thanks in advance.

PS. @AndreiHarasemiuc   Is this still happening to you?
