### ISSUE TITLE
Compilation Issue when property named 'type'

### ISSUE THREAD

**Issue by JonahStarling** [apollographql/apollo-android#807]
The compiler creates a folder named type and creates a naming conflict when a property is named type. This produces the following error:

`error: cannot find symbol CustomType`

Where CustomType is the value of type (URL, JSON, etc.). Custom Types are being defined and implemented per the readme's instruction. Below is the code showing a basic setup using java.lang.String to test with.

build.gradle
```gradle
apollo {
    customTypeMapping['DATETIME'] = "java.lang.String"
    customTypeMapping['ID'] = "java.lang.String"
    customTypeMapping['URL'] = "java.lang.String"
}
```

SomeFragment
```kotlin
val customTypeAdapter = object : CustomTypeAdapter<String> {
    override fun decode(value: String): String {
         return value
    }

    override fun encode(value: String): String {
         return value
    }
}

val apolloClient = ApolloClient.builder()
    .addCustomTypeAdapter(CustomType.DATETIME, customTypeAdapter)
    .addCustomTypeAdapter(CustomType.URL, customTypeAdapter)
    .addCustomTypeAdapter(CustomType.ID, customTypeAdapter)
    .serverUrl(baseUrl)
    .okHttpClient(okHttpClient)
    .build()
```

This issue is similar to the issue below that was filed on the Apollo-ios repo:

[https://github.com/apollographql/apollo-ios/issues/103](url)

This issue was solved on iOS by prefixing the word with 'graphql'.

**Comment by sav007** [comment]
Did you put graphql files under the package, like `/graphql/com/apollographql/apollo/sample/GihuntRepositoryDetailQuery.graphql`. I believe it will resolve the conflicts.

**Comment by JonahStarling** [comment]
@sav007 This solves my issue. I originally had put them under the folder `/graphql/`, per the documentation, but changing the path to something like `/graphql/sample/project/` fixed the issue.
