### ISSUE TITLE
`:app:installApolloCodegen` gradle task long exec. time

### ISSUE THREAD

**Issue by sp00ne** [apollographql/apollo-android#811]
Hi there,

I was wondering how come it takes `:app:installApolloCodegen` such a long time to execute, is it possible to cache it or somehow reduce the execution time? For me, it always stays at this process for about 1 minute.

**Comment by paour** [comment]
It takes a long time because it seems to be pulling a bunch of nodejs dependencies. I wish it was possible to disable this build step and just keep the generated code in git.

**Comment by hzsweers** [comment]
Also - if you have multiple modules that use apollo, then each one will run separately (creating duplicate node dependencies)
