### ISSUE TITLE
Clarify the order in which the plugins must be applied

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#817]
In a pure Kotlin project, I had to apply the `kotlin` plugin *before* the `apollo` one.

The README.md mentions that `kotlin-android` must be applied after `apollo`.

Could we potentially make it so that order is not important ?

**Comment by digitalbuddha** [comment]
When on say pure kotlin do you mean non android?

**Comment by martinbonnin** [comment]
Yep, non-android

**Comment by martinbonnin** [comment]
Also, it would be nice to remove the dependency on the android plugin. Trying to apply version 1.0.0 on a non-android project gives me the below:

    Could not find com.android.tools.build:gradle:3.3.0.
            Searched in the following locations:
    - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.pom
    - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.jar
    - https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.pom
    - https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.jar
    - https://jcenter.bintray.com/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.pom
    - https://jcenter.bintray.com/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.jar
    Required by:
        project : > com.apollographql.apollo:apollo-gradle-plugin:1.0.0

**Comment by tasomaniac** [comment]
I also use Apollo plugin in non-Android Kotlin project. Gradle allows this dynamicity. Ideally, it shouldn't be user's concern.

The Android dependency can definitely be optional. Since the project will react to Android plugin being available it will just work in both Android and regular projects. It should work as before if we use `runtimeOnly`

**Comment by martinbonnin** [comment]
The order thing is old. Maybe this is fixed now. But in all cases the README.md still mentions this so it's a bit confusing.

The Android dependency is still a thing. I had to include the google() repo on a project recently to be able to resolve it.

**Comment by tasomaniac** [comment]
It used to force you to add jCenter() too. Maybe still does.

**Comment by martinbonnin** [comment]
jcenter() is where the artifacts are uploaded so it's needed until we decide to tackle https://github.com/apollographql/apollo-android/issues/1130

**Comment by tasomaniac** [comment]
The problem mentioned here about Android dependency unnecessarily downloaded is fixed here: #1470 and #1511 

I don't think ordering issue is valid anymore. It works in both conditions.

**Comment by DSteve595** [comment]
Anecdotally, can also confirm that the order doesn't seem to matter in the existing plugin or the incubating plugin.
