### ISSUE TITLE
Android bug 

### ISSUE THREAD

**Issue by prog7hera** [apollographql/apollo-android#818]
> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'testCompile' in project ':app' is deprecated. Use 'testImplementation' instead.
Exception while marshalling /opt/android-sdk/build-tools/17.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/18.0.1/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/18.1.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/18.1.1/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/19.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/19.0.1/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/19.0.2/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/19.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/19.1.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/20.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/21.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/21.0.1/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/21.0.2/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/21.1.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/21.1.1/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/21.1.2/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/22.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/22.0.1/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/23.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/23.0.1/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/23.0.2/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/23.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/24.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/24.0.1/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/24.0.2/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/24.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/25.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/25.0.1/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/25.0.2/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/25.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/26.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/26.0.1/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/26.0.2/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/26.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/27.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/27.0.1/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/27.0.2/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/27.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/docs/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platform-tools/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-10/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-11/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-12/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-13/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-14/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-15/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-16/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-17/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-18/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-19/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-20/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-21/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-22/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-23/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-24/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-25/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-26/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-27/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-8/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-9/package.xml. Probably the SDK is read-only
Observed package id 'platforms;android-22' in inconsistent location '/opt/android-sdk/temp/PlatformPackage.old01' (Expected '/opt/android-sdk/platforms/android-22')
Already observed package id 'platforms;android-22' in '/opt/android-sdk/platforms/android-22'. Skipping duplicate at '/opt/android-sdk/temp/PlatformPackage.old01'
Observed package id 'system-images;android-25;google_apis;x86_64' in inconsistent location '/opt/android-sdk/temp/SystemImagePackage.old01' (Expected '/opt/android-sdk/system-images/android-25/google_apis/x86_64')
Exception while marshalling /opt/android-sdk/tools/package.xml. Probably the SDK is read-only
Build properties not found for package Android SDK Platform 16, rev 5

FAILURE: Build failed with an exception.

* Where:
Build file '/opt/polat/android-instances/golf/build.gradle' line: 26

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Cannot invoke method buildToolsVersion() on null object
   > java.lang.NullPointerException (no error message)

**Comment by sav007** [comment]
I don't see any issue related to the Apollo
