### ISSUE TITLE
Watcher broken for empty cache

### ISSUE THREAD

**Issue by nekdenis** [apollographql/apollo-android#822]
I’m subscribing for cache changes:
`apolloClient.query(query).responseFetcher(ApolloResponseFetchers.CACHE_ONLY).watcher()`

and then update cache:
`apolloClient.query(query).responseFetcher(ApolloResponseFetchers.NETWORK_ONLY)`

unfortunately watcher do not actually watch for cache changes and load data from updated cache.  Is it proper behaviour or bug?

But if I'm recreating watcher it grabs cached data. But only after recreation =(
Important note: I’m fetching full collection of objects not several keys

I think it is happening because in `CacheOnlyFetcher` there is no dependant keys are provided  in `cacheMissResponse()` method

**Comment by sav007** [comment]
When cache is empty this `apolloClient.query(query).responseFetcher(ApolloResponseFetchers.CACHE_ONLY).watcher()` doesn't make any sense, as internally it won't be able to resolve dependant keys to watch. 

I'm guessing you want to register local cache watcher much earlier then actual fetching from network?

**Comment by nekdenis** [comment]
Is it possible to check that cache is empty to trigger network request manually in that case?
