### ISSUE TITLE
Typecast problem

### ISSUE THREAD

**Issue by Artem-Klyuev** [apollographql/apollo-android#828]
Apollo version:
apollo-runtime version 0.4.4
apollo-android-support version 0.4.4
apollo-rx2-support 0.4.4

i have a problem with typecasting
`LatestEventsQuery latestEvents = LatestEventsQuery.builder()
                .portal("23ffbb5d-d57c-40aa-ae7d-2415dd1f58e3")
                .start(new Date().getTime())
                .end(new Date().getTime() + DateUtils.WEEK_IN_MILLIS * 8)
                .build();`

okHttpRequest body:
`{"query":"query latestEvents($portal: UUID!, $start: DateTime!, $end: DateTime!) {  latestEvents(dateRange: {start: $start, end: $end, timezone: \"UTC\"}, portal: $portal) {    __typename    edges {      __typename      node {        __typename        uuid        title        lastUpdated        featuredImage {          __typename          url(params: {width: 600, height: 400, method: CROP})        }        dateRange {          __typename          start          end        }        locationName      }      cursor    }    pageInfo {      __typename      endCursor      hasNextPage    }  }}","variables":{"portal":"23ffbb5d-d57c-40aa-ae7d-2415dd1f58e3","start":"1519049720683","end":"1523888120683"}}`

problem is variables.start is string instead of Long

**Comment by sav007** [comment]
I see that `$start: DateTime!` is a grahql custom scalar type. So it will be serialized as string. If you need it to be sent as `Long` then this graphql field must be declared as `Int`. 

See `com.apollographql.apollo.CustomTypeAdapter#encode` it always returns `String`.

**Comment by sav007** [comment]
Ok, GraphQL spec was abstract to the encode format of custom scalar types, I guess this PR fixes this issue https://github.com/facebook/graphql/pull/326.

We need to allow user to define what Json supported type will be returned as result of `com.apollographql.apollo.CustomTypeAdapter#encode`
