### ISSUE TITLE
Setting Explicit schema location is not working in android

### ISSUE THREAD

**Issue by rahuldream11** [apollographql/apollo-android#838]
I am using Apollo 0.4.3, It is not generating the model files when I explicitly set the Schema Location, its working fine when I put the schema at default location i.e. /graphql

here is build.gradle code
```
apollo {
     schemaFilePath = "/src/main/java/com/app/dream11/core/service/graphql/schema.json"
     outputPackageName = "com.app.dream11.core.service.graphql.api"
     generateModelBuilder = true
}
```
I have put the Query file at the same location as schema,its compiling successfully but not generating model files

**Comment by sav007** [comment]
Could you please post a top level structure of your project, I guess what can be the issue
