### ISSUE TITLE
Is there any way to plug in a custom type converter?

### ISSUE THREAD

**Issue by emiliano-sala** [apollographql/apollo-android#861]
So i'm trying to use Apollo on an instant apps development, where we need to keep the size under 4MB. The problem is that the generated code is quite large by itself, so it'd be nice if i could plugin in my own generated code in there which i can reduce to a minimum.
Not sure if there are other strategies to reducing the size of the generated code, but i'd really appreciate if someone had try to do something similar.

**Comment by sav007** [comment]
There is no way you can plug in custom code generation. Try to reduce the amount of fields, fragments in your query

**Comment by sav007** [comment]
Closing
