### ISSUE TITLE
Implementation of Parcelable for response classes

### ISSUE THREAD

**Issue by KingIdee** [apollographql/apollo-android#869]
The generated response classed should implement Parcelable to help users transfer data easily through intents.

**Comment by digitalbuddha** [comment]
Users should not be passing apollo models through intents as there is no guarantee that models will be smaller than the bundle limit.

Apollo is designed in a  way where you can requery when a new activity opens and only need to pass the query params between activities.

**Comment by KingIdee** [comment]
Okay. Cool.
