### ISSUE TITLE
Subscription fail error on subscription ?HTTP FAILED: java.net.ConnectException: Failed to connect

### ISSUE THREAD

**Issue by Ali-zain-javed** [apollographql/apollo-android#877]
<!--**Function of subscription**
//////////////////////////////////////////////////////////////////////////////////////////////////
private void subscribeRepoCommentAdded() {

        ApolloSubscriptionCall<AssetSubscription.Data> subscriptionCall = Myapolloclient.getmyapolloclient()
                .subscribe(new AssetSubscription());

       
        disposables.add(Rx2Apollo.from(subscriptionCall)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeWith(
                        new DisposableSubscriber<Response<AssetSubscription.Data>>() {
                            @Override public void onNext(Response<AssetSubscription.Data> response) {
                              //  commentsListViewAdapter.addItem(response.data().commentAdded().content());
                                Log.d("response_of_subscripti", response.data().Asset().__typename());
                            }

                            @Override public void onError(Throwable e) {
                                Log.d("error_response", e.toString());
                            }

                            @Override public void onComplete() {
                                Log.d("fail_response", "subscription complete");
                            }
                        }
                )
        );
    }
//////////////////////////////////////////////////////////////////
apolloclient and subscription socket layer 
 
    private static final String BASE_URL = "https://-----------------.io/graphql";
    private static final String SUBSCRIPTION_BASE_URL = "ws://------------------.io:5000";

        OkHttpClient okHttpClient2 = new OkHttpClient.Builder()
                .build();

    HttpLoggingInterceptor loggingInterceptor=new HttpLoggingInterceptor();
loggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
OkHttpClient okHttpClient=new OkHttpClient.Builder().addInterceptor(loggingInterceptor).build();

myapolloclient=ApolloClient.builder().serverUrl(BASE_URL).
        subscriptionTransportFactory(new WebSocketSubscriptionTransport
                .Factory(SUBSCRIPTION_BASE_URL, okHttpClient)).okHttpClient(okHttpClient).build();

return myapolloclient;

**Comment by Ali-zain-javed** [comment]
/////////////////////////////
apolloclient and socket layer
///////////////////////////////////////
 private static final String BASE_URL = "https://-----------io/graphql";
    private static final String SUBSCRIPTION_BASE_URL = "ws://--------------.io:5000";
   OkHttpClient okHttpClient2 = new OkHttpClient.Builder()
                .build();

    HttpLoggingInterceptor loggingInterceptor=new HttpLoggingInterceptor();
loggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
OkHttpClient okHttpClient=new OkHttpClient.Builder().addInterceptor(loggingInterceptor).build();

myapolloclient=ApolloClient.builder().serverUrl(BASE_URL).
        subscriptionTransportFactory(new WebSocketSubscriptionTransport
                .Factory(SUBSCRIPTION_BASE_URL, okHttpClient)).okHttpClient(okHttpClient).build();

return myapolloclient;


................................................................
private void subscribeRepoCommentAdded() {

        ApolloSubscriptionCall<AssetSubscription.Data> subscriptionCall = Myapolloclient.getmyapolloclient()
                .subscribe(new AssetSubscription());


        disposables.add(Rx2Apollo.from(subscriptionCall)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeWith(
                        new DisposableSubscriber<Response<AssetSubscription.Data>>() {
                            @Override public void onNext(Response<AssetSubscription.Data> response) {
                              //  commentsListViewAdapter.addItem(response.data().commentAdded().content());
                                Log.d("response_of_subscripti", response.data().Asset().__typename());
                            }

                            @Override public void onError(Throwable e) {
                                Log.d("error_response", e.toString());
                            }

                            @Override public void onComplete() {
                                Log.d("fail_response", "subscription complete");
                            }
                        }
                )
        );
    }

**Comment by Ali-zain-javed** [comment]
@sav007

**Comment by Ali-zain-javed** [comment]
simple mutation and query work on this,but subscription create error ,send exception

**Comment by sav007** [comment]
Doesn't exception tell you that there is some connectivity issue? Check if you are using right web socket address for subscription server and make sure server is actually available.

**Comment by Ali-zain-javed** [comment]
@sav007 yes server is live ,and this subscription address is working on react website but now i am using in android studio ,against this url exception occur ,like i mentioned above  



this is result "
////////////////////////////////////////////////////////////////////////////////////
04-13 11:12:26.890 2902-2958/com.example.alizain.new_apollo_example D/OkHttp: --> GET https:/----------------------------------------5000/ http/1.1
    Sec-WebSocket-Protocol:  g-------ws
    Cookie: 
    Upgrade: websocket
    Connection: Upgrade
    Sec-WebSocket-Key: 9zJ5QSeqELKhoWj6ThJfuA==
    Sec-WebSocket-Version: 13
 --> END GET
///////////////////////////////////////////////////////////////////////////////////////////////////////
   excepion is 


 D/OkHttp: <-- HTTP FAILED: java.net.ConnectException: Failed to connect to gixcvvt.meccis.io/52.29.60.183:5000

com.example.alizain.new_apollo_example D/error_response: com.apollographql.apollo.exception.ApolloNetworkException: Subscription failed

**Comment by Ali-zain-javed** [comment]
@sav007  please can you review the above code (program),maybe i am missing something ,thanks

**Comment by sav007** [comment]
not sure but I tried to ping your server at `gixcvvt.meccis.io` it doesn't respond

**Comment by Ali-zain-javed** [comment]
@sav007 this is not right server ,because i have changed the name of server their due to privacy.right server is working on web in react,and in query and mutation request in android.

**Comment by sav007** [comment]
I'm sorry, I can't really help you with this as it seems the issue with your server setup.
