### ISSUE TITLE
Question on InputFieldMarshaller

### ISSUE THREAD

**Issue by fkruege** [apollographql/apollo-android#879]
I noticed for Apollo Generated types there is the following method below to serialize a custom type.  Is there a supporting API to deserialize it into a object?  

We have a use case where we need to queue mutation requests when a user is offline and then replay the requests once the user is back online.  I was hoping to serialize the Types and then deserialize and rebuild the mutation requests.

```
public InputFieldMarshaller marshaller() {
...
}
```

**Comment by sav007** [comment]
`InputFieldMarshaller ` is used to serialize query variables to the json. See https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloServerInterceptor.java#L147

In your case the issue that generated `Variables` class for query can be only serialized to the json. It doesn't have code for deserialization. So even if you serialize query variables there is no way you can restore them later.

**Comment by fkruege** [comment]
Thank you for your response.
