### ISSUE TITLE
[Code Generation] Add support of custom scalar types

### ISSUE THREAD

**Issue by sav007** [apollographql/apollo-android#88]
In most GraphQL service implementations, there is also a way to specify custom scalar types. For example, we could define a Date type

**Comment by digitalbuddha** [comment]
Ideally we follow a pattern similar to sqldelight where user would be able to define custom types within  .graphql files and then passes in adapters for how to serialize.  Maybe we can add custom type Metadata to schema files?

**Comment by sav007** [comment]
we can use comments :)
```
query Test($count:Int!) {
  shop {
    products(first:$count) {
      edges {
        node {
          title
          createdAt # as java.util.Date
        }
      }
    }
  }
}
```

**Comment by marwanad** [comment]
I feel a top-level extension could be useful in that case. We're going to have one anyways for setting the POJO flag, so might as well let the user define the mapping there.

The plugin can then manipulate the `schema.json` file with that information before passing it to the compiler.

**Comment by martijnwalraven** [comment]
Yeah, you don't want to specify the mapping on a per-field basis, so the `.graphql` file is not the right place I think.

So some kind of project wide configuration makes the most sense to me. You'd specify a mapping from `DateTime` to `java.util.Date` in there for instance, and something like a type adapter.

You wouldn't want to manipulate the `schema.json`, but the compiler should be aware of the mapping and generate fields of the right type.

**Comment by sav007** [comment]
@martijnwalraven @digitalbuddha @felipecsl @marwanad so what is gonna be how user will define the mapping between GraphqQL custom types to java classes? should it be in gradle as config option for plugin or some file like meta or smth?
