### ISSUE TITLE
Please Release 📦

### ISSUE THREAD

**Issue by zetaron** [apollographql/apollo-android#883]
Hi I'd like to request a Release as we are in need of the connection parameters, which got introduced in #865.
Our Server uses [apollographql/subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) and the `connectionParams` as a way to send the `Authorization` Header in a WebSockety way.
Without it we are currently unable to authenticate our WebSocket connections.

Thanks for the hard work on this Library, I really appreciate it! 👍

**Comment by sav007** [comment]
Via https://github.com/apollographql/apollo-android/pull/884

**Comment by zetaron** [comment]
Many thanks for the quick action!
