### ISSUE TITLE
Enum within list of similar name causes build error

### ISSUE THREAD

**Issue by sp00ne** [apollographql/apollo-android#885]
# Issue
Having an enum of the same type as the parent struct causes an import clash.
The generated code and query* follows
```
@Generated("Apollo GraphQL")

...

    public static final class Mapper implements ResponseFieldMapper<Data> {
      @Override
      public Data map(ResponseReader reader) {
        final List<CarType> carTypes = reader.readList($responseFields[0], new ResponseReader.ListReader<CarType>() {
          @Override
          public CarType read(ResponseReader.ListItemReader listItemReader) {
            return CarType.safeValueOf(listItemReader.readString());
          }
        });
        return new Data(carTypes);
      }
    }
  }

  public static class CarType {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("carType", "carType", null, false, Collections.<ResponseField.Condition>emptyList())
    };

  ...

  }
}
```

```
query CarTypeQuery {
	carTypes {
		carType
                 ...
	}
}
```
Will generate error: `Cannot resolve method .safeValueOf(java.lang.String)`. 
*The dots indicate non-interesting parts. 

The problem lies in that `carTypes` is a list and will generate a type: `CarType` located in the same class. `carType` is an enum of type `CarType` (unfortunately). This causes a shadowing scenario in the generated code where it rather references `CarTypeQuery.CarType` -> `CarType` than the `CarType` generated in the `type`-subpackage.

This affects iOS also so I presume it is an apollo codegen related issue.

/label Type: Bug

**Comment by sav007** [comment]
As a work around you can use aliases for requested `carTypes `

**Comment by sp00ne** [comment]
Yup, discovered that feature :)

**Comment by digitalbuddha** [comment]
Closing since a workaround exists, kindly open an issue with Apollo-CodeGen if a better solution is needed.
