### ISSUE TITLE
ApolloParseException: Failed to parse http response even for 0.4.4 and newest 0.5.0 version

### ISSUE THREAD

**Issue by ParaskP7** [apollographql/apollo-android#886]
Linked issue: #767 

Hi guys, I am getting the same error as the closed issue above, but with `0.4.4` and `0.5.0` this time. Are we sure that all cases were fixed?

```
query Feed() {
  feed() {
    __typename
    elements {
      __typename
      aaa {
        ...FragmentA
      }
    }
  }
}

fragment FragmentA on AAA {
  __typename
  bbb {
    ...FragmentB
  }
}

fragment FragmentB on BBB {
  __typename
  ... on One {
   __typename
   id
  }
}
```

`BBB` has two types, `One` and `Two`. If `Two` is not specified then I get the:

```
ApolloParseException: Failed to parse http response

Caused by: java.lang.NullPointerException: FragmentB == null
        at com.apollographql.apollo.api.internal.Utils.checkNotNull(Utils.java:27)
```

`bbb` is actually a nullable type in the schema.

PS: It works on `0.4.2`, but doesn't on `0.4.3`, `0.4.4` and `0.5.0`.

**Comment by sav007** [comment]
Is the any way to see the part of your schema for `BBB`. Plus could you please send generated class for `FragmentA ` and `FragmentB ` you have.
