### ISSUE TITLE
Can't resolve query file in an flavours based Android app

### ISSUE THREAD

**Issue by amendezcabrera** [apollographql/apollo-android#887]
I followed the steps to add the required dependencies to my Android project.
* Added `classpath 'com.apollographql.apollo:apollo-gradle-plugin:0.5.0'` to my project gradle file
* Added `compile 'com.apollographql.apollo:apollo-runtime:0.5.0'` and `compile "com.apollographql.apollo:apollo-android-support:0.5.0"` to my app module gradle file
* Then I created the `graphql` folder in my `main` flavour folder with the generated `schema.json` file and one `.graphql` file with one GraphQL query
After building the project I can see the `Query` class in the generated `apollo` folder but I can't reference it in my code. The generated file isn't in a package, it hangs right at the `build->generated->source->apollo` folder

Can I use the Apollo Client library in a flavours based app? How could I solve this issue? 
Thank you very much

**Comment by sp00ne** [comment]
Hi there and welcome!

In your project gradle file, have you included:
```
apollo {
    outputPackageName = "[ Here you can set whatever you'd like, I wrote my applicationId.api]"
}
```

**Comment by amendezcabrera** [comment]
Thanj you very much for your help dude!! That worked!!
