### ISSUE TITLE
Cannot set the value of read-only property 'schemaFilePath' for task ':generateDebugApolloIR'

### ISSUE THREAD

**Issue by fluxxion82** [apollographql/apollo-android#888]
I'm getting the following error when I try to build my project:
"Cannot set the value of read-only property 'schemaFilePath' for task ':myModule:generateDebugApolloIR' of type com.apollographql.apollo.gradle.ApolloIRGenTask."

I'm using the latest version of apollo (0.5.0), updated my local npm, double checked my queries, reran apollo-codegen but not making any progress. Any ideas?

**Comment by sav007** [comment]
Just checked on my  sample app, can't reproduce. What version of gradle, android gradle plugin are you using?

**Comment by fluxxion82** [comment]
I using gradle 4.4, and I just upgrade to gradle plugin 3.1.2 today from 3.1.1. It's failing when I execute `./gradlew :myModule:assembleRelease` from the command line.

**Comment by digitalbuddha** [comment]
Sorry nothing jumps out.  Closing issue for now, If you can post a sample project that is not working we can take a look at what is happening
