### ISSUE TITLE
How to pass JSON paramter in mutation query in android ? When i pass error FATAL EXCEPTION: Apollo Dispatcher and JSON to: class java.lang.Object. Did you forget to add custom type adapter?

### ISSUE THREAD

**Issue by Ali-zain-javed** [apollographql/apollo-android#890]
mutation new_mutation($email:JSON!,$password:JSON!)
{
  Account
  {
    AccountLogin(input:{credentials:{email:$email,password:$password}})
    {
      obj
    }
  }
}

and this is function:

private void mutation()
    {
        try {
            JSONObject jsonBody1 = new JSONObject();
            JSONObject jsonBody2 = new JSONObject();
            jsonBody1.put("email", "orient@blueeast.com");
            jsonBody2.put("password", "Ori@1");
            Myapolloclient.getmyapolloclient().mutate(
                               New_mutationMutation.builder().email(jsonBody1).password(jsonBody2).build()).enqueue(new  ApolloCall.Callback<New_mutationMutation.Data>(){

                @Override
                public void onResponse(@Nonnull Response<New_mutationMutation.Data> dataResponse)   {

                    Log.d("response", dataResponse.data().Account().__typename());
                }

                @Override
                public void onFailure(@Nonnull ApolloException e) {

                }
            });
        } catch (Throwable t) {
            Log.d("exception", t.toString());
        }
    }

**Comment by Ali-zain-javed** [comment]
@digitalbuddha @sav007 please sir review this ,thanks

**Comment by digitalbuddha** [comment]
Why would need to make json instead of passing strings?

**Comment by Ali-zain-javed** [comment]
Sir when i use this same error occur
mutation new_mutation($email:JSON!,$password:JSON!)
{
  Account
  {
    AccountLogin(input:{credentials:{email:$email,password:$password}})
    {
      obj
    }
  }
}


//////////////////////////////////////////////////calll

            Myapolloclient.getmyapolloclient().mutate(
                    New_mutationMutation.builder().email("orient@blueeast.com").password("Orient@123").build()).enqueue(new ApolloCall.Callback<New_mutationMutation.Data>(){

                @Override
                public void onResponse(@Nonnull Response<New_mutationMutation.Data> dataResponse) {

                    Log.d("response", dataResponse.data().Account().__typename());
                }

                @Override
                public void onFailure(@Nonnull ApolloException e) {

                }
            });
        } catch (Throwable t) {
            Log.d("exception", t.toString());
        }

**Comment by Ali-zain-javed** [comment]
04-19 11:52:36.469 13430-13451/com.sourcey.materialloginexample E/AndroidRuntime: FATAL EXCEPTION: Apollo Dispatcher
    Process: com.sourcey.materialloginexample, PID: 13430
    java.lang.IllegalArgumentException: Can't map GraphQL type: JSON to: class java.lang.Object. Did you forget to add custom type adapter?
        at com.apollographql.apollo.response.ScalarTypeAdapters.adapterFor(ScalarTypeAdapters.java:30)
        at com.apollographql.apollo.internal.json.InputFieldJsonWriter.writeCustom(InputFieldJsonWriter.java:72)
        at com.example.alizain.new_apollo_example.New_mutationMutation$Variables$1.marshal(New_mutationMutation.java:149)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor.httpRequestBody(ApolloServerInterceptor.java:147)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor.httpCall(ApolloServerInterceptor.java:112)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1.run(ApolloServerInterceptor.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by Ali-zain-javed** [comment]
Sir server side accept object but from there data passing through string ,so error is creating

**Comment by sav007** [comment]
You should pass `email` argument as a  `String` or create a separate GraphQL type for it.

**Comment by sav007** [comment]
With this PR you can now pass JSON as argument: https://github.com/apollographql/apollo-android/pull/897
