### ISSUE TITLE
Incorrect Type Conversion for Lists with Shared-model type

### ISSUE THREAD

**Issue by cavega** [apollographql/apollo-android#898]
We have a subquery _photos_ where 2 fields (or subqueries) called _published_ and _archived_ that share the same properties or subqueries:

```
photos {
    published {
        id
       thumbnail
       etc....
    }

    archived {
        id
        thumbnail
        etc....
    }
}
```

The _schema.json_ generated by Apollo Codegen is shown below.  As you can see, both _published_ and _archived_ are objects of type **LIST** with items of type **VenuePhoto**:

```
[
{
          "kind": "OBJECT",
          "name": "Photos",
          "description": "",
          "fields": [       
            {
              "name": "published",
              "description": "the published photos",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "VenuePhoto",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": null
            },
            {
              "name": "archived",
              "description": "the archived photos",
              "args": [],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "VenuePhoto",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": null
            }            
          ]
        },
{
          "kind": "OBJECT",
          "name": "VenuePhoto",
          "description": "",
          "fields": [
            {
              "name": "id",
              "description": "the unique ID of this photo",
              "args": [],
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": null
            },
            {
              "name": "thumbnail",
              "description": "a thumbnail image for this photo",
              "args": [
                {
                  "name": "treatment",
                  "description": "",
                  "type": {
                    "kind": "SCALAR",
                    "name": "String",
                    "ofType": null
                  },
                  "defaultValue": null
                }
              ],
              "type": {
                "kind": "OBJECT",
                "name": "Image",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": null
            },
            {
              "name": "fullSize",
              "description": "a full-size image for this photo",
              "args": [
                {
                  "name": "treatment",
                  "description": "",
                  "type": {
                    "kind": "SCALAR",
                    "name": "String",
                    "ofType": null
                  },
                  "defaultValue": null
                }
              ],
              "type": {
                "kind": "OBJECT",
                "name": "Image",
                "ofType": null
              },
              "isDeprecated": false,
              "deprecationReason": null
            }                   
          ]
        }
]
```

The current issue we are facing with Apollo Android is that the generated models are of the following type;

```
List<Archived> archived;
List<Published> published;
```

where we are expecting the following:

```
List<VenuePhoto> archived;
List<VenuePhoto> published;
```

A failed attempt to coerce the tool to generate the right models was to extra everything inside `photos{}` as a fragment but that did not change the results.

I would appreciate some feedback as to whether the current behavior and model output is either a bug or if it is working as intended and there is a missing feature or flag that I need to incorporate in my `*.graphql` file to achieve the desired results.

**Comment by sav007** [comment]
If you want them to share the same model you have to use fragment:
```
photos {
    published {
       ...VenuePhotoFragment
    }

    archived {
        ...VenuePhotoFragment
    }
}

fragment VenuePhotoFragment on VenuePhoto {
   id
   thumbnail
   etc....
}
```
It will generate `Archived.Fragments` and `Published.Fragments` classes that have the same reference to `VenuePhotoFragment`. Yes it still generates 2 different models for `Archived` and `Published` because the set of requested fields might be different as well as arguments for requested fields. 

At the same time I agree that we should recognize identical sub-queries and have generated only one model class instead of 2 identical ones.

**Comment by cavega** [comment]
@sav007 That's exactly what I ended up doing but, again, because it is still 2 different models my RecyclerView code looks kinda ugly. I will proceed with the suggestion for the time being. However, is there any chance that a future version of Apollo-Android could enhance/fix this so that a single model class is used? Thanks for the feedback.

**Comment by sav007** [comment]
We encourage you to use ViewModels for UI, that layer of abstraction will give you flexibility and resolve such issues, as in many cases generated models don't satisfies UI needs and  requires to have additional fields or different types to present on UI

**Comment by cavega** [comment]
That's true but there really shouldn't be a reason for the generated code to break the contract defined in the schema.json file (i.e. the 2 lists use the same data type). Thanks for the feedback.  I'll revisit my solution.

**Comment by digitalbuddha** [comment]
Closing for now. Let us know if any recommendations of how to make experience better.
