### ISSUE TITLE
Cannot parse *.graphql with any comments in it

### ISSUE THREAD

**Issue by josephyanks** [apollographql/apollo-android#914]
If I try to run generateDebugApolloIR when I have a graphql file that is fully commented such as this:

```
# fragment TestFragment on TestData {
#        id
#        type
# }
```

I receive the error: `Syntax Error: Unexpected <EOF>`

I also cannot run the generation command on the following either (I get the same failure):

```
fragment TestFragment on TestData {
#        id
       type
}
```

It would be nice to have the ability to keep the commented graphql files in the codebase without needing to remove them entirely. It also makes sense to be able to add comments in these files.

**Comment by sav007** [comment]
Pls try the latest 1.1.0 version.
