### ISSUE TITLE
Access object "implementation" with Apollo 0.5 version

### ISSUE THREAD

**Issue by mariolourobert** [apollographql/apollo-android#919]
Hi !
I try to update Apollo from 0.4.2 to 0.5.0 but I can't access an object "implementation". For example, the schema provide a "User" class with two implementation, X and Y. In apollo 0.4.2 (my previous version), I was able to access an object implementation with : t?.data()?.user?.asX...
But there isn't "asX" object in my new generated user class...
Is it an issue ?

**Comment by RobinYoopies** [comment]
Same problem for me.

**Comment by sav007** [comment]
With release https://github.com/apollographql/apollo-android/releases/tag/0.4.3 we changed how inline fragments been generated via https://github.com/apollographql/apollo-android/pull/735
