### ISSUE TITLE
Add Apollo Link Functionality

### ISSUE THREAD

**Issue by christopherperry** [apollographql/apollo-android#931]
I'm looking to have Apollo as a single source of truth for data and data management in an Android app, as promised here: 

https://dev-blog.apollodata.com/the-future-of-state-management-dd410864cae2

My particular use case is I have a legacy Android app that is slowly being migrated to GraphQL. We are using apollo-android but currently bypassing the caching it provides because we have a legacy cache via GreenDAO. We also have tons of REST calls which won't be migrated any time soon. We don't want to maintain two different caches, we would like a single cache, and a single way to obtain data in the app.

Here is what we would like:

![screen shot 2018-05-30 at 5 55 04 pm](https://user-images.githubusercontent.com/1331096/40755594-d95ed71e-6433-11e8-80a5-3e3f8ac35f7b.png)

Replace the UI box with the relevant JVM/Android bits.

**Comment by wtrocki** [comment]
@christopherperry I believe that this can be done currently using Android CLient modular architecture. Cache is just yet another netowork interceptor that depending on strategy you will pick it will save the data. Default one is using SqlLite and works with queries only. It's possible to switch over to anything else like GreenDAO etc.

**Comment by sav007** [comment]
i think we can close this old issue, as there is no much benefit of introducing such complex logic, usually on android desired behaviour can be covered with proper clean arch.
