### ISSUE TITLE
Create "Getting Started" Page

### ISSUE THREAD

**Issue by adavis** [apollographql/apollo-android#942]
This page will resemble the layout of the related **React** Page, found [here](https://www.apollographql.com/docs/react/essentials/get-started.html).

It will include:
- Installation
- Downloading a Schema
- Creating a Client
- Creating a .graphql File
- Code Generation
- Consuming Code

**Comment by martinbonnin** [comment]
I tried to do that in https://github.com/apollographql/apollo-android/pull/1768 (link to the README file: https://github.com/apollographql/apollo-android/blob/bb542004b2f25247832e3edf4c2d774bebffece3/README.md).

**Comment by tasomaniac** [comment]
I'm closing this since we have the getting started page already and with the new updates on docs, it is quite decent.
