### ISSUE TITLE
Error: too many parameters

### ISSUE THREAD

**Issue by dima-ostapovets** [apollographql/apollo-android#947]
Hello.
I'm trying to generate query with input that has more than 300 parameters.
I know it's not the best data structure, but...
Is there any workaround for this limitation?

Apollo version : 0.5.0
schema snippet:

`{
  "kind": "INPUT_OBJECT",
  "name": "ClubFilter",
  "description": "Input describing all the fields you can filter Club with.",
  "fields": null,
  "inputFields": [
    {
      "name": "slug",
      "description": "",
      "type": {
        "kind": "SCALAR",
        "name": "String",
        "ofType": null
      },
      "defaultValue": null
    },
    {
      "name": "slug_not",
      "description": "All values that are not equal to the given value.",
      "type": {
        "kind": "SCALAR",
        "name": "String",
        "ofType": null
      },
      "defaultValue": null
    }
  ]
}`

Generated constructor snippet:
`ClubFilter(Input<String> slug, Input<String> slug_not, Input<String> slug_contains,...`

Actual result:
error: too many parameters

**Comment by gefilte** [comment]
I am seeing this same error.

Compiler error:
```/Users/dpisoni/sandbox/gitapps/gp-android/QBPayments/build/generated/source/apollo/com/intuit/qbpayments/network/model/v4/type/Company_Definitions_Models_qbfInput.java:730: error: too many parameters
  Company_Definitions_Models_qbfInput(Input<String> amtNewLiab3Mos,
```

The generated code (a constructor) has 144 parameters.

(Sorry, I didn't _write_ this schema, I'm just trying to consume it.)

**Comment by sav007** [comment]
@gefilte could you please send me over generated files for this. According to https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.11 the limit is 255 so 144 parameters should be ok.

@dima-ostapovets is there any way you can change the your schema as seems 300 over the limit for constructors

**Comment by sav007** [comment]
And just curious what is the service that provides you input object with > 100 arguments, it seem to me bad designed schema

**Comment by gefilte** [comment]
Sorry, my mistake. It's 288 parameters. (Was 144 lines, but 2 parameters/line.)

And I would agree WRT schema design, but alas, these are the cards I've been dealt.

**Comment by digitalbuddha** [comment]
Is it possible for you to split into multiple queries?

**Comment by gefilte** [comment]
It's a mutation, so I think not. I have a query that uses the same fragment and it works fine, doesn't generate anything this crazy.

**Comment by dima-ostapovets** [comment]
I requested new schema, hope it will be fixed on backend side, grouping params seems to be a solutions

**Comment by gefilte** [comment]
The thing is my mutation doesn't even need this bit of the schema, but for whatever reason if I include this mutation then the code generation bit fills up the "type" package with a ton of classes that _aren't_ included if I only have a query. I suppose this may be by design, but it still seems like it's generating far more than I use.

**Comment by sav007** [comment]
The issue is that with query you specify the exact set of fields you need, but for mutations that accepts input object there is no way to provide such set, we don't know what fields you will use in input object type, that's why we need to include them all. But tbh this is an issue on server side schema design.

**Comment by gefilte** [comment]
Agreed, schema is vastly over-complex. It still might be beneficial however to put some guard code in the code generator to prevent this outcome.

**Comment by digitalbuddha** [comment]
We will discuss and figure how to handle. No easy solution exists.

**Comment by Yanivox** [comment]
is there any change about this?

**Comment by sav007** [comment]
Sorry but there is not much we can do on our end as it's limitation of Java https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.11

The only option is change GraphQL schema.
