### ISSUE TITLE
Generated code with field "type" conflicts with "type.CustomType" during compilation phase

### ISSUE THREAD

**Issue by gefilte** [apollographql/apollo-android#949]
This error occurs in `compileDebugJavaWithJavac` phase – after Apollo code generation. Here is a sample of failing generated code:

```
@Generated("Apollo GraphQL")
public final class Schema_SchemaInput {
...
  private final Input<String> type;
...
  public InputFieldMarshaller marshaller() {
    return new InputFieldMarshaller() {
      @Override
      public void marshal(InputFieldWriter writer) throws IOException {
...
        if (multipleOf.defined) {
          writer.writeCustom("multipleOf", type.CustomType.BIGDECIMAL, multipleOf.value != null ? multipleOf.value : null);
        }
```

And the compiler error:
```
/Users/dpisoni/sandbox/gitapps/gp-android/QBPayments/build/generated/source/apollo/type/Schema_SchemaInput.java:677: error: cannot find symbol
          writer.writeCustom("multipleOf", type.CustomType.BIGDECIMAL, multipleOf.value != null ? multipleOf.value : null);
                                               ^
  symbol:   variable CustomType
  location: variable type of type Input<String>
```

It seems strange that no one else has encountered this yet, as "type" seems like a pretty common field name to have in schema.

Naturally, this is a blocking issue since it results in a compilation failure.

Gradle: **4.4**
Grandle Android Plugin: **3.1.2**
Android SDK: **27**
apollo-android: **0.5.1-SNAPSHOT**

*N.B., I am using SNAPSHOT because I need the benefits of an unreleased bug fix. Using 0.5.0 my schema fails to compile because there is a field contained within called "class", a Java reserved keyword.*

**Comment by sav007** [comment]
You should put the graphql files under some package structure

**Comment by gefilte** [comment]
My graphql files are in a package structure, about 7 levels deep! The code generator however generates the "type" directory flat.

**Comment by sav007** [comment]
what about the schema file?

**Comment by gefilte** [comment]
Ah, so I was not aware moving that around had any effect. Not obvious from the documentation, though I see the sample app does this. I will try this now...

That worked! Or at least, compilation isn't failing for _this_ reason any more. (It now appears I've bumped into [#949)](https://github.com/apollographql/apollo-android/issues/949)

Thank you!
