### ISSUE TITLE
ApolloCodeGenInstallTaskSpec test failure

### ISSUE THREAD

**Issue by KingDavid91** [apollographql/apollo-android#952]
When executing `gradle check` it appears that there's a failed test in the test class `ApolloCodeGenInstallTaskSpec`. After further investigation of the issue, it looks like the assertion on line 51 (i.e. ```assert packageFile.isFile()```) fails due to the failed execution of the of the task `ApolloCodegenInstallTask` (which I assume from looking at the source code is supposed to generate this `package.json` specified for the test)

I've labeled this as `blocking` due to the fact that from the `contributing.md` it is a requirement to execute `gradle check` when attempting to open a PR

**Comment by sav007** [comment]
This PR https://github.com/apollographql/apollo-android/pull/979 should fix this issue, closing
