### ISSUE TITLE
Creating 'Mutations' page

### ISSUE THREAD

**Issue by GurpreetSK95** [apollographql/apollo-android#954]
This page will serve as an introduction to what a mutation on GraphQL is and how to write data successfully to the server using apollo-android. The layout will resemble the layout for [react](https://www.apollographql.com/docs/react/essentials/mutations.html) page.

- [x] docs

**Comment by martinbonnin** [comment]
The page is available there: https://www.apollographql.com/docs/android/essentials/mutations/
