### ISSUE TITLE
Error: bad format using List<List<Date>>

### ISSUE THREAD

**Issue by CrisCR** [apollographql/apollo-android#956]
I currently have a problem with one of my input, from a mutation, which is a list of list of `Date`.
the input is:
```
timeSlots = {Input@9840}
value = {ArrayList@9843}  size = 2
 0 = {ArrayList@9848}  size = 2
  0 = {Date@9857} "Thu Sep 20 13:00:00 GMT+02:00 2018"
  1 = {Date@9858} "Thu Sep 20 19:00:00 GMT+02:00 2018"
 1 = {ArrayList@9849}  size = 2
  0 = {Date@9863} "Sun Sep 23 08:00:00 GMT+02:00 2018"
  1 = {Date@9864} "Mon Sep 24 00:00:00 GMT+02:00 2018"
```

but the output is:

```"timeSlots":["2018-09-20T11:00:00.000Z","2018-09-20T17:00:00.000Z","2018-09-23T06:00:00.000Z","2018-09-23T22:00:00.000Z"]```

something is wrong with the output format which is a simple list of `Date`.

Gradle conf:

```
classpath 'com.apollographql.apollo:apollo-gradle-plugin:0.5.1-SNAPSHOT'
implementation 'com.apollographql.apollo:apollo-runtime:0.5.1-SNAPSHOT'
```

Apollo codegen version: 0.19.1

**Comment by digitalbuddha** [comment]
Might be related to https://github.com/apollographql/apollo-android/pull/938 @sav007 could you kindly take a look when you have a chance. Thanks!
