### ISSUE TITLE
Mutation sending null parameters

### ISSUE THREAD

**Issue by SefronZ** [apollographql/apollo-android#965]
I'm trying to integrate Apollo-Android with a server mounted locally, the query to show all of the entries is working fine, but when I try to create a new entry, it sends a query without the parameters.

At first I thought it was a server-side problem, but it doesn't seems like it, since it's creating the entry but with null values.

The server it's made on Spring Boot using SPQR for the schema generation, and SpringData-JPA with Hibernate for the connection to a PostGreSQL database.

This is what the server says:
<blockquote>
Hibernate: insert into author (first_name, last_name) values (?, ?)<br>
2018-06-25 14:48:25.479  INFO 6670 --- [nio-8080-exec-3] s.testing.controllers.GraphQLController  : {data={createAuthor={__typename=Author, firstName=null, lastName=null}}}
</blockquote>

And this is the response I get on Android Studio:
<blockquote>
06-25 14:48:24.974 16068-16132/com.example.nburk.apollodemo D/graphcool: Executed mutation: CreateAuthor{__typename=Author, firstName=null, lastName=null}
</blockquote>

On Android Studio this is the builder:
<blockquote><pre>
private void createPost(String firstname, String lastname) {
        application.apolloClient().mutate(
                CreateAuthorMutation.builder()
                        .firstName(firstname)
                        .lastName(lastname)
                        .build())
                .enqueue(createPostMutationCallback);
    }
</pre></blockquote>

That enqueue this:

<blockquote><pre>
private ApolloCall.Callback<CreateAuthorMutation.Data> createPostMutationCallback = new ApolloCall.Callback<CreateAuthorMutation.Data>() {
        @Override
        public void onResponse(@Nonnull final Response<CreateAuthorMutation.Data> dataResponse) {
            Log.d(ApolloDemoApplication.TAG, "Executed mutation: " + dataResponse.data().createAuthor().toString());
            fetchPosts();
        }
        @Override
        public void onFailure(@Nonnull ApolloException e) {
            Log.d(ApolloDemoApplication.TAG, "Error:" + e.toString());
        }
    };
</pre></blockquote>

If you need it, here is my mutation:
<blockquote><pre>
mutation CreateAuthor($firstName: String, $lastName: String){
    createAuthor(firstName: $firstName, lastName: $lastName){
        firstName
        lastName
    }
}
</pre></blockquote>

This project is based on this: https://github.com/graphcool-examples/android-graphql/tree/master/quickstart-with-apollo

Uploading my schema too.

[Copia de schema.txt](https://github.com/apollographql/apollo-android/files/2134365/Copia.de.schema.txt)

Thanks beforehand for your help.

**Comment by sav007** [comment]
`firstName / lastName ` are nullable? If so then check the generated overloaded methods `firstNameInput() / lastNameInput()`. With this methods you need pass a wrapped values with `com.apollographql.apollo.api.Input` that provides fine control how to deal with null values:

```
/**
   * Creates a new {@link Input} instance that is defined in case if {@code value} is not-null and undefined otherwise.
   *
   * @param value to be wrapped
   * @return a new {@link Input} instance
   */
  public static <V> Input<V> optional(@Nullable V value)

/**
   * Creates a new {@link Input} instance that is always defined.
   *
   * @param value to be wrapped
   * @return a new {@link Input} instance
   */
  public static <V> Input<V> fromNullable(@Nullable V value)

/**
   * Creates a new {@link Input} instance that is always undefined.
   *
   * @param value to be wrapped
   * @return a new {@link Input} instance
   */
  public static <V> Input<V> absent()
```

So if you don't want to send nulls then you need to use `com.apollographql.apollo.api.Input#optional`

**Comment by SefronZ** [comment]
Just changed them to make them non-nullable, and this is what I got:

Server:
<blockquote><pre>
s.testing.controllers.GraphQLController  : {errors=[{message=Variable 'firstName' has coerced Null value for NonNull type 'String!', locations=[{line=1, column=23}]}]}
</pre></blockquote>

And in Android Studio:
<blockquote><pre>
06-25 16:56:41.596 30403-30439/com.example.nburk.apollodemo E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.example.nburk.apollodemo, PID: 30403
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.CreateAuthorMutation$CreateAuthor com.CreateAuthorMutation$Data.createAuthor()' on a null object reference
        at com.example.nburk.apollodemo.MainActivity$1.onResponse(MainActivity.java:64)
        at com.apollographql.apollo.internal.RealApolloCall$1.onResponse(RealApolloCall.java:224)
        at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor$1$1.onResponse(ApolloCacheInterceptor.java:85)
        at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:54)
        at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:94)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
</pre></blockquote>

It's weird because the builder is taking the data, but it doesn't reach the callback

![captura de pantalla 2018-06-25 a la s 17 05 22](https://user-images.githubusercontent.com/29349671/41875821-0b5cdf84-789a-11e8-8505-02bf0a4a2bd0.png)

**Comment by sav007** [comment]
Sorry I confused, are you passing for non nullable types `firstName / lastName` null value? You can't do it, that is why you getting an graphql validation error from server `{errors=[{message=Variable 'firstName' has coerced Null value for NonNull type 'String!', locations=[{line=1, column=23}]}]}`.

By looking into your stacktrace it reaches your callback, except the fact that `com.apollographql.apollo.api.Response#data` is null, and you have `com.apollographql.apollo.api.Response#errors` non empty (you should always check `com.apollographql.apollo.api.Response#hasErrors` to be safe that there is no any graphql errors returned from the server first)

**Comment by SefronZ** [comment]
As you can see in the debbuger, I'm sending "Testing" and "Android", so there shouldn't be any null values:

![captura de pantalla 2018-06-26 a la s 10 19 03](https://user-images.githubusercontent.com/29349671/41918540-925cd01c-792a-11e8-806e-15e35874c552.png)

And the builder is receiving the data:

![captura de pantalla 2018-06-26 a la s 10 18 44](https://user-images.githubusercontent.com/29349671/41918581-a7e1c3c0-792a-11e8-8618-f1ae35a5f19d.png)

**Comment by sav007** [comment]
Could you please add log interceptors to okHtppClient and see the actual request sent to the server?

```
.addNetworkInterceptor(new HttpLoggingInterceptor().setLevel(BODY))
```

**Comment by SefronZ** [comment]
This is what I got from the interceptor:

![captura de pantalla 2018-06-27 a la s 09 00 35](https://user-images.githubusercontent.com/29349671/41975435-ade28f2a-79e8-11e8-9b61-1d37d3fb80d3.png)

**Comment by sav007** [comment]
What you showed is a response logs, but I was more interesting request logs, to make sure that Apollo client sends non null values.

**Comment by SefronZ** [comment]
The second image has the request, it's sending the data, but Hibernate says that the statement isn't valid.

PS: The id is defined as autoincremental in the database, and I'm using the GeneratedValue annotation from Hibernate for that: 
<blockquote><pre>
@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;
</pre></blockquote>

**Comment by SefronZ** [comment]
For some reason, the mutation is sending the __typename as a parameter:

![captura de pantalla 2018-06-27 a la s 12 09 05](https://user-images.githubusercontent.com/29349671/41986062-0e26416e-7a03-11e8-82bf-53a34ccbce63.png)

Is there any way to avoid that? I want to try without that parameter, because when making mutations using GraphiQL, it sends an exception if you add that parameter.

**Comment by SefronZ** [comment]
A friend found the problem, when he defined the schema manually (without SPQR), and declared the id as an ID type, it worked.

Conclusion: The problem is with SPQR, because it doesn't define the id as an ID when it generates the schema.

I'll try to make SPQR work, since it helps a lot.

**Comment by SefronZ** [comment]
Found the problem, it's from SPQR side, so if anyone wants to implement it:

First you need to add the "@GraphQLId" at the getter (serverside):

![captura de pantalla 2018-06-28 a la s 15 25 08](https://user-images.githubusercontent.com/29349671/42056175-7a3bfb16-7ae7-11e8-9d16-030acd76e6ae.png)

Then, you need to add a mapper for the variables (serverside, at the controller that generates the schema): 

![captura de pantalla 2018-06-28 a la s 15 27 04](https://user-images.githubusercontent.com/29349671/42056274-cd6a3352-7ae7-11e8-92d4-c87d34cff7c9.png)

This isn't said at the example of SPQR, so it could help more people.
