### ISSUE TITLE
Too many different classes with the same fields

### ISSUE THREAD

**Issue by darkeneez** [apollographql/apollo-android#978]
Hello guys!

I use Apollo Graphql in android project and have one problem...When i create query or mutation, Apollo generates a lot of classes with same fields. Some of them are completely identical. 
Can I merge them into one? 

Sorry for my bad English :(

**Comment by digitalbuddha** [comment]
Take a look at the concept of graphql fragments.   Say you have a query and a mutation that both have the fields: name/age/size you can make a Fragment out of those fields and share them with many queries/mutations. Apollo will only generate each fragment once

**Comment by darkeneez** [comment]
Awesome! It's work. Thank u!
