### ISSUE TITLE
Fields are incorrectly nullable in 1.0.0-alpha

### ISSUE THREAD

**Issue by scottkennedy** [apollographql/apollo-android#982]
I'm not sure what's changed to cause this, but I have a few generated fields that were formerly correctly annotated `@NotNull` that are now being annotated `@Nullable` in 1.0.0-alpha.

As far as I can tell, they're all declared as `Type!`, which should result in `@NotNull`.

I can't upload the whole schema here, but I'm happy to do whatever debugging I can to help fix this.

**Comment by sav007** [comment]
Can you please provide more info like example of the query you have?

**Comment by Chris-Thoma-CK** [comment]
type MerchandisedCardsV2 implements IClientVisualElement {
    impressionEvent: ImpressionEvent

    entries: [MerchandisedCardEntryType]!
}

This list is being generated as nullable

**Comment by scottkennedy** [comment]
Looks like it was actually a bug in 0.5.0, and it's fine now.
