### ISSUE TITLE
Question/Problem about Inline Fragments as polymorphic type

### ISSUE THREAD

**Issue by RobinMaronierY** [apollographql/apollo-android#984]
I have a problem. I'm doing the migration of my Apollo Client to the 1.0.0-alpha version (from 0.4.2).
I have a lot of thing to migrate. I almost finished and I found something I can't explain.
About the new : **Inline fragments as polymorphic type**

My query generate 3 types of object with same properties :
<img width="134" alt="image" src="https://user-images.githubusercontent.com/37659037/42511729-fb520a96-8452-11e8-81da-6189bf5f1fde.png"><img width="335" alt="image" src="https://user-images.githubusercontent.com/37659037/42511713-eef5954c-8452-11e8-8f37-efc79048569a.png">

But in my code, the `AsApplicant` and `AsApplicant2` are empty. I can't understand why I have 3 objects like that.

I can give you the query, but it's a little bit big one to put in here.

Do you have an answer ?

**Comment by sav007** [comment]
Per our conversation offline, the code generated for your query is completely legit.
Here is some overview how code generation works for inline fragments. Inline fragments usually defined on some interface or union types, for example we have this query:
```
hero {
    name
    ... on Human {
      height
    }
    ... on Droid {
      primaryFunction
    }
  }
```

`Hero` is defined as an interface (`Character` in schema) where `Human` and `Droid` are its subclasses. With this query all fields that are common for all subtypes (defined in the interface) will be merged with  fields defined in the subtypes, in our example  common field `name` will be available in both subtypes `Human.name` and `Droid.name`.  As a result there will be 2 classes generated: `AsHuman` and `AsDroid` implementing interface `Hero` with accessor methods for common fields (in our case `getName()`).
There will be another class generated `AsCharacter` (based on the name of interface defined in the schema) to cover the rest possible subtypes that weren't requested.

The things become more complicated when inline fragments request complex objects, for example:
```
hero {
  name
  friendsConnection {
    totalCount
  }
  ... on Human {
    friendsConnection {
      edges {
        node {
          name
        }
      }
    }
  }
  ... on Droid {
    name
    primaryFunction
  }
}
```
Here we have 2 different version of `friendsConnection` from set of requested fields perspective. The same logic as for the simple case all requested common fields will be merged into subtypes, means the version of `friendsConnection` defined in `... on Human` will get all `totalCount` requested in `hero`.

**Comment by RobinMaronierY** [comment]
I think I did it 👍 Just seems weird to have few same objects even if we don't query them inside inline fragment. Hope this could be improve later. But by now, I will fix it by using normal fragment 
Thx !
