### ISSUE TITLE
How to handle the big int when I can not change the schema.json or add a customtype?

### ISSUE THREAD

**Issue by NateRobinson** [apollographql/apollo-android#989]
Because the server only make a filed as Int ,but it actually return a big int , in java I cannot handle the big int correctly as a Integer type.
I can't change the schema.json or add a new customtype for handle it.

**Comment by sav007** [comment]
Right now theres is no way to override the default GraphQL scalars type mappings, only if it custom scalar type. But I think it's a feature nice to have.

**Comment by sav007** [comment]
Just to be clear that according to the spec  https://graphql.org/learn/schema/#scalar-types:
`Int: A signed 32‐bit integer.` means that your GraphQL schema violates the requirements for Int type.

**Comment by NateRobinson** [comment]
Thanks, I have show the spec to our backend engineer, the may add a custom type for big int firstly.
