### ISSUE TITLE
Could not find com.apollographql.apollo:apollo-gradle-plugin:1.0.0.

### ISSUE THREAD

**Issue by Gamezpedia** [apollographql/apollo-android#990]
Followed the readme **Adding Apollo to your Project**

**1 - project build.gradle**
![image](https://user-images.githubusercontent.com/1169093/42708198-fc714ffe-86f5-11e8-8f3a-d44a7376aa5f.png)

**2 - app module build.gradle**
![image](https://user-images.githubusercontent.com/1169093/42708257-32e4bb5c-86f6-11e8-9998-7b5095345cd2.png)

**After sync:**
 
![image](https://user-images.githubusercontent.com/1169093/42708348-7861aeec-86f6-11e8-917b-e4ae4c6a9d39.png)

**Raw**

```
Could not find com.apollographql.apollo:apollo-gradle-plugin:1.0.0.
Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/apollographql/apollo/apollo-gradle-plugin/1.0.0/apollo-gradle-plugin-1.0.0.pom
    https://dl.google.com/dl/android/maven2/com/apollographql/apollo/apollo-gradle-plugin/1.0.0/apollo-gradle-plugin-1.0.0.jar
    https://jcenter.bintray.com/com/apollographql/apollo/apollo-gradle-plugin/1.0.0/apollo-gradle-plugin-1.0.0.pom
    https://jcenter.bintray.com/com/apollographql/apollo/apollo-gradle-plugin/1.0.0/apollo-gradle-plugin-1.0.0.jar
Required by:
    project :

```

**Comment by digitalbuddha** [comment]
1.0.0 is not yet. Add alpha at the end of your dependency

**Comment by Gamezpedia** [comment]
thanks i just figured out :)
