### ISSUE TITLE
Unable to generate Java classes from schema.json 

### ISSUE THREAD

**Issue by Gamezpedia** [apollographql/apollo-android#992]
Hi,

after trying every thing i am asking it here :

after installing i tried to generate the files by compiling but i can't find them in the build folder.

what i have tried so far: 

first i tried with this and got the schema.json in a form that you can't read anything it's like uglyfied version of js.
`apollo schema:download --endpoint=http://localhost:8080/graphql schema.json`

then after looking here and there i found the pull request:
`Note that this requires exactly version `0.19.1` (not older, not newer). You can install this conventionall via `npm install -g apollo-codegen@0.19.1`.`

after that i can see schema in proper formatting.

but i still don't have any apollo folder in my project > build > generated folder.

Snapshot here:

![image](https://user-images.githubusercontent.com/1169093/42713899-8daadb66-870a-11e8-8921-b8a08fad4338.png)

**api.graphql contains :**

```
query testQuery{
  test
}

mutation register($email: String!, $password: String!, $name: String!, $role:String) {
  register(email: $email, password: $password, name: $name, role: $role) {
    result
  }
}

```

i added the mutation too to check - but nothing is getting generated in the build folder.

am i missing some thing ? or doing wrong ?

thanks

**Comment by Gamezpedia** [comment]
i wish there were proper documentation links of this cool project :) right after i posted this i was still searching for things and found this link : [](https://www.apollographql.com/docs/android/get-started)
and it clears the folder structure confusion. also https://www.apollographql.com/docs/ is targeting repo folder instead of that link.

**Comment by digitalbuddha** [comment]
We do have documentation https://www.apollographql.com/docs/android/get-started

**Comment by Gamezpedia** [comment]
sorry i forgot to add that exact link i was talking , but the link on main domain / docs/ is targeting to the repo not the get-started page :)
