### ISSUE TITLE
First letter in field name changed to lower case

### ISSUE THREAD

**Issue by brownm26** [apollographql/apollo-android#994]
If a field name starts with a capital letter then Apollo changes it to a lower case letter. This causes the query or mutation to fail. Changing the function and variable names is just fine, but the marshaller should use a non-modified field name.

**Comment by sav007** [comment]
Could you please provide example of the query and what was generated in `static final ResponseField[] $responseFields = { }` section.

Another question what version are you using?

**Comment by sav007** [comment]
Oh `InputFieldMarshaller `, yeah thx, will take a look at it ASAP
