### ISSUE TITLE
subscription need resubscribe after server close websocket connection

### ISSUE THREAD

**Issue by khejing** [apollographql/apollo-android#996]
For now, WebSocketListener class in WebSocketSubscriptionTransport.java, just notify upper level when on failure. When on closed, it just release, and notify nothing. So if the websocket server close the connection, client will lost the subscription forever, and don't know when to resubscribe. Please fix it, thanks!

**Comment by wtrocki** [comment]
Going to take look into this issue. Logged something similar here: https://github.com/apollographql/apollo-android/issues/1003

**Comment by khejing** [comment]
@wtrocki Your solution is to solve the problem when there are network exceptions, but I mean for such scenario: you subscribe a subscription, but the server engineer fix some bug or implement some new requirement, he has to restart the server in the deployment process. Because it's a restart, the server will first close the connection normally, and then start again. So there is no network exception. I thought apollo-android should send notification to upper level, but auto-reconnection is ok either. I have test the react-apollo implementation for this, it auto reconnects the server even the server closes the connection normally. If auto-reconnection is implemented, notification is unnecessary. I like your idea too.

**Comment by sav007** [comment]
@wtrocki @digitalbuddha @khejing there are 2 approaches I see how to address this issue:
1. is add additional callback to `com.apollographql.apollo.internal.subscription.SubscriptionManager.Callback` like `onClosed`
2. Create a special sub-class of `ApolloSubscriptionException` like `ApolloSubscriptionInterruptedException` that will indicate server closed connection without any notice (initiated by the sever without sending `complete` message).

Any thoughts?

**Comment by Dragons0458** [comment]
Hello! Is there any solution for this? Thank you!

**Comment by wtrocki** [comment]
I went with the path of having `onClosed()` method in callback. This however had some side effects on multiple subscriptions -  need to resubscribe manually on error.  Going this path did not resolved problem as it was just covering single subscription when problems are usually related with global subscription manager backed by websockets connection that is being closed.

I spent some time debugging this under various network conditons and found websockets having problems with slow mobile networks. Technically your device can be connected to internet, but websockets connections will still fail.

I found application level solution that were too specific to contribute upstream. In my case subscriptions  are used to refuel  local state ( ccache.I just wrote my own subscription manager that has all subscriptions on startup. This way I can avoid memory leaks and have one centralized place for holding state where I interact with my cache leayer.

What I love in Apollo is that their SDK architecture allows to swap implementations so if something is not working I can always override behaviour to code that makes sense for my use case.

**Comment by wtrocki** [comment]
Actually auto reconection could be good upstream solution for those problems. Problem with that aproach is to see when reconnection can happen and this is really hard to generalize. Relying on offline online state will not be enough as server can go down as well etc.

**Comment by khejing** [comment]
@Dragons0458 For now, I call subscriptionTransportFactory() to get websocket events. When websocket is closing, I call apolloClient.subscriptionManager.disconnect() by using reflection, and then dispose the subscription. After that, I resubscribe it again.

**Comment by wtrocki** [comment]
@khejing Really strange that this is needed as RealSubscriptionManager already does that:
https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/subscription/RealSubscriptionManager.java#L369

The only feature that is missing is reconnect.

**Comment by Dragons0458** [comment]
Why is reconnection difficult? I implemented an Apollo link in Nativescript, and my way of reconnecting was that when it closed it would send the connection message again until the server answered something, or does that generate a problem? for the moment I am using the solution that @khejing give me, but it seems to me that reconnection is necessary, thank you very much!

**Comment by adrian1388** [comment]
How can I use the onTerminated callback to get a reconnection?

I tried to clone the subscription as suggested in #1075, when onError method of DisposableSubscriber runs, but I am obviously doing something wrong.

```
public void disposablesAdd(ApolloSubscriptionCall<MySubscription.Data> subscriptionCall) {
    disposables.add(Rx2Apollo.from(subscriptionCall)
        .subscribeOn(Schedulers.io())
        .subscribeWith(
            new DisposableSubscriber<Response<MySubscription.Data>>() {
              @Override public void onNext(Response<MySubscription.Data> response) {
            	  logger.info("RESPONSE SUBS TIME: " + response.data());
              }

              @Override public void onError(Throwable e) {
            	  logger.info("Subscription failure: " + e);
            	  e.printStackTrace();
            	  if (e instanceof ApolloSubscriptionTerminatedException) {
            	     logger.info(subscription call CLONED: "+ subscriptionCall);
            	     disposablesAdd(subscriptionCall.clone());
            	  }
              }

              @Override public void onComplete() {
            	  logger.info("Subscription exhausted");
              }
            }
        )
    );
}
```
